### ISSUE TITLE
Race condition in mmap

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#100]
`pal-Linux-SGX` seems to hang from time to time, even on the `helloworld` example.

Reproduction steps:
----------------------
Run any SGX code using pal-Linux-SGX in a loop, e.g.:
```Bash
~/graphene/LibOS/shim/test/native$ while true; do ./pal_loader SGX helloworld; done
```
After ~40 tries it should hang with the following error on the stdout:
```
[P7548] Check vma flag failure: vma flags 22, checked flags 20000022
bug() bookkeep/shim_vma.c:258
[    1] ---- shim_open("/lib/tls/libc.so.6",O_RDONLY|2000000,1326420530) ...
[P7548] teminating the whole process
[P7548] deleting port 0xba8d0b0 (handle 0xbfadd80) for process 0
[    1] ---- return from shim_open(...) = -2
[P7548] deleting port 0xba8d038 (handle 0xbfada40) for process 0
[P7548] process 1070727548 successfully terminated
[    1] ---- shim_stat("/lib/tls",0xb9a2da6) = -2
[    1] ---- shim_open("/lib/libc.so.6",O_RDONLY|2000000,1326420530) ...
```

After pressing Ctrl+C for the first time two additional lines appear:
```
[    1] signal_logs[1]: head=0, tail=1
[    1] memory fault at 0x0 (IP = 0xbd87c79)
```

Further Ctrl+Cs don't do anything.
Full log: https://gist.github.com/mkow/c8295b1beb3ead7871de40bba5d22416

During the hang `pal-Linux-SGX` contains only one thread, which consumes 100% CPU. It seem to be hanged inside an enclave:
```gdb
gdb$ info threads
  Id   Target Id         Frame
* 1    Thread 0x7f3541725740 (LWP 380) "pal-Linux-SGX" 0x00005575b9fb04b0 in async_exit_pointer ()
```

There are some samples which seem to fail more often (e.g. `vfork`), but I haven't conducted enough experiments to be sure.

I think there are three separate issues here:
1. The vma flags assert triggers randomly.
2. Handling of the above fault hangs the process and makes it unkillable with Ctrl+C (but SIGKILL works).
3. Also, this looks like a bug in printing process id to logs: `process 1070727548`.

Config
-------
I built everything using the guide at https://github.com/oscarlab/graphene/wiki/SGX-Quick-Start.
Commit: 35d6b976ccd5411ddc37af080ea31c49e2c2e868
OS: Ubuntu 16.04
Unfortunately I don't have any other machine with SGX, so I can't say if this would be reproducible on any other config.

**Comment by mkow** [comment]
I did more tests, the probability of failure seems to be independent from the sample:

```
Number of fails:
  helloworld: 3/50
  vfork: 0/50
  malloc: 1/50
  helloworld.pthread: 2/50
  time: 4/50
```

**Comment by mkow** [comment]
`process_id` seems to be a mixed with start time. What's the purpose of this? Moreover, it's mixed only with higher bits of the time, so it still can collide (if that was the reason for mixing time into the id).
https://github.com/oscarlab/graphene/blob/64a57f2241483599eaa53c34e958472ee7d5037c/Pal/src/host/Linux-SGX/db_main.c#L165
https://github.com/oscarlab/graphene/blob/14b34f37acefdecc733e68ae87c80d9569713e08/Pal/src/host/Linux/db_main.c#L248
https://github.com/oscarlab/graphene/blob/c2c92723b9da232481882d5b4bd494b6663c79ee/Pal/src/host/FreeBSD/db_main.c#L181

In addition to this, it seems that the `process_id` is incorrectly printed to the log. I added a bit more debugging info and got this:
```
[DEBUG] linux_state.process_id = 1666135933
[P5933] set tcb to 0x7ffd6a50c958
```
Note that the id I printed is in decimal. This bug is caused by this line:
https://github.com/oscarlab/graphene/blob/2e9438f71c487c5a3ae2e7b3ca1c2d957dee6d3e/LibOS/shim/src/utils/printf.c#L140-L141
It should be `0x10000`, not `10000`.

**Comment by chiache** [comment]
I can confirm this bug after running 114 times.

**Comment by donporter** [comment]
Please let us know if PR #126 addresses this hang issue.

**Comment by penhoi** [comment]
This bug is always triggered:) Even for a helloworld program
 
bug() bookkeep/shim_vma.c:257

**Comment by mkow** [comment]
Important note: the bug seems to be still unfixed after merging #126, it just occurs very rarely now. More info in the discussion in https://github.com/oscarlab/graphene/pull/126/#issuecomment-357384018.

**Comment by donporter** [comment]
Do we believe #183 resolved this bug?

**Comment by donporter** [comment]
I just tried to repro this on current master.  I can run helloworld and time >150 times and see no hang.

Of course, this may be consistent with @mkow 's comment about happening "very rarely".  

I am going to close this issue until someone can help repro the issue/confirm it is still happening.  If @mkow is sitting on any other fixes that are related to this issue, I'd be much obliged to pull them in.  Thanks again for the report.
