### ISSUE TITLE
[Pal]bug report: ocall_sock_recv does not handle the result correctly

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#1001]
testcase:
start lighttpd: make start-graphene-server
run testcase: ./benchmark-http.sh 0.0.0.0:8000

error msg:
(connections.c.384) connection closed - read failed: Permission denied 13

In ocall_sock_recv(), if sgx_ocall(OCALL_SOCK_RECV, ms) return 0,  sgx_copy_to_enclave(buf, count, ms->ms_buf, retval) will return 0, causing the above error to be sent.
I tried to fix it and it works ok:
```
diff --git a/Pal/src/host/Linux-SGX/enclave_ocalls.c b/Pal/src/host/Linux-SGX/enclave_ocalls.c
index ebaca7d..57f23c1 100644
--- a/Pal/src/host/Linux-SGX/enclave_ocalls.c
+++ b/Pal/src/host/Linux-SGX/enclave_ocalls.c
@@ -771,7 +771,7 @@ int ocall_sock_recv (int sockfd, void * buf, unsigned int count,
             *addrlen = copied;
         }
 
-        if (!sgx_copy_to_enclave(buf, count, ms->ms_buf, retval)) {
+        if (retval > 0 && !sgx_copy_to_enclave(buf, count, ms->ms_buf, retval)) {
             retval = -EPERM;
             goto out;
         }
```

PS:
The same thing will happen in ocall_sock_recv_fd().
But I did not verify the results of it:
```
diff --git a/Pal/src/host/Linux-SGX/enclave_ocalls.c b/Pal/src/host/Linux-SGX/enclave_ocalls.c
index ebaca7d..03ac02c 100644
--- a/Pal/src/host/Linux-SGX/enclave_ocalls.c
+++ b/Pal/src/host/Linux-SGX/enclave_ocalls.c
@@ -856,19 +864,22 @@ int ocall_sock_recv_fd (int sockfd, void * buf, unsigned int count,
     retval = sgx_ocall(OCALL_SOCK_RECV_FD, ms);
 
     if (retval >= 0) {
-        if (!sgx_copy_to_enclave(buf, count, ms->ms_buf, retval)) {
+        if (retval > 0 && !sgx_copy_to_enclave(buf, count, ms->ms_buf, retval)) {
             sgx_reset_ustack();
             return -EPERM;
         }
 
-        copied = sgx_copy_to_enclave(fds, max_nfds_bytes, ms->ms_fds, ms->ms_nfds * sizeof(int));
-        if (!copied) {
-            sgx_reset_ustack();
-            return -EPERM;
+        if (ms->ms_nfds > 0) {
+            copied = sgx_copy_to_enclave(fds, max_nfds_bytes, ms->ms_fds, ms->ms_nfds * sizeof(int));
+            if (!copied) {
+                sgx_reset_ustack();
+                return -EPERM;
+            }
+            *nfds = copied / sizeof(int);
+        } else {
+            *nfds = 0;
         }
-        *nfds = copied / sizeof(int);
     }
-
     sgx_reset_ustack();
     return retval;
 }
```

**Comment by dimakuv** [comment]
Thanks for the bug report! This is unrelated to #1000, right? In the sense that both need to be merged into master.

**Comment by yamahata** [comment]
nice catch.
as counter part, ocall_sock_send, ocall_sock_send_fd would need similar fix, I guess.
what about ocall_read/ocall_write?

Anyway we should check all the ocall in this view point.

**Comment by pangzi85480** [comment]
> Thanks for the bug report! This is unrelated to #1000, right? In the sense that both need to be merged into master.

They should have a little relationship because they are all similar to the test cases.

**Comment by pangzi85480** [comment]
> nice catch.
> as counter part, ocall_sock_send, ocall_sock_send_fd would need similar fix, I guess.
> what about ocall_read/ocall_write?
> 
> Anyway we should check all the ocall in this view point.

yes, I also review the functions you mentioned, they don’t seem to have similar problems.

**Comment by dimakuv** [comment]
I'm working on this issue. Currently going through all OCALLs and checking for this pattern. Notes:

- `ocall_read` already has a check on `retval > 0`
- `ocall_getdents` already has a check on `retval > 0`
- `ocall_poll` does a copy but doesn't use retval as the size argument, so it is fine
- general rule: if OCALL's `sgx_copy_to_enclave(..., <size>)` doesn't use retval as size, then it is fine

**Comment by dimakuv** [comment]
@pangzi85480 Please check #1006. If you think it's correct please stamp with LGTM.
