### ISSUE TITLE
`make SGX=1 clean` doesn't work

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1010]
At least on my developer machine, the current Graphene master (cfe4036bbf) fails on `make SGX=1 clean` (after building with `make SGX=1`):
```
...
make[2]: Entering directory '/home/dimakuv/graphene/Pal/regression'
make -C ../src user_start.o
make[3]: Entering directory '/home/dimakuv/graphene/Pal/src'
  [ user_start.o ]
make[3]: Leaving directory '/home/dimakuv/graphene/Pal/src'
make[2]: *** No rule to make target '../../Runtime/libpal-Linux-SGX.so', needed by 'Process'.  Stop.
make[2]: Leaving directory '/home/dimakuv/graphene/Pal/regression'
Makefile:11: recipe for target 'clean' failed
make[1]: *** [clean] Error 2
...
```

# My Suspicion

Note how the Pal/regression/Makefile has the following target:
```
../src/user_shared_start.o ../src/user_start.o: ../src/user_start.S
    $(MAKE) -C ../src $(notdir $@)
```

So something triggers the calculation of `../src/user_start.o`. In the same file, `user_start.o` is used in this target:
```
LDLIBS-executables = ../src/user_start.o $(graphene_lib) $(pal_lib) $(preloads)
...
$(executables): %: %.c $(LDLIBS-executables)
```

And then in the clean target we have:
```
clean:
    rm -rf $(call expand_target,$(target)) ...
< where target is "target = $(executables) $(manifests)" >
```

So my suspicion was that `expand_target` actually triggers the calculation of the dependency chain, which brings us to `user_start.o` and its command `$(MAKE) -C ../src $(notdir $@)`.

I am by no means a Makefile expert, so this is all just speculation. The root cause may be totally different.

**Comment by stefanberger** [comment]
This works fine for me. Maybe issue has been resolved?

**Comment by dimakuv** [comment]
Yes, it also works fine for me. We fixed it at some point but forgot to close this issue.
