### ISSUE TITLE
Jenkins slaves fail to fetch submodules

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#1036]
When you open a PR on the main graphene repo and this PR updates one of the submodules (some?) Jenkins slaves fail to fetch the new submodule commit even though you opened a PR on the submodule first and therefore the commit should be fetchable (`refs/pull/*/head`).

If you push the change into a regular branch (`refs/heads/*`) of the submodule the problem goes away.

My best guess currently is that Jenkins does some git mirroring which doesn't mirror PRs.

Example log: https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-sgx/2252/build-log

Note how the recursive clone on Jenkins master works, but fails on the slave.

IIRC, on some slaves this doesn't happen. But when I tried to reproduce this I was unlucky and my jobs always got run on the same slaves.

cc: @dcowhig

**Comment by mkow** [comment]
This issue didn't occur for quite some time, so I'm closing this PR.
