### ISSUE TITLE
Specifying sgx.allowed_files = "./somefile" doesn't work

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1044]
If the user specifies the file in the SGX manifest as:
```
sgx.allowed_files.whatever = ./somefile
```
then the host file `somefile` in the current directory won't be recognized as an allowed one. This is because the logic in parsing the filename doesn't  understand `./`. (The culprit is probably `enclave_framework.c: register_trusted_file()` but I haven't debugged yet.)

This is annoying for cases like in Nginx:
```sh
# the manifest template contains this
sgx.allowed_files.logs = file:$(INSTALL_DIR)/logs

# the makefile contains this
THIS_DIR := $(dir $(lastword $(MAKEFILE_LIST)))  # THIS_DIR = ./ !!!
sed -e 's|$$(INSTALL_DIR)|'"$(INSTALL_DIR)"'|g' nginx.manifest.template > nginx.manifest
```

**Comment by jiazhang0** [comment]
The same issue happens on get_base_name() which cannot recognize `..`.

**Comment by boryspoplawski** [comment]
@dimakuv Seems that we are missing path normalization when handling allowed files, I will fix that.

@jiazhang0 Can you elaborate what the exact problem is (i.e. a specific use case, code that does not work as expected)? Comment above `get_base_name` says what it does and, to be honest, I have no idea what the base name of `..` should be.
