### ISSUE TITLE
[LibOS] Thread exit race

### ISSUE THREAD

**Issue by boryspoplawski** [oscarlab/graphene#1070]
When a thread exits it  wakes up its creator if it CLONE_CHILD_CLEARTID was set during `clone` call (using `release_clear_child_id`), but at this point it is still alive (not for long but still) and using some resources, most notably stack that might have been provided by `clone` caller. Caller might decide to free or reuse that stack (as pthreads do) causing some nasty to debug issues.

(This is one of the problems of #969)

**Comment by yamahata** [comment]
how about #332 ?

**Comment by boryspoplawski** [comment]
What about it?

**Comment by dimakuv** [comment]
@boryspoplawski, @yamahata meant https://github.com/oscarlab/graphene/pull/322 (he made a typo).

I also got into this mess while rebasing the Exitless PR and getting segfaults on `spinlock` LibOS regression test.

Unfortunately, #322 still doesn't solve all (my) problems. Even though #322 correctly switches the TCB and the stack of the exiting process, the Pthread logic still touches the same memory occupied by the old thread (and Pthread thinks this memory can be re-used by the new thread).

I am trying to figure out a better way of informing Pthreads that the thread actually exited...

**Comment by dimakuv** [comment]
Even if #322 would solve the segfaults, there is still the fact that there could be more threads inside the enclave than app/user expects (because the "dying" thread still occupies an enclave TCS):
```
[     1] ---- shim_clone(CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID,0x1d14f30,0x1d159d0,0x1d159d0,0x1d15680) ... clone
[     1] allocated pid: 254
[     1] bkeep_unmapped: 0xb234000-0xb236000 => slab
[     1] bkeep_unmapped: 0xb22f000-0xb234000 => slab
There are no available TCS pages left for a new thread!
Please try to increase sgx.thread_num in the manifest.
... even though the manifest contains the correct max number of enclave threads !..
```

**Comment by dimakuv** [comment]
We discussed this offline. It looks like the most correct strategy is to do it in `enclave_entry.S: .Lhandle_thread_reset`. We create a new in-enclave variable and toggle it (recall that at this point entering LibOS is impossible for this dying thread). LibOS's waiting thread may for example spin on this variable before going out of `futex(WAIT)`. This will ensure that the waiting thread continues only *after* the dying thread left the enclave.

Also, @boryspoplawski is working on the futex re-implementation. His changes also touch `CLONE_CHILD_CLEARTID`.

**Comment by mkow** [comment]
> Also, @boryspoplawski is working on the futex re-implementation. His changes also touch `CLONE_CHILD_CLEARTID`.

Corresponding PR: #1164
