### ISSUE TITLE
[Libos]Graphene-sgx does not support nginx in https mode

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#1092]
1. configure nginx with https mode, and build it.
```
diff --git a/nginx/Makefile b/nginx/Makefile
-       cd $(NGINX_SRC) && ./configure --prefix=$(abspath $(INSTALL_DIR))
+       cd $(NGINX_SRC) && ./configure --prefix=$(abspath $(INSTALL_DIR)) --with-http_stub_status_module --with-http_ssl_module --with-http_v2_module
```
2. change server conf in install/conf/nginx-graphene.conf:
```
    server {
        listen 8002 ssl http2;
        server_name 127.0.0.1;

        ssl_certificate /etc/nginx/ssl/server.crt;
        ssl_certificate_key /etc/nginx/ssl/server.key;

        ssl_session_cache shared:SSL:50m;
        ssl_session_timeout 1d;
        ssl_session_tickets off;

        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1.2;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        #charset koi8-r;

        #access_log  logs/host.access.log  main;
```
/etc/nginx/ssl/server.crt & server.key is generated by cmd:
```
openssl req -x509 -newkey rsa:2048 -days 365 -nodes -keyout /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.crt  -subj "/O=Test/CN=nginx" -sha256
```
3. run nginx:
SGX=1 ./pal_loader ./nginx.manifest -c conf/nginx-graphene.conf

4. test https:
curl -k https://127.0.0.1:8002

error info:
```
recvmsg()/recvmmsg()/recvfrom():flags parameter unsupported
```

Nginx call recv with flags MSG_PEEK, but graphene-sgx not support it.

I read the implementation of recv in graphene:
```
do_recvfrom()
   -> do_recvmsg()
     -> DkStreamRead()
       -> tcp_read()
         -> ocall_sock_recv()
          ->sgx_ocall_sock_recv()  INLINE_SYSCALL(recvfrom, XXX)
```

I tried to implement do_recvmsg, the nginx is running ok with https mode .
```
do_recvfrom()
   -> do_recvmsg_with_flags()
     -> DkStreamRecvmsg()
       -> tcp_recvmsg()
        -> ocall_sock_recvmsg()
          ->sgx_ocall_sock_recvmsg()  INLINE_SYSCALL(recvmsg, XXX)
```

So I also want to know, the previous implementation is why recv does not support flags, and will it be considered to support flags in some way?

**Comment by dimakuv** [comment]
This is a duplicate of #66. Indeed, Graphene doesn't support the `MSG_PEEK` flag. The implementation effort to support this flag won't be trivial (we need to buffer the reads and peek into this buffer). But agreed, this is an important missing feature.

> I tried to implement do_recvmsg, the nginx is running ok with https mode.

How did you implement this? Could you post your diff here or create a PR with it? We'll be happy to review it and merge if it is a good implementation.

**Comment by pangzi85480** [comment]
> This is a duplicate of #66. Indeed, Graphene doesn't support the `MSG_PEEK` flag. The implementation effort to support this flag won't be trivial (we need to buffer the reads and peek into this buffer). But agreed, this is an important missing feature.
> 
> > I tried to implement do_recvmsg, the nginx is running ok with https mode.
> 
> How did you implement this? Could you post your diff here or create a PR with it? We'll be happy to review it and merge if it is a good implementation.

In fact, I just pass the flags to linux os and let the os kernel do the work.
Because as you said, the current recvmsg(in graphene) does not manage buffer, so I understand that the work can be done in os.
Or does graphene not do this for other reasons?

**Comment by dimakuv** [comment]
This is a good question. I was under the impression that it required more work, not just passing the flags to the host OS. @thomasknauth, do you remember any discussions on `MSG_PEEK`?

**Comment by thomasknauth** [comment]
Hm, good question. At least these days you get a somewhat helpful message that MSG_PEEK is not supported. I think we never discussed how to implement it. Letting the OS handle it may open you up to certain attacks. Return A on MSG_PEEK and something else on the subsequent read? If the data is encrypted/integrity protect, this will probably be caught. But things along those lines would have to be considered by the implementation.

**Comment by pangzi85480** [comment]
> Hm, good question. At least these days you get a somewhat helpful message that MSG_PEEK is not supported. I think we never discussed how to implement it. Letting the OS handle it may open you up to certain attacks. Return A on MSG_PEEK and something else on the subsequent read? If the data is encrypted/integrity protect, this will probably be caught. But things along those lines would have to be considered by the implementation.

Thank you for your answer, but I am not sure about the risk of os handling MSG_PEEK. Can you answer it specifically?

PS, I am currently trying a simple solution to achieve this function, please also help us to see if this solution is feasible? #1110

**Comment by donporter** [comment]
In general, I think there should be a very high bar to adding functionality to the PAL ABI, or "punching holes" to the host.  This makes it harder to port Graphene to new hosts that may not support peek in the host OS (or requires a PAL to implement this), as well as introducing some concern about Iago attacks.  I think there is less security risk with networking, which tends to be verified end-to-end, but trusting what you get from a peek buffer and acting on malicious input could create problems.

My design question is whether it would be possible to buffer peek buffers in the libos/shim, rather than letting the host do this.

**Comment by dimakuv** [comment]
@pangzi85480 Thanks for submitting PR #1110. I left my comments there.

In general, the approach of "punching a hole" in #1110 won't work for us. But I believe there is a rather simple solution of adjusting the offset of the FD inside the LibOS for MSG_PEEK read syscalls. If you have the time, you could look into this. Otherwise one of us will probably try to implement this functionality in the near future.

**Comment by pangzi85480** [comment]
> In general, I think there should be a very high bar to adding functionality to the PAL ABI, or "punching holes" to the host. This makes it harder to port Graphene to new hosts that may not support peek in the host OS (or requires a PAL to implement this), as well as introducing some concern about Iago attacks. I think there is less security risk with networking, which tends to be verified end-to-end, but trusting what you get from a peek buffer and acting on malicious input could create problems.
> 
> My design question is whether it would be possible to buffer peek buffers in the libos/shim, rather than letting the host do this.

Yes, read your explanation, in fact, I also think it should be solved in libos.

**Comment by pangzi85480** [comment]
> @pangzi85480 Thanks for submitting PR #1110. I left my comments there.
> 
> In general, the approach of "punching a hole" in #1110 won't work for us. But I believe there is a rather simple solution of adjusting the offset of the FD inside the LibOS for MSG_PEEK read syscalls. If you have the time, you could look into this. Otherwise one of us will probably try to implement this functionality in the near future.

Nice, I am looking forward to explaining how to use offset to implement this function.
If not complicated, or I can try to do it.

**Comment by dimakuv** [comment]
Scratch my previous suggestion. Sockets don't have "offset", so my approach doesn't make sense. There must be a buffering mechanism inside of LibOS. But now that I read into this, it looks like it's enough to:
- dynamically allocate a buffer once `recv(MSG_PEEK)` is detected (and free the previous buffer if any)
- perform a read on this socket, copy result into this peek buffer
- on a next `recv()`, return result from that peek buffer (if need more data, perform another actual read on socket)

**Comment by bigdata-memory** [comment]
> Scratch my previous suggestion. Sockets don't have "offset", so my approach doesn't make sense. There must be a buffering mechanism inside of LibOS. But now that I read into this, it looks like it's enough to:
> 
> * dynamically allocate a buffer once `recv(MSG_PEEK)` is detected (and free the previous buffer if any)
> * perform a read on this socket, copy result into this peek buffer
> * on a next `recv()`, return result from that peek buffer (if need more data, perform another actual read on socket)

The size of peek buffer needs to be limited and its life-span could be managed by LibOS layer to make it more efficient.

**Comment by pangzi85480** [comment]
> > Scratch my previous suggestion. Sockets don't have "offset", so my approach doesn't make sense. There must be a buffering mechanism inside of LibOS. But now that I read into this, it looks like it's enough to:
> > 
> > * dynamically allocate a buffer once `recv(MSG_PEEK)` is detected (and free the previous buffer if any)
> > * perform a read on this socket, copy result into this peek buffer
> > * on a next `recv()`, return result from that peek buffer (if need more data, perform another actual read on socket)
> 
> The size of peek buffer needs to be limited and its life-span could be managed by LibOS layer to make it more efficient.

Nice idea.
But I am also considering whether there will be some special operations:
- first recv (peek) such as 10 bytes, next recv (no peek) only reads less than 10 bytes in length, then our buffer should be adjusted to only contain the last 5 bytes.
- The first time peek has 5 bytes, the second time continues peek 10 bytes, then we are going to read 5 bytes through dkrtreamread and rebuild a 10-byte buffer?

Or do we not allow the above operation?

**Comment by dimakuv** [comment]
> * first recv (peek) such as 10 bytes, next recv (no peek) only reads less than 10 bytes in length, then our buffer should be adjusted to only contain the last 5 bytes.
> * The first time peek has 5 bytes, the second time continues peek 10 bytes, then we are going to read 5 bytes through dkrtreamread and rebuild a 10-byte buffer?
> Or do we not allow the above operation?

We should allow such operations. It feels like we may want to use a ring buffer here, but maybe we can get away with:
1. A static buffer that starts with e.g. 64B and grows (via realloc) if a next MSG_PEEK has more than the current capability of the buffer.
2. We track capability (amount of allocated memory) and length (how many network-data bytes it currently holds) of the buffer.
3. Every time there is a recv(size), we start by reading from this buffer. (1) If length of the buffer is less than requested size, then we perform DkStreamRead(length - size) and concatenate the two, (2) if length is greater, then we read only from the buffer and memmove() the rest in the buffer to beginning of the buffer, and adjust length.
4. If it is a recv(MSG_PEEK, size), we do the same as in 3, but do not memmove() in the buffer -- we keep whatever is there. Also, if we perform DkStreamRead(length - size), we append it to the buffer.

Something like this.

**Comment by dimakuv** [comment]
+1 for @thomasknauth idea.

**Comment by thomasknauth** [comment]
Adding some more details. In the case of nginx, it either peeks for one byte or NGX_PROXY_PROTOCOL_MAX_HEADER bytes, which is defined as 107. Apache httpd seems to have one instance where is uses MSG_PEEK and this is for [one byte](https://github.com/apache/httpd/blob/03d334ebe0fe728db8ae701a656437619de8627e/modules/proxy/proxy_util.c) too. Lighttpd 1.4 has one instance of MSG_PEEK also for a size of [~100 bytes](https://github.com/lighttpd/lighttpd1.4/blob/1300815688497ed2a0b778db496cdec3e90e526a/src/mod_extforward.c#L1309).

A static buffer of 256 bytes may thus already be enough to cover most use cases of MSG_PEEK. If anything, the basic implementation can just error out. If, in the future, there is a need for a more robust implementation, we can always revisit this.

**Comment by bigdata-memory** [comment]
It may need read-write lock to protect the shared peek buffers otherwise would hit concurrency problem that is a little bit difficult to detect.

**Comment by pangzi85480** [comment]
> W.r.t. 3.: It is ok for recv() to return less than the requested number of bytes. This may reduce the complexity of our implementation. If there are 5 bytes in the Graphene-internal peek buffer, but the recv() is for 10 bytes, simply return 5 bytes. If the application cares/is written correctly, it will issue another recv() for the remaining bytes.
> 
> @pangzi85480 are you planning to submit a revised PR based on this updated design?

If this feature is not urgent, I can try to do this next week.

**Comment by pangzi85480** [comment]
> It may need read-write lock to protect the shared peek buffers otherwise would hit concurrency problem that is a little bit difficult to detect. probably TSX.

I plan to put the buffer as a member variable in the struct shim_sock_handle and protect it with lock(&hdl->lock).

**Comment by dimakuv** [comment]
@pangzi85480 This feature is not urgent, we'll be happy if you contribute your solution in the coming weeks. Thanks for this!

**Comment by dimakuv** [comment]
@pangzi85480 Did you make any progress on this feature? It would be nice to fix it already, as more and more people complain about Nginx not working with HTTPS :)

**Comment by dimakuv** [comment]
Note to myself: the peek buffer must be *per-socket*. We can add a new field for the socket handle in LibOS -- `char* peekbuf`. The buffer is NULL by default (to save space, most sockets won't ever use it) and is allocated to say 256 on the first MSG_PEEK. No need for additional locking since the buffer is per-socket-handle and is already covered by the socket lock.

We read into this buffer on recv with MSG_PEEK. On other recvs, we first check the peek buffer, and return (probably partial) results from there. It will be the responsibility of the app to correctly handle the case of partial returns, as Thomas suggested.

We need to be careful with checkpointing -- this new buffer must be checkpointed and restored correctly. Write a simple test to verify this.

**Comment by dimakuv** [comment]
@pangzi85480 I just noticed that you rebased #1110 according to our discussion here. Somehow, this new revision was lost by GitHub, and I noticed it only now. Currently reviewing, thanks for this!
