### ISSUE TITLE
[LibOS] Multiprocess futexes and graphene

### ISSUE THREAD

**Issue by boryspoplawski** [oscarlab/graphene#1107]
Please, correct me if I'm wrong.
While rewriting current implementation of futexes, I realized that it is quite impossible to implement mutliprocess futexes in graphene. Futexes are identified solely by their **physical** address and such information is impossible to get in userspace (well, at least if process is not owned by root).
What follows, is that the **only** supported by graphene use of futexes is when threads share one address space and use one virtual address to access the futex (i.e. it is not mapped twice).

**Comment by yamahata** [comment]
From the view point of unix process, (shared-mapped file, offset) can be used instead of physical address. The current implementation doesn't track which file is shared or not, though.

**Comment by boryspoplawski** [comment]
That might work, but what about pages mapped with MAP_SHARED? We would need some unique identifier to each page mapped and keep track of it (all remaps and any other operation that might move such page).
Overall it seems doable, with enough effort.

**Comment by thomasknauth** [comment]
How about requiring FUTEX_PRIVATE_FLAG in futex_op and worry about multi-process later? :)

As an aside, when you say "Futexes are identified solely by their physical address ..." this refers to their implementation inside the Linux kernel, correct? Also, how would a root-process go about turning a virtual address into a physical address? Why is this impossible for a non-root-process?

**Comment by boryspoplawski** [comment]
> How about requiring FUTEX_PRIVATE_FLAG in futex_op and worry about multi-process later? :)
Sounds good :) At the moment this flag is ignored and it's silently assumed that all accesses to a futex are made through one virtual address.

> As an aside, when you say "Futexes are identified solely by their physical address ..." this refers to their implementation inside the Linux kernel, correct? Also, how would a root-process go about turning a virtual address into a physical address? Why is this impossible for a non-root-process?
Correct (futexes are Linux-specific).
You can read /proc/[pid]/pagemap which contains among others physical addresses of each page. Output of this pseudo-file is sanitized when read by non-root process.

**Comment by dimakuv** [comment]
+1 to @thomasknauth idea of explicitly forbidding across-process futexes.

**Comment by boryspoplawski** [comment]
Closing, as the consensus seems to be reached (at least for now).
