### ISSUE TITLE
[LibOS/shim/test/apps/apache] run fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1115]
Env: Ubuntu 18.04

Test according toe README:

#cd LibOS/shim/test/apps/apache  
#sudo apt-get install -y build-essential flex libapr1-dev libaprutil1-dev libpcre2-dev apache2-utils
#make SGX=1
#make SGX=1 sgx-tokens
#make SGX=1 start-graphene-server &
...
httpd: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
DkProcessExit: Returning exit code 127
Makefile:237: recipe for target 'start-graphene-server' failed
make: *** [start-graphene-server] Error 127

Solution recommendation:
Need install libpcre3-dev rather than libpcre2-dev in Ubuntu 18.04

**Comment by dimakuv** [comment]
Could you create a PR with fixes for this?

**Comment by mkow** [comment]
Outdated, closing (this example was rewritten since then).
