### ISSUE TITLE
[LibOS/shim/test/apps/python] compile fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1116]
Env: Ubuntu 18.04

#cd LibOS/shim/test/apps/python  
#make SGX=1 
...
 make: *** No rule to make target '/lib/x86_64-linux-gnu/libcrypto.so.1.0.0', needed by 'python.manifest.sgx'.  Stop.
 make: *** No rule to make target '/lib/x86_64-linux-gnu/libssl.so.1.0.0', needed by 'python.manifest.sgx'.  Stop.

Solution recommendation:
ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/
ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/

**Comment by dimakuv** [comment]
Thank you. We are currently updating the Python example. We will fix this issue soon.

**Comment by jiazhang0** [comment]
By the way, could you add the info about the dependencies and test steps for ubuntu 18.04 for all app tests? @dimakuv

**Comment by dimakuv** [comment]
By the way, if anyone wants to try a newer Python example, check here: https://github.com/oscarlab/graphene-tests/pull/29.

It is still work in progress because it's unclear how to find all trusted files that Python use.

**Comment by mkow** [comment]
Outdated, closing (this example was rewritten since then).
