### ISSUE TITLE
[LibOS/shim/test/apps/r] compile fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1119]
Env: Ubuntu 18.04

#cd LibOS/shim/test/apps/r
#make SGX=1
...
ldd: /usr/lib/R/bin/exec/R: No such file or directory
Makefile:55: recipe for target 'R-ldd' failed
make: *** [R-ldd] Error 1
rm R-ldd/usr/lib/R/bin/exec/R: No such file or directory

Solution recommendation: apt-get install -y r-base

**Comment by TomTanJun** [comment]
After compiling successfully, run failed:
root@dbf6791bf75d:~/graphene/LibOS/shim/test/apps/r# SGX=1 ./pal_loader R.manifest --slave --vanilla -f scripts/sample.r
Manifest file: file:R.manifest.sgx
Executable file: file:R
Cannot read manifest: equal mark expected
Invalid manifest: file:R.manifest.sgx

**Comment by TomTanJun** [comment]
> Env: Ubuntu 18.04
> 
> #cd LibOS/shim/test/apps/r
> #make SGX=1
> ...
> ldd: /usr/lib/R/bin/exec/R: No such file or directory
> Makefile:55: recipe for target 'R-ldd' failed
> make: *** [R-ldd] Error 1
> rm R-ldd/usr/lib/R/bin/exec/R: No such file or directory
> 
> Solution recommendation: apt-get install -y r-base

Please add it to README, thanks.

**Comment by dimakuv** [comment]
We haven't updated the R example yet (I believe it's like ~5 months old).

Could you create a PR with your proposed fixes?

**Comment by mkow** [comment]
Outdated, closing (this example was rewritten since then).
