### ISSUE TITLE
[LibOS/shim/test/apps/curl] compile fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1120]
Env: Ubuntu 18.04

#cd LibOS/shim/test/apps/curl
#make SGX=1
...
../../Makefile.Test:86: curl.manifest.sgx.d: No such file or directory
[ curl.manifest ]
RELDIR= && \
sed -e 's:\$(PAL):/root/graphene/Runtime/pal_loader SGX:g' -e 's:\$(PWD):/root/graphene/LibOS/shim/test/apps/curl:g' -e 's:\$(BIN):curl:g' -e 's:\$(SHIMPATH):'$RELDIR'../..//../../../Runtime/libsysdb.so:g' -e 's:\$(LIBCDIR):'$RELDIR'../..//../../../Runtime:g'  curl.manifest.template > curl.manifest
(grep -q '^#!' curl.manifest && chmod +x curl.manifest) || true
  [ curl.manifest.sgx.d ]
ln -sf ../..//../../../Runtime/pal_loader
make: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libgnutls.so.26', needed by 'curl.manifest.sgx'.  Stop.

After investigation, we need to do:
1, Install packages:
apt-get install -y librtmp1 libidn11 libnghttp2-14 libpsl5 libgcrypt11-dev libcurl4 curl 

2, Create soft links
ln -sfn /usr/lib/x86_64-linux-gnu/libgcrypt.so /lib/x86_64-linux-gnu/libgcrypt.so
ln -sfn /lib/x86_64-linux-gnu/libidn.so.11 /usr/lib/x86_64-linux-gnu/libidn.so.11
ln -sfn /usr/lib/x86_64-linux-gnu/librtmp.so.1 /usr/lib/x86_64-linux-find gnu/librtmp.so.0

3, Modify curl.manifest.template:
 sgx.trusted_files.libnss2 = file:/lib/x86_64-linux-gnu/libnss_files.so.2
 sgx.trusted_files.libnss3 = file:/lib/x86_64-linux-gnu/libnss_nis.so.2
 sgx.trusted_files.libnss4 = file:$(LIBCDIR)/libnss_dns.so.2
-sgx.trusted_files.libssl = file:/lib/x86_64-linux-gnu/libssl.so.1.0.0
-sgx.trusted_files.libcrypto = file:/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
+sgx.trusted_files.libssl = file:/usr/lib/x86_64-linux-gnu/libssl.so.1.1
+sgx.trusted_files.libcrypto = file:/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
 sgx.trusted_files.libresolv = file:$(LIBCDIR)/libresolv.so.2
 sgx.trusted_files.libcurl = file:/usr/lib/x86_64-linux-gnu/libcurl.so.4
 sgx.trusted_files.libidn = file:/usr/lib/x86_64-linux-gnu/libidn.so.11
-sgx.trusted_files.librtmp = file:/usr/lib/x86_64-linux-gnu/librtmp.so.0
+sgx.trusted_files.librtmp = file:/usr/lib/x86_64-linux-gnu/librtmp.so.1
 sgx.trusted_files.libgssapi_krb5 = file:/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
 sgx.trusted_files.liblber = file:/usr/lib/x86_64-linux-gnu/liblber-2.4.so.2
 sgx.trusted_files.libldap_r = file:/usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
-sgx.trusted_files.libgnutls = file:/usr/lib/x86_64-linux-gnu/libgnutls.so.26
-sgx.trusted_files.libgcrypt = file:/lib/x86_64-linux-gnu/libgcrypt.so.11
+sgx.trusted_files.libgnutls = file:/usr/lib/x86_64-linux-gnu/libgnutls.so.30
+sgx.trusted_files.libgcrypt = file:/lib/x86_64-linux-gnu/libgcrypt.so
 sgx.trusted_files.libk5crypto = file:/usr/lib/x86_64-linux-gnu/libk5crypto.so.3
 sgx.trusted_files.libcom_err = file:/lib/x86_64-linux-gnu/libcom_err.so.2
 sgx.trusted_files.libkrb5support = file:/usr/lib/x86_64-linux-gnu/libkrb5support.so.0
@@ -83,6 +83,14 @@ sgx.trusted_files.libsqlite3 = file:/usr/lib/x86_64-linux-gnu/libsqlite3.so.0
 sgx.trusted_files.libcrypt = file:/lib/x86_64-linux-gnu/libcrypt.so.1
 sgx.trusted_files.libhcrypto = file:/usr/lib/x86_64-linux-gnu/libhcrypto.so.4
 sgx.trusted_files.libnsl = file:/lib/x86_64-linux-gnu/libnsl.so.1
+sgx.trusted_files.libnghttp2 = file:/usr/lib/x86_64-linux-gnu/libnghttp2.so.14
+sgx.trusted_files.libidn2 = file:/usr/lib/x86_64-linux-gnu/libidn2.so.0
+sgx.trusted_files.libpsl5 = file:/usr/lib/x86_64-linux-gnu/libpsl.so.5
+sgx.trusted_files.libunistring = file:/usr/lib/x86_64-linux-gnu/libunistring.so.2
+sgx.trusted_files.libhogweed = file:/usr/lib/x86_64-linux-gnu/libhogweed.so.4
+sgx.trusted_files.libnettle = file:/usr/lib/x86_64-linux-gnu/libnettle.so.6
+sgx.trusted_files.libgmp = file:/usr/lib/x86_64-linux-gnu/libgmp.so.10
+sgx.trusted_files.opensslcnf = file:/usr/lib/ssl/openssl.cnf

Then we can compile successfully

**Comment by TomTanJun** [comment]
Another issue is run curl https failed
#SGX=1 ./pal_loader curl.manifest https://www.baidu.com
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
DkProcessExit: Returning exit code 77

Solution recommendation is to modify curl.manifest.template:
- fs.mount.etc.uri = file
+ fs.mount.etc.uri = file:/etc
+ sgx.allowed_files.etc = file:/etc

**Comment by dimakuv** [comment]
We haven't updated the Curl example yet (I believe it's like ~5 months old).

Could you create a PR with your proposed fixes?

**Comment by mkow** [comment]
@TomTanJun Curl example was recently rewritten, please check it now.

**Comment by TomTanJun** [comment]
I run "make SGX=1 check" per README, and error occurs:
`Exception: Cannot resolve file:/lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2 or the file does not exist.`

Does it mean we need install some packages?
Could you please add more detailed info in README such as which packages need to be installed?

Thanks

**Comment by dimakuv** [comment]
`sudo apt install libnss-mdns`

**Comment by TomTanJun** [comment]
> install libnss-mdns

It works.

The test run pass.

Thanks.

**Comment by mkow** [comment]
@TomTanJun: Fix for the readme: https://github.com/oscarlab/graphene-tests/pull/59
