### ISSUE TITLE
[LibOS/shim/test/apps/ltp] compile fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1121]
Env: Ubuntu 18.04

 #cd LibOS/shim/test/apps/ltp  
 #make SGX=1
 ...
 cd /root/graphene/LibOS/shim/test/apps/ltp//opt/ltp/testcases/bin && make
make[1]: Entering directory '/root/graphene/LibOS/shim/test/apps/ltp/opt/ltp/testcases/bin'
Traceback (most recent call last):
File "./runltp_xml.py", line 33, in <module>
  from lxml import etree
ModuleNotFoundError: No module named 'lxml'
Traceback (most recent call last):
File "./runltp_xml.py", line 33, in <module>
  from lxml import etree
ModuleNotFoundError: No module named 'lxml'
Traceback (most recent call last):
File "./runltp_xml.py", line 33, in <module>
  from lxml import etree
ModuleNotFoundError: No module named 'lxml'
Traceback (most recent call last):
File "./runltp_xml.py", line 33, in <module>
  from lxml import etree
ModuleNotFoundError: No module named 'lxml'
Traceback (most recent call last):
File "./runltp_xml.py", line 33, in <module>
  from lxml import etree
ModuleNotFoundError: No module named 'lxml'

Solution recommendation: 
apt-get install python-dev libxml2 libxml2-dev libxslt-dev  python3-lxml

**Comment by TomTanJun** [comment]
After compiling successfully, run failed:
#make SGX=1 regression
Makefile:48: recipe for target 'ltp-sgx.xml' failed
make[1]: *** [ltp-sgx.xml] Error 38
make[1]: Leaving directory '/root/graphene/LibOS/shim/test/apps/ltp'
Makefile:39: recipe for target 'regression' failed
make: *** [regression] Error 2

**Comment by dimakuv** [comment]
1. Could you create a PR with the proposed changes to README (specifying which packages to install for Ubuntu 18.04)?

2. LTP is not expected to work on SGX currently :) The fact that it fails at runtime is normal.

**Comment by mkow** [comment]
No response from the reporter, closing.
