### ISSUE TITLE
GSCE redis sample fails to run

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1122]
following the https://github.com/oscarlab/graphene/blob/master/Tools/README 

running Ubuntu 16.04.6 LTS, Docker version 18.09.7, build 2d0083d

when i run ./gsce run -i -t -p 6379:6379 redis:latest

i get

Step 6/13 : COPY Runtime/* /home/vania/graphene/Runtime/
COPY failed: stat /var/lib/docker/tmp/docker-builder167250489/home/vania/graphene/LibOS/glibc-build/csu/crt1.o: no such file or directory
Unable to find image 'gsc_redis:latest' locally
docker: Error response from daemon: pull access denied for gsc_redis, repository does not exist or may require 'docker login'.
See 'docker run --help'.

docker run -i -t -p 6379:6379 redis:latest works as expected

**Comment by dimakuv** [comment]
It looks like the Graphene build failed.

Could you build Graphene without Docker, just on your Ubuntu? You can follow this: https://github.com/oscarlab/graphene/wiki/Graphene-SGX-Quick-Start

**Comment by fixerivan** [comment]
redid the whole setup this time on ubuntu 19.04

out of the box i get:

ln: target '/lib/x86_64-linux-gnu/libssl.so.1.0.0' is not a directory
The command '/bin/sh -c ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0' returned a non-zero code: 1
Unable to find image 'gsc_redis:latest' locally
docker: Error response from daemon: pull access denied for gsc_redis, repository does not exist or may require 'docker login'.
See 'docker run --help'.

when i remove the gsc_ prefix in the gsce script i get up till:

./gsce run -i -t -p 6379:6379 redis:latest
Sending build context to Docker daemon  1.135GB
Step 1/14 : FROM redis:latest
 ---> de25a81a5a0b
Step 2/14 : USER root
 ---> Using cache
 ---> 34e8e88be41e
Step 3/14 : RUN apt-get update &&     apt-get install -y openssl libjemalloc-dev python python-pip python-dev
 ---> Using cache
 ---> 060037ddf43c
Step 4/14 : RUN pip install protobuf &&     pip install pycrypto
 ---> Using cache
 ---> c1d1adb2162a
Step 5/14 : RUN ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0
 ---> Running in 354cc2d8c605
**ln: target '/lib/x86_64-linux-gnu/libssl.so.1.0.0' is not a directory**
The command '/bin/sh -c ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0' returned a non-zero code: 1
1:C 08 Nov 2019 12:57:55.744 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 08 Nov 2019 12:57:55.744 # Redis version=5.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 08 Nov 2019 12:57:55.744 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.6 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 08 Nov 2019 12:57:55.745 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 08 Nov 2019 12:57:55.745 # Server initialized
1:M 08 Nov 2019 12:57:55.745 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 08 Nov 2019 12:57:55.745 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 08 Nov 2019 12:57:55.745 * Ready to accept connections

**Comment by fixerivan** [comment]
added some debug output to the script this step is failing:

~/graphene # docker build -f Tools/build/Dockerfile.redis -t gsc_redis .
Sending build context to Docker daemon  1.135GB
Step 1/14 : FROM redis:latest
 ---> de25a81a5a0b
Step 2/14 : USER root
 ---> Using cache
 ---> 34e8e88be41e
Step 3/14 : RUN apt-get update &&     apt-get install -y openssl libjemalloc-dev python python-pip python-dev
 ---> Using cache
 ---> 060037ddf43c
Step 4/14 : RUN pip install protobuf &&     pip install pycrypto
 ---> Using cache
 ---> c1d1adb2162a
Step 5/14 : RUN ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0
 ---> Running in 8ba187f00e7b
ln: target '/lib/x86_64-linux-gnu/libssl.so.1.0.0' is not a directory
The command '/bin/sh -c ln -s /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 RUN ln -s /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 /lib/x86_64-linux-gnu/libssl.so.1.0.0' returned a non-zero code: 1


redis:latest already rolls on libcrypto1.1 and libssl1.1 after changing to that i get up to:

~/graphene # docker build -f Tools/build/Dockerfile.redis -t gsc_redis .
Sending build context to Docker daemon  1.135GB
Step 1/15 : FROM redis:latest
 ---> de25a81a5a0b
Step 2/15 : USER root
 ---> Using cache
 ---> 34e8e88be41e
Step 3/15 : RUN apt-get update &&     apt-get install -y openssl libjemalloc-dev python python-pip python-dev libssl1.1
 ---> Using cache
 ---> 52d6cc9d3dee
Step 4/15 : RUN pip install protobuf &&     pip install pycrypto
 ---> Using cache
 ---> 1065574e7326
Step 5/15 : RUN ln  /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
 ---> Running in f33a85f1e559
Removing intermediate container f33a85f1e559
 ---> da057735216b
Step 6/15 : RUN ln  /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /lib/x86_64-linux-gnu/libssl.so.1.0.0
 ---> Running in b90732f7e2d8
Removing intermediate container b90732f7e2d8
 ---> 8025ef3e1678
Step 7/15 : RUN mkdir -p /root/graphene/LibOS/shim/test/apps/redis  && mkdir -p /root/graphene/Pal/src/host/Linux-SGX/signer  && mkdir -p /root/graphene/Runtime  && mkdir /gbin
 ---> Running in 473ccfeb2516
Removing intermediate container 473ccfeb2516
 ---> dc1f49885f80
Step 8/15 : COPY Runtime/* /root/graphene/Runtime/
COPY failed: stat /var/lib/docker/tmp/docker-builder876940316/root/graphene/LibOS/glibc-build/csu/crt1.o: no such file or directory

which is pretty weird because:

~/graphene # find | grep crt1.o
./Runtime/crt1.o
./LibOS/glibc-build/csu/gcrt1.o
./LibOS/glibc-build/csu/Scrt1.o
./LibOS/glibc-build/csu/crt1.o
./LibOS/glibc-build/csu/Mcrt1.o

**Comment by fixerivan** [comment]
@dimakuv graphene build is ok - samples / sample apps run, i am quite sure this is a docker generation issue i always get just to that COPY build file instruction and thats it (gsce script Step 8/15 : COPY Runtime/* /root/graphene/Runtime/)

**Comment by dimakuv** [comment]
@fixerivan I know what the reason is. Sorry I forgot about it earlier, but our Tools/README actually has the hint:
```
1) Graphene is having trouble handling the symbolic links in graphene/Runtime
	- For some reason Graphene doesn't read symbolic links in certain instances. You will need to replace all of the links with a copy of the actual files with the same name to the Runtime folder. Rather than doing this manually (more painful than you may think) use this trick:
	- `shopt -s globstar` <-- enables globstar option
	- `sed -i '' **/*` <-- replaces all of the links
```

Please try this (replacing all symlinks in `graphene/Runtime`) and run the tool again.

P.S. Sorry for this. The GSCE tool was experimental and is not user-friendly at all. We are working on a complete re-write, but this is not the highest priority for us.

**Comment by fixerivan** [comment]
thanks that helped, now we are one step further! :) 

now it fails on:

Step 12/13 : RUN cd /root/graphene/LibOS/shim/test/apps/redis &&     /root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal /root/graphene/Pal/src/host/Linux-SGX/../../../../Runtime/libpal-Linux-SGX.so -key /root/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output redis.manifest.sgx -manifest redis.manifest

first it was missing python3 - so i added that, now it fails with python3 on:

Step 12/13 : RUN cd /root/graphene/LibOS/shim/test/apps/redis &&     /root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal /root/graphene/Pal/src/host/Linux-SGX/../../../../Runtime/libpal-Linux-SGX.so -key /root/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output redis.manifest.sgx -manifest redis.manifest
 ---> Running in 3e93c424f283
Traceback (most recent call last):
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 12, in <module>
    from generated_offsets import *
ModuleNotFoundError: No module named 'generated_offsets'

yes this kinda feels like it needs an update / rewrite

**Comment by fixerivan** [comment]
noticed that is probably what is meant in readme too .. so added to gsce

df.write('COPY Pal/src/host/Linux-SGX/* ' + proj_dir + '/Pal/src/host/Linux-SGX/signer/\n')

then it started to fail on:

Successfully tagged gsc_redis:latest
sudo docker build -f Tools/build/Dockerfile.redis -t gsc_redis .

Traceback (most recent call last):
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 9, in <module>
    import aesm_pb2
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/aesm_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google'
/gbin/app_exec: line 7: ./redis.manifest.sgx: Permission denied

which was resolved by adding pip3 install dependencies 

now it goes all the way to:

Successfully tagged gsc_redis:latest
sudo docker build -f Tools/build/Dockerfile.redis -t gsc_redis .

Attributes:
    mr_enclave:  ca81829cb82f9a8e0b77402b5ca75cc942479272be5623fb87f0054039059f83
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   1f00000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     653850fccea300219b7e1a573422ff82...
    exponent:    3
    signature:   6417ba2f2f391575e2a3931255d2347f...
    date:        2019-11-09
/gbin/app_exec: line 7: ./redis.manifest.sgx: Permission denied

not sure what was the problem but after trying to run the docker image manually there was more output:

docker run -it 20255344805c --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket /bin/bash
Attributes:
    mr_enclave:  ca81829cb82f9a8e0b77402b5ca75cc942479272be5623fb87f0054039059f83
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   1f00000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     653850fccea300219b7e1a573422ff82...
    exponent:    3
    signature:   6417ba2f2f391575e2a3931255d2347f...
    date:        2019-11-09
Traceback (most recent call last):
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 153, in <module>
    sys.exit(main())
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 147, in main
    token = connect_aesmd(attr)
  File "/root/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 102, in connect_aesmd
    raise socket.error("Cannot connect to the AESMD service")
OSError: Cannot connect to the AESMD service
/gbin/app_exec: line 7: ./redis.manifest.sgx: Permission denied

which is weird because aesmd service is running: 

ps -aux | grep aesmd
root      8399  0.0  0.0  11772   860 pts/2    S+   12:11   0:00 grep --color=auto aesmd
aesmd    29606  0.0  0.0 359912 14720 ?        Ssl  Nov08   0:00 /opt/intel/sgxpsw/aesm/aesm_service

sgx / graphene-sgx drivers are loaded:

lsmod | grep sgx
graphene_sgx           16384  0
isgx                   49152  2

tried load.sh reloading:

cd Pal/src/host/Linux-SGX/sgx-driver
make
sudo ./load.sh

and retried gsce, still the same result always getting that /gbin/app_exec: line 7: ./redis.manifest.sgx: Permission denied

**Comment by fixerivan** [comment]
added chmod 777 on the .manifest.sgx to gsce 

after that it goes all the way to:

sudo docker run -i -t -i -t -p 6379:6379 --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc_redis

Attributes:
    mr_enclave:  d4c34dbb95f81aa2e719722c32ec7b0af22d4f3f111261c0943dd06fb58455fe
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   1f00000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     653850fccea300219b7e1a573422ff82...
    exponent:    3
    signature:   365b44ade09632129be678300bdcff49...
    date:        2019-11-09
/root/graphene/Runtime/pal-Linux-SGX: error while loading shared libraries: libprotobuf-c.so.1: cannot open shared object file: No such file or directory

according to Readme:

10) "Error while loading shared libraries: cannot open shared object file: No such file or directory"
        - Add the library to your graphene/Runtime directory. This is a temporary workaround.

did that - still the same

when i change the entrypoint in sgce run it and then manually go into the container

sudo docker run -i -t -i -t -p 6379:6379 --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc_redis /bin/bash

and run manually:

root@104d67f19431:~/graphene/LibOS/shim/test/apps/redis# ./redis.manifest.sgx
redis-server: /graphene/libc.so.6: version `GLIBC_2.28' not found (required by redis-server)

if i add COPY of libprotobuf-c.so.1 to /lib/ then it finds it and gsce gets to the same point of telling me that:

    mr_enclave:  d4c34dbb95f81aa2e719722c32ec7b0af22d4f3f111261c0943dd06fb58455fe
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   1f00000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     653850fccea300219b7e1a573422ff82...
    exponent:    3
    signature:   365b44ade09632129be678300bdcff49...
    date:        2019-11-09
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
redis-server: /graphene/libc.so.6: version `GLIBC_2.28' not found (required by redis-server)

which is pretty much end of the road as far as i know graphene-sgx supports glibc of up to 2.27

so redis:latest can't work ...

**Comment by dimakuv** [comment]
Yes, `GLIBC_2.28 not found` looks like a dead-end for you :)

Graphene currently supports up to Glibc 2.27. It looks like it's time to upgrade to Glibc 2.30...

**Comment by mkow** [comment]
@fixerivan a small request: please use ``` when pasting logs (especially when they are long), otherwise it's hard to see which part is your comment and which is logs.

**Comment by mkow** [comment]
GSC was deprecated and a new implementation is coming, see https://github.com/oscarlab/graphene/pull/1345. Closing this issue as outdated.
