### ISSUE TITLE
[LibOS/shim/test/apps/tensorflow] run fail

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1124]
Env: Ubuntu 18.04

cd LibOS/shim/test/apps/tensorflow
make install-dependencies-ubuntu
SGX=1 make all sgx-tokens
SGX=1 make check

./pal_loader ./label_image.manifest.sgx -m inception_v3.tflite -i image.bmp -t 1
make: ./pal_loader: Command not found
Makefile:72: recipe for target 'check' failed
make: *** [check] Error 127

Solution recommendation:
ln -sfn ../../../../../Runtime/pal_loader pal_loader

**Comment by dimakuv** [comment]
Thanks for the bug report!

Could you create a PR for that? Seems trivial.

**Comment by TomTanJun** [comment]
After sync code from the latest graphene git repo, tensorflow can run successfully.

The output:
Loaded model inception_v3.tflite
resolved reporter
invoked
average time: 1018.21 ms
0.699144: 653 military uniform
0.0383276: 668 mortarboard
0.0223822: 401 academic gown
0.0187004: 835 suit
0.0142862: 458 bow tie
