### ISSUE TITLE
how to debug - Unknown or illegal instruction

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1138]
trying to run pre-build (from packages) app on Ubuntu 16.04. getting this:

*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Unknown or illegal instruction at RIP 0x00000008f4762766

any tips how to debug / what can be done? 

thx!

**Comment by fixerivan** [comment]
when i enable debug i see just this:

[     1] ---- shim_getpid() = 1
[     1] ---- shim_access("/proc/1/oom_score_adj",F_OK) = -2
[     1] ---- shim_access("/proc/1/oom_adj",F_OK) = -2
[     1] ---- shim_socketpair(UNIX,SEQPACKET,0 ... socketpair
[     1] ---- return from shim_socketpair(...,[-1893329440, 8]) = -93
Unknown or illegal instruction at RIP 0x00000008f4760766
[     1] illegal instruction at 0x8f4760766
[     1] SIGILL handled
[     1] run signal handler 0x8f2466bcd (4, 0x88f260ce0, 0x88f260d68)
[     1] killed by SIGILL
[     1] IPC broadcast: IPC_CLD_EXIT(1, 1, 0, 132)
[     1] clear child tid at 0x881201e50
[     1] this is the only thread 1
[     1] Waiting for 0.5s for all in-flight IPC messages to reach their destinations
[     1] Deleting port 0x8f23ff048 (handle 0x8fbf725b0) of process 7
[     1] process 7 exited with status 132
DkProcessExit: Returning exit code 132
[P00007] IPC helper thread terminated

**Comment by dimakuv** [comment]
Hi @fixerivan,

What you can do is look through the complete log and find an executable/library that occupies the region of memory where your "illegal instruction" error happens. In particular, Graphene tells you `illegal instruction at RIP 0x00000008f4760766`. So you should look for a memory region containing `0x8f4760766` in the log. After you identify which exec/library it is, you can inspect this exec/library via e.g. `objdump -D <exec-name>`, and find this instruction at the specified address (but be careful with offsets, you'll have to do additional math to calculate the correct offset in the exec/lib).

At this point, you will helpfully identify the tuple <exec/lib, function, instruction>. This should be enough information to figure out why the application fails.

My suspicion it is some AVX instruction. Please report back if this description helps and you find anything interesting.

P.S. GDB rules, it will probably help you in debugging.

**Comment by mkow** [comment]
Closing due to no reply from the reporter. @fixerivan feel free to reopen if you get more information (see @dimakuv's comment).
