### ISSUE TITLE
how to allow temp files?

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1139]
trying to run an existing app, it seams it tries to create a file in the /tmp folder

21:37:24.832: Fatal initialization error: Could not create a temporary directory in ?/tmp?.

there doesn't seam to be a way to allow such behavior in the manifest, or am i missing something? 

thx!

**Comment by dimakuv** [comment]
```
fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp

sgx.allowed_files.tmp = file:/tmp
sgx.allow_file_creation = 1
```

This should work.

**Comment by fixerivan** [comment]
thx, worked
