### ISSUE TITLE
 [LibOS/shim/test/native/helloworld] run fail

### ISSUE THREAD

**Issue by sqq0216** [oscarlab/graphene#1140]
Env: Ubuntu 16.04

```
cd LibOS/shim/test/native
make SGX=1
make SGX=1 sgx-tokens
```

```
 [ Token: epoll_socket ]
Traceback (most recent call last):
  File "/home/ubuntu-sqq/Graphene/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 9, in <module>
    import aesm_pb2
  File "/home/ubuntu-sqq/Graphene/graphene/Pal/src/host/Linux-SGX/signer/aesm_pb2.py", line 9, in <module>
    from google.protobuf import symbol_database as _symbol_database
ImportError: cannot import name 'symbol_database'
..//../../../Pal/src//host/Linux-SGX/Makefile.Test:12: recipe for target 'epoll_socket.token' failed
make: *** [epoll_socket.token] Error 1
```

**Comment by dimakuv** [comment]
What about `sudo pip install --upgrade protobuf` ? Try it and re-build your helloworld example.

**Comment by sqq0216** [comment]
I have solved the problem above, and run  'make SGX=1 sgx-tokens' successfully, but when I run 'SGX=1 ./pal_loader helloworld' , there is another problem:
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Unknown or illegal instruction at RIP 0x000000000bcd5cc7
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. *** 
(vector = 0x6, type = 0x3 valid = 1, RIP = +0x00027cc7)
rax: 0xffffffe0 rcx: 0x0fee36e0 rdx: 0x00000000 rbx: 0x0ffe6318
rsp: 0x0ffe6250 rbp: 0x0ffe6250 rsi: 0x0fee3230 rdi: 0x0bee2980
r8 : 0x0fee42e0 r9 : 0x0fee3ee0 r10: 0x0fee43e0 r11: 0x0fee47e0
r12: 0x00000010 r13: 0x0fee3230 r14: 0x0bee8414 r15: 0x00000000
rflags: 0x00010247 rip: 0x0bcd5cc7  
I saw some other similer problem on issues, and the suggestion is look through the complete log, if what I should do is so I want to know where is the log, and if there are other suggestions?

**Comment by dimakuv** [comment]
This is interesting. This looks like a bug in Graphene.

The complete log means that you need to put `loader.debug_type = inline` in your manifest and re-build and re-run your application. This time, you will see a lot of output. This is what is meant by the log.

**Comment by mkow** [comment]
I just verified that this test still crashes on the current master (47d19bda95f61992166bb5023b4610b2ebbffdc6), although slightly differently:
```
[1:helloworld] shim process initialized
[1:helloworld] memory fault at 0x00000000 (IP = 0x001da68f)
[1:helloworld] signal 11 handled
[1:helloworld] run signal handler 0xb5c151e (11, 0xfeee4b0, 0xfeee538)
[1:helloworld] killed by signal 11
```

I needed ~80 runs to trigger this bug. It's probably totally unrelated to the test itself and most likely just a general SGX PAL instability.

**Comment by mkow** [comment]
Ok, it's just #1408. Time to try fixing it, I guess...

**Comment by mkow** [comment]
Since the originally reported bug doesn't seem to trigger anymore and we have a separate issue for the NULL-deref bug (#1408), I'm closing this one.
