### ISSUE TITLE
no errors but app is not running, nothing is happening

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1141]
created manifest, running in debug mode, no errors encountered, the last lines of log say just this:

allowed: file:/tmp
[P00022] set tcb to 0x87ffe3550
[P00022] host: Linux-SGX
[P00022] bkeep_unmapped: 0x87bb7d000-0x87bb7f000 => vma
[P00022] allocate 0x87bb7d000-0x87bb7f000 for vmas
[P00022] Converting early VMA [0x87bc8a080] 0x87bc8f000-0x87bea6000
[P00022] Converting early VMA [0x87bc8a0c8] 0x87fffa000-0x87fffff72
[P00022] Converting early VMA [0x87bc8a110] 0x87bb80000-0x87bc8e000
[P00022] Converting early VMA [0x87bc8a158] 0x87bb7d000-0x87bb7f000
[P00022] heap top adjusted to 0x85224e000
[P00022] bkeep_unmapped: 0x87bb6c000-0x87bb7d000 => slab
[P00022] bkeep_unmapped: 0x87bb4b000-0x87bb6c000 => slab
[P00022] bkeep_unmapped: 0x87bb47000-0x87bb4b000 => slab
[P00022] bkeep_unmapped: 0x87bb42000-0x87bb47000 => slab
[P00022] bkeep_unmapped: 0x87bb3a000-0x87bb42000 => slab
[P00022] shim loaded at 0x87bb80000, ready to initialize
[     1] bkeep_unmapped: 0x87b376000-0x87b378000 => slab
[     1] bkeep_unmapped: 0x87b375000-0x87b376000 => slab
[     1] bkeep_unmapped: 0x87b373000-0x87b375000 => slab
[     1] bkeep_munmap: 0x87b375000-0x87b376000
[     1] bkeep_unmapped: 0x87b36f000-0x87b373000 => slab
[     1] bkeep_munmap: 0x87b373000-0x87b375000
[     1] bkeep_unmapped: 0x87b367000-0x87b36f000 => slab
[     1] bkeep_munmap: 0x87b36f000-0x87b373000
[     1] bkeep_unmapped: 0x87b358000-0x87b367000 => slab
[     1] bkeep_munmap: 0x87b367000-0x87b36f000
[     1] bkeep_unmapped: 0x87b375000-0x87b376000 => slab
[     1] bkeep_unmapped: 0x87b374000-0x87b375000 => slab
[     1] bkeep_unmapped: 0x87b373000-0x87b374000 => slab
[     1] bkeep_unmapped: 0x87b372000-0x87b373000 => slab
[     1] bkeep_unmapped: 0x87b371000-0x87b372000 => slab
[     1] bkeep_unmapped: 0x87b370000-0x87b371000 => slab
[     1] bkeep_unmapped: 0x87b36f000-0x87b370000 => slab
[     1] bkeep_unmapped: 0x87b36e000-0x87b36f000 => slab
[     1] bkeep_unmapped: 0x87b36d000-0x87b36e000 => slab
[     1] bkeep_unmapped: 0x87b36c000-0x87b36d000 => slab
[     1] bkeep_unmapped: 0x87b36b000-0x87b36c000 => slab
[     1] bkeep_unmapped: 0x87b36a000-0x87b36b000 => slab
[     1] bkeep_unmapped: 0x87b369000-0x87b36a000 => slab
[     1] bkeep_munmap: 0x87b358000-0x87b367000
[     1] bkeep_unmapped: 0x87b368000-0x87b369000 => slab
[     1] bkeep_unmapped: 0x87b367000-0x87b368000 => slab
[     1] bkeep_unmapped: 0x87b366000-0x87b367000 => slab
[     1] bkeep_unmapped: 0x87b365000-0x87b366000 => slab
[     1] complete checkpointing data
[     1] bkeep_munmap: 0x87b365000-0x87b366000
[     1] bkeep_munmap: 0x87b366000-0x87b367000
[     1] bkeep_munmap: 0x87b367000-0x87b368000
[     1] bkeep_munmap: 0x87b368000-0x87b369000
[     1] bkeep_munmap: 0x87b369000-0x87b36a000
[     1] bkeep_munmap: 0x87b36a000-0x87b36b000
[     1] bkeep_munmap: 0x87b36b000-0x87b36c000
[     1] bkeep_munmap: 0x87b36c000-0x87b36d000
[     1] bkeep_munmap: 0x87b36d000-0x87b36e000
[     1] bkeep_munmap: 0x87b36e000-0x87b36f000
[     1] bkeep_munmap: 0x87b36f000-0x87b370000
[     1] bkeep_munmap: 0x87b370000-0x87b371000
[     1] bkeep_munmap: 0x87b371000-0x87b372000
[     1] bkeep_munmap: 0x87b372000-0x87b373000
[     1] bkeep_munmap: 0x87b373000-0x87b374000
[     1] bkeep_munmap: 0x87b374000-0x87b375000
[     1] bkeep_munmap: 0x87b375000-0x87b376000
[     1] bkeep_munmap: 0x87b376000-0x87b378000
[     1] checkpoint of 8315002 bytes created, 0 microsecond is spent.
[P00022] bkeep_mmap: 0x875378000-0x875b67000
[P00022] checkpoint mapped at 0x875378000-0x875b6607a
[     1] bkeep_munmap: 0x875378000-0x879378000
[P00022] 8315002 bytes read on stream
[P00022] receive handles: 4 entries

but nothing is happening, its like this for minutes, app clearly doesn't run, CPU usage also none ... what's going on?

**Comment by dimakuv** [comment]
I see that you have two processes, `[1]` forking the `[P00022]`.

It looks like the first process created the child and sent the checkpoint to the child. The child was able to read it and started applying it on itself. But then it went into infinite loop? What do you see as host processes (via `top`/`htop`/`ps`)? Maybe one process silently died, and the other is waiting for it to reply? Do you have both processes with `loader.debug_type = inline`?

In any case, multi-process applications must always have the same `sgx.enclave_size` (!!!) and `sgx.static_address = 1`. Please ensure that's the case.

**Comment by fixerivan** [comment]
got sgx.enclave_size and also sgx.static_address = 1

running loader.debug_type = inline 

htop doesn't show any cpu activity

i am getting this behavior on any "graphical app" i try ... did you ever try to run for example firefox in graphene-sgx with X server accessed over network?

**Comment by dimakuv** [comment]
We haven't tried to run graphical apps. Running a behemoth like Firefox or Chromium is interesting but surely there are some bugs/special cases in Graphene that will result in hangs like you observe. Such applications require a lot of debugging...

Please keep us in loop if you have any progress on this. Otherwise, you may want to wait for/actively help with bug fixes.

**Comment by fixerivan** [comment]
btw - xeyes works if you want a GUI demo on graphene-sgx :) just use X server over network

**Comment by mkow** [comment]
Seems this issue is dead, closing.
@fixerivan Feel free to reopen if you're still interested in making this work.
