### ISSUE TITLE
Manual code review finds 35 vulnerabilities in 8 enclave SDKs

### ISSUE THREAD

**Issue by bgrieder** [oscarlab/graphene#1144]
Hi,

https://www-zdnet-com.cdn.ampproject.org/c/s/www.zdnet.com/google-amp/article/manual-code-review-finds-35-vulnerabilities-in-8-enclave-sdks/

The article says that issues have been privately reported to you. 
Do you have an ETA (and/or comments) on this ?

(it would be nice that you start a Slack - or equivalent - channel to discuss things likes this)

**Comment by dimakuv** [comment]
All the vulnerabilities were reported to us back in April-May 2019. They were **all fixed** in May 2019. The article is a bit misleading, but the paper from these authors mentions both the (private) disclosure and that the vulnerabilities were quickly fixed. See the paper here: https://people.cs.kuleuven.be/~jo.vanbulck/ccs19-tale.pdf.

For an example of a PR fixing these issues, see https://github.com/oscarlab/graphene/pull/622. (It's not the only PR.)

We have this Slack: https://graphene-libraryos.slack.com/. It is used mainly for our internal developer channels but you can join and discuss matters on the `#general` channel.

**Comment by bgrieder** [comment]
@dimakuv Many thanks and excellent news.

**Comment by dimakuv** [comment]
A wrote a detailed explanation on the authors' github: https://github.com/jovanbulck/0xbadc0de/issues/1. Hope this helps others.
