### ISSUE TITLE
disable all restrictions

### ISSUE THREAD

**Issue by fixerivan** [oscarlab/graphene#1149]
is there a way to disable all restrictions? aka trust all files, allow everything? for testing purposes only ...

**Comment by dimakuv** [comment]
Yes, there is:
```
sgx.file_check_policy=[strict|allow_all_but_log]
(Default: strict)
```

So you can set `sgx.file_check_policy = allow_all_but_log` in your manifest and check the output :) Very helpful.

We usually update such info on the manifest syntax here: https://github.com/oscarlab/graphene/blob/master/Documentation/oldwiki/Graphene-SGX-Manifest-Syntax.md.

**Comment by fixerivan** [comment]
thanks somehow i overlooked it in the wiki
