### ISSUE TITLE
[LibOS/shim/test/apps/python] run fail

### ISSUE THREAD

**Issue by sqq0216** [oscarlab/graphene#1153]
Env: Ubuntu 16.04

cd LibOS/shim/test/apps/python
make SGX=1
make SGX=1 sgx-tokens
./python.manifest.sgx scripts/helloworld.py

*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Unknown or illegal instruction at RIP 0x000000000bcd5cc7
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. *** 
(vector = 0x6, type = 0x3 valid = 1, RIP = +0x00027cc7)
rax: 0xffffffe0 rcx: 0x0fee36e0 rdx: 0x00000000 rbx: 0x0ffe6318
rsp: 0x0ffe6250 rbp: 0x0ffe6250 rsi: 0x0fee3230 rdi: 0x0bee2980
r8 : 0x0fee42e0 r9 : 0x0fee3ee0 r10: 0x0fee43e0 r11: 0x0fee47e0
r12: 0x00000010 r13: 0x0fee3230 r14: 0x0bee85f0 r15: 0x00000000
rflags: 0x00010247 rip: 0x0bcd5cc7

I saw an other similer problem on issues, and the suggestion is look through the complete log, if what I should do is so I want to know where is the log, I have found a build.log in graphene/LibOS/ but can't look for a memory region containing 0x000000000bcd5cc7 in the log,  are there other log files or other suggestions?
thanks!

**Comment by dimakuv** [comment]
We are preparing a new version of the Python example (actually, there will be two examples): https://github.com/oscarlab/graphene-tests/pull/29. This is work in progress, but it will be merged soon.

So please ignore the current old version of the Python example.

P.S. As to your question about the log, you should put `loader.debug_type = inline` in your manifest. This will force Graphene to output a log of everything it does. This is the log we meant.

**Comment by sqq0216** [comment]
When I use Graphene_SGX to run application there always is a error:

*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Unknown or illegal instruction at RIP 0x000000000bcd5cc7
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. ***
(vector = 0x6, type = 0x3 valid = 1, RIP = +0x00027cc7)
rax: 0xffffffe0 rcx: 0x0fee36e0 rdx: 0x00000000 rbx: 0x0ffe6318
rsp: 0x0ffe6250 rbp: 0x0ffe6250 rsi: 0x0fee3230 rdi: 0x0bee2980
r8 : 0x0fee42e0 r9 : 0x0fee3ee0 r10: 0x0fee43e0 r11: 0x0fee47e0
r12: 0x00000010 r13: 0x0fee3230 r14: 0x0bee85f0 r15: 0x00000000
rflags: 0x00010247 rip: 0x0bcd5cc7

I want to know if there need AES-NI instructions, my PC doesn't support the AES-NI,  Is this  error  related to it？
thanks!

**Comment by dimakuv** [comment]
I don't think Graphene *requires* AES-NI. Where do you see this error? Does it pop up on every application you try, even HelloWorld? What logs do you see when you do `loader.debug_type = inline` in your manifest.template?

Also, can you find another machine with AES-NI and try the same workload on that machine? Then you'll know whether it is about AES-NI (which I doubt) or something else.

**Comment by mkow** [comment]
No response from the reporter, closing (also, the issue seems to be outdated now).
