### ISSUE TITLE
[LibOS/shim/test/benchmark] Need modify Makefile and manifest.template

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1156]
Compile:
#cd graphene LibOS/shim/test/benchmark 
#make SGX=1 sgx-tokens  
make: Nothing to be done for 'sgx-tokens'.

To fix it:
#diff Makefile
-target = $(c_executables) $(cxx_executables) \\
         manifest
+exec_target = $(c_executables) $(cxx_executables) \\
         manifest

Compile:
#make SGX=1 clean
#make SGX=1
#make SGX=1 sgx-tokens

Run:
#./pal_loader SGX <benchmark>
Accessing file:../../../../Runtime/ld-linux-x86-64.so.2 is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:../../../../Runtime/libc.so.6 is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:../../../../Runtime/liblibos.so.1 is denied. (Unknown error) This file is not trusted or allowed.

To fix it:
#diff manifest.template
+sgx.trusted_files.ld = file:..//../../../Runtime/ld-linux-x86-64.so.2
+sgx.trusted_files.libc = file:..//../../../Runtime/libc.so.6
+sgx.trusted_files.liblibos = file:..//../../../Runtime/liblibos.so.1

**Comment by mkow** [comment]
FYI: This directory will be removed soon, we're reworking all the benchmarks.

**Comment by mkow** [comment]
This directory was removed, closing.
