### ISSUE TITLE
Graphene on QubeOS ?

### ISSUE THREAD

**Issue by bgrieder** [oscarlab/graphene#1165]
Hello,

@woju Does Graphene run on QubeOS ?
If yes, Is there any particular install procedure to follow to make it run inside a Qube VM?

Many Thanks

**Comment by woju** [comment]
> @woju Does Graphene run on QubeOS ?
> If yes, Is there any particular install procedure to follow ?

Please do not use issues tracker to ask questions. This is what Slack is for.
If you don't have access, see https://grapheneproject.io/#section-contact and
ask for invitation via email.

To answer question: we don't have any particular procedure. For graphene
development we use dedicated machines without Qubes OS.

**Comment by bgrieder** [comment]
>  Please do not use issues tracker to ask questions. This is what Slack is for.
OK

> For graphene development we use dedicated machines without Qubes OS.
OK. But this does not really answer the question unless you meant you *never* tried running it on QubeOS. 
Moving to Slack
