### ISSUE TITLE
Graphene-SGX manifests should support chroot-mounts on root directory

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1179]
The feature should support the following configuration in GSGX manifest.
> fs.mount.root.type = chroot
> fs.mount.root.path = /
> fs.mount.root.uri = file:///
This way is able to allow GSGX to mount the specified root directory by chroot as default fs used by application running inside enclave. Thanks.

**Comment by dimakuv** [comment]
Strange, I had a feeling it already worked that way. Is there an error/hang when specifying this in the manifest for say HelloWorld or Redis examples?

**Comment by bigdata-memory** [comment]
> Strange, I had a feeling it already worked that way. Is there an error/hang when specifying this in the manifest for say HelloWorld or Redis examples?

Thanks for the information.

**Comment by dimakuv** [comment]
I made a quick test on Memcached. Indeed, Graphene-SGX *theoretically* allows mounting a root dir, but in practice it leads to breaking our assumptions on mount points and clashing with other directories.

In particular:
1. Stuff like  `fs.mount.lib.path = /lib; fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime` overlaps with the root directory, and it confuses Graphene. This results in segfaults and failed asserts like `assert failed shim_syscalls.c:431 preempt == get_cur_preempt()`.
2. Pseudo-FSes like `/proc` and `/sys` are emulated in Graphene. These pseudo-FSes also overlap with the root directory, and it results in weird errors like `Accessing file:/dev/tty is denied`.

To correct implement such a feature, we need to have a way to remove certain subdirs from the root directory...

**Comment by bigdata-memory** [comment]
> I made a quick test on Memcached. Indeed, Graphene-SGX _theoretically_ allows mounting a root dir, but in practice it leads to breaking our assumptions on mount points and clashing with other directories.
> 
> In particular:
> 
> 1. Stuff like  `fs.mount.lib.path = /lib; fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime` overlaps with the root directory, and it confuses Graphene. This results in segfaults and failed asserts like `assert failed shim_syscalls.c:431 preempt == get_cur_preempt()`.
> 2. Pseudo-FSes like `/proc` and `/sys` are emulated in Graphene. These pseudo-FSes also overlap with the root directory, and it results in weird errors like `Accessing file:/dev/tty is denied`.
> 
> To correct implement such a feature, we need to have a way to remove certain subdirs from the root directory...

Thank you for the analysis

**Comment by dimakuv** [comment]
Ok, Graphene supports a special `fs.root` syntax in the manifest, so host-root FS actually (almost) works. See PR https://github.com/oscarlab/graphene/pull/1209. I'll need to run more tests with real-world applications to iron out other bugs if any.
