### ISSUE TITLE
LTP "pipe05" fails with debug=inline

### ISSUE THREAD

**Issue by boryspoplawski** [oscarlab/graphene#1189]
Setting `loader.debug_type = inline` makes "pipe05" from LTP segfault.
This test checks for invalid argument passed to `pipe` - a non-existent address (just NULL, I believe). Inline debug enables syscall argument parsing, which for pipe does:
```
static void parse_pipe_fds(va_list ap) {
    int* fds = va_arg(ap, int*);

    PRINTF("[%d, %d]", fds[0], fds[1]);
}
```
i.e. it dereferences the provided address causing a segfault.
On the normal path `pipe` check for the validity of address, but that's inside the syscall handler itself, which runs after argument parsing in debug mode.

**Comment by dimakuv** [comment]
A couple months ago, I tried to patch all such occurrences in this PR: https://github.com/oscarlab/graphene/pull/715. Apparently, I failed to notice this case of `parse_pipe_fds()`. Basically, it's just a matter of checking `test_user_memory(fds ... )` before doing the deference.

Looking at `shim_parser.c`, this looks like the only non-hardened function left. Could you submit a PR with a fix? Sounds simple.
