### ISSUE TITLE
How to call sgx functions in graphene?

### ISSUE THREAD

**Issue by FrankZhangCN** [oscarlab/graphene#1190]
I am trying to build some applications utilizing TensorFlow and local attestation.
But I did not find any information about how to call sgx functions, e.g., sgx_dh_initiator_proc_msg3, in graphene?
Has graphene provided such APIs?

**Comment by FrankZhangCN** [comment]
I added 
`-I/opt/intel/sgxsdk/include -L/opt/intel/sgxsdk/lib64 -Wl,--start-group -lsgx_tservice -lsgx_trts -lsgx_tcrypto -lsgx_tstdc -Wl,--end-group -Wl,--defsym,__ImageBase=0` to the makefile. But finally, I got some errors:
`undefined reference to `g_ecall_table'` and `undefined reference to `g_dyn_entry_table'`
`

**Comment by dimakuv** [comment]
Graphene does not provide any APIs to call SGX-specific functions. Please note that Graphene has *no* connection to SGX SDK, and thus trying to add SGX SDK's libraries will fail.

Graphene is just not the right tool for your use case (at least for now).

**Comment by FrankZhangCN** [comment]
Get it. Thank you for your reply.
