### ISSUE TITLE
[LibOS/shim/test/apps/apache] "SGX=1 make start-graphene-server" not work under SGX

### ISSUE THREAD

**Issue by TomTanJun** [oscarlab/graphene#1193]
It prints out the error message:

file_map does not currently support writable pass-through mappings on SGX.  You may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep the writes inside the enclave but they won't be reflected outside of the enclave.

**Comment by TomTanJun** [comment]
And this error:
Listen on 127.0.0.1:8001
./pal_loader httpd.manifest -D FOREGROUND \
        -f conf/httpd-graphene.conf \
        -C "LoadModule mpm_prefork_module modules/mod_mpm_prefork.so" \
        -C "Listen 127.0.0.1:8001" \
        -C "ServerName 127.0.0.1" \
        -C "PidFile logs/httpd-127.0.0.1-8001.pid"
[Mon Dec 02 12:04:05.578261 2019] [core:warn] [pid 1] (92)Protocol not available: AH00076: Failed to enable APR_TCP_DEFER_ACCEPT

**Comment by dimakuv** [comment]
These are not errors but warnings. Have you tried accessing the server via some client (`ab`, `curl`, `wget`)? Does the server die?

**Comment by TomTanJun** [comment]
> These are not errors but warnings. Have you tried accessing the server via some client (`ab`, `curl`, `wget`)? Does the server die?

You are right. These are just warnings. The server doesn't die, the client can link to the server.
