### ISSUE TITLE
[Graphene SGX driver]Should set vm.mmap_min_addr instead of vm.mmap_min

### ISSUE THREAD

**Issue by mangohero** [oscarlab/graphene#1198]
When building the Graphene SGX driver under [Building with Intel SGX Support], the instruction gives:
cd Pal/src/host/Linux-SGX/sgx-driver
make
sudo ./load.sh
**sudo sysctl vm.mmap_min = 0**

But sysctl cannot acquire the stat of /proc/sys/vm/mmap_min, cus there is no such file.

Instead, the command should be:
**sudo sysctl vm.mmap_min_addr=0**
or **sudo sysctl -w vm.mmap_min_addr=0** if a temporary change is preferred.

**Comment by dimakuv** [comment]
Thank you for reporting this! This will be fixed in PR https://github.com/oscarlab/graphene/pull/1200.
