### ISSUE TITLE
Build sgx-driver issues

### ISSUE THREAD

**Issue by woonhak** [oscarlab/graphene#12]
I'd like to compile sgx-driver in graphene(Pal/src/host/Linux-SGX/sgx-driver)
However, linux-sgx-driver has been changed and removed many symbols such as ISGX_IOCTL_XXX (changed to ISGX_IOC_XXX), isgx_create_param, and ISGX_ADD_SKIP_EEXTEND.
So I can't build and load graphene-sgx driver.

**Comment by somename11111** [comment]
Yup, same problem here.

**Comment by somename11111** [comment]
Seems like the commit which broke things was https://github.com/01org/linux-sgx-driver/commit/63a19a5ac658fd8217c75af7864136ed0db03a72

**Comment by woonhak** [comment]
@somename11111 thanks. That works for me.

**Comment by chiache** [comment]
The current version is compatible with the Intel SDK 1.6 version. We are working on a new version for the new Intel driver APIs. If you are running the current version, please revert the intel-sgx and intel-sgx-driver repositories back to [sgx_1.6](https://github.com/01org/linux-sgx/tree/sgx_1.6) and  [sgx_driver_1.6](https://github.com/01org/linux-sgx-driver/tree/sgx_driver_1.6).

Here's a detailed instruction for cleanly reinstalled the old SDK and driver:


1. uninstall psw:     `sudo /opt/intel/sgxpsw/uninstall.sh`
 

2. update linux-sgx and linux-sgx-driver:

```
cd linux-sgx-driver
git checkout sgx_driver_1.6
make clean
cd ../linux-sgx
git checkout sgx_1.6
make clean
./download_prebuilt.sh
```


3. build and install linux-sgx-driver:
```
cd ../linux-sgx-driver
make
sudo make install
sudo mkdir -p "/lib/modules/"`uname -r`"/kernel/drivers/intel/sgx"
sudo cp isgx.ko "/lib/modules/"`uname -r`"/kernel/drivers/intel/sgx"
sudo sh -c "cat /etc/modules | grep -Fxq isgx || echo isgx >> /etc/modules"
sudo /sbin/depmod $ sudo /sbin/modprobe isgx
```


4. build and install linux-sgx:
```
cd ../linux-sgx
make
make psw_install_pkg
make sdk_install_pkg
cd linux/installer/bin
sudo ./sgx_linux_x64_psw_1.6.100.34922.bin
sudo ./sgx_linux_x64_sdk_1.6.100.34922.bin
```


5. rebuild and test Graphene

```
cd ../../../../Graphene/Pal/src
make clean
make SGX=1
cd host/Linux-SGX/sgx-driver
make clean
make
sudo ./load.sh
cd ../../../../test
make clean
make SGX=1
make SGX_RUN=1
../src/pal HelloWorld
```

**Comment by donporter** [comment]
The latest HEAD should now work with the latest SGX driver, FYI.
