### ISSUE TITLE
Sealing

### ISSUE THREAD

**Issue by Khallu** [oscarlab/graphene#1211]
Hello All,

I'd like to know if Sealing for graphene is in the roadmap. If not, some guidance on how to go about it would help. 

I did check out adombeck's python-sgx implementation, although it's insightful that's not the ideal path I wish to follow.

Thanks

**Comment by mkow** [comment]
What do you mean by "Sealing for graphene", exactly?

**Comment by Khallu** [comment]
I want to know how it'd be possible to seal files corresponding to an enclave and then when the enclave is run, the sealed files automatically are unsealed in runtime (by pointing the sealed files in the manifest? or mapping them some other way)

**Comment by Khallu** [comment]
@mkow Please let me know if you have any ideas.

**Comment by dimakuv** [comment]
@Khallu This is currently not supported. We are currently in the process of reviewing the "Protected FS" PR: https://github.com/oscarlab/graphene/pull/1090. You can take a look at it for inspiration, if you want to modify Graphene for your purposes.

**Comment by Khallu** [comment]
Okay, thanks @dimakuv

**Comment by Khallu** [comment]
Hey @dimakuv how can I approach accessing the seal keys from the sdk to replace the pf-encryption-key?

**Comment by dimakuv** [comment]
This is a question for @sudharkrish and @omeg.

**Comment by Khallu** [comment]
Thanks for pointing out @dimakuv . Hey @sudharkrish & @omeg I'm trying to use the sealing functionality in graphene in the same manner as the protected files system. I'm trying to figure out how i can access the seal keys through graphene
