### ISSUE TITLE
Malformed request received (May be forged for attack)

### ISSUE THREAD

**Issue by dirknono** [oscarlab/graphene#1228]
I have added my linkable SPID and API key in the manifest template and tried to run the app with remote attestation. 
It somehow works and my IAS webpage shows that the call is successful. 
But when I check the status of the local aesm service, it gives:

aesm_service[3628]: Malformed request received (May be forged for attack)

Doesn't look well though... Can somebody help me out?

Thank you!

**Comment by dimakuv** [comment]
@dirknono , could you provide more info?

Are you experiencing issues with remote attestation under Graphene-SGX or Intel SGX SDK?

What exactly are you running? What happens if you run a Remote Attestation sample application shipped with Intel SGX SDK? Does the AESM service still complain?

What do you mean by "my IAS webpage shows that the call is successful"? I probably just don't know about this; is there an interactive dashboard provided by IAS or logs you can look at?

What are the versions of (1) Graphene (which commit/release from which date), (2) Intel SGX Driver, (3) Intel SGX SDK/PSW, (4) your OS distribution? Note that we recommend using Intel SGX Driver + SDK/PSW of version 2.4+.

It could be that the AESM version you're using has an incompatible protocol with Graphene-SGX (at some point there was a switch in the internal protocol, but versions 2.4+ should work).

**Comment by dirknono** [comment]
Sure.

This is an issue with Graphene-SGX, and I am running the native sample code (e.g., time, helloword).
When I am using other samples with Intel SGX, the AESM doesn't complain any more.

For IAS, I get the result from https://api.portal.trustedservices.intel.com/Developer/Analytics, the web dashboard provided by IAS.

For versions of Graphene and SGX driver/SDK/PSW, I use all the latest version (directly cloned from github), and my OS is ubuntu 18.04.

**Comment by dimakuv** [comment]
For an experiment, could you uninstall your current SGX SDK/PSW and re-install the version 2.4 (https://github.com/intel/linux-sgx/tree/sgx_2.4)?

The culprit seems to be an incorrect AESM message header (encoded in Google protobuf format). See the code: https://github.com/intel/linux-sgx/blob/d10cabebb5512878e84f5d21cdf27c39c428ffe2/psw/ae/aesm_service/source/core/AESMQueueManager.cpp.

I wonder if the SGX SDK/PSW internal AESM messaging format diverged from what we have in Graphene-SGX... (We build our own messages, see https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/quote/aesm.proto). Also, could you attach your auto-generated files `Pal/src/host/Linux-SGX/quote/aesm.pb-c.h` and `Pal/src/host/Linux-SGX/quote/aesm.pb-c.c` (they are generated in https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/Makefile).

**Comment by dimakuv** [comment]
By the way, it also could be a wrong version of Google Protobuf compiler installed on your OS. Check these issues:
- https://github.com/intel/linux-sgx/issues/328
- https://github.com/intel/linux-sgx/issues/131

Seems like you may be using an unsupported/buggy version of Protobuf (e.g., v3 seems to be not supported at all).

**Comment by dirknono** [comment]
The two files you mentioned, Pal/src/host/Linux-SGX/quote/aesm.pb-c.h:

**Comment by dirknono** [comment]
The two files you mentioned, Pal/src/host/Linux-SGX/quote/aesm.pb-c.h:
/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: quote/aesm.proto */

#ifndef PROTOBUF_C_quote_2faesm_2eproto__INCLUDED
#define PROTOBUF_C_quote_2faesm_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Request Request;
typedef struct _Request__InitQuoteRequest Request__InitQuoteRequest;
typedef struct _Request__GetQuoteRequest Request__GetQuoteRequest;
typedef struct _Response Response;
typedef struct _Response__InitQuoteResponse Response__InitQuoteResponse;
typedef struct _Response__GetQuoteResponse Response__GetQuoteResponse;


/* --- enums --- */


/* --- messages --- */

struct  _Request__InitQuoteRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timeout;
  uint32_t timeout;
};
#define REQUEST__INIT_QUOTE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__init_quote_request__descriptor) \
    , 0,0 }


struct  _Request__GetQuoteRequest
{
  ProtobufCMessage base;
  ProtobufCBinaryData report;
  uint32_t quote_type;
  ProtobufCBinaryData spid;
  protobuf_c_boolean has_nonce;
  ProtobufCBinaryData nonce;
  protobuf_c_boolean has_sig_rl;
  ProtobufCBinaryData sig_rl;
  uint32_t buf_size;
  protobuf_c_boolean has_qe_report;
  protobuf_c_boolean qe_report;
  protobuf_c_boolean has_timeout;
  uint32_t timeout;
};
#define REQUEST__GET_QUOTE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__get_quote_request__descriptor) \
    , {0,NULL}, 0, {0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0, 0,0, 0,0 }


struct  _Request
{
  ProtobufCMessage base;
  Request__InitQuoteRequest *initquotereq;
  Request__GetQuoteRequest *getquotereq;
};
#define REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request__descriptor) \
    , NULL, NULL }


struct  _Response__InitQuoteResponse
{
  ProtobufCMessage base;
  uint32_t errorcode;
  protobuf_c_boolean has_targetinfo;
  ProtobufCBinaryData targetinfo;
  protobuf_c_boolean has_gid;
  ProtobufCBinaryData gid;
};
#define RESPONSE__INIT_QUOTE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__init_quote_response__descriptor) \
    , 1u, 0,{0,NULL}, 0,{0,NULL} }


struct  _Response__GetQuoteResponse
{
  ProtobufCMessage base;
  uint32_t errorcode;
  protobuf_c_boolean has_quote;
  ProtobufCBinaryData quote;
  protobuf_c_boolean has_qe_report;
  ProtobufCBinaryData qe_report;
};
#define RESPONSE__GET_QUOTE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__get_quote_response__descriptor) \
    , 1u, 0,{0,NULL}, 0,{0,NULL} }


struct  _Response
{
  ProtobufCMessage base;
  Response__InitQuoteResponse *initquoteres;
  Response__GetQuoteResponse *getquoteres;
};
#define RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__descriptor) \
    , NULL, NULL }


/* Request__InitQuoteRequest methods */
void   request__init_quote_request__init
                     (Request__InitQuoteRequest         *message);
/* Request__GetQuoteRequest methods */
void   request__get_quote_request__init
                     (Request__GetQuoteRequest         *message);
/* Request methods */
void   request__init
                     (Request         *message);
size_t request__get_packed_size
                     (const Request   *message);
size_t request__pack
                     (const Request   *message,
                      uint8_t             *out);
size_t request__pack_to_buffer
                     (const Request   *message,
                      ProtobufCBuffer     *buffer);
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator);
/* Response__InitQuoteResponse methods */
void   response__init_quote_response__init
                     (Response__InitQuoteResponse         *message);
/* Response__GetQuoteResponse methods */
void   response__get_quote_response__init
                     (Response__GetQuoteResponse         *message);
/* Response methods */
void   response__init
                     (Response         *message);
size_t response__get_packed_size
                     (const Response   *message);
size_t response__pack
                     (const Response   *message,
                      uint8_t             *out);
size_t response__pack_to_buffer
                     (const Response   *message,
                      ProtobufCBuffer     *buffer);
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Request__InitQuoteRequest_Closure)
                 (const Request__InitQuoteRequest *message,
                  void *closure_data);
typedef void (*Request__GetQuoteRequest_Closure)
                 (const Request__GetQuoteRequest *message,
                  void *closure_data);
typedef void (*Request_Closure)
                 (const Request *message,
                  void *closure_data);
typedef void (*Response__InitQuoteResponse_Closure)
                 (const Response__InitQuoteResponse *message,
                  void *closure_data);
typedef void (*Response__GetQuoteResponse_Closure)
                 (const Response__GetQuoteResponse *message,
                  void *closure_data);
typedef void (*Response_Closure)
                 (const Response *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor request__descriptor;
extern const ProtobufCMessageDescriptor request__init_quote_request__descriptor;
extern const ProtobufCMessageDescriptor request__get_quote_request__descriptor;
extern const ProtobufCMessageDescriptor response__descriptor;
extern const ProtobufCMessageDescriptor response__init_quote_response__descriptor;
extern const ProtobufCMessageDescriptor response__get_quote_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_quote_2faesm_2eproto__INCLUDED */

**Comment by dirknono** [comment]
Pal/src/host/Linux-SGX/quote/aesm.pb-c.c:

/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: quote/aesm.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "quote/aesm.pb-c.h"
void   request__init_quote_request__init
                     (Request__InitQuoteRequest         *message)
{
  static Request__InitQuoteRequest init_value = REQUEST__INIT_QUOTE_REQUEST__INIT;
  *message = init_value;
}
void   request__get_quote_request__init
                     (Request__GetQuoteRequest         *message)
{
  static Request__GetQuoteRequest init_value = REQUEST__GET_QUOTE_REQUEST__INIT;
  *message = init_value;
}
void   request__init
                     (Request         *message)
{
  static Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init_quote_response__init
                     (Response__InitQuoteResponse         *message)
{
  static Response__InitQuoteResponse init_value = RESPONSE__INIT_QUOTE_RESPONSE__INIT;
  *message = init_value;
}
void   response__get_quote_response__init
                     (Response__GetQuoteResponse         *message)
{
  static Response__GetQuoteResponse init_value = RESPONSE__GET_QUOTE_RESPONSE__INIT;
  *message = init_value;
}
void   response__init
                     (Response         *message)
{
  static Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__init_quote_request__field_descriptors[1] =
{
  {
    "timeout",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Request__InitQuoteRequest, has_timeout),
    offsetof(Request__InitQuoteRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__init_quote_request__field_indices_by_name[] = {
  0,   /* field[0] = timeout */
};
static const ProtobufCIntRange request__init_quote_request__number_ranges[1 + 1] =
{
  { 9, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor request__init_quote_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.InitQuoteRequest",
  "InitQuoteRequest",
  "Request__InitQuoteRequest",
  "",
  sizeof(Request__InitQuoteRequest),
  1,
  request__init_quote_request__field_descriptors,
  request__init_quote_request__field_indices_by_name,
  1,  request__init_quote_request__number_ranges,
  (ProtobufCMessageInit) request__init_quote_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__get_quote_request__field_descriptors[8] =
{
  {
    "report",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quote_type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, quote_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "spid",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, spid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nonce",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Request__GetQuoteRequest, has_nonce),
    offsetof(Request__GetQuoteRequest, nonce),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sig_rl",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Request__GetQuoteRequest, has_sig_rl),
    offsetof(Request__GetQuoteRequest, sig_rl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "buf_size",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request__GetQuoteRequest, buf_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qe_report",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Request__GetQuoteRequest, has_qe_report),
    offsetof(Request__GetQuoteRequest, qe_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Request__GetQuoteRequest, has_timeout),
    offsetof(Request__GetQuoteRequest, timeout),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__get_quote_request__field_indices_by_name[] = {
  5,   /* field[5] = buf_size */
  3,   /* field[3] = nonce */
  6,   /* field[6] = qe_report */
  1,   /* field[1] = quote_type */
  0,   /* field[0] = report */
  4,   /* field[4] = sig_rl */
  2,   /* field[2] = spid */
  7,   /* field[7] = timeout */
};
static const ProtobufCIntRange request__get_quote_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 7 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor request__get_quote_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request.GetQuoteRequest",
  "GetQuoteRequest",
  "Request__GetQuoteRequest",
  "",
  sizeof(Request__GetQuoteRequest),
  8,
  request__get_quote_request__field_descriptors,
  request__get_quote_request__field_indices_by_name,
  2,  request__get_quote_request__number_ranges,
  (ProtobufCMessageInit) request__get_quote_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[2] =
{
  {
    "initQuoteReq",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, initquotereq),
    &request__init_quote_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getQuoteReq",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, getquotereq),
    &request__get_quote_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = getQuoteReq */
  0,   /* field[0] = initQuoteReq */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  2,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t response__init_quote_response__error_code__default_value = 1u;
static const ProtobufCFieldDescriptor response__init_quote_response__field_descriptors[3] =
{
  {
    "errorCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response__InitQuoteResponse, errorcode),
    NULL,
    &response__init_quote_response__error_code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetInfo",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__InitQuoteResponse, has_targetinfo),
    offsetof(Response__InitQuoteResponse, targetinfo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__InitQuoteResponse, has_gid),
    offsetof(Response__InitQuoteResponse, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__init_quote_response__field_indices_by_name[] = {
  0,   /* field[0] = errorCode */
  2,   /* field[2] = gid */
  1,   /* field[1] = targetInfo */
};
static const ProtobufCIntRange response__init_quote_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__init_quote_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.InitQuoteResponse",
  "InitQuoteResponse",
  "Response__InitQuoteResponse",
  "",
  sizeof(Response__InitQuoteResponse),
  3,
  response__init_quote_response__field_descriptors,
  response__init_quote_response__field_indices_by_name,
  1,  response__init_quote_response__number_ranges,
  (ProtobufCMessageInit) response__init_quote_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t response__get_quote_response__error_code__default_value = 1u;
static const ProtobufCFieldDescriptor response__get_quote_response__field_descriptors[3] =
{
  {
    "errorCode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response__GetQuoteResponse, errorcode),
    NULL,
    &response__get_quote_response__error_code__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "quote",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__GetQuoteResponse, has_quote),
    offsetof(Response__GetQuoteResponse, quote),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qe_report",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Response__GetQuoteResponse, has_qe_report),
    offsetof(Response__GetQuoteResponse, qe_report),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__get_quote_response__field_indices_by_name[] = {
  0,   /* field[0] = errorCode */
  2,   /* field[2] = qe_report */
  1,   /* field[1] = quote */
};
static const ProtobufCIntRange response__get_quote_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor response__get_quote_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response.GetQuoteResponse",
  "GetQuoteResponse",
  "Response__GetQuoteResponse",
  "",
  sizeof(Response__GetQuoteResponse),
  3,
  response__get_quote_response__field_descriptors,
  response__get_quote_response__field_indices_by_name,
  1,  response__get_quote_response__number_ranges,
  (ProtobufCMessageInit) response__get_quote_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "initQuoteRes",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, initquoteres),
    &response__init_quote_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "getQuoteRes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, getquoteres),
    &response__get_quote_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = getQuoteRes */
  0,   /* field[0] = initQuoteRes */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};

**Comment by dirknono** [comment]
**For protobuf usage, I just followed what Graphene-SGX github README gives, installing with:
sudo apt-get install -y python3-protobuf libprotobuf-c-dev protobuf-c-compiler**
The current versions of the dependencies are as follows:

root@tencent-NUC7i5BNHXF:~# apt-get install python3-protobuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-protobuf is already the newest version (3.0.0-9.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@tencent-NUC7i5BNHXF:~# apt-get install python3-protobuf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-protobuf is already the newest version (3.0.0-9.1ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@tencent-NUC7i5BNHXF:~# apt-get install protobuf-c-compiler
Reading package lists... Done
Building dependency tree       
Reading state information... Done
protobuf-c-compiler is already the newest version (1.2.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by mkow** [comment]
@dirknono Does your problem still occur on the current master? Does it happen also with non-Graphene applications which use SGX?

**Comment by mkow** [comment]
No reply for quite some time, closing (and seems to be an SGX setup problem, not a Graphene issue).

**Comment by dirknono** [comment]
> @dirknono Does your problem still occur on the current master? Does it happen also with non-Graphene applications which use SGX?

thanks. the problem doesn't occur for now.
