### ISSUE TITLE
[Linux-SGX] remote attestation: need a way to bypass CONFIGURATION_NEEDED

### ISSUE THREAD

**Issue by lejunzhu** [oscarlab/graphene#1231]
There is already an option to bypass the GROUP_OUT_OF_DATE status returned from IAS, but not the CONFIGURATION_NEEDED status. According to the document:

> CONFIGURATION_NEEDED - The EPID signature of the ISV enclave QUOTE has been verified correctly, but additional configuration of SGX platform may be needed (for further details see Advisory IDs). The platform has not been identified as compromised and thus it is not revoked. It is up to the Service Provider to decide whether or not to trust the content of the QUOTE, and whether or not to trust the platform performing the attestation to protect specific sensitive information.

When such status is returned, PAL always ends the process. I suggest that when ra_accept_group_out_of_date is set, CONFIGURATION_NEEDED is bypassed as well.

**Comment by dimakuv** [comment]
@lejunzhu, could you check if this PR helps: https://github.com/oscarlab/graphene/pull/1232 ?

**Comment by lejunzhu** [comment]
> @lejunzhu, could you check if this PR helps: #1232 ?

I just tested #1232 and it works fine on my machine. Thanks for the help.

**Comment by dimakuv** [comment]
@lejunzhu Thanks for testing, we'll merge this PR soon-ish.
