### ISSUE TITLE
GSCE cannot read files in Runtime/

### ISSUE THREAD

**Issue by Khallu** [oscarlab/graphene#1234]
The following comand in the generated Dockerfile causes the issue: 

```
RUN cd /home/khallu/_dev/core/graphene/LibOS/shim/test/apps/secureapp && \
    /home/khallu/_dev/core/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal /home/khallu/_dev/core/graphene/Pal/src/host/Linux-SGX/../../../../Runtime/libpal-Linux-SGX.so -key /home/khallu/_dev/core/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output secureapp.manifest.sgx -manifest secureapp.manifest
```
The above signing step returns :
FileNotFoundError: [Errno 2] No such file or directory: '/home/khallu/_dev/core/graphene/Runtime/libsysdb.so'

I removed this command the dockerfile, logged in the docker to check the file was accessible, through a python shell. And they were. I also tried modifying the pal-sgx-sign to list the files in the directory. Which showed me all the files. Finally, I also checked whether the file were broken before it was copied to the image & they were fine. 

Any help would be appreciated. Thanks.

**Comment by dimakuv** [comment]
This can be due to the fact that most files under `graphene/Runtime/` are symbolic links. From the README of GSCE:
```
1) Graphene is having trouble handling the symbolic links in graphene/Runtime
	- For some reason Graphene doesn't read symbolic links in certain instances. You will need to replace all of the links with a copy of the actual files with the same name to the Runtime folder. Rather than doing this manually (more painful than you may think) use this trick:
	- `shopt -s globstar` <-- enables globstar option
	- `sed -i '' **/*` <-- replaces all of the links
```

So you can go and replace all symlinks (including your failing `libsysdb.so`) with actual files and try again.

But please note that **GSCE is known to not work properly and is deprecated**. There will be a complete rewrite of Docker support.

**Comment by mkow** [comment]
As @dimakuv said, GSC is deprecated, and was even removed from the current master recently (see https://github.com/oscarlab/graphene/pull/1242). We are working right now on a better solution.
