### ISSUE TITLE
[Linux-SGX] Encrypted IPC

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1235]
This is a design document for encrypted IPC in Graphene-SGX.

# General

Previously, Graphene-SGX performed all Inter-Process Communication (between SGX enclaves) in plaintext. In particular, these IPC mechanisms are vulnerable to attacks due to lack of integrity and encryption:

1. Process checkpoint send/receive.
2. Process inheritance of host resources (file descriptors in Linux-SGX), implemented via [sendmsg/recvmsg](https://sumitomohiko.wordpress.com/2015/09/24/file-descriptor-passing-with-sendmsg2-and-recvmsg2-over-unix-domain-socket/).
3. Communication over pipes and socketpairs.
4. Communication over multicast (*Update: this is removed from Graphene completely*).

We want to have robust, minimal, encrypted and integrity-verified IPC communication. Design principles are:
1. Encapsulate all modifications in Linux-SGX PAL. There is no reason to introduce it at other levels (LibOS, generic PAL, other non-secure PALs).
2. Use a minimalistic crypto mechanism. We must use established crypto instead of implementing our own ad-hoc mechanism (read: TLS).
3. Re-use already-existing mutual local SGX attestation between enclaves (see #332). In other words, use TLS-PSK (Pre-Shared Keys).
4. Start small.

# Implementation

We currently build on mbedTLS-provided TLS-PSK (without DH) chipersuite: `MBEDTLS_TLS_PSK_WITH_AES_128_GCM_SHA256`. Since every pair of SGX enclaves creates a new shared key via SGX local attestation, there is no need for additional forward secrecy.

- [x] **Process checkpoint send/receive.** Implemented in PR #1229.
- [ ] **Process inheritance of host resources.** This is probably not needed because the host OS already knows basically all metadata on host resources. But we must carefully sanitize PAL handle metadata sent from parent to child (see #1229 for an example of shared-key sanitization).
- [ ] **Communication over pipes and socketpairs.** In Graphene, pipes are emulated via socketpairs, so implementation boils down to hardening socketpairs. Two issues: (1) cannot share socketpairs among 3+ enclaves; (2) need to establish new TLS-PSK connection when host socketpair is inherited via fork/clone. *Need to discuss!*
- [x] **Communication over multicast.** Could this be simply removed from Graphene?

# Crypto Details

- We use the current implementation of Pal-lib's crypto adapters. At this point, it starts dangerously growing in complexity. Not sure if we need to have a clearer way of introducing TLS-PSK.

- We cannot use host-based sources of entropy (e.g. `dev/random`) because the host is malicious. The only source of entropy then is whatever is provided by the CPU. We use the following in mbedTLS:
```
#define MBEDTLS_ENTROPY_HARDWARE_ALT  /* use mbedtls_hardware_poll() */
#define MBEDTLS_NO_PLATFORM_ENTROPY  /* do not use host-based sources */

/* mbedTLS entropy logic expects this function where we use rdrand x86 instruction */
int mbedtls_hardware_poll(void* data, unsigned char* output, size_t len, size_t* olen) {
    for (size_t i = 0; i < len; i += 8) {
        unsigned long long rand64;
        while (__builtin_ia32_rdrand64_step(&rand64) == 0) /*nop*/;
        memcpy(output + i, &rand64, sizeof(rand64));
    }
    *olen = len;
}
```

- We do not use TLS reset or renegotiation. Renegotiation is known to be vulnerable and is excluded from TLS 1.3. Reset is not needed since we expect a benign TLS session between two SGX enclaves on the same machine to never fail.

- Currently, after the checkpoint is sent/received, the parent/child processes downgrade their sockets to plain non-secure ones (by disabling TLS). This is done because child may spawn a grandchild that also wants to communicate with grandparent, but it is impossible for multiple processes to share same TLS context. *TODO: how to fix this and always have encrypted IPC?*

- PSK identity is currently hard-coded to `"dummy"`. Since the pre-shared key is always unique to a pair of SGX enclaves, I don't see a need for a dynamic PSK identity. Maybe we should reconsider this decision when we figure out how to allow 3+ enclaves to share a socketpair (then a server enclave will have two PSK identities, one for each of client enclaves).

**Comment by mkow** [comment]
Thanks for the summary. For now, maybe we should state somewhere that multiprocessing in Graphene isn't secure currently?

Also, one small issue: The code for `mbedtls_hardware_poll` you pasted writes past the `output` buffer when `len` is not a multiple of 8.

**Comment by dimakuv** [comment]
### Assumption: no need for multicast

As discussed offline (@chiache and @mkow), it seems there are no real use cases when we need to support multicast (e.g., single-writer-many-readers). Therefore, our point-to-point TLS-PSK should be good for all pipe/socket purposes.

Additionally, there seem to be no real-world multicast crypto-protocol at application level. Google "multicast crypto" for details. A couple links:
- https://www.odva.org/Portals/0/Library/Conference/Paper%203_2018-ODVA-Conference_Visoky%20Wiberg_SecureMulticast_FINAL.pdf
- https://stackoverflow.com/questions/11425216/encrypted-and-authorized-multicast

- [ ] TODO: Figure out what `multicast` PAL handle does and if can be removed completely.

### Requirement: pass ownership of TLS session

When parent forks/execs a child, it must pass the ownership of all PAL handles not closed-on-exec.

This requires to collect the internal state of an mbedTLS session for this PAL handle. Unfortunately, mbedTLS doesn't have serialize/deserialize functionality to transfer the TLS state. We will need to introduce our own serialization functions that cherry-pick internal fields of internal structs in mbedTLS... **TODO: Can we do it in a nicer way?**

**Comment by dimakuv** [comment]
https://github.com/oscarlab/graphene/pull/1260 removed all multicast functionality. So we can ignore `multicast` issue.

**Comment by dimakuv** [comment]
mbedTLS 2.16.5 (latest stable release from Feb 2020; note that Graphene currently uses 2.16.3) has support for TLS session serialization! See:

- https://github.com/ARMmbed/mbedtls/blob/c31f970a46a2fe41e02fb581ce542faed4a0b12a/include/mbedtls/config.h#L1407.

- `ssl_session_save()` and `ssl_session_load()`.

**Comment by dimakuv** [comment]
I created a PR with update to mbedTLS 2.21: https://github.com/oscarlab/graphene/pull/1372. It works nicely.

**Comment by dimakuv** [comment]
Looking at the implementation of pipes in Graphene.

The PAL layer has four different pipe types:
- `pal_type_pipe`: never used??? (I don't see where LibOS would create such a pipe type)
- `pal_type_pipesrv`: two uses: (a) listening socket, only used as a temporary object to establish connection with "client" pipe; (b) read end of pipe
- `pal_type_pipecli`: write end of pipe
- `pal_type_pipeprv`: normal unnamed pipe (with two underlying FDs: one a read end, one a write end)

Also, there seems to be no implementation of Named Pipes (FIFOs) in Graphene: `mkfifo()` POSIX function uses `mknod()`/`mknodat()` syscalls, both these syscalls are not implemented in Graphene.

**Comment by dimakuv** [comment]
An interesting problem: pipes/socketpairs have the flow of `pipe()` -> `fork()` -> `close()` one in parent and on in child. This means that during `fork()`, we have four FDs and we don't know which ones will be used for communication (only two out of these four). This clashes with TLS sessions: before the first read/write, a TLS channel should be established via an SSL/TLS handshake.

We cannot perform an SSL/TLS handshake during `pipe()` emulation: this would mean that during `fork()`, we need to close & save the SSL context of one of the pipes (the requirement of `mbedtls_ssl_context_save()`, it always closes the session!), and we don't know which pipe will be closed after fork!

It seems that the only option is to create/initialize the SSL context on the first read/write pipe operation. This lazy initialization also has the benefit of fitting nicely in two main supported cases: (1) intra-process pipe for thread communication, and (2) parent - child communication starting right after fork, with no reads/writes before the fork.

For the SSL context initialization, we need a pre-shared key. Since pipes/socketpairs are always created in the same process, we create a unique random key for each pipe pair/socketpair. However, pipe emulation is complicated in PAL: LibOS emulates `pipe()` by explicitly creating two pipes, and the only shared setting for them is `pipeid`. So the suggestion is to derive a unique key from the combination of enclave-global `enclave_id` + `pipeid`. This key is then passed (in encrypted form) during PAL-handles send/receive on `fork()` to the child.

So the process is envisioned like this:
1. Parent does `pipe()`. PAL sees two `DkStreamOpen(url = pipeid)` and populates a new field `pal_handle.pipe.session_key = KDF(enclave_id || pipeid)`. The session key is thus the same in both pipe ends.
2. Parent does `fork()`. As part of checkpoint, the PAL handle of pipe is sent to the child, encrypted and containing the session key.
3. Parent closes its end of the pipe, child closes its end. Nothing really happens with these ends since they never had an established TLS connection.
4. Parent does first `read()`, child does first `write()`. Both notice that the session key exists, so we must create/initialize mbedTLS context. From this point on, the TLS connection is established.

There are a couple corner cases: `pipeprv` immediately creates two pipes in PAL. In this case, we just use some random key and give it to both pipe ends.

Also, this solution doesn't allow the pattern "use pipe in one process, then start using the same pipe in another process (e.g., child)". This would require some tricky mbedTLS context save/restore which is surprisingly hard to do right (just read the comments on `mbedtls_ssl_context_save()`).

**Comment by dimakuv** [comment]
I'll leave this here for future reference:

If we instantiate the TLS context on pipe() , we must choose one end as the server. Note that the server TLS endpoint cannot be serialized in current mbedTLS (it is probably impossible in general). So if we choose fds[0]  as the server, and the server does fork() , the only endpoint we can serialize is fds[1]  (the client). Ok, so now we have the parent process with two fds  and the child with two fds . If the parent's code decides to close fds[0] and use fds[1], we are doomed -- this is a client endpoint. And the child will use fds[0] , but this was the server endpoint, and we didn't even try to serialize and send it to the child.

**Comment by dimakuv** [comment]
I tried to use `mbedtls_ssl_context_save()` and `mbedtls_ssl_context_load()`. However, these functions only work on DTLS 1.2 with AEAD ciphers. So they don't work with our Graphene-used TLS sessions.

Clearly, these functions are still in their infancy. I'll try to avoid serialization/deserialization of SSL contexts in my current approach (see my lazy-handshake description).

**Comment by dimakuv** [comment]
The "lazy handshake" approach doesn't work in many cases. In particular, a typical scenario is when one process writes some status on a pipe and goes back to its stuff, whereas the second process does its own stuff and checks this pipe once in a while. Because Linux safely buffers such writes, it's ok for this process to be completely asynchronous.

With TLS sessions, unfortunately, we need *synchronous* communication for the very first exchange because of the TLS handshake. In other words, the very first write and read should be synchronized. This is impossible to guarantee in the general case with "lazy handshake"...

At this point I'm stuck and should revert back to the approach with serialization/deserialization. I hope to get some help from mbedTLS developers (https://github.com/ARMmbed/mbedtls/issues/3141).

Finally, one last approach is to circumvent serialization and establish a brand new TLS session (with a new TLS context) on each fork, somewhere in `DkSendHandle()` and `DkReceiveHandle()`. Unfortunately, this would limit our pipes only to the case of direct parent <-> child IPC. Also, two otherwise independent PAL handles (`pipe` and `pipecli`) will have to maintain pointers to each other, so that when one PAL handle is migrated and starts the handshake, the other one (in the parent process) also starts the handshake. Well, this gets really dirty....

**Comment by dimakuv** [comment]
OK, one more idea. Maybe we should reconsider using TLS-PSK layer and go one level down. This will require implementing our own rudimentary "secure communication channel". We were originally opposed to the idea of re-implementing the wheel, but nobody anticipated such problems as above...

**Comment by dimakuv** [comment]
Ok, I circled back to the serialization/deserialization approach.

> I tried to use mbedtls_ssl_context_save() and mbedtls_ssl_context_load(). However, these functions only work on DTLS 1.2 with AEAD ciphers. So they don't work with our Graphene-used TLS sessions.

After debugging mbedTLS and understanding its internal representation of a TLS context, I was able to create a patch for works for our TLS-PSK: https://github.com/dimakuv/mbedtls-psk-example.

Now I can hopefully use this patch and continue with Encrypted Pipes.

**Comment by dimakuv** [comment]
So I don't forget, I had a small bug in my mbedTLS 2.21.0 PR that I fixed: https://github.com/dimakuv/mbedtls-psk-example/blob/a416a5872d363075116a1892967eb8b130d957d8/Makefile#L47.

It is important to copy `config.h` in *both* subrepos of mbedTLS. Need to fix it in Graphene.
