### ISSUE TITLE
[Build/pylint] current pylint doesn't allow update to Pal/Linux-SGX generated_offset

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#1239]
When generated-offset.c in Pal/Linux/host/Linux-SGX/generated-offset.c and used it in pal-sgx-sign. pylint complains like Pal/src/host/Linux-SGX/signer/pal-sgx-sign +377:50: undefined-variable: Undefined variable 'ENCLAVE_SIG_STACK_SIZE'
This is found by https://github.com/oscarlab/graphene/pull/1238

Basically pylint fails to import generated_offset.py and complains because it's not created yet.
If it successfully imports generated_offsets.py, it complains many unused import like
Pal/src/host/Linux-SGX/signer/pal-sgx-sign:12:0: W0614: Unused import SGX_GPR_RAX from wildcard import (unused-wildcard-import)

the option would be update .pylint to suppress the complain.
other options would be to update prfilter to handle it specifically.
thoughts?

**Comment by woju** [comment]
looking into this
