### ISSUE TITLE
Can't run memcached with graphene: Failed to open '.lck'

### ISSUE THREAD

**Issue by sp21** [oscarlab/graphene#1255]
```
$ ./pal_loader SGX memcached -u nobody
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Accessing file:.lck is denied. (Unknown error) This file is not trusted or allowed.
Failed to open ".lck": File exists
```
While trying to run memcached with graphene, I encountered such errors.

Depending on whether the file exists or not, the error varies (e.g. file exists or permission denied), and in neither case, the app cannot make progress.

I guess that the authors are, in general, aware of this issue, as they mention `.lck` in the manifest file of memcached.

```
# TODO(dimakuv): Graphene's PAL incorrectly handles this currently. See
# `read_environments()`, the end of function. Below strings create envvars
# with empty strings, which forces Memcached to do incorrect things like
# creating an empty-prefix .lck file (due to MEMCACHED_PORT_FILENAME=="").
loader.env.MEMCACHED_PORT_FILENAME =
loader.env.MEMCACHED_HASH_BULK_MOVE =
loader.env.SASL_CONF_PATH =
loader.env.MEMCACHED_SASL_PWDB =
loader.env.T_MEMD_INITIAL_MALLOC =
loader.env.MEMCACHED_SLAB_BULK_CHECK =
```

Anyone have idea on how to walk around this issue?

**Comment by dimakuv** [comment]
You can just comment out these `loader.env` lines in the manifest and rebuild.

Yes, we are aware of this issue. This is a rather big change in the manifest syntax which we haven't implemented yet.

**Comment by sp21** [comment]
Ah thanks! I am closing this issue and will wait for the changes. I think I can follow your advice in the meanwhile.
