### ISSUE TITLE
Retire Graphene SGX driver

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#127]
We originally introduced a wrapper driver for the Intel SGX driver to solve a compatibility issue: the previous Intel driver does not support creating enclaves at low addresses (e.g., 0x400000). 

Intel driver v1.8 solves the problem, and thus the Graphene-SGX driver no longer calls the ioctl operations of the Intel driver. 

The only reason that we still need a driver is to enable the WRFSBASE instruction in enclaves. 

If this issue is addressed in future versions of the Intel SGX driver, we will be able to retire our driver.

**Comment by mkow** [comment]
Resolved by #1997.
