### ISSUE TITLE
Consider systematic testing to find flaky tests

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#1298]
Moving discussion from #1297 here:

@woju:
> Apart from any particular bug there, do you have recommendation on how to detect subtle bugs, which won't immediately cause the testsuite to fail, but introduce flakiness?
> 
> We could run the testsuite multiple times, but currently this is not done, because this would take too much time (both real time and Jenkins' CPU time). Instead, maintainers sometimes feel like they should do it manually and just write "[J]enkins retest please" 5 times or so.

@dimakuv:
> @woju Can we have a Jenkins job that runs every night (by night I mean some US time) for ~8 hours and reports how many tests failed? It should also show what PRs were merged from the previous run (the previous night). It won't be proactive but at least retroactively we'll have good understanding if some PRs introduced flakiness.

@HW42:
> As @dimakuv already proposed I think a nightly job (or even weekly would help) that loops as often as reasonably possible is a good solution. This not only allows spotting regressions but also helps to asses flaky results on PRs (i.e. If test X has failed for PR123 but succeeded on retry, you can look at the recent nightlies to asses if this is likely to be related to the PR).

@woju:
> @dimakuv We could, but depending on how much time the run would take we would have trouble to schedule it so it happens during the night in both our time zones.
> 
> We have 4 important pipelines ({16.04, 18.04} * {no sgx, sgx} and pick one of {no debug, debug}), 5 testsuite loops, each 30 min. Say it takes 5 hours on two concurrent Jenkins runners. So if we'd like this to be finished by, say, 09:00 in any time zone, the worst case this is 09:00 CEST (UTC+2), so this would have to start 02:00 UTC, which is, still in worst case, 18:00 PST. Now this worst case happens only for one week in autumn and two or three weeks in sprint, but nonetheless is a real problem. We could push this a few hours forward, so it would finish by, say 11:00 CEST, but this would still be 20:00 PST, and I think I saw you working at that time more than once.
> 
> <details><summary>My time zone cheat sheet</summary>
> <pre><code>NA standard -> summer: 2nd Sunday in March
> EU standard -> summer: last Sunday in March
> EU summer -> standard: last Sunday in October
> NA summer -> standard: 1st Sunday in November
> PST     PDT     AST     ADT     UTC     CET     CEST
> 16:00   17:00   20:00   21:00   00:00   01:00   02:00
> 17:00   18:00   21:00   22:00   01:00   02:00   03:00
> 18:00   19:00   22:00   23:00   02:00   03:00   04:00
> 19:00   20:00   23:00   00:00   03:00   04:00   05:00
> 20:00   21:00   00:00   01:00   04:00   05:00   06:00
> 21:00   22:00   01:00   02:00   05:00   06:00   07:00
> 22:00   23:00   02:00   03:00   06:00   07:00   08:00
> 23:00   00:00   03:00   04:00   07:00   08:00   09:00
> 00:00   01:00   04:00   05:00   08:00   09:00   10:00
> 01:00   02:00   05:00   06:00   09:00   10:00   11:00
> 02:00   03:00   06:00   07:00   10:00   11:00   12:00
> 03:00   04:00   07:00   08:00   11:00   12:00   13:00
> 04:00   05:00   08:00   09:00   12:00   13:00   14:00
> 05:00   06:00   09:00   10:00   13:00   14:00   15:00
> 06:00   07:00   10:00   11:00   14:00   15:00   16:00
> 07:00   08:00   11:00   12:00   15:00   16:00   17:00
> 08:00   09:00   12:00   13:00   16:00   17:00   18:00
> 09:00   10:00   13:00   14:00   17:00   18:00   19:00
> 10:00   11:00   14:00   15:00   18:00   19:00   20:00
> 11:00   12:00   15:00   16:00   19:00   20:00   21:00
> 12:00   13:00   16:00   17:00   20:00   21:00   22:00
> 13:00   14:00   17:00   18:00   21:00   22:00   23:00
> 14:00   15:00   18:00   19:00   22:00   23:00   00:00
> 15:00   16:00   19:00   20:00   23:00   00:00   01:00</code></pre></details>

**Comment by HW42** [comment]
If we need to optimize runtime I would only test on 18.04.

But can't we get an extra machine for this? Then it's not important that all tests are finished before the morning.

**Comment by mkow** [comment]
> But can't we get an extra machine for this? Then it's not important that all tests are finished before the morning.

@donporter @dcowhig ^

**Comment by donporter** [comment]
Non-SGX is easy.  SGX machines are a bit harder.  What type do we need?

**Comment by HW42** [comment]
We should also test SGX. But testing only some combination (for example only non-SGX on 18.04) would be a good start.

**Comment by woju** [comment]
Also, a tool for bisecting afterwards would be handy.

**Comment by dimakuv** [comment]
I would just test three pipelines in a loop: `Jenkins-18.04`, `Jenkins-SGX-18.04`, and `Jenkins-SGX-18.04-apps`.

**Comment by mkow** [comment]
@dimakuv I'd also run builds with `DEBUG=1`, testing also with asserts enabled is IMO worth the cost.

**Comment by dimakuv** [comment]
Nothing happened on this for the last 1.5 years. I don't think this deserves an explicit issue, so closing this.
