### ISSUE TITLE
Compiling with DEBUG=0 makes all SGX programs segfault

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#1313]
This is mostly annoying and to document the behavior. I used to switch between DEBUG=0|1 all the time but this particular commit introduced some undefined behavior: https://github.com/oscarlab/graphene/commit/647a8f3953e8af5f1789b1f0ec926c82c1040fee

Just do `DEBUG=0 SGX=1 make -j` in Graphene's root. Afterwards, any SGX program fails at runtime with some segfault in untrusted code, e.g.,

```
% SGX=1 ./pal_loader ./helloworld
SGX=1 ./pal_loader ./helloworld
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
Memory Mapping Exception in Untrusted Code (RIP = 55e01b1bc6a1)
```

**Comment by yamahata** [comment]
The work around is use DEBUG undefined instead of DEBUG=1. i.e. "SGX=1 make -j"

I share what I found so far

- DEBUG: undefined: -O2: yes -DDEBUG: no  => ok
- DEBUG=0:             : -O2: no  -DDEBUG: no => not working. you hit it
- DEBUG=1:             : -O2: no -DDEBUG: yes => ok
                                   -O2: yes -DDEBUG:yes => ok see #1302 and #1305

**Comment by yamahata** [comment]
Can you please try #1315 ?
