### ISSUE TITLE
Tensorflow Training with Graphene

### ISSUE THREAD

**Issue by dirknono** [oscarlab/graphene#1338]
Hi there,

Could somebody help me figure out this error? Thank you very much!
I want to use Graphene-SGX to work out a tensorflow-based training program. The original program is written by python, and I have used pyinstaller to make it a binary file (named retrain). This file can be successfully executed with the following files: tensorflow_inception_graph.pb (as model),  imagenet_comp_graph_label_strings.txt (for labelling), and a directory named ./flower_photes (as samples).

After I wrote a Makfile and genrated a manifest.sgx file, I run with: 
$ ../../../../../Runtime/pal_loader retrain
And I got this:
assert failed fs/shim_namei.c:318 start->state & DENTRY_ISDIRECTORY

When running with:
$ SGX=1 ../../../../../Runtime/pal_loader retrain (Note that the file check policy is allow_all_but_log.)
I got this:
assert failed fs/shim_namei.c:318 start->state & DENTRY_ISDIRECTORY
DkProcessExit: Returning exit code -131
Saturation error in exit code -131, getting rounded down to 125
DkProcessExit: Returning exit code 9

**Comment by dirknono** [comment]
My manifest template:

#!$(PAL)

loader.preload = file:$(GRAPHENEDIR)/Runtime/libsysdb.so
loader.exec = file:retrain
#loader.execname=
loader.env.LD_LIBRARY_PATH = $(PYTHONHOME)/lib:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
loader.env.PATH = /bin:/usr/bin
loader.debug_type = none
#loader.debug_type = inline

sgx.file_check_policy=allow_all_but_log
sgx.allow_file_creation=1

fs.mount.lib1.type = chroot
fs.mount.lib1.path = /lib
fs.mount.lib1.uri = file:$(GRAPHENEDIR)/Runtime

fs.mount.lib2.type = chroot
fs.mount.lib2.path = /lib/x86_64-linux-gnu
fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu

fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp

sgx.enclave_size = 4G

sgx.thread_num = 16

sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
sgx.trusted_files.ld = file:$(GRAPHENEDIR)/Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:$(GRAPHENEDIR)/Runtime/libc.so.6
sgx.trusted_files.libdl = file:$(GRAPHENEDIR)/Runtime/libdl.so.2
sgx.trusted_files.libm = file:$(GRAPHENEDIR)/Runtime/libm.so.6
sgx.trusted_files.libcpp = file:$(GRAPHENEDIR)/Runtime/libstdc++.so.6
sgx.trusted_files.libgcc = file:$(GRAPHENEDIR)/Runtime/libgcc_s.so.1
sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
sgx.trusted_files.librt = file:$(GRAPHENEDIR)/Runtime/librt.so.1

sgx.trusted_files.pbfiles = file:./tensorflow_inception_graph.pb
sgx.trusted_files.labels = file:./imagenet_comp_graph_label_strings.txt
sgx.allowed_files.samples = file:./flower_photos

**Comment by dirknono** [comment]
Makefile as follows:


manifests = $(addsuffix .manifest,retrain)
exec_target = $(manifests)
target = retrain

GRAPHENEDIR ?= ../../../../..


PHONY: default
default: retrain.manifest
ifeq ($(SGX),1)
default: retrain.manifest.sgx
endif

$(GRAPHENEDIR)/Runtime/libgcc_s.so.1:
	cp /lib/x86_64-linux-gnu/libgcc_s.so.1 $@

$(GRAPHENEDIR)/Runtime/libstdc++.so.6:
	cp /usr/lib/x86_64-linux-gnu/libstdc++.so.6 $@

retrain.manifest: retrain 
retrain.manifest: $(GRAPHENEDIR)/Runtime/libgcc_s.so.1 $(GRAPHENEDIR)/Runtime/libstdc++.so.6
retrain.manifest: retrain.manifest.template
	sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
		-e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
		$< > $@

retrain.manifest.sgx: retrain.manifest
	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
		-libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
		-key $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem \
		-manifest $< -output $@ \
		-exec retrain
	$(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
		-output retrain.token -sig retrain.sig

.PHONY: run-native
run-native: default
	./retrain

.PHONY: run-graphene
run-graphene: default
	$(GRAPHENEDIR)/Runtime/pal_loader ./retrain 


.PHONY: clean
clean:
	$(RM) retrain.manifest retrain.manifest.sgx retrain.sig retrain.token

**Comment by dimakuv** [comment]
You seem to be using a rather old Graphene and Makefile example... Could you update to the newest Graphene, rebuild and try again?

Also, please also send the auto-generated manifest.sgx file.

Did you try to build with `GRAPHENEDEBUG = 1`? What is the output?

Finally, try to debug with strace: `strace -f   ../../../../../Runtime/pal_loader retrain`. What does it show? At which point this error is observed?

**Comment by dirknono** [comment]
I have updated to the newest version and tried again. The problem still exists. 
Here is my manifest.sgx file:

# DO NOT MODIFY. THIS FILE WAS AUTO-GENERATED.

#!$(PAL)

loader.preload = file:../../../../../Runtime/libsysdb.so
loader.exec = file:retrain
loader.env.LD_LIBRARY_PATH = $(PYTHONHOME)/lib:/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
loader.env.PATH = /bin:/usr/bin
loader.debug_type = none


sgx.file_check_policy = allow_all_but_log
sgx.allow_file_creation = 1

fs.mount.lib1.type = chroot
fs.mount.lib1.path = /lib
fs.mount.lib1.uri = file:../../../../../Runtime


fs.mount.lib2.type = chroot
fs.mount.lib2.path = /lib/x86_64-linux-gnu
fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu



fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp

sgx.enclave_size = 4G

sgx.thread_num = 16

sgx.trusted_files.libz = file:/lib/x86_64-linux-gnu/libz.so.1
sgx.trusted_files.ld = file:../../../../../Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:../../../../../Runtime/libc.so.6
sgx.trusted_files.libdl = file:../../../../../Runtime/libdl.so.2
sgx.trusted_files.libm = file:../../../../../Runtime/libm.so.6
sgx.trusted_files.libcpp = file:../../../../../Runtime/libstdc++.so.6
sgx.trusted_files.libgcc = file:../../../../../Runtime/libgcc_s.so.1
sgx.trusted_files.libpthread = file:../../../../../Runtime/libpthread.so.0
sgx.trusted_files.librt = file:../../../../../Runtime/librt.so.1

sgx.trusted_files.pbfiles = file:./tensorflow_inception_graph.pb
sgx.trusted_files.labels = file:./imagenet_comp_graph_label_strings.txt
sgx.allowed_files.samples = file:./flower_photos


sgx.isvprodid = 0
sgx.isvsvn = 0
sgx.sigfile = file:retrain.sig
sgx.static_address = 1
sgx.trusted_checksum.exec = 7143f22006cfcc3af10efccad85db4a977507267bfc96c38e2aad21bb79c6f0d
sgx.trusted_checksum.labels = da2a31ecfe9f212ae8dd07379b11a74cb2d7a110eba12c5fc8c862a65b8e6606
sgx.trusted_checksum.ld = e6d91ab43c8abd66ebda8b12c5255cdf9062b3ca6b5fb63dee7a55bf4a59103d
sgx.trusted_checksum.libc = 2b90c523c2960fdf55d2b79ae12bfe8390502f4d90583570dcc39c41fff0ef24
sgx.trusted_checksum.libcpp = 6726cc7f6d72f64114380973d56efeaf99d4a4b167291fa8338a3bbb811b1779
sgx.trusted_checksum.libdl = 8058a534c9593fe0e22271b78e27d1d1486b09c7de2eade92af73bbe2a28e8a9
sgx.trusted_checksum.libgcc = e78f03a3817f7b72058b4070c68cd2f42835e4d2c957467d1e34b496dd089ddc
sgx.trusted_checksum.libm = a9c2882313826a31044af08a63dbc6778cf1773f286675597c8f764373be0040
sgx.trusted_checksum.libpthread = 5d96fd1511d0052f7ca3817d7cd889676eb62ea72a514a6c04140f0e228cb913
sgx.trusted_checksum.librt = 77be33a23f436b22b1f503492285270060eec076846d3258eb26b3d9f0f2bd79
sgx.trusted_checksum.libz = 219c6c0efe93bd6d751bba1e8ae84a162309c665cc5e36beddcf295b72f9bc09
sgx.trusted_checksum.pbfiles = 009d6814d1bc560d4e7b236e170e9b2d5ca6f4b57bd8037f6db05776204415c6
sgx.trusted_checksum.preload0 = 98dae855ed6e8ea68c736f9239bd28630befc95a15bafbd750cd0d534a02973a

**Comment by dirknono** [comment]
When using strace, the error is observed as follows:

[pid 18491] open("/tmp/_MEInwlG4y/libexpat.so.1", O_RDONLY|O_CLOEXEC) = 29
[pid 18491] stat("/tmp/_MEInwlG4y/libpthread.so.0", 0x68a58a3f2df0) = -1 ENOENT (No such file or directory)
[pid 18491] stat("../../../../../Runtime/libpthread.so.0", {st_mode=S_IFREG|0755, st_size=2377480, ...}) = 0
[pid 18491] open("../../../../../Runtime/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 30
[pid 18491] mmap(0x7f574c7a1000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 30, 0) = 0x7f574c7a1000
[pid 18491] mmap(0x68a588ebd000, 2224128, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 30, 0) = 0x68a588ebd000
[pid 18491] mprotect(0x68a588ed6000, 2097152, PROT_NONE) = 0
[pid 18491] mmap(0x68a5890d6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 30, 0x19000) = 0x68a5890d6000
[pid 18491] mmap(0x68a5890d8000, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a5890d8000
[pid 18491] open("../../../../../Runtime/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 31
[pid 18491] mprotect(0x68a588ebe000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
[pid 18491] mprotect(0x68a588ec1000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC) = 0
[pid 18491] mprotect(0x68a588ebe000, 4096, PROT_READ|PROT_EXEC) = 0
[pid 18491] mprotect(0x68a588ec1000, 4096, PROT_READ|PROT_EXEC) = 0
[pid 18491] stat("/tmp/_MEInwlG4y/libutil.so.1", 0x68a58a3f2d90) = -1 ENOENT (No such file or directory)
[pid 18491] stat("../../../../../Runtime/libutil.so.1", {st_mode=S_IFREG|0755, st_size=39856, ...}) = 0
[pid 18491] open("../../../../../Runtime/libutil.so.1", O_RDONLY|O_CLOEXEC) = 32
[pid 18491] mmap(0x7f574c79d000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 32, 0) = 0x7f574c79d000
[pid 18491] mmap(0x68a588cba000, 2109440, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 32, 0) = 0x68a588cba000
[pid 18491] mprotect(0x68a588cbc000, 2093056, PROT_NONE) = 0
[pid 18491] mmap(0x68a588ebb000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 32, 0x1000) = 0x68a588ebb000
[pid 18491] open("../../../../../Runtime/libutil.so.1", O_RDONLY|O_CLOEXEC) = 33
[pid 18491] stat("/tmp/_MEInwlG4y/libm.so.6", 0x68a58a3f2d60) = -1 ENOENT (No such file or directory)
[pid 18491] stat("../../../../../Runtime/libm.so.6", {st_mode=S_IFREG|0755, st_size=6025896, ...}) = 0
[pid 18491] open("../../../../../Runtime/libm.so.6", O_RDONLY|O_CLOEXEC) = 34
[pid 18491] mmap(0x7f574c799000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 34, 0) = 0x7f574c799000
[pid 18491] mmap(0x68a588929000, 3739648, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED, 34, 0) = 0x68a588929000
[pid 18491] mprotect(0x68a588ab9000, 2093056, PROT_NONE) = 0
[pid 18491] mmap(0x68a588cb8000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 34, 0x18f000) = 0x68a588cb8000
[pid 18491] open("../../../../../Runtime/libm.so.6", O_RDONLY|O_CLOEXEC) = 35
[pid 18491] mprotect(0x68a588cb8000, 4096, PROT_READ) = 0
[pid 18491] mprotect(0x68a588ebb000, 4096, PROT_READ) = 0
[pid 18491] mprotect(0x68a5890d6000, 4096, PROT_READ) = 0
[pid 18491] mprotect(0x68a58930b000, 8192, PROT_READ) = 0
[pid 18491] mprotect(0x68a5898e4000, 16384, PROT_READ) = 0
[pid 18491] stat("./root", 0x68a58a3f4980) = -1 ENOENT (No such file or directory)
[pid 18491] read(5, "\277\371r;W\231\322\264\364\315\35\342\320r\17w\3532\217\322\20 V\307", 24) = 24
[pid 18491] mmap(0x68a5888e9000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a5888e9000
[pid 18491] mmap(0x68a5888a9000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a5888a9000
[pid 18491] munmap(0x68a5888a9000, 262144) = 0
[pid 18491] mmap(0x68a588869000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a588869000
[pid 18491] mmap(0x68a588769000, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a588769000
[pid 18491] mmap(0x68a588729000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a588729000
[pid 18491] stat("/tmp/_MEInwlG4y/base_library.zip", {st_mode=S_IFREG|0700, st_size=771132, ...}) = 0
[pid 18491] open("/tmp/_MEInwlG4y/base_library.zip", O_RDONLY|O_CLOEXEC) = 36
[pid 18491] mmap(0x7f574c778000, 135168, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f574c778000
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xbc000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xb8000) = 0x7f574c774000
[pid 18491] mmap(0x68a5886e9000, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x68a5886e9000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xbc000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] close(36)                   = 0
[pid 18491] open("/tmp/_MEInwlG4y/base_library.zip", O_RDONLY|O_CLOEXEC) = 36
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0x7c000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] close(36)                   = 0
[pid 18491] open("/tmp/_MEInwlG4y/base_library.zip", O_RDONLY|O_CLOEXEC) = 36
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0x7c000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] close(36)                   = 0
[pid 18491] open("/tmp/_MEInwlG4y/base_library.zip", O_RDONLY|O_CLOEXEC) = 36
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xb0000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] mmap(0x7f574c768000, 65536, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xb0000) = 0x7f574c768000
[pid 18491] munmap(0x7f574c768000, 65536) = 0
[pid 18491] close(36)                   = 0
[pid 18491] open("/tmp/_MEInwlG4y/base_library.zip", O_RDONLY|O_CLOEXEC) = 36
[pid 18491] mmap(0x7f574c774000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xb0000) = 0x7f574c774000
[pid 18491] munmap(0x7f574c774000, 16384) = 0
[pid 18491] mmap(0x7f574c768000, 65536, PROT_READ, MAP_PRIVATE|MAP_FIXED, 36, 0xb0000) = 0x7f574c768000
[pid 18491] munmap(0x7f574c768000, 65536) = 0
[pid 18491] close(36)                   = 0
[pid 18491] write(1, "assert failed fs/shim_namei.c:32"..., 68) = 68
[pid 18491] --- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
[pid 18492] <... ppoll resumed> <unfinished ...>) = ?
[pid 18492] +++ killed by SIGTRAP +++
[pid 18491] +++ killed by SIGTRAP +++
[pid 18490] <... ppoll resumed> )       = 2 ([{fd=20, revents=POLLIN|POLLHUP}, {fd=22, revents=POLLIN|POLLHUP}])
[pid 18490] ioctl(20, FIONREAD, [0])    = 0
[pid 18490] ppoll([{fd=20, events=POLLIN|POLLOUT}], 1, {tv_sec=0, tv_nsec=0}, NULL, 0) = 1 ([{fd=20, revents=POLLIN|POLLOUT|POLLHUP}], left {tv_sec=0, tv_nsec=0})
[pid 18490] shutdown(20, SHUT_RDWR)     = 0
[pid 18490] shutdown(22, SHUT_RDWR)     = 0
[pid 18490] write(11, "\335", 1)        = 1
[pid 18490] futex(0x7fc2bb125378, FUTEX_WAKE, 1) = 1
[pid 18480] <... futex resumed> )       = 0
[pid 18490] close(20)                   = 0
[pid 18480] munmap(0x7fc2baab9000, 20480 <unfinished ...>
[pid 18490] close(22 <unfinished ...>
[pid 18480] <... munmap resumed> )      = 0
[pid 18490] <... close resumed> )       = 0
[pid 18490] ppoll([{fd=10, events=POLLIN}, {fd=6, events=POLLIN}], 2, NULL, NULL, 0) = 1 ([{fd=10, revents=POLLIN}])
[pid 18490] read(10, "\335", 100)       = 1
[pid 18490] ppoll([{fd=10, events=POLLIN}, {fd=6, events=POLLIN}], 2, NULL, NULL, 0 <unfinished ...>
[pid 18480] nanosleep({tv_sec=0, tv_nsec=500000000}, 0x3b0b15d3baa0) = 0
[pid 18480] write(11, " ", 1)           = 1
[pid 18490] <... ppoll resumed> )       = 1 ([{fd=10, revents=POLLIN}])
[pid 18480] shutdown(6, SHUT_RDWR)      = 0
[pid 18490] read(10,  <unfinished ...>
[pid 18480] exit_group(9 <unfinished ...>
[pid 18490] <... read resumed> " ", 100) = 1
[pid 18480] <... exit_group resumed>)   = ?
[pid 18490] +++ exited with 9 +++
+++ exited with 9 +++

**Comment by dirknono** [comment]
For the latest version of graphene, when I do
$ ../../../../../Runtime/pal_loader retrain
It gives:
assert failed fs/shim_namei.c:322 start->state & DENTRY_ISDIRECTORY

And when I do:
$ make GRAPHENEDEBUG=1
It gives:
sed -e 's|$(GRAPHENEDIR)|'"../../../../.."'|g' \
	-e 's|$(GRAPHENEDEBUG)|'"1"'|g' \
	retrain.manifest.template > retrain.manifest

**Comment by dimakuv** [comment]
You should do `make SGX=1 GRAPHENEDEBUG=1` and run the SGX version of your application. It will output a log of debug information. Can you also copy-paste this output here?

Right now I don't see any suspicious outputs. It is unclear to me based on your manifest and the strace output what goes wrong.

**Comment by dimakuv** [comment]
Another thing to do: try strace w/o Graphene, on the original application.

Per your strace output, Graphene fails somewhere after opening `/tmp/_MEInwlG4y/base_library.zip` several times. What happens in the original-application execution? What is the next file the application opens?

**Comment by dirknono** [comment]
Thanks a lot. The problem has been solved. I think it is due to using python without venv. I rewrote the makefile and manifest.template. The training works for me now.

**Comment by carlzhangweiwen** [comment]
@dirknono Hi, could you share your code? I'm a newer, and my python code not worked. Thanks~

**Comment by wrh0520** [comment]
@dirknono Hi, could you please share your code? I'm trying to run a tensorflow program with Graphene-SGX, but I don't know how to begin. Thanks
