### ISSUE TITLE
Can Graphene SGX OS Library be used with DPDK

### ISSUE THREAD

**Issue by markueni** [oscarlab/graphene#1343]
Hi,
I have an application built on top of DPDK, and I was planning to use Graphene to port my application into SGX enclave while leaving DPDK outside enclave and other parts inside enclave. Is it possible to use Graphene Library to interact with DPDK outside enclave?

Cheers

**Comment by dimakuv** [comment]
Hi,

Generally, no. Graphene in its current state assumes that *the whole* application runs inside an SGX enclave.

However, if you are willing to change the Graphene source code itself, you can achieve the interoperability with the outside-of-enclave DPDK. We did this a couple years ago: https://github.com/cloud-security-research/sgx-ids. You may be particularly interested in this patch to Graphene: https://github.com/cloud-security-research/sgx-ids/blob/master/misc/graphene-03-trustedclock-dpdkocalls.diff.

**Note** that this is a very old project from 2018. It is not maintained and serves only as an example of what can be theoretically achieved. This project used DPDK similarly to your use case, with an IDS (Snort) running inside of the enclave.

We also wrote a small technical report on this endeavour: https://arxiv.org/abs/1802.00508.

Hope this helps. To reiterate, there is nothing like "run some code outside of enclave" on the Graphene agenda.

**Comment by markueni** [comment]
So when I will build Graphene Library OS and sign my application (as whole) on developer machine it will include also DPDK inside enclave by default? My application is agnostic to usage of kernel stack so it can either work with a normal linux kernel stack or DPDK depending how I execute it. For that reason DPDK is not located inside my application folder and so I download DPDK seperately and then built it. In such case when my application and dpdk are different folders should I build them both and then sign them both?  I lately run into Graphene so I hope my question do really make sense to you

**Comment by dimakuv** [comment]
By default, Graphene will put the whole application with all its dependencies (libraries, spawned child processes) inside SGX enclaves. There is no way to put the main application inside the SGX enclave with Graphene and "connect it" to the DPDK untrusted part. Graphene doesn't support Inter-Process Communication between enclave applications and non-enclave applications. So your usage won't be possible with vanilla Graphene.

**Comment by markueni** [comment]
hi,
Are u saying that even if I put dpdk inside enclave will it still not be
possible to use graphene for my application?
Cheers

**Comment by dimakuv** [comment]
If you put the whole application including DPDK inside Graphene, then it would *theoretically* work. Unfortunately, DPDK is too low-level and requires (at least for the control plane) very NIC-specific commands -- unsupported IOCTLs, traversing the `/dev` pseudo-FS, etc. Graphene was never designed to deal with close-to-hardware software, and DPDK inside Graphene will fail.

**Comment by markueni** [comment]
Hi,
Thanks for your amazing support but I just find it out that Graphene only
support native unmodified Linux application. My application uses its own
DPDK and mTCP version and therefore is not unmodified. I guess Graphene is
not designed to support sucj application, but I have seen that u have
ported snort-Intrusion Detection System (IDS) at graphene which leads me to
believe that it would be possible to port my application to Graphene if I
manage to properly modify Graphene code for my scenario. Is it correct? If
so can u give me a hint where I should look at the code of Graphene which I
may need to adapt?

Thanks,
Enio

**Comment by dimakuv** [comment]
Yes, your understanding is correct. With some modifications to Graphene, you would be able to run it with DPDK. Please see my original reply https://github.com/oscarlab/graphene/issues/1343#issuecomment-589222092.
