### ISSUE TITLE
Error while executing "make SGX=1 sgx-tokens"

### ISSUE THREAD

**Issue by kleirama** [oscarlab/graphene#1351]
I have started my aesmd service using command 

> sudo service aesmd start

and then in directory _../LibOS/shim/test/native_ I run the command  

> make SGX=1 sgx-tokens

And get the following error: 

>  [ Token: exec_fork ]
> Traceback (most recent call last):
>   File "/home/nuc/graphene/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 157, in <module>
>     sys.exit(main())
>   File "/home/nuc/graphene/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 151, in main
>     token = connect_aesmd(attr)
>   File "/home/nuc/graphene/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 117, in connect_aesmd
>     raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
> Exception: Failed. (Error Code = 30)
> ../../../../Scripts//../Pal/src/host/Linux-SGX/Makefile.manifest:19: recipe for target 'exec_fork.token' failed
> make: *** [exec_fork.token] Error 1

Also when I run command  

> ./pal_loader SGX helloworld
I got the error

> Cannot open device /dev/gsgx. Please make sure the Graphene SGX kernel module is loaded.

Am I doing something wrong?

**Comment by dimakuv** [comment]
Are you sure your AESM service works correctly? What is the output of `sudo service aesmd status`?

If there are errors or suspicious messages in the status of AESM, then you have to first solve this issue (it has nothing to do with Graphene). Please check the official repositories and guidelines about SGX PSW (which includes AESM daemon): https://github.com/intel/linux-sgx and https://github.com/intel/SGXDataCenterAttestationPrimitives.

**Comment by dimakuv** [comment]
Also, are you sure you installed both the (1) Intel SGX driver and the (2) Graphene SGX driver?

If not, please refer to our README: https://github.com/oscarlab/graphene/#how-to-build-graphene

**Comment by markueni** [comment]
> https://github.com/intel/SGXDataCenterAttestationPrimitives

The status of AESMD is :

> ● aesmd.service - Intel(R) Architectural Enclave Service Manager
>    Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: en
>    Active: active (running) since Tue 2020-02-25 18:04:08 CET; 4h 6min ago
>   Process: 1107 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=ex
>   Process: 1104 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, statu
>   Process: 1103 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exi
>   Process: 1101 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, statu
>   Process: 1096 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exi
>   Process: 1093 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=
>   Process: 1071 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=e
>  Main PID: 1114 (aesm_service)
>     Tasks: 4 (limit: 4915)
>    CGroup: /system.slice/aesmd.service
>            └─1114 /opt/intel/sgx-aesm-service/aesm/aesm_service
> 
> Feb 25 18:04:08 nuc-NUC8i7HVK systemd[1]: Starting Intel(R) Architectural Enclav
> Feb 25 18:04:08 nuc-NUC8i7HVK systemd[1]: Started Intel(R) Architectural Enclave
> Feb 25 18:04:08 nuc-NUC8i7HVK aesm_service[1114]: The server sock is 0x560c91076
> Feb 25 18:09:48 nuc-NUC8i7HVK aesm_service[1114]: InKernel LE loaded

However when I run instead of 

> make SGX=1 sgx-tokens

, I run 

> make SGX_RUN=1

I got the output:

> ../../../../Scripts//Makefile.Host:16: *** recipe commences before first target.  Stop.

When I installed the Graphene SGX driver I put the path of sgx.h in the command prompt because the command _./load.sh_ was not working neither the command _sudo insmod gsgx.ko_

Is it wrong to place the path where sgx.h is located?

**Comment by kleirama** [comment]
When running AESMD service to check the status I got the following output:

> ● aesmd.service - Intel(R) Architectural Enclave Service Manager
>    Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: en
>    Active: active (running) since Tue 2020-02-25 18:04:08 CET; 4h 6min ago
>   Process: 1107 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=ex
>   Process: 1104 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, statu
>   Process: 1103 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exi
>   Process: 1101 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, statu
>   Process: 1096 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exi
>   Process: 1093 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=
>   Process: 1071 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=e
>  Main PID: 1114 (aesm_service)
>     Tasks: 4 (limit: 4915)
>    CGroup: /system.slice/aesmd.service
>            └─1114 /opt/intel/sgx-aesm-service/aesm/aesm_service
> 
> Feb 25 18:04:08 nuc-NUC8i7HVK systemd[1]: Starting Intel(R) Architectural Enclav
> Feb 25 18:04:08 nuc-NUC8i7HVK systemd[1]: Started Intel(R) Architectural Enclave
> Feb 25 18:04:08 nuc-NUC8i7HVK aesm_service[1114]: The server sock is 0x560c91076
> Feb 25 18:09:48 nuc-NUC8i7HVK aesm_service[1114]: InKernel LE loaded

Since the command 

> make SGX=1 sgx-tokens

did not work out I instead executed command  

> make SGX_RUN=1

 and got the output 

>  ../../../../Scripts//Makefile.Host:16: *** recipe commences before first target.  Stop.

While installing Graphene SGX Driver I put the local path folder of where my _sgx.h_ folder was located instead of using 

>  sudo insmod gsgx.ko
> sudo sysctl vm.mmap_min_addr = 0 
cuz this commands output error

**Comment by dimakuv** [comment]
I just noticed that you seem to use a jumbled version of Graphene: Graphene doesn't support `make SGX_RUN=1` for ~6 months already.

Please update Graphene and your Makefiles (if you created any yourself) so that they use the new way of building applications (via `make SGX=1 sgx-tokens`).

**Comment by kleirama** [comment]
But when I use  

> make SGX=1 sgx-tokens

to run helloWorld example I got the error I mentioned. And I can see from the status of aesmd that aesmd is working correctly. Is something I can do to fix such issue?

**Comment by dimakuv** [comment]
You are using an old version of Graphene. I don't know how you ended up with this old version, but simply remove the whole directory and re-install Graphene from scratch.

Are you using the master branch? Or you're using one of the older releases? (I would recommend you to use the master branch.)

**Comment by kleirama** [comment]
I git clone  "https://github.com/oscarlab/graphene.git" located at https://github.com/oscarlab/graphene/tree/master

My guess is that should be the right one

**Comment by dimakuv** [comment]
Yes, that sounds correct.

I guess you just did `make SGX_RUN=1` because you used it before... Anyway, this command will fail.

Now back to your issue with AESM daemon and error code `30`. Did you test Intel SGX SDK first? Do sample enclaves from Intel SGX SDK work correctly?

What is the version of Intel SGX SDK/PSW and the SGX driver that you installed on your system? Graphene doesn't support Intel SGX driver of version less than 2.0, and doesn't support Intel SGX SDK/PSW of version less than 2.4 (if I recall correctly).

**Comment by kleirama** [comment]
I have installed the latest version of all packages which I recall is 2.6 for driver and 2.8 for SDK from this site [](https://download.01.org/intel-sgx/sgx-linux/2.8/distro/ubuntu18.04-server/). However when I installed them I do not use the link you provided in ReadMe file but I download the binary files and then install them using this guide [](https://download.01.org/intel-sgx/linux-2.3/docs/Intel_SGX_Installation_Guide_Linux_2.3_Open_Source.pdf) 

Anyhow I guess I am doing something wrong since I tried to run SampleEnclave and I can build it using 

> sudo make

But when I run **./app** I get the following error

> Info: Please make sure SGX module is enabled in the BIOS, and install SGX driver afterwards.
> Error: Invalid SGX device.
> Enter a character before exit ...

And that is super strange since I checked my BIOS several times and SGX is enabled at BIOS. Probably this has to do with the new BIOS UPDATES after foreshadow attack and still for my PC there is no BIOS UPDATE and this is what I think is to blame for such erros

**Comment by dimakuv** [comment]
That could be...

You can check what `dmesg` outputs (if the Intel SGX driver fails, you will see its error log). Other than that, you can also try to downgrade your Intel SGX driver and SDK/PSW (for example, I'm also using packages from the official web-site, but my SDK/PSW version is 2.6).

**Comment by kleirama** [comment]
When I run 

> dmesg | grep sgx
> [  267.067967] intel_sgx: Intel SGX Driver v2.6.0
> [  267.067982] intel_sgx INT0E0C:00: EPC bank 0x70200000-0x75f80000
> [  267.069100] intel_sgx: second initialization call skipped 

which seems SGX Driver is installed. Anyway I am gonna downgrade the all related SGX binary files. Can you give me an advice: Do I have to install SGX SDK and Driver, PSW from intel repositories or is ok if I go to:  https://download.01.org/intel-sgx/sgx-linux/2.8/distro/ubuntu18.04-server/ and download binary files and then install them using the procedure at : https://download.01.org/intel-sgx/linux-2.3/docs/Intel_SGX_Installation_Guide_Linux_2.3_Open_Source.pdf (One thing I realised is that SGX PSW has many related packages with this new release version which older version did not have).

**Comment by dimakuv** [comment]
@kleirama , I used both approaches.

I personally prefer to clone from GitHub repositories (as described in Graphene's README). Over time, I used many versions (git tags, e.g., `sgx_driver_2.6`) of the SGX driver and the SDK/PSW (e.g., `sgx_2.6`).

But I also used binary packages from `01.org`. They also worked fine. (One thing that I periodically forget is that if you're behind a corporate firewall/proxy, you need to update `/etc/aesmd.conf` every time you re-install PSW).

**Comment by dimakuv** [comment]
@kleirama Also, in an unlikely case you have a fancy SGX machine with Flexible Launch Control (FLC), then you need to use these packages: https://download.01.org/intel-sgx/latest/dcap-latest/linux/distro/ubuntuServer18.04/. This is a "special" version of the SGX driver + SDK/PSW that is tailored to FLC-based SGX machines.

**Comment by kleirama** [comment]
I thank you for your valuable contribution and I am gonna uninstall all SGX related packages and use downgraded version of binary packages. One more thing: When I build Graphene SGX driver as described here: 

> cd Pal/src/host/Linux-SGX/sgx-driver
> make
> # The console will be prompted to ask for the path of Intel SGX driver code
> sudo insmod gsgx.ko
> sudo sysctl vm.mmap_min_addr = 0

When the console is prompted if I use  _sudo insmod gsgx.ko_ It gives me the error that it can not locate sgx.h file but when the console is prompted and use the local path of where sgx.h file is then it does not give any error. Does this have to do with SGX driver of my machine? And is this i a case of concern if I put the local path of my _sgx.h_ file instead of using _sudo insmod gsgx.ko_

**Comment by dimakuv** [comment]
When you type in `make` to build the Graphene SGX driver, you're supposed to type in the local path of where the `sgx.h` file is located, *not* the line `sudo insmod gsgx.ko`.

After you build the driver via `make`, then you must type a new command in your console: `sudo insmod gsgx.ko` to install the built driver on your machine. Hope this explanation helps.

**Comment by kleirama** [comment]
That solved my problem. I was not executing command 

> sudo insmod gsgx.ko

after the console was prompted.

Thnx for your help.

**Comment by dimakuv** [comment]
Glad to help! I'll close this issue then.
