### ISSUE TITLE
Run statically compiled executables from enclavized Bash

### ISSUE THREAD

**Issue by ArnaudCarrere** [oscarlab/graphene#1353]
Hi,
If I run a statically compiled (with -static flag) executable from enclavized Bash, the subenclave fails with:

> sgx shim_init() in do_migration (-13)
> Saturation error in exit code -13

If I remove the -static flag on compilation, the subprocess enclave runs well

**Comment by dimakuv** [comment]
Thanks for the bug description! I will try to find time and look into this bug.

Does this statically linked executable run fine in Graphene (w/o being spawned by Bash)?

Does it happen even with a HelloWorld-style executable?

**Comment by ArnaudCarrere** [comment]
The static executable runs properly as the main executable and generates this bug only when run as a child. I'm gonna try it with a HelloWorld binary

**Comment by ArnaudCarrere** [comment]
Yes, the error is the same with a HelloWorld :
*** allocating out of heap: 0x808667000 ***
shim_init() in do_migration (-13)
Saturation error in exit code -13, getting rounded down to 243
run.sh: line 4:    33 Killed                  ./hw

**Comment by dimakuv** [comment]
Could you do `file /bin/bash` and `file <your-hello-world-exec>` and post the results here? Also, what are the `sgx.enclave_size` values in your manifests?

I think I know what the problem is. See https://github.com/oscarlab/graphene-tests/pull/14 and https://github.com/oscarlab/graphene/issues/826. Briefly, Bash parent process creates a checkpoint with predefined memory regions, and the child receives this checkpoint and tries to restore at exactly the same addresses. But since the child was (presumably) started at a different base address, it cannot map the checkpoint to the same addresses.

**Comment by ArnaudCarrere** [comment]
Here are the results of `file <my-hello-world-exec>` : 

> hw: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=028540bf8786923811855b3edd58b2072f92a78c, not stripped

and of `file /bin/bash` : 

> /bin/bash: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=12f73d7a8e226c663034529c8dd20efec22dde54, stripped

The `sgx.enclave_size` values in the manifests are both 256M.

Here are the last lines of the execution in debug mode, the checkpoint seems to be restored :

> [P03636] host: Linux-SGX
> [P03636] bkeep_unmapped: 0x80b6c0000-0x80b6c2000 => vma
> [P03636] allocate 0x80b6c0000-0x80b6c2000 for vmas
> [P03636] Converting early VMA [0x80b98e060] 0x80b993000-0x80bcad000
> [P03636] Converting early VMA [0x80b98e0a8] 0x80fffe000-0x80ffff342
> [P03636] Converting early VMA [0x80b98e0f0] 0x80b6c3000-0x80b992000
> [P03636] Converting early VMA [0x80b98e138] 0x80b6c0000-0x80b6c2000
> [P03636] heap top adjusted to 0x8050ca000
> [P03636] bkeep_unmapped: 0x80b6af000-0x80b6c0000 => slab
> [P03636] bkeep_unmapped: 0x80b68e000-0x80b6af000 => slab
> [P03636] bkeep_unmapped: 0x80b68a000-0x80b68e000 => slab
> [P03636] bkeep_unmapped: 0x80b685000-0x80b68a000 => slab
> [P03636] bkeep_unmapped: 0x80b67d000-0x80b685000 => slab
> [P03636] shim loaded at 0x80b6c3000, ready to initialize
> [P03636] bkeep_mmap: 0x80329e000-0x8032e2000
> [P03636] checkpoint mapped at 0x80329e000-0x8032e1660
> [     1] bkeep_munmap: 0x80329e000-0x80729e000
> [P03636] 276064 bytes read on stream
> [P03636] receive handles: 1 entries
> [P03636] restore checkpoint at 0x80329e000 rebased from 0x80329e000
> [P03636] bkeep_unmapped: 0x80b678000-0x80b67d000 => slab

**Comment by dimakuv** [comment]
Looking at the output, what are the memory regions that you see in the HelloWorld child app?

In one of the previous comments, you mentioned: `*** allocating out of heap: 0x808667000 ***`. Can you find this address in one of the reserved memory regions of the child?

Basically, without reproducing your setup locally, I can only recommend looking at the debug output and trying to figure out if the memory address on which Graphene fails makes sense.

Btw, does it work on non-SGX Graphene?

**Comment by mkow** [comment]
No response from the reporter / not enough info to reproduce, closing.
@ArnaudCarrere: feel free to reopen if you have more information (see @dimakuv's questions) and if the bug still occurs on the current master.
