### ISSUE TITLE
Scanning application binary failed: 8 

### ISSUE THREAD

**Issue by claudiavmbrito** [oscarlab/graphene#1358]
Hi, 
I am currently trying to leverage the use of data analytics frameworks within SGX and Graphene seemed the most suitable approach to do this. However, I am trying to port an unmodified Apache Spark standalone application and a simple python script to run within Spark and I keep getting the same error.
`Scanning application binary failed: 8`
Any idea to why this may happen? For what I've seen in the source code, it comes from the scanning the enclave binary function, and even using gdb it does not bring any more information. 
[sample.txt](https://github.com/oscarlab/graphene/files/4282963/sample.txt)

**Comment by dimakuv** [comment]
Hi @claudiavmbrito,

What is the output of `file /home/spark-2.4.5-bin-hadoop2.6/bin/spark-submit`?

Also, what system are you running it on? Ubuntu 18.04?

Are you using the latest commit on the master branch of Graphene (recommended)?

**Comment by dimakuv** [comment]
Ok, it looks like `spark-submit` is not an executable file. The internet tells me that it is a script, most probably bash script (https://spark.apache.org/docs/latest/submitting-applications.html).

Graphene doesn't expect non-executables to be supplied as the "running process". You must modify your manifest to directly execute the binary, *not* the script.

**Comment by claudiavmbrito** [comment]
Hi, yes, I'm using the latest commit on the master branch of Graphene and running on Ubuntu 18.04. And yes, again, I was using the script and not the binaries. That may be the issue here. Thank you! :)

**Comment by mkow** [comment]
Seems the root issue was found, closing. Feel free to reopen if this isn't the case.
