### ISSUE TITLE
[Graphene-SGX] FIFO creation for parent-child IPC

### ISSUE THREAD

**Issue by ArnaudCarrere** [oscarlab/graphene#1375]
I created a parent program that launches a child program with `fork+execv`. Then the parent (writer) and the child (reader) open a named pipe (aka FIFO) passed as argument to communicate. The manifest defines the parent-child relationship, and the FIFO as a trusted_file.

If the FIFO was created with the linux command `mkfifo myfifo` before launching the parent `SGX=1 ./pal_loader parent.manifest.sgx --verbose --output=myfifo`, both parent and child process are blocked on the `open` command.

However, if the FIFO doesn't exist when launching the parent but the open commands have the O_CREAT flag, then a file is created (not a FIFO) and the parent-child communication succeeds.

So, my questions are :

- why `open` blocks on a FIFO previously created with the linux command mkfifo ? Is this a bug or a normal behavior ?
- is there a way to create a FIFO (mkfifo(name, permission) doesn't work from within Graphene-SGX) instead of classic file ?

Thanks
[parent.cc.txt](https://github.com/oscarlab/graphene/files/4354243/parent.cc.txt)
[child.cc.txt](https://github.com/oscarlab/graphene/files/4354244/child.cc.txt)

**Comment by dimakuv** [comment]
> why open blocks on a FIFO previously created with the linux command mkfifo ? Is this a bug or a normal behavior ?

This is "normal" behavior. Graphene expects a regular file to be opened (unless it was created with `mkfifo()` in https://github.com/oscarlab/graphene/pull/1454). There is currently simply no check that the file can be non-regular. I'll probably fix this later, but it is not high-priority.

**Comment by dimakuv** [comment]
> is there a way to create a FIFO (mkfifo(name, permission) doesn't work from within Graphene-SGX) instead of classic file ?

I created this PR: https://github.com/oscarlab/graphene/pull/1454. Please check it out.

I re-wrote your example C++ code in pure C (and with slightly different fork logic). It passes our tests. You can check my C code: https://github.com/oscarlab/graphene/pull/1454/files#diff-04c49fec4016a190b1e19dbd577b5b1a. I encourage you to also try your C++ code.

**Comment by dimakuv** [comment]
@ArnaudCarrere #1454 was merged today. If it solves all your problems, please close this issue.
