### ISSUE TITLE
[Examples] R is broken

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1390]
## Description of the problem:

R doesn't run as is (due to `trusted_files.libstdc++` -- plus signs are not allowed in manifests). Even after fixing this issue manually, R segfaults on one of the examples.

Need to update its Makefile and manifest and fix all found bugs.

## Steps to reproduce:

Go to `Examples/r` and try `make SGX=1` and then `SGX=1 ./pal_loader R.manifest --slave --vanilla -f scripts/sample.r`.

**Comment by mkow** [comment]
Blocked by #1724.
