### ISSUE TITLE
Try to run openjdk8 on SGX based on Graphene

### ISSUE THREAD

**Issue by superajun-wsj** [oscarlab/graphene#1391]
## Description of the problem:

when I tried to run openjdk8 on SGX based on Graphene, an error happened like this:

Error: could not find libjava.so
Error: Could not find Java SE Runtime Environment.

## Expected results:

load libjvm.so successful and print out Hello World.

## Actual results:

give information that could not find libjava.so

## Additional information: 

here is my manifest.sgx file: 

# DO NOT MODIFY. THIS FILE WAS AUTO-GENERATED.

loader.exec = file:/home/jeffery.wsj/j2sdk-image/bin/java

loader.preload = file:/home/jeffery.wsj/graphene/Runtime/libsysdb.so

#loader.debug_type =

loader.env.LD_LIBRARY_PATH = /home/jeffery.wsj/j2sdk-image/jre/lib/amd64/server:/home/jeffery.wsj/j2sdk-image/jre/lib/amd64:/home/jeffery.wsj/j2sdk-image/lib/amd64/jli:/graphene:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
loader.env.PATH = /home/jeffery.wsj/j2sdk-image/bin:/bin:/usr/bin
loader.env.JAVA_HOME = /home/jeffery.wsj/j2sdk-image

fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:/home/jeffery.wsj/graphene/Runtime

fs.mount.lib2.type = chroot
fs.mount.lib2.path = /lib/x86_64-linux-gnu
fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu

fs.mount.lib3.type = chroot
fs.mount.lib3.path = /usr/lib/x86_64-linux-gnu
fs.mount.lib3.uri = file:/usr/lib/x86_64-linux-gnu

fs.mount.etc.type = chroot
fs.mount.etc.path = /etc
fs.mount.etc.uri = file:/etc

fs.mount.jre.type = chroot
fs.mount.jre.path = /jre
fs.mount.jre.uri = file:/home/jeffery.wsj/j2sdk-image

fs.mount.usr.type = chroot
fs.mount.usr.path = /usr
fs.mount.usr.uri = file:/usr

fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp

sys.stack.size = 4M
sys.brk.size = 64M
glibc.heap_size = 16M
sgx.enclave_size = 32G
sgx.thread_num = 256

sgx.search_trusted_libs.java = file:/home/jeffery.wsj/j2sdk-image/jre/lib/amd64
sgx.search_trusted_libs.java_server = file:/home/jeffery.wsj/j2sdk-image/jre/lib/server

sgx.trusted_libs.libjava = file:/home/jeffery.wsj/j2sdk-image/jre/lib/amd64/libjava.so
#sgx.trusted_libs.libjli = file:$(JAVA_HOME)/lib/jli/libjli.so
#sgx.trusted_libs.libjvm = file:$(JAVA_HOME)/lib/server/libjvm.so
#sgx.trusted_libs.libzip = file:$(JAVA_HOME)/lib/libzip.so
#sgx.trusted_libs.libnet = file:$(JAVA_HOME)/lib/libnet.so
#sgx.trusted_libs.libnio = file:$(JAVA_HOME)/lib/libnio.so
sgx.trusted_libs.libnssc = file:/lib/x86_64-linux-gnu/libnss_compat.so.2
sgx.trusted_libs.libnssf = file:/lib/x86_64-linux-gnu/libnss_files.so.2
sgx.trusted_libs.libnssn = file:/lib/x86_64-linux-gnu/libnss_nis.so.2

sgx.trusted_files.ld = file:/home/jeffery.wsj/graphene/Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:/home/jeffery.wsj/graphene/Runtime/libc.so.6
sgx.trusted_files.libm = file:/home/jeffery.wsj/graphene/Runtime/libm.so.6
sgx.trusted_files.libdl = file:/home/jeffery.wsj/graphene/Runtime/libdl.so.2
sgx.trusted_files.librt = file:/home/jeffery.wsj/graphene/Runtime/librt.so.1
sgx.trusted_files.libutil = file:/home/jeffery.wsj/graphene/Runtime/libutil.so.1
sgx.trusted_files.libpthread = file:/home/jeffery.wsj/graphene/Runtime/libpthread.so.0
sgx.trusted_files.libresolv = file:/home/jeffery.wsj/graphene/Runtime/libresolv.so.2
sgx.trusted_files.libnssdns = file:/home/jeffery.wsj/graphene/Runtime/libnss_dns.so.2

sgx.file_check_policy = allow_all_but_log

# Generated by Graphene

sgx.allow_file_creation = 0
sgx.isvprodid = 0
sgx.isvsvn = 0
sgx.sigfile = file:java.sig
sgx.static_address = 1
sgx.trusted_checksum.exec = 71e4740b0fcfaf1323a2d7922c99d77ee8bf9eaebf013b0605090357d5c84884
sgx.trusted_checksum.ld = aca91bc8c9757a3479508f25e987c6c8394e490575c1677579da13e81c044a6d
sgx.trusted_checksum.libc = 830000d56ffd881fec911aefdaa7c8420afe43d2dddd4bc3949641ce8f7ad689
sgx.trusted_checksum.libdl = 92a7a73cbc535d3b041ba0f010905c0c23c515b499ca05cd82b060165fd4d35e
sgx.trusted_checksum.libm = 66ff3b03416c2b56716b3b58b0ceb1b82f5c47151e6ce31921638b7824e10741
sgx.trusted_checksum.libnssdns = c7151e17eac4cc3265880c41e16180f0b817c0ddd4693bbabc60b3a47ef0b9cb
sgx.trusted_checksum.libpthread = 127e697d25d0bf308aa7c8c9606b68e55cd9c0df835149be080bffd7d221d4c6
sgx.trusted_checksum.libresolv = bf0731219fb4a4870ef10a2af05e2dbf0a0a169367a4ab1ceaa5e0445c312dad
sgx.trusted_checksum.librt = 162817d1ba095d52de3fd07a682aa07af5bc66536fad4d9d8ad4d74934ad0338
sgx.trusted_checksum.libutil = 6c2c24e5f778c0aee7abafc2b7a04754ebfab0603a69ca417266bf60d5e44b3b
sgx.trusted_checksum.preload0 = 0f7280a2236e88ade5165f1bd9f50b3b726c7f91034bd303fbdf670e7a35cf2d

**Comment by dimakuv** [comment]
In your `manifest.sgx` file, you have this line:
```
#sgx.trusted_libs.libjvm = file:$(JAVA_HOME)/lib/server/libjvm.so
```

This is your missing `libjvm.so`. But this line is **commented out**, so Graphene tools skip the process of finding this file and putting its checksum in the manifest (it would appear in an auto-generated line like `sgx.trusted_checksum.libjvm = ...`).

Please uncomment this line back in your original `manifest.template` and re-run the build process for your Java example.

**Comment by superajun-wsj** [comment]
I tried to uncomment the line, but still without 'sgx.trusted_checksum.libjvm = ...',  could you please provide a manifest.template and Makefile for openjdk8?

**Comment by dimakuv** [comment]
We don't yet have an example with OpenJDK or any other JVM, unfortunately.

We have plans to add such an example. However, it will take some time...

**Comment by mkow** [comment]
This seems to just be a user configuration error, closing.
