### ISSUE TITLE
Usability improvement on deployment of gsgx.ko

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1402]
## Description of the problem:
the gsgx.ko needs to be manually loaded into kernel space using command "insmod", it would be a little bit confusing by regular user and also not flexible to extend features relevant to this kernel module checking & loading. I suggest to add a new target to Makefile, so user can just using the following command to verify and load it.

$ sudo make SGX=1 install

## Steps to reproduce:
it could be produced in current latest version according to the document
https://graphene.readthedocs.io/en/latest/quickstart.html#sgx-quick-start

## Expected results:
The gsgx.ko is able to be loaded across power cycles w/o the knowledge of kernel module loading mechanism needed

## Actual results:
It requires user to have basic knowledge of kernel module loading mechanism and no control of this process to verify and given useful information if loading failed

**Comment by mkow** [comment]
GSGX driver is deprecated and we definitely don't want to install it without explicit administrator consent. See https://github.com/oscarlab/graphene-sgx-driver/blob/09fc0e943693a8f68f1f3389dbaa68387b691106/README.rst.
