### ISSUE TITLE
[Pal/Linux,Linux-SGX] siglongjmp from exception handler is not supported

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1404]
#1326 introduces a change where Graphene always *has* an alternative signal stack which processes signals.

However, this "always" conflicts with a peculiar code pattern used by some LTP tests such as `mmap05`:
1. Install a signal handler for SIGSEGV without alternative signal stack
2. Save stack context in normal execution via `sigsetjmp()`; the saved context is "normal stack"
3. Perform an illegal memory access (`*0x50 = blabla`) to generate SIGSEGV
4. Print "Hurray, I caught SIGSEGV as expected" in the signal handler and call `siglongjmp()` to restore the saved context
5. Continue on the "normal execution" path as if exception didn't happen

The problem with Graphene is that step 4 happens on alternative signal stack, so the internal logic of `siglongjmp()` gets confused -- it expects the saved context to be on the normal stack, but we are currently executing on the signal stack, so Glibc breaks.

This is because Graphene now always handles all signals on the alternative signal stack. Even when the app doesn't request for it. Note that Graphene actually must handle all signals on this signal stack because of our infamous PAL exception handling scheme (otherwise app + LibOS normal execution intertwines with LibOS + PAL signal handling, and this leads to nasty errors in cases of nested signals).

Current simple solution is to disallow such patterns (`siglongjmp() from the exception handler back into the normal execution` -- LTP developers are either crazy or really hardcore) and disable `mmap05` test and similar.

Ideally we would want to have 4 separate stacks: (1) normal app stack, (2) signal app stack, (3) normal Graphene stack, (4) signal Graphene stack. And switch between them all the time.

**Comment by yamahata** [comment]
#1218  does allocate those four stacks.

**Comment by boryspoplawski** [comment]
There's one more issue in this scenario: currently Graphene disables interrupts (which just means: temporarily stop handling new signals) before handling a signal - if a app does siglongjmp out of signal context, it will be running with disabled interrupts (signal handling) forever.
