### ISSUE TITLE
[sgx_util]: ias_verify_url and ias_sigrl_url not managed by ias_context_t

### ISSUE THREAD

**Issue by kubkon** [oscarlab/graphene#1405]
## Description of the problem:

While working on Rust bindings for the `sgx_util` library, I've noticed that `ias_context_t` structure holds pointers to locations managed outside of the object. I'm thinking here mainly about the URL strings: `ias_verify_url` and `ias_sigrl_url`.  I'd expect both to be copied out from the input args in `ias_init`. Otherwise, there is always the possibility that the caller will free both before they are used.

For reference, here's the function signature:

```c
struct ias_context_t* ias_init(const char* ias_api_key, const char* ias_verify_url,
                               const char* ias_sigrl_url);
```

And the line number: [Linux-SGX/tools/common/ias.c#L198](https://github.com/kubkon/graphene/blob/master/Pal/src/host/Linux-SGX/tools/common/ias.c#L198).

cc @omeg

**Comment by dimakuv** [comment]
+1, good point. At least the comments on `isa_context_t::ias_verify_url / ias_sigrl_url` do not state that these are just pointers to separately-managed string objects. So I can see how confusion and data corruptions can arise.

Also, it seems like a very simple fix (calloc more memory to accommodate both strings and memcpy). @omeg, will you have time to submit a fix?
