### ISSUE TITLE
lat_vfork bug

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#142]
The lmbench lat_vfork test intermittently (but fairly frequently) blows this assertion:

assert failed sys/shim_mmap.c:78 cur_stack < addr || cur_stack > addr + length (value:0)

Temporarily taking it out of CI to get a stable baseline; documenting it here so that it can be fixed in the near future.

**Comment by mkow** [comment]
LMbench was removed from our test suite due to multiple issues/bugs within it (see #1588). Closing.
