### ISSUE TITLE
Apache hangs in debug build

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#144]
On a Linux host, debug build, apache bench hangs rather than servicing requests.  To reproduce, run the standard apachebench.  For some reason, this is not a problem on a non-debug build.  This is fairly consistent.

There is at least one pending epoll PR (#137 ).  Retest this after merging that.

For now, I'm taking apache out of the Linux host/Debug build CI.

**Comment by chiache** [comment]
I think it hangs when the semaphore is migrated to another process. I am still looking into why.

**Comment by mkow** [comment]
Apache runs now in CI and seems to be fine, closing.
