### ISSUE TITLE
Patch 'Enforce that executable is always located at a predefined address' breaks apps

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#1441]
This recent patch here breaks apps in Examples, such as the nodejs one.

https://github.com/oscarlab/graphene/commit/cd1648bcd8e057b7ee596fbe4641dec73eca155d

If you set `DEFAULT_OBJECT_EXEC_ADDR` to `NULL` it works again.

**Comment by stefanberger** [comment]
I have a simple local test script that I could give to you if you want it:

https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20200420/run_tests.sh

It's for quick smoke testing of Pal, LibOS , and Example test cases.

I run this as a scripts as a travis test as well:

https://travis-ci.org/github/stefanberger/graphene4ppc64/builds/678227353

I can send you a PR for support Travis support as well. It may take load off of your Jenkins server and is easier for people to set up - for non-SGX, of course. It needs a change to one particular test case iirc related to CPU info.

Let me know.

**Comment by dimakuv** [comment]
@stefanberger Thanks for the report! I will try to debug it today. Is there any other application (not NodeJS) that breaks? I would prefer to debug smth simpler... Also, do you have an idea why NodeJS may break with this patch?

**Comment by stefanberger** [comment]
@dimakuv I do NOT know why the test breaks nor do I have a simple app.

**Comment by dimakuv** [comment]
@stefanberger We debugged the issue.

Here is the PR to fix it: https://github.com/oscarlab/graphene/pull/1443. This PR only circumvents the real issue though, the underlying issue is: https://github.com/oscarlab/graphene/issues/1408.

But this fix should be good enough for all executables with binary size less than 85TB :)

**Comment by dimakuv** [comment]
#1443 was merged now. Please check node.js (or run your test suite) on the most recent master.

**Comment by stefanberger** [comment]
@dimakuv Yes, we are all green again: https://travis-ci.org/github/stefanberger/graphene4ppc64/builds/678576719

Thank you!
