### ISSUE TITLE
Support Graphene on other architectures, particularly ppc64

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#1450]
I want to state my interest in seeing support for Graphene on other architectures than x86_64. One such architecture I'd be particularly interested in is PowerPC64 (ppc64).

I have a PowerPC64 port of Graphene working. A first PR that would helps this case is PR https://github.com/oscarlab/graphene/pull/1449  where we get rid of x86_64 specifics from the build system.

Otherwise, my continuous Travis tests for PPC64 are occurring here: https://travis-ci.org/github/stefanberger/graphene4ppc64/builds  (Sometimes good days, sometimes not so good ones ...)

**Comment by stefanberger** [comment]
I just wanted to let you know that I am following the changes of Graphene using automated Continous Rebasing (TM :-)) on top of your master branch.  I think this is currently the best way to proceed for both parties since you guys can make progress with x86 and I don't block your progress in case ppc64 needs attention and I don't have time to follow up.

Today's tree for example is here: https://github.com/stefanberger/graphene4ppc64/commits/powerpc64.20201105

Thanks for all your attention in the past! It's been really good!

   Stefan

**Comment by mkow** [comment]
Good to hear, we were afraid you gave up :)
What's the current state of the port? How much is already working?

**Comment by stefanberger** [comment]
There were some example tests that are x86-specific, which I don't run of course when testing. Most other examples are running and being continuously tested, though:

- PAL and LibOS tests are working: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20201105/run_tests0
- Many examples are working: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20201105/run_tests1
- Several more tests are working: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20201105/run_tests2

I run these scripts locally and on [Travis](https://travis-ci.org/github/stefanberger/graphene4ppc64).

I recently lost the gcc example test following changes to Examples/gcc iirc. I couldn't figure out how to make it 'see' certain files 'ld' needs for linking.

The LTP tests are almost all working as on x86_64 with a few exceptions: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20201105/LibOS/shim/test/ltp/ltp-bug-ppc64.cfg  . Maybe some of the current PRs will fix them.

To make LTP work following the update to the more recent LTP test suite I had to add a few new `xyz_time64` syscalls: https://github.com/stefanberger/graphene4ppc64/commits/powerpc64.20201105 I suppose you don't need these for x86_64, otherwise we could split off some of them. Primarily they introduce and use [`struct timespec64`](https://github.com/stefanberger/graphene4ppc64/commit/53bd1c4a08374f579773caddb733eb73d3b302ea#diff-301808b4516c1c7863456fe8f6adeb3f892c6d60c163f4e2bd32e2ba18df19eeR90).

I didn't give up but I am hoping that there won't be any 'change the world' patches...

**Comment by mkow** [comment]
Nice!

> I recently lost the gcc example test following changes to Examples/gcc iirc. I couldn't figure out how to make it 'see' certain files 'ld' needs for linking.

Yeah, I had the same problem and I didn't manage to get it working after the start of loader rework. It should be back up again after I finish all the planned changes.

> The LTP tests are almost all working as on x86_64 with a few exceptions: https://github.com/stefanberger/graphene4ppc64/blob/powerpc64.20201105/LibOS/shim/test/ltp/ltp-bug-ppc64.cfg . Maybe some of the current PRs will fix them.

#1945 contains some fixes for sethostname()/setdomainname(), maybe they'll help :)

> I didn't give up but I am hoping that there won't be any 'change the world' patches...

On the PAL layer only the finalizing of the loader changes and the manifest syntax change (see #1892). If you have any non-ppc64-specific changes then you should try upstreaming them, it will ease the rebasing a bit :) In the future we would be happy to merge your port, but this is quite tricky logistically - we aren't experts in ppc64 and it will be hard for us to keep it in a good shape.

**Comment by stefanberger** [comment]
> #1945 contains some fixes for sethostname()/setdomainname(), maybe they'll help :)

Yes, I have seen that PR. Some of the failures related to domain and hostname only occurred on Travis and worked fine locally, so I just disabled them.

> In the future we would be happy to merge your port, but this is quite tricky logistically - we aren't experts in ppc64 and it will be hard for us to keep it in a good shape.

Yes, and that's exactly  what I am a bit worried about. If you end up running ppc64 tests via Travis and you cannot figure out how to fix failures then it will either deteriorate or becomes a blocker waiting for me to resolve the issue on someone's PR.

> If you have any non-ppc64-specific changes then you should try upstreaming them, it will ease the rebasing a bit :)

I would.
I had thought about sending a PR related to `struct timespec64` and changing all code working with `struct timespec` to use the `struct timespec64` instead and then convert back to `struct timespec` in a calling function so the existing syscalls return the expected result. But then x86_64 doesn't need it at all, so no need to upstream it now.

**Comment by dimakuv** [comment]
Stefan already submitted (and continues submitting) fixes to make Graphene PPC64 compatible. Thanks for this effort, greatly appreciated! But this general meta-issue can be closed now.
