### ISSUE TITLE
Invalid executable path for token generation tip

### ISSUE THREAD

**Issue by emilhem** [oscarlab/graphene#1451]
When Graphene is giving you the tip
```
Cannot open token 'file:xxx.token'. Use 'PATHTOSOURCE/graphene/Pal/src/pal-sgx-get-token' on the runtime host or run 'make SGX=1 sgx-tokens' in the Graphene source to create the token file.
```
The file `pal-sgx-get-token` is actually located in `graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token`. Just thought that you should know about it.

**Comment by mkow** [comment]
Thanks for noticing this, I'll fix it.
