### ISSUE TITLE
How to test nginx perf with nginx-tests

### ISSUE THREAD

**Issue by lackan** [oscarlab/graphene#146]
Hi,

Currently I can run nginx successfully with` ./nginx.manifest.sgx`, and I can also login the `http;//localhost` in web browser to see the nginx print. But i don't know how to use the nginx-tests to test the performance of sgx nginx. 

Can you give me some details?

Thanks.

**Comment by lackan** [comment]
BTW, I can run nginx-tests with native nginx, what I do is:
cd ngixn-tests
TEST_NGINX_BINARY=PATH/TO/GRAPHENE/libOS/shim/test/apps/nginx/nginx-1.10.1/objs/nginx prove .
But about SGX nginx, I'm not sure how to run it on the right way.

**Comment by donporter** [comment]
I'm not certain about this.  In general, you can configure the manifest for a web server to listen on a port on the local host, and just direct a test harness to that port.  For instance, we use apache bench pointed to port 8000 for our CI.

Hope that helps.

**Comment by lackan** [comment]
@donporter Thanks.
