### ISSUE TITLE
[Suggestion] moving application sample tarballs to a separate Github

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#147]
Since we are moving on to LGPL, application samples like lmbench are moved to submodules. However there are still quite a few applications sample left in the repository as tarballs, which can very possibly be GPL. What about moving them to a separate github and just keep a download link in Makefiles?

I also feel like keeping lmbench and C code samples as submodules is overkill. It creates an illusion that they are dependencies to the project, and causes troubles of maintaining submodule versions.

**Comment by donporter** [comment]
I am fine with being consistent and moving all of the test cases to separate repos.  I think this is best practice, so we only have our code/project code in the repo.  I only did it for code I noticed was GPL-ed.

We could also build docker images for the unit tests to marginally accelerate things.

**Comment by mkow** [comment]
outdated, closing (we got rid of all the tarballs)
