### ISSUE TITLE
FYI: Stability gains on more recent kernel (5.4.13-201.fc31.x86_64)

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#1470]
Some of the basic Pal and LibOS tests occasionally fail on Fedora 31 x86_64. It may be related to the VDSO. It looks like a lot of stability is gained with this small modification here:

```
diff --git a/Pal/src/host/Linux/pal_linux_defs.h b/Pal/src/host/Linux/pal_linux_defs.h
index e9e4901c..ee02ea70 100644
--- a/Pal/src/host/Linux/pal_linux_defs.h
+++ b/Pal/src/host/Linux/pal_linux_defs.h
@@ -6,8 +6,8 @@
 #define THREAD_STACK_SIZE (PRESET_PAGESIZE * 2)   /* 8KB initial stack (grows automatically) */
 #define ALT_STACK_SIZE    (PRESET_PAGESIZE * 16)  /* 64KB signal stack */
 
-#define USE_VSYSCALL_GETTIME 0
-#define USE_VDSO_GETTIME     1
+#define USE_VSYSCALL_GETTIME 1
+#define USE_VDSO_GETTIME     0
 #define USE_CLOCK_GETTIME    1
 
 #define USE_ARCH_RDRAND 0

 ```

**Comment by dimakuv** [comment]
@yamahata Isaku added vDSO to our Graphene. I wonder if he has any comments on this.

**Comment by yamahata** [comment]
Those are two different ones.

My vDSO support is to make libOS expose libOS vDSO to app.
On the other hand, the one in this issue is for libpal (pal/Linux in this case) to use vDSO in host to get time. So vdso support in LibOS is unrelated.

At a rough look at the related code in Pal/Linux, I'm not sure what causes the difference of stability.
Is stack size too small? Can we try to increase THREAD_STACK_SIZE in pal_linux_defs.h?
For example 64KB? 8KB seems a bit aggressive.

**Comment by yamahata** [comment]
I looked at it a bit deeper. Those are my thoughts.
I haven't done any benchmark. Just thought based on reading codes.

USE_VSYSCALL_GETTIME doesn't seem to make sense.
USE_VSYSCALL_GETTIME should be removed.

USE_CLOCK_GETTIME:
Why is this introduced? Did ChiaChe try to measure performance difference?
If it was simply for benchmark, we can  remove this #ifdefs.

USE_VDSO_GETTIME:
This switch is to user vdso in host or not.
Anyway those ifdefs are very ugly. If we don't have special reasons, those ifdefs should be removed.
I don't see why this causes stability. I can think of only stack.

**Comment by stefanberger** [comment]
I must say I am glad these ifdefs are there since they allow me to disable 'something' that causes instability. 

The randomness of the instability may hint at the random address of the vDSO. Maybe it has something to do with the range of randomness. Just guesses here...

**Comment by mkow** [comment]
@stefanberger Do you still have those stability issues? If so, could you give us a reproduction steps?

**Comment by stefanberger** [comment]
@mkow I am now running a 5.7.15 kernel on Fedora 31 and the PAL test suite and the 2 test suite for LibOS are passing. LTP also passes when started using this command line: `env -i PATH=$PATH make ltp.xml` (I see failures when using plain 'make ltp.xml`). Cheers!
