### ISSUE TITLE
Crashes due to ASLR on the brk (noticed on ppc64)

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#1472]
I noticed that nginx wasn't working reliably anymore on ppc64 port. The reason was that there is randomization occurring on the brk that causes the program to fail. I do not know whether the same problem occurs on x86_64 since I am only running a limited amount of programs there. Though here's the patch that I am using for solving the issue on powerpc64:

```
iff --git a/LibOS/shim/src/sys/shim_brk.c b/LibOS/shim/src/sys/shim_brk.c
index 719e77c0..89c76171 100644
--- a/LibOS/shim/src/sys/shim_brk.c
+++ b/LibOS/shim/src/sys/shim_brk.c
@@ -62,7 +62,7 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
             && brk_max_size <= (uintptr_t)PAL_CB(user_address.end)
             && (uintptr_t)brk_start < (uintptr_t)PAL_CB(user_address.end) - brk_max_size) {
         size_t offset = 0;
-#if ENABLE_ASLR == 1
+#if ENABLE_ASLR == 1 && !defined(__powerpc64__)
         int ret = DkRandomBitsRead(&offset, sizeof(offset));
         if (ret < 0) {
             return -convert_pal_errno(-ret);
@@ -72,6 +72,8 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
         offset %= MIN((size_t)0x2000000,
                       (size_t)((char*)PAL_CB(user_address.end) - brk_max_size - (char*)brk_start));
         offset = ALLOC_ALIGN_DOWN(offset);
+#else
+        int ret;
 #endif
         brk_start = (char*)brk_start + offset;
 
@@ -86,8 +88,10 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
             return ret;
         }
     } else {
+#if !defined(__powerpc64__)
         /* Let's try mapping brk anywhere. */
         brk_start = NULL;
+#endif
     }
 
     if (!brk_start) {
```

I don't think the code is right. With ASLR enabled we basically will always get a random brk but we cannot have this after a fork()!

Either we get randomization in the if branch: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_brk.c#L61

Or then via brk_start in the else branch: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_brk.c#L88

You may be lucky if your architecture in general or a particular program doesn't use brk, but if it does it may not work (correctly).

**Comment by dimakuv** [comment]
@boryspoplawski Please take a look, this is your recent changes of `brk()`.

**Comment by dimakuv** [comment]
Btw, I also noticed a couple crashes of the `brk01` LTP test. Probably related to this?

**Comment by boryspoplawski** [comment]
@dimakuv Could you send me some more details about those crashes (which pipeline etc.)? I tried locally with and without debug and couldn't reproduce it.

@stefanberger As far as this code might be the reason of fails, I don't think it's exactly what you described. After all this is what ASLR is for: randomize the memory layout (including brk). `fork()` should not be an issue - we have a checkpointing mechanism that restores all user memory, so this function should not be run in the child process.
There is one thing in this code that I was unsure about: how other archs (than x86) will behave with brk in a random memory place i.e. not necessarily right after main binary. From a quick glance at the Linux kernel code I don't see any issues or ppc specific handling of brk. Do you have any idea if that could be an issue?

**Comment by stefanberger** [comment]
@boryspoplawski It seems glibc does run it again and when the n different children all passed in the same parameter to brk() they all have to get the same result back but don't due to the ASLR. I think it matters in which order brk() is called relative to fork() or whether it is called again after fork(). ASLR must not kick in after fork() or we get failures. For me this patch does solve a problem ending up in crashes  IF the passed in brk was < brk.brk_start.In fact nginx was working 20% of the time if the passed in brk address happened to be > brk.brk_start.

**Comment by stefanberger** [comment]
Here are the grep's from a bad run (without the patch):

```
$ grep shim_brk out.log 
[     1] ---- shim_brk(0x0) = 0x5d3a6f190000
[     1] ---- shim_brk(0x0) = 0x5d3a6f190000
[     1] ---- shim_brk(0x5d3a6f1c0000) = 0x5d3a6f1c0000
[     2] ---- shim_brk(0x5d3a6f200000) = 0x5f7870f00000
[     3] ---- shim_brk(0x5d3a6f200000) = 0x79d4c1160000
[     4] ---- shim_brk(0x5d3a6f200000) = 0x79d4c0000000
[     5] ---- shim_brk(0x5d3a6f200000) = 0x5139a19d0000
```

All brk() with the same input parameter result in different output parameters. This is bad!
Looking into it deeper we see failures like this one here (luckily) following right after the brk statement:

```
[     2] ---- shim_brk(0x5d3a6f200000) = 0x5f7870f00000
[     2] memory fault at 0x5d3a6f1d0f88 (IP = 0x5d3a6ee1ed48)
[     2] SIGSEGV handled
[     2] run signal handler 0x71c6f35558f0 (11, 0x71c6f36e0820, 0x71c6f36e08a8)
```

Now this is a good run with the patch applied:
```
 grep shim_brk out.log 
[     1] ---- shim_brk(0x0) = 0x79d4bfce0000
[     1] ---- shim_brk(0x0) = 0x79d4bfce0000
[     1] ---- shim_brk(0x79d4bfd10000) = 0x79d4bfd10000
[     2] ---- shim_brk(0x79d4bfd50000) = 0x79d4bfce0000
[     3] ---- shim_brk(0x79d4bfd50000) = 0x79d4bfce0000
[     4] ---- shim_brk(0x79d4bfd50000) = 0x79d4bfce0000
[     5] ---- shim_brk(0x79d4bfd50000) = 0x79d4bfce0000
```

I am using this patch here now:

```
diff --git a/LibOS/shim/src/sys/shim_brk.c b/LibOS/shim/src/sys/shim_brk.c
index 719e77c0..cd82b0da 100644
--- a/LibOS/shim/src/sys/shim_brk.c
+++ b/LibOS/shim/src/sys/shim_brk.c
@@ -58,11 +58,15 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
         return -EINVAL;
     }
 
+    if (brk_start && brk_start == brk_region.brk_start) {
+        goto skip;
+    }
+
     if (brk_start && brk_start <= PAL_CB(user_address.end)
             && brk_max_size <= (uintptr_t)PAL_CB(user_address.end)
             && (uintptr_t)brk_start < (uintptr_t)PAL_CB(user_address.end) - brk_max_size) {
         size_t offset = 0;
-#if ENABLE_ASLR == 1
+#if ENABLE_ASLR == 1 && !defined(__powerpc64__)
         int ret = DkRandomBitsRead(&offset, sizeof(offset));
         if (ret < 0) {
             return -convert_pal_errno(-ret);
@@ -72,6 +76,8 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
         offset %= MIN((size_t)0x2000000,
                       (size_t)((char*)PAL_CB(user_address.end) - brk_max_size - (char*)brk_start));
         offset = ALLOC_ALIGN_DOWN(offset);
+#else
+        int ret;
 #endif
         brk_start = (char*)brk_start + offset;
 
@@ -86,8 +92,10 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
             return ret;
         }
     } else {
+#if !defined(__powerpc64__)
         /* Let's try mapping brk anywhere. */
         brk_start = NULL;
+#endif
     }
 
     if (!brk_start) {
@@ -103,6 +111,7 @@ int init_brk_region(void* brk_start, size_t data_segment_size) {
         }
     }
 
+skip:
     brk_region.brk_start = brk_start;
     brk_region.brk_current = brk_region.brk_start;
     brk_region.brk_end = (char*)brk_start + brk_max_size;

```

Of course one needs a brk-critical app to test this with, otherwise there will be sunshine all around. For me it was *only* nginx that was failing.

**Comment by dimakuv** [comment]
@stefanberger Do you know what Nginx (or underlying Glibc logic) tries to achieve with these `brk()` calls? In particular, why would Nginx/Glibc assume the following about brk:

> ... when the n different children all passed in the same parameter to brk() they all have to get the same result back [...] ASLR must not kick in after fork() or we get failures ...

The man page for `brk()` is very vague in this regard. It would be helpful to get more info what Glibc/Nginx *actually* assume about brk. And given that Nginx is that popular, we should definitely support its quirks.

**Comment by boryspoplawski** [comment]
@stefanberger I meant `init_brk_region` - this function is only ran once at process startup, `fork` doesn't use it. `brk` itself can be called multiple times, sure, but it does no address randomization.
The grep results are super weird, it should not behave like that. Are you running this on a code pushed somewhere, so I could have a look at it? If yes then a full log would be helpful too.

**Comment by boryspoplawski** [comment]
@dimakuv ASLR is set-up at the process creation, not later, so all children have to get the same address. The thing is with the current implementation they should be getting it ...

**Comment by dimakuv** [comment]
@boryspoplawski Got it. Then yes, something truly strange happens in child processes.

**Comment by stefanberger** [comment]
From the malloc manpage:


"To scalably handle memory allocation  in multithreaded  applications,  glibc creates additional memory allocation arenas if mutex contention is detected. Each arena is a large region of memory that is internally allocated by the system (using brk(2) or mmap(2)), and managed with its own mutexes."

So I don't know how to cause brk() to be used on x86_64 but what you need is an application that does this in multiple child processes to find this 'sleeping bug'. I did not see brk being used with nginx on x86_64, so this is not the right app for it.

**Comment by boryspoplawski** [comment]
Ok, I've found the issue: `brk_init_region` is indeed ran in the child as well. Seems like the whole `shim_init` is ran in child as well. I need to debug it a bit.

**Comment by stefanberger** [comment]
> Ok, I've found the issue: `brk_init_region` is indeed ran in the child as well. Seems like the whole `shim_init` is ran in child. I need to debug it a bit - I thought child does not need to run this.

Yes, this here **always** runs:
```
[     2] adding file:install/sbin/nginx as runtime object loaded at 0x79d4bfbc0000-0x79d4bfce0000
```
