### ISSUE TITLE
Not able to run enclave after modifying sgx_main.c

### ISSUE THREAD

**Issue by Franklin-pixel** [oscarlab/graphene#1473]
Hey , guys so I tried modifying the Pal/host/Linux-SGX/sgx_main.c by adding a printf statement. It builds successfully , but when I run using the pal loader I get the error message. `Cannot find enclave image: libpal-Linux-SGX.so `. I have tried similar modifications to the graphene codebase and got this error each time. Why does this occur ?

**Comment by dimakuv** [comment]
@Franklin-pixel Are you using the newest (`master` branch) version of Graphene? What is `libpal-enclave.so`? We don't have such a file. What we have is `libpal-Linux-SGX.so`.

I have a feeling you're using some very old Graphene version (tag 0.6?). Or you're using some very old manifest which has something like `sgx.enclave_pal_file = file:libpal-enclave.so`...

**Comment by Franklin-pixel** [comment]
@dimakuv  , sorry for mixing things up. The message said ,`cannot load enclave image: libpal-Linux-SGX.so` . It is the branch with protected file system.

**Comment by dimakuv** [comment]
Do you have this file built? It must be under `<graphene>/Runtime/`.

What application are you trying to run? What is the manifest of this application? Do you have `libpal-Linux-SGX.so` mentioned somewhere in the manifest (you shouldn't: let Graphene use the default location for this file).

**Comment by Franklin-pixel** [comment]
Hey @dimakuv it was there but I hadn't built the entire repository properly. Specially I hadn't used make but only make SGX=1 and rebuilt drivers. Thank you so much for the support.
