### ISSUE TITLE
sgx nginx example error: libnss_systemd.so.2 is denied. 

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1498]
I am new to graphene. When i try to run the nginx example, i got the error. Any advice would be appreciated. Thanks in advance.

OS: Ubuntu 18.04 
SGX: [https://github.com/intel/linux-sgx](url) master branch
All files under `graphene` project is not changed.   
Maybe i need to add something in `graphene/Examples/nginx/nginx.manifest.sgx`? I am not sure.
But despite this problem, I can still visit `http://127.0.0.1:8002/random/10K.1.html`

` root@k8s-master:/home/pengfei/graphene/Examples/nginx# SGX=1 ./pal_loader ./nginx.manifest -c conf/nginx-graphene.conf`
Accessing file:/lib/x86_64-linux-gnu/libnss_systemd.so.2 is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/lib/x86_64-linux-gnu/libnss_systemd.so.2 is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/lib/x86_64-linux-gnu/libnss_systemd.so.2 is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/lib/x86_64-linux-gnu/libnss_systemd.so.2 is denied. (Unknown error) This file is not trusted or allowed.

**Comment by mkow** [comment]
Try adding this library here: https://github.com/oscarlab/graphene/blob/a179c79e3cb27431092f1e41fa02f81529f981bc/Examples/nginx/nginx.manifest.template#L72-L75
I checked, and we have the same warning on our Jenkins, but only on 18.04. If you want you can try to fix this and submit a PR, if not we can try to find someone else to fix it. The only tricky part is that this should be added only on Ubuntu 18.04, so you'd need to port the conditional lines support from other examples. See e.g.: https://github.com/oscarlab/graphene/blob/a179c79e3cb27431092f1e41fa02f81529f981bc/Examples/pytorch/pytorch.manifest.template#L138-L141

**Comment by justalittlenoob** [comment]
@mkow  Your suggestion is perfect. I truly appreciate your timely help.
