### ISSUE TITLE
Recent moves of PAL header files -- made accessible to LibOS ? An issue?

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#1507]
So far the following PAL commits moved header files from PAL Linux/Linux-SGX into the public Pal/include/... while deduplicating some of those header files. Is the new location of these header files a problem? If it is, I would move them under a hierarchy under Pal/src/host/{Linux,Linux-SGX}/include before they get entangled too deeply. We'd loose the deduplication on the way, though.

 Pal/src/host/Linux/elf-x86_64.h → Pal/include/arch/x86_64/Linux/elf-arch.h  (https://github.com/oscarlab/graphene/commit/f781cc919256d26fefc69378adf07a7e58eb0516)
 Pal/src/host/Linux-SGX/include/ucontext.h → Pal/include/arch/x86_64/Linux/ucontext.h (https://github.com/oscarlab/graphene/commit/98187f6b93ac5bccf05ef71d85267c752449d1f6)
  Pal/src/host/Linux-SGX/include/sigcontext.h → Pal/include/arch/x86_64/Linux/sigcontext.h  (https://github.com/oscarlab/graphene/commit/ea2c54d39ce90a0bbcba52aa5c8931fd5af4fb57)
  Pal/src/host/Linux-SGX/include/sigset.h → Pal/include/arch/x86_64/Linux/sigset.h (https://github.com/oscarlab/graphene/commit/ea2c54d39ce90a0bbcba52aa5c8931fd5af4fb57) 
  Pal/src/host/Linux-SGX/sysdep-x86_64.h → Pal/include/arch/x86_64/Linux/sysdep-arch.h (https://github.com/oscarlab/graphene/commit/8bbe609bb9d43a0857a8b8b279181beabee2023d)
   Pal/src/dl-machine-x86_64.h → Pal/include/arch/x86_64/dl-machine.h (https://github.com/oscarlab/graphene/commit/5354f12a1739e87cf5429ec97993756da3c84bab)

**Comment by dimakuv** [comment]
I don't think moving PAL-private headers under `Pal/include/arch/...` is correct. Some PAL headers have nothing to do with architecture details (examples are `pal_host.h` and `pal_linux.h` files). So I would be against this proposal.

I see two solutions:

1. Put a guard `#ifndef IN_PAL  #error CANNOT INCLUDE THIS IN LIBOS` or similarly `#ifdef IN_PAL ...declare all ... #else ...declare only LibOS visible...`. We do it already in several headers, e.g.: https://github.com/oscarlab/graphene/blob/8f5a0d20d350734fd020dd3ec367e294ca89cf1f/Pal/src/host/Linux/pal_host.h#L26.

2. Create an additional `Pal/include/private/...` subdir, but it will only complicate things even further.

I'd prefer option 1.

**Comment by stefanberger** [comment]
@dimakuv I was mostly concerned about the moves we already have done due to comments from @yamahata . They are not providing API prototypes of the PAL for others to call, so from that perspective the moves would be fine. Otherwise they contain inline functions that may not be of use to LibOS for example. So worst case could be that they cause clashes due to structure being redefined, but that's not the case right now.

**Comment by stefanberger** [comment]
@dimakuv Let's use `#ifndef IN_PAL` then to hide things.

**Comment by dimakuv** [comment]
Sounds good! At least for now it should work fine.

**Comment by yamahata** [comment]
I'm fine with IN_PAL trick.
