### ISSUE TITLE
Building Graphene-SGX encountered an error "ld: cannot find -lc"

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1525]
## Description of the problem

Building Graphene-SGX based on https://graphene.readthedocs.io/en/latest/building.html .  Previous steps works well. But, build Graphene-SGX encountered an error.

## Steps to reproduce

```
# In Graphene root dir
make SGX=1
```

## Actual results

```
gcc -Wall -fPIC -O2 -std=c11 -c debugger/sgx_gdb.c -o debugger/sgx_gdb.o
ld -shared debugger/sgx_gdb.o -o debugger/sgx_gdb.so -lc
ld: cannot find -lc
Makefile:79: recipe for target 'debugger/sgx_gdb.so' failed
make[3]: *** [debugger/sgx_gdb.so] Error 1
make[3]: Leaving directory '/home/fabric/working/graphene/Pal/src/host/Linux-SGX'
Makefile:93: recipe for target 'host/Linux-SGX/libpal-Linux-SGX.a' failed
make[2]: *** [host/Linux-SGX/libpal-Linux-SGX.a] Error 2
make[2]: Leaving directory '/home/fabric/working/graphene/Pal/src'
```

Seems that gcc is looking for `libc.a`, which comes with gcc.2.19 package.

**Comment by dimakuv** [comment]
What is the Linux distribution you're using?

The error that you see `cannot find -lc` means that the system linker (`ld`) cannot find Glibc (the standard C library). This is highly unusual. I can only assume that you're trying to build on a Musl-based Linux distribution such as Alpine. This won't work unfortunately.

We are currently supporting Ubuntu 16.04, 18.04, and 20.04. We are also aware of successful deployments of Graphene on Fedora and Clear Linux (also probably RHEL, but I don't remember).

**Comment by qiyuangong** [comment]
@dimakuv 
Thank you for reply! :)

I'm using Ubuntu 18.04, and an older commits. I will try master later.

**Comment by qiyuangong** [comment]
Master branch works well. :)
Issue closed.
