### ISSUE TITLE
docker-entrypoint issue when using GSC build docker images

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1530]
I am trying to using [GSC](https://github.com/oscarlab/graphene/tree/191f6550c2c144f9fe3a86df27c8844c795d3485/Tools/gsc) to convert standard docker images to sgx based.    

If the image doesn't have a `docker-entrypoint`, such as `nginx`, everything goes well.  
But when the image has a `docker-entrypoint` sh file, such as `redis`, the generated  `gsc-redis` image cannot work.  

It seems that GSC doesn't support docker images which has a `docker-entrypoint` file, right?   
If so, is there any way to solve this problem?

Any advice would be appreciated. Thanks in advance.

**Comment by vahldiek** [comment]
The issue here is that the entrypoint is not an executable binary. In its current implementation GSC does not understand this difference as I recently documented in the [limitations of GSC](https://github.com/oscarlab/graphene/issues/1520).

As a result,  GSC asks Grapehene to work with a executable file not binary. A simple workaround is to make the interpreter which is an executable binary explicit. You could do this by creating another docker image based on the following docker file:
``` 
FROM <your-favorite-image>

ENTRYPOINT ["<path to interpreter>", "<previous entrypoint script>"]
CMD ["<previous CMD, if there was any>"]
```

This will notify GSC and Graphene that the interpreter should be called. The long term solution will recognize that the entrypoint is a script and detect which interpreter to call instead.

**Comment by justalittlenoob** [comment]
@vahldiek   
Your detailed instructions let me know more about GSC and Graphene. Thank you very much.  
According to your advice, i remake the `redis` docker image.  But when i run `docker run` command, there is an error  
`pal-sgx-get-token: error: argument --sig/-sig: can't open 'sh.sig': [Errno 2] No such file or directory: 'sh.sig'`    

My steps are as follows. Did i miss something?  (Ubuntu 18.04)
1. `cat Dockerfile`  
    `From redis:latest`
    `ENTRYPOINT ["/bin/sh", "docker-entrypoint.sh"]`
    `CMD ["redis-server"]`  

2. `docker build -t zredis:0.1 .`

3. `cat redis.manifest`
    `sgx.allow_file_creation = 1`
    `sgx.enclave_size = 4G`
    `sgx.thread_num = 8`

4. `cat config.json`
    `{`
        `"distro": "ubuntu18.04",`
        `"graphene_repository": "https://github.com/oscarlab/graphene.git",`
        `"graphene_branch": "master",`
        `"sgxdriver_repository": "https://github.com/intel/linux-sgx-driver.git",`
        `"sgxdriver_branch": "sgx_driver_2.6"`
    `}`

5. `./gsc build zredis:0.1 redis.manifest`

6. `docker run --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket --name zredis-test -p 6379:6379 -it gsc-zredis:0.1`
+ executable=sh
+ /graphene/signer/pal-sgx-get-token -output sh.token -sig sh.sig
usage: pal-sgx-get-token [-h] --sig SIGNATURE --output OUTPUT
pal-sgx-get-token: error: argument --sig/-sig: can't open 'sh.sig': [Errno 2] No such file or directory: 'sh.sig'

**Comment by vahldiek** [comment]
The error message that you show hints at an issue in step 5. Step 5 should have generated a signature (if successful). Could you share the output of one of the steps in step 5? In particular, the step which invokes `finalize_manifests.py`.

Besides this issue, you will run into trouble, since you only specified a single manifest file. You'll have to at least specify two manifest files (since you're invoking sh and redis). So please change step 5 into `./gsc build ... sh.manifest redis.manifest`. Both files should have the same enclave memory size and otherwise mention the application-specific manifest options.

**Comment by justalittlenoob** [comment]
@vahldiek   
Hi, according to you advice. I changed step 5, and the error message is as below.  
I am not sure the `sh.manifest` will work.
`cat sh.manifest`
sgx.enclave_size = 4G

`cat redis.manifest`
sgx.allow_file_creation = 1
sgx.enclave_size = 4G
sgx.thread_num = 8  

`./gsc build zredis:0.1 sh.manifest redis.manifest` 
 ---> dd239ccf3f52
Step 16/20 : COPY *.manifest ./

 ---> 031ac04c2f8f
Step 17/20 : COPY finalize_manifests.py /

 ---> f9d3d63b0a9e
Step 18/20 : RUN chmod u+x apploader.sh     && python3 /finalize_manifests.py / sh.manifest redis.manifest     && rm -f /finalize_manifests.py

 ---> Running in 42d743017da5
Found 12546 files in '/'.
Setting LD_LIBRARY_PATH to '/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:'.
redis.manifest:
Traceback (most recent call last):
  File "/finalize_manifests.py", line 154, in <module>
    main(sys.argv)
  File "/finalize_manifests.py", line 116, in main
    binary_path = get_binary_path(executable)
  File "/finalize_manifests.py", line 48, in get_binary_path
    stderr=subprocess.STDOUT, shell=True).decode()
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'which redis' returned non-zero exit status 1.

Failed to build graphenized image for zredis:0.1

**Comment by vahldiek** [comment]
Sorry to not have mentioned this in the previous post, but the manifest name has to be ``app.manifest`` where app is the binary that is visible under the current ``$PATH`` environment variable. The program fails, since this is not the case.

I think the actual binary of redis may be called ``redis-server`` and hence, the manifest needs to be called ``redis-server.manifest``. GSC only infers the executable for the first binary (since it can due to the entrypoint). For the remainder of the binaries, the manifest name is reused. So please change to 

```
./gsc build zredis:0.1 sh.manifest redis-server.manifest
```

or whatever the redis server binary is actually called.

Thanks!

**Comment by justalittlenoob** [comment]
@vahldiek 
After change the manifest name, the image can be built. But when `docker run`, still has the error. There is no signature file generated.   
`graphene/Tools/gsc/gsc-zredis:0.1# ls`
apploader.sh  Dockerfile  finalize_manifests.py  redis-server.manifest  sh.manifest  


`./gsc build zredis:0.1 sh.manifest redis-server.manifest`
 ---> 288f1a2e5a73
Step 17/20 : COPY finalize_manifests.py /

 ---> 6bb6ea960c8d
Step 18/20 : RUN chmod u+x apploader.sh     && python3 /finalize_manifests.py / sh.manifest redis-server.manifest     && rm -f /finalize_manifests.py

 ---> Running in d9d9a747885d
Found 12546 files in '/'.
Setting LD_LIBRARY_PATH to '/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:'.
redis-server.manifest:
        Setting exec file to '/usr/local/bin/redis-server'.
        Wrote redis-server.manifest.
        Generated redis-server.manifest.sgx and generated signature.
sh.manifest:
        Setting exec file to '/bin/sh'.
        Wrote sh.manifest.
        Generated sh.manifest.sgx and generated signature.
 ---> 37d5d9e6e35d
Step 19/20 : ENTRYPOINT  ["/bin/sh", "./apploader.sh"]

 ---> Running in 94ec488167fd
 ---> a6308104800f
Step 20/20 : CMD []

 ---> Running in 53f26c588dba
 ---> c9149908aab2
Successfully built c9149908aab2
Successfully tagged gsc-zredis:0.1
Successfully graphenized docker image zredis:0.1 into docker image gsc-zredis:0.1

`docker run --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket --name zredis-test -p 6379:6379 -it gsc-zredis:0.1`

+ executable=sh
+ /graphene/signer/pal-sgx-get-token -output sh.token -sig sh.sig
usage: pal-sgx-get-token [-h] --sig SIGNATURE --output OUTPUT
pal-sgx-get-token: error: argument --sig/-sig: can't open 'sh.sig': [Errno 2] No such file or directory: 'sh.sig'

**Comment by vahldiek** [comment]
The output of finalize_manifest.py does not show an error, but it is incomplete (no mention of a generation of a manifest for redis-server). Let me try to replicate this issue and get back to you (likely tomorrow).

If you want to debug yourself, try running the finalize_manifest.py script at this stage of the gsc build yourself and see why the invocation of pal_signer fails or what its output is...

**Comment by justalittlenoob** [comment]
@vahldiek   
Thanks, i'll have a try and looking forward to your results.

**Comment by justalittlenoob** [comment]
@vahldiek   
Hi,  I've tried something. It seems that both`.sgx` and `.sig` file are successfully generated. But for unknown reasons, `pal-sgx-get-token` didn't work.    

Do you have any suggestions？

**Comment by vahldiek** [comment]
Could you provide some output, otherwise it is very though to know the error...

Thanks,
Anjo

**Comment by justalittlenoob** [comment]
@vahldiek   
Hi Anjo, thank you for your patience. I also hope to generate some useful output but unfortunately there is no useful information. Every step looks normal without error.  Have you tried to replicate this issue? Or you don't have that problem? It would be great if you can tell me your build/test steps(including config and manifest files), so i can have a try according to it.
  
The only error message is when running   
`docker run --device=/dev/gsgx --device=/dev/isgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket --name zredis-test -p 6379:6379 -it gsc-zredis:0.1`  

executable=sh
/graphene/signer/pal-sgx-get-token -output sh.token -sig sh.sig
usage: pal-sgx-get-token [-h] --sig SIGNATURE --output OUTPUT
pal-sgx-get-token: error: argument --sig/-sig: can't open 'sh.sig': [Errno 2] No such file or directory: 'sh.sig'

**Comment by vahldiek** [comment]
This seems again to be an error related to your gsc build process. The 'sh.sig' file should have been created during `gsc build` command. The important output would be from the `gsc build`. I think this could be again related to the finalize_manifests.py not producing enough error output and silently failing.

I'll try to have a look at this over the next couple of days and try to reproduce it.

**Comment by vahldiek** [comment]
GSC currently does not support scripts as entrypoints. Please see issue #1728 for details and a workaround.
