### ISSUE TITLE
Unable to install Graphene-SGX on Ubuntu 18.04

### ISSUE THREAD

**Issue by noodlehair-git** [oscarlab/graphene#1533]
I am not able to install Graphene properly (https://graphene.readthedocs.io/en/latest/building.html). While running the sample code, I am getting the following error

```Cannot open device /dev/gsgx. Please make sure the Graphene SGX kernel module is loaded```.

This is probably because, during the installation command 
```sudo insmod gsgx.ko```, I got the following error 

```insmod: ERROR: could not insert module gsgx.ko: Required key not available```.

Rest all (related to SGX) seems fine as I was able to run sample SGX examples and ```sudo service aesmd status``` gives

    aesmd.service - Intel(R) Architectural Enclave Service Manager
       Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
       Active: active (running) since Fri 2020-05-22 16:28:55 EDT; 2h 45min ago
      Process: 4404 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
      Process: 4403 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
      Process: 4402 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
      Process: 4400 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
      Process: 4391 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
      Process: 4388 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
      Process: 4369 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
     Main PID: 4405 (aesm_service)
        Tasks: 4 (limit: 4915)
       CGroup: /system.slice/aesmd.service
               └─4405 /opt/intel/sgx-aesm-service/aesm/aesm_service

**Comment by dimakuv** [comment]
It looks like your system has Secure Boot enabled. Please check this: https://askubuntu.com/questions/762254/why-do-i-get-required-key-not-available-when-install-3rd-party-kernel-modules.

**Comment by noodlehair-git** [comment]
Thanks for the response. Sure, I'll disable and try once. Any specific reason on why should secure boot be a problem? @dimakuv
