### ISSUE TITLE
Try to run ray (multi-process) with Graphene-SGX

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1539]
## Description of the problem
Try to run ray (https://github.com/ray-project/ray) with Graphene-SGX. Based on https://github.com/oscarlab/graphene/tree/master/Examples/python-scipy-insecure .

Ray will launch 2 process with code below.

`scripts/test-ray.py`

```python
#!/usr/bin/env python3

import ray

ray.init(memory=100 * 1024 * 1024,
        object_store_memory=80 * 1024 * 1024,
        driver_object_store_memory=20 * 1024 * 1024)

@ray.remote
def f(x):
        return x * x

futures = [f.remote(i) for i in range(1)]
print(ray.get(futures))

```

## Steps to reproduce
```
# install ray into /usr/lib/python3/dist-packages
pip3 install ray
make PYTHONPATH=/usr PYTHONVERSION=python3.6 SGX=1
SGX=1 ./pal_loader python.manifest scripts/test-ray.py
```

## Expected results
```
[0]
```
## Actual results
```
Accessing file:/usr/bin/gcc is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/ld is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/gcc is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/ld is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/lib/x86_64-linux-gnu/libyaml-0.so.2 is denied. (Unknown error) This file is not trusted or allowed.
```

Seems that ray is looking for `gcc` and `ld`.

**Comment by dimakuv** [comment]
Yes, it looks like you need to add manifests for `gcc` and `ld` and mark them as `sgx.trusted_children` in the Python manifest.

You can look at this example: https://github.com/oscarlab/graphene/tree/master/Examples/gcc. Notice how the main executable (`gcc`) has trusted_children in its manifest: https://github.com/oscarlab/graphene/blob/master/Examples/gcc/gcc.manifest.template.

Btw, Graphene also complains about the shared library `/usr/lib/x86_64-linux-gnu/libyaml-0.so.2`. Simply add it to the list of `sgx.trusted_files`.

**Comment by qiyuangong** [comment]
OK. I will try that later. :)

Another question is that: Ray is trying to launch a socket for connection (multi-node). I guess `gcc` and `ld` is involved in this stage. Do I need to trust network related libs?

**Comment by dimakuv** [comment]
> Do I need to trust network related libs?

I'm unsure what you mean by this. You typically add all libraries that you trust to the manifest as `sgx.trusted_file = file:<path-to-trusted-library>`. This way, when you build the `manifest.sgx` file, the library is measured, and its hash is appended to the manifest. Afterwards, since the `manifest.sgx` file is a part of the MRENCLAVE (SGX enclave) measurement, the trust in a particular version of the library is gained transitively. Also note that Graphene's runtime loader verifies that the measurement of the currently loaded library corresponds to the expected one from the `manifest.sgx` file.

**Comment by qiyuangong** [comment]
I have add `gcc` and `ld` with  `trusted_children` in manifest, and copy `*.sig` and `*.sgx`.

Still encounter `gcc` and `ld` error:
```
Accessing file:/usr/bin/gcc is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/ld is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/gcc is denied. (Unknown error) This file is not trusted or allowed.
Accessing file:/usr/bin/ld is denied. (Unknown error) This file is not trusted or allowed.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ray/thirdparty_files/psutil/_common.py", line 405, in wrapper
    return cache[key]
KeyError: (('/proc',), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ray/thirdparty_files/psutil/_pslinux.py", line 309, in <module>
    set_scputimes_ntuple("/proc")
  File "/usr/lib/python3/dist-packages/ray/thirdparty_files/psutil/_common.py", line 407, in wrapper
    ret = cache[key] = fun(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/ray/thirdparty_files/psutil/_pslinux.py", line 276, in set_scputimes_ntuple
    with open_binary('%s/stat' % procfs_path) as f:
  File "/usr/lib/python3/dist-packages/ray/thirdparty_files/psutil/_common.py", line 713, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/stat'
```

Another error is related to child process
```
2020-05-28 10:01:03,903 INFO resource_spec.py:212 -- Starting Ray with 0.1 GiB memory available for workers and up to 0.08 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
Traceback (most recent call last):
  File "scripts/test-ray.py", line 7, in <module>
    driver_object_store_memory=20 * 1024 * 1024)
  File "/usr/lib/python3/dist-packages/ray/worker.py", line 767, in init
    ray_params=ray_params)
  File "/usr/lib/python3/dist-packages/ray/node.py", line 177, in __init__
    self.start_head_processes()
  File "/usr/lib/python3/dist-packages/ray/node.py", line 649, in start_head_processes
    self.start_redis()
  File "/usr/lib/python3/dist-packages/ray/node.py", line 473, in start_redis
    fate_share=self.kernel_fate_share)
  File "/usr/lib/python3/dist-packages/ray/services.py", line 769, in start_redis
    fate_share=fate_share)
  File "/usr/lib/python3/dist-packages/ray/services.py", line 943, in _start_redis_instance
    fate_share=fate_share)
  File "/usr/lib/python3/dist-packages/ray/services.py", line 514, in start_ray_process
    preexec_fn=preexec_fn if sys.platform != "win32" else None)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1365, in _execute_child
    raise child_exception_type(err_msg)
subprocess.SubprocessError: Exception occurred in preexec_fn.

```

**Comment by dimakuv** [comment]
Please attach your generated `manifest.sgx` file. Something is wrong in the way GCC and LD are added.

Did you also add the `/usr/bin` FS mount point to the manifest?

**Comment by qiyuangong** [comment]
`gcc` and `ld` error are caused by `trusted_files`. I forgot to add `/usr/bin/gcc` and `/usr/bin/ld` into trusted files.

**Comment by qiyuangong** [comment]
No more gcc and ld errors. Just infinity debug message. :( 
```
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x2c39e520,2,-1) ... poll

```

**Comment by qiyuangong** [comment]
No output. That's the strange part. Seem that code is freeze on init stage.

**Comment by dimakuv** [comment]
What do you mean no output? I meant the whole debug output from Graphene (the part of it you copy-pasted in your previous message).

To collect the whole output from Graphene, I typically use `tee` like this:
```sh
SGX=1 ./pal_loader ./myapp 2>&1 | tee myapp.log
```

I'd like to peek into your collected `myapp.log` output.

**Comment by qiyuangong** [comment]
Still cannot work. Seems that main process is creating and killing child-process in an infinite loop.

Attached is a debug.log. I deleted infinite log in tails.
[debug.log](https://github.com/oscarlab/graphene/files/4727242/debug.log)

**Comment by qiyuangong** [comment]
I also tried this PR (https://github.com/oscarlab/graphene/pull/1542). Still doesn't work for me. The same infinity loop.

**Comment by qiyuangong** [comment]
@dimakuv 
Another question is that: ray is launching a few Python child process. Do I need to add these Python child process into `trusted_children` .

**Comment by dimakuv** [comment]
@qiyuangong Sorry for the late response. No, if your child processes are the same Python executable, then *no*, you don't need to specify them as `trusted_children`.

**Comment by qiyuangong** [comment]
I will check if #1607 fixed this issue. :)

**Comment by mkow** [comment]
@qiyuangong any updates? #1607 was merged, if it solves your problem then please close this issue.

**Comment by qiyuangong** [comment]
@mkow #1607 solved current problem. :)
Issue closed
