### ISSUE TITLE
Importing scapy, timeloop, socks, flask, tbselenium, selenium

### ISSUE THREAD

**Issue by noodlehair-git** [oscarlab/graphene#1547]
I wanted to import ```scapy, timeloop, socks, flask, tbselenium, selenium``` in the ```python-manifest``` file. So, I added the dependencies to first make ```socks``` work, but I still get import error. Here is my manifest file. 
[manifest.zip](https://github.com/oscarlab/graphene/files/4706343/manifest.zip)

**Comment by dimakuv** [comment]
Did you change `python.manifest` file? You are supposed to change the template: `python.manifest.template`. The `python.manifest` file is auto-generated from the template.

What do you mean by "I get import error"? Please re-build your Python example with `make SGX=1 DEBUG=1`, save the log output, and copy-paste it here (or figure out yourself what Graphene wants from you).

**Comment by noodlehair-git** [comment]
Thank you so much for your reply. I'm pretty much new to SGX and Graphene and hence having issues figuring out. I have attached my log file as well as the manifest template I am using. 

[log.zip](https://github.com/oscarlab/graphene/files/4719882/log.zip)
[manifest.zip](https://github.com/oscarlab/graphene/files/4719884/manifest.zip)

By import error I mean that I am getting the following error when I try to run a python code that uses ```socks```
```Traceback (most recent call last):
  File "scripts/func_exec.py", line 16, in <module>
    import socks
ModuleNotFoundError: No module named 'socks'```

**Comment by noodlehair-git** [comment]
@dimakuv Did you get a chance to see where exactly I am going wrong? I am having issues importing python packages.

**Comment by mkow** [comment]
Closing, as probably outdated.
@noodlehair-git If you still have problems with this, please move the discussion to our support mailing list (support@graphene-project.io), we use GitHub issues only for tracking bugs and feature requests.
