### ISSUE TITLE
[Graphene-SGX] JVM needs syscall getcpu to start

### ISSUE THREAD

**Issue by lejunzhu** [oscarlab/graphene#1552]
When testing JVM (openjdk version "11.0.7" 2020-04-14), starting "java" fails with such message: 
"A fatal error has been detected by the Java Runtime Environment: SIGSEGV (0xb) at pc=0xffffffffff600800, pid=1, tid=2"

With debug message enabled, the following message suggests that it's trying to use getcpu syscall, then falling back to vsyscall, which causes SIGSEGV:
[     2] WARNING: syscall getcpu not implemented. Returning -ENOSYS.
[     2] WARNING: syscall getcpu not implemented. Returning -ENOSYS.
[     2] memory fault at 0x00000000 (IP = 0xffffffffff600800)
[     2] SIGSEGV handled

A quick test shows that with getcpu returns correctly, JVM can continue to start and at least run a hello world program.

**Comment by mkow** [comment]
Thanks for debugging this. We don't support Java explicitly yet, but if you'd have time to implement a PR which implements getcpu syscall (which would just return that there's only one node) we'd gladly merge it :)
