### ISSUE TITLE
[error] SGX_INVALID_LICENSE in the graphene/Pal/src/host/Linux-SGX/sgx_framework.c is not declared

### ISSUE THREAD

**Issue by TaihuLight** [oscarlab/graphene#156]
[Error] SGX_INVALID_LICENSE in the graphene/Pal/src/host/Linux-SGX/sgx_framework.c (348th line)is not declared, and it leads to error for latest graphene!

**Comment by TaihuLight** [comment]
The graphene stops when run ./python.manifest.sgx scripts/helloworld.py , and CPU 100%

./python.manifest.sgx scripts/helloworld.py
manifest file: file:python.manifest.sgx
enclave created:
base: 0x0000000000000000
size: 0x0000000010000000
attr: 0x0000000000000007
xfrm: 0x0000000000000007
ssaframesize: 1
isvprodid: 0x00000000
isvsvn: 0x00000000
adding page to enclave: 000000000ffff000 [REG:R--] (manifest) measured
adding pages to enclave: 000000000fff6000-000000000fffe000 [REG:RW-] (ssa)
adding pages to enclave: 000000000fff1000-000000000fff5000 [TCS:---] (tcs)
adding pages to enclave: 000000000ffec000-000000000fff0000 [REG:RW-] (tls)
adding pages to enclave: 000000000ffdb000-000000000ffeb000 [REG:RW-] (stack)
adding pages to enclave: 000000000ffca000-000000000ffda000 [REG:RW-] (stack)
adding pages to enclave: 000000000ffb9000-000000000ffc9000 [REG:RW-] (stack)
adding pages to enclave: 000000000ffa8000-000000000ffb8000 [REG:RW-] (stack)
adding pages to enclave: 000000000bd76000-000000000bda4000 [REG:R-X] (code) measured
adding page to enclave: 000000000bfa4000 [REG:RW-] (data) measured
adding pages to enclave: 000000000bfa5000-000000000ffa7000 [REG:RW-] (bss)
adding pages to enclave: 0000000000400000-00000000006e9000 [REG:RWX] (code) measured
adding pages to enclave: 00000000008e8000-0000000000961000 [REG:RW-] (data) measured
adding pages to enclave: 0000000000961000-0000000000984000 [REG:RW-] (bss)
adding pages to enclave: 0000000000984000-000000000bd75000 [REG:RWX] (free)
adding pages to enclave: 0000000000010000-0000000000400000 [REG:RWX] (free)
enclave initializing:
enclave id: 0x000000000ffff000
enclave hash: 3a 24 14 cd 9f 77 2f 78 f4 6b 70 a0 a2 b2 66 ca 3f 8e 21 ce e5 32 05 8a 4b e4 1d f6 18 e3 a5 90
Get sealing key: e72f44bc654bd7d4161fe920639cce5
enclave (software) key hash: b4bbec653d49ce4b0cc48c45198807ff7f0a31ea279359f673e1ed9836f487f
trusted: [1] 2cdf459db6d2a82d87fd8f65cb28547bfe752d6763f6a91a52158feebb4573a7 file:/usr/bin/python
trusted: [2] a6048640494d327383021ff1b6527d8fd213e2a010e7094aad686bced1943f09 file:../../../../../Runtime/libsysdb.so

trusted: [16] e5448a9de1c4675ceb16278bcb46fbd6b0f797636096c144ac97c897a104dedd file:hosts
trusted: [17] 7e8ad76e0d200e93918ca2e93c99ff8ecd02071953bf1479819db3ac0dbb6d07 file:resolv.conf
trusted: [18] 76a5771adee7b9f36c7ae66eae78d72f325557500269107f2d98a7e3560a1808 file:gai.conf
allowed: file:/usr/lib/python2.7
allowed: file:scripts

**Comment by andyzyb** [comment]
SGX_INVALID_LICENSE was probably coming from old SGX SDK, now it is likely changed to SGX_ERROR_INVALID_LAUNCH_TOKEN

**Comment by TaihuLight** [comment]
No, SGX_INVALID_LICENSE is the latest graphene, in 348th line of file graphene/Pal/src/host/Linux-SGX/sgx_framework.c. It is a bug?

**Comment by donporter** [comment]
I believe that the PR above should fix this.  Please let us know if you are still having problems.
