### ISSUE TITLE
[Linux-SGX] Children argv goes through untrusted host

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#1561]
Currently Linux-SGX PAL passes arguments to newly spawned children through host's execve, which is not secure. Linux-SGX should be changed to work the same as Linux PAL, which passes them inside the checkpoint (which is encrypted on Linux-SGX).

**Comment by dimakuv** [comment]
> Linux-SGX should be changed to work the same as Linux PAL, which passes them inside the checkpoint

The part about "Linux PAL passes argv inside the checkpoint" is incorrect. Linux PAL works the same as Linux-SGX PAL where it simply passes argv during `execve()`:
```c
// db_process.c
static int __attribute_noinline child_process(struct proc_param* proc_param) {
    int ret = ARCH_VFORK();
    if (ret)
        return ret;

    /* child */
    ...
    int res = INLINE_SYSCALL(execve, 3, PAL_LOADER, proc_param->argv, linux_state.environ);
    ...
}
```

**Comment by mkow** [comment]
> The part about "Linux PAL passes argv inside the checkpoint" is incorrect.

I think I actually got this info from you ;) Anyways, should we fix both PALs? Fixing it in Linux PAL doesn't make that much sense, but OTOH doing the change in both would make the PALs more consistent.

**Comment by dimakuv** [comment]
Yeah, I'm fixing it in both PALs. But first I need to refactor the checkpoint/migrate code...
