### ISSUE TITLE
[Linux-SGX] Implement sched_setaffinity

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1563]
## Description of the problem
The most of performance benchmark tools and some key applications that optimized for performance may heavily rely on the set_affinity feature to explicitly arrange the thread affinity to underlying processor according to the topology of HW. currently the LibOS uses dummy function to handle the set-affinity related request, that would cause unexpected behaviors to run those applications.  the concrete case is the workload inside the enclave read the same core id when using CPUID 0bH to retrieve it.

Fixes #788

## Steps to reproduce
Using CPUID instruction 0bH, 00H to read Acpi info, it result in the same AcpiID that could be the id of exitless ocall thread or the same calling thread after the dummy shim_do_sched_setaffinity get called in LibOS.

## Expected results
The Graphene SGX workload is able to set thread affinity to designated processor.

## Actual results
the setaffinity is handled by dummy LibOS function and cannot fulfill the expected effect, that causes unexpected behaviors when running some performance benchmark tools, some optimized multithread/numa oriented applications.

**Comment by qiyuangong** [comment]
What will happen if I used OMP with affinity configuration in current version/master?

**Comment by dimakuv** [comment]
@qiyuangong Probably nothing bad, but performance of OpenMP will be sub-optimal. Performance degradation will be especially pronounced on many-core machines (24+ cores). PR #1580 will fix it.

We actually run small OpenMP examples as part of our test suite, and it works fine. At least it doesn't break on the current master and outputs correct results.

**Comment by qiyuangong** [comment]
> @qiyuangong Probably nothing bad, but performance of OpenMP will be sub-optimal. Performance degradation will be especially pronounced on many-core machines (24+ cores). PR #1580 will fix it.
> 
> We actually run small OpenMP examples as part of our test suite, and it works fine. At least it doesn't break on the current master and outputs correct results.

OK. I got it.

Thank you for reply. :)
