### ISSUE TITLE
Does any one use  python-sgx to develop python app with SGX?

### ISSUE THREAD

**Issue by TaihuLight** [oscarlab/graphene#157]
I build and test python-sgx [https://github.com/adombeck/python-sgx](url) , but there are many problems described in [https://github.com/adombeck/python-sgx/issues/2](url)
Could you help me?

**Comment by tarikova** [comment]
I am also trying to make it work but not much luck making basic functions such as seal work inside graphene's SGX enclaves :(

**Comment by donporter** [comment]
Can you share a more specific output or set of symptoms?  Make sure to enable debugging (build with DEBUG=1) and set the debug output in the manifest to inline.

**Comment by tarikova** [comment]
Thanks for your suggestions Professor Porter. I will.

The frustrating thing is right now I get no symptoms. The programs exist without any output. In fact, I put a debug print statement inside the python function. That does not run when I called the `_sealing_swing.seal` function from the generated `_sealing_swig.so` file, which is supposed to run the underlying `sgx_seal_data` function from  `sgx_tseal.h`

**Comment by tarikova** [comment]
@donporter I compiled graphene with DEBUG=1 and then tried running the swig sealing program by @adombeck 
I get an assertion error in `shim_namei.c`--more specifically ` assert(start->state & DENTRY_ISDIRECTORY);` on line 97. Unclear if it has anything to do with the library.

**Comment by donporter** [comment]
Interesting.  Can you share any more details about how to reproduce this error?
