### ISSUE TITLE
linux 3.19 boot and compile issue

### ISSUE THREAD

**Issue by sainath14** [oscarlab/graphene#158]
I see two issue with using 3.19 linux kernel
1) make kernel_install in Pal folder doesn't work. It doesnt know recipe for "kernel"
2) I did what kernel_install does manually by doing
       make install
       make modules_install
       make headers_install
   in the kernel directory. But when I try to boot the 3.19 from grub, it does not boot. It is stuck.

**Comment by donporter** [comment]
HI @sainath14 - sorry for the delay in getting back to you.

I'm a little unclear what you are trying to do.  In general, we have experimented with kernel extensions, but they are not required for Graphene to work properly.  

Can you give a bit more details on your issue (what are you trying to do, the commands you issued, outputs, etc)?

**Comment by mkow** [comment]
Outdated, closing.
