### ISSUE TITLE
Issues with using popen() and pipe() in graphene SGX

### ISSUE THREAD

**Issue by manojgop** [oscarlab/graphene#1585]
## Description of the problem
If we call `popen()` and `pipe()` in graphene SGX and get the result of execution, then results are not obtained. The same works as a normal linux application.

## Steps to reproduce
1) Unzip the attached file (cppexec.zip) in `graphene/Examples/` directory
2) `cd graphene/Examples/cppexec`. 
3) Build --> `make distclean && make SGX=1`
4) Run --> `SGX=1 ./pal_loader cppexec.manifest`

## Expected results
Need to get output of `ls` command with `popen()/pipe()` in terminal.

## Actual results
Output of `ls` command is empty

Execute the application as a linux application using command `./src/cppexec`. Then output of ls command executed using `popen()` is read from `pipe()` and printed in terminal.
[cppexec.zip](https://github.com/oscarlab/graphene/files/4785395/cppexec.zip)

**Comment by dimakuv** [comment]
Thanks for this!

I looked into this, and there is no bug in Graphene. Unfortunately, your Makefile and `manifest.template` were incorrectly written. When I fixed all the issues, your example worked correctly.

## Issue 1: wrong/missing mount points

In `manifest.template`, you have:
```
# Mount /bin
fs.mount.bin.type = chroot
fs.mount.bin.path = $(EXECDIR)
fs.mount.bin.uri = file:$(EXECDIR)
```

That's wrong because `EXECDIR` actually resolves to `src`. This led to `/bin/sh` not found by Graphene because `/bin` directory was never mounted in your manifest.

So you should replace with:
```
# Mount /src
fs.mount.src.type = chroot
fs.mount.src.path = $(EXECDIR)
fs.mount.src.uri = file:$(EXECDIR)

# Mount /bin
fs.mount.bin.type = chroot
fs.mount.bin.path = /bin
fs.mount.bin.uri = file:/bin
```

## Issue 2: Incorrect replacements in Makefile

In your Makefile, you have:
```
sh.manifest: manifest.template sh-trusted-children sh.trusted-libs
	sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(EXECNAME)|cppexec|g' \  # WRONG
                -e 's|$$(EXECPATH)|'"$(shell which $(SRCDIR)/cppexec)"'|g' \  # WRONG
                -e 's|$$(EXECDIR)|'"$(shell dirname $(shell which $(SRCDIR)/cppexec))"'|g' \  # WRONG
                -e 's|$$(TRUSTED_LIBS)|'"`cat sh.trusted-libs`"'|g' \
                -e 's|$$(TRUSTED_CHILDREN)|'"`cat sh-trusted-children`"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
```

See `WRONG` marks. You copy-pasted from the target `cppexec` but forgot to update to `sh`. This led to Graphene believing that `sh` executable is actually a `cppexec` executable, and Graphene rightfully failed during execve and SGX attestation.

Here's how I fixed this:
```
sh.manifest: manifest.template sh-trusted-children sh.trusted-libs
    sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(EXECNAME)|sh|g' \
                -e 's|$$(EXECPATH)|'"$(shell which sh)"'|g' \
                -e 's|$$(EXECDIR)|'"$(shell dirname $(shell which $(SRCDIR)/cppexec))"'|g' \
                -e 's|$$(TRUSTED_LIBS)|'"`cat sh.trusted-libs`"'|g' \
                -e 's|$$(TRUSTED_CHILDREN)|'"`cat sh-trusted-children`"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
```

## Issue 3 (in newest Graphene): need to add `insecure__use_cmdline_argv`

In the newest Graphene, your example will fail because you don't allow to pass arguments in the command line. So you need to add `loader.insecure__use_cmdline_argv = 1` to your manifests.

# After fixing these issues, everything works

After fixing the above:
```sh
# the warnings are expected
$ SGX=1 ./pal_loader cppexec.manifest
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Using insecure argv source. Don't use this configuration in production!
file:ls: sh.sig: Function not implemented  # this is because getxattr() syscall is used by ls but not implemented in Graphene
Test exec with popen
Child Process
Child: exec result : total 0
-rw------- 1 0 0  6176 Jan  1  1970 Makefile
-rw------- 1 0 0  3162 Jan  1  1970 cppexec.manifest
-rw------- 1 0 0  5070 Jan  1  1970 cppexec.manifest.sgx
-rw------- 1 0 0  1808 Jan  1  1970 cppexec.sig
-rw------- 1 0 0   304 Jan  1  1970 cppexec.token
-rw------- 1 0 0 81328 Jan  1  1970 log.log
-rw------- 1 0 0  3143 Jan  1  1970 ls.manifest
-rw------- 1 0 0  4881 Jan  1  1970 ls.manifest.sgx
-rw------- 1 0 0  1808 Jan  1  1970 ls.sig
-rw------- 1 0 0   304 Jan  1  1970 ls.token
-rw------- 1 0 0  3122 Jan  1  1970 manifest.template
-rwx------ 1 0 0  1864 Jan  1  1970 pal_loader
-rw------- 1 0 0  3076 Jan  1  1970 sh.manifest
-rw------- 1 0 0  4799 Jan  1  1970 sh.manifest.sgx
-rw------- 1 0 0  1808 Jan  1  1970 sh.sig
-rw------- 1 0 0   304 Jan  1  1970 sh.token

Test exec with popen
Parent Process: wait for child to exit
```

**Comment by manojgop** [comment]
@dimakuv Thanks for looking at this. I was able to execute it successfully after making the changes to Manifest and Makefile suggested above. I think from a graphene user perspective it would be easier if we can make the manifest less complex :-). One observation the output result.  I was not expecting the line  `Test exec with popen` twice in the output like below. The unmodified linux application, print this line only once in terminal.

```
Test exec with popen
Child Process
......
Test exec with popen
Parent Process: wait for child to exit
```

**Comment by manojgop** [comment]
Also how can we keep the attributes of the files in `ls` command executed in graphene SGX same as that in host file system for example file permissions "rwx" and the date modified

**Comment by mkow** [comment]
> Also how can we keep the attributes of the files in ls command executed in graphene SGX same as that in host file system for example file permissions "rwx" and the date modified

We don't have emulation for this yet. The whole filesystem layer needs to be rewritten, afterwards we probably will be able to support such features.
