### ISSUE TITLE
Running a second python script in enclave.

### ISSUE THREAD

**Issue by noodlehair-git** [oscarlab/graphene#1597]
The application that I am building using Graphene-SGX requires to run/launch a second python script within an enclave(from a script already running in enclave). How can I do this? I require the same ```python.manifest``` file. Shall I just run ```./pal_loader python.manifest second_script.py``` (after specifying second script as a trusted file in ```python.manifest.template```)?

**Comment by dimakuv** [comment]
What do you mean "requires to run/launch"?

Do you mean the first python script calls a second python script? In this case, you don't need to do anything special.

Or do you mean the first python script expects a user to start a second python script, and then they communicate with each other somehow? In this case, it depends on the communication style. If it is through files and/or TCP sockets, Graphene should handle it correctly. In other cases, it will be very cumbersome or plain impossible.

**Comment by noodlehair-git** [comment]
Thank you for your reply! Yes, I do mean the first python script calls a second python script.

**Comment by dimakuv** [comment]
In this case, it should (hopefully) work out of the box.

**Comment by mkow** [comment]
Seems the question was answered, closing.
