### ISSUE TITLE
Internal memory fault when using SGX+multithreading

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#160]
When using the same code and setup as in #159 I once triggered the following error:
```
Internal memory fault at 0x0 (IP = +0x1c9f8, VMID = 464615045, TID = 1)
```
This message was being printed to the console infinitely. This happened only once (I ran my code about 3000 times in total), so this seems to be quite a rare bug. The code which prints this error:
https://github.com/oscarlab/graphene/blob/c911f0213ab000d5393cd213d06947a544384072/LibOS/shim/src/bookkeep/shim_signal.c#L249-L254

Any ideas? IMO it looks like some unchecked malloc/mmap which failed and returned zero, but I couldn't reproduce this bug to obtain more info.

**Comment by donporter** [comment]
Not obvious what the culprit is here.  I think there are cases where faults don't really terminate properly, but just cause recurring exceptions.

**Comment by mkow** [comment]
Ok, I tested this on the current master (b194aa17fb2a9ca3947cf8b98141322ad791c6ef) and couldn't reproduce any of the issues: #159, #160, #161. I did 1k tries on SGX and 5k on non-SGX Linux PAL.
