### ISSUE TITLE
poll() syscall cannot receive POLLHUP

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1600]
I reuse the pipe test to show a minimal poll() case.
https://github.com/llly/graphene/blob/poll_test/LibOS/shim/test/native/pipe.c
or
https://github.com/llly/graphene/commit/887d39d79904f53cf69cddc1606ae49cb5bd25ec#diff-8ec2c39fadf7057d4addec266a30bc10
`make DEBUG=1` and run native executable
```
$ ./pipe
hello world
.revents: 0x10
```
Expected same output on Linux host and Linux-SGX host.

Actual results:
```
$SGX=1 ./pal_loader pipe
......
[     1] ---- return from shim_poll(...) = 1
[     1] ---- shim_read(3,0x8023900d0,12) ... read
[     1] ---- return from shim_read(...) = 0
[     1] ---- shim_poll(0x8023900c8,1,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x8023900c8,1,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x8023900c8,1,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
[     1] ---- shim_poll(0x8023900c8,1,-1) ... poll
[     1] ---- return from shim_poll(...) = 0
......
```
And never exit. `$./pal_loader pipe` gives same result.
Log show it never reach `else if(0 != (astPollfd[0].revents & (POLLHUP | POLLERR | POLLNVAL)))` to break from `for` loop.
I think #1539 is caused by same logic and this case is more easy to reproduce.

**Comment by dimakuv** [comment]
Thank you for the test case! Yes, this is some bug in Graphene. I'll try to debug it soon and report back.

Again, thanks for providing a minimal example!
