### ISSUE TITLE
undefined root directory and mount semantics

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#1605]
## Description of the problem

When an application starts running in Graphene, it's current working directory is `/`.  If the application lists `/`, it gets a listing of the `pal_loader`s current working directory, and if it lists `..`, it gets a listing of the `pal_loaders`'s parent directory, and so forth.  

Moreover, if the application chroot mounts `$GRAPHENE_ROOT/Runtime/` onto `/lib`, and the system's `/lib/x86_64-linux-gnu` onto `/lib/x86_64-linux-gnu`,  then when the application walks `/lib`, it ends up walking `$GRAPHENE_ROOT/Runtime`, and when it walks `/lib/x86-64-linux-gnu`, it ends up walking the `/lib/x86-64-linux-gnu` host directory.  In other words, the walk doesn't cross mounts.

Thus, semantically speaking, Graphene doesn't present a root directory, and doesn't implement mounting.  This may be intended (I'm sure it simplifies the implementation while still supporting many applications), but , at the very least, is counter-intuitive.  Perhaps it's simply best addressed through documentation.

## Steps to reproduce

commit id: 3ef4e96ed6d50be88fe0be11cff0c088e1543c45
OS: Ubuntu 18.04

You can experiment with this with a variety of tools (e.g., busybox).  I was playing around with running Lua in Graphene-SGX, as well as using the `lua-posix` module. 

Install and Lua and lua-posix:

```
sudo apt-get install liblua5.3-dev lua5.3 lua-posix-dev
```

There is a bug in the debian lua-posix debian package (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=891541); thus, after installation, you also have to create a symlink:

```
sudo ln -s /usr/lib/x8664-linux-gnu/lub/5.3/posix_c.so /usr/lib/x86_64-linux-gnu/lua/5.3/posix.so
```

This is script from https://luaposix.github.io/luaposix/examples/tree.lua.html that implements a simplified version of `tree(1)`:

```
#! /usr/bin/env lua5.3

-- tree view of the file system like the 'tree' unix utility
-- John Belmonte <jvb@prairienet.org>

local dir = require 'posix.dirent'.dir
local islink = require 'posix.sys.stat'.S_ISLNK
local isdir = require 'posix.sys.stat'.S_ISDIR
local readlink = require 'posix.unistd'.readlink
local stat = require 'posix.sys.stat'.stat

local leaf_indent = '|   '
local tail_leaf_indent = '   '
local leaf_prefix = '|-- '
local tail_leaf_prefix = '`-- '
local link_prefix = ' -> '

local function printf(...)
  io.write(string.format(...))
end

local function do_directory(directory, level, prefix)
   local num_dirs = 0
   local num_files = 0
   local files = dir(directory)
   local last_file_index = #files
   table.sort(files)
   for i, name in ipairs(files) do
      if name ~= '.' and name ~= '..' then
         local full_name = string.format('%s/%s', directory, name)
         local info = assert(stat(full_name))
         local is_tail = (i==last_file_index)
         local prefix2 = is_tail and tail_leaf_prefix or leaf_prefix
         local link = ''
         if islink(info.st_mode) ~= 0 then
            linked_name = assert(readlink(full_name))
            link = string.format('%s%s', link_prefix, linked_name)
         end
         printf('%s%s%s%s\n', prefix, prefix2, name, link)
         if isdir(info.st_mode) ~= 0 then
            local indent = is_tail and tail_leaf_indent or leaf_indent
            -- TODO: cache string concatenation
            sub_dirs, sub_files = do_directory(full_name, level+1,
               prefix .. indent)
            num_dirs = num_dirs + sub_dirs + 1
            num_files = num_files + sub_files
         else
            num_files = num_files + 1
         end
      end
   end
   return num_dirs, num_files
end

local function fore(directory)
   print(directory)
   num_dirs, num_files = do_directory(directory, 0, '')
   printf('\n%d directories, %d files\n', num_dirs, num_files)
end

directory = (arg and #arg > 0) and arg[1] or '.'
fore(directory)
```

This is my manifest for running the script:

```
# This manifest was prepared on Ubuntu 18.04 for the lua5.3 executable
#
# Lua must be run with the pal_loader:
#
# SGX=1 GRAPHENE_ROOT/Runtime/pal_loader lua5.3.manifest.sgx /home/dir.lua
# 
# You will need to change any references to /home/smherwig to fit your setup

# The executable to load in Graphene.
loader.exec = file:/usr/bin/lua5.3

# Graphene environment, including the path of the library OS and the debug
# option (inline/none).
loader.preload = file:/home/smherwig/src/phoenix/Runtime/libsysdb.so
loader.debug_type = inline

#------------------------------------------------------------
# SGX OPTIONS
#------------------------------------------------------------

# Set the virtual memory size of the SGX enclave. For SGX v1, the enclave
# size must be specified during signing.   Must be a power of 2
sgx.enclave_size = 128M

# Set the maximum number of enclave threads. For SGX v1, the number of enclave
# TCSes must be specified during signing, so the application cannot use more
# threads than the number of TCSes. Note that Graphene also creates an internal
# thread for handling inter-process communication (IPC), and potentially another
# thread for asynchronous events. Therefore, the actual number of threads that
# the application can create is (sgx.thread_num - 2).
sgx.thread_num = 4

# Mounted FSes. The following "chroot" FSes mount a part of the host FS into the
# guest. Other parts of the host FS will not be available in the guest.

#------------------------------------------------------------
# MOUNT /lib /lib
# Default glibc files, mounted from the Runtime directory in GRAPHENEDIR.
#------------------------------------------------------------
fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:/home/smherwig/src/phoenix/Runtime

# glibc libraries
sgx.trusted_files.ld = file:/home/smherwig/src/phoenix/Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:/home/smherwig/src/phoenix/Runtime/libc.so.6
sgx.trusted_files.libm = file:/home/smherwig/src/phoenix/Runtime/libm.so.6
sgx.trusted_files.libdl = file:/home/smherwig/src/phoenix/Runtime/libdl.so.2
sgx.trusted_files.librt = file:/home/smherwig/src/phoenix/Runtime/librt.so.1
sgx.trusted_files.libutil = file:/home/smherwig/src/phoenix/Runtime/libutil.so.1
sgx.trusted_files.libpthread = file:/home/smherwig/src/phoenix/Runtime/libpthread.so.0
sgx.trusted_files.libnssdns = file:/home/smherwig/src/phoenix/Runtime/libnss_dns.so.2
sgx.trusted_files.libresolv = file:/home/smherwig/src/phoenix/Runtime/libresolv.so.2

#------------------------------------------------------------
# MOUNT /lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
#------------------------------------------------------------
fs.mount.lib_arch.type = chroot
fs.mount.lib_arch.path = /lib/x86_64-linux-gnu
fs.mount.lib_arch.uri = file:/lib/x86_64-linux-gnu

# lua5.3 dependencies 
sgx.trusted_files.lib_arch_2 = file:/lib/x86_64-linux-gnu/libreadline.so.7
sgx.trusted_files.lib_arch_3 = file:/lib/x86_64-linux-gnu/libtinfo.so.5

# lua-posix dependencies 
sgx.trusted_files.lib_arch_4 = file:/lib/x86_64-linux-gnu/libcrypt.so.1

#------------------------------------------------------------
# MOUNT /usr/lib/x86_64-linux-gnu /usr/lib/x86_64-linux-gnu
#------------------------------------------------------------
fs.mount.usr_lib_arch.type = chroot
fs.mount.usr_lib_arch.path = /usr/lib/x86_64-linux-gnu
fs.mount.usr_lib_arch.uri = file:/usr/lib/x86_64-linux-gnu

sgx.trusted_files.usr_lib_arch_0 = file:/usr/lib/x86_64-linux-gnu/lua/5.3/posix.so

#------------------------------------------------------------
# MOUNT /home/smherwig/src/makemanifest-basic/templates/home /home
#------------------------------------------------------------
fs.mount.home.type = chroot
fs.mount.home.path = /home
fs.mount.home.uri = file:/home/smherwig/src/makemanifest-basic/templates/home

sgx.trusted_files.home_0 = file:/home/smherwig/src/makemanifest-basic/templates/home/tree.lua
#------------------------------------------------------------
# ENVIRONMENT VARIABLES
#------------------------------------------------------------
loader.env.LD_LIBRARY_PATH = /lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu
```

## Expected results
Described in the problem (but if, unclear, I can add some output examples from running `SGX=1 
$GRAPHENE_ROOT/Runtime/pal_loader lua5.3.manifest.sgx /home/dir.lua DIRECTORY`

## Actual results
ditto

**Comment by mkow** [comment]
This is basically point 4. of the list from #1544. Basically the whole filesystem layer should be rewritten from scratch, there's no hope there :)
There are many more issues like this, we just need to implement this whole thing from scratch.

**Comment by dimakuv** [comment]
+1 to @mkow. The semantics of the current in-Graphene FS implementation are moot and underspecified. Fixing these semantics requires a complete re-write of the FS subsystem.

**Comment by dimakuv** [comment]
@pwmarcz @mkow Do you think it is still relevant?

**Comment by pwmarcz** [comment]
None of these things should happen now.

>When an application starts running in Graphene, it's current working directory is /. If the application lists /, it gets a listing of the pal_loaders current working directory, and if it lists .., it gets a listing of the pal_loaders's parent directory, and so forth.

Using Busybox, `ls ..` gives me the same listing as `ls .` and `ls /`. I'm not sure how the above happened before, but that code is gone.

>Moreover, if the application chroot mounts $GRAPHENE_ROOT/Runtime/ onto /lib, and the system's /lib/x86_64-linux-gnu onto /lib/x86_64-linux-gnu, then when the application walks /lib, it ends up walking $GRAPHENE_ROOT/Runtime, and when it walks /lib/x86-64-linux-gnu, it ends up walking the /lib/x86-64-linux-gnu host directory. In other words, the walk doesn't cross mounts.

Using Busybox, `ls /lib` gives me a listing of the Runtime directory, but with the `x86-64-linux-gnu` directory added. This is expected: `x86-64-linux-gnu` is a mountpoint for `file:/lib/x86-64-linux-gnu`. Before refactoring, a bug was causing such mountpoints to be hidden from listings.

>Thus, semantically speaking, Graphene doesn't present a root directory, and doesn't implement mounting. This may be intended (I'm sure it simplifies the implementation while still supporting many applications), but , at the very least, is counter-intuitive. Perhaps it's simply best addressed through documentation.

Right now, Graphene implements pretty standard mount semantics, except that you can mount over a non-existing file (such as `/lib/x86-64-linux-gnu`) and a synthetic mountpoint will be created for you.
