### ISSUE TITLE
strstr returns const char *; POSIX says it returns char *

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#1610]
## Description of the problem
commit: bf155c7

`graphene/Pal/lib/string/strstr.c`'s `strstr` returns `const char *`.  This of course makes sense, but POSIX says the return value is simply a `char *`.  (https://pubs.opengroup.org/onlinepubs/9699919799/functions/strstr.html) 

## Steps to reproduce

N/A

## Expected results
N/A

## Actual results
N/A

**Comment by dimakuv** [comment]
Thanks for reporting this! Does this lead to any build or runtime failures? Looks like just a small harmless divergence from the standard. (We should fix it though.)

**Comment by smherwig** [comment]
No, it doesn't lead to any failure that I know of.  It's just a minor issue if you're incorporating additional third-party code that expects the POSIX signature.

**Comment by dimakuv** [comment]
This is fixed by #1325 as a side effect.
