### ISSUE TITLE
shim_mprotect: assert failed ../include/shim_flags_conv.h:32 WITHIN_MASK(prot, PROT_READ | PROT_WRITE | PROT_EXEC)

### ISSUE THREAD

**Issue by vshulhat** [oscarlab/graphene#1612]
Thanks for your great job!

## Description of the problem
I'm trying to run simple python script with Graphene.
```python
import mxnet
```
It ends with error:
```
[     1] ---- shim_stat("/lib/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("/usr/lib/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("/lib/x86_64-linux-gnu/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("/usr/lib/x86_64-linux-gnu/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("/home/user/.local/lib/python3.6/site-packages/mxnet/libmxnet.so",0x7b51a8364fb0) = 0
[     1] ---- shim_stat("/home/user/.local/lib/python3.6/site-packages/mxnet/libmxnet.so",0x7b51a8364fb0) = 0
[     1] ---- shim_stat("/home/user/.local/lib/python3.6/site-packages/mxnet/../../lib/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("/home/user/.local/lib/python3.6/site-packages/mxnet/../../build/libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_stat("../../../libmxnet.so",0x7b51a8364fb0) = -2
[     1] ---- shim_openat(AT_FDCWD,"/home/user/.local/lib/python3.6/site-packages/mxnet/libmxnet.so",O_RDONLY|2000000,0000) = 4
[     1] ---- shim_read(4,0x7b51a8364a68,832) ... read
[     1] ---- return from shim_read(...) = 832
[     1] ---- shim_fstat(4,0x7b51a8364900) = 0
[     1] ---- shim_mmap(0x0,76163960,PROT_READ|PROT_EXEC,MAP_PRIVATE|0x800,4,0) ... mmap
[     1] ---- return from shim_mmap(...) = 0x7b5185469000
[     1] ---- shim_mprotect(0x7b51869b8000,52576256,PROT_NONE) ... mprotect
[     1] ---- return from shim_mprotect(...) = 0
[     1] ---- shim_mmap(0x7b5189bdc000,421888,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_FIXED|0x800,4,22343680) ... mmap
[     1] ---- return from shim_mmap(...) = 0x7b5189bdc000
[     1] ---- shim_mmap(0x7b5189c43000,822136,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON|MAP_FIXED,-1,0) ... mmap
[     1] ---- return from shim_mmap(...) = 0x7b5189c43000
[     1] ---- shim_mprotect(0x7b51a8326000,2180,PROT_READ|PROT_WRITE) ... mprotect
[     1] ---- return from shim_mprotect(...) = 0
[     1] ---- shim_mprotect(0x7b51a8326000,2180,PROT_READ) ... mprotect
[     1] ---- return from shim_mprotect(...) = 0
[     1] ---- shim_mprotect(0x7b51a8368000,4096,PROT_READ|PROT_WRITE|PROT_EXEC) ... mprotect
assert failed ../include/shim_flags_conv.h:32 WITHIN_MASK(prot, PROT_READ | PROT_WRITE | PROT_EXEC)
[     1] Deleting port 0x7fa98956e048 (handle 0x7fa989b13f10) of process 28759
[     1] process 28759 exited with status -131
```
There is full [log](https://github.com/oscarlab/graphene/files/4820885/log.txt).
The same error in SGX and non-SGX mode.
I ran some your examples and there were no errors. 

Please, give me any advice. Thanks in advance.

## Steps to reproduce
commit: b0d95cfe
OS: Ubuntu 18.04
python: 3.6.9
mxnet: 1.5.1

**Comment by stefanberger** [comment]
The fixed log will show this here:

```
[     1] ---- shim_mprotect(0x2f70b55b5000,4096,PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) ... mprotect
assert failed ../include/shim_flags_conv.h:23 WITHIN_MASK(prot, PROT_READ | PROT_WRITE | PROT_EXEC)
```

So, there's an additional flag in there that we don't handle, yet. At least for this I now created PR #1613 .

**Comment by dimakuv** [comment]
@vshulhat Are you familiar with this Python library? Why does it require `PROT_GROWSDOWN`? Does it use its own internal stacks?

**Comment by dimakuv** [comment]
@stefanberger Thanks for the PR! Do you think that we could emulate these currently-unsupported flags by simply ignoring them? I looked at `man mprotect`, they seem to be rather useless.

**Comment by stefanberger** [comment]
@dimakuv I tried to implement support for PROT_GROWSDOWN and it didn't work because the vma->flags didn't have MAP_GROWSDOWN set as it should be and I couldn't find a corresponding shim_mmap() call that had 0x100 (MAP_GROWSDOWN) set. They may not be entirely useless and depending on how they are used could have some side effects if not properly supported. So I had the impression one could say PROT_WRITE|PROT_GROWSDOWN on `addr + 0x1000` and it wouldn't split the vma that starts at `addr` but give it all PROT_WRITE...

**Comment by dimakuv** [comment]
@stefanberger Thanks. Yes, there could be some unexpected side effects if we just ignore these flags. I wonder though if this works for most cases (like this Python library). We could always write a warning that this may lead to unexpected results.

**Comment by vshulhat** [comment]
@dimakuv It's popular Deep Learning framework. Unfortunately I don't know very well what happens under hood, so can't answer these questions.

**Comment by stefanberger** [comment]
@dimakuv Sent PR #1615 . Maybe we can find something.

**Comment by boryspoplawski** [comment]
@vshulhat  Could you check this out on #1636 ?

**Comment by vshulhat** [comment]
@boryspoplawski This error has disapeared. I can import lib and run test script. Thanks a lot!
