### ISSUE TITLE
Please speed up the project building using all cpu cores. It is very slow.

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1626]
## Description of the problem
I have tried to build the clean project, it cost me about several more minutes on my powerful machine. I found it just uses 1 cpu core to fulfill the building. that is why it is so slow. 

## Steps to reproduce
make

## Expected results
Used up all cpu core to accelerate project compilation.

## Actual results
It just used 1 core to build this project.

**Comment by dimakuv** [comment]
One can simply add `-j X` to parallelize the make build. In fact, this is what we do in Jenkins.

**Comment by bigdata-memory** [comment]
Thanks.
