### ISSUE TITLE
GNU ar report 'u' modifier messages repeatably during project building

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1628]
## Description of the problem
There are many following lines repeatably shown in project building.
    _ar: `u' modifier ignored since `D' is the default (see `U')_

## Steps to reproduce
make

## Expected results
no such many messages produced during building

## Actual results
![image](https://user-images.githubusercontent.com/10856796/85910362-3564c380-b7d3-11ea-9aa1-059adde5bc4e.png)

**Comment by mkow** [comment]
@bigdata-memory for the future: Please don't post logs as screenshots and instead paste them in a code block (enclosed in \`\`\`).

**Comment by bigdata-memory** [comment]
> @bigdata-memory for the future: Please don't post logs as screenshots and instead paste them in a code block (enclosed in ```).

I see, thanks.
