### ISSUE TITLE
Network and port allowed question

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1643]
Simple question about network related configuration. 

I have tried redis and apache examples. It works. :)

I saw `net.allow_bind.redisport = :6379`  in redis example (https://github.com/oscarlab/graphene/blob/master/Examples/redis/redis-server.manifest.template#L76). It opened an allowed port for external connection. However, for apache example, there isn't and port or network related configuration. 

Does it mean all ports are allowed for apache example?

**Comment by dimakuv** [comment]
The option ` net.allow_bind` is *not* currently enforced. Graphene currently ignores it. It was added to the Redis example "for future". At some point, Graphene will restrict network configurations based on the manifest file, but this is still future work.

**Comment by qiyuangong** [comment]
@dimakuv Thanks for reply! :)

That means all Graphene ports widely opened for connection right now. That's not a big problem in most cases, but may cause troubles if someone try to hack that service.

Hoping this configuration will be ready in near future. Issue closed.
