### ISSUE TITLE
pal_loader doesn't handle incorrect file name properly

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#165]
If you run the following command:
```Bash
[...]/graphene/LibOS/shim/test/native/pal_loader SGX something_which_doesnt_exist
```
Then nothing happens (no errors or warnings on the console). This is very annoying in cases where you made a typo in the file name and are wondering what's wrong. Also, this seems to happen only in SGX mode.

Another problem occurs when you type `something.manifest` instead of `something`. AFAIR your Wiki said somewhere that it should also work, but I always get the following error when using the command with `.manifest`:
```
enclave EINIT failed - Invalid measurement
initializing enclave failed: init_enclave: 1
```

Tested on the commit c911f0213ab000d5393cd213d06947a544384072.

**Comment by donporter** [comment]
These sound like legit issues to me.

**Comment by mkow** [comment]
Couldn't reproduce on current master (https://github.com/oscarlab/graphene/tree/34b8eb1ec2b23d5538d8ede385eb1be50e29354d). Seems that this was fixed when refactoring pal-$HOST binaries interface.
