### ISSUE TITLE
Unexpected AEX vector occurred inside PAL!  Panic!

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1664]
## Description of the problem
I encounter " Unexpected AEX vector occurred inside PAL! " panic when I run a modified LibOS native test case  "time" after several seconds.
it just repeatedly call getimeofday() at interval 5 secs. 

## Steps to reproduce
SGX=1 ./pal_loader time # repeatedly call gettimeofday() at interval 5 secs

## Expected results
No panic

## Actual results
the following is the latest panic info I collected.
```
*** Unexpected AEX vector occurred inside PAL! ***
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x0000a5ff)
rax: 0x00000000 rcx: 0x55fc75cee0b9 rdx: 0xfffffffffffbb1c8 rbx: 0x80005c540
rsp: 0x80fed6f40 rbp: 0x80fed7020 rsi: 0x80b8991d0 rdi: 0x80b8c6de8
r8 Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
Unknown or illegal instruction at RIP 0x000000080b8991d0
*** Unexpected AEX vector occurred inside PAL! ***
(vector = 0x6, type = 0x3 valid = 1, RIP = +0x000241d0)
rax: 0x00000000 rcx: 0x55fc75cee0b9 rdx: 0x00000039 rbx: 0x80005c540
rsp: 0x80fedf370 rbp: 0x80fedf860 rsi: 0x00000000 rdi: 0x00000039
r8 : 0x00000000 r9 : 0x00000000 r10: 0x00000000 r11: 0x00000202
r12: 0x00000000 r13: 0x00000000 r14: 0x00000000 r15: 0x00000000
rflags: 0x00010202 rip: 0x80b8991d0
DkProcessExit: Returning exit code 1
```

**Comment by dimakuv** [comment]
I will debug this now. It could be the same issue as here: https://github.com/oscarlab/graphene/pull/1663. I'll check.

**Comment by dimakuv** [comment]
@bigdata-memory , so the error you see happened due to FSGSBASE becoming prohibited? Then I won't debug this error.

**Comment by bigdata-memory** [comment]
@dimakuv Yes, I tried several times, it popped up such panics many times after several seconds, and then I'm aware of that may caused by machine suspending, and I digged into this issue and found the root cause, after that, I reloaded the GSGX driver, it works.

**Comment by bigdata-memory** [comment]
This panic didn't show any useful message and make user confused on this case.
I think it is also related to GSGX UX issue.

**Comment by dimakuv** [comment]
@bigdata-memory Thanks for debugging this! Your PR is approved.

**Comment by bigdata-memory** [comment]
> 
> 
> @bigdata-memory Thanks for debugging this! Your PR is approved.

Thank you very much for helping me fix the bug in my PR and approving it.
