### ISSUE TITLE
[Question]where is my RA_CLIENT_SPID?

### ISSUE THREAD

**Issue by bearDream** [oscarlab/graphene#1671]
## Description of the problem
      
In Examples, ra-tls-mbedtls.
I try for that "RA-TLS flows with SGX and with Graphene, EPID-based (IAS) attestation:", but I don't know where found my SPID, so please help me.

**Comment by dimakuv** [comment]
EPID-based remote attestation relies on a web service called IAS provided by Intel.

You must register with Intel via https://software.intel.com/content/www/us/en/develop/topics/software-guard-extensions/request-license.html to use this service. After you register, you get your credentials which include the SPID.

**Comment by bearDream** [comment]
> EPID-based remote attestation relies on a web service called IAS provided by Intel.
> 
> You must register with Intel via https://software.intel.com/content/www/us/en/develop/topics/software-guard-extensions/request-license.html to use this service. After you register, you get your credentials which include the SPID.

Thanks a lot
