### ISSUE TITLE
some cases failed from LibOS/shim/test/regression, with DCAP driver

### ISSUE THREAD

**Issue by jinghe-INTC** [oscarlab/graphene#1680]
## Description of the problem
I took the DCAP 1.7 version of SGX driver and SDK for Graphene. Most of the regression cases passed with it, except 3 from LibOS/shim/test/regression:
TC_04_Attestation::test_000_attestation
TC_04_Attestation::test_001_attestation_stdio 
TC_90_CpuidSGX::test_000_cpuid

## Steps to reproduce

1. Checkout SGX code from:
https://github.com/intel/linux-sgx
and  submodules are necessary to checkout too
2. Build SGX SDK and PSW
3. Build and install DCAP driver, code can be found at linux-sgx/external/dcap_source/driver/linux/
4. Install SGX PSW packages
5. Build Graphene, providing the above driver path when asked
6. Do regression test under Pal/regression and LibOS/shim/test/regression

## Expected results
All cases should be pass or xfail

## Actual results
3 cases failed at LibOS/shim/test/regression:
TC_04_Attestation::test_000_attestation
TC_04_Attestation::test_001_attestation_stdio 
TC_90_CpuidSGX::test_000_cpuid

The same cases can pass on SGX driver from https://github.com/01org/linux-sgx-driver

Single step execution log of attestation with linux-sgx-driver:
```
~/graphene/LibOS/shim/test/regression$ SGX=1 ../../../../Runtime/pal_loader attestation.manifest.sgx
WARNING: Using insecure argv source. Don't use this configuration in production!
Test local attestation... SUCCESS
Test quote interface... SUCCESS
Test resource leaks in attestation filesystem... SUCCESS
~/graphene/LibOS/shim/test/regression$ SGX=1 ../../../../Runtime/pal_loader cpuid.manifest.sgx
WARNING: Using insecure argv source. Don't use this configuration in production!
CPUID test passed.
~/graphene/LibOS/shim/test/regression$
```

With DCAP driver:
```
~/graphene/LibOS/shim/test/regression$ SGX=1 ../../../../Runtime/pal_loader attestation.manifest.sgx
~/graphene/LibOS/shim/test/regression$ 
~/graphene/LibOS/shim/test/regression$ SGX=1 ../../../../Runtime/pal_loader cpuid.manifest.sgx
WARNING: Using insecure argv source. Don't use this configuration in production!
Unexpected value in host CPUID. Exiting...
~/graphene/LibOS/shim/test/regression$
```

**Comment by dimakuv** [comment]
Thanks, we'll debug this as soon as we'll find time.

Do you know what changed in the DCAP driver v1.7? I remember that versions v1.6 and intermediate ones `LD_1.32` and `LD_1.33` worked.

**Comment by jinghe-INTC** [comment]
As I know, there is no big change in DCAP 1.7 driver, v1.35. 
And on my machine, the failures are still reproducible if DCAP 1.6 driver and PSW are installed.

**Comment by dimakuv** [comment]
Hm, then I don't know how to debug this. DCAP 1.6 works fine on my machines.

Are you sure the AESM service works correctly on your machine? Do you see any errors via `sudo service aesmd status` and `dmesg | grep sgx`?

**Comment by jinghe-INTC** [comment]
You are right. I didn't install sgx-aesm. After I installed sgx-aesm and sgx-aesm-quote-ex, the 2 attestation cases passed.

But the CPUID case still fails. Is it working properly on you machines with DCAP driver 1.32/1.33 or 1.35. Thanks!

**Comment by dimakuv** [comment]
Yes, it is working properly on our machines. It doesn't depend on the SGX driver. I think you have a "corner case" CPU that reports something in CPUID which Graphene tries to parse but doesn't recognize.

What is this CPU? Is there anything "special" in this CPU? Some feature that is very new or really rare?

Could you execute `cpuid` on your machine and show us the output?

**Comment by jinghe-INTC** [comment]
If I execute `cpuid` alone, there is always `CPUID test passed`. 

But the machines with the problem are indeed specially, because they are of development models and for Intel internal use. Some information like "Model name" wasn't written in. 

It is still interesting since `cpuid` only fails with Graphene on these machines.  Is it possible to make it pass in Graphene the same as it does without Graphene?

**Comment by dimakuv** [comment]
The reason why `cpuid` fails with Graphene is because Graphene must *validate* and *sanitize* returned CPUID values. Recall that Graphene runs the application inside the SGX enclave with security guarantees, so Graphene must perform additional checks on untrusted inputs. And CPUID returns many values -- if some of them were maliciously modified by the hacker, the application inside the enclave could become vulnerable.

So Graphene has some checks on "good" CPUID values: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_misc.c#L205-L313.

**Comment by jinghe-INTC** [comment]
Thanks for the explanation. I will close the issue since you help solve all my problems.
