### ISSUE TITLE
[PAL/Linux] Failed to declare '_r_debug@@PAL'  as default

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1685]
## Description of the problem
The Graphene building failed due to an Error as follows
> make[3]: Entering directory '/home/gary/graphene/Pal/src/host/Linux'
>   [ db_eventfd.o ]
> /tmp/ccOTt36Q.s: Assembler messages:
> /tmp/ccOTt36Q.s: Error: invalid attempt to declare external version name as default in symbol `_r_debug@@PAL'
> Makefile:65: recipe for target 'db_eventfd.o' failed
> make[3]: *** [db_eventfd.o] Error 1

on platform

> VERSION="18.04.3 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.3 LTS"
> gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> GNU ld (GNU Binutils) 2.34.50.20200426

## Steps to reproduce
make

## Expected results
No any errors

## Actual results
reports

> make[3]: Entering directory '/home/gary/graphene/Pal/src/host/Linux'
>   [ db_eventfd.o ]
> /tmp/ccOTt36Q.s: Assembler messages:
> /tmp/ccOTt36Q.s: Error: invalid attempt to declare external version name as default in symbol `_r_debug@@PAL'
> Makefile:65: recipe for target 'db_eventfd.o' failed
> make[3]: *** [db_eventfd.o] Error 1
>

**Comment by llly** [comment]
You need to use default as from Ubuntu. The as provided by SGX repo has higher version that `/usr/bin/as` Ubuntu.

I'm not sure it expected error or not. Removing the as from sgx-linux works.

**Comment by bigdata-memory** [comment]
This issue can be fixed, I'm going to submit a PR
Thank you for the suggestion.

**Comment by dimakuv** [comment]
I will copy-paste @chiache's reply to this (on a slack channel):

> r_debug is part of the glibc convention to communicate with gdb and we use a special version (`@@PAL`) to prevent the LibOS from replacing the actual glibc symbols with this one. [...] this only applies to Linux PAL since the SGX PAL uses two separate binaries as in enclave and out of enclave loaders. There is a different trick we use in SGX PAL, which is to emit GDB command at breakpoints set by the host script.

> I am not sure why r_debug is failing compilation with newer versions of GCC and binutils. This certainly worths investigation as it might suggest some other compilation issues in newer GCC.

>If we want to switch completely to breakpoint-based model, that's completely fine with me. I don't think there is any downside and might even be easier to debug the GDB support.

**Comment by dimakuv** [comment]
https://github.com/oscarlab/graphene/pull/1778 explains the issue in greater detail. Basically, Graphene incorrectly injected the asm directive in files where the required symbol (global variable) was not declared, which is prohibited by newer `as`.
