### ISSUE TITLE
[LibOS] program could hang because ipc_helper_lock used in shim_clean_and_exit() before create_lock() called

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1688]
## Description of the problem
`ipc_helper_lock` is created in` init_ipc_helper()` called via [RUN_INIT(init_ipc_helper);](https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/shim_init.c#L572)
However a lot of `RUN_INIT` is used before RUN_INIT(init_ipc_helper);. At that time `ipc_helper_lock` is uninitialized. 

When any of `RUN_INIT()` before `RUN_INIT(init_ipc_helper);` fails, the `RUN_INIT` MACRO calls `shim_clean_and_exit` then `del_all_ipc_ports` then `lock(&ipc_helper_lock);`.
Then [lock](https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_internal.h#L494) call `__abort()` which also calls `shim_clean_and_exit` recursively. And the program hangs.
 
## Steps to reproduce
Using latest [master](https://github.com/oscarlab/graphene/commit/fe6cdb3cd4100214330e37e3775d20c1f42a6892)
Option 1. Try to run Graphene-SGX using config
```
sgx.enclave_size = 256M
sys.brk.max_size = 512M
```
Option 2. When running multiply SGX-Graphene instances at same time, Sometimes reproduced this issue.
## Expected results
fail gently
## Actual results
hang and need CTRL-Z to stop.
debug log:
```
......
[     1] mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
get_pf(/lib/x86_64-linux-gnu) = 0x0
get_pf(/lib/x86_64-linux-gnu) = 0x0
[     1] mounting as chroot filesystem: from file:/usr/lib/x86_64-linux-gnu to /usr/lib/x86_64-linux-gnu
get_pf(/usr/lib/x86_64-linux-gnu) = 0x0
get_pf(/usr/lib/x86_64-linux-gnu) = 0x0
[     1] mounting as chroot filesystem: from file:lib to /mnt
get_pf(lib) = 0x0
get_pf(lib) = 0x0
[     1] mounting as chroot filesystem: from file:/bin to /bin
get_pf(/bin) = 0x0
get_pf(/bin) = 0x0
[     1] mounting as chroot filesystem: from file:/etc to /etc
get_pf(/etc) = 0x0
get_pf(/etc) = 0x0
get_pf(test_shuffle) = 0x0
[     1] allocated stack at 0x80a019000 (size = 8388608)
[     1] adding file:test_shuffle as runtime object loaded at 0x80b1f3000-0x80b463000
shim_init() in init_loader (-12)
[     1] Trying to lock an uninitialized lock at ipc/shim_ipc_helper.c:393!
^Z
[20]  + 9424 suspended  SGX=1 ./pal_loader test_shuffle
......

**Comment by dimakuv** [comment]
Thanks @llly ! Impressive analysis. I'll look into it and submit a patch.

**Comment by dimakuv** [comment]
Done. See https://github.com/oscarlab/graphene/pull/1691.

Now it fails like this instead of hanging:
```
$ SGX=1 ./pal_loader ./init_fail2.manifest
shim_init() in init_loader (-12)
Saturation error in exit code -12, getting rounded down to 244
```
