### ISSUE TITLE
make SGX=1 failed when building redis and all other applications in Example directory

### ISSUE THREAD

**Issue by markueni** [oscarlab/graphene#1692]
I am trying to run redis in Example directory by typtin 

> make SGX=1 

but I get the following error:

```
>  File "../../Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 122, in connect_aesmd
>     raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
> Exception: Failed. (Error Code = 30)
> Makefile:88: recipe for target 'redis-server.manifest.sgx' failed
> make: *** [redis-server.manifest.sgx] Error 1
```

When I have built graphene before some months I did not get any error of that type but now that I have reinstalled again I get such error. Does this error may have to do with new kernel patches? I have downgraded my kernel version at 4.20.3 generic and I am assuming it may have to do with that.

**Comment by dimakuv** [comment]
> File "../../Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 122, in connect_aesmd

This error means that you cannot connect to the AESM service. What does `sudo service aesmd status` show?

You need to install AESM (it is a part of Intel SGX PSW) and start it.

**Comment by markueni** [comment]
@dimakuv here is the output of aesmd

```
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2020-07-17 15:36:32 CEST; 9h ago
 Main PID: 1339 (aesm_service)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/aesmd.service
           └─1339 /opt/intel/sgx-aesm-service/aesm/aesm_service

Jul 17 22:24:52 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 22:26:59 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 22:27:05 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 22:27:51 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 22:54:15 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 23:01:22 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 23:56:38 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 17 23:57:46 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 18 00:01:09 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
Jul 18 00:37:26 nuc-NUC8i7HVK aesm_service[1339]: InKernel LE loaded
```
I think that I have installed all SGX binaries. I say binaries because I did not install SDK, PSW and Driver from git repository.

**Comment by dimakuv** [comment]
You seem to be running the newest Intel SGX SDK/PSW and the Intel SGX driver?

Do you know if these are the DCAP versions? In particular, is the driver a DCAP-based driver from https://github.com/intel/SGXDataCenterAttestationPrimitives?

If the driver that you installed on the system is the DCAP driver, then you need to rebuild Graphene from scratch because it probably thinks that the driver is still the legacy driver. I would suggest to `make SGX=1 distclean` in Graphene and then `make SGX=1`. When you are asked for the driver path, please specify the driver path of the DCAP driver (which is typically `/usr/src/sgx-XYZ`).

**Comment by markueni** [comment]
Problem solved. I inputed as driver path the old sgx driver but now when I inputed the path of DCAP-based driver it worked. Thnx @dimakuv
