### ISSUE TITLE
how to build graphene on RHEL8.2

### ISSUE THREAD

**Issue by WilliamXieIntel** [oscarlab/graphene#1716]
Anyone successfully built graphene on RHEL8.2?

I met below error:
checking if gcc is sufficient to build libc... yes
checking for nm... nm
checking for python3... python3
checking version of python3... 3.6.8, ok
configure: WARNING:
*** These auxiliary programs are missing or incompatible versions: makeinfo
*** some features or tests will be disabled.
*** Check the INSTALL file for required versions.
checking LD_LIBRARY_PATH variable... contains current directory
configure: error:
*** LD_LIBRARY_PATH shouldn't contain the current directory when
*** building glibc. Please change the environment variable
*** and run configure again.
make[1]: *** [Makefile:58: glibc-build/Makefile] Error 1
make[1]: Leaving directory '/root/graphene/graphene/LibOS'
make: *** [Makefile:15: all] Error 2

in graphene/LibOS/glibc-build/config.log

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU C Library configure (see version.h), which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ../glibc-2.31/configure --prefix=/root/graphene/graphene/LibOS/../Runtime --with-tls --without-selinux --disable-test --disable-nscd

## --------- ##

hostname = localhost.localdomain
uname -m = x86_64
uname -r = 5.7.0-intel-next-03494-g424e7e9bfaa9
uname -s = Linux
uname -v = #1 SMP Wed Jun 10 15:46:03 PDT 2020

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /root/bin

## ----------- ##

configure:2218: checking build system type
configure:2232: result: x86_64-pc-linux-gnu
configure:2252: checking host system type
configure:2265: result: x86_64-pc-linux-gnu
configure:2334: checking for gcc
configure:2350: found /usr/bin/gcc
configure:2361: result: gcc
configure:2590: checking for C compiler version
configure:2599: gcc --version >&5
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2610: $? = 0
configure:2599: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 
configure:2610: $? = 0
configure:2599: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:2610: $? = 1
configure:2599: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
gcc: fatal error: no input files
compilation terminated.
configure:2610: $? = 1
configure:2615: checking for suffix of object files
configure:2637: gcc -c -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  conftest.c >&5
configure:2641: $? = 0
configure:2662: result: o
configure:2666: checking whether we are using the GNU C compiler
configure:2685: gcc -c -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  conftest.c >&5
configure:2685: $? = 0
configure:2694: result: yes
configure:2703: checking whether gcc accepts -g
configure:2723: gcc -c -g  conftest.c >&5
configure:2723: $? = 0
configure:2764: result: yes
configure:2884: checking for readelf
configure:2900: found /usr/bin/readelf
configure:2911: result: readelf
configure:2993: checking for g++
configure:3009: found /usr/bin/g++
configure:3020: result: g++
configure:3047: checking for C++ compiler version
configure:3056: g++ --version >&5
g++ (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3067: $? = 0
configure:3056: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --disable-libmpx --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC) 
configure:3067: $? = 0
configure:3056: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3067: $? = 1
configure:3056: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'; did you mean '--version'?
g++: fatal error: no input files
compilation terminated.
configure:3067: $? = 1
configure:3071: checking whether we are using the GNU C++ compiler
configure:3090: g++ -c   conftest.cpp >&5
configure:3090: $? = 0
configure:3099: result: yes
configure:3108: checking whether g++ accepts -g
configure:3128: g++ -c -g  conftest.cpp >&5
configure:3128: $? = 0
configure:3169: result: yes
configure:3194: checking whether g++ can link programs
configure:3217: g++ -o conftest -g -O2   conftest.cpp  >&5
configure:3217: $? = 0
configure:3240: g++ -o conftest -g -O2   -static conftest.cpp  >&5
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status
configure:3240: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Library"
| #define PACKAGE_TARNAME "glibc"
| #define PACKAGE_VERSION "(see version.h)"
| #define PACKAGE_STRING "GNU C Library (see version.h)"
| #define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
| #define PACKAGE_URL "https://www.gnu.org/software/glibc/"
| #define PKGVERSION "(GNU libc) "
| #define REPORT_BUGS_TO "<https://www.gnu.org/software/libc/bugs.html>"
| /* end confdefs.h.  */
| 
| #include <iostream>
| 
| int
| main()
| {
|   std::cout << "Hello, world!";
|   return 0;
| }
| 
configure:3255: result: no
configure:3794: gcc -c -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  conftest.c >&5
conftest.c: In function 'main':
conftest.c:18:2: error: #error no CET compiler support
 #error no CET compiler support
  ^~~~~
configure:3794: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Library"
| #define PACKAGE_TARNAME "glibc"
| #define PACKAGE_VERSION "(see version.h)"
| #define PACKAGE_STRING "GNU C Library (see version.h)"
| #define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
| #define PACKAGE_URL "https://www.gnu.org/software/glibc/"
| #define PKGVERSION "(GNU libc) "
| #define REPORT_BUGS_TO "<https://www.gnu.org/software/libc/bugs.html>"
| #define HAVE_TUNABLES 1
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
| #ifndef __CET__
| #error no CET compiler support
| #endif
|   ;
|   return 0;
| }
configure:3853: checking for sysdeps preconfigure fragments
configure:6: checking for grep that handles long lines and -e
configure:64: result: /usr/bin/grep
configure:69: checking for egrep
configure:131: result: /usr/bin/grep -E
configure:6: checking for grep that handles long lines and -e
configure:64: result: /usr/bin/grep
configure:69: checking for egrep
configure:131: result: /usr/bin/grep -E
configure:9: checking whether gcc compiles in -mx32 mode by default
configure:27: gcc -c -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  conftest.c >&5
conftest.c:13:3: error: #error not x32
 # error not x32
   ^~~~~
configure:27: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Library"
| #define PACKAGE_TARNAME "glibc"
| #define PACKAGE_VERSION "(see version.h)"
| #define PACKAGE_STRING "GNU C Library (see version.h)"
| #define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
| #define PACKAGE_URL "https://www.gnu.org/software/glibc/"
| #define PKGVERSION "(GNU libc) "
| #define REPORT_BUGS_TO "<https://www.gnu.org/software/libc/bugs.html>"
| #define HAVE_TUNABLES 1
| /* end confdefs.h.  */
| #ifndef __ILP32__
| # error not x32
| #endif
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:34: result: no
configure:3860: result: 
configure:3890: checking for use of fpu sysdeps directories
configure:3909: result: yes
configure:3913: checking for -fstack-protector
configure:3919: gcc -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  -Werror -fstack-protector -xc /dev/null -S -o /dev/null
configure:3922: $? = 0
configure:3930: result: yes
configure:3933: checking for -fstack-protector-strong
configure:3939: gcc -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  -Werror -fstack-protector-strong -xc /dev/null -S -o /dev/null
configure:3942: $? = 0
configure:3950: result: yes
configure:3953: checking for -fstack-protector-all
configure:3959: gcc -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  -Werror -fstack-protector-all -xc /dev/null -S -o /dev/null
configure:3962: $? = 0
configure:3970: result: yes
configure:4013: checking for assembler and linker STT_GNU_IFUNC support

Relocation section '.rela.plt' at offset 0x110 contains 1 entry:
  Offset          Info           Type           Sym. Value    Sym. Name + Addend
000000600128  000000000025 R_X86_64_IRELATIV                    400128
configure:4044: result: yes
configure:4048: checking for gcc attribute ifunc support
configure:4074: result: yes
configure:4079: checking whether the linker supports textrels along with ifunc
configure:4109: gcc -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value   -nostartfiles -nostdlib -fno-stack-protector -pie -o conftest conftest.S
configure:4112: $? = 0
configure:4119: result: yes
configure:4124: checking if compiler warns about alias for function with incompatible types
conftest.c:9:34: error: 'foo_alias' alias between functions of incompatible types 'int(const void *, int)' and 'int (*(void))(const void *, int)' [-Werror=attribute-alias]
 extern __typeof (__redirect_foo) foo_alias __attribute__ ((alias ("foo")));
                                  ^~~~~~~~~
conftest.c:4:28: note: aliased declaration here
 __typeof (__redirect_foo) *foo_impl (void)
                            ^~~~~~~~
cc1: all warnings being treated as errors
configure:4146: result: yes
configure:4184: checking sysdep dirs
configure:4381: result: sysdeps/generic
configure:4401: checking for a BSD-compatible install
configure:4469: result: /usr/bin/install -c
configure:4484: checking whether ln -s works
configure:4488: result: yes
configure:4514: checking whether as is GNU as
configure:4528: result: yes
configure:4533: checking whether ld is GNU ld
configure:4547: result: yes
configure:4557: checking for as
configure:4584: result: as
configure:4599: checking version of as
configure:4609: result: 2.30, ok
configure:4687: checking for ld
configure:4714: result: ld
configure:4729: checking version of ld
configure:4739: result: 2.30, ok
configure:4754: checking for gnumake
configure:4784: result: no
configure:4754: checking for gmake
configure:4770: found /usr/bin/gmake
configure:4781: result: gmake
configure:4796: checking version of gmake
configure:4806: result: 4.2.1, ok
configure:4818: checking for gnumsgfmt
configure:4848: result: no
configure:4818: checking for gmsgfmt
configure:4848: result: no
configure:4818: checking for msgfmt
configure:4834: found /usr/bin/msgfmt
configure:4845: result: msgfmt
configure:4860: checking version of msgfmt
configure:4870: result: 0.19.8.1, ok
configure:4881: checking for makeinfo
configure:4911: result: no
configure:4944: checking for sed
configure:4960: found /usr/bin/sed
configure:4971: result: sed
configure:4986: checking version of sed
configure:4996: result: 4.5, ok
configure:5007: checking for gawk
configure:5023: found /usr/bin/gawk
configure:5034: result: gawk
configure:5049: checking version of gawk
configure:5059: result: 4.2.1, ok
configure:5070: checking for bison
configure:5086: found /usr/bin/bison
configure:5097: result: bison
configure:5112: checking version of bison
configure:5122: result: 3.0.4, ok
configure:5130: checking if gcc is sufficient to build libc
configure:5150: gcc -c -O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value  conftest.c >&5
configure:5150: $? = 0
configure:5157: result: yes
configure:5206: checking for nm
configure:5222: found /usr/bin/nm
configure:5233: result: nm
configure:5331: checking for python3
configure:5347: found /usr/bin/python3
configure:5358: result: python3
configure:5373: checking version of python3
configure:5383: result: 3.6.8, ok
configure:5400: WARNING:
*** These auxiliary programs are missing or incompatible versions: makeinfo
*** some features or tests will be disabled.
*** Check the INSTALL file for required versions.
configure:5451: checking LD_LIBRARY_PATH variable
configure:5461: result: contains current directory
configure:5464: error: 
*** LD_LIBRARY_PATH shouldn't contain the current directory when
*** building glibc. Please change the environment variable
*** and run configure again.

## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value='-O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value'
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-pc-linux-gnu
ac_cv_objext=o
ac_cv_path_EGREP='/usr/bin/grep -E'
ac_cv_path_GREP=/usr/bin/grep
ac_cv_path_install='/usr/bin/install -c'
ac_cv_prog_AS=as
ac_cv_prog_AWK=gawk
ac_cv_prog_BISON=bison
ac_cv_prog_LD=ld
ac_cv_prog_MAKE=gmake
ac_cv_prog_MSGFMT=msgfmt
ac_cv_prog_PYTHON_PROG=python3
ac_cv_prog_SED=sed
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_ac_ct_NM=nm
ac_cv_prog_ac_ct_READELF=readelf
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
libc_cv_compiler_default_cet=no
libc_cv_compiler_ok=yes
libc_cv_cxx_link_ok=no
libc_cv_gcc_incompatible_alias=yes
libc_cv_gcc_indirect_function=yes
libc_cv_ld_gnu_indirect_function=yes
libc_cv_nss_crypt=no
libc_cv_prog_as_gnu=yes
libc_cv_prog_ld_gnu=yes
libc_cv_ssp=yes
libc_cv_ssp_all=yes
libc_cv_ssp_strong=yes
libc_cv_static_nss_crypt=no
libc_cv_textrel_ifunc=yes
libc_cv_with_fp=yes
libc_cv_x32=no

## ----------------- ##

AR='ar'
AS='as'
ASFLAGS_config=''
AUTOCONF='no'
AWK='gawk'
BASH_SHELL=''
BISON='bison'
BUILD_CC=''
CC='gcc'
CFLAGS='-O2 -Wp,-U_FORTIFY_SOURCE -fno-stack-protector -Wno-unused-value'
CPP='gcc -E'
CPPFLAGS=''
CPPUNDEFS=''
CXX=''
CXXFLAGS='-g -O2'
CXX_BITS_STD_ABS_H=''
CXX_CMATH_HEADER=''
CXX_CSTDLIB_HEADER=''
CXX_SYSINCLUDES=''
DEFINES=''
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
GPROF='gprof'
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_INFO=''
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
LD='ld'
LDFLAGS=''
LIBGD=''
LIBOBJS=''
LIBS=''
LN_S='ln -s'
LTLIBOBJS=''
MAKE='gmake'
MAKEINFO=':'
MSGFMT='msgfmt'
NM='nm'
OBJCOPY='objcopy'
OBJDUMP='objdump'
OBJEXT='o'
PACKAGE_BUGREPORT='https://sourceware.org/bugzilla/'
PACKAGE_NAME='GNU C Library'
PACKAGE_STRING='GNU C Library (see version.h)'
PACKAGE_TARNAME='glibc'
PACKAGE_URL='https://www.gnu.org/software/glibc/'
PACKAGE_VERSION='(see version.h)'
PATH_SEPARATOR=':'
PERL=''
PKGVERSION='(GNU libc) '
PKGVERSION_TEXI='(GNU libc) '
PYTHON='python3 -B'
PYTHON_PROG='python3'
READELF='readelf'
RELEASE=''
REPORT_BUGS_TEXI='@uref{https://www.gnu.org/software/libc/bugs.html}'
REPORT_BUGS_TO='<https://www.gnu.org/software/libc/bugs.html>'
SED='sed'
SHELL='/bin/sh'
SYSINCLUDES=''
VERSION=''
ac_ct_CC='gcc'
ac_ct_CXX='g++'
all_warnings=''
base_machine='x86_64'
bindir='${exec_prefix}/bin'
bindnow='no'
build='x86_64-pc-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_crypt='yes'
build_nscd='default'
build_obsolete_nsl='no'
build_os='linux-gnu'
build_pt_chown='no'
build_vendor='pc'
cross_compiling='no'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
enable_timezone_tools='yes'
enable_werror='yes'
exec_prefix='NONE'
experimental_malloc='yes'
extra_nonshared_cflags=''
fno_unit_at_a_time=''
force_install='yes'
hardcoded_path_in_tests='no'
have_libaudit=''
have_libcap=''
have_selinux=''
have_tunables='yes'
host='x86_64-pc-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='pc'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
ldd_rewrite_script=''
libc_cv_cc_loop_to_function=''
libc_cv_cc_nofma=''
libc_cv_cc_pie_default=''
libc_cv_cc_submachine=''
libc_cv_cc_with_libunwind=''
libc_cv_complocaledir=''
libc_cv_cxx_thread_local=''
libc_cv_fpie=''
libc_cv_gcc_unwind_find_fde=''
libc_cv_has_glob_dat=''
libc_cv_hashstyle=''
libc_cv_insert=''
libc_cv_localstatedir=''
libc_cv_mtls_dialect_gnu2=''
libc_cv_multidir=''
libc_cv_nss_crypt='no'
libc_cv_output_format=''
libc_cv_pic_default=''
libc_cv_pie_default=''
libc_cv_protected_data=''
libc_cv_rootsbindir=''
libc_cv_rtlddir=''
libc_cv_slibdir=''
libc_cv_ssp='yes'
libc_cv_static_nss_crypt='no'
libc_cv_sysconfdir=''
libc_cv_textrel_ifunc='yes'
libc_cv_with_fp='yes'
libc_cv_z_combreloc=''
libc_cv_z_execstack=''
libc_extra_cflags=''
libc_extra_cppflags=''
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
link_obsolete_rpc='no'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mach_interface_list=''
mandir='${datarootdir}/man'
multi_arch='default'
no_stack_protector='-fno-stack-protector -DSTACK_PROTECTOR_LEVEL=0'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/root/graphene/graphene/LibOS/../Runtime'
profile='no'
program_transform_name='s,x,x,'
psdir='${docdir}'
sbindir='${exec_prefix}/sbin'
shared='yes'
sharedstatedir='${prefix}/com'
stack_protector='-fno-stack-protector'
static=''
static_nss='no'
subdirs=' '
submachine=''
sysconfdir='${prefix}/etc'
sysheaders=''
sysnames=' sysdeps/unix/sysv/linux/x86_64/64 sysdeps/unix/sysv/linux/x86_64 sysdeps/unix/sysv/linux/x86 sysdeps/x86/nptl sysdeps/unix/sysv/linux/wordsize-64 sysdeps/x86_64/nptl sysdeps/unix/sysv/linux sysdeps/nptl sysdeps/pthread sysdeps/gnu sysdeps/unix/inet sysdeps/unix/sysv sysdeps/unix/x86_64 sysdeps/unix sysdeps/posix sysdeps/x86_64/64 sysdeps/x86_64/fpu/multiarch sysdeps/x86_64/fpu sysdeps/x86/fpu sysdeps/x86_64/multiarch sysdeps/x86_64 sysdeps/x86 sysdeps/ieee754/float128 sysdeps/ieee754/ldbl-96 sysdeps/ieee754/dbl-64/wordsize-64 sysdeps/ieee754/dbl-64 sysdeps/ieee754/flt-32 sysdeps/wordsize-64 sysdeps/ieee754 sysdeps/generic'
target_alias=''
use_default_link='default'
use_ldconfig=''
use_nscd='no'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "GNU C Library"
#define PACKAGE_TARNAME "glibc"
#define PACKAGE_VERSION "(see version.h)"
#define PACKAGE_STRING "GNU C Library (see version.h)"
#define PACKAGE_BUGREPORT "https://sourceware.org/bugzilla/"
#define PACKAGE_URL "https://www.gnu.org/software/glibc/"
#define PKGVERSION "(GNU libc) "
#define REPORT_BUGS_TO "<https://www.gnu.org/software/libc/bugs.html>"
#define HAVE_TUNABLES 1
#define HAVE_CC_NO_STACK_PROTECTOR 1
#define STACK_PROTECTOR_LEVEL 0
#define USE_MULTIARCH 1

configure: exit 1

**Comment by WilliamXieIntel** [comment]
unset LD_LIBRARY_PATH by "export LD_LIBRARY_PATH=" resolved the issue.
Not sure why yet.

**Comment by dimakuv** [comment]
It's due to the fact that Graphene builds Glibc as part of its own build. And Glibc doesn't build correctly with some `LD_LIBRARY_PATH` values. See https://github.com/Linuxbrew/legacy-linuxbrew/issues/141.
