### ISSUE TITLE
Memory protection not working when using SGX

### ISSUE THREAD

**Issue by hanjae** [oscarlab/graphene#172]
Memory region with `PROT_NONE` shouldn't be accessed, but when using SGX the region is accessible.

```
#include <stdio.h>
#include <unistd.h>
#include <sys/mman.h>

int main (int argc, const char ** argv)
{
    char *mem = (char *)mmap(NULL, 10, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0);
    sprintf(mem, "TEST");
    printf("%s\n", mem);

    return 0;
}
```
This code should raise SIGSEGV but correctly write text and print with SGX.

**Comment by chiache** [comment]
Hi, Hanjae,

This is a known limitation of Graphene on the current SGX hardware. To enable dynamic page protection, Graphene needs EMODPR and EMODPE instructions from SGX2. We are working internally with our contributors to port Graphene to SGX2. Currently, SGX2 is only available on formally Gemini Lake processors (https://ark.intel.com/products/codename/83915/Gemini-Lake).

Thanks for the comment.

**Comment by hanjae** [comment]
Ok, I see.
Thank you for the explanation.
