### ISSUE TITLE
How to run ./pal_loader

### ISSUE THREAD

**Issue by kleirama** [oscarlab/graphene#1722]
I am trying to run `pal_loader` using the following command:
` SGX=1 ./pal_loader b-kernel-dynamic.manifest` but I get the following error:
```
Manifest file: file:b-kernel-dynamic.manifest.sgx
Inferred executable file: file:b-kernel-dynamic
Cannot read manifest: equal mark expected
Invalid manifest: file:b-kernel-dynamic.manifest.sgx
```
My directory looks like that:

```
root@kleira-OptiPlex-7060:~/graphene/Examples/VNF_LinuxKernel# ls
b-kernel-dynamic.manifest      b-kernel-dynamic.manifest.template  b-kernel-dynamic.token  pal_loader
b-kernel-dynamic.manifest.sgx  b-kernel-dynamic.sig                Makefile                src
```
Am I running pal_loader with wrong arguments or is that there is an error when I build my manifest using 

> make SGX=1

When I executed the above command I did not get any error though and .token, .sig, .manifest.sgx files were generated 

I need some help. I tried to follow the  `Makefile` and `redis.manifest.tempalte` logic to build my `Makefile and b-kernel-dynamic.manifest.templat`e file. The problem is that I wan not able to get the script **redis-server** which is generated at `/$(GrapheneDir)/Examples/redis` directory because of the way I have written my `Makefile` so I think I need to run ./pal_loader using a manifest file instead

**Comment by mkow** [comment]
I guess you have a hyphen in a key name in the manifest? This is not supported by the current syntax, but you can work around it by using an underscore instead.
And yes, current manifest syntax and parsing is terrible, I hope someday we'll find somebody to work on #870.

**Comment by kleirama** [comment]
Hei @mkow do you mean that I need to change b-kernel-dynamic into b_kernel_dynamic?

**Comment by mkow** [comment]
> My question may sound weird but I did not quite get what you mean a hyphen of a key name in the manifest file

See the docs: https://graphene.readthedocs.io/en/latest/manifest-syntax.html#basic-syntax:
> [Key][.Key][.Key] = [Value]  or  [Key][.Key][.Key] = "[Value]"

Probably one of your keys contains a hyphen (`-`).

> redis-server runs without a problem and it also does not have an underscore?

It contains hyphens only in the values, not in the keys.

**Comment by dimakuv** [comment]
Just to make @mkow 's point more concrete: you should change your `b-kernel-dynamic.manifest.template` to not contain keys with a hyphen (`-`) and generally any non-alphabet symbols, like this:
```
# Graphene fails to parse the below syntax
sgx.trusted_files.b-kernel-dynamic = file:src/b-kernel-dynamic

# but Graphene correctly parses the below syntax
sgx.trusted_files.b_kernel_dynamic = file:src/b-kernel-dynamic
```

**Comment by kleirama** [comment]
@dimakuv  I am confused now. b-kernel-dynamic is my executabel just like it is redis-server. 
I have this kind of manifest.template file

 ```
1	loader.exec = file:b-kernel-dynamic
       
     2	loader.preload = file:$(GRAPHENEDIR)/Runtime/libsysdb.so
       
     3	loader.debug_type = $(GRAPHENEDEBUG)
       
     4	loader.insecure__use_cmdline_argv = 1
       
     5	loader.env.LD_LIBRARY_PATH = /lib:$(ARCH_LIBDIR):/usr/$(ARCH_LIBDIR)
       
     6	fs.mount.lib.type = chroot
     7	fs.mount.lib.path = /lib
     8	fs.mount.lib.uri = file:$(GRAPHENEDIR)/Runtime
       
     9	fs.mount.lib2.type = chroot
    10	fs.mount.lib2.path = $(ARCH_LIBDIR)
    11	       fs.mount.lib2.uri = file:$(ARCH_LIBDIR)
       
    12	fs.mount.lib3.type = chroot
    13	fs.mount.lib3.path = /usr/$(ARCH_LIBDIR)
    14	fs.mount.lib3.uri = file:/usr/$(ARCH_LIBDIR)
       
    15	fs.mount.lib4.type = chroot
    16	fs.mount.lib4.path = /usr/lib
    17	        fs.mount.lib4.uri = file:/usr/lib
       
    18	fs.mount.etc.type = chroot
    19	fs.mount.etc.path = /etc
    20	fs.mount.etc.uri = file:/etc
       
    21	sgx.enclave_size = 1024M
    22	sgx.thread_num = 8
       
    23	sgx.trusted_files.ld = file:$(GRAPHENEDIR)/Runtime/ld-linux-x86-64.so.2
    24	sgx.trusted_files.libc = file:$(GRAPHENEDIR)/Runtime/libc.so.6
    25	sgx.trusted_files.libm = file:$(GRAPHENEDIR)/Runtime/libm.so.6
    26	sgx.trusted_files.libdl = file:$(GRAPHENEDIR)/Runtime/libdl.so.2
    27	sgx.trusted_files.librt = file:$(GRAPHENEDIR)/Runtime/librt.so.1
    28	sgx.trusted_files.libpthread = file:$(GRAPHENEDIR)/Runtime/libpthread.so.0
       
       
    29	sgx.trusted_files.libvnfkerneldynamic  = file:/usr/lib/libvnf-kernel-dynamic.so
    30	sgx.trusted_files.libspdlog  = file:/usr/$(ARCH_LIBDIR)/libspdlog.so.1.7.0
    31	sgx.trusted_files.libsctp = file:/usr/$(ARCH_LIBDIR)/libsctp.so.1.0.17
    32	sgx.trusted_files.libboostatomic = file:/usr/$(ARCH_LIBDIR)/libboost_atomic.so.1.65.1
    33	sgx.trusted_files.libboostchrono = file:/usr/$(ARCH_LIBDIR)/libboost_chrono.so.1.65.1
    34	sgx.trusted_files.libboostcontainer = file:/usr/$(ARCH_LIBDIR)/libboost_container.so.1.65.1
    35	sgx.trusted_files.libboostcontext = file:/usr/$(ARCH_LIBDIR)/libboost_context.so.1.65.1
       
    36	sgx.allowed_files.nsswitch  = file:/etc/nsswitch.conf
    37	sgx.allowed_files.hosts     = file:/etc/hosts
    38	sgx.allowed_files.hosts     = file:/etc/ethers
```
Now when I run it as SGX=1 ./pal_loader b-kernel-dynamic I got the following error:

> Manifest file: file:b-kernel-dynamic.manifest.sgx
> Executable file: file:b-kernel-dynamic
> Cannot read manifest: key format invalid
> Invalid manifest: file:b-kernel-dynamic.manifest.sgx

I am trying to deby why my key format is invalid but could not find any error. I would really appreciate if you can help me about this error

**Comment by mkow** [comment]
```
   15	fs.mount.lib4.type = chroot
   16	fs.mount.lib4.path = /usr/lib
   17	        fs.mount.lib4.uri = file:/usr/lib
```

Try removing leading blanks from the last line here.

**Comment by mkow** [comment]
(same in one more place)

**Comment by dimakuv** [comment]
Follow @mkow's advice. But I also notice this:
```
   37	sgx.allowed_files.hosts     = file:/etc/hosts
   38	sgx.allowed_files.hosts     = file:/etc/ethers
```

You cannot have the same key for two different files! Please fix to:
```
   37	sgx.allowed_files.hosts     = file:/etc/hosts
   38	sgx.allowed_files.ethers    = file:/etc/ethers
```

**Comment by kleirama** [comment]
@mkow thank you for your reply. However that was just a typo of me when writing the code of manifest here but in my manifest template I do not have those spaces,@dimakuv thank you for pointing out that I have the same key to two different files, I will try to run it again.

**Comment by kleirama** [comment]
Now I am able to run graphene server but I got the following error. I just want to know if that error is part of graphene or it is because I have not correctly configured my manifest file. If it is graphene error can you please tell me what this error means, if it is an error of my side then I will try to figure it out the problem by myself.

```
sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
assert failed fs/shim_fs.c:447 dent == dentry_root || !(dent->state & DENTRY_VALID)
DkProcessExit: Returning exit code -131
Saturation error in exit code -131, getting rounded down to 125
```

**Comment by dimakuv** [comment]
It's hard to say what it is without the debug output. Please rebuild your example with `make SGX=1 DEBUG=1` and check the log.

Regarding your manifest, I see two additional potential issues:
```
# your manifest option
loader.env.LD_LIBRARY_PATH = /lib:$(ARCH_LIBDIR):/usr/$(ARCH_LIBDIR)

# proposed manifest option
loader.env.LD_LIBRARY_PATH = /lib:$(ARCH_LIBDIR):/usr/$(ARCH_LIBDIR):/usr/lib
```

This is because you mount `/usr/lib` and have a file under this directory (`file:/usr/lib/libvnf-kernel-dynamic.so`), but you don't specify this directory as "searchable for libraries".

The second potential issue is you're not propagating environment variables. Please check if adding `loader.insecure__use_host_env = 1` to your manifest helps. If it does, please read https://graphene.readthedocs.io/en/latest/manifest-syntax.html#environment-variables for more information.

**Comment by kleirama** [comment]
@dimakuv I followed all your advices above and I still get the same error: The output below is with DEBUG argument enabled

```
sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Forwarding host environment variables to the app is enabled. Don't use this configuration in production!
[P04386] host: Linux-SGX
[P04386] Initial VMA region 0x83b7bd000-0x83b8d6000 (LibOS) bookkeeped
[P04386] Initial VMA region 0x83fffc000-0x840000000 (manifest) bookkeeped
[P04386] Initial VMA region 0x83b8d6000-0x83b924000 (exec) bookkeeped
[P04386] ASLR top address adjusted to 0x831107000
[P04386] shim loaded at 0x83b7bd000, ready to initialize
[P04386] mounting default root filesystem
[P04386] mounting as proc filesystem: /proc
[P04386] mounting as dev filesystem: /dev
[P04386] mounting as chroot filesystem: from dev:tty to /dev
[P04386] creating pipe: pipe.srv:557388066
[P04386] Adding port (handle 0x83b9d6951) for process 4386 (type 0002)
[P04386] allocated pid: 1
[     1] mounting as chroot filesystem: from file:../../Runtime to /lib
[     1] mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[     1] mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[     1] mounting as chroot filesystem: from file:/usr/lib to /usr/lib
assert failed fs/shim_fs.c:447 dent == dentry_root || !(dent->state & DENTRY_VALID)
[     1] Deleting port 0x83af6b048 (handle 0x83b9d6951) of process 4386
[     1] process 4386 exited with status -131
DkProcessExit: Returning exit code -131
Saturation error in exit code -131, getting rounded down to 125
```

So even though I took care of both potential issues you suggested at me, I still got the same problem.

**Comment by dimakuv** [comment]
Thanks! Now we can see the issue:
```
[     1] mounting as chroot filesystem: from file:/usr//lib/x86_64-linux-gnu to /usr//lib/x86_64-linux-gnu
[     1] mounting as chroot filesystem: from file:/usr/lib to /usr/lib
```

You are mounting two points: one is the direct child of the other one. This makes no sense, at least in Graphene, so it fails.

This happens because you have these two mount points in the manifest:
```
   12	fs.mount.lib3.type = chroot
   13	fs.mount.lib3.path = /usr/$(ARCH_LIBDIR)
   14	fs.mount.lib3.uri = file:/usr/$(ARCH_LIBDIR)
      
   15	fs.mount.lib4.type = chroot
   16	fs.mount.lib4.path = /usr/lib
   17	fs.mount.lib4.uri = file:/usr/lib
```

Please remove the first mount point (lines 12-14) since the second mount point already subsumes it. Rebuild and try again.

**Comment by kleirama** [comment]
@dimakuv and @mkow  now everything works fine, thanks to your helpful comments. You may close this issue now
