### ISSUE TITLE
Does the performance of an application porting in Graphene decrades after different several runnings?

### ISSUE THREAD

**Issue by markueni** [oscarlab/graphene#1739]
Hi,

I have ported an application in **_Graphene-SGX_** and performed some benchmark testing. At first performance was close to vanilla application but now it is degraded a lot. After each run I execute `make SGX=1 distclean` and then I rebuild again using `make SGX=1 DEBUG=1`. However when I run the applicat now as `SGX=1 ./pal_loader $(my_executable)`  the performance is 60% less than before and sometimes it even fails. I can not run my application for more than 20 seconds otherwise I get the following error
```
ERROR: epoll monitoring failed, closing fd
[     1] ---- return from shim_write(...) = 43
[     1] signal delayed (2)
[     1] ---- shim_close(0) = 0
[     1] signal delayed (2)
[     1] ---- shim_close(0) = -9
[     1] signal delayed (2)
[     1] ---- shim_munmap(0x81734b000,33558528) ... munmap
[     1] ---- return from shim_munmap(...) = 0
[     1] signal delayed (2)
[     1] ---- shim_write(1,0x819c69250,57) ... write
```

Is this a disadvante of Graphene or have I not cleared the enclave pages somehow after several runnings. I am surprised now because all day long the performance was great but now for some reason it is bad. Can you please tell me what is going on?

**Comment by dimakuv** [comment]
This should never be the case. Something is happening with your system. I can imagine several issues:

1. You actually run Graphene in different settings. Maybe the first couple times you ran Graphene, you didn't have many client requests, but the next time you had a flood of client requests -- Graphene's performance will be different.

2. You have "zombie" processes in your system. Maybe these are "not fully terminated" old Graphene processes, maybe something else. If you for example experience the same degradation of Graphene *even after reboot*, then it gets interesting...

3. Maybe you were just unlucky and your system decided to upgrade during the last run of Graphene? Again, it's not about Graphene but about some background processes running on your system.

**Comment by markueni** [comment]
After reboot that problem was gone. I am not sure though but I guess the second option you mentioned is most likely. 
I have another question off-topic. Is it possible to run Graphene-SGX in a VM with no KVM and QEMU patches. I always run it on my host machine but I want to try and run my application in a virtualized environment. I knew that there were issues of SGX inside VMs and the only way to do that was with KVM and QEMU patches. Do you know if SGX community has tackled that at this moment of speaking?

**Comment by dimakuv** [comment]
@markueni Glad you fixed the original problem! Regarding KVM/QEMU: unfortunately, I am not aware of the current status of VM support of SGX. The last time I checked it was not upstreamed, so one had to rely on custom Intel patches to KVM/QEMU. I will try to ask those developers and get back to you if I know any new info.
