### ISSUE TITLE
Remove manifest/config entries limit

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#174]
There's a hardcoded limit for a total number of config entries. Is there any reason why it's needed? Can we remove it?

https://github.com/oscarlab/graphene/blob/15c2950e0a2afdd9e7595ced62421d62c141c8b0/Pal/lib/api.h#L144

**Comment by donporter** [comment]
I don't have any principled reason to limit the number of entries.  It is used in several places in the code as a convenience.  Assuming you had a patch that replaced them with code that dynamically allocated enough memory for the config, I'd be happy to accept the change.

**Comment by mkow** [comment]
I have a fix for this but I'm waiting with a PR until #183 is merged.
