### ISSUE TITLE
Can one run several executables inside a single enclave at once?

### ISSUE THREAD

**Issue by markueni** [oscarlab/graphene#1745]
Hei,

I have a scenarion in which I run a VNF over my VNF framework. I have created 5 VNFs component where 4 of them use APIs of my VNF framework. Now I want to run these VNFs component build over my VNF framework inside enclave. When I run it normally (no Graphene used) I run it in that order .`/hss ./icscf ./pcscf ./scscf`. Now the way I decided to run them over Graphene-SGX is as below:

In `../../$(GRAPHENEDIR)/Examples/$(my_created_directory)` I have a .manifest.template for each of the four components mentioned above. Respectively `hss.manifest.template, icscf.manifest.template, pcscf.manifest.template, scscf.manifest.template`

My Makefile looks like this:

```
# Relative path to Graphene root
GRAPHENEDIR = ../..
SGX_SIGNER_KEY ?= $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem

#SRCDIR = src
#COMMIT = master
#TAR_SHA256 = 35839b9b8d2889e67e452aaccdd202797bfd0014

ifeq ($(DEBUG),1)
GRAPHENEDEBUG = inline
else
GRAPHENEDEBUG = none
endif

.PHONY: all
all:  hss.manifest      icscf.manifest  pcscf.manifest scscf.manifest   pal_loader
ifeq ($(SGX),1)
all: hss.manifest.sgx   icscf.manifest.sgx      pcscf.manifest.sgx      scscf.manifest.sgx
endif

include ../../Scripts/Makefile.configs

hss.manifest:   hss.manifest.template
        sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
icscf.manifest:   icscf.manifest.template
        sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
pcscf.manifest:   pcscf.manifest.template
        sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
scscf.manifest:   scscf.manifest.template
        sed -e 's|$$(GRAPHENEDIR)|'"$(GRAPHENEDIR)"'|g' \
                -e 's|$$(GRAPHENEDEBUG)|'"$(GRAPHENEDEBUG)"'|g' \
                -e 's|$$(ARCH_LIBDIR)|'"$(ARCH_LIBDIR)"'|g' \
                $< > $@
hss.manifest.sgx: hss.manifest  /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/hss
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(SGX_SIGNER_KEY) \
                -manifest $< -output $@ \
                -exec   /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/hss
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
                -output hss.token -sig hss.sig

icscf.manifest.sgx: icscf.manifest  /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/icscf
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(SGX_SIGNER_KEY) \
                -manifest $< -output $@ \
                -exec   /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/icscf
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
                -output icscf.token -sig icscf.sig

pcscf.manifest.sgx: pcscf.manifest  /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/pcscf
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(SGX_SIGNER_KEY) \
                -manifest $< -output $@ \
                -exec   /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/pcscf
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
                -output pcscf.token -sig pcscf.sig

scscf.manifest.sgx: scscf.manifest  /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/scscf
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(SGX_SIGNER_KEY) \
                -manifest $< -output $@ \
                -exec   /home/eniom/graphene/Examples/libVNF_kernel_socc_ims/scscf
                $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
                -output scscf.token -sig scscf.sig
########################### COPIES OF EXECUTABLES #############################

# Redis build process creates the final executable as src/redis-server. For
# simplicity, copy it into our root directory.
# Also, create a link to pal_loader for simplicity.

#b-kernel-dynamic: $(SRCDIR)/src/libVNF-master
#       cp $< $@

pal_loader:
        ln -s $(GRAPHENEDIR)/Runtime/pal_loader $@

############################## RUNNING TESTS ##################################
.PHONY: start-native-server
start-native-server: all
        ./hss ./pcscf ./icscf ./scscf --save '' --protected-mode no

.PHONY: start-graphene-server
start-graphene-server: all
        ./pal_loader hss icscf pcscf scscf --save '' --protected-mode no

################################## CLEANUP ####################################

.PHONY: clean
clean:
        $(RM) *.token *.sig *.manifest.sgx *.manifest pal_loader  *.rdb

.PHONY: distclean
distclean: clean
        $(RM) *.token *.sig *.manifest.sgx *.manifest pal_loader
```

Now when I execute `make SGX=1 DEBUG=1` there is no error and everything looks fine.
After that I execute `SGX=1 ./pal_loader hss icscf pcscf scscf`

This also executes without problem, but then when I start `./ran 1 30` which is not built over Graphene, nothing happens and no packets are recieved.

In the case when I start the four components above without Graphene and then execute `./ran 1 30`, I receive thousands of packets _for 30 seconds for a single thread_ but in case when I run components in Graphene I receive **0** packets.

I am wondering, if it is possible to place all executables inside an enclave and if they are supposed to communicate with each other as they do without Graphene

**Comment by mkow** [comment]
Graphene can only run a single executable, but it is allowed to fork into more processes later. So, you can create an "entrypoint" shell script or executable which would then spawn all required processes. They will run in separate processes and enclaves, but inside the same Graphene namespace.

**Comment by markueni** [comment]
@mkow 

`So, you can create an "entrypoint" shell script or executable which would then spawn all required processes`

I would appreciate if you can elaborate this for me a bit more related to my scenario.

Do you mean that for my executable hss I need to modify it in the way that it calls all three other processes once it runs inside enclave? Is there any example in Graphene repository which has similiar situation with my example so I could take a look on my own to understand it better

**Comment by mkow** [comment]
> I need to modify it in the way that it calls all three other processes once it runs inside enclave?

Yes.

> Is there any example in Graphene repository which has similiar situation with my example so I could take a look on my own to understand it better

AFAIR there isn't any. But you can just use a shell script or a simple C/C++ program spawning a few processes, there's nothing more to this.

**Comment by markueni** [comment]
@mkow I get your point and will do that. I have one concern though? When you have 4 processes running in different enclaves is performance supposed to downgrade a lot or it will be the same as it is when there is a single process in a single enclave?

**Comment by dimakuv** [comment]
Performance will be roughly the same because the real bottleneck is the size of EPC (physical enclave memory). It is currently 128MB on Intel CPUs. So you will likely hit this limit -- both with "4 smaller enclaves in 4 processes" and with "1 huge enclave in 1 process".

**Comment by dimakuv** [comment]
Be aware that **creating a process/enclave** is super-slow in SGX and Graphene. But **once the process/enclave is created**, the performance is good (and limited by the size of EPC).

**Comment by markueni** [comment]
I have ported this application in Graphene SGX, so 4 processes in 4 different enclaves which communicate with each other and when I did some benchmarking I see that performance is 10x slower. I have ported also another VNF which has a single process runnning inside enclave and in that case performance was great but now with these 4 processes and 4 enclaves the performance is way too bad :(.

**Comment by dimakuv** [comment]
We'll need more info from you to give better answers regarding performance overheads. What is the multi-processing communication you use? How many messages processes send to each other, how often? Do you periodically spawn new processes or start them all together once? Is this C/C++ or some other language?

**Comment by markueni** [comment]
I start all processes at once. It is 100%  c++ language. I send continously messages for a period of time I specify (30 seconds, 1 min, 5 min and so on). But the performance downgrade with 10x is when I try with 30 seconds. Also with one minute and 2 minutes and so on is still around 10x. Below is a more detailed description fo my scenario.

I am in `graphene/Example/$(my_directory)`. In this directory I have:
```
hss                    icscf                    Makefile        Makefile_pcscf  pcscf                    scscf                    src
hss.manifest.template  icscf.manifest.template  Makefile_icscf  Makefile_scscf  pcscf.manifest.template  scscf.manifest.templat
```
hss, icsf,scscf,pcscf are the four executables I have:
I build first hss using `make SGX=1 DEBUG=1`
Then I build icscf using `make SGX=1 DEBUG=1 -f Makefile_icscf`
Then I build pcscf using `make SGX=1 DEBUG=1 -f Makefile_pcscf`
Then I build scscf using `make SGX=1 DEBUG=1 -f Makefile_scscf`

After that I start **hss** like:
`SGX=1 ./pal_loader hss`
After this is ready to capture packets I start **icscf**
`SGX=1 ./pal_loader icscf`
Then `SGX=1 ./pal_loader pcscf` and in the end
`SGX=1 ./pal_loader scscf`

All this processes are now waiting for the component **run** which generate packets. This component does not run inside enclave. I start this component as `./ransim.out 1 30` where 1 is the number of threads and 30 is the number of seconds. After the component **run** starts, then **hss, icscf, pcscf and scscf** starts communicating with each other.
Hope I have explained it clearly enough for you so you may have the idea of my scenario clearly now.

Thnx for your collaboration

**Comment by dimakuv** [comment]
What is the EPC size of your machine where you test it? The current SGX machines have only 128MB and 256MB of EPC. When you create 4 enclaves, each of size 1GB, they all compete for this small amount of EPC. Basically, your machine tries to multiplex 4GB of enclave memory on 128/256MB of actual available memory. This leads to tremendous overheads due to *EPC paging*.

**Comment by markueni** [comment]
@dimakuv the EPC size of my machine is 256 MBs. Is there a way to overcome such problem? I have to run each component of my Network function application in separate enclaves, but I was also wondering is possible in Graphene-SGX to run all components within the same enclave instead of having 4 enclaves, so the components can still communicate to each other?

**Comment by dimakuv** [comment]
> Is there a way to overcome such problem?

No, it's a hardware limitation. The only way is to wait for new SGX hardware with larger EPC sizes and buy it :)

> is possible in Graphene-SGX to run all components within the same enclave instead of having 4 enclaves

No, unfortunately, Graphene doesn't support such a feature. You may take a look at Occlum though: https://github.com/occlum/occlum
