### ISSUE TITLE
[Graphere SGX]python invoke other python script problem.

### ISSUE THREAD

**Issue by bearDream** [oscarlab/graphene#1757]
## Description of the problem

I'm so sorry to ask this issue again. I have posted other issues and send mail to support@graphene-project.io but not solve my problem. 

I want to in a python script invoke another script (Like this: os.system('python3 helloworld.py')), but it is failed.
Invoke sequentially: python3.manifest -> sh.manifest -> python.manifest. There are three manifests separately.
With @dimakuv help, I have solved sh as a child process, but sh invoke python still exists.

The other about issues following:
https://github.com/oscarlab/graphene/issues/1696
https://github.com/oscarlab/graphene/issues/1736

## Steps to reproduce
In the master branch.

Three manifests in [here](https://github.com/oscarlab/graphene/issues/1736#issuecomment-668926436)
Debug output in [here](https://github.com/oscarlab/graphene/issues/1736#issuecomment-668358734)

## Expected results
hello world.

## Actual results
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError[    33] ---- return from shim_write(...) = 19
No module named 'encodings'[    33] ---- return from shim_write(...) = 27
Current thread 0x[    33] ---- return from shim_write(...) = 17
000000000b15a740[    33] ---- return from shim_write(...) = 16

I have added 'loader.insecure__use_host_env = 1' in all manifests.

Pretty thanks.

**Comment by llly** [comment]
```
proc = subprocess.Popen(["python3.6", "scripts/helloworld.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
```
can reproduce this issue.
I also have investigated my debug log and found Suspicious item.
```
[P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d853e0) = 0
[P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d84b80) = 0
[P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d85340) = 0
[P27698:T1:python3.6] ---- shim_openat(AT_FDCWD,"/usr/lib/python3.6",O_RDONLY|2204000,0000) = 3
[P27698:T1:python3.6] ---- shim_fstat(3,0x12d85260) = 0
[P27698:T1:python3.6] ---- shim_getdents64(3,0x11848a00,32768) = 7025
[P27698:T1:python3.6] ---- shim_getdents64(3,0x11848a00,32768) = 0
[P27698:T1:python3.6] ---- shim_close(3) = 0
```
This is from the parent python. getdents64("/usr/lib/python3.6") returns 7025.
```
[P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a223f0) = 0
[P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a21b90) = 0
[P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a22350) = 0
[P27716:T2:python3.6] ---- shim_openat(AT_FDCWD,"/usr/lib/python3.6",O_RDONLY|2204000,0000) = 3
[P27716:T2:python3.6] ---- shim_fstat(3,0x19a22270) = 0
[P27716:T2:python3.6] ---- shim_getdents64(3,0x184e5a00,32768) = 53
[P27716:T2:python3.6] ---- shim_getdents64(3,0x184e5a00,32768) = 0
[P27716:T2:python3.6] ---- shim_close(3) = 0
``` 
This is from the child python. getdents64("/usr/lib/python3.6") returns 53.

Maybe not all the trusted files in "/usr/lib/python3.6" are found by child python.

Hope it helps.

**Comment by bearDream** [comment]
> ```
> proc = subprocess.Popen(["python3.6", "scripts/helloworld.py"], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
> ```
> 
> can reproduce this issue.
> I also have investigated my debug log and found Suspicious item.
> 
> ```
> [P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d853e0) = 0
> [P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d84b80) = 0
> [P27698:T1:python3.6] ---- shim_stat("/usr/lib/python3.6",0x12d85340) = 0
> [P27698:T1:python3.6] ---- shim_openat(AT_FDCWD,"/usr/lib/python3.6",O_RDONLY|2204000,0000) = 3
> [P27698:T1:python3.6] ---- shim_fstat(3,0x12d85260) = 0
> [P27698:T1:python3.6] ---- shim_getdents64(3,0x11848a00,32768) = 7025
> [P27698:T1:python3.6] ---- shim_getdents64(3,0x11848a00,32768) = 0
> [P27698:T1:python3.6] ---- shim_close(3) = 0
> ```
> 
> This is from the parent python. getdents64("/usr/lib/python3.6") returns 7025.
> 
> ```
> [P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a223f0) = 0
> [P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a21b90) = 0
> [P27716:T2:python3.6] ---- shim_stat("/usr/lib/python3.6",0x19a22350) = 0
> [P27716:T2:python3.6] ---- shim_openat(AT_FDCWD,"/usr/lib/python3.6",O_RDONLY|2204000,0000) = 3
> [P27716:T2:python3.6] ---- shim_fstat(3,0x19a22270) = 0
> [P27716:T2:python3.6] ---- shim_getdents64(3,0x184e5a00,32768) = 53
> [P27716:T2:python3.6] ---- shim_getdents64(3,0x184e5a00,32768) = 0
> [P27716:T2:python3.6] ---- shim_close(3) = 0
> ```
> 
> This is from the child python. getdents64("/usr/lib/python3.6") returns 53.
> 
> Maybe not all the trusted files in "/usr/lib/python3.6" are found by child python.
> 
> Hope it helps.

Thanks for @llly response. But I think '53' is an early problem when I add "loader.insecure__use_host_env = 1" in manifests and some operations, this error not happened. This problem has been bothering me for more than a month.

**Comment by dimakuv** [comment]
@llly is right, as always. Thanks for debugging this!

I was able to reproduce this error, and indeed the root cause is that suspicious `shim_getdents64(3,0x184e5a00,32768) = 53` (in other words, Graphene reads much less files from `/usr/lib/python3.6` in the child process than it's supposed to).

I am currently debugging this. I will create a multi-process Python example per @bearDream requests. I'm sorry I didn't look into this earlier. I hope to submit the example and the bug fix this week.

**Comment by llly** [comment]
I cannot root cause this error and didn't create issue about it. I'm glad that I can help.

**Comment by dimakuv** [comment]
I fixed the bug and also added the Python multi-process example here: https://github.com/oscarlab/graphene/pull/1771. Please check it.

**Comment by bearDream** [comment]
Thanks for @dimakuv example provided.
