### ISSUE TITLE
protected file key  g_pf_wrap_key is not passed from parent to child during process creation

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1762]
## Description of the problem
I'm testing protected files using configs
```
loader.env.LD_PRELOAD = libsecret_prov_attest.so
loader.env.SECRET_PROVISION_CONSTRUCTOR = 1
loader.env.SECRET_PROVISION_SET_PF_KEY = 1
loader.env.SECRET_PROVISION_CA_CHAIN_PATH = 
loader.env.SECRET_PROVISION_SERVERS = 
```
similar to secret_prov_pf_client Example to provisioning protected file key from server .
`LD_PRELOAD = libsecret_prov_attest.so` helps unmodified program to store the key in file `/dev/attestation/protected_files_key` and env `SECRET_PROVISION_SECRET_STRING` then access protected_files transparently.
However, if unmodified program fork() or exec(), the trusted children cannot get protected file key anymore unless they communicate using ` libsecret_prov_attest.so` with server again.

I propose a design that trusted children inherit protected file key automatically. Only the first program of a program chain need to provision with the server. Other programs of a program chain can also access protected file using same key. It saves a lot of time.

## Steps to reproduce
Add `fork();` at https://github.com/oscarlab/graphene/blob/5cf182366a2d3e162d70fd9f68cf8b85a3ab050e/Examples/ra-tls-secret-prov/src/secret_prov_pf_client.c#L23, just before open protected file. 
rebuild and run `SGX=1 ./pal_loader ./secret_prov_pf_client` following example README.

## Expected results
Both parent and child program can read protected file.

## Actual results
Parent program can  read protected file. Child program cannot read protected file with debug log:
```
load_protected_file: files/input.txt, fd 22: opening new PF 0x80baef17b
pf_open(22, files/input.txt) failed: wrap key was not provided
pf_file_attrquery: load_protected_file(files/input.txt, 22) failed
[P18305:T2:secret_prov_pf_client] ---- shim_openat(AT_FDCWD,"files/input.txt",O_RDONLY,0000) = -2
```
## Additional information
I can see that g_master_key is send from parent to child through SSL session.
https://github.com/oscarlab/graphene/blob/5cf182366a2d3e162d70fd9f68cf8b85a3ab050e/Pal/src/host/Linux-SGX/db_process.c#L282-L283
Can use same logic to send g_pf_wrap_key.

**Comment by mkow** [comment]
Seems we overlooked this, the key should of course be inherited. Thanks for reporting!

**Comment by dimakuv** [comment]
@llly Thanks for debugging and reporting this! Indeed, we didn't test this feature with fork/execve.

I will find time and fix this next week.

**Comment by dimakuv** [comment]
@llly Could you check if https://github.com/oscarlab/graphene/pull/1765 fixes your application? It works for me on a DCAP-based system.

**Comment by llly** [comment]
#1765 fixes this issue. Thanks for the quick fix.
