### ISSUE TITLE
[LibOS]Apache flink using JDK7 not work due to socket flag checking

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1764]
## Description of the problem
When enabling https://github.com/apache/flink , Java exception `java.net.SocketException: Operation not supported (Read failed) ` is returned because Graphene socket syscall `shim_do_recvfrom` rejects socket flags `(MSG_DONTWAIT | MSG_PEEK)` .
## Steps to reproduce
Run flink using Graphene-SGX.
flink Java code
[int response = is.read();](https://github.com/apache/flink/blob/c5915cf87f96e1c7ebd84ad00f7eabade7e7fe37/flink-runtime/src/main/java/org/apache/flink/runtime/blob/BlobOutputStream.java#L151)
calls JDK code
[n = socketRead0(fd, b, off, length, timeout);](https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/net/SocketInputStream.java#L150)
which is a native function `java.base/java.net.SocketInputStream.socketRead0(Native Method) `
Finally, 
` ssize_t recvfrom(int sockfd, void *buf, size_t len, int flags,
                        struct sockaddr *src_addr, socklen_t *addrlen);`
 with flags `(MSG_DONTWAIT | MSG_PEEK)` is called.

## Expected results
recvmsg() with flags (MSG_DONTWAIT | MSG_PEEK) succeeds.
The above Java code succeeds.
## Actual results
recvfrom() with flags (MSG_DONTWAIT | MSG_PEEK) fails with debug log
```
[   105] recvmsg()/recvmmsg()/recvfrom(): unknown flag (only MSG_PEEK is supported).
[   105] ---- shim_recvfrom(204,0xc3d407de0,1,64,0x0,0x0) = -95 
```
The log comes from checking 
https://github.com/oscarlab/graphene/blob/2093d64ce22c430d599da1dd9ba0ae5802be56d4/LibOS/shim/src/sys/shim_socket.c#L1216-L1220

Java exception `java.net.SocketException: Operation not supported (Read failed) ` is caught.
## Additional information
After I comment these lines to bypass the checking, flink can work. Currently I use this change as workaround. 
Need to evaluate  whether updating flag bit combine checking is enough or adding logic to deal with `MSG_DONTWAIT` is required.

**Comment by dimakuv** [comment]
@llly Can you check if https://github.com/oscarlab/graphene/pull/1766 helps?

**Comment by llly** [comment]
Looks good for me. Thanks a lot.
