### ISSUE TITLE
[Pal/Linux-SGX]sendfile() cannot work with protected file as in_fd

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1769]
## Description of the problem
There are several kinds of syscalls to access file, read, mmap, sendfile. I tried sendfile() and found it doesn't work with protected file.
## Steps to reproduce
This commit https://github.com/llly/graphene/commit/a45b3740b80852e7093a1209761a54445c725573 uses ra-tls-secret-prov example to call ` ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);`
`out_fd` is regular file and `in_fd` is protected file.
## Expected results
return plain text size, `out_fd` contains plain text.
## Actual results
program fails because of `assert` at 
https://github.com/oscarlab/graphene/blob/707b62e3cfcec2e77b1d91951e1a3aa338460dc8/Pal/src/host/Linux-SGX/db_files.c#L345-L346
Debug log:
```
load_protected_file: files/input.txt, fd 27: opening new PF 0x80baddb62
ipf_open: handle: 27, path: 'files/input.txt', real size: 4096, mode: 0x1
ipf_init_existing_file: data size 10
ipf_open: OK (data size 10)
[P8821:T1:secret_prov_pf_client] ---- shim_openat(AT_FDCWD,"files/input.txt",O_RDONLY,0000) = 3
[P8821:T1:secret_prov_pf_client] ---- shim_openat(AT_FDCWD,"files/out.txt",O_RDWR|O_CREAT,0000) = 4
pf_file_map(PF fd 27): pf 0x80baddb62, addr 0x0, prot 1, offset 0, size 4096
assert failed db_files.c:346 *addr
```
 ## Additional information
I also captured backtrack of ` ssize_t copy_file_range(int fd_in, loff_t *off_in,                               int fd_out, loff_t *off_out, size_t len, unsigned int flags);`. It calls sendfile() and triggers this assert(). Frame 3 shows `addr=0x0`.
```
#0  pf_file_map (pf=0x80baee16e <g_mem_pool+92398>, handle=0x80bb1f27e <g_mem_pool+293374>, addr=0x808de8728, prot=1, offset=0, size=4096) at db_files.c:321
#1  0x000000080b8848f8 in file_map (handle=0x80bb1f27e <g_mem_pool+293374>, addr=0x808de8728, prot=1, offset=0, size=4096) at db_files.c:393
#2  0x000000080b87ff5a in _DkStreamMap (handle=0x80bb1f27e <g_mem_pool+293374>, paddr=0x808de8780, prot=1, offset=0, size=4096) at db_streams.c:514
#3  0x000000080b880071 in DkStreamMap (handle=0x80bb1f27e <g_mem_pool+293374>, addr=0x0, prot=1, offset=0, size=4096) at db_streams.c:546
#4  0x000000080b2baa9d in chroot_mmap (hdl=0x80aa209c8, addr=0x808de8840, size=4096, prot=1, flags=0, offset=0) at fs/chroot/fs.c:717
#5  0x000000080b2e43f3 in handle_copy (hdli=0x80aa209c8, offseti=0x0, hdlo=0x807a06da8, offseto=0x0, count=10) at sys/shim_fs.c:429
#6  0x000000080b2e50d0 in shim_do_sendfile (ofd=1, ifd=3, offset=0x0, count=16777216) at sys/shim_fs.c:676
#7  0x000000080b279d26 in __shim_sendfile (__arg1=1, __arg2=3, __arg3=0, __arg4=16777216) at shim_syscalls.c:236
#8  0x000000080b299ed0 in syscalldb ()
#9  0x0000000807d90535 in copy_file_range (infd=196010350, pinoff=0x80bb1f27e <g_mem_pool+293374>, outfd=148801320, poutoff=0x1, length=0, flags=4096)
    at ../sysdeps/unix/sysv/linux/copy_file_range.c:29
```

**Comment by dimakuv** [comment]
@llly Could you check if solves your issue: https://github.com/oscarlab/graphene/pull/1774.

**Comment by llly** [comment]
This PR fixes my issue. Thanks.
