### ISSUE TITLE
Regression test hangs on a QEMU-KVM client with small EPC

### ISSUE THREAD

**Issue by jinghe-INTC** [oscarlab/graphene#1777]
## Description of the problem

On a SGX capable QEMU-KVM client machine running Ubuntu 18.04 with DCAP driver, if the EPC size is as small as 16MB, it is understandable that the regression case "test_pal.py::TC_01_Bootstrap::test_120_8gb_enclave" would be the only failed one.
However, if repeat running the regression test set under Pal/regression, the test will hang at the case "test_pal.py::TC_20_SingleProcess::test_410_socket".  Even after exiting the test, the CPU resource is held by a few kworker processes. Checked with "ps ef", there is a process of [pal-Linux-SGX] in D state.  It cannot run any Graphene-SGX test after that. Only rebooting can eliminate the problem.

## Steps to reproduce

- Graphene commit b66fbd1c857e55e28ac6389cc34ecf7d6e52a217 (tag: v1.1)

- QEMU-KVM client machine, 16MB EPC

- Ubuntu 18.04 with SGX 2.11, DCAP 1.8, DCAP driver 1.36

- Repeat running Pal/regression test cases

## Expected results
Only the failure of test_pal.py::TC_01_Bootstrap::test_120_8gb_enclave is reasonable.

## Actual results
 test_pal.py::TC_01_Bootstrap::test_120_8gb_enclave always fail, but after a few times of repeating, the other case test_pal.py::TC_20_SingleProcess::test_200_event also fails, and the process hangs at test_pal.py::TC_20_SingleProcess::test_410_socket . 
And the  [pal-Linux-SGX] will be in D state, and most the CPU resources cannot be released.

**Comment by jinghe-INTC** [comment]
On a physical machine, the EPC size can be set to as small as 32MB, while is_sgx_available reports 22MB. If repeat the same regression test cases there will be no case failure or hanging.

**Comment by dimakuv** [comment]
I don't see anything special in the `socket` and `event` PAL regression tests. These tests don't spawn child processes (and thus child enclaves) and one of them doesn't even create child threads (in the same enclave). So there is very little that can go wrong. These are very weird failures.

Is there any other information that could help identifying the root cause?

Could it be the bug in the QEMU-KVM SGX plugin? I don't think any of us Graphene maintainers has QEMU-KVM environment (and expertise on how to debug it).

**Comment by mkow** [comment]
btw:

> if the EPC size is as small as 16MB, it is understandable that the regression case "test_pal.py::TC_01_Bootstrap::test_120_8gb_enclave" would be the only failed one

That's actually not true - EPC is only a cache (as per "C" in it's name :) ). This test works on standard EPC size (128MB, which is much smaller than 8GB) and should also work on 32MB EPC.

**Comment by jinghe-INTC** [comment]
> btw:
> 
> > if the EPC size is as small as 16MB, it is understandable that the regression case "test_pal.py::TC_01_Bootstrap::test_120_8gb_enclave" would be the only failed one
> 
> That's actually not true - EPC is only a cache (as per "C" in it's name :) ). This test works on standard EPC size (128MB, which is much smaller than 8GB) and should also work on 32MB EPC.

That's true. The test was OK on a physical machine with 32MB EPC(as is-sgx-available measured 22MB).

**Comment by mkow** [comment]
> The test was OK on a physical machine with 32MB EPC(as is-sgx-available measured 22MB).

But it still breaks under QEMU-KVM? Could you run this single binary compiled with `DEBUG=1` added to Make invocation and "loader.debug" changed to "inline" in `Bootstrap6.manifest.template` and paste stdout + stderr from it?

**Comment by jinghe-INTC** [comment]
Here's the output from Bootstrap6 in debug mode:
$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
Manifest file: file:Bootstrap6.manifest.sgx
Inferred executable file: file:Bootstrap6
Token file: file:Bootstrap6.token
Read dummy DCAP token
enclave created:
    base:           0x0000000000000000
    size:           0x0000000200000000
    misc_select:    0x00000000
    attr.flags:     0x0000000000000007
    attr.xfrm:      0x00000000000000e7
    ssa_frame_size: 1
    isv_prod_id:    0x00000000
    isv_svn:        0x00000000
adding page  to enclave: 0x1fffff000 [REG:R--] (manifest) measured
adding pages to enclave: 0x1ffffd000-0x1fffff000 [REG:RW-] (ssa) measured
adding page  to enclave: 0x1ffffc000 [TCS:---] (tcs) measured
adding page  to enclave: 0x1ffffb000 [REG:RW-] (tls) measured
adding pages to enclave: 0x1fffbb000-0x1ffffb000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1fffab000-0x1fffbb000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1fb986000-0x1fb9d4000 [REG:R-X] (code) measured
adding pages to enclave: 0x1fbbd3000-0x1fbbd6000 [REG:RW-] (data) measured
adding pages to enclave: 0x1fbbd6000-0x1fffab000 [REG:RW-] (bss) measured
adding page  to enclave: 0x400000 [REG:RWX] (code) measured
adding pages to enclave: 0x600000-0x602000 [REG:RW-] (data) measured
adding pages to enclave: 0x602000-0x1fb986000 [REG:RWX] (free)
adding pages to enclave: 0x10000-0x400000 [REG:RWX] (free)
Enclave EADD returned -12
Adding pages (free) to enclave failed: 12

and the VM config: 
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x1000000

**Comment by jinghe-INTC** [comment]
I tried Graphene on an Azure VM running Ubuntu 18.04 with small EPC,. Most of the regression cases passed except the 8gb case.  
$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
Killed

and its config:
Max enclave size (64-bit): 0x1000000000
EPC size: 0x2a00000

**Comment by mkow** [comment]
Oh, I just noticed this: "Graphene commit b66fbd1 (tag: v1.1)". Please use current master, this version is more than 100 commits old...

**Comment by jinghe-INTC** [comment]
I have tried the latest commit f94c72b, and when doing the same test at the first time,  there was a different error message:
$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
Manifest file: file:Bootstrap6.manifest.sgx
Inferred executable file: file:Bootstrap6
Token file: file:Bootstrap6.token
Read dummy DCAP token
enclave created:
    base:           0x0000000000000000
    size:           0x0000000200000000
    misc_select:    0x00000000
    attr.flags:     0x0000000000000007
    attr.xfrm:      0x00000000000000e7
    ssa_frame_size: 1
    isv_prod_id:    0x00000000
    isv_svn:        0x00000000
adding page  to enclave: 0x1fffff000 [REG:R--] (manifest) measured
adding pages to enclave: 0x1ffff7000-0x1fffff000 [REG:RW-] (ssa) measured
adding pages to enclave: 0x1ffff3000-0x1ffff7000 [TCS:---] (tcs) measured
adding pages to enclave: 0x1fffef000-0x1ffff3000 [REG:RW-] (tls) measured
adding pages to enclave: 0x1fffaf000-0x1fffef000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1fff6f000-0x1fffaf000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1fff2f000-0x1fff6f000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1ffeef000-0x1fff2f000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1ffedf000-0x1ffeef000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffecf000-0x1ffedf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffebf000-0x1ffecf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffeaf000-0x1ffebf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1fb878000-0x1fb8d8000 [REG:R-X] (code) measured
adding pages to enclave: 0x1fbad7000-0x1fbada000 [REG:RW-] (data) measured
adding pages to enclave: 0x1fbada000-0x1ffeaf000 [REG:RW-] (bss) measured
adding page  to enclave: 0x400000 [REG:RWX] (code) measured
adding pages to enclave: 0x600000-0x602000 [REG:RW-] (data) measured
adding pages to enclave: 0x602000-0x1fb878000 [REG:RWX] (free)
adding pages to enclave: 0x10000-0x400000 [REG:RWX] (free)
enclave initializing:
    enclave id:   0x00000001fffff000
    mr_enclave:   31ef75a0eb1aef7b4f40e1c86dfe0323a134aeb4c9996bbd1b1faa4f73e54afa
Memory Mapping Exception in Untrusted Code (RIP = 55b532f1b319)

But if repeat it, there would be the same error as before:

$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
Manifest file: file:Bootstrap6.manifest.sgx
Inferred executable file: file:Bootstrap6
Token file: file:Bootstrap6.token
Read dummy DCAP token
enclave created:
    base:           0x0000000000000000
    size:           0x0000000200000000
    misc_select:    0x00000000
    attr.flags:     0x0000000000000007
    attr.xfrm:      0x00000000000000e7
    ssa_frame_size: 1
    isv_prod_id:    0x00000000
    isv_svn:        0x00000000
adding page  to enclave: 0x1fffff000 [REG:R--] (manifest) measured
adding pages to enclave: 0x1ffff7000-0x1fffff000 [REG:RW-] (ssa) measured
adding pages to enclave: 0x1ffff3000-0x1ffff7000 [TCS:---] (tcs) measured
adding pages to enclave: 0x1fffef000-0x1ffff3000 [REG:RW-] (tls) measured
adding pages to enclave: 0x1fffaf000-0x1fffef000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1fff6f000-0x1fffaf000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1fff2f000-0x1fff6f000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1ffeef000-0x1fff2f000 [REG:RW-] (stack) measured
adding pages to enclave: 0x1ffedf000-0x1ffeef000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffecf000-0x1ffedf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffebf000-0x1ffecf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1ffeaf000-0x1ffebf000 [REG:RW-] (sig_stack) measured
adding pages to enclave: 0x1fb878000-0x1fb8d8000 [REG:R-X] (code) measured
adding pages to enclave: 0x1fbad7000-0x1fbada000 [REG:RW-] (data) measured
adding pages to enclave: 0x1fbada000-0x1ffeaf000 [REG:RW-] (bss) measured
adding page  to enclave: 0x400000 [REG:RWX] (code) measured
adding pages to enclave: 0x600000-0x602000 [REG:RW-] (data) measured
adding pages to enclave: 0x602000-0x1fb878000 [REG:RWX] (free)
Enclave EADD returned -12
Adding pages (free) to enclave failed: 12

**Comment by mkow** [comment]
Please paste logs in raw blocks (\`\`\`). I had to edit your post to make it readable.

Could you run our [`is_sgx_available`](https://graphene.readthedocs.io/en/latest/manpages/is_sgx_available.html) tool under your QEMU setup?

**Comment by jinghe-INTC** [comment]
```
~/graphene/Pal/regression$ ../../Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x1000000
SGX driver loaded: true
SGX PSW/libsgx installed: true
AESMD running: true
```

**Comment by mkow** [comment]
Interesting, I'd say it may be a problem with QEMU's SGX emulation, but hard to say without more debugging. I'm currently quite busy, so I'm afraid you'll need to try to debug this yourself.
I'd start with looking at the code which is emitting this error and seeing which call to the driver caused it, then probably enable verbose output from the driver you're using.

**Comment by dimakuv** [comment]
+1 to @mkow . I cannot imagine anything wrong with Graphene in these test cases. It looks more like the QEMU deployment problem.

**Comment by jinghe-INTC** [comment]
But it doesn't work properly on an Azure VM either. It was killed shortly after starting.

```
~/graphene/Pal/regression$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
Killed
~/graphene/Pal/regression$ ../../Pal/src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): false
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): false
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x1000000000
EPC size: 0x2a00000
SGX driver loaded: true
SGX PSW/libsgx installed: true
AESMD running: true
```
The DCAP driver on KVM and Azure VM are both v1.36.

**Comment by dimakuv** [comment]
@jinghe-INTC I am confused. What you're showing is the log of **8GB-enclave Bootstrap6**. It is supposed to be killed since the VM (Azure or your local one, doesn't matter) doesn't have enough EPC/RAM alloted for such a big SGX enclave. This is expected.

What I'm interested in: when and how do `socket` and `event` tests fail?

**Comment by jinghe-INTC** [comment]
On a physical machine with small EPC, the case can still pass. 
```
$ SGX=1 ../../Runtime/pal_loader Bootstrap6.manifest.sgx
sgx.protected_fileskey not found in manifest, protected files will not be available
Binary 1 Preloaded
Binary 2 Preloaded
User Program Started
Loaded Executable: file:Bootstrap
Loaded Manifest: file:Bootstrap6.manifest.sgx
# of Arguments: 1
argv[0] = Bootstrap
Process ID: 0005b02c1d612b98
Host ID: 0000000000000000
Parent Process: 0x0
Written to Debug Stream
Allocation Alignment: 4096
User Address Range: 0x10000 - 0x1fb28d000
User Address Range OK
Executable Range: 0x400000 - 0x405000
Executable Range OK
CPU num: 2
CPU vendor: GenuineIntel
CPU brand: Intel(R) Celeron(R) J4005 CPU @ 2.00GHz
CPU family: 6
CPU model: 122
CPU stepping: 1
CPU flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe
$ ../src/host/Linux-SGX/tools/is-sgx-available/is_sgx_available
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): false
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x1000000000
EPC size: 0x1600000
SGX driver loaded: true
SGX PSW/libsgx installed: true
AESMD running: true
```

So it will have more strict requirement than that on VM?

**Comment by jinghe-INTC** [comment]
And I've never seen failure of case `socket `and `event` on any of the platforms.

**Comment by dimakuv** [comment]
How much RAM do you have on your physical machine and on your VM instances?

Recall that in Linux, you may have a swap file (Linux moves RAM contents in this swap file when no more space left in RAM). Frequently in VM instances, this swap file is either *absent* or *very small*. So if you have say 1GB of RAM allocated for your VM, and no swap file, then any application that requires 8GB of memory will be killed. I believe this is what happens in your `Bootstrap6` case. And you don't see this failure on your physical machine because it has much more RAM + swap file.

**Comment by mkow** [comment]
> doesn't have enough EPC/RAM alloted for such a big SGX enclave

@dimakuv EPC has nothing to do with this, it's just a cache.

But not enough RAM in the VM sounds like a probable explanation for this failure.

**Comment by mkow** [comment]
No response from the original reporter for quite some time, closing (and we believe this is just a problem with not enough RAM in the VM). Feel free to reopen if that's not the case.
