### ISSUE TITLE
[LibOS, PAL] Add support for pseudo sysfs to get platform topology information 

### ISSUE THREAD

**Issue by vijaydhanraj** [oscarlab/graphene#1783]
## Description of the problem
Many libraries such as tbb, hwloc use sysfs-devices-system to get the underlying platform topology. But currently this isn't emulated in LibOS and PAL. So propose to support the following as pseudo files as a start. Based on feedback I can extend/trim these as needed.

/sys/devices/system/node
/sys/devices/system/cpu/cpu#/topology/core_siblings
/sys/devices/system/cpu/cpu#/topology/thread_siblings
/sys/devices/system/cpu/offline
/sys/devices/system/cpu/online
/sys/devices/system/cpu/possible

## Expected results
Avoid crashes with latest openVINO 2020.4 with tbb/hwloc libraries and also address the performance gap due to missing topology info.

## Actual results
With openVINO 2020.4 benchmark observed the following issues due to these missing topology info.
1. openVINO 2020.4 uses topology info to identify thread siblings and tries not to schedule on the sibling cores. Since the feature is missing, observe ~12% degrade in benchmark latency. 
2. openVINO 2020.4 uses tbb libraries which in turn use hwloc to get numa information. hwloc uses sysfs and since this is not supported, openVINO ends up getting the number of numa nodes as zero resulting in a divide-by-zero exception.

**Comment by dimakuv** [comment]
I suggest to have an initialization-only emulation of the CPU topology. In other words, we shouldn't introduce a new PAL (`DkNewFunc()`) and OCALL functions, but instead propagate the necessary CPU topology during enclave initialization in the `pal_sec` object. See https://github.com/oscarlab/graphene/blob/49746f8716167f1e98a5b16cb734ab62ff4ddb04/Pal/src/host/Linux-SGX/db_main.c#L184-L186.

The corresponding untrusted code is around here: https://github.com/oscarlab/graphene/blob/49746f8716167f1e98a5b16cb734ab62ff4ddb04/Pal/src/host/Linux-SGX/sgx_main.c#L794.

We need to do something similar to what we already do with `pal_sec->num_cpus`.

**Comment by mkow** [comment]
(and if it turns out we need dynamic info for some use-case then we'll expand this implementation)

**Comment by vijaydhanraj** [comment]
Thanks @dimakuv and @mkow for the feedback.
