### ISSUE TITLE
[LibOS] Feature Request: Add in-memory tmpfs

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1787]
When native app needs to use temporary files, typical solution is mounting /tmp of host OS #1139. There are several mountable_fs and builtin_fs file system type, `chroot` is used. 

Now Protected filesystem feature is added. When temporary files contain sensitive data, it's hard to add them to manifest as sgx.protected_files because the file name is usually contain generated random string.

In-memory tmpfs can solve this problem and  avoid encryption/decryption overhead. In-memory tmpfs is located inside SGX enclave. So it cannot access from host OS and is cleaned after enclave destroyed. Don't need to encryption it as Protected filesystem.

Is it feasible? Or we already had another better solution?

**Comment by dimakuv** [comment]
I definitely like this idea of a new type of FS (`tmpfs`).

I think it will be sufficiently simple to add this to our LibOS. I'm pretty sure we can re-use the `str` file system.

The only question is: who will implement this? :)

**Comment by dimakuv** [comment]
@llly Do I understand you correctly, that you want:
```
fs.mount.tmp.type = tmpfs
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp

# None of the below is needed because tmpfs is always inside the enclave and not backed by anything!
# sgx.allowed_files.tmp = file:/tmp
# sgx.trusted_files.tmp = file:/tmp
# sgx.protected_files.tmp = file:/tmp
# sgx.allow_file_creation = 1
```

**Comment by yamahata** [comment]
+1. nice idea and it's easy to implement.

**Comment by llly** [comment]
@dimakuv Yes, that's what I want. And `fs.mount.tmp.uri = file:/tmp` is not needed, either.

I can implement it and create PR of no objection.
A lot of operations in `shim_fs_ops`  and `shim_d_ops` of str fs are lacked. Need to add necessary operations when reusing str fs. Right?

**Comment by mkow** [comment]
>  A lot of operations in `shim_fs_ops` and `shim_d_ops` of str fs are lacked. Need to add necessary operations when reusing str fs. Right?

I think that's the case. Basically, don't trust our codebase, a lot of things are missing or are incorrectly implemented :/

**Comment by dimakuv** [comment]
@llly You mentioned:
> And fs.mount.tmp.uri = file:/tmp is not needed, either.

But why not? On normal Linux (at least on Ubuntu), the `/tmp` directory is not tmpfs but normal storage. I would like to keep this logic. This may be especially important if two applications -- one in Graphene enclave, another normal process -- want to share some file under `/tmp`.

So I'd vote for explicit syntax to declare mount points of type `tmpfs`. Then the user can choose which logic (persistence or in-enclave-memory) he wants, and modify the manifest accordingly.

**Comment by dimakuv** [comment]
> I can implement it and create PR of no objection.

This would be great!

> A lot of operations in shim_fs_ops and shim_d_ops of str fs are lacked. Need to add necessary operations when reusing str fs. Right?

Yes, that's correct. You should check how the `chroot` mount point is implemented, under `fs/chroot/fs.c`, and implement the same functions-callbacks but based on `strfs`.

**Comment by mkow** [comment]
> > And fs.mount.tmp.uri = file:/tmp is not needed, either.
>
> But why not? On normal Linux (at least on Ubuntu), the /tmp directory is not tmpfs but normal storage. I would like to keep this logic. This may be especially important if two applications -- one in Graphene enclave, another normal process -- want to share some file under /tmp.

@dimakuv: Hmm, I don't get your response. If `type` is `tmpfs` then what would be the semantics of `uri`? If you want persistent `/tmp` then you just do `chroot` mount, not `tmpfs`. I think @llly is right that this parameter doesn't make any sense with `tmpfs`.

**Comment by dimakuv** [comment]
Ah, sorry, I misunderstood the comment.

What @llly means is that only two lines (instead of typical three) are needed for tmpfs mount points:
```
fs.mount.tmp.type = tmpfs
fs.mount.tmp.path = /tmp
# fs.mount.tmp.uri = file:/tmp  <-- this is useless
```

I initially understood @llly's comment as "Let's hard-code /tmp to be of type tmpfs".

**Comment by llly** [comment]
I'll start from only tmpfs instead of mixing chroot and tmpfs. We can enhance design later if needed .

**Comment by mkow** [comment]
If I follow the discussion correctly there, are no plans for mixing of chrootfs and tmpfs, this was just a slight confusion in the discussion ;)
There should be a separate "tmpfs" type which you can mount at specific path inside Graphene and which isn't backed up by the host FS (and doesn't need "uri" parameter). If someone wants to have host-backed storage then they can just use (already implemented) chrootfs, no new features are required for this.

**Comment by dimakuv** [comment]
+1 to @mkow said. Sorry if I confused everyone.

**Comment by vijaydhanraj** [comment]
@llly can you please give more context to this issue? In a sense what was the workload, how to reproduce the issue and failure logs etc.
In the comments, I see that you have mentioned submitting a PR. Are you still working on this or do you want us to take up this task?

**Comment by llly** [comment]
@vijaydhanraj  Spark worker will store some intermediate files in /tmp directory such as `/tmp/spark-c56fc39d-d0c2-4009-9391-be2560567386/`
and remove them before exit. intermediate files may contain privacy information and need to be protected too. Currently, Protected Filesystem can be used to protect them. in-memory tmpfs can achieve better performance. 
There is a limitation that tmpfs need to store all data inside enclave. EPC is scarce for heavy Spark worker #2014 . in-memory tmpfs can be used in Spark worker after EDMM is implemented. 

I'm still working on this and will create a PR within few weeks.

**Comment by vijaydhanraj** [comment]
@llly thanks for the update!
