### ISSUE TITLE
[Pal] Out-of-memory reported when protected file size bigger than 32M

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1792]
## Description of the problem
Protected files calloc `file_mht_node` and `file_data_node` when reading protected files.https://github.com/oscarlab/graphene/blob/c9fc06b9f5050974a980a90fe7fe7b2428cc4e22/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1148
https://github.com/oscarlab/graphene/blob/c9fc06b9f5050974a980a90fe7fe7b2428cc4e22/Pal/src/host/Linux-SGX/protected-files/protected_files.c#L1021 
 Some of them are not freed until file closed. If  protected file is big, a large amount of memory is allocated and hold.

In #1768 , When pre-allocated memory pool runs out, Pal reports Out-of-memory instead of allocate more pages. Before this commit, big protected file can work by increasing enclave size. After this commit,  protected file with size bigger than 32M always fails with error `*** Out-of-memory in PAL (try increasing POOL_SIZE and rebuilding Graphene) ***`. It's not a good solution to edit source code rather than edit manifest.
## Steps to reproduce
Write sample app like
```
#define MAXBUF  65536
char buf[MAXBUF];
int n;
FILE *fp = fopen(fname, "r");
while ( (n = fread(buf,1,MAXBUF,fp)) > 0 );
fclose(fp);
```
fname is protected file with size of 31M and 32M and 4GB. manifest contains `sgx.enclave_size = 16G`.
## Expected results
protected file with size of 31M and 32M and 4GB can fopen, fread an fclose.
## Actual results
protected file with size of 31M can fopen, fread an fclose.
protected file with size of 32M and 4GB can fopen, Fail with `*** Out-of-memory in PAL (try increasing POOL_SIZE and rebuilding Graphene) ***` when fread.

**Comment by dimakuv** [comment]
Yes, this is a known and very annoying problem. I will fix it now. I plan to introduce a new manifest option (instead of a build-time hack).

> In #1768 , When pre-allocated memory pool runs out, Pal reports Out-of-memory instead of allocate more pages. Before this commit, big protected file can work by increasing enclave size.

That's actually not entirely correct. Before that commit, the Graphene internal memory and application memory could grow into each other, and all hell broke loose. The application would start failing with random errors. With #1768 it became at least deterministic. But I agree that it was only a temporary solution to not shoot yourself in the foot.

**Comment by mkow** [comment]
Eh, maybe it's time to finally solve this PAL dynamic allocation issue? This isn't the first time we have troubles because of it and we'll eventually need a fix if we want to reasonably scale to bigger workloads.

**Comment by dimakuv** [comment]
I am currently doing it (but again in a hacky way) through the new manifest option `sgx.internal_size = <integer>`.

I was thinking about this issue for a while but gave up -- it requires a lot of thought/work to consolidate the logic of LibOS and PAL. I'll submit my hacky but working solution soon.

**Comment by llly** [comment]
Yes. This fix solves this issue.
