### ISSUE TITLE
[Examples] Pytorch accessing file:/etc/fstab is denied

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1804]
## Description of the problem
On my SGX2 system:
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
DCAP SGX driver = yes
PYTHONVERSION = 3.6.9

it reports the following error when run pytorch in SGX mode
```Accessing file:/etc/fstab is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).```

## Steps to reproduce
According to the readme in folder Examples/pytorch, running the following command to reproduce.
```SGX=1 ./pal_loader ./pytorch.manifest ./pytorchexample.py```

## Expected results
the following command can produce result.txt successfully
```SGX=1 ./pal_loader ./pytorch.manifest ./pytorchexample.py```

## Actual results
the following command failed
```SGX=1 ./pal_loader ./pytorch.manifest ./pytorchexample.py```

**Comment by bigdata-memory** [comment]
The screenshot is attached here.
![image](https://user-images.githubusercontent.com/10856796/92654275-79c91100-f2a4-11ea-8a86-2f76fbf5c68e.png)

**Comment by mkow** [comment]
Please paste text logs instead of screenshots.
