### ISSUE TITLE
Race condition in slabmgr

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#181]
There's a race condition here:
https://github.com/oscarlab/graphene/blob/d548ee2048a4afcf0439691ea36a5e42c46fd772/Pal/lib/slabmgr.h#L352-L357

If there are enough concurrent allocations, the unlocked region can be raced: right after that call another thread can do enough allocations to make `mgr->addr[level] == mgr->addr_top[level]` condition true again, which after the allocation in line 364:
https://github.com/oscarlab/graphene/blob/d548ee2048a4afcf0439691ea36a5e42c46fd772/Pal/lib/slabmgr.h#L364
will break this assert:
https://github.com/oscarlab/graphene/blob/d548ee2048a4afcf0439691ea36a5e42c46fd772/Pal/lib/slabmgr.h#L366

**Comment by donporter** [comment]
Looks like we all agree this issue was fixed by #183.  Closing.
