### ISSUE TITLE
could not run code in graphene-sgx

### ISSUE THREAD

**Issue by dirknono** [oscarlab/graphene#1819]
I use graphene-sgx on my laptop. After reboot, I insmod gsgx.ko as uaual but today I cannot run my program in graphene-sgx.
I really don't know why.
I re-install sgx driver, sdk, psw and re-compile graphene, but I still get the following result when I run a code in graphene-sgx:
```
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
The {RD,WR}{FS,GS}BASE instruction is not currently enabled. Please reload Graphene SGX kernel module.
Segmentation Fault in Untrusted Code (RIP = 56229cdba359)
^C*** Unexpected exception occurred inside PAL at RIP = +0x0002a93d! ***
(untrusted PAL sent PAL event 0x2)
rax: 0xffffffff rcx: 0x00000000 rdx: 0xffffffff rbx: 0x00000000
rsp: 0x83f76d9c8 rbp: 0x83f76d9e0 rsi: 0x83f76daf0 rdi: 0x83f76db80
r8 : 0x00000000 r9 : 0x00000000 r10: 0x00000000 r11: 0x83af71848
r12: 0x00000000 r13: 0x00000000 r14: 0x00000000 r15: 0x00000000
rflags: 0x00010202 rip: 0x83af7193d
DkProcessExit: Returning exit code 1

````

Could you please have a look? Thank you!

**Comment by dirknono** [comment]
My graphene version is the lastest master branch and sgx driver/sdk/psw is the stable version 2.7.1

**Comment by dirknono** [comment]
well, sgx driver is tag 2.6

**Comment by mkow** [comment]
This may be caused by the recent change in the upstream kernel where they prohibited changing CR4.FSGSBASE. Could you try either using kernel v5.9-rc5 or v5.4 with our backported FSGSBASE patches? See https://github.com/oscarlab/graphene-sgx-driver/blob/8ba1f588552531a3c63c81a91d11a2b5e7587b81/README.rst.

**Comment by dirknono** [comment]
> This may be caused by the recent change in the upstream kernel where they prohibited changing CR4.FSGSBASE. Could you try either using kernel v5.9-rc5 or v5.4 with our backported FSGSBASE patches? See https://github.com/oscarlab/graphene-sgx-driver/blob/8ba1f588552531a3c63c81a91d11a2b5e7587b81/README.rst.

Thanks very much. This problem has been solved.
