### ISSUE TITLE
OpenVINO LTS and model zoo

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1823]
## Description of the problem
Glad to see that openvino example has been upgraded to 2020.4. But, this version is not a LTS version, which means it will be replaced by future release 4-5 months later.

1. Change to [2020.3LTS](https://software.intel.com/content/www/us/en/develop/articles/openvino-2020-3-lts-relnotes.html) maybe a better idea. 

2. model zoo is released according to openvino version. Need to change to the same version with openvino.

**Comment by monavij** [comment]
Qiyuan - can you contribute updated openvino example with 2020.3LTS?

**Comment by qiyuangong** [comment]
OK. That's a minor change. I will submit a PR for that. :)

**Comment by dimakuv** [comment]
@qiyuangong We just merged https://github.com/oscarlab/graphene/pull/1975. Do we still want to keep this issue?

**Comment by qiyuangong** [comment]
Issue closed. :)
