### ISSUE TITLE
Example/openvino build error(GCC 9): redundant move in return statement

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1825]
OS: Ubuntu 20.04
gcc: 9.3.0

Is there any way to solve this problem without replacing gcc 9?
Any advice would be appreciated.

`make SGX=1`
>[ 34%] [cpplint] speech_sample_cpplint
make[3]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
[ 34%] Built target speech_sample_cpplint
make[3]: Entering directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make[3]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
[ 34%] Built target cpplint_all
make[3]: Entering directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make[3]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make[3]: Entering directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
[ 34%] Building CXX object thirdparty/ade/sources/ade/CMakeFiles/ade.dir/source/execution_engine.cpp.o
/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp: In member function ‘std::unique_ptr<ade::Executable> ade::ExecutionEngine::createExecutable(const ade::Graph&)’:
/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp:141:21: **error: redundant move in return statement [-Werror=redundant-move]
  141 |     return std::move(ret);
      |            ~~~~~~~~~^~~~~**
/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/thirdparty/ade/sources/ade/source/execution_engine.cpp:141:21: note: remove ‘std::move’ call
cc1plus: all warnings being treated as errors
make[3]: *** [thirdparty/ade/sources/ade/CMakeFiles/ade.dir/build.make:115: thirdparty/ade/sources/ade/CMakeFiles/ade.dir/source/execution_engine.cpp.o] Error 1
make[3]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make[2]: *** [CMakeFiles/Makefile2:2667: thirdparty/ade/sources/ade/CMakeFiles/ade.dir/all] Error 2
make[2]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make[1]: *** [Makefile:163: all] Error 2
make[1]: Leaving directory '/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build'
make: *** [Makefile:64: openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd] Error 2

**Comment by vijaydhanraj** [comment]
This doesn't seem to be a graphene issue but have you tried removing the redundant move? This was suggested in https://qiita.com/PINTO/items/9c39466b8473da2a27e1
```
execution_engine.cpp
           ret->addExec(std::move(bexec));
        }
    }

    //return std::move(ret);
    return ret;
}
```

**Comment by justalittlenoob** [comment]
@vijaydhanraj  Thank you very much, I think your advice is right.
