### ISSUE TITLE
Examples/openvino Error: OpenCV is not available

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1834]
Hi, I got some trouble when tring to run openvino with graphene sgx. The detail is as below.  
Any advice would be appreciated.   

**os: ubuntu 20.04**
**graphene: v1.1**

`make SGX=1`
```
../../Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
        -libpal ../../Runtime/libpal-Linux-SGX.so \
        -key ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem \
        -manifest openvino.manifest -output openvino.manifest.sgx
Attributes:
    size:        2147483648    thread_num:  16
    isv_prod_id: 0    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   0300000000000000
    misc_select: 00000000
    date:        2020-09-21
Trusted files:
Traceback (most recent call last):
  File "../../Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 14, in <module>    sys.exit(main())
  File "../../Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 929, in main    return main_sign(args)
  File "../../Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 839, in main_sign
    for key, val in get_trusted_files(manifest, args).items():  File "../../Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 254, in get_trusted_files    targets[key] = (val, resolve_uri(val, check_exist))
  File "../../Pal/src/host/Linux-SGX/signer/pal_sgx_sign.py", line 216, in resolve_uri
    raise **Exception(Exception: Cannot resolve file:./openvino/inference-engine/temp/opencv_4.1.1_ubuntu16/lib/libopencv_imgcodecs.so.4.1 or the file does not exist.**
make: *** [Makefile:80: openvino.manifest.sgx] Error 1
```

`graphene/Examples/openvino/openvino/inference-engine/temp$ ls`
```
download  gna  tbb  vpu
```

There is no folder called `opencv_4.1.1_ubuntu16`.  
Besides, when I tried to find `libopencv_imgcodecs.so.4.1`(`sudo find / -name "libopencv_imgcodecs.so.4.1"`), I got nothing.

**Comment by mkow** [comment]
> graphene: v1.1

Please use current master, not v1.1, it's been more than 100 commits this release. Also, the issue template has a huge banner asking to test on current master before posting an issue ;)

**Comment by mkow** [comment]
Btw. I just noticed that there's a new PR which fixes some stuff in OpenVINO, you can give it a try: https://github.com/oscarlab/graphene/pull/1833.

**Comment by justalittlenoob** [comment]
@mkow   
Thank you for your reply. I took your advice. But there is a new issue (_OpenCV is not available on current platform_) when using master branch. I tried to get some useful information in openvino PRs, but nothing help.  

`libopencv-dev` and `python3-opencv` are installed. Did I miss something?

`make SGX=1`
>--     ENABLE_CPPLINT_REPORT = OFF
--     ENABLE_CLANG_FORMAT = ON
--     ENABLE_TBB_RELEASE_ONLY = OFF
--
-- MODELS_PATH=
CMake Warning at inference-engine/cmake/vpu_dependencies.cmake:120 (message):
  VPU_OCL_COMPILER is not found.  Some tests will skipped
Call Stack (most recent call first):
  inference-engine/cmake/dependencies.cmake:43 (include)
  inference-engine/CMakeLists.txt:18 (include)


CMake Error at inference-engine/cmake/dependencies.cmake:240 (message):
  **OpenCV is not available on current platform**
Call Stack (most recent call first):
  inference-engine/CMakeLists.txt:18 (include)


-- Configuring incomplete, errors occurred!
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeOutput.log".
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:62: openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd] Error 1

**Comment by mkow** [comment]
I don't know OpenVINO well, but this seems like something unrelated to Graphene (maybe modulo our docs which should say what you need to install). I guess you need to go to OpenVINO docs and check the system requirements, they should have an building/installation guide.
