### ISSUE TITLE
[LibOS] Deadlock in fork() when another thread blocked in socket accept()

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1842]
## Description of the problem
`shim_handle` structure contains a mutex lock to protect other members. Lots of functions acquire the lock before read or write shim_handle structure.

Here are two of them.
`static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen);`
https://github.com/oscarlab/graphene/blob/0432c1794a5a2dacc125997a959c8e6b7e2ecc9d/LibOS/shim/src/sys/shim_socket.c#L875-L883
`shim_do_accept()` lock `hdl->lock` first then wait for client to connect. It finally calls accept() OS syscall and blocks until clients connect it. Finally unlock `hdl->lock` and return.

`BEGIN_CP_FUNC(handle)` extend to `int cp_handle(struct shim_cp_store* store, void* obj, size_t size, void** objp);`
https://github.com/oscarlab/graphene/blob/0432c1794a5a2dacc125997a959c8e6b7e2ecc9d/LibOS/shim/src/bookkeep/shim_handle.c#L705
It is hidden behind a series of Macros. This function is used to collect handles into a checkpoint store when creating checkpoint for fork().

When one thread call fork() while another thread blocked in socket accept().
https://github.com/oscarlab/graphene/blob/0432c1794a5a2dacc125997a959c8e6b7e2ecc9d/LibOS/shim/src/sys/shim_fork.c#L25-L29
will finally collect the handle used by blocked  socket accept() in that thread.

Unfortunately `hdl->lock` is already locked. If no client connects it, fork() is deadlocked.

## Actual results
After I move `DkStreamWaitForClient` out of lock range in https://github.com/llly/graphene/commit/eeba0ae4a2ad280c86ed15ca4057c13e6d7d8c1c
The deadlock doesn't exist. But it's not a good fix.
Change mutex lock to read-write lock can solved this issue.

**Comment by dimakuv** [comment]
Interesting deadlock. Yes, it is an obvious bug, thanks for debugging this!

1. Not related to the bug itself, but why do you have a multi-threaded application that runs `fork()` in one thread and does `accept()` in another thread? AFAIK, forking on a multi-threaded application is strongly discouraged. What application is that?

2. I think it's perfectly normal to unlock before `DkStreamWaitForClient()` and lock again immediately afterwards. We may verify that no other thread changed the important fields of the socket (`sock_state == SOCK_LISTENED`), but other than that I see no problems with this approach. (We already got a reference for this socket handle, so it won't be freed for sure.)

@mkow @yamahata @boryspoplawski What do you think about proposal 2? I could quickly implement the patch.

**Comment by yamahata** [comment]
un/lock before/after dkwaitforclient itself seems okay. But we should audit if there are similar lock in libos.

**Comment by mkow** [comment]
This needs to be implemented carefully, we can't read `hdl->pal_handle` without the lock (I think).

**Comment by dimakuv** [comment]
@mkow , yes, agreed. But once set, `hdl->pal_handle` cannot be modified. So we can read it under the lock, check that it is not NULL, and use it later without the lock.

**Comment by boryspoplawski** [comment]
@dimakuv I don't think that's the case, e.g. https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_socket.c#L780

**Comment by llly** [comment]
@dimakuv It's Spark using Java. I'm trying to enable it during these days.

**Comment by yamahata** [comment]
One second  thought, this is design issue.
At the moment hdl->lock is mutex. So it assumes that the thread can blocked with the lock held.
On the other hand, fork logic assumes that other thread won’t hold the lock indefinitely. It means that the logic assumes the lock is spinlock effectively.

If we go to the direction for unlock before block, hdl->lock should be replaced with spinlock.
other choice is to modify fork logic somehow to handle locked mutex.

As short term fix, unlock before block seems okay to me.
