### ISSUE TITLE
Openvino in Graphene error while loading shared libraries

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1843]
I am trying to make openvino work in graphene-sgx according to [this doc](https://github.com/oscarlab/graphene/tree/master/Examples/openvino).  How can I make step 3 and step 4 work? The manifest file is attached [openvino.manifest.template](https://github.com/oscarlab/graphene/files/5281426/openvino.manifest.template.txt). Any advice would be appreciated.

1. build, **success**.
`make SGX=1` 

2. run original OpenVINO/object_detection_sample_ssd, **success**.
` ./openvino/bin/intel64/Release/object_detection_sample_ssd -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU` 
>[197,17] element, prob = 0.00592674    (1861,805)-(1941,863) batch id : 0
[198,17] element, prob = 0.00578203    (1912,775)-(1984,828) batch id : 0
[199,17] element, prob = 0.00573069    (1890,836)-(1976,896) batch id : 0
[ INFO ] Image out_0.bmp created!
[ INFO ] Execution successful
[ INFO ] This sample is an API example, for any performance measurements please use the dedicated benchmark_app tool

3. run OpenVINO/object_detection_sample_ssd in non-SGX Graphene, **faile**. The ` libopencv_imgcodecs.so.4.4` file is in /inference-engine/temp/opencv_4.4.0_ubuntu20/opencv/lib/  
`./pal_loader openvino.manifest -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>WARNING: Using insecure argv source. Don't use this configuration in production!
object_detection_sample_ssd: error while loading shared libraries: libopencv_imgcodecs.so.4.4: cannot open shared object file: No such file or directory

4. run OpenVINO/object_detection_sample_ssd in Graphene-SGX, **fail**.
`SGX=1 ./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:/lib/x86_64-linux-gnu/libstdc++.so.6 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
object_detection_sample_ssd: error while loading shared libraries: libopencv_imgcodecs.so.4.4: cannot open shared object file: No such file or directory

**Comment by dimakuv** [comment]
It seems that you're using Ubuntu 20.04. We didn't test OpenVINO on this version of Ubuntu.

Apparently, some paths changed on this newer Ubuntu.

In particular,  `/usr/x86_64-linux-gnu/libstdc++.so.6` now moved to `/lib/x86_64-linux-gnu/libstdc++.so.6`. Please reflect this change in your manifest-template file (on line 87).

Also, for some reason, your OpenVINO doesn't find the file `libopencv_imgcodecs.so.4.4` even though you correctly modified it in your manifest-template (on line 112). Are you sure you did `make SGX=1 clean` and then rebuilt it again via `make SGX=1` after modifying this manifest-template file? It could be that you didn't clean properly and Graphene still uses old files.

Also, you should try rebuilding with `make DEBUG=1` and `make SGX=1 DEBUG=1` and look at the output log. This will give you more information what failed.

**Comment by justalittlenoob** [comment]
@dimakuv Hi, thank you very much. I think your suggestion is quite right. I can't try it right away, because my machine is crashed. I'll try your method tomorrow.

**Comment by justalittlenoob** [comment]
@dimakuv  Just tried. Still has the issue (libopencv_imgcodecs.so.4.4: cannot open shared object file: No such file or directory).
  
1. run original OpenVINO/object_detection_sample_ssd, success.
2. run OpenVINO/object_detection_sample_ssd in Graphene-SGX or Graphene-NoSGX, fail.
`/graphene/Examples/openvino$ ./pal_loader openvino.manifest -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>WARNING: Using insecure argv source. Don't use this configuration in production!
object_detection_sample_ssd: error while loading shared libraries: libopencv_imgcodecs.so.4.5: cannot open shared object file: No such file or directory

`./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
object_detection_sample_ssd: error while loading shared libraries: libopencv_imgcodecs.so.4.5: cannot open shared object file: No such file or directory

**Comment by dimakuv** [comment]
Could you attach the auto-generated `openvino.manifest` and `openvino.manifest.sgx` files here?

**Comment by justalittlenoob** [comment]
@dimakuv Sure.   
[openvino.manifest](https://github.com/oscarlab/graphene/files/5298073/openvino.manifest.txt) 
[openvino.manifest.sgx](https://github.com/oscarlab/graphene/files/5298076/openvino.manifest.sgx.txt)
[openvino.manifest.template](https://github.com/oscarlab/graphene/files/5298077/openvino.manifest.template.txt)

**Comment by dimakuv** [comment]
Let's try a couple things in your manifest.template file.

1. Please add the line `loader.insecure__use_host_env = 1` (see https://graphene.readthedocs.io/en/latest/manifest-syntax.html#environment-variables).

2. I don't like these lines in the auto-generated manifests:
```
fs.mount.cwd.type = chroot
fs.mount.cwd.path = /home/s031-n001/graphene/Examples/openvino/openvino
fs.mount.cwd.uri = file:./openvino
```

Is the second line the correct one? Could you replace these lines in the manifest.template with just `openvino` instead of `$(OPENVINO_DIR_ABSPATH)` and `$(OPENVINO_DIR)`? I have a feeling that this is mount point is incorrect.

**Comment by justalittlenoob** [comment]
@dimakuv   Thank you very much for your patience.
1. If only do step 1(add `loader.insecure__use_host_env = 1`), the result is same.  
2. If do step 1 and 2:
`./pal_loader openvino.manifest -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Forwarding host environment variables to the app is enabled. Don't use this configuration in production!
object_detection_sample_ssd: error while loading shared libraries: libformat_reader.so: cannot open shared object file: No such file or directory

`SGX=1 ./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
>sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
WARNING: Forwarding host environment variables to the app is enabled. Don't use this configuration in production!
object_detection_sample_ssd: error while loading shared libraries: libformat_reader.so: cannot open shared object file: No such file or directory

openvino manifest files changed according to your advice:   
[openvino.manifest.template](https://github.com/oscarlab/graphene/files/5298794/openvino.manifest.template.txt)
[openvino.manifest](https://github.com/oscarlab/graphene/files/5298797/openvino.manifest.txt)
[openvino.manifest.sgx](https://github.com/oscarlab/graphene/files/5298798/openvino.manifest.sgx.txt)

Besides, there is some environment setting which I am using.
`source /opt/intel/sgxsdk/environment`
`LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib`
`export OPENCV_TEST_DATA_PATH=/home/s031-n001/opencv/opencv_extra/testdata`
`export OpenCV_DIR=/home/s031-n001/opencv/opencv-4.4.0/build`

I hope this information can help.

**Comment by dimakuv** [comment]
I'm giving up, I don't understand why your manifest doesn't work :(

We'll need to find an Ubuntu 20.04 machine and try Graphene + OpenVINO ourselves. I am out of ideas.

**Comment by justalittlenoob** [comment]
@dimakuv Thank you for your efforts. BTW, on my ubuntu18.04, there is the same issue...

**Comment by justalittlenoob** [comment]
@dimakuv   
Hi, I walk around the problem by hard code the opencv lib path to `loader.env.LD_LIBRARY_PATH`  
Although I know it's not beautiful to do this.
