### ISSUE TITLE
Change the way Jenkins builds are set up

### ISSUE THREAD

**Issue by pwmarcz** [oscarlab/graphene#1844]
**Background**: My immediate problem is adding builds for Clang (see https://github.com/oscarlab/graphene/issues/1794). After the PR https://github.com/oscarlab/graphene/pull/1830 is merged, it should be possible to build and test the (Ubuntu 18.04, non-SGX) combination. However, I would rather not add more Jenkinsfiles that contain almost exactly the same code.

**Problem**: The Jenkinsfiles contain a lot of duplication. While it looks like SGX and non-SGX builds are significantly different, there are other axes on which the configuration is pretty similar:
* Ubuntu 16.04 and 18.04 (and possibly 20.04 soon)
* non-DEBUG and DEBUG
* soon: GCC and Clang

With the current setup, that means a lot of copy-paste between the files, and unintended configuration drift as some files are updated but not others.

**Proposed solutions**:
1. Use [`matrix` declaration in Jenkinsfiles](https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/). This seems to work but it's a relatively new feature and the UI isn't very good. All the output is displayed on one page, and it seems that it is not possible to re-run a single configuration.
2. Set up a [multi-configuration project](https://wiki.jenkins.io/display/JENKINS/Building+a+matrix+project) which seems to be the "standard" way to do this in Jenkins. However, this moves more configuration out of the repo and into Jenkins UI.
3. Generate the Jenkinsfiles from a template. This seems like a cheap solution, and a good temporary first step. It does require us to commit the generated Jenkinsfiles to Git, which is slightly ugly. However, the risk of drift is minimized - we will not edit the files manually anymore, but edit the template and re-generate them.
4. Use another CI?

CC @mkow @woju

**Comment by dimakuv** [comment]
@woju Did we fix this issue? Should we close it?

**Comment by dimakuv** [comment]
Oops, actually the author is @pwmarcz . Do you consider this issue closed?

**Comment by pwmarcz** [comment]
Yes, this looks much better now, I'm closing the issue.
