### ISSUE TITLE
Error while trying to built the target libra_tls_verify_dcap.so

### ISSUE THREAD

**Issue by kleirama** [oscarlab/graphene#1847]
I am trying to build `ra-tls` using `make dcap` and I got the following error:

```
 make -C ../../Pal/src/host/Linux-SGX/tools/ra-tls dcapmake: Entering directory '/home/kleir/graphene/Pal/src/host/Linux-SGX/tools/ra-tls'
gcc ra_tls_verify_common.o ra_tls_verify_dcap.o -L../../../../../lib/crypto/mbedtls/install/lib -Wl,-rpath,. -L../common -lsgx_util -lmbedcrypto -lmbedx509 -lsgx_dcap_quoteverify -shared -o libra_tls_verify_dcap.so
/usr/local/bin/ld: cannot find -lsgx_dcap_quoteverify
collect2: error: ld returned 1 exit status
Makefile:29: recipe for target 'libra_tls_verify_dcap.so' failed
make: *** [libra_tls_verify_dcap.so] Error 1
```
I have `libsgx_dcap_quoteverify.so.1` under `/usr/lib/x86_64-linux-gnu` and as I see from Makefile located at  `Pal/src/host/Linux-SGX/tools/ra-tls`, I see that it expects libsgx_dcap_quoteverify.so.1 under `Pal/src/host/Linux-SGX/tools/common`

How can I manage to build dcap?

**Comment by dimakuv** [comment]
Could you execute this particular step that fails manually, adding `-Wl,--verbose`? Like this:
```bash
~/graphene/Pal/src/host/Linux-SGX/tools/ra-tls$ gcc -Wl,--verbose ra_tls_verify_common.o ra_tls_verify_dcap.o -L../../../../../lib/crypto/mbedtls/install/lib -Wl,-rpath,. -L../common -lsgx_util -lmbedcrypto -lmbedx509 -lsgx_dcap_quoteverify -shared -o libra_tls_verify_dcap.so
```

GCC will output a lot of helpful info. In my case, I see these lines:
```
...
attempt to open ../common/libsgx_dcap_quoteverify.so failed
attempt to open ../common/libsgx_dcap_quoteverify.a failed
attempt to open /usr/lib/gcc/x86_64-linux-gnu/7/libsgx_dcap_quoteverify.so failed
attempt to open /usr/lib/gcc/x86_64-linux-gnu/7/libsgx_dcap_quoteverify.a failed
attempt to open /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libsgx_dcap_quoteverify.so succeeded
...
```

As you can see, my GCC tried several paths, and found `libsgx_dcap_quoteverify.so` in one of the classical Linux paths (`/usr/lib/x86_64-linux-gnu/`). Also, this is what I have in this directory (after installing Intel SGX DCAP):
```bash
$ ll /usr/lib/x86_64-linux-gnu/libsgx_dcap*
lrwxrwxrwx 1 root root      19 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so -> libsgx_dcap_ql.so.1
lrwxrwxrwx 1 root root      27 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so.1 -> libsgx_dcap_ql.so.1.6.100.2
-rw-r--r-- 1 root root   14176 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_ql.so.1.6.100.2
lrwxrwxrwx 1 root root      28 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so -> libsgx_dcap_quoteverify.so.1
lrwxrwxrwx 1 root root      36 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so.1 -> libsgx_dcap_quoteverify.so.1.6.100.2
-rw-r--r-- 1 root root 2937944 Apr  3 00:58 /usr/lib/x86_64-linux-gnu/libsgx_dcap_quoteverify.so.1.6.100.2
```

You're supposed to see similar outputs.

**Comment by mkow** [comment]
No response from the original reporter for quite some time, closing.

**Comment by ltinerary** [comment]
I had the same problem.
And according to @dimakuv  answer，
I found in my `/usr/lib/x86_64-linux-gnu`  directory,
My machine environment missed a *.so file.
And the *.so file is just a Symbolic Link.
So I Manually set up the Symbolic Link.
It worked!
![image](https://user-images.githubusercontent.com/79144923/122325745-b7f30f80-cf5d-11eb-92b3-20624582a8a0.png)
