### ISSUE TITLE
Graphene on CentOS 8.1

### ISSUE THREAD

**Issue by yehuihe** [oscarlab/graphene#1851]
## Description of the problem
I installed graphene on my CentOS 8.1. When i 'make' in the root it showed me the following error:

*make -C Pal all*
*make[1]: Entering directory '/home/admin/Project/graphene-master/Pal'*
*src/Makefile.Host:10: *** Unsupported platform: x86_64-redhat-linux.  Stop.*
*make[1]: Leaving directory '/home/admin/Project/graphene-master/Pal'*
*make: *** [Makefile:12: all] Error 2*

Anyone who uses CentOS have encountered this problem before? 

## Steps to reproduce

1. Download graphene-master.zip
2. unzip
3. In the root of graphene-master. 'make'
4. Error

## Actual results

*make -C Pal all*
*make[1]: Entering directory '/home/admin/Project/graphene-master/Pal'*
*src/Makefile.Host:10: *** Unsupported platform: x86_64-redhat-linux.  Stop.*
*make[1]: Leaving directory '/home/admin/Project/graphene-master/Pal'*
*make: *** [Makefile:12: all] Error 2*

OS: CentOS 8.1

**Comment by mkow** [comment]
Interesting. This was generated by this check: https://github.com/oscarlab/graphene/blob/4bb416952eb0e703beb7e0cc715bf5d161e15568/Scripts/Makefile.Host#L8-L12
but I don't see how could it fail this way, you have "linux" in the platform name. Are you sure you're using Graphene from master branch?

**Comment by yehuihe** [comment]
> Interesting. This was generated by this check:
> 
> https://github.com/oscarlab/graphene/blob/4bb416952eb0e703beb7e0cc715bf5d161e15568/Scripts/Makefile.Host#L8-L12
> 
> 
> but I don't see how could it fail this way, you have "linux" in the platform name. Are you sure you're using Graphene from master branch?

I downloaded zip from git (not clone). The directory named 'graphene-master'.

What it suppose to generate?

**Comment by mkow** [comment]
I don't think you're actually using master branch, the line numbers doesn't match. The error log you pasted contains `src/Makefile.Host:10`, while this error is generated on line 11 on current master.

I never used this "download zip" feature, no idea what exactly is downloaded there. Maybe you unpacked some older version from your Downloads folder?

**Comment by mkow** [comment]
No response from the author + the cause was most likely using an old version of Graphene (see my previous comment). Closing.
