### ISSUE TITLE
Graphene-SGX limits maximum enclave size to 32G only

### ISSUE THREAD

**Issue by veenasai2** [oscarlab/graphene#1856]
## Description of the problem
Current implementation of Graphene-SGX doesn't allow enclave size larger than 32G. 
sgx.enclave_size = 64G in manifest file, throws an error. 

## Steps to reproduce
1.  cd graphene/Examples/redis    or any other Example code
2.  sudo vim redis-server.manifest.template
3.  sgx.enclave_size = 64G  and save
4.  sudo make SGX=1
5.  sudo SGX=1 ./pal_loader redis-server
error: pal-Linux-SGX: assert failed sgx_framework.c:134 IS_ALIGNED(secs->base, secs->size)

## Expected results
sgx.enclave_size = 64G  should work

## Actual results
sgx.enclave_size = 64G
gives  error 
pal-Linux-SGX: assert failed sgx_framework.c:134 IS_ALIGNED(secs->base, secs->size)

## Workaround
Inside Pal/src/host/Linux-SGX/pal_linux_defs.h change the ENCLAVE_HIGH_ADDRESS as follows

Original value 
#define ENCLAVE_HIGH_ADDRESS   0x800000000  //32G

New value 
#define ENCLAVE_HIGH_ADDRESS   0x1000000000 //64G

**Comment by dimakuv** [comment]
@veenasai2 Could you check that https://github.com/oscarlab/graphene/pull/1863 fixes your issue on your 64GB enclave?

**Comment by veenasai2** [comment]
@dimakuv the issue is fixed now. I verified for enclave size 1024M, 32G, 64G, and 128G . All are working fine. You can close the issue. Thanks.
