### ISSUE TITLE
Recent FSGSBASE update issue. 

### ISSUE THREAD

**Issue by noodlehair-git** [oscarlab/graphene#1861]
My NUC specifications are as follows: 

```Linux NUC10i7FNH 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```

```Distributor ID: Ubuntu ; Description:    Ubuntu 18.04.5 LTS ; Release:        18.04 ; Codename:       bionic```

I haven't done any updates in like a month (or maybe more), but I am facing this error when I try to run my python script on Graphene (which worked fine previously). 

```
FSGSBASE instructions, which Graphene requires on SGX.
The best option is to move to a newer Linux kernel with FSGSBASE support (5.9+), or a kernel with a back-ported patch to support FSGSBASE. One may also load the Graphene SGX kernel, although this is insecure. If the Graphene SGX module is loaded, check permissions on the device /dev/gsgx, as we cannot open this file.”
```

If I haven't done any updates in the past I shouldn't be facing this!? What would you suggest me to do in this case? My project was built and tested over the previous version and I am still left with some benchmarks. Would upgrading make any difference?

**Comment by dimakuv** [comment]
You probably rebooted your machine, and the `/dev/gsgx` kernel module (the insecure Graphene SGX module) was not automatically loaded. Please do smth like this on your machine:
```
~/graphene$ cd Pal/src/host/Linux-SGX/sgx-driver/
~/graphene/Pal/src/host/Linux-SGX/sgx-driver$ make
~/graphene/Pal/src/host/Linux-SGX/sgx-driver$ sudo insmod gsgx.ko
```

Please be aware that this trick is *only for debugging purposes* and *your OS becomes insecure*. Ideally, you would want to move to Linux 5.9 or higher or backport our FSGSBASE patches to Linux 5.4 (see https://github.com/oscarlab/graphene-sgx-driver).

**Comment by mkow** [comment]
This may also be helpful: https://graphene.readthedocs.io/en/latest/building.html#install-the-linux-kernel-patched-with-fsgsbase

**Comment by noodlehair-git** [comment]
Thank you for your reply! 
I get this error when I tried your suggested solution 
```insmod: ERROR: could not load module gsgx.ko: No such file or directory```
