### ISSUE TITLE
Openvino in Graphene-SGX error: Accessing file: libstdc++.so.6/libjpeg.so.8/libpng16.so.16 denied

### ISSUE THREAD

**Issue by justalittlenoob** [oscarlab/graphene#1869]
when run OpenVINO/object_detection_sample_ssd in Graphene-SGX(accroding to this https://github.com/oscarlab/graphene/tree/master/Examples/openvino)
`SGX=1 ./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`   

ubuntu 20.04 log
```
sgx.protected_fileskey not found in manifest, protected files will not be available
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:/lib/x86_64-linux-gnu/libstdc++.so.6 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libjpeg.so.8 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/usr/lib/x86_64-linux-gnu/libjpeg.so.8 is denied (Unknown error). This file is not trusted or allowed. Trustedfiles should be regular files (seekable).
object_detection_sample_ssd: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such fileor directory
```

ubuntu 18.04 log
```
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:/usr/lib/x86_64-linux-gnu/libjpeg.so.8 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
object_detection_sample_ssd: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```

According to the error, I add sgx.trusted_files.libjpeg = file:/usr/$(ARCH_LIBDIR)/libjpeg.so.8 to openvino.manifest.template and rebuilt it. But when i run it again, there is another lib file accessing error.
`SGX=1 ./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
```
Accessing file:/lib/x86_64-linux-gnu/libstdc++.so.6 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libjpeg.so.8 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libpng16.so.16 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/usr/lib/x86_64-linux-gnu/libpng16.so.16 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
object_detection_sample_ssd: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```

So i add `sgx.trusted_files.libpng16 = file:/usr/$(ARCH_LIBDIR)/libpng16.so.16` to the manifest file, rebuilt and run it again.
`SGX=1 ./pal_loader openvino.manifest.sgx -i images/horses.jpg -m model/VGG_VOC0712Plus_SSD_300x300_ft_iter_160000.xml -d CPU`
```
WARNING: Using insecure argv source. Don't use this configuration in production!
Accessing file:/lib/x86_64-linux-gnu/libstdc++.so.6 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libjpeg.so.8 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libpng16.so.16 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/lib/x86_64-linux-gnu/libtiff.so.5 is denied (Unknown error). This file is not trusted or allowed. Trusted files should be regular files (seekable).
Accessing file:/usr/lib/x86_64-linux-gnu/libtiff.so.5 is denied (Unknown error). This file is not trusted or allowed. Trustedfiles should be regular files (seekable).
object_detection_sample_ssd: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such fileor directory
```

No matter how much trusted file addded to the manifest, the error seems endless.    
The manifest file is [openvino.manifest.template](https://github.com/oscarlab/graphene/files/5325033/openvino.manifest.template.txt)

Besides, another question is about manifest syntax(https://graphene.readthedocs.io/en/latest/manifest-syntax.html#environment-variables).   
`fs.mount.[identifier].path=[PATH]`
`fs.mount.[identifier].type=[chroot|...]`
`fs.mount.[identifier].uri=[URI]`
How many `identifier` are there in graphene? I have seen `lib` `lib2` `lib3` `etc` `cwd`, anything else?
Any advice would be appreciated. Thank you in advance.

**Comment by dimakuv** [comment]
In the manifest that you've sent, you have these lines:
```
fs.mount.lib.type = chrootfs.mount.lib.path = /lib
fs.mount.lib.uri = file:$(GRAPHENE_DIR)/Runtime
```

Note how you have two entries fused together in the first line. I don't know if you incorrectly copy-pasted your actual manifest, but this shouldn't work (I'm surprised Graphene didn't fail).

It should be three lines like this:
```
fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:$(GRAPHENE_DIR)/Runtime
```

> How many identifier are there in graphene? I have seen lib lib2 lib3 etc cwd, anything else?

Infinite number of identifiers is possible. Identifiers are just some names that you choose for convenience. Sometimes it makes sense to give a meaningful name like `etc` but sometimes you just don't care and give a name like `lib2`. It doesn't matter *as long as identifiers are unique* throughout your manifest.

**Comment by justalittlenoob** [comment]
@dimakuv   
Sorry, it is a incorrectly copy-pasted mistake. It does look like this：
`fs.mount.lib.type = chroot`
`fs.mount.lib.path = /lib`
`fs.mount.lib.uri = file:$(GRAPHENE_DIR)/Runtime`

I have corrected this manifest file: [openvino.manifest.template](https://github.com/oscarlab/graphene/files/5328506/openvino.manifest.template.txt)  
There are only 4 lines in this file that have been changed (lines ending with comment `zpf`), the others are the same as the original https://github.com/oscarlab/graphene/blob/master/Examples/openvino/openvino.manifest.template  

I think I must have missed something, but I don't know where. Can you give me some guidance? Thank you very much.

**Comment by dimakuv** [comment]
Are you sure you're running the latest master of Graphene?

I am puzzled because I don't experience any problems on Ubuntu 18.04.

**Comment by justalittlenoob** [comment]
@dimakuv   
I am sure i am using the latest master branch.  
I am building graphene according to https://graphene.readthedocs.io/en/latest/building.html, but without the step `Install the Linux kernel patched with FSGSBASE`. Does this matter?
Besides, the opencv is installed according to https://github.com/openvinotoolkit/openvino/blob/master/build-instruction.md#use-custom-opencv-builds-for-inference-engine  `Use Custom OpenCV Builds for Inference Engine`

**Comment by justalittlenoob** [comment]
@dimakuv  The reason i am using `Custom OpenCV Builds for Inference Engine` is because I have a `OpenCV is not available on current platform` problem.(This problem is described here https://github.com/openvinotoolkit/openvino/issues/2392 )

**Comment by dimakuv** [comment]
@justalittlenoob I'm still confused... So what version of OpenVINO are you trying to run on Ubuntu 18.04? Is it the default https://github.com/oscarlab/graphene/tree/master/Examples/openvino without any changes to the Makefile and the manifest? Could you first verify that on Ubuntu 18.04, with the latest Graphene master version, and with unmodified OpenVINO example, it works fine?

**Comment by justalittlenoob** [comment]
@dimakuv   

> Could you first verify that on Ubuntu 18.04, with the latest Graphene master version, and with unmodified OpenVINO example, it works fine?

Yes. It works.  

But what embarrassed me was 
1. I had to use ubuntu20.04.  (Project needs).
2. If using ubuntu20.04, when run `graphene/Examples/openvino$make SGX=1` will get the issue 
>‘/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/download/iomp.tgz’ saved [685885/685885]
-- extracting...
src='/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/download/iomp.tgz'
dst='/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/temp/omp'
-- extracting... [tar xfz]
CMake Error at inference-engine/cmake/dependencies.cmake:240 (message):
OpenCV is not available on current platform
Call Stack (most recent call first):
inference-engine/CMakeLists.txt:18 (include)
-- Configuring incomplete, errors occurred!
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeOutput.log".
See also "/home/s031-n001/graphene/Examples/openvino/openvino/inference-engine/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:62: openvino/inference-engine/bin/intel64/Release/object_detection_sample_ssd] Error 1

3. So, I have to `Use Custom OpenCV Builds for Inference Engine`.....
4. As a result, it leads to this problem `Accessing file: XXX denied` 

So, I use 18.04 (copy the steps on 20.04) to test openvino sample. It seems doesn't work too.  
Thant's why I did it.  
My goal is actually very simple, let openvino sample(graphene sgx mode) run on ubuntu20.04. Because we will use graphene and openvino on ubuntu 20.04 in later projects.   
Do you have any suggestions?

**Comment by dimakuv** [comment]
Got it. There seems to be some non-trivial issue in OpenVINO on Ubuntu 20.04. I am hoping to start testing Graphene under Ubuntu 20.04 more extensively and I'll update the OpenVINO example as well. Hopefully some time this week.

**Comment by justalittlenoob** [comment]
@dimakuv  Thank you very much for your help:)

**Comment by dimakuv** [comment]
OpenVINO works under Ubuntu 20.04 with the latest Graphene. Closing this. @justalittlenoob If your issue still persists under latest Graphene, feel free to reopen.
