### ISSUE TITLE
[LibOS] Error with *at() calls when absolute path is provide with invalid dirfd (like -1)

### ISSUE THREAD

**Issue by vijaydhanraj** [oscarlab/graphene#1877]
## Description of the problem
As per linux man-pages, dirfd can be ignored if an absolute path is provided when invoking *at() calls. But in graphene many of the *at() calls require a valid dirfd even when an absolute path is provided. If not, the call fails.

## Steps to reproduce
1. Build a simple graphene test application.
2. Invoke openat() function by setting dirfd to -1 and provide an absolute file path like "/proc/cpuinfo"
3. The call will fail with EBADF 9 Bad file descriptor.

## Expected results
openat() call should succeed as dirfd should be ignored when an absolute path is provided.

## Actual results
openat() function call fails with EBADF 9 Bad file descriptor error.

**Comment by dimakuv** [comment]
@vijaydhanraj Will you be able to provide a PR fixing this?

Isaku said this on Slack, posting here for context:
```
- The logic is common, so it shouldn't be scattered.i.e. get_dirfd_dentry(dfd, filename, &dir)
- if (dir) put_dentry

- optional: refactor *at() and *(). so that *() just calls *at(). some code already does. some doesn't yet
- optional: enable LTP with *at
```

**Comment by vijaydhanraj** [comment]
@dimakuv, yes I can provide a PR fixing this issue.
