### ISSUE TITLE
Undeclared SGX_INVALID_LICENSE variable

### ISSUE THREAD

**Issue by yhechaichi** [oscarlab/graphene#188]
Hello everyone, 
I'm trying to install graphene with intel SGX support (make SGX=1), everything works fine until I enter my sgx-driver folder and its version, after that I have the following error :

`sgx_framework.c: In function ‘init_enclave’:
sgx_framework.c:348:14: error: ‘SGX_INVALID_LICENSE’ undeclared (first use in this function)
         case SGX_INVALID_LICENSE:
`
I don't know where it comes from. Maybe I declared the wrong version or something as I don't know where to check it. Any help would be greatly appreciated !

**Comment by donporter** [comment]
What version of the Intel SGX driver are you using?  There was a recent pull request merged on the graphene SGX driver that should address this (you may need to do a 'git submodule update --recursive' to pull the latest graphene driver).

**Comment by yhechaichi** [comment]
It worked, thank you very much sir !
