### ISSUE TITLE
[LibOS]Glibc function daemon() fails because stat of /dev/null lacks st_rdev

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1891]
## Description of the problem
It's a simple issue. Glibc function `daemon` open and stat `/dev/null`, then checks stat.st_rdev against predefined value. See https://github.com/lattera/glibc/blob/master/misc/daemon.c#L70-L73 and https://github.com/lattera/glibc/blob/master/sysdeps/unix/sysv/linux/device-nrs.h#L25-L26.
However st_rdev is not set. https://github.com/oscarlab/graphene/blob/1b8e648ed8c6a38d872a42ea7523b630ca74545c/LibOS/shim/src/fs/dev/null.c#L38-L44
## Steps to reproduce
```
    if(daemon(0, 0) < 0)
    {
        printf("no daemon\n");
        exit(1);
    }
```
## Expected results
No prints.
## Actual results
`no daemon` printed.

**Comment by dimakuv** [comment]
Thanks for this bug report! @llly Would you like to provide a PR with a simple fix? Just hard-code the value `1,3` for `/dev/null` and add a comment that it's taken from Glibc 2.31 and is required by e.g. Glibc's `daemon()` functions.

**Comment by mkow** [comment]
> a comment that it's taken from Glibc 2.31

But we're emulating the kernel, not Glibc :) So, you should take the minor/major versions from the most recent Linux release.

**Comment by llly** [comment]
Major 1 is Macro MEM_MAJOR and minor 3 is from https://github.com/torvalds/linux/blob/master/drivers/char/mem.c#L978
