### ISSUE TITLE
C++ support?

### ISSUE THREAD

**Issue by JoshLind** [oscarlab/graphene#19]
Hi,

I'm not too sure where to find the answer to this, but how much support does Graphene-SGX provide for C++ applications? I've tried writing an example helloworld.cpp application and building/running it with Graphene, but I get errors when trying to link to the common libstdc++ libraries, such as iostream etc.

Does Graphene support C++ applications?

**Comment by chiache** [comment]
We have tested applications (e.g., OpenJDK) that link with libstdc++. You many want to check if you had added the URI of system's libstdc++.so to sgx.trusted_files.xxx in the manifest file.

If you have seen a warning "Accessing file:... is denied", it means the file is not recognized by the manifest. Make sure you update the manifest and re-sign the enclave.

**Comment by woonhak** [comment]
Here's some example.(please check path of the shared library) 

sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by JoshLind** [comment]
Great, thanks guys! Seem to have it working now :)

**Comment by AsierRF** [comment]
Hello,

I saw this issue has been set as closed but I face the same problem as @JoshLind with a cpp program. The "libstdc++.so.6" is not found.  I added the file to trusted files but still not working. I also added it to the loader.preload, still not working.

Here my manifest:

> loader.preload = file:../../../../Runtime/libsysdb.so,file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
loader.env.LD_LIBRARY_PATH = /lib
loader.debug_type = inline
loader.syscall_symbol = syscalldb
fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:../../../../Runtime
fs.mount.bin.type = chroot
fs.mount.bin.path = /bin
fs.mount.bin.uri = file:/bin
sys.brk.size = 32M
sys.stack.size = 4M
# allow to bind on port 8000
net.allow_bind.1 = 127.0.0.1:8000
# allow to connect to port 8000
net.allow_peer.1 = 127.0.0.1:8000
# sgx-related
sgx.trusted_files.ld = file:../../../../Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:../../../../Runtime/libc.so.6
sgx.trusted_files.libdl = file:../../../../Runtime/libdl.so.2
sgx.trusted_files.libm = file:../../../../Runtime/libm.so.6
sgx.trusted_files.libpthread = file:../../../../Runtime/libpthread.so.0
sgx.trusted_files.victim = file:exec_victim
sgx.trusted_children.victim = file:exec_victim.sig
sgx.trusted_files.librt = file:../../../../Runtime/librt.so.1
sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6

Any help will be welcome :)

**Comment by adombeck** [comment]
You didn't mount the directory that `libstdc++.so.6` is in. It should work if you add something like this to the manifest: 
```
fs.mount.usr.type = chroot
fs.mount.usr.path = /usr
fs.mount.usr.uri = file:/usr

```

**Comment by AsierRF** [comment]
Thanks for your quick response @adombeck 

I actually tried adding the fs.mount also and does not work, none as "fs.mount.usr.uri = file:/usr/lib/x86_64-linux-gnu/" and "fs.mount.usr.uri = file:/usr".

Here my manifest with it:

> loader.preload = file:../../../../Runtime/libsysdb.so,file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
loader.env.LD_LIBRARY_PATH = /lib
loader.debug_type = inline
loader.syscall_symbol = syscalldb
fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:../../../../Runtime
fs.mount.bin.type = chroot
fs.mount.bin.path = /bin
fs.mount.bin.uri = file:/bin
fs.mount.usr.type = chroot
fs.mount.usr.path = /usr
fs.mount.usr.uri = file:/usr/lib/x86_64-linux-gnu/
sys.brk.size = 32M
sys.stack.size = 4M
sgx.trusted_files.ld = file:../../../../Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:../../../../Runtime/libc.so.6
sgx.trusted_files.libdl = file:../../../../Runtime/libdl.so.2
sgx.trusted_files.libm = file:../../../../Runtime/libm.so.6
sgx.trusted_files.libpthread = file:../../../../Runtime/libpthread.so.0
sgx.trusted_files.victim = file:exec_victim
sgx.trusted_children.victim = file:exec_victim.sig
sgx.trusted_files.librt = file:../../../../Runtime/librt.so.1
sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6

**Comment by adombeck** [comment]
> Here my manifest with it:
> [...]
> fs.mount.usr.type = chroot
> fs.mount.usr.path = /usr
> fs.mount.usr.uri = file:/usr/lib/x86_64-linux-gnu/

You mounted your host systems `/usr` directory to Graphene's `/usr/lib/x86_64-linux-gnu`. This way, the `libstdc++.so.6` will be at `/usr/lib/x86_64-linux-gnu/lib/x86_64-linux-gnu/libstdc++.so.6` in Graphene. You should either mount `/usr` to `file:/usr` (like I suggested in my previous post) or mount `/usr/lib/x86_64-linux-gnu` to `file:/usr/lib/x86_64-linux-gnu`.

**Comment by AsierRF** [comment]
Hello once more.

Thanks for your help. Now I understand better what I was doing wrong. I was also missing to include the paths in loader.env.LD_LIBRARY_PATH = /lib separated with ":".

I managed to add all the libraries and the program seems to start working until It comes with the following "Cannot attach to any TCS!". I will continue with this problem now.

Once more, thank you very much :)

**Comment by donporter** [comment]
Thanks for the advice, @adombeck !  Glad @AsierRF was able to get this working.

**Comment by Vampsj** [comment]
Hello, 

I have checked the solutions, but I still have some problems with cpp.
I followed @woonhak 's example and simply add to the gcc.manifest with library checked. Also I have remake the files. However it seems not working.

> Accessing file:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus is denied. (Unknown error) This file is not trusted or allowed.
gcc: error trying to exec '/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus': execv: Permission denied

Any help will be welcome, thank you

**Comment by Vampsj** [comment]
@donporter Thank you for your response!

Here is my manifest template
> loader.preload = file:$(SHIMPATH)
loader.exec = file:/usr/bin/g++
loader.execname = /usr/bin/g++
loader.env.LD_LIBRARY_PATH = /lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
loader.env.PATH = /bin:/usr/bin
loader.debug_type = $(DEBUGTYPE)
fs.mount.lib1.type = chroot
fs.mount.lib1.path = /lib
fs.mount.lib1.uri = file:$(LIBCDIR)
fs.mount.lib2.type = chroot
fs.mount.lib2.path = /lib/x86_64-linux-gnu
fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
fs.mount.usr.type = chroot
fs.mount.usr.path = /usr
fs.mount.usr.uri = file:/usr
fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp
sgx.enclave_size = 1G
sgx.trusted_files.ld = file:$(LIBCDIR)/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:$(LIBCDIR)/libc.so.6
sgx.trusted_files.libdl = file:$(LIBCDIR)/libdl.so.2
sgx.trusted_files.libm = file:$(LIBCDIR)/libm.so.6
sgx.trusted_files.libpthread = file:$(LIBCDIR)/libpthread.so.0
sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
sgx.trusted_files.libgcc = file:/usr/lib/x86_64-linux-gnu/libgccpp.so.1
sgx.trusted_files.cc1plus = files:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus
sgx.trusted_files.cc1 = file:$(GCCDIR)/cc1
sgx.trusted_files.collect2 = file:$(GCCDIR)/collect2
sgx.trusted_files.as = file:/usr/bin/as
sgx.allowed_files.tmp = file:/tmp
sgx.allowed_files.test_files = file:test_files
sgx.trusted_children.cc1 = file:cc1.sig
sgx.trusted_children.collect2 = file:collect2.sig
sgx.trusted_children.as = file:as.sig

When I **make SGX=1**, this part **sgx.trusted_files.cc1plus = files:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus** went wrong and I got
> Traceback (most recent call last):
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 720, in <module>
    for key, val in get_trusted_files(manifest, args).items():
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 232, in get_trusted_files
    targets[key] = (val, resolve_uri(val))
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 203, in resolve_uri
    raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve files:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus or the file does not exist.
../../../../../Pal/src///host/Linux-SGX/Makefile.Test:40: recipe for target 'gcc.manifest.sgx' failed
make: *** [gcc.manifest.sgx] Error 1

While if I comment out the cc1plus line, I can successfully make, but when I compile the cpp file, I get error

> Accessing file:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus is denied. (Unknown error) This file is not trusted or allowed.
g++: error trying to exec '/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus': execv: Permission denied

**Comment by dimakuv** [comment]
@Vampsj , you have a typo in the `sgx.trusted_files.cc1plus = files:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus` line. It should be **file:**, not **files:**.

**Comment by Vampsj** [comment]
Thank you so much for your help! @dimakuv  You are right! I missed it. 

Now I can successfully **make SGX** and **make SGX_RUN**, but the  __cc1plus.menifest.sgx __ is not generated and thus I got
>cannot open manifest file: cc1plus.manifest.sgx

So I also added cc1plus as **sgx.trusted_children**, but I got
> Traceback (most recent call last):
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 720, in <module>
    for key, val in get_trusted_files(manifest, args).items():
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 216, in get_trusted_files
    targets['exec'] = (args['exec'], resolve_uri(args['exec']))
  File "/home/vamps/git/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 203, in resolve_uri
    raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve $/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus or the file does not exist.
../../../../../Pal/src///host/Linux-SGX/Makefile.Test:40: recipe for target 'cc1plus.manifest.sgx' failed
make[1]: *** [cc1plus.manifest.sgx] Error 1
rm cc1plus.manifest
make[1]: Leaving directory '/home/vamps/git/graphene/LibOS/shim/test/apps/gpp'
../../../../../Pal/src///host/Linux-SGX/Makefile.Test:40: recipe for target 'gcc.manifest.sgx' failed
make: *** [gcc.manifest.sgx] Error 2

Do I really need to add cc1plus as trusted file or I should set it as loader.exec? 
Thank you very much

**Comment by dimakuv** [comment]
@Vampsj , the exception tells that it cannot find `$/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus`. Note the dollar sign `$` in the beginning -- it should not be there.

You're doing everything right with adding `cc1plus` as a trusted child, but you seem to have another typo in your manifest. What is the line that you're trying to add?

**Comment by Vampsj** [comment]
@dimakuv Thank you for your reply. I add  **sgx.trusted_children.cc1plus = file:cc1plus.sig** just as others. My full manifest is as follows:

> loader.preload = file:$(SHIMPATH)
loader.exec = file:/usr/bin/g++
loader.execname = /usr/bin/g++
loader.env.LD_LIBRARY_PATH = /lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu
loader.env.PATH = /bin:/usr/bin
loader.debug_type = $(DEBUGTYPE)
fs.mount.lib1.type = chroot
fs.mount.lib1.path = /lib
fs.mount.lib1.uri = file:$(LIBCDIR)
fs.mount.lib2.type = chroot
fs.mount.lib2.path = /lib/x86_64-linux-gnu
fs.mount.lib2.uri = file:/lib/x86_64-linux-gnu
fs.mount.usr.type = chroot
fs.mount.usr.path = /usr
fs.mount.usr.uri = file:/usr
fs.mount.tmp.type = chroot
fs.mount.tmp.path = /tmp
fs.mount.tmp.uri = file:/tmp
sgx.enclave_size = 1G
sgx.trusted_files.ld = file:$(LIBCDIR)/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:$(LIBCDIR)/libc.so.6
sgx.trusted_files.libdl = file:$(LIBCDIR)/libdl.so.2
sgx.trusted_files.libm = file:$(LIBCDIR)/libm.so.6
sgx.trusted_files.libpthread = file:$(LIBCDIR)/libpthread.so.0
sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
sgx.trusted_files.libgcc = file:/usr/lib/x86_64-linux-gnu/libgccpp.so.1
sgx.trusted_files.libcpp5 = file:/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.so
sgx.trusted_files.libcpp5a = file:/usr/lib/gcc/x86_64-linux-gnu/5/libstdc++.a
sgx.trusted_files.cc1plus = file:/usr/lib/gcc/x86_64-linux-gnu/5/cc1plus
sgx.trusted_files.cc1 = file:$(GCCDIR)/cc1
sgx.trusted_files.collect2 = file:$(GCCDIR)/collect2
sgx.trusted_files.as = file:/usr/bin/as
sgx.allowed_files.tmp = file:/tmp
sgx.allowed_files.test_files = file:test_files
sgx.trusted_children.cc1 = file:cc1.sig
sgx.trusted_children.collect2 = file:collect2.sig
sgx.trusted_children.as = file:as.sig
sgx.trusted_children.cc1plus = file:cc1plus.sig

Thank you very much!
