### ISSUE TITLE
Which branch does openjdk work?

### ISSUE THREAD

**Issue by wangchenghku** [oscarlab/graphene#190]
Hi,

I'm trying to build Openjdk 1.7 using the master branch. However, I found there are two problems. First, there is no such JDK-8015880.patch file in this branch. Second, the build fails and it shows the following information:
```
for f in `grep -Po 'sgx.trusted_children.[^\\s=]+\\s*=\\s*file:\\K\\S+' java.manifest`; do make ${f%.sig}.manifest.sgx; done
make[1]: Entering directory `/home/hkucs/graphene/LibOS/shim/test/apps/openjdk'
make[1]: `java.manifest' is up to date.
make[1]: Leaving directory `/home/hkucs/graphene/LibOS/shim/test/apps/openjdk'
[ java.manifest.sgx ]
/home/hkucs/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal /home/hkucs/graphene/Pal/src/host/Linux-SGX/../../../../Runtime/libpal-Linux-SGX.so -key /home/hkucs/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output java.manifest.sgx -manifest java.manifest
Attributes:
    size:      268435456
    threadnum: 12
    isvprodid: 0
    isvsvn:    0
    flags:     0600000000000000
    xfrms:     0700000000000000
    miscs:     00000000
Trusted files:
Traceback (most recent call last):
  File "/home/hkucs/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 720, in <module>
    for key, val in get_trusted_files(manifest, args).items():
  File "/home/hkucs/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 232, in get_trusted_files
    targets[key] = (val, resolve_uri(val))
  File "/home/hkucs/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign", line 203, in resolve_uri
    raise Exception('Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve file:openjdk-7-jre/lib/tzdb.dat or the file does not exist.
make: *** [java.manifest.sgx] Error 1

```
It says tzdb.dat is missing. However, I think Java 1.8 uses tzdb.dat file, while java 1.7 should use `zi` folder for time zone information. Therefore, I get confused because here we are trying to build JDK 1.7 but it tries to find tzdb.dat file.

May I know which branch is stable for making Openjdk work? Thanks for your time and patience.

**Comment by donporter** [comment]
Did you figure this out?  @chiache knows more details about running openjdk on Graphene.

**Comment by wangchenghku** [comment]
To run Openjdk successfully, I have reverted back to 1.8-build branch :(

**Comment by donporter** [comment]
I'm going to flag this as a bug and reopen the issue - we should fix the openjdk regression and get this in CI.

**Comment by zavalyshyn** [comment]
@wangchenghku what were your actions to run it at 1.8 build? For me, it still complains on the missing patch even on the 1.8 build.

**Comment by wangchenghku** [comment]
@zavalyshyn I think this is the needed patch. Just rename it to JDK-8015880.patch. https://github.com/oscarlab/graphene/blob/1.8-build/LibOS/shim/test/apps/openjdk/smaller-jdk.patch

**Comment by zavalyshyn** [comment]
Just for anyone coming here for openjdk compilation.

Indeed, as @wangchenghku mentioned openjdk does compile on 1.8-build branch only. That brunch still requires linux-sgx-driver v 1.8. 
To compile and execute a HelloWorld program run:
``` 
make SGX=1
make SGX_RUN=1
./run-compact-java -cp classes: HelloWorld
```
Even a simple HelloWorld java program took couple of minutes to execute. Not sure if that is because of the outdated version of code or the memory footprint of openjdk.

**Comment by melbek** [comment]
Hi everyone,

@zavalyshyn which branch do you mean? The link from @wangchenghku is not working anymore and I cannot find or restore the mentioned 1.8-build branch.
So is graphene not applicable to Java applications anymore?

Thank you in advance!

**Comment by zavalyshyn** [comment]
@melbek that branch does not exist anymore apparently. I suggest to try with the latest version of Graphene.

**Comment by JackSpice** [comment]
Latest version has the same issue. Could you please upload the path file?

**Comment by mkow** [comment]
Seems that the discussion moved to #1152, this one is outdated.
