### ISSUE TITLE
Signed Graphenized docker Exception: Failed. (Error Code = 30)

### ISSUE THREAD

**Issue by sanmiawi** [oscarlab/graphene#1900]
## Description of the problem
I get the following error when trying to run a graphenized docker image built and signed with the **GSC** tool

```
+ [ -z  ]
+ GSC_PAL=Linux-SGX
+ executable=bash
+ /graphene/signer/pal-sgx-get-token -output bash.token -sig bash.sig
Attributes:
    mr_enclave:  82b7e8a43781ae675de4e642dcc32b46e7553e4ac08be4024e16cdced931879b
    mr_signer:   eeb6d1b76737a593ba28b73557bfdfca0390819026b598a00385119e2407cc32
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   1f00000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     c192014afcd61cc948f362c565429355...
    exponent:    3
    signature:   e6aecab6689393fa96823bf8571973b5...
    date:        2020-10-16
Traceback (most recent call last):
  File "/graphene/signer/pal-sgx-get-token", line 207, in <module>
    sys.exit(main())
  File "/graphene/signer/pal-sgx-get-token", line 199, in main
    token = connect_aesmd(attr)
  File "/graphene/signer/pal-sgx-get-token", line 122, in connect_aesmd
    raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
Exception: Failed. (Error Code = 30)

```

## Steps to reproduce

- OS Ubuntu 18.04
- git cloned graphene  `git clone https://github.com/oscarlab/graphene.git`
- `cd graphene`
- `make` 
- `make SGX=1`
- built docker image
- built graphenized image with `./gsc build --insecure-args b_docker_2 b_docker_2.manifest`
- signed image with `./gsc sign-image b_docker_2 enclave-key.pem`
- issued `sudo docker run --device=/dev/gsgx --device=/dev/sgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket -it gsc-b_docker_2` to run container

Docker runs fine with bash prompt.
Graphenized image does not.

How can I fix this?

**Comment by mkow** [comment]
Does Graphene with Linux-SGX PAL works for you? (without GSC)
Error 30 is `AESM_SERVICE_UNAVAILABLE`. Could you check logs/status for aesmd service in your system?

**Comment by sanmiawi** [comment]
Hi @mkow , thanks for your reply.
> Does Graphene with Linux-SGX PAL works for you? (without GSC)

I am new to Linux-SGX and do not know if PAL requires extra configuration. I have been able to install SGX SDK and run some of the sample codes that come with the intel driver 

```
make[1]: Entering directory '/opt/intel/sgxsdk/SampleCode/SampleEnclave'
GEN  =>  App/Enclave_u.h
CC   <=  App/Enclave_u.c
CXX  <=  App/App.cpp
CXX  <=  App/Edger8rSyntax/Types.cpp
CXX  <=  App/Edger8rSyntax/Pointers.cpp
CXX  <=  App/Edger8rSyntax/Arrays.cpp
CXX  <=  App/Edger8rSyntax/Functions.cpp
CXX  <=  App/TrustedLibrary/Thread.cpp
CXX  <=  App/TrustedLibrary/Libcxx.cpp
CXX  <=  App/TrustedLibrary/Libc.cpp
LINK =>  app
GEN  =>  Enclave/Enclave_t.h
CC   <=  Enclave/Enclave_t.c
CXX  <=  Enclave/Edger8rSyntax/Arrays.cpp
CXX  <=  Enclave/Edger8rSyntax/Functions.cpp
CXX  <=  Enclave/Edger8rSyntax/Pointers.cpp
CXX  <=  Enclave/Edger8rSyntax/Types.cpp
CXX  <=  Enclave/Enclave.cpp
CXX  <=  Enclave/TrustedLibrary/Libc.cpp
CXX  <=  Enclave/TrustedLibrary/Libcxx.cpp
CXX  <=  Enclave/TrustedLibrary/Thread.cpp
LINK =>  enclave.so
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>0x40000</StackMaxSize>
    <HeapMaxSize>0x100000</HeapMaxSize>
    <TCSNum>10</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <!-- Recommend changing 'DisableDebug' to 1 to make the enclave undebuggable for enclave release -->
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
</EnclaveConfiguration>
tcs_num 10, tcs_max_num 10, tcs_min_pool 1
The required memory is 4059136B.
The required memory is 0x3df000, 3964 KB.
Succeed.
SIGN =>  enclave.signed.so
The project has been built in debug hardware mode.
make[1]: Leaving directory '/opt/intel/sgxsdk/SampleCode/SampleEnclave'
```

```

/opt/intel/sgxsdk/SampleCode/SampleEnclave$ ./app
Checksum(0x0x7ffd608813c0, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...
m

```



> Error 30 is `AESM_SERVICE_UNAVAILABLE`. Could you check logs/status for aesmd service in your system?

```
$ systemctl status aesmd
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-10-15 18:08:08 CEST; 2 days ago
 Main PID: 2211 (aesm_service)
    Tasks: 4 (limit: 4915)
   CGroup: /system.slice/aesmd.service
           └─2211 /opt/intel/sgx-aesm-service/aesm/aesm_service

Okt 16 04:02:29 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 16 14:35:37 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 16 23:48:38 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 16 23:49:05 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 16 23:49:21 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 17 00:33:13 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 17 00:34:40 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 17 01:01:02 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 17 01:01:21 usrk1 aesm_service[2211]: InKernel LE loaded
Okt 17 01:08:34 usrk1 aesm_service[2211]: InKernel LE loaded

```

**Comment by mkow** [comment]
> I am new to Linux-SGX and do not know if PAL requires extra configuration. I have been able to install SGX SDK and run some of the sample codes that come with the intel driver

The steps are:
1. Build Graphene with Linux-SGX PAL: https://graphene.readthedocs.io/en/latest/building.html#building-with-sgx-support
2. Go to `LibOS/shim/test/regression/` and run `make SGX=1 regression`.

Hope I didn't forget any step.

**Comment by sanmiawi** [comment]
>     1. Build Graphene with Linux-SGX PAL: https://graphene.readthedocs.io/en/latest/building.html#building-with-sgx-support

I already used the steps in the provided link.

>     2. Go to `LibOS/shim/test/regression/` and run `make SGX=1 regression`.
This failed with the following error:

```
==================================================================================================== FAILURES =====================================================================================================
________________________________________________________________________________________ TC_30_Syscall.test_052_large_mmap ________________________________________________________________________________________

self = <test_libos.TC_30_Syscall testMethod=test_052_large_mmap>

    def test_052_large_mmap(self):
        try:
>           stdout, _ = self.run_binary(['large_mmap'], timeout=480)

test_libos.py:417: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_libos.TC_30_Syscall testMethod=test_052_large_mmap>, args = ['large_mmap'], timeout = 480, prefix = [], kwds = {}, loader = '/home/usrk1/graphene/graphene/Runtime/pal-Linux-SGX'
libpal = '/home/usrk1/graphene/graphene/Runtime/libpal-Linux-SGX.so', process = <subprocess.Popen object at 0x7fa7ab784c88>, stdout = b'', stderr = b''

    def run_binary(self, args, *, timeout=None, prefix=None, **kwds):
        timeout = (max(self.DEFAULT_TIMEOUT, timeout) if timeout is not None
            else self.DEFAULT_TIMEOUT)
    
        loader = self.get_env(self.LOADER_ENV)
        if not pathlib.Path(loader).exists():
            self.skipTest('loader ({}) not found'.format(loader))
    
        libpal = self.get_env(self.LIBPAL_PATH_ENV)
        if not pathlib.Path(libpal).exists():
            self.skipTest('libpal ({}) not found'.format(libpal))
    
        if prefix is None:
            prefix = []
    
        with subprocess.Popen([*prefix, loader, libpal, 'init', *args],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                preexec_fn=os.setpgrp,
                **kwds) as process:
            try:
                stdout, stderr = process.communicate(timeout=timeout)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)
                self.fail('timeout ({} s) expired'.format(timeout))
    
            self.print_output(stdout, stderr)
    
            if process.returncode:
                raise subprocess.CalledProcessError(
>                   process.returncode, args, stdout, stderr)
E               subprocess.CalledProcessError: Command '['large_mmap']' died with <Signals.SIGKILL: 9>.

../../../../Scripts/regression.py:86: CalledProcessError
-------------------------------------------------------- generated xml file: /home/usrk1/graphene/graphene/LibOS/shim/test/regression/libos-regression.xml --------------------------------------------------------
============================================================================================= short test summary info =============================================================================================
FAILED test_libos.py::TC_30_Syscall::test_052_large_mmap - subprocess.CalledProcessError: Command '['large_mmap']' died with <Signals.SIGKILL: 9>.
=============================================================================== 1 failed, 84 passed, 4 skipped in 452.13s (0:07:32) ===============================================================================
Makefile:179: recipe for target 'libos-regression.xml' failed
make[1]: *** [libos-regression.xml] Error 1
make[1]: Leaving directory '/home/usrk1/graphene/graphene/LibOS/shim/test/regression'
Makefile:175: recipe for target 'regression' failed
make: *** [regression] Error 2
```

Thanks

**Comment by dimakuv** [comment]
@sanmiawi I see two separate issues here:

1. A couple of normal Graphene-SGX tests failed (as indicated in your previous email). This looks like your machine doesn't have large enough RAM and/or EPC (Enclave Page Cache) to allow large enclaves. E.g., `large_mmap` creates an 8GB enclave (which of course must be backed by at least 8GB of RAM). Are you using say an Azure Confidential Compute VM with a small amount of EPC and a small amount of RAM? Or a wimpy machine like that?

2. But overall it looks like SGX and Graphene-SGX both work without GSC. Have you changed the https://github.com/oscarlab/graphene/blob/master/Tools/gsc/config.yaml.template file locally? By default, it has `https://github.com/01org/linux-sgx-driver.git` and version `sgx_driver_1.9` which is *wrong* for your system -- it has the in-kernel SGX driver. So ideally you should use something like `https://github.com/intel/SGXDataCenterAttestationPrimitives.git` and `DCAP_1.8` (hm, maybe also you'll need to change https://github.com/oscarlab/graphene/blob/master/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, but this is more complicated). See also https://graphene.readthedocs.io/en/latest/manpages/gsc.html#configuration.

If you're using Azure, Graphene already has the support for its VMs. Please read this: https://graphene.readthedocs.io/en/latest/cloud-deployment.html.

**Comment by sanmiawi** [comment]
> @sanmiawi I see two separate issues here:
> 
>     1. A couple of normal Graphene-SGX tests failed (as indicated in your previous email). This looks like your machine doesn't have large enough RAM and/or EPC (Enclave Page Cache) to allow large enclaves. E.g., `large_mmap` creates an 8GB enclave (which of course must be backed by at least 8GB of RAM). Are you using say an Azure Confidential Compute VM with a small amount of EPC and a small amount of RAM? Or a wimpy machine like that?
> 

Well I am deploying locally. The laptop I use has the following specs

- Ubuntu 18.04.5 LTS
- Memory 15.4 GiB
- Processor Intel® Core™ i7-8750H CPU @ 2.20GHz × 12 
- Graphics GeForce GTX 1050/PCIe/SSE2
- GNOME 3.28.2
- OS type64-bit
- Disk 105.2 GB


>    2. But overall it looks like SGX and Graphene-SGX both work without GSC. Have you changed the https://github.com/oscarlab/graphene/blob/master/Tools/gsc/config.yaml.template file locally? By default, it has `https://github.com/01org/linux-sgx-driver.git` and version `sgx_driver_1.9` which is _wrong_ for your system -- it has the in-kernel SGX driver.


I followed the steps at [here](https://graphene.readthedocs.io/en/latest/manpages/gsc.html#example) which say to rename `config.yaml.template` to `config.yaml`

> So ideally you should use something like `https://github.com/intel/SGXDataCenterAttestationPrimitives.git` and `DCAP_1.8` (hm, maybe also you'll need to change https://github.com/oscarlab/graphene/blob/master/Tools/gsc/templates/Dockerfile.ubuntu18.04.compile.template, but this is more complicated). See also https://graphene.readthedocs.io/en/latest/manpages/gsc.html#configuration.
> 

I deleted the generated containers
In root directory I issued 
make SGX=1 distclean
make clean
make SGX=1
selected in-kernel driver when building graphene

In Tools/gsc/
>
```
$ sudo ./gsc build --insecure-args b_docker b_docker.manifest
...

Successfully built 4daaa7b30c58
Successfully tagged gsc-b_docker-unsigned:latest
Successfully graphenized docker image b_docker into docker image gsc-b_docker-unsigned
```
>

Signed image with ./gsc sign-image b_docker enclave-key.pem

```
$ sudo ./gsc sign-image b_docker enclave-key.pem 
Step 1/7 : FROM gsc-b_docker-unsigned as unsigned_image

 ---> 6c1091a09ee3
Step 2/7 : COPY gsc-signer-key.pem /gsc-signer-key.pem

 ---> 1cb74e0c4faf
Step 3/7 : RUN python3 -B sign_manifests.py signing_order.txt

 ---> Running in 9258c2bb50c7
Signing manifests:
Traceback (most recent call last):
  File "/graphene/signer/pal-sgx-sign", line 14, in <module>
    sys.exit(main())
  File "/graphene/signer/pal_sgx_sign.py", line 920, in main
    return main_sign(args)
  File "/graphene/signer/pal_sgx_sign.py", line 826, in main_sign
    for key, val in get_trusted_files(manifest, args).items():
  File "/graphene/signer/pal_sgx_sign.py", line 248, in get_trusted_files
    targets[key] = (val, resolve_uri(val, check_exist))
  File "/graphene/signer/pal_sgx_sign.py", line 211, in resolve_uri
    'Cannot resolve ' + orig_uri + ' or the file does not exist.')
Exception: Cannot resolve file:/graphene/LibOS/glibc-2.31/benchtests/strcoll-inputs/lorem_ipsum or the file does not exist.

Finalize manifests failed due to pal-sgx-sign failure.
Removing intermediate container 9258c2bb50c7
Failed to sign graphenized image for b_docker


```

I changed  `Dockerfile.ubuntu18.04.sign_manifests.template`

```
# We sign the image in a multi-stage build to ensure that the signing key is never part of the
# final image.
FROM {{image}} as unsigned_image

COPY gsc-signer-key.pem /gsc-signer-key.pem

CMD ln -s /graphene/Pal/src/host/Linux-SGX/signer /graphene/signer

RUN python3 -B sign_manifests.py signing_order.txt

FROM {{image}}

COPY --from=unsigned_image {{working_dir}}*.sig ./
COPY --from=unsigned_image {{working_dir}}*.sgx ./

RUN rm signing_order.txt sign_manifests.py /graphene/signer/pal-sgx-sign /graphene/signer/pal_sgx_sign.py

```


Added the following copy lines to `Dockerfile.ubuntu18.04.build.template`

```
# Copy Graphene runtime and signer tools to /graphene
...


COPY --from=graphene /graphene/LibOS/glibc-2.31/benchtests/strcoll-inputs/lorem_ipsum#en_US.UTF-8 /graphene/LibOS/glibc-2.31/benchtests/strcoll-inputs/lorem_ipsum
COPY --from=graphene /graphene/LibOS/glibc-2.31/benchtests/strcoll-inputs/filelist#en_US.UTF-8  /graphene/LibOS/glibc-2.31/benchtests/strcoll-inputs/filelist
```

Replaced this
```
# Define default command
# ENTRYPOINT ["/bin/sh", "./apploader.sh"]
# CMD [{% if insecure_args %} "{{'", "'.join(cmd)}}" {% endif %}]

# ENTRYPOINT ["/bin/sh", ""]
```
with 
`
WORKDIR /`


Now the graphene image is signed successfully and runs.

Do you think these step could have compromised the security of graphene containers based on the signed image?

**Comment by dimakuv** [comment]
So you resolved your issue?

Sorry, that's just too much info :) Based on your last paragraphs, you were able to resolve the original `Exception: Failed. (Error Code = 30)` issue.

If you haven't resolved the original issue, you should have noticed this in our GSC documentation:
```
cd Tools/gsc
cp config.yaml.template config.yaml
# Adopt config.yaml to the installed Intel SGX driver and desired Graphene repository.  <-- !!! IMPORTANT !!!
```

By default, GSC uses the legacy SGX driver, see https://github.com/oscarlab/graphene/blob/fffd703b740c3c4c9e8893ab9d188b1f8a4097ef/Tools/gsc/config.yaml.template#L6.

You're using the new DCAP SGX driver, so you need to change the `config.yaml` template to something like is done here: https://github.com/oscarlab/graphene/blob/master/Tools/gsc/Makefile#L13-L21.

> Do you think these step could have compromised the security of graphene containers based on the signed image?

No, I don't think the security is compromised. From what I understand, you simply add a couple Glibc files (`lorem_ipsum` and `filelist`) to your original image. This is fine. Though I'm surprised why your original application/Docker image wants these files.
