### ISSUE TITLE
[LibOS] prepare_ipc_leader() is probably broken

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#1903]
Borys says this:

> Old code called it in fork but never in clone, even if it was used to create a new process. From what I can tell, this function is supposed to find the IPC leader process. Unfortunately there's some bug in it and uncommenting it causes some ipc messages disappearing, e.g. message about signal being sent in pipe_ocloexec regression test. Any unfortunate soul that knows IPC better than me willing to debug it? Note that all tests work with this being commented and that this function might not have been tested well previously - it was used only in fork and glibc uses clone to implement fork.

From what I understand, `prepare_ipc_leader()` is used to detect the leader of the PID + SYS-V namespace. Currently in Graphene, there is only one leader -- which is the main process in the Graphene instance. Theoretically, a child process may somehow "forget" about the main process and thus the leader, and invoke this function to send IPC messages to other processes to ask "hey, who is the IPC leader, give me its address". However, in the current scheme with only a single leader (the main process) I don't see how any child process may *not* have a leader or forget about it (recall that IPC leader info is copied on fork/clone/execve).

Maybe this function is completely useless.

**Comment by dimakuv** [comment]
Ok, it's even more contrived. In the case of this particular bug, invoking `prepare_ipc_leader()` is only a key to the actual code path where the bug (data race) happens.

Here is an example log of a bad run with my comments and some additional debug info:
```
[P2916:T2:pipe_ocloexec] Adding port (handle 0xba611e1) for process 2899 (type 0041)
[P2916:T2:pipe_ocloexec] Reconnected namespace-leader port 0xb2d40f8 (handle 0xba611e1) for process 2899 (type 0041)
... at this point P2916 created a helper thread for init of TLS-pipe with leader process...

[P2899:i1:pipe_ocloexec] IPC helper: DkStreamWaitForClient connection on port 0xba40bf3
... IPC helper thread of P2899 and temp helper thread of P2916 are doing TLS handshake ...

[P2916:T2:pipe_ocloexec] ---- shim_execve("./pipe_ocloexec" .. )

[P2916:i1:pipe_ocloexec] Listening to process ...
... IPC helper thread of P2916 starts listening on port 0xb2d40f8 ...
... THIS COLLIDES WITH TLS HANDSHAKE ON THE SAME PORT IN MBEDTLS HELPER THREAD! ...

[P2916:i1:pipe_ocloexec] Reading on port 0xb2d40f8 (handle 0xba611e1) for process 2899 (type 0041)
... P2916:i1 hangs on waiting for TLS-pipe init (happens in helper thread) ...
... ALL SUBSEQUENT IPC WITH P2916 HANGS BECAUSE IPC HELPER THREAD IS UNRESPONSIVE ...
```

**Comment by dimakuv** [comment]
In other words, the root cause is that adding invocation of `prepare_ipc_leader()` in #1902 (before it was commented out) led to a new code path in `init_ns_ipc_port() -> ...oh parent had a leader, let me connect to this leader!.. -> DkStreamOpen() -> pipe_connect() -> ...encrypted pipe establishes TLS connection with leader...`, and at this point mbedTLS's logic of TLS handshake collides with the IPC-helper-thread logic of "oh there is a new (leader) IPC port, let me start polling/reading it".

Now two threads (the mbedTLS helper thread and the IPC helper thread) try to read on the same pipe, and this corrupts mbedTLS in a way that the TLS handshake on this pipe never finishes. Therefore, all subsequent IPC communication on this pipe hangs (the subsequent communication is interestingly `connect_owner()`, not the actual send of SIGKILL).

**Comment by dimakuv** [comment]
Btw, a simple workaround is:
```
--- a/LibOS/shim/src/ipc/shim_ipc_helper.c
+++ b/LibOS/shim/src/ipc/shim_ipc_helper.c
@@ -135,19 +141,24 @@ static int init_ns_ipc_port(void) {
             return -PAL_ERRNO();
         }
+
+        /* FIXME: workaround to wait for helper SGX thread to finish TLS handshake */
+        DkThreadDelayExecution(100000); /* in microseconds */
     }
     add_ipc_port_by_id(g_process_ipc_info.ns->vmid, g_process_ipc_info.ns->pal_handle,
```

Of course, the correct fix would be to *burn IPC code and write it anew*. In particular:
1. Remove complex leader-discovery logic -- the leader is always the main (first) process, and every process knows the main process by chain of forks/clones/exec.
2. Merge `shim_ipc_info` and `shim_ipc_port` -- a lot of duplication there.
3. A lot of IPC message types won't be needed after leader simplification (I assume).

**Comment by yamahata** [comment]
+1 for managing resources in centralized manner.

This sounds like a big design change. IIUC, graphene manages resources like pid in a distributed way.
This discussion proposes to make it centralized with the main process.(or a dedicated process for it in a case that the first process exists leaving children running.)
It will greatly simplify the implementation. Also it would open a door for fctl LOCK because it would be difficult to implement advisory locking on file without centralized manager. (It's another option to pass the lock request through the host kernel, but exec emulation incur difficulty.)

**Comment by mkow** [comment]
> IIUC, graphene manages resources like pid in a distributed way.

For pids yes, but for almost everything else it's only an illusion, most of it is implemented only partially or left in a broken state. Graphene isn't actually a distributed OS, we have to fix the code to stop pretending it is :)

**Comment by dimakuv** [comment]
Yes, agreed with Isaku. It is an interesting research exercise to create a fully distributed emulation of the host OS (Linux), but that is complicated in practice. It's time for Graphene to scale back to a centralized emulation framework.

**Comment by boryspoplawski** [comment]
The problem with making the main process a unchangeable leader is that the code like ("daemonizing"):
```c
p = fork();
if (p) {
    exit();
}
```
will not ever work.

**Comment by dimakuv** [comment]
@boryspoplawski That's true. Do we want to support this? Well, I guess we should...

I still believe there must be a *single* leader at all times. And to support the daemon case, we may have a well-defined protocol where a dying process promotes the next process in line to be a new leader. With some kind of stop-the-world semantics.

**Comment by mkow** [comment]
@boryspoplawski If what you mean is that the host OS should see such a process as detached from original parent then I don't think we should support this. If you want to have a daemon then you should wrap Graphene in a daemon code, not run the daemon inside it and hope that we'll proxy this behavior to the host environment. We want to emulate the whole Linux inside Graphene without anything leaking outside. The example you mentioned doesn't make sense on non-Linux PALs, and we want to be backend-agnostic.

**Comment by boryspoplawski** [comment]
@mkow I meant that there could exist software that does it and we would like to run it under Graphene without modifications (which I guess is the main point of Graphene).

**Comment by mkow** [comment]
Ok, with this I agree, but why can't we just keep the first process alive after such a sequence? (serving just as the holder of the global state, with its existence not noticeable from the inside of Graphene namespace).

**Comment by boryspoplawski** [comment]
I guess we could, but wouldn't it be easier to just spawn some kind of IPC broker process right at the beginning? (just a random thought)

**Comment by boryspoplawski** [comment]
This is no longer a problem:
1) the offending code is already gone,
2) currently the first process is an unchangeable IPC leader.
