### ISSUE TITLE
Missing error message on lack of binary to execute

### ISSUE THREAD

**Issue by woju** [oscarlab/graphene#1905]
## Steps to reproduce
36edd357fac526467025bd6676cfd452a326191a

- create any executable (helloworld is OK),
- create and sign a manifest without `loader.exec`
- remove the ELF
- run graphene (`SGX=1 pal_loader the.manifest.sgx`)

## Expected results
graphene would inform about missing executable and abort

## Actual results
On stderr:
```
Initializing enclave failed: 1
```

In strace:
```
open("/dev/sgx/enclave", O_RDWR|O_CLOEXEC) = 4
...
ioctl(4, _IOC(_IOC_WRITE, 0xa4, 0x2, 0x8), 0x7fffdac2a2a0) = -1 EPERM (Operation not permitted)
write(2, "Initializing enclave failed: 1\n", 31) = 31
```

Getting additional information is difficult at best. One has to recompile the driver (I used DCAP commit 59be44b7b1b40e4a298b5bdfa2c589a3886cb9a6) and either manually modify the included Makefile, or invoke the Kbuild's make manually to include `CFLAGS_ioctl.o=-DDEBUG`. 

Full invocation (adjust the paths accordingly):
```
make -C /lib/modules/`uname -r`/build M=/opt/intel/SGXDataCenterAttestationPrimitives/driver/linux CFLAGS_MODULE="-I/opt/intel/SGXDataCenterAttestationPrimitives/driver/linux -I/opt/intel/SGXDataCenterAttestationPrimitives/driver/linux/include" modules CFLAGS_ioctl.o=-DDEBUG
```

Then after installing and reloading module, this is in dmesg:
```
sgx: EINIT returned 4
```

According to SDM vol 3D part 4, 40.1.4, this means `SGX_INVALID_MEASUREMENT`.

## Additional information
Adding the missing `loader.exec` fixes the issue.

IIUC `loader.exec` is being removed as part of loader rework (#1901) and the proposed solution is to use symlinks.

**Comment by mkow** [comment]
I actually already started working on this, it's planned as the 3rd part of the loader rework (I'll just disallow starting without a binary and make the error handling better).
