### ISSUE TITLE
Memory fault

### ISSUE THREAD

**Issue by moriaab** [oscarlab/graphene#191]
Hi,
I have memory fault running c++ code with Graphene-SGX on Ubuntu 16.04.3 LTS. 
The code:
#include <iostream>
int main(){
        std::cout << "Hello" << std::endl;
        return 0;
}

The manifest:
loader.preload = file:/home/moria/work/sgx/graphene/Runtime/libsysdb.so,file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6,file:/lib/x86_64-linux-gnu/libgcc_s.so.1
loader.exec = file:/home/moria/work/evm-sgx/test2/test
loader.env.LD_LIBRARY_PATH = /lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
loader.debug_type = inline
loader.syscall_symbol = syscalldb
fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:/home/moria/work/sgx/graphene/Runtime
fs.mount.bin.type = chroot
fs.mount.bin.path = /bin
fs.mount.bin.uri = file:/bin
fs.mount.usr.type = chroot
fs.mount.usr.path = /usr/lib/x86_64-linux-gnu
fs.mount.usr.uri = file:/usr/lib/x86_64-linux-gnu
fs.mount.lib1.type = chroot
fs.mount.lib1.path = /lib/x86_64-linux-gnu
fs.mount.lib1.uri = file:/lib/x86_64-linux-gnu
sys.brk.size = 32M
sys.stack.size = 4M

sgx.trusted_files.libstdc_plus=file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6
sgx.trusted_files.ld = file:/home/moria/work/sgx/graphene/Runtime/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:/home/moria/work/sgx/graphene/Runtime/libc.so.6
sgx.trusted_files.libdl = file:/home/moria/work/sgx/graphene/Runtime/libdl.so.2
sgx.trusted_files.libm = file:/home/moria/work/sgx/graphene/Runtime/libm.so.6
sgx.trusted_files.libpthread = file:/home/moria/work/sgx/graphene/Runtime/libpthread.so.0
sgx.trusted_files.victim = file:exec_victim
sgx.trusted_children.victim = file:exec_victim.sig

The error:
memory fault at 0x0 (IP = 0xb7bc87a)

**Comment by donporter** [comment]
Hi @moriaab 

I was able to reproduce the problem.  I think the bug is that libstdc++ is not being initialized properly when preloaded.

In general, preloading anything other than libsysdb.so should not be needed.  I was able to get Hello to work just fine by removing libstdc++ from the preload directive.

I'm guessing this is a proxy for a larger application issue.  If you can get by without preloading, that would be nice - let me know if you can't.

Thanks!

**Comment by mkow** [comment]
@moriaab: Could you check if this issue still occurs on the current master?

**Comment by moriaab** [comment]
Hi,
the issue is not relevant anymore.
Thank you.
