### ISSUE TITLE
Remote Attestation with EPID

### ISSUE THREAD

**Issue by damgaard22** [oscarlab/graphene#1914]
## Description of the problem
I want to do Remote Attestation using EPID as opposed to DCAP, though it seems that i can not turn DCAP off.
## Steps to reproduce
Run the ra-tls-mbedify example on an Azure Confidential Compute VM.
I added some debug printf statements around Pal/src/host/Linux-SGX/misc.db:380 to see if it generates a DCAP quote or an EPID quote.
Debug statements:
```
int _DkAttestationQuote(const PAL_PTR user_report_data, PAL_NUM user_report_data_size,
                        PAL_PTR quote, PAL_NUM* quote_size) {
    if (user_report_data_size != sizeof(sgx_report_data_t))
        return -PAL_ERROR_INVAL;

#ifdef SGX_DCAP
    /* for DCAP attestation, spid and linkable arguments are ignored */
    sgx_spid_t spid = {0};
    bool linkable = false;
    printf("Running in DCAP mode \n");
#else

    printf("Running in EPID mode \n");
    char spid_hex[sizeof(sgx_spid_t) * 2 + 1];
    ssize_t len = get_config(g_pal_state.root_config, "sgx.ra_client_spid", spid_hex,
                             sizeof(spid_hex));
```
No matter what i do it always seems to generate a DCAP quote.
It feels like i have missed something very basic and i guess i am just confused about the functionality.
If this issue fits better as a question on your mailing list, feel free to tell me so and i will delete the issue 😄 

## Expected results
It uses the presence of SPID and Linkable in the manifest to choose to do EPID, or explicitly documents how to toggle between the two.
## Actual results
It always generates a DCAP quote

**Comment by dimakuv** [comment]
Graphene is built either against the EPID-based SGX software infrastructure or against the DCAP-based SGX software infrastructure. There is no way to toggle between the two (as it would require two different software stacks on the host system installed at the same time).

From what I understand, MS Azure CC relies on DCAP only? Is it even possible to run EPID-style attestations on these machines? I had a feeling that the Azure CC stack provides DCAP only.

Also, if I remember correctly, even the format of *SGX quotes* between EPID and DCAP attestations varies significantly. So if you have a DCAP Quoting Enclave, then the produced SGX quotes will be incompatible with EPID (and Intel IAS will reject them). And the other way around.

Or am I missing something? How can one use EPID on Azure CC VMs?

**Comment by damgaard22** [comment]
Thanks for your response!

I have no problem running the intel sgx-sample-ra code and do full EPID remote attestation with IAS using my SPID and IAS Sub key. So it definitely seems possible, though it seems you make the decision to use DCAP based on where the SGX device is located.

sgx-driver/link-intel-driver.py:52
```
        if dev_path == '/dev/sgx' or dev_path == '/dev/sgx/enclave':
            f.write('\n\n#ifndef SGX_DCAP\n#define SGX_DCAP 1\n#endif\n')
``` 

When is the SGX not under on of these paths? Is it when it is under /dev/isgx?
I am still not quite sure how or when the decision for graphene to do DCAP or EPID is made.

Small clarification:
To be clear, Microsoft Remote Attestation relies on DCAP but i want to attest against IAS using EPID on a Azure CC VM, which seems possible.

**Comment by dimakuv** [comment]
Yes, you are correct that Graphene decides on whether the host system is EPID-based or DCAP-based by looking at the installed SGX driver. See e.g. here: https://github.com/oscarlab/graphene-sgx-driver/blob/3256afed71cfa7878080c31760ec089f161e6f7c/link-intel-driver.py#L14-L22.

And yes, the "older" EPID scheme is used when the detected SGX driver is the legacy driver under `/dev/isgx`.

I will need to dig deeper into this, but I agree that deciding on EPID vs DCAP based on the version of the SGX driver is a bit silly. (In my defense, at the time I implemented EPID vs DCAP, there was a lot of chaos regarding SGX drivers :))

It does sound reasonable to me that Graphene could decide between EPID vs DCAP attestations based on the options in the manifest. If `sgx.ra_client_spid` is given, then it's clearly EPID, otherwise it should be DCAP.

I will read a bit more about it and will try to implement this functionality soon (next week maybe). Thanks for the pointers! If you have any suggestions or ideas, please post them here.

**Comment by damgaard22** [comment]
Cool!

Is there anything i can do as of right now to make Graphene generate EPID quotes?

I tried to hardcode SGX_DCAP to 0, but that does not make as some structs in the autogenerated header file sgx.h is missing fields required for EPID attestation, specifically sgx_enclave_init is missing einittoken which gives the following error when making graphene:
```
sgx_framework.c:358:22: note: (near initialization for ‘param.sigstruct’)
sgx_framework.c:360:10: error: ‘struct sgx_enclave_init’ has no member named ‘einittoken’
         .einittoken = (uint64_t)token,
```

Could it work if i patched my local graphene code so that around db_misc.c:380 it always ran the EPID specific code? 

Thanks for the quick responses 😄

**Comment by dimakuv** [comment]
> Could it work if i patched my local graphene code so that around db_misc.c:380 it always ran the EPID specific code?

Yes, I think you can do this.

**Comment by damgaard22** [comment]
Alright i will experiment with this until there is another way to specify EPID usage.
Thanks for the help!

Should we keep the issue open as you work on the changes?

**Comment by dimakuv** [comment]
> Should we keep the issue open as you work on the changes?

Yes, let's keep this issue open. Also, feel free to add whatever comments / suggestions you may have.

**Comment by damgaard22** [comment]
I have not been able to patch the code in a way that lets me generate an EPID quote.
This is pretty urgent for me and some others i am working with, but we really appreciate your work!

Checking the presence of SPID and Linkable is probably the best way to choose but remember to make it explicitly clear in the online documentation :)

**Comment by dimakuv** [comment]
@damgaard22 Please check https://github.com/oscarlab/graphene/pull/1917.

**Comment by damgaard22** [comment]
Sorry, i forgot to update this issue.
I checked out the PR as soon as you made it, it works like a charm 👍 

Though a message stating if you are using EPID or DCAP during building of the manifests could be very nice.
It could just be a debug level message.

**Comment by dimakuv** [comment]
@damgaard22 It is merged now. I added a debug message on building the manifest and on starting the enclave (if Graphene is built with `DEBUG=1`).
