### ISSUE TITLE
Java cannot locate libjava.so after the commit of removing loader.exec 

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#1927]
## Description of the problem
I rebased previous working Java example to latest trunk. It cannot work anymore because of  removing loader.exec in #1901 .

In prevous `java.manitest.sgx`, I uses `loader.exec = file:/opt/jdk8/bin/java`.
After removing `loader.exec`, the executable must be java in current dir, which is a link to `/opt/jdk8/bin/java`.

Java will read `/proc/self/exe` to get it's read path, then cut `bin` off and add `lib` to make up JRE location.

current dir is mounted as `/` and `/proc/self/exe` is always `/java`. Java fails to make up JRE path and report error.

## Steps to reproduce
Run java example

## Expected results
Using commit before https://github.com/oscarlab/graphene/commit/e587869e13010e6f8b66e02cd694f24a72fe70de with `loader.exec = file:/opt/jdk8/bin/java` in java.manifest.sgx
log snap
```
[P8706:T1:java] ---- shim_readlink("/proc/self/exe",0xc652290e0,4096) = 18
[P8706:T1:java] ---- shim_access("/opt/jdk8/lib/amd64/libjava.so",F_OK) = -2
[P8706:T1:java] ---- shim_access("/opt/jdk8/jre/lib/amd64/libjava.so",F_OK) = 0
```
the return of readlink is char number of  `/opt/jdk8/bin/java`. Java removes `/bin/java` then add `lib/amd64/libjava.so` and `jre/lib/amd64/libjava.so` to find `libjava.so`.
## Actual results
Using latest  master with no `loader.exec` in java.manifest.sgx
log snap
```
[P18442:T1:java] ---- shim_readlink("/proc/self/exe",0xb12679950,4096) = 5
[P18442:T1:java] ---- shim_write(2,0xb126772b0,32) ... write
Error: could not find libjava.so[P18442:T1:java] ---- return from shim_write(...) = 32
[P18442:T1:java] ---- shim_write(2,0xb11d8f643,1) ... write
```
the return of readlink is char number of  `/java`.  Java report error  and doesn't try to find `libjava.so`.

## Additional information
I found a similar issue https://www.ibm.com/support/pages/apar/IJ15709

**Comment by dimakuv** [comment]
What Java does is... ugly.

I see two options:
1. Update to newer Java SE (at least version 8.0.6.0 where this bug was fixed).
2. Move your manifest file (and all other required files: `.sig`, `.token`, `.manifest.sgx`) inside `/opt/jdk8/bin`.

I understand that both options are not optimal...

@mkow Can we do anything else about this issue?

**Comment by bigdata-memory** [comment]
In openJDK15, it also read /proc/self/exe and compromised the paths of its dependent dynamic libraries.

**Comment by bigdata-memory** [comment]
Suggest to emulate the /proc/self/exe in LibOS/Pal accordingly.

**Comment by mkow** [comment]
@dimakuv: both options you proposed sound good IMO. I don't think we can do much about this on our side.

**Comment by glorysdj** [comment]
Is there any java sample can be run on latest graphene?

**Comment by mkow** [comment]
I don't think so, but placing the manifest right next to the executable sounds like an easy solution for this particular problem. There were other problems with Java though, please grep the issue list for "Java" or "OpenJDK" to find more.

**Comment by glorysdj** [comment]
@mkow Thanks.
Java has its own directory layout like:
/opt/jdk
├── bin
      ├── java
├── include
├── jre
├── lib
 
So I need to put Makefile/manifest into /opt/jdk/bin to make java executable on Graphene?  

BTW. What are "other problems with Java". Is there any doc listing the known issues of Java on Graphene?
Thanks a lot!

**Comment by mkow** [comment]
> So I need to put Makefile/manifest into /opt/jdk/bin to make java executable on Graphene?

For Linux PAL only the manifest, for Linux-SGX it will be manifest.sgx, signature and token.

> BTW. What are "other problems with Java". Is there any doc listing the known issues of Java on Graphene?

See my reply above ;) "please grep the issue list for "Java" or "OpenJDK" to find more."

**Comment by llly** [comment]
> > So I need to put Makefile/manifest into /opt/jdk/bin to make java executable on Graphene?
> 
> For Linux PAL only the manifest, for Linux-SGX it will be manifest.sgx, signature and token.
> 

@mkow This doesn't work. java still don't try to load libjava.so at any location. If java logic is not changed, the fix is emulating the /proc/self/exe in LibOS/Pal accordingly. Otherwise revert the `loader.exec` change.

**Comment by dimakuv** [comment]
> java still don't try to load libjava.so at any location.

Why doesn't it work? If you have something like this in the manifest:
```
fs.mount.etc.type = chroot
fs.mount.etc.path = /opt
fs.mount.etc.uri = file:/opt
```

then `/proc/self/exec` should result in `/opt/jdk/bin/java`, no? What is the Graphene log, what size does it return?

You should also run Graphene something like this:
`./pal_loader /opt/jdk/bin/java <...Java arguments...>`

What happens if you do that?

**Comment by llly** [comment]
You are right. It works. I didn't realize command  `./pal_loader /opt/jdk/bin/java`.

**Comment by mkow** [comment]
Should we close the issue then?

btw. All such issues will be greatly simplified soon, I'm working on introducing one central manifest, so that most of the workloads (like this one) will get much simpler to configure.
