### ISSUE TITLE
How can I get memory usage inside of enclave or LibOS?

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1941]
Encountered an `LibOS OOM` in my application. Wondering how to get memory usage of LibOS with Graphene

**Comment by dimakuv** [comment]
I don't think we have any stats like this to print out in Graphene. You could try debugging with GDB and looking at e.g. https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/LibOS/shim/src/bookkeep/shim_vma.c#L1134

But I can't think of any simple way to check the overall consumption of LibOS memory. @boryspoplawski any suggestions?

Also, you can calculate how much LibOS memory you have: `sgx.enclave_size - 64MB - loader.pal_internal_mem_size - <size of all app executables>`. As a rule of thumb, if you specified say 4GB of enclave size, the LibOS probably uses about 3.8GB of this enclave memory.

**Comment by boryspoplawski** [comment]
Other than using https://github.com/oscarlab/graphene/blob/ec270d07616f30a1bb5bdc83e193ff6d33c8f016/LibOS/shim/src/bookkeep/shim_vma.c#L1383 in gdb or manually inserting it in some places in code, I don't think we have any way to get memory usage in LibOS atm.

**Comment by qiyuangong** [comment]
Thank you @dimakuv and @boryspoplawski for giving this detailed suggestion. 👍 

I will try it during debug.

Will graphene or SGX support this feature in future release?

**Comment by dimakuv** [comment]
@qiyuangong We could add this in the future, yes.

You would like to have something like "Peak Resident Set Size (Working Set Size)" printed out at the end of the run (including abnormal termination)?

**Comment by qiyuangong** [comment]
Thank you @dima

> @qiyuangong We could add this in the future, yes.
> 
> You would like to have something like "Peak Resident Set Size (Working Set Size)" printed out at the end of the run (including abnormal termination)?

Yes. I think we need it during memory related debug and tuning. In current stage, I can change this line and add debug output. 

But, in customer view, especially in cluster env, they may want to know how much memory is already used by application, such that they can determinate how many tasks/workloads should be assign to this application.

**Comment by mkow** [comment]
I believe all the question here were answered, can we close this issue now?

btw. @qiyuangong: Please use issues only to report bugs or send feature requests, for general questions/support we use our mailing list ;)

**Comment by qiyuangong** [comment]
Thank you, @mkow 

Will propose features requests through mailing list. Issue closed.
