### ISSUE TITLE
Does graphene support application written in C++

### ISSUE THREAD

**Issue by sudharkrish** [oscarlab/graphene#195]
I have a C++ application, and some of the code may also need to be packaged as a separate library.
Currently all of the code is C++ and built as part of one whole application.

I was able to build the C++ code by using some of the makefiles as reference under the path:
LibOS/shim/test/apps/helloworld

Modified Makefile to use g++ instead of gcc.

Needed to use g++ compiler, for some of the C++ operators such as new and delete, that were part of the code being built.

It builds fine, but when trying to run the application, it fails, with the following error:

helloworld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory^M

Can you let me know, if there is any quick way to resolve this, (OR) would it be a huge request of adding C++ support to Graphene, similar to glibc-2.19 which is currently supported by Graphene.

Here is the full log, when running the application:

SGX=1 ./pal_loader helloworld
manifest file: file:helloworld.manifest.sgx
enclave created:
    base:         0x0000000000000000
    size:         0x0000000040000000
    attr:         0x0000000000000007
    xfrm:         0x0000000000000007
    ssaframesize: 1
    isvprodid:    0x00000000
    isvsvn:       0x00000000
adding page  to enclave: 000000003ffff000 [REG:R--] (manifest) measured
adding pages to enclave: 000000003fff6000-000000003fffe000 [REG:RW-] (ssa)
adding pages to enclave: 000000003fff1000-000000003fff5000 [TCS:---] (tcs)
adding pages to enclave: 000000003ffec000-000000003fff0000 [REG:RW-] (tls)
adding pages to enclave: 000000003ffdb000-000000003ffeb000 [REG:RW-] (stack)
adding pages to enclave: 000000003ffca000-000000003ffda000 [REG:RW-] (stack)
adding pages to enclave: 000000003ffb9000-000000003ffc9000 [REG:RW-] (stack)
adding pages to enclave: 000000003ffa8000-000000003ffb8000 [REG:RW-] (stack)
adding pages to enclave: 000000003bd76000-000000003bda2000 [REG:R-X] (code) measured
adding pages to enclave: 000000003bfa2000-000000003bfa4000 [REG:RW-] (data) measured
adding pages to enclave: 000000003bfa4000-000000003ffa7000 [REG:RW-] (bss)
adding pages to enclave: 0000000000400000-0000000000411000 [REG:RWX] (code) measured
adding pages to enclave: 0000000000610000-0000000000612000 [REG:RW-] (data) measured
adding pages to enclave: 0000000000612000-000000003bd75000 [REG:RWX] (free)
adding pages to enclave: 0000000000010000-0000000000400000 [REG:RWX] (free)
enclave initializing:
    enclave id:   0x000000003ffff000
    enclave hash: 80 a2 c1 89 d1 75 bc a1 86 e3 2c 8d 59 e3 a8 04 65 3e 10 ad 13 28 eb 04 71 04 da 5c 0b 70 9c 1b
Get sealing key: 77df6d648451a5f807622e85ec2ba229
enclave (software) key hash: f8492de34121b2a3e6d01a701cc2675890a1e08d8b7fc9c24e61edf41efbd775
trusted: [1] b24e165f27efaef2a92b615735364f6be5013b6c075d107f077811a023943c72 file:helloworld
trusted: [2] 849de331c0624e6fdda0b110509578fae6c9a7d47c4a167ff83c514952e5b4f6 file:../../../../../Runtime/libsysdb.so
trusted: [3] 02b7c001f586a3db4a9ce5a4679037b54e6fe586c01786bb4efd9ffb58595852 file:../../../../../Runtime/ld-linux-x86-64.so.2
trusted: [4] d3043c8b12ea657c81339816f9adcb2ba746a738653af01a9e8c3e48a42fb63e file:../../../../../Runtime/libc.so.6
trusted: [5] de8f629f00430da586526571a4b9f05532bd5a34e1d4a9316b3884771547591e file:../../../../../Runtime/libm.so.6
trusted: [6] ac709382a064c4d6e7879f01f7947cd9cbe7ae7141b118e52d02fb966bafb55a file:../../../../../Runtime/libpthread.so.0
trusted: [7] 3fe988797911e25cb62afce73d416552d553f719233e41e7fec555e0bf1df8df file:/lib/x86_64-linux-gnu/libcrypt.so.1
trusted: [8] 50ed213d2b82cc88d2e7a5f99981106b932f4343327a08765f6f6c7f04e8ba72 file:../../../../../Runtime/libuprotfs.so
allowed: file:/var/run/secrets
[P15352] set tcb to 0x3ffe94c8
[P15352] host: Linux-SGX
[P15352] initial random value: 54aec5439975d358
[P15352] allocate internal heap at 0x3b9a0000 - 0x3baa0000
[P15352] User space range given from PAL: 0x10000-0x3baa0000
[P15352] setting initial heap to 0x10000-0x3baa0000
[P15352] heap top adjusted to 0x1b218000
[P15352] bkeep_mmap: 0x3b9a0000-0x3b9aa000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b214000-0x1b218000
[P15352] bkeep_mmap: 0x1b214000-0x1b218000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b20f000-0x1b214000
[P15352] bkeep_mmap: 0x1b20f000-0x1b214000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b208000-0x1b20f000
[P15352] bkeep_mmap: 0x1b208000-0x1b20f000
[P15352] shim loaded at 0x3baa1000, ready to initialize
[P15352] bkeep_mmap: 0x3ffff000-0x40000000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b207000-0x1b208000
[P15352] bkeep_mmap: 0x1b207000-0x1b208000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b206000-0x1b207000
[P15352] bkeep_mmap: 0x1b206000-0x1b207000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b205000-0x1b206000
[P15352] bkeep_mmap: 0x1b205000-0x1b206000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b203000-0x1b205000
[P15352] bkeep_mmap: 0x1b203000-0x1b205000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b200000-0x1b203000
[P15352] bkeep_mmap: 0x1b200000-0x1b203000
[P15352] mounting default root filesystem
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b1fe000-0x1b200000
[P15352] bkeep_mmap: 0x1b1fe000-0x1b200000
[P15352] bkeep_unmmap: 0x1b1fe000-0x1b200000
[P15352] Querying a directory; I count 35 links.
[P15352] mounting as proc filesystem: /proc
[P15352] mounting as dev filesystem: /dev
[P15352] mounting as chroot filesystem: from dev:tty to /dev
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b1ff000-0x1b200000
[P15352] bkeep_mmap: 0x1b1ff000-0x1b200000
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b1fe000-0x1b1ff000
[P15352] bkeep_mmap: 0x1b1fe000-0x1b1ff000
[P15352] adding port (handle 0x3bfac690) for process 0 (type 0001)
[P15352] creating pipe: pipe.srv:1631380950
[P15352] adding port (handle 0x3bfacf90) for process 0 (type 0002)
[P15352] walk_thread_list(callback=0x3bae1552)
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b1fd000-0x1b1fe000
[P15352] bkeep_mmap: 0x1b1fd000-0x1b1fe000
[P15352] allocated pid: 1
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1b1f8000-0x1b1fd000
[P15352] bkeep_mmap: 0x1b1f8000-0x1b1fd000
[     1] mounting as chroot filesystem: from file:../../../../../Runtime to /lib
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f6000-0x1b1f8000
[     1] bkeep_mmap: 0x1b1f6000-0x1b1f8000
[     1] bkeep_unmmap: 0x1b1f6000-0x1b1f8000
[     1] Querying a directory; I count 24 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f7000-0x1b1f8000
[     1] bkeep_mmap: 0x1b1f7000-0x1b1f8000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f5000-0x1b1f7000
[     1] bkeep_mmap: 0x1b1f5000-0x1b1f7000
[     1] bkeep_unmmap: 0x1b1f5000-0x1b1f7000
[     1] Querying a directory; I count 24 links.
[     1] mounting as chroot filesystem: from file:/lib/x86_64-linux-gnu to /lib/x86_64-linux-gnu
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f5000-0x1b1f7000
[     1] bkeep_mmap: 0x1b1f5000-0x1b1f7000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f2000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f2000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1f5000-0x1b1f7000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1ed000-0x1b1f2000
[     1] bkeep_mmap: 0x1b1ed000-0x1b1f2000
[     1] bkeep_unmmap: 0x1b1f2000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1ed000-0x1b1f2000
[     1] Querying a directory; I count 207 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f5000-0x1b1f7000
[     1] bkeep_mmap: 0x1b1f5000-0x1b1f7000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f2000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f2000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1f5000-0x1b1f7000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1ed000-0x1b1f2000
[     1] bkeep_mmap: 0x1b1ed000-0x1b1f2000
[     1] bkeep_unmmap: 0x1b1f2000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1ed000-0x1b1f2000
[     1] Querying a directory; I count 207 links.
[     1] mounting as chroot filesystem: from file:/var/run/secrets to /var/run/secrets
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f6000-0x1b1f7000
[     1] bkeep_mmap: 0x1b1f6000-0x1b1f7000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f4000-0x1b1f6000
[     1] bkeep_mmap: 0x1b1f4000-0x1b1f6000
[     1] bkeep_unmmap: 0x1b1f4000-0x1b1f6000
[     1] Querying a directory; I count 3 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f4000-0x1b1f6000
[     1] bkeep_mmap: 0x1b1f4000-0x1b1f6000
[     1] bkeep_unmmap: 0x1b1f4000-0x1b1f6000
[     1] Querying a directory; I count 3 links.
[     1] mounting as chroot filesystem: from file:/bin to /bin
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f4000-0x1b1f6000
[     1] bkeep_mmap: 0x1b1f4000-0x1b1f6000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f1000-0x1b1f4000
[     1] bkeep_mmap: 0x1b1f1000-0x1b1f4000
[     1] bkeep_unmmap: 0x1b1f4000-0x1b1f6000
[     1] bkeep_unmmap: 0x1b1f1000-0x1b1f4000
[     1] Querying a directory; I count 160 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f4000-0x1b1f6000
[     1] bkeep_mmap: 0x1b1f4000-0x1b1f6000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f1000-0x1b1f4000
[     1] bkeep_mmap: 0x1b1f1000-0x1b1f4000
[     1] bkeep_unmmap: 0x1b1f4000-0x1b1f6000
[     1] bkeep_unmmap: 0x1b1f1000-0x1b1f4000
[     1] Querying a directory; I count 160 links.
[     1] mounting as chroot filesystem: from file:/usr to /usr
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f5000-0x1b1f6000
[     1] bkeep_mmap: 0x1b1f5000-0x1b1f6000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f3000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f3000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1f3000-0x1b1f5000
[     1] Querying a directory; I count 9 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f3000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f3000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1f3000-0x1b1f5000
[     1] Querying a directory; I count 9 links.
[     1] mounting as chroot filesystem: from file: to /etc
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f3000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f3000-0x1b1f5000
[     1] bkeep_unmmap: 0x1b1f3000-0x1b1f5000
[     1] Querying a directory; I count 35 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f3000-0x1b1f5000
[     1] bkeep_mmap: 0x1b1f3000-0x1b1f5000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f1000-0x1b1f3000
[     1] bkeep_mmap: 0x1b1f1000-0x1b1f3000
[     1] bkeep_unmmap: 0x1b1f1000-0x1b1f3000
[     1] Querying a directory; I count 35 links.
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b1f2000-0x1b1f3000
[     1] bkeep_mmap: 0x1b1f2000-0x1b1f3000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1b0f1000-0x1b1f2000
[     1] bkeep_mmap: 0x1b0f2000-0x1b1f2000
[     1] bkeep_mprotect: 0x1b0f2000-0x1b1f2000
[     1] bkeep_mmap: 0x1b0f1000-0x1b0f2000
[     1] bkeep_mmap: 0x1b0f1000-0x1b0f2000
[     1] allocated stack at 0x1b0f2000 (size = 1048576)
[     1] adding file:helloworld as runtime object loaded at 0x400000-0x612000
[     1] bkeep_mmap: 0x400000-0x411000
[     1] bkeep_mmap: 0x610000-0x612000
[     1] brk area: 0x1cde000 - 0x1cdf000
[     1] brk reserved area: 0x1cdf000 - 0x5cde000
[     1] bkeep_mmap: 0x1cde000-0x1cdf000
[     1] bkeep_mmap: 0x1cdf000-0x5cde000
[     1] search interpreter: /lib/ld-linux-x86-64.so.2
[     1] bkeep_mmap: 0x3ba9c000-0x3baa0000
[     1] find unmapped vma between 0x10000-0x1b218000
[     1] get unmapped: 0x1aece000-0x1b0f1000
[     1] bkeep_mmap: 0x1aece000-0x1b0f1000
[     1] bkeep_mprotect: 0x1aeef000-0x1b0ee000
[     1] bkeep_mmap: 0x1aece000-0x1aeef000
[     1] bkeep_mmap: 0x1b0ee000-0x1b0f1000
[     1] bkeep_mmap: 0x1b0ee000-0x1b0f0000
[     1] bkeep_mprotect: 0x1b0ee000-0x1b0f0000
[     1] bkeep_mmap: 0x1b0f0000-0x1b0f1000
[     1] bkeep_mmap: 0x1b0f0000-0x1b0f1000
[     1] add a library for gdb: file:../../../../../Runtime/ld-linux-x86-64.so.2
[     1] shim process initialized
[     1] ---- shim_brk(0x0) = 0x1cde000
[     1] ---- shim_uname(0x1b1f0b5a) = 0
[     1] ---- shim_mmap(0x0,8192,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANON,-1,0) ...
[     1] find unmapped vma between 0x10000-0x1b218000
[P15352] set tcb to 0x3ffd9a40
[     1] get unmapped: 0x1aecc000-0x1aece000
[P15352] ipc helper thread started
[P15352] find unmapped vma between 0x10000-0x1b218000
[P15352] get unmapped: 0x1aec7000-0x1aecc000
[     1] bkeep_mmap: 0x1aecc000-0x1aece000
[     1] ---- return from shim_mmap(...) = 0x1aecc000
[     1] ---- shim_open("/lib/tls/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[     1] ---- return from shim_open(...) = -2
[P15352] bkeep_mmap: 0x1aec7000-0x1aecc000
[     1] ---- shim_stat("/lib/tls",0x1b1f05b0) = -2
[P15352] allocated stack at 0x1aec8000 (size = 16384)
[     1] ---- shim_open("/lib/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[P15352] listen to process 0 on port 0x1b1fe0b0 (handle 0x3bfacf90, type 0002)
[P15352] listen to process 0 on port 0x1b1fe038 (handle 0x3bfac690, type 0001)
[     1] ---- return from shim_open(...) = -2
[     1] Stat: Returning link count 24
[     1] ---- shim_stat("/lib",0x1b1f05b0) = 0
[     1] ---- shim_open("/lib/x86_64-linux-gnu/tls/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[     1] ---- return from shim_open(...) = -2
[     1] ---- shim_stat("/lib/x86_64-linux-gnu/tls",0x1b1f05b0) = -2
[     1] ---- shim_open("/lib/x86_64-linux-gnu/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[     1] ---- return from shim_open(...) = -2
[     1] Stat: Returning link count 207
[     1] ---- shim_stat("/lib/x86_64-linux-gnu",0x1b1f05b0) = 0
[     1] ---- shim_open("/home/skris14/graphene_latest/graphene/Runtime/etc/ld.so.cache",O_RDONLY|2000000,0001) ...
[     1] ---- return from shim_open(...) = -2
[     1] ---- shim_open("/home/skris14/graphene_latest/graphene/Runtime/lib/tls/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[     1] ---- return from shim_open(...) = -2
[     1] ---- shim_stat("/home/skris14/graphene_latest/graphene/Runtime/lib/tls",0x1b1f05b0) = -2
[     1] ---- shim_open("/home/skris14/graphene_latest/graphene/Runtime/lib/libstdc++.so.6",O_RDONLY|2000000,3303600530) ...
[     1] ---- return from shim_open(...) = -2
[     1] ---- shim_stat("/home/skris14/graphene_latest/graphene/Runtime/lib",0x1b1f05b0) = -2
helloworld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
[     1] ---- shim_writev(2,0x1b1f0270,10) = 124
[     1] ---- shim_exit_group (returning 127)
[     1] now kill other threads in the process
[     1] walk_thread_list(callback=0x3bb4034a)
[     1] now exit the process
[     1] ipc broadcast: IPC_CLD_EXIT(1, 1, -127)
[     1] found port 0x1b1fe0b0 (handle 0x3bfacf90) for process 0 (type 0002)
[     1] found port 0x1b1fe038 (handle 0x3bfac690) for process 0 (type 0001)
[     1] parent not here, need to tell another process
[     1] ipc broadcast: IPC_CLD_EXIT(1, 1, -127)
[     1] found port 0x1b1fe0b0 (handle 0x3bfacf90) for process 0 (type 0002)
[     1] found port 0x1b1fe038 (handle 0x3bfac690) for process 0 (type 0001)
[     1] this is the only thread
[     1] exiting ipc helper
[P15352] ipc helper thread terminated
[     1] deleting port 0x1b1fe0b0 (handle 0x3bfacf90) for process 0
[     1] deleting port 0x1b1fe038 (handle 0x3bfac690) for process 0
[     1] process 15352 successfully terminated

**Comment by sudharkrish** [comment]
I had to add libstdc++ and libgcc under /usr/lib and /lib folders on my host system as trusted files in my manifest file. With that change, the application works fine.

If the above resolution is acceptable, this issue can be CLOSED.

**Comment by donporter** [comment]
In general, it is fine to add required libraries to a manifest.  I'm glad that is all it took.

More generally, a library should only need modifications to run on Graphene if it issues system call instructions or uses TLS, which should be aware of Graphene.
