### ISSUE TITLE
Reduce/filter debug log in debug mode

### ISSUE THREAD

**Issue by qiyuangong** [oscarlab/graphene#1950]
During debugging a long-time running job (crash after a few hours in stress test), my debug log file becomes extremely large (25GB for now, and it's still keep growing). Sad thing is that most logs are useless for us, such as `shim_sched_yield() = 0` and `shim_clock_gettime` etc. 

Any idea about filter out unwanted logs/events?

**Comment by mkow** [comment]
We could implement some filtering, but I think as a quick workaround you could just pipe it through `grep` with `-v`, e.g. `grep -v 'shim_sched_yield\(\)'`.

**Comment by qiyuangong** [comment]
> We could implement some filtering, but I think as a quick workaround you could just pipe it through `grep` with `-v`, e.g. `grep -v 'shim_sched_yield\(\)'`.

Thanks, @mkow . I will try it. 👍

**Comment by mkow** [comment]
FYI: #1979 may help in your case.

**Comment by qiyuangong** [comment]
> FYI: #1979 may help in your case.

Thanks 👍 
Pls close this issue after 1979 is merged.
