### ISSUE TITLE
INVALID SIGNATURE when running under sgx.debug=0

### ISSUE THREAD

**Issue by damgaard22** [oscarlab/graphene#1952]
## Description of the problem
My enclave works fine when sgx.debug=1 but it fails to launch when sgx.debug=0.
It is init_enclave() that fails, when inserting some debug statements i find that it is the INLINE_SYSCALL:
` int ret = INLINE_SYSCALL(ioctl, 3, g_isgx_device, SGX_IOC_ENCLAVE_INIT, &param);`
at `Pal/src/host/Linux-SGX/sgx_framework.c:383`
The error switch under that line returns `INVALID_SIGNATURE`

I have a commercial license and i am signing with a key that is whitelisted. Furthermore when i was not signing with the right key Graphene failed in the signing stage as expected, so it does not seem to be a problem with Launch Enclave or the Whitelist.

My main question is what signature the error message is referring to?
I sign 3 enclaves and see 3 different signatures when generating the sigstruct for each, though it is all the same MRSIGNER and modulus.

Have you seen this before or do you have any idea how i can fix this/debug further 😄 
(Thanks for fixing the EPID attestation btw, it is awesome!)

## Expected results

The enclave starts and runs in the same way as if it had been built with sgx.debug=1

## Actual results

The enclave fails to start and fails with the error message:
`Initializing enclave failed: 1 
load_enclave() failed with error -1`

**Comment by dimakuv** [comment]
Do I understand correctly that you add a line `sgx.debug = 0` to the `manifest.template` file (which is the correct thing to do; do *not* add this line to `manifest` or `manifest.sgx` files!)

Also, could it be that you're using a buggy version of SGX PSW and the Quoting Enclave? There was a bug with "invalid signature" in some versions of the PSW: https://download.01.org/intel-sgx/sgx-linux/2.9.1/docs/Intel_SGX_PSW_Release_Notes_Linux_2.9.1_Open_Source.pdf (search for "invalid signature").

Finally, does `dmesg` say anything? Graphene fails on `EINIT` of the enclave, i.e., this is the SGX driver complaining that the MRSIGNER doesn't correspond to the one specified in the SIGSTRUCT (`.sig` file).

**Comment by damgaard22** [comment]
Got it working now!

I basically reinstalled and signed everything again.
Thanks for the help, closing this issue
