### ISSUE TITLE
Internal memory error when running uwsgi on Graphene-SGX

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#196]
I'm trying to run uwsgi on Graphene-SGX. It fails with repeatedly printing "Internal memory fault at 0x0 (IP = +0x9d0e6, VMID = 3799327262, TID = 1)".

I've attached the output when running this with debug = inline and strace.

[uwsgi.txt](https://github.com/oscarlab/graphene/files/1877120/uwsgi.txt)

[uwsgi.manifest.sgx.txt](https://github.com/oscarlab/graphene/files/1877122/uwsgi.manifest.sgx.txt)

**Comment by donporter** [comment]
Hi @thomasknauth 

Are you still having this issue on the latest master?  Also, do you have any additional instructions to reproduce the issue? (what distro, version number, etc)

The thing that is most likely suspicious is this:

```
[pid  8845] --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x562165deb870} ---
[pid  8845] rt_sigreturn({mask=[]})     = 3
[pid  8845] --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x562165deb870} ---
[pid  8845] rt_sigreturn({mask=[]})     = 3
[pid  8845] --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x562165deb870} ---
[pid  8845] rt_sigreturn({mask=[]})     = 3
```
I am guessing this binary may have an instruction that isn't well-handled in SGX, and things eventually try to access 0 as it gets more confused.

This address seems to repeat; any chance you can figure out what instruction is there (e.g., via a disassembler like objdump on the binary, or perhaps looking at this address with gdb attached)?  

Thanks!

**Comment by thomasknauth** [comment]
Not sure if it helps. Running in gdb, I see a series of SIGILLs followed by a SIGBUS.

```
Thread 1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
0x00000000669db568 in ?? ()
CPUID bypassed. Ignore this exception.

Thread 1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
0x00000000669db62f in ?? ()
CPUID bypassed. Ignore this exception.

Thread 1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
0x00000000669db644 in ?? ()
CPUID bypassed. Ignore this exception.

Thread 1 "pal-Linux-SGX" received signal SIGILL, Illegal instruction.
0x00000000669db6ac in ?? ()
CPUID bypassed. Ignore this exception.

Thread 1 "pal-Linux-SGX" received signal SIGBUS, Bus error.
0x000000007bb3eb58 in shim_do_sigprocmask (how=1, set=0x68e31cd0, oldset=0x0) at sys/shim_sigaction.c:124
124             __signotset(&set_tmp, &set_tmp, set);
(gdb) p $_siginfo
p $_siginfo
$1 = {si_signo = 7, si_errno = 0, si_code = 2, _sifields = {_pad = {0, 0, 64124640, 0, 31095616, 32648, -964229872, 32765, 31095600, 32648, -964229856,
      32765, 31095664, 32648, 964229857, -32766, 0, 0, 0, 0, 0, 0, 155968560, 0, 46553744, 0, -964229132, 32765}, _kill = {si_pid = 0, si_uid = 0},
    _timer = {si_tid = 0, si_overrun = 0, si_sigval = {sival_int = 64124640, sival_ptr = 0x3d276e0}}, _rt = {si_pid = 0, si_uid = 0, si_sigval = {
        sival_int = 64124640, sival_ptr = 0x3d276e0}}, _sigchld = {si_pid = 0, si_uid = 0, si_status = 64124640, si_utime = 133554653768974336,
      si_stime = -4141335766066233464}, _sigfault = {si_addr = 0x0, _addr_lsb = 64124640, _addr_bnd = {_lower = 0x7f8801da7b40,
        _upper = 0x7ffdc6870510}}, _sigpoll = {si_band = 0, si_fd = 64124640}}}
```

**Comment by donporter** [comment]
If you can get us the disassembly of the cpuid + a few more instructions afterwards (ideally, to the faulting instruction), it may tell us what is wrong.  For example, our cpuid emulation may not be setting a value correctly in one of the registers, which is then used as an offset to something.

**Comment by thomasknauth** [comment]
https://github.com/oscarlab/graphene/blob/master/LibOS/shim/include/shim_signal.h#L16 this macro is wrong. Should be (8 * sizeof(unsigned long). Then the error is gone.

**Comment by donporter** [comment]
Thanks @thomasknauth !  This seems like a clear, no-brainer fix to me.

Out of curiosity, how did you zero in on this issue?  Any chance you have a good, smaller unit test for this?

**Comment by thomasknauth** [comment]
Just starring at the code of __signotset and trying to understand what it does really. Luckily, cause and effect were close in space and time. I believe anything that results in __signotset (or variants) getting called would cause an issue and could be used as a test case. Don't have anything smaller though.
