### ISSUE TITLE
App fails with error "forkfd: Cannot assign requested address" after 822 runs.

### ISSUE THREAD

**Issue by shamamathew** [oscarlab/graphene#1960]
## Description of the problem
App fails with error "forkfd: Cannot assign requested address" after 822 runs.

## Expected results
Tests continue to run without failures

## Actual results
App fails with error "forkfd: Cannot assign requested address" after 822 runs.

**Comment by dimakuv** [comment]
Thanks @shamamathew for submitting the issue. I can assert that this failure indeed happens.

I assume that this is due to some hard-coded limit in Graphene on the number of open FDs, spawned processes... Something like this. Or maybe a memory leak that we hit after 822 spawned processes.

**Comment by dimakuv** [comment]
This looks relevant: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_getrlimit.c#L25-L29

Graphene has an internal limit on the maximum number of opened file descriptors -- `900` FDs in total.

It seems that when a child process terminates, there is no freeing of the FD. So a kind of FD leak. Need to dig deeper.

**Comment by dimakuv** [comment]
My simple test shows that there is no (apparent) leak of the forked processes:
```c
#define _XOPEN_SOURCE 700
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>

int main(int argc, const char** argv, const char** envp) {
    int iterations = argc > 1 ? atoi(argv[1]) : 10000;
    for (int i = 0; i < iterations; i++) {
        pid_t child_pid = fork();

        if (child_pid == 0) {
            /* child simply prints its number and exits */
            printf("iteration %d: child is OK\n", i);
            return 0;
        } else if (child_pid > 0) {
            /* parent waits for child termination */
            int status;
            pid_t pid = wait(&status);
            if (pid < 0) {
                perror("wait failed");
                return 1;
            }
            if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
                puts("child termination status is not zero");
                return 1;
            }
        } else {
            /* error */
            perror("fork failed");
            return 1;
        }
    }

    puts("TEST OK");
    return 0;
}
```

It correctly forks 10,000 child processes under Graphene.

**Comment by dimakuv** [comment]
Just to make it more visible: this issue is fixed by https://github.com/oscarlab/graphene/pull/1980.
