### ISSUE TITLE
Giving access to [‘/tmp’, ‘/var/tmp’, ‘/usr/tmp’, ‘/’]“. 

### ISSUE THREAD

**Issue by noodlehair-git** [oscarlab/graphene#1968]
I was trying to run my python project with Graphene which throws this error ```“Error in eval: [Errno 2] No usable temporary directory found in [‘/tmp’, ‘/var/tmp’, ‘/usr/tmp’, ‘/’]“ ```. Can you please guide me on how should I modify my ```python.manifest.template``` to give the required access/permissions?

**Comment by dimakuv** [comment]
This should work: https://github.com/oscarlab/graphene/blob/master/Examples/python-simple/python.manifest.template#L49-L52

**Comment by noodlehair-git** [comment]
I am using this manifest file only! This block exists in my current manifest.

**Comment by dimakuv** [comment]
Oh, this is surprising. What is the Python script you're trying to run?

Could you check the output with `loader.debug_type = "inline"` in the manifest? (Or alternatively just do `make clean; make DEBUG=1`). Usually the produced log hints to an underlying problem.

**Comment by noodlehair-git** [comment]
I was able to overcome this error by using ```sgx.allowed_files.tmp = file:/tmp```.

I want to run something like the client script here : https://stem.torproject.org/tutorials/to_russia_with_love.html#using-pycurl that initiates Tor. But when I launch Tor with ```tor_process = stem.process.launch_tor_with_config(
    config = {
      'SocksPort': str(SOCKS_PORT),
    }
  )```, it gives a ```Broken Pipe``` error. I have specified all required libraries in the manifest though. Any advice on that?
