### ISSUE TITLE
Python: memory fault when running `statsmodels` 

### ISSUE THREAD

**Issue by mainarke** [oscarlab/graphene#1976]
## Description of the problem
I try to run the `adfuller` function of the `statsmodels` Python module with Graphene (without SGX). The code runs fine on Ubuntu 18.04 without Graphene. When running with Graphene (`./pal_loader python.manifest code.py`), it terminates unexpectedly. 

I tried to run it with DEBUG mode, and collected the traces. Near the end, I see this:

```
[P2041:T1:python3] ---- shim_mmap(0x0,33554432,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS,-1,0) ... mmap
[P2041:T1:python3] ---- return from shim_mmap(...) = 0x3a92612fb000
[P2041:T1:python3] ---- shim_mbind(0x3a92612fb000,0x2000000,1,0x0,0x0,0) = 0
[P2041:T1:python3] memory fault at 0x3a92ac1b46b0 (IP = 0x3a92a9274591)
[P2041:T1:python3] signal 7 handled
[P2041:T1:python3] run signal handler 0x7fa75bad5f00 (7, 0x7fa75bb6d200, 0x7fa75bb6d288)
[P2041:T1:python3] killed by signal 7
```

I suspect this was the reason. Does anyone know what this means? Thanks for the help!

The code is listed below. The DEBUG log is also attached.
[test_adfuller.txt](https://github.com/oscarlab/graphene/files/5558710/test_adfuller.txt)

## Steps to reproduce

Python Code:

```
import numpy as np
from statsmodels.tsa.stattools import adfuller

print ("before!")
arr = np.arange(0,100)
result = adfuller(arr)
print ("after!")

```

Python version: 3.6.9

run : `./pal_loader python.manifest code.py`

If I comment out the `adfuller` line, it runs OK with Graphene.

## Expected results
The code finishes normally.

## Actual results
The code terminates unexpectedly.

**Comment by dimakuv** [comment]
@mainarke If this is still relevant for you, could you check on the latest Graphene version? Otherwise I will close this issue after a couple days, assuming the issue was fixed.

**Comment by mkow** [comment]
I tested it without SGX on 20.04 and it works with current master. Under SGX it required more complex configuration, so I skipped it (and it seems the reporter ran it without SGX).
I'm closing this issue. @mainarke: Please reopen/ping us if it's still relevant.
