### ISSUE TITLE
Patching TOML source files issue

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#1981]
## Description of the problem
The build failed after pulling due to the previous patched source files extracted from external TOML repo that already got patched or changed, it prompts the following messages.
```
...
patch -p1 -l < toml.patch || exit 255
patching file toml.c
Reversed (or previously applied) patch detected!  Assume -R? [n]
...
```
This issue can be mitigated by run command ``` make distclean``` first, but it would be more friendly with no need to recompile other source files.
## Steps to reproduce
It is on the latest revision: c06e72288e0780277cb0f9ab7d570cadf5d3e386 (Nov.18)

## Expected results
Patching on the toml source files specified by checksums successfully with no need of "make distclean"

## Actual results
From my side, the build failed after the code got updated.

**Comment by dimakuv** [comment]
We rewrote the Common library (previously under Pal/lib) completely -- from Makefiles to Meson. So this issue is not relevant anymore, closing.
