### ISSUE TITLE
[Linux-PAL] Segfault in R / [SGX-PAL] crash

### ISSUE THREAD

**Issue by jopasserat** [oscarlab/graphene#1988]
## Description of the problem

I'm trying to run an R [plumber](https://www.rplumber.io/) webservice in graphene SGX.
When launched, the app captures a segfault and prints:

**address 0x200, cause 'memory not mapped'**

After displaying this error message and the corresponding stacktrace, it resumes a seemingly normal graphene startup (load pages, checks trusted files, ...) and finally crashes after having started multiple threads.

## Steps to reproduce

graphene commit id: 8ff79072f5baf1331445eb0819968dade9c76d3e
R plumber service: reproduced with the "hello world" on this page => https://www.rplumber.io/

## Expected results

Web server is started and available in SGX.

### When starting with pal-Linux:

```
Running plumber API at http://0.0.0.0:5000

 *** caught segfault ***
address 0x200, cause 'memory not mapped'

Traceback:
 1: makeTcpServer(host, port, private$appWrapper$onHeaders, private$appWrapper$onBodyData,     private$appWrapper$call, private$appWrapper$onWSOpen, private$appWrapper$onWSMessage,     private$appWrapper$onWSClose, private$appWrapper$staticPaths,     private$appWrapper$staticPathOptions, quiet)
 2: initialize(...)
 3: WebServer$new(host, port, app, quiet)
 4: startServer(host, port, app)
 5: httpuv::runServer(host, port, self)
 6: run_myapp$run(host = "0.0.0.0", port = 5000, swagger = FALSE)
An irrecoverable exception occurred. R is aborting now ...
ng pipe: pipe.srv:2044726324
```

### When starting from pal-SGX

The app seems to be starting a 2 R threads as expected (log shows the trusted files being verified twice).
No error message from an invalid manifest, measurement or unreachable trusted file.

first debug logs:
```
[P3340:R] Host: Linux-SGX
[P3340:R] LibOS xsave_enabled 1, xsave_size 0x440(1088), xsave_features 0x1f
[P3340:R] Initial VMA region 0x1faa73000-0x1fad2e000 (LibOS) bookkeeped
[P3340:R] Initial VMA region 0x1fffec000-0x200000000 (manifest) bookkeeped
[P3340:R] Initial VMA region 0x1fad2e000-0x1faf30000 (exec) bookkeeped
[P3340:R] ASLR top address adjusted to 0x101f79000
[P3340:R] Shim loaded at 0x1faa73000, ready to initialize
[P3340:R] Mounting root as chroot filesystem: from file:/ to /
[P3340:R] Mounting special proc filesystem: /proc
[P3340:R] Mounting special dev filesystem: /dev
[P3340:R] Mounting terminal device /dev/tty under /dev
[P3340:R] Creating pipe: pipe.srv:3673427212
[P3340:R] Adding port (handle 0x1ff170cb0) for process 3340 (type 0001)
[P3340:T1:R] Allocated stack at 0xfff79000 (size = 33554432)
[P3340:T1:R] adding file:R as runtime object loaded at 0x1fad2e000-0x1faf30000
[P3340:T1:R] search interpreter: /graphene/Runtime/ld-linux-x86-64.so.2
[P3340:T1:R] add a library for gdb: file://graphene/Runtime/ld-linux-x86-64.so.2
[P3340:T1:R] Shim process initialized
[P3340:i1:R] Allocated stack at 0x1fa9e1000 (size = 16384)
[P3340:i1:R] IPC helper thread started
[P3340:T1:R] ---- shim_brk(0x0) = 0xfff38000
[P3340:i1:R] Listening to process 3340 on port 0x1fa9ec048 (handle 0x1ff170cb0, type 0001)
```

When reaching `sh` and `rm` (used internally in R):
```
trusted: file:/bin/sh
trusted: file:/graphene/Runtime/libsysdb.so
trusted: file:/graphene/Runtime/ld-linux-x86-64.so.2
trusted: file:/graphene/Runtime/libc.so.6
trusted: 477089246884926730947c49c0e37aaf9144060e09f1b736759d0fd1fdd519c6 file:/bin/rm.sig
DkProcessExit: Returning exit code -2
Saturation error in exit code -2, getting rounded down to 254
DkProcessExit: Returning exit code 1048576
Temporary process exits after emulating execve, wait for child to exit
DkProcessExit: Returning exit code 134
```

The plumber starting message does get displayed amongst the debug logs though, suggesting R has somehow started before crashing

```
Running plumber API at http://0.0.0.0:5000
save_enabled 1, xsave_size 0x440(1088), xsave_features 0x1f
```

I've also seen this message after a crash:
```
[P3585:R] restored memory from checkpoint
[P3585:R] receiving 6 PAL handles
[P3585:R] restoring checkpoint at 0x1f4524000 rebased from 0x1f4524000
assert failed bookkeep/shim_thread.c:563 tcb->context.regs && shim_context_get_sp(&tcb->context)
DkProcessExit: Returning exit code 1
assert failed ipc/shim_ipc_ranges.c:288 owner
DkProcessExit: Returning exit code 1
```

### Context

The demo is based on a manifest generated using `gsc` and further tweaked for debugging purposes.
The resulting docker image contains graphene as well as all the dependencies required to run the app.
The app works fine when creating a plain docker container and executing without graphene.
I do not have full control over the number of threads started by the app, as it is determined by an underlying dependency of plumber as described here: https://github.com/rstudio/plumber/issues/494 (_at least 2 threads are started, my manifest specifies 32 max_)

### Content of R.manifest

```
loader.preload = "file:/graphene/Runtime/libsysdb.so"

# Get path of binary
#loader.exec = "file:/usr/local/lib/R/bin/exec/R"

loader.env.LD_LIBRARY_PATH = "/graphene/Runtime:/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server:/usr/lib/x86_64-linux-gnu/libfakeroot:/usr/local/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib:/usr/lib:"
loader.env.PATH = ".:/usr/local/lib/R/bin/exec/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
loader.env.R_HOME_DIR = "/usr/local/lib/R"
loader.env.R_HOME = "/usr/local/lib/R"
loader.env.R_SHARE_DIR = "/usr/local/lib/R/share"
loader.env.R_INCLUDE_DIR = "/usr/local/lib/R/include"
loader.env.R_DOC_DIR = "/usr/local/lib/R/doc"
loader.env.R_LD_LIBRARY_PATH = "/usr/local/lib/R/lib:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/jvm/java-11-openjdk-amd64/lib/server"
loader.debug_type = "inline"

fs.root.type = "chroot"
fs.root.path = "/"
fs.root.uri = "file:/"

# With fs.root Graphene's working directory is '/', setting fs.start_dir changes the
# working directory to the desired location
fs.start_dir = "/appdir/"

# Start at static addresses (otherwise breaks when static and PIE executables are used)
sgx.static_address = 1

loader.insecure__use_host_env = 1
loader.insecure__use_cmdline_argv = 1

# All trusted files and the user defined manifest specifications should be after this line

sgx.trusted_files.ld = "file:/graphene/Runtime/ld-linux-x86-64.so.2"
sgx.trusted_files.libc = "file:/graphene/Runtime/libc.so.6"
sgx.trusted_files.libm = "file:/graphene/Runtime/libm.so.6"
sgx.trusted_files.libdl = "file:/graphene/Runtime/libdl.so.2"
sgx.trusted_files.librt = "file:/graphene/Runtime/librt.so.1"
sgx.trusted_files.libutil = "file:/graphene/Runtime/libutil.so.1"
sgx.trusted_files.libpthread = "file:/graphene/Runtime/libpthread.so.0"
sgx.trusted_files.libnssdns = "file:/graphene/Runtime/libnss_dns.so.2"
sgx.trusted_files.libresolve = "file:/graphene/Runtime/libresolv.so.2"
sgx.allow_file_creation = 1
sgx.enclave_size = "8G"
sgx.thread_num = 32
sys.stack.size = "32M"
```
...
followed by a list of 400+ trusted files and these trusted children:

```
sgx.trusted_children.child0 = "file:/bin/sh.sig"
sgx.trusted_children.child1 = "file:/bin/rm.sig"
sgx.trusted_children.child2 = "file:/bin/uname.sig"
```

### Misc

I've tried varying the enclave (4G and 8G) and stack sizes (16M, 32M) in SGX to no success.
The R code behind the webservice is using a pre-compiled openblas so it could be related to this issue: https://github.com/oscarlab/graphene/issues/977

**Comment by dimakuv** [comment]
Thanks for a detailed bug report!

Indeed, seems like there are three separate issues:

- `address 0x200, cause 'memory not mapped'` that happens even in non-SGX Graphene.

- `assert failed bookkeep/shim_thread.c:563 tcb->context.regs && shim_context_get_sp(&tcb->context)` that happens in Graphene-SGX during child-process restore.

- `assert failed ipc/shim_ipc_ranges.c:288 owner` that I guess happens also during child-process "talk to my parent" logic.

Quite some stuff to debug... We'll try our best to fix this soon.

**Comment by jopasserat** [comment]
Thanks for looking into this! Let me know if you need more input from me to assist you with debugging this.
Also happy to provide you with some more material to reproduce (maybe aside from github if you want to have access to large filesystems for instance..)

**Comment by dimakuv** [comment]
This will be low-priority for us, so if you can, feel free to debug the issues yourself using GDB: https://graphene.readthedocs.io/en/latest/devel/debugging.html. Beware, debugging multi-process applications is  a PITA, so check GDB docs, e.g. https://sourceware.org/gdb/onlinedocs/gdb/Forks.html.

**Comment by jopasserat** [comment]
any tips as to where to look? (i'm fairly ok with GDB but not so much with the graphene codebase :) )

**Comment by dimakuv** [comment]
I would start with running non-SGX Graphene (Linux PAL) and figuring out the ` *** caught segfault *** address 0x200, cause 'memory not mapped'` failure. Just `run` the app when in GDB, and the app with Graphene will stop at SIGSEGV failure. At this point you can look at the backtrace and maybe it will give you a hint what went wrong.

**Comment by dimakuv** [comment]
Very old issue, Graphene did a lot of bug fixing in the meantime, and our R example works. Closing it. @jopasserat Feel free to reopen this issue if your problem still persists.
