### ISSUE TITLE
How to implementation sgx-PCL with Graphene + SGX

### ISSUE THREAD

**Issue by baoyibao99-baohan** [oscarlab/graphene#1994]
Hi, the SGX Protected Code Loader (PCL) is intended to protect Intellectual Property (IP) within the code for Intel(R) SGX enclave applications running on the Linux* OS.

I want to protect my code in sgx, how to do so?

thanks

**Comment by dimakuv** [comment]
There is currently no such thing implemented in Graphene. You could write an application that runs on top of Graphene and that loads the encrypted binary inside the enclave memory, but this will be your own implementation, independent of Graphene.

**Comment by baoyibao99-baohan** [comment]
Thank you, dimakuv. 

In term of Graphene, i am a novice. I get some information from https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html#end-to-end-confidential-pytorch-workflow, but it protected data file, not binary. You said to "encrypt binary inside the enclave memory", but where do i encrypt the binary, and where do i decrypt the binary to be executed in the enclave.

**Comment by dimakuv** [comment]
You create an application that serves as a loader of other applications. You put this application inside Graphene. You do SGX remote attestation with your trusted "encrypted application provider" machine and establish a TLS channel between the Graphene-SGX enclave and the trusted machine. The trusted machine has the binary of the actual application-to-run. The binary is sent to the Graphene-SGX enclave (encrypted since this is TLS), and then the binary is run by your "loader" application.

**Comment by dimakuv** [comment]
This is only one option off the top of my mind.

**Comment by baoyibao99-baohan** [comment]
I get you ideal, thanks. Now, I am facing a difficult: how to run the binary by my "loader" in SGX graphene? is there a sample for me to study?

**Comment by dimakuv** [comment]
No, unfortunately there is no example for a "loader" app.

For the SGX remote attestation, RA-TLS, and secret provisioning you may look at these:
- https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/tools/README.rst
- https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-mbedtls
- https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-secret-prov
- https://arxiv.org/ftp/arxiv/papers/1801/1801.05863.pdf

**Comment by baoyibao99-baohan** [comment]
Now, I have no problem with remote attestation, but it's difficult to create a "loader" to load an encrypted binary, and decrypt and relocate. For example,
$ SGX=1 ./pal_loader my_loader my_app
my_loader should do the  steps:
 1. read binary into enclave memory
 2. decrypt the binary and save into enclave memory
 3. relocate 
at step 3, I want to do the same as LibOS loads and relocate my_loader, but the related code is very difficult to me. How can I do these easily?

**Comment by dimakuv** [comment]
The code for dynamic relocation is indeed extremely difficult to understand (I'm talking about e.g. https://github.com/oscarlab/graphene/blob/master/Pal/src/db_rtld.c)... I don't think there is an "easy" way of doing that. You have to either:
1. gain a deep understanding of ELF binaries and relocation procedures (see https://refspecs.linuxfoundation.org/elf/elf.pdf and http://stffrdhrn.github.io/hardware/embedded/openrisc/2019/11/29/relocs.html), or
2. try to adapt an already-existing tool for this; I would look at documentation and code of things like https://grugq.github.io/docs/phrack-58-05.txt and https://github.com/intel/linux-sgx-pcl. 

Also, you can examine a more friendly code of the dynamic linker in Musl C: https://git.musl-libc.org/cgit/musl/tree/ldso/dynlink.c.
