### ISSUE TITLE
Incorrect reporting of AESMD running via "is_sgx_available"

### ISSUE THREAD

**Issue by jurobystricky** [oscarlab/graphene#1998]
## Description of the problem
Incorrect reporting of AESMD running via "is_sgx_available"

## Steps to reproduce
Stop the aesmd service:
<pre>
$ sudo systemctl stop aesmd
</pre>
Run _is_sgx_available_
<pre>
$  is_sgx_available 
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x10000000
SGX driver loaded: true
SGX PSW/libsgx installed: true
AESMD running: true
</pre>

## Expected results

AESMD running: false

## Actual results

AESMD running: true

Verify aesmd really stopped:

<pre>
$ sudo systemctl status aesmd
● aesmd.service - Intel(R) Architectural Enclave Service Manager
   Loaded: loaded (/usr/lib/systemd/system/aesmd.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2020-11-25 09:58:03 EST; 9h ago
  Process: 1190 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
  Process: 1185 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 1182 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 1179 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 1176 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 1161 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
  Process: 1095 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
 Main PID: 1211 (code=exited, status=0/SUCCESS)

Nov 24 18:58:46 sdp-sgx-centos33 systemd[1]: Starting Intel(R) Architectural Enclave Service Manager...
Nov 24 18:58:46 sdp-sgx-centos33 systemd[1]: Started Intel(R) Architectural Enclave Service Manager.
Nov 24 18:58:46 sdp-sgx-centos33 aesm_service[1211]: The server sock is 0x157fde0
Nov 24 23:56:11 sdp-sgx-centos33 aesm_service[1211]: InKernel LE loaded
Nov 25 09:58:03 sdp-sgx-centos33 systemd[1]: Stopping Intel(R) Architectural Enclave Service Manager...
Nov 25 09:58:03 sdp-sgx-centos33 systemd[1]: Stopped Intel(R) Architectural Enclave Service Manager.

</pre>

**Comment by dimakuv** [comment]
Not reproducible on my Ubuntu 18.04 with Linux 4.15:
```
~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ sudo systemctl stop aesmd
~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ ./is_sgx_available
...
AESMD running: false

~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ sudo systemctl start aesmd
~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ ./is_sgx_available
...
AESMD running: true
```

Internally, to decide whether AESMD is running or not, `is_sgx_available` tries to fine the pseudo-file`/var/run/aesmd/aesm.socket`. If the file exists, then AESMD is running; if it doesn't exist, then AESMD is not running.

What is the Intel SGX PSW version that is installed on your machine? Or maybe it's another Linux version? I also see that you use CentOS -- could it be that CentOS uses a different pseudo-file for AESMD service?

**Comment by woju** [comment]
Reporter is kinda right in that when aesmd has open socket, but spews error 30, this might not count as "running". This happens on hiccups, but also when you install aesmd from packages and don't have the right set of plugins, because the dependencies are poorly defined on official debs.

I have a better version here, adapted for monitoring: https://github.com/woju/prometheus-sgx-exporter. It actively queries aesmd and checks the response. Usually it is run as http server (that's how prometheus works), but you can run it as a one-off:
```
$ python3 -m prometheus_sgx_exporter test
cpuid_is_cpuid_supported 1
cpuid_is_intel_cpu{vendor_id="GenuineIntel"} 1
#cpuid_max_enclave_size_bytes{arch="x86"} 0x80000000p0
cpuid_max_enclave_size_bytes{arch="x86"} 2147483648
#cpuid_max_enclave_size_bytes{arch="x86_64"} 0x1000000000p0
cpuid_max_enclave_size_bytes{arch="x86_64"} 68719476736
#cpuid_epc_size_bytes 0x5d80000p0
cpuid_epc_size_bytes 98041856
cpuid_is_sgx_supported 1
cpuid_is_flc_supported 0
cpuid_is_sgx1_supported 1
cpuid_is_sgx2_supported 0
cpuid_is_sgx_virt_supported 0
cpuid_is_sgx_mem_concurrency_supported 0
cpuid_is_cet_supported 0
cpuid_is_kss_supported 0
sgx_driver{type="inkernel"} 0
sgx_driver{type="dcap"} 0
sgx_driver{type="oot"} 1
aesmd_up 1
aesmd_serviceable 1
#aesmd_error 0
```

**Comment by jurobystricky** [comment]
> Not reproducible on my Ubuntu 18.04 with Linux 4.15:
> 
> ```
> ~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ sudo systemctl stop aesmd
> ~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ ./is_sgx_available
> ...
> AESMD running: false
> 
> ~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ sudo systemctl start aesmd
> ~/dev-graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available$ ./is_sgx_available
> ...
> AESMD running: true
> ```
> 
> Internally, to decide whether AESMD is running or not, `is_sgx_available` tries to find the pseudo-file`/var/run/aesmd/aesm.socket`. If the file exists, then AESMD is running; if it doesn't exist, then AESMD is not running.
> 
> What is the Intel SGX PSW version that is installed on your machine? Or maybe it's another Linux version? I also see that you use CentOS -- could it be that CentOS uses a different pseudo-file for AESMD service?

I use CentOS 8.2. Just in case, I reinstalled sgx-aesm-service with the latest version available from https://download.01.org/intel-sgx/sgx-linux/2.12/distro/centos8.2-server/
After stopping the service, the unix socket still remains present, so "is_sgx_available" reports AESMD running:true.

**Comment by jurobystricky** [comment]
> Reporter is kinda right in that when aesmd has open socket, but spews error 30, this might not count as "running". This happens on hiccups, but also when you install aesmd from packages and don't have the right set of plugins, because the dependencies are poorly defined on official debs.
> 
Yes, aesmd can report error 30 (AESM_SERVICE_UNAVAILABLE). Considering the error is issued by the aesmd itself, it is misleading to say the least. I found this error is issued when trying to obtain SGX token using IN-TREE sgx driver (possibly other cases as well, not sure). 
The journal will typically report something like "InKernel LE loaded".

**Comment by dimakuv** [comment]
I'm not sure how to proceed with this issue.

1. We could add active communication with AESMD to the `is_sgx_available` tool. But this would require the use of Protobuf and knowing the format of AESMD messages. I am reluctant to add such complex functionality to this simple tool.

2. We could remove printing the status of AESMD completely from this tool.

3. We could replace the misleading `AESMD running: true` to `AESMD installed: true`.

4. We could leave it as-is.

**Comment by woju** [comment]
If you'd like to do it, it's not that hard:

https://github.com/woju/prometheus-sgx-exporter/blob/87384d3641bc304ad2d11fbc5a469e8db6fab26b/prometheus_sgx_exporter/coll_aesmd.py#L20-L41

I suggest to either drop AESMD reporting (2).

**Comment by jinghe-INTC** [comment]
I have tried with CentOS 8.3 with kernel 4.18.0， SGX PSW is 2.12 with driver 1.36.2. 
It seems is-sgx-available results matched AESM status.

I also tried https://github.com/woju/prometheus-sgx-exporter. When AESMD was stopped:

```
[root@localhost prometheus-sgx-exporter]#  prometheus-sgx-exporter test
...
# aesmd: file not found
aesmd_up 0
aesmd_serviceable 0
```
And when AESMD was running:
```
[root@localhost prometheus-sgx-exporter]#  prometheus-sgx-exporter test
...
aesmd_up 1
aesmd_serviceable 0
#aesmd_error 30
```

**Comment by woju** [comment]
Looks correct. `aesmd_serviceable 0` means that for an attempt to sign something, aesmd threw up an error. The comment says it was error 30.

If you tried to actually get a token, the result would be the same (error 30).
