### ISSUE TITLE
Graphene support for SGX Simulation mode?

### ISSUE THREAD

**Issue by JoshLind** [oscarlab/graphene#20]
Hi,

One question I'm not sure about is whether or not we can run graphene SGX applications without SGX hardware. In the Intel Sample Code, for example, omitting the flag "SGX_MODE=HW" allows you to run the application in simulation mode (see the README here: https://github.com/01org/linux-sgx/tree/master/SampleCode/SampleEnclave). Is the same true with Graphene? If I specify make "SGX=1", does this force me to require SGX enabled hardware?

Thanks for your help!

**Comment by chiache** [comment]
You will need the SGX hardware, Graphene does not have a simulation mode now.

**Comment by JoshLind** [comment]
Okay, thanks for your help! :)
