### ISSUE TITLE
set/get affinity code paths do not handle offline CPUs properly

### ISSUE THREAD

**Issue by stefanberger** [oscarlab/graphene#2009]
## Description of the problem

When CPUs are offline, such as in this case here, then the sched_getaffinity call and associated test cases will fail.

```
# cat /sys/devices/system/cpu/online 
0,8,16,24,32,40,48,56,64,72,80,88,96,104,112,120,128,136,144,152
```

The issue lies in the applications thinking that there are 20 CPUs available and using a smaller mask than what the kernel is using internally an we get an EINVAL due this this condition here (https://man7.org/linux/man-pages/man2/sched_setaffinity.2.html):

```
      EINVAL (sched_getaffinity() and, in kernels before 2.6.9,
              sched_setaffinity()) cpusetsize is smaller than the size of
              the affinity mask used by the kernel.
```

## Steps to reproduce

Set some CPUs offline and you should get these test case failures here:

test_libos.py::TC_30_Syscall::test_080_sched FAILED                                                                                    [ 60%]
test_libos.py::TC_30_Syscall::test_101_sched_set_get_cpuaffinity FAILED                                                                [ 68%]
test_libos.py::TC_30_Syscall::test_102_pthread_set_get_affinity FAILED                                                                 [ 69%]

## Expected results

Test cases should succeed.

**Comment by stefanberger** [comment]
Two possible solutions:

1.  virtual configuration fixup: fixing up the `mask` right before the sched_getaffinity syscall and setting those bits the callers wants and that correspond to the currently 'real' configuration of the system. So if CPUs 1-7 are offline and the user wants CPU 1 (start counting at 0) we would have to set bit 8 for example.
2. real hardware configuration: present the real configuration of the system reflecting all the offline CPUs

Using 2) maybe better for existing applications that would know how to deal with a changing real (hardware) configuration while an application is running...

**Comment by vijaydhanraj** [comment]
@stefanberger thanks for creating the issue. Topology changes are being added to graphene and supporting offlined cores is in the pipeline. Until the support is in place, we have added a debug message `Warning: some CPUs seem to be offline; Graphene doesn't take this into account which may lead to subpar performance` and PAL initialization will fail.

**Comment by dimakuv** [comment]
We have at least a warning on this (and we're also currently working on sysfs), so I think we should just close this issue.
