### ISSUE TITLE
sgx-driver is not having any makefile

### ISSUE THREAD

**Issue by Nidhimidha** [oscarlab/graphene#201]
I am using Linux 16.04 and I am trying to follow steps mentioned on https://github.com/oscarlab/graphene/wiki/SGX-Quick-Start.

I have followed all the prerequisites such as installing linux-sgx and linux-sgx-driver. Though when I ran make on graphene/pal/src, sgx-driver is not getting build, and its just an empty folder. I am stuck at the 3rd step. 

Few other observations that I noticed:
graphene-master/LibOS/shim/test/apps/lmbench is an empty folder.
graphene-master/LibOS/shim/test/apps isn't having any hello folder.

I am assuming this is something related to bad build. Though, I made sure to first install linux-sgx and linux-sgx-driver, and then make graphene.

What could possibly be the issue that I am not able to build properly?

**Comment by chiache** [comment]
Please run "git submodule update --init" in the local repository.

**Comment by Nidhimidha** [comment]
Thank you very much. I certainly missed that step out. Extracted code now looks much better. I am able to proceed from 3rd step. When i was asked to write down the path for sgx-driver in 3rd step, I had given below information:

Enter the Intel SGX driver directory: home/yashshvi/Downloads/linux-sgx-driver-sgx2
Enter the driver version (default: 1.9): 2.0



Though I am getting any issue when trying to run fifth step, i.e., "Run a helloworld program". 
Below are the results after running the commands. What could possibly be issue since I had been following everything step by step?



yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene$ cd LibOS/shim/test/native
yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ make SGX=1
make: *** No rule to make target 'static.manifest.sgx', needed by 'all'.  Stop.
yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ make SGX_RUN=1
make: *** No rule to make target 'static.token', needed by 'all'.  Stop.
yashshvi@yashshvi-Lenovo-YOGA-710-15IKB:~/Downloads/graphene/LibOS/shim/test/native$ ./pal_loader SGX helloworld    or    SGX=1 ./pal_loader helloworld
/home/yashshvi/Downloads/graphene/Runtime/pal-Linux-SGX is not built, or security mode is not supported
