### ISSUE TITLE
A potential type issue in the memory allocation

### ISSUE THREAD

**Issue by xxu36** [oscarlab/graphene#2022]
I 'm browsing the graphene code, and wondering whether this line
https://github.com/oscarlab/graphene/blob/d88e35e1c1dadd54a974a0641f42605797cad52a/LibOS/shim/src/bookkeep/shim_handle.c#L491
has a typo and should be `handle_map->map = calloc(size, sizeof(struct shim_fd_handle *));` ? 

Because all the other places in the code behave like `handle_map->map` is a pointer to an pointer array.

**Comment by dimakuv** [comment]
@xxu36 Indeed this looks like a bug! Thanks! Do you want to create a PR fixing this? We'll be happy to review and merge it.

Fortunately, this is a rather benign bug. On e.g. x86-64 we have:
- `sizeof(struct shim_fd_handle)` is equal to 16
- `sizeof(struct shim_fd_handle*)` is equal to 8

So we allocate twice as much memory as we actually need. So we have a slight memory leak but **no** memory corruption.
