### ISSUE TITLE
pal-Linux-SGX runs manifest and not attached fun

### ISSUE THREAD

**Issue by elichai** [oscarlab/graphene#203]
Hi, I'm trying to run a manifest with interpreter and a py file but after the manifest is checked the file doesn't run correctly `/home/elichai2/gits/sgx/python-sgx/graphene/Runtime/pal-Linux-SGX /var/lib/python-sgx/python3.manifest.sgx -B /usr/local/bin/sgx-ra-manager`
python3.manifest.sgx: https://gist.github.com/elichai/8259db28cd7cbe21c70528e736bef616
The output: https://gist.github.com/elichai/5a83c158cd8cb84d1931927a426471e5 

I tried comparing my manifest to the one from the `python.manifest` example and couldn't find any significant difference.
Any ideas?

**Comment by donporter** [comment]
Hi @elichai , can you try setting debug_type to inline in the manifest and see if that gives a more detailed output?  Also, consider building Graphene with the 'DEBUG=1' option.

It is hard to tell what is happening from this output.  Does it eventually crash, or hang, or something else unexpected?

**Comment by mkow** [comment]
No updates from the reporter, closing.
