### ISSUE TITLE
A mistake in the unit of the loading time printing

### ISSUE THREAD

**Issue by jinghe-INTC** [oscarlab/graphene#2034]
It seems the variable `end_time` is recorded in microsecond:

https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/Pal/src/host/Linux-SGX/db_misc.c#L48

https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/Pal/src/host/Linux-SGX/db_main.c#L428

But when printing the loading time, which was the offset between `end_time` and `start_time`, it uses `milliseconds`  not `microseconds` :

https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/Pal/src/host/Linux-SGX/db_main.c#L433
https://github.com/oscarlab/graphene/blob/cac1bb22c37ac41fb7af6e0726831000ab00e51c/Pal/src/host/Linux-SGX/db_main.c#L434

Please fix it.

**Comment by dimakuv** [comment]
Thanks @jinghe-INTC , indeed a bug in printing. It must be `microseconds`.

There is a whole lot of ugliness in that code and `start_time`... I'll clean it up. I guess the macro `PRINT_ENCLAVE_STAT` is still useful, so I'll keep it.

**Comment by dimakuv** [comment]
@jinghe-INTC Please try #2035. Note that you **don't** need to enable `PRINT_ENCLAVE_STAT` now, but instead just use `sgx.enable_stats = 1` in the manifest file.

**Comment by jinghe-INTC** [comment]
Now it prints `SGX stats` of the processes and thread. Is it any way to get the enclave loading time from `SGX stats`? 
And I don't see any update for this on db_main.c.

**Comment by dimakuv** [comment]
You should search for `SGX enclave loading time` in your output. It is printed in the beginning, not at the end.

**Comment by jinghe-INTC** [comment]
Yes. You were right. I am closing the case now.
