### ISSUE TITLE
TOML doesn't support '+' in key name in manifest file trustedfile section

### ISSUE THREAD

**Issue by dashuaic** [oscarlab/graphene#2039]
## Description of the problem
TOML doesn't support key name have '+' in manifest file in trusted_files section.  for example, if have line like below
`sgx.trusted_files.libstdc++so6 = "file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6"`
will get TOML parse error like this
`PAL failed at parsing the manifest: line 69: bad key`
I checked the code, found in normalize_key() function in toml.c.
`for bare-key allow only this regex: [A-Za-z0-9_-]+`
Can add the **+** to allowed char list in here?
## Expected results
Toml can accept the '+' in key name
## Actual results
will get TOML parse error like this
`PAL failed at parsing the manifest: line 69: bad key`

**Comment by dimakuv** [comment]
We cannot change the specification of TOML (https://toml.io/en/v1.0.0-rc.3#keys), and we don't want to deviate from the TOML specification.

Regarding your issue, TOML allows to put keys in double quotes, so you can write like this:
```
sgx.trusted_files."libstdc++so6" = "file:/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
```
