### ISSUE TITLE
There should be a way to build Graphene without tests

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#204]
It would be nice to have a way to build Graphene without tests. Two proposed solutions:
* Move all tests to a new target, "test".
* Add a switch to the main Makefile, e.g. `NO_TESTS=1`.

I prefer the first option more (AFAIR this is a widespread convention), but the second should work well also. @donporter @chiache Any preferences? I can implement this as a pull request once we decide which way to go.

**Comment by donporter** [comment]
Fine with me.  No preference. 

The only problem with 'make test' is that sometimes this convention means to run the test, not just build the tests.  But seems like something easily fixable with README modifications.

**Comment by HW42** [comment]
Implemented in PR #759 (separate Make target which builds the tests).
