### ISSUE TITLE
Internal memory fault

### ISSUE THREAD

**Issue by hhb584520** [oscarlab/graphene#2066]
[thread-10.txt](https://github.com/oscarlab/graphene/files/5785005/thread-10.txt)

Ignore some log, you can see in thead-10.txt
[P47747:T4:envoy-static] ---- shim_set_robust_list(0x8b2529e0,24) = 0
[P47747:T4:envoy-static] ---- shim_mmap(0x0,134217728,PROT_NONE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE,-1,0) ... mmap
[P47747:T1:envoy-static] ---- return from shim_clone(...) = 4
[P47747:T1:envoy-static] ---- shim_socket(UNIX,SOCK_NONBLOCK|DGRAM,0) = 6
Internal memory fault at 0x00000000 (IP = +0x48b5e, VMID = 110344835, TID = 1)

## Description of the problem
Can not Pre-allocated memory greater than 1G EPC size memory.
Kernel:  5.10.0-rc3+ (https://github.com/intel/kvm-sgx.git branch is **next** 196fb3dc4)
OS: Ubuntu 18.04.5 LTS
Graphene: https://github.com/oscarlab/graphene.git (commit id: 8ff79072)
SGX information: 
   eax=7H, ecx=0H, read ebx 0xf2bf27ef
   Support SGX
   sgx1 available
   sgx2 available
   EPC section 0x50180000-0x5bd7ffff, size:0xbc00000

## Steps to reproduce

$ cd /home/sgx/
$ cd graphene
$ cat manifest-for-envoy
loader.preload = "file:/home/sgx/graphene/Runtime/libsysdb.so"
loader.env.LD_LIBRARY_PATH = "/lib"
loader.debug_type = "inline"
loader.insecure__use_cmdline_argv = 1

fs.mount.lib.type = "chroot"
fs.mount.lib.path = "/lib"
fs.mount.lib.uri = "file:/home/sgx/githome/graphene/Runtime"

fs.mount.bin.type = "chroot"
fs.mount.bin.path = "/bin"
fs.mount.bin.uri = "file:/bin"

#sys.brk.max_size = "300M"
#sys.stack.size = "4M"
sgx.enclave_size = "2G"
sgx.thread_num= 10

sgx.trusted_files.ld = "file:/home/sgx/githome/graphene/Runtime/ld-linux-x86-64.so.2"
sgx.trusted_files.libc = "file:/home/sgx/githome/graphene/Runtime/libc.so.6"
sgx.trusted_files.libdl = "file:/home/sgx/githome/graphene/Runtime/libdl.so.2"
sgx.trusted_files.libm = "file:/home/sgx/githome/graphene/Runtime/libm.so.6"
sgx.trusted_files.libpthread = "file:/home/sgx/githome/graphene/Runtime/libpthread.so.0"
sgx.trusted_files.librt = "file:/home/sgx/githome/graphene/Runtime/librt.so.1"

sgx.trusted_files.tcp_c = "file:tcp.c"

[envoy-static-no_tcmalloc.zip](https://github.com/oscarlab/graphene/files/5784968/envoy-static-no_tcmalloc.zip)

$ cd /home/sgx/graphene/LibOS/shim/test/native
$ unzip envoy-static-no_tcmalloc.zip
$ mv envoy-static-no_tcmalloc envoy-static
$ wget https://github.com/envoyproxy/envoy/blob/master/configs/envoy-demo.yaml
$ pal-sgx-sign -libpal /home/sgx/graphene/Runtime/libpal-Linux-SGX.so -key /home/sgx/graphene/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output envoy-static.manifest.sgx -exec envoy-static -manifest manifest-for-envoy
$ pal-sgx-get-token -output envoy-static.token -sig envoy-static.sig
$ sudo SGX=1 pal_loader envoy-static -c envoy-demo.yaml

## Expected results
Can forward request 

## Actual results
internal memory fault

**Comment by dimakuv** [comment]
> GO: go version go1.15.5 linux/amd64

Is your Envoy app written in Go? From what I see, this: https://github.com/envoyproxy/envoy is written in C++. Where do you use Go then?

We are currently working on support for Go. We are aware that Go apps fail under Graphene currently because of some quirks (in particular, signal handling and stacks). In fact, one PR to fix stacks in Graphene will land soon.

Or is there nothing in Envoy that depends on Go? Then it indicates a bug in Graphene which we'll need to debug...

**Comment by hhb584520** [comment]
> > GO: go version go1.15.5 linux/amd64
> 
> Is your Envoy app written in Go? From what I see, this: https://github.com/envoyproxy/envoy is written in C++. Where do you use Go then?
> 
> We are currently working on support for Go. We are aware that Go apps fail under Graphene currently because of some quirks (in particular, signal handling and stacks). In fact, one PR to fix stacks in Graphene will land soon.
> 
> Or is there nothing in Envoy that depends on Go? Then it indicates a bug in Graphene which we'll need to debug...

Sorry, it is for pilot-agent, I will delete it.

**Comment by mkow** [comment]
@hhb584520 Please paste logs using proper Markdown formatting (triple backticks).

**Comment by bigdata-memory** [comment]
@hhb584520  will submit a PR to address this problem, thanks.
