### ISSUE TITLE
uname syscall not reporting correct kernel release in Graphene

### ISSUE THREAD

**Issue by jinengandhi-intel** [oscarlab/graphene#2067]
## Description of the problem

uname syscall is supported by Graphene but the kernel release version is incorrectly reported as it's hard coded to 3.10.0. Code snippet from shim_uname.c: https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_uname.c#L25

```static struct new_utsname g_current_uname = {
    .sysname  = "Linux",
    .nodename = "localhost",
    .release  = "3.10.0",
    .version  = "1",
#ifdef __x86_64__
    .machine  = "x86_64",
#else
#error "Not implemented"
#endif
    .domainname = "(none)", /* this seems to be the default on Linux */
};

int shim_do_uname(struct new_utsname* buf) {
    if (!buf || test_user_memory(buf, sizeof(*buf), /*write=*/true))
        return -EFAULT;

    memcpy(buf, &g_current_uname, sizeof(g_current_uname));
    return 0;
}
```
This is causing multiple LTP test failures where some tests require a minimum kernel version and since the kernel version hard coded in Graphene is so low, none of those tests run.

## Steps to reproduce

Simply run the following C program in Linux native and Graphene and you will notice the difference in the kernel version that Graphene reports.

```
#include <stdio.h>
#include <sys/utsname.h>

int main() 
{
    struct utsname un;
    uname(&un);
    printf("Kernel release %s\n", un.release);

    return 0;
}
```

## Expected results

uname should report the exact kernel release on the system.

## Actual results

Graphene always reports the kernel release as 3.10.0

**Comment by dimakuv** [comment]
@pwmarcz said this:

> I'm not sure if using host version is the way to go: if programs depend on the Linux version to determine what system calls are supported, then I think it's better to hardcode something that approximates LibOS API.

I agree with this. I also guess that hard-coding a more recent and "Graphene-enabled" version is better. Also this removes the problem of creating say Windows or FreeBSD PALs (where hosts obviously don't have a "Linux version"). 

Then the question is: which version to choose? I think `4.15` is a decent approximation for the current Graphene implementation.

**Comment by mkow** [comment]
> kernel release version is incorrectly reported

It's not "incorrect", as we don't really implement a specific kernel version.

> you will notice the difference in the kernel version that Graphene reports.

But difference with what? We emulate Linux ourselves, what would we compare with?

> Then the question is: which version to choose? I think 4.15 is a decent approximation for the current Graphene implementation.

We can bump it, but I'm afraid that if we do this then apps will start to use features we don't implement.

> This is causing multiple LTP test failures where some tests require a minimum kernel version and since the kernel version hard coded in Graphene is so low, none of those tests run.

@jinengandhi-intel I guess they are testing it to see if specific features are available, which we may actually not have implemented. Could you check what features these tests use, assuming the kernel version check passes? (you can easily bump the version reported by Graphene and check).

**Comment by jinengandhi-intel** [comment]
Copied below are the results when I bump up the kernel version to 4.15. fnctl and ioctl are couple of syscalls which are implemented in graphene and the test proceeds to fail with some other message. For the rest of the syscalls which are ENOSYS, it allows the test to proceed and end with a logical ENOSYS failure.

3.19 or higher:
bpf_map01 - ENOSYS
bpf_prog01 - ENOSYS

3.18 or higher:
bpf_prog02 - syscall(125) __NR_capget not supported, eventually might fail with bpf ENOSYS call.
bpf_prog03 - syscall(125) __NR_capget not supported, eventually might fail with bpf ENOSYS call.
bpf_prog04 - Failed to open FILE '/proc/sys/kernel/tainted', eventually might fail with bpf ENOSYS call.

3.15 or higher:
fcntl134 - TBROK: fcntl(4,cmd,...) failed: ENOSYS (38)
fcntl136 - TBROK: fcntl(4,cmd,...) failed: ENOSYS (38)

4.3 or higher:
membarrier01 - ENOSYS
userfaultd01 - ENOSYS

4.5 or higher:
ioctl08 - Timedout

4.9  or higher:
ioctlns_01 - TBROK open(/proc/self/ns/pid,0,00) failed: ENOENT (2)
ioctlns_02 - TBROK open(/proc/self/ns/uts,0,012455703060) failed: ENOENT (2)
ioctlns_04 - TBROK open(/proc/self/ns/user,0,037177523060) failed: ENOENT (2)
ioctlns_05 - TBROK: ltp_clone failed: EINVAL (22)
ioctlns_06 - TBROK: ltp_clone failed: EINVAL (22)

4.10 or higher:
quotactl04 - Fails in setup as it cannot find the kernel config file. LTP sources uses uname to find the kernel config file in /boot.

4.11 or higher:
ioctlns_03 - TBROK open(/proc/self/ns/uts,0,033176233060) failed: ENOENT (2)
ioctlns_07 TFAIL: unexpected ioctl error: ENOSYS (38)
statx01 TBROK: tst_path_has_mnt_flags: failed to open /proc/mounts: ENOENT (2)
statx02 - symlink(test_temp,test_temp_ln) failed: ENOSYS (38), 
statx03 - statx ENOSYS
statx04 - Timedout 
statx05 - Timedout 
statx06 - Timedout 

4.14 or higher:
memfd_create03 - Fails in setup with "Huge page is not supported" error.
memfd_create04 - Fails in setup with "Huge page is not supported" error.

**Comment by mkow** [comment]
> fnctl and ioctl are couple of syscalls which are implemented in graphene

They aren't, we just support maybe a few special cases in each one, but otherwise we return ENOSYS.

Ok, so looking at the errors, there seem to be no point in raising the kernel version we report?

**Comment by jinengandhi-intel** [comment]
The original intention behind raising this issue was that if we support uname syscall we should be returning the right host release. If Graphene does not support certain kernel release then have a check for that and may be exit out for the features we don't support.

**Comment by mkow** [comment]
> we should be returning the right host release

There's no "right host release", we're not aiming to return host kernel version. Graphene is a Linux kernel API implementation in usermode and has no relation to the host kernel (which may be even Windows, depending on PAL you use).

**Comment by mkow** [comment]
Closing, as I believe there's nothing on our side do to here. All the syscalls listed in https://github.com/oscarlab/graphene/issues/2067#issuecomment-757646970 are not supported, and it seems to be a good idea to be conservative w.r.t the declared Linux version we implement.
