### ISSUE TITLE
Graphene don't support sealing/unsealing functions 

### ISSUE THREAD

**Issue by Isan-Rivkin** [oscarlab/graphene#207]
I am trying to use the sealing functionality of SGX SDK. 
So far:
1. I tried using the native SDK functions (sgx_seal_data() )  but it returns ERROR because it fails while testing is_within_enclave() function that is being called behind the scenes. 
2. I tried to look for native Graphene implementation ( did the same with sgx_get_report and it worked) and failed to find it. 

Seems odd not to have this option, Am I missing something?

**Comment by martinschmatz** [comment]
@Isan-Rivkin Have you by any chance found a solution for sealing? 
Also: How did you get access to Graphene's `sgx_get_report` from your application. Judging from the your comment, I you seem to have figured it out. In particular: which libraries did you use for linking?
I'm trying to access some SGX functionalities (e.g. `sgx_getkey,` `sgx_get_report,..)` from within my application which executes inside an enclave.
I'd appreciate any hints. Thanks!

**Comment by dimakuv** [comment]
@martinschmatz If you only need basic SGX functionality (`sgx_getkey()`, `sgx_get_report()`) then you can just copy-paste these functions into the code of your application. If you don't want to deal with pure-assembly files, look at the C implementations from this PR: https://github.com/oscarlab/graphene/pull/410. (It will be merged very soon.)

If you need some more advanced functionality from Graphene's LibOS, then yes, you have to play with linkers and visibility of symbols exported by Graphene's `libsysdb.so`.

**Comment by martinschmatz** [comment]
@dimakuv Thanks for the info. 
Where I'm struggling is to find out which libraries I need to use to enable even the basic SGX functionalities `(sgx_getkey()`, `sgx_get_report()`). I included `sgx_api.h`, so for example a call to 'sgx_getkey()' compiles, but then fails when linking. 
Any hint there? 
Or do you mean by copy-paste to include the sources of e.g. `sgx_getkey()`?

**Comment by dimakuv** [comment]
Yes, I just meant copy-paste the sources. You will also need `#include "sgx_arch.h"` header which you can copy-paste from the Linux SGX driver.

**Comment by martinschmatz** [comment]
OK, understood. 
I'll certainly give it a try (either via assembler code, or the C-inline from the PR you mentioned).
Thanks for the clarification!


   Dmitrii Kuvaiskii --- [EXTERNAL] Re: [oscarlab/graphene] Graphene don't support sealing/unsealing functions (#207) --- 
    Von:"Dmitrii Kuvaiskii" <notifications@github.com>An:"oscarlab/graphene" <graphene@noreply.github.com>Kopie:"martinschmatz" <mrt@zurich.ibm.com>, "Mention" <mention@noreply.github.com>Datum:Di. 09.07.2019 19:53Betreff:[EXTERNAL] Re: [oscarlab/graphene] Graphene don't support sealing/unsealing functions (#207)
  
  Yes, I just meant copy-paste the sources. You will also need #include "sgx_arch.h" header which you can copy-paste from the Linux SGX driver.

**Comment by martinschmatz** [comment]
@dimakuv Just FYI - I used the C-inline calls from the PR #410 plus inclusion of `sgx_arch.h` (see below). 
With that (and quite a number of constants defined in various files to assemble the key request structure), I can execute a `my_sgx_getkey(...)` request and hence get access to enclave keys from within my app (which executes inside Graphene) - which is what I wanted. 

Going forward, I might change from using 'sxg_arch.h' to leverage the standard include files from the Intel SGX SDK, which for example would mean that `sgx_arch_keyrequest_t` turns into `sgx_key_request_t' - this to be able to use the Intel nomenclature of various defines of constants, types, etc.

In any case: Issue solved, case closed. Thanks!

```
#include "sgx_arch.h"

#define ENCLU ".byte 0x0f, 0x01, 0xd7" 

static inline int64_t my_sgx_getkey (sgx_arch_keyrequest_t * keyrequest,
                                  sgx_arch_key128_t * key)
{
    int64_t rax = EGETKEY;
    __asm__ volatile(
    ENCLU "\n"
    : "+a"(rax)
    : "b"(keyrequest), "c"(key)
    : "memory");
    return rax;
}

static inline int my_sgx_report (sgx_arch_targetinfo_t * targetinfo,
                              void * reportdata, sgx_arch_report_t * report)
{
    __asm__ volatile(
    ENCLU "\n"
    :: "a"(EREPORT), "b"(targetinfo), "c"(reportdata), "d"(report)
    : "memory");
    return 0;
}

static inline uint32_t my_rdrand (void)
{
    uint32_t ret;
    __asm__ volatile(
    "1: .byte 0x0f, 0xc7, 0xf0\n" /* RDRAND %EAX */
    "jnc 1b\n"
    :"=a"(ret)
    :: "cc");
    return ret;
}
```

**Comment by martinschmatz** [comment]
For what it's worth, here some related code snippets (now using the include files from Intel SGX instead the ones from Graphene): 
https://gist.github.com/martinschmatz/5eb479a74e9280772be4c7cef28cdbd6

**Comment by mkow** [comment]
> In any case: Issue solved, case closed. Thanks!

Ok, closing then (seems we missed that this is already reasolved).
