### ISSUE TITLE
Differ between running native test in docker and host ? 

### ISSUE THREAD

**Issue by duanbing** [oscarlab/graphene#2098]
## Description of the problem
When I run native test in Docker,   I got exception as below:

```
:/app/graphene/LibOS/shim/test/native# ./pal_loader helloworld
[P49234] set tcb to 0x7ffe84f81130
[P49234] host: Linux
[P49234] bkeep_unmapped: 0x7f52ae952000-0x7f52ae954000 => vma
[P49234] allocate 0x7f52ae952000-0x7f52ae954000 for vmas
assert failed db_exception.c:317 tcb (value:0)
```

## Steps to reproduce
I  install and run the graphene and SGX according to this doc: https://graphene.readthedocs.io/en/latest/building.html  in **without** SGX environment.
and verify the fsgsbase driver is ok as below.
```
:/app/graphene/LibOS/shim/test/native# LD_SHOW_AUXV=1 /bin/true | grep AT_HWCAP2
AT_HWCAP2:       0x2
```
and when I run it outside of the docker,  I got the expected return: 
```
...
Hello world (file:sleep)!
[     1] ---- return from shim_write(...) = 26
[     1] ---- shim_exit_group (returning 0)
[     1] now kill other threads in the process
[     1] walk_thread_list(callback=0x7f5483f6cf98)
[     1] now exit the process
[     1] IPC broadcast: IPC_CLD_EXIT(1, 1, 0, 0)
[     1] this is the only thread 1
[     1] Waiting for 0.5s for all in-flight IPC messages to reach their destinations
[     1] Deleting port 0x7f5483c7c048 (handle 0x7f5484400f10) of process 48400
[     1] process 48400 exited with status 0
```

How can I make it work inside docker container？   Thanks

**Comment by dimakuv** [comment]
Wow, this error is unexpected.

Could you please provide more information? How did you create this Docker image? How do you run this Docker container? What is the distro/version of your host OS? What is the distro/version of your in-Docker OS? What is the exact commit of Graphene?

**Comment by duanbing** [comment]
Both dist is `Linux n227-079-168 5.4.89-custom #2 SMP Mon Jan 18 12:42:30 CST 2021 x86_64 GNU/Linux`, compiled  and upgraded by https://wiki.ubuntu.com/KernelTeam/GitKernelBuild.  The docker image is ubuntu:18:04 pulled from Docker Hub.  entrypoint is `docker run -it  --name=sgx --net=host -v $PWD:/app -w /app  ubuntu:18.04 bash` , graphene commit id is e98be31b00710c053a558828149eb303351d9597.

**Comment by dimakuv** [comment]
You're using a very old version of Graphene (`mkow committed on Sep 11, 2019`).

Could you move to the latest master commit and check there?

**Comment by duanbing** [comment]
Yes. I guess 1.0.1 is stable, so you mean I can trust the master branch? or which one is the latest stable ?   Thanks.

**Comment by dimakuv** [comment]
The master branch is pretty stable.

To give some context: we temporarily "gave up" on the idea of stable releases. Graphene is undergoing a *major* rewrite, with many breaking changes. This is needed to drive Graphene to a production-ready state.

So for now, we don't provide any stable releases. We simply make sure that the master branch is sufficiently stable. The actual next stable release will be somewhere in autumn 2021.

**Comment by duanbing** [comment]
Great to hear that.  Could you give me some clues about the next big changes?  this is a great project, thanks for  your  guys' efforts

**Comment by dimakuv** [comment]
A couple next big changes:
- https://github.com/oscarlab/graphene/pull/2090 -- this is almost done, it changes mostly the internals of Graphene, no (or very few) user-visible changes
- File system rewrite -- this is not yet started, it will hopefully have only a couple user-visible changes
- https://github.com/oscarlab/graphene/pull/2075 -- logging, mostly interesting for developers/debuggers, log messages of Graphene change a bit

That's all from the top of my head.

**Comment by mkow** [comment]
We also plan to add EDMM support (dynamic memory on SGX), but that's at least a few months of work.
