### ISSUE TITLE
IPC subsystem needs to be rewritten

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#2107]
## Description of the problem

This subsystem is one huge hack and is full of bugs, we need to write it from scratch.

## Steps to reproduce

Try doing anything using IPC.

## Expected results

It works if your change is correct.

## Actual results

Nothing works because of bugs in IPC :)

**Comment by dimakuv** [comment]
To be honest, we need to properly prepare for this IPC rewrite. It's not just a matter of emulating what Linux does, it's a matter of writing a clean and performant *distributed OS primitives*.

I guess some background reading on microkernels, IPC messages, and alike is a pre-requisite here.
