### ISSUE TITLE
regression test failed using in-kernel SGX driver (kernel version 5.11+)

### ISSUE THREAD

**Issue by johnvenn** [oscarlab/graphene#2114]
## Description of the problem
compilation error in regression test:
File "/home/sgx_xiangping/graphene/graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token", line 19, in <module>
    sys.exit(main())
  File "/home/sgx_xiangping/graphene/graphene/python/graphenelibos/sgx_get_token.py", line 203, in main
    token = connect_aesmd(attr)
  File "/home/sgx_xiangping/graphene/graphene/python/graphenelibos/sgx_get_token.py", line 126, in connect_aesmd
    raise Exception("Failed. (Error Code = %d)" % (ret_msg.ret.error))
Exception: Failed. (Error Code = 30)
../../../../Scripts//../Pal/src/host/Linux-SGX/manifest.mk:19: recipe for target 'abort.token' failed
make: *** [abort.token] Error

## Steps to reproduce
pulling the latest graphene code.(Head:1b8848bdae09fa0e92e4644b7fbd4e8c6cd1718c)
OS: ubuntu 18.04 
SGX in-kernel driver upstream and remap was done /dev/sgx_enclave --> /dev/sgx/enclave, /dev/sgx_provision --> /dev/sgx/provision

doing regression test under LibOS/shim/test/regression, error while "make SGX=1 sgx-tokens"

##User's comment:
is there any suggestion on how to solve/debug this issue?

**Comment by dimakuv** [comment]
Did you install the latest Inel SGX SDK/PSW?

The error complains about AESM daemon. This daemon is a part of Intel SGX PSW installation.

Also, please check the examples from Intel SGX SDK work on your machine. If they don't work, then something is wrong with SGX installation on your machine (and thus Graphene will not work too).

**Comment by johnvenn** [comment]
well, I checked again, the Sample Enclave failed. This is a device I used to do regression test with the latest release. I will check the reason.

**Comment by johnvenn** [comment]
> Did you install the latest Inel SGX SDK/PSW?
> 
> The error complains about AESM daemon. This daemon is a part of Intel SGX PSW installation.
> 
> Also, please check the examples from Intel SGX SDK work on your machine. If they don't work, then something is wrong with SGX installation on your machine (and thus Graphene will not work too).

reopen this because I tested again on the same platform, SGX PSW aesmd service is ok, SampleEnclave ok in SGX SDK installer, but LibOS/shim/test/regression compilation into the same error.

**Comment by dimakuv** [comment]
What versions of SGX PSW and the Intel SGX driver do you have on your system?

**Comment by johnvenn** [comment]
> What versions of SGX PSW and the Intel SGX driver do you have on your system?

The new version of SGX PSW, 2.13....

**Comment by dimakuv** [comment]
How to get this version 2.13? I can only see the latest 2.12 version... See https://github.com/intel/linux-sgx/releases and https://01.org/intel-software-guard-extensions/downloads.

**Comment by johnvenn** [comment]
> How to get this version 2.13? I can only see the latest 2.12 version... See https://github.com/intel/linux-sgx/releases and https://01.org/intel-software-guard-extensions/downloads.

yes, the newer version is to be released, if you want it, i can provide you, you can contact me via email...

**Comment by dimakuv** [comment]
We debugged this issue. It turned out it has nothing to do with SGX PSW and AESMD.

The real reason was the corrupted `gsgx.h` and `generated-offsets.py`. Basically, when Graphene Linux-SGX PAL build fails for some reason (typically when the user forgets to set `ISGX_DRIVER_PATH`), then our build system doesn't notice the failure and continues creating bogus `gsgx.h` and `generated-offsets.py` (hurray Makefiles!). In the best case, this leads to immediate failure of other parts of the build, in the worst case it manifests itself as in this issue.

We will need to fix our Makefiles, but for now the solution is to clean Graphene completely:
```
cd <graphene root dir>
make distclean
make SGX=1 distclean
# now Graphene dir is clean again, we can rebuild
make -j
make -j SGX=1 ISGX_DRIVER_PATH=<your Intel SGX driver path>
```

**Comment by johnvenn** [comment]
yes, I checked that after "make clean", gsgx.h is still there, I thought it should be removed.

**Comment by mkow** [comment]
@johnvenn We recently fixed some bugs in our Makefiles related to this, could you check again?

**Comment by johnvenn** [comment]
> @johnvenn We recently fixed some bugs in our Makefiles related to this, could you check again?

sure, I will find some time do it early next week.

**Comment by johnvenn** [comment]
> @johnvenn We recently fixed some bugs in our Makefiles related to this, could you check again?

could you tell me which PR fixed the issue?

**Comment by johnvenn** [comment]
The problem is fixed.

**Comment by johnvenn** [comment]
verified on commit bfb2f33d3b3782d4573fb9265f6bdf8a0d4a08f9 (HEAD -> master, origin/master, origin/HEAD)

**Comment by mkow** [comment]
> could you tell me which PR fixed the issue?

I think it was #2132 specifically.

> The problem is fixed.

Good, I'm closing it then.
