### ISSUE TITLE
docker build of gsc does not take env into account

### ISSUE THREAD

**Issue by orangecalculator** [oscarlab/graphene#2117]
## Description of the problem
Sometimes one might need a custom docker host. (kubernetes docker for my case) However, `gsc build` command fails to build on the custom docker host pointed by the bash environment variables. Instead, it issues the build command on the default docker host which is listening on `unix://var/run/docker.sock`. 

I have analyzed some of the code on the repository. I have tested using commit `a37a85ba` but the latest commit `0a88f93d` doesn't seem to be much modified on this part. 

At `gsc.py:220`, the script issues the build command using function `build_docker_image`. 
Then, at `gsc.py:224` the `gsc.py` script checks whether the build succeeded using the `docker_socket` client object constructed at `gsc.py:201` using `docker.from_env()`.  However, inspecting the function `build_docker_image` in `gsc.py:162` the build was issued on the default docker environment using APIClient class object `docker_api`. 

When using kubernetes, the default docker daemon is not used, so this leads to a misleading behavior. 

## Steps to reproduce

I have tested using commit `a37a85ba` but the latest commit `0a88f93d` doesn't seem to be much modified on this part. I have used this commit because the `Tools/gsc/config.yaml.template` of the master branch uses this commit. 

I was trying to use gsc on docker of kubernetes. 

```
minikube start

eval $(minikube docker-env)

cd $GRAPHENE_DIR/Tools/gsc

./gsc build --insecure-args python test/ubuntu18.04-python3.manifest
```

## Expected results
output ending with follows. workaround applied.
```
Successfully built d0d55e66b30d
Successfully tagged gsc-python-unsigned:latest
Successfully graphenized docker image python into docker image gsc-python-unsigned
```

## Actual results
output ending with follows.
```
Successfully built ec9e5cceb893
Successfully tagged gsc-python-unsigned:latest
Failed to build graphenized image for python
```

## Additional information

I have found 2 workarounds for making this work. 

# Method 1
Just use method `docker_socket.images.build` instead of function `build_docker_image`. However, this workaround does not show the docker build command output, i.e. the docker build command runs silently. I figure the source tried to avoid this. Am I right?

# Method 2
Modify `build_docker_image` function. Currently the function newly constructs the APIClient object from socket `unix://var/run/docker.sock`. Instead, receive the backend of `docker_socket` object used in functions `gsc_build`, `gsc_sign_image`, `gsc_build_graphene` and others. We could access the backend of `docker_socket` by referencing `docker_socket.api`. Warning, [this](https://github.com/docker/docker-py/blob/ce2669e3edfe5d3215ba501cc9771fc0ffad680a/docker/client.py#L45) is not a documented feature of the package and could be changed, as far as I know. See `git diff` output. 

```
diff --git a/Tools/gsc/gsc.py b/Tools/gsc/gsc.py
index 565e7f47..d3e6b67e 100755
--- a/Tools/gsc/gsc.py
+++ b/Tools/gsc/gsc.py
@@ -159,8 +159,8 @@ def get_docker_image(docker_socket, image):
     except (docker.errors.ImageNotFound, docker.errors.APIError):
         return None
 
-def build_docker_image(path, name, dockerfile, **kwargs):
-    docker_api = docker.APIClient(base_url='unix://var/run/docker.sock')
+def build_docker_image(docker_api, path, name, dockerfile, **kwargs):
+    #docker_api = docker.APIClient(base_url='unix://var/run/docker.sock')
     # Docker build returns stream of json output
     stream = docker_api.build(path=path,
                               tag=name,
@@ -217,7 +217,7 @@ def gsc_build(args):
 
     buildargs_dict = extract_build_args(args)
 
-    build_docker_image(gsc_image_name(image), gsc_unsigned_image_name(image), 'Dockerfile.build',
+    build_docker_image(docker_socket.api, gsc_image_name(image), gsc_unsigned_image_name(image), 'Dockerfile.build',
                        rm=args.rm, nocache=args.no_cache, buildargs=buildargs_dict)
 
     # Check if docker build failed
@@ -269,7 +269,7 @@ def gsc_build_graphene(args):
     else:
         buildargs_dict = extract_build_args(args)
 
-        build_docker_image(image, image, 'Dockerfile.compile',
+        build_docker_image(docker_socket.api, image, image, 'Dockerfile.compile',
                        rm=args.rm, nocache=args.no_cache, buildargs=buildargs_dict)
 
         # Check if docker build failed
@@ -314,7 +314,7 @@ def gsc_sign_image(args):
     try:
         # We force the removal of intermediate Docker images to not leave the signing
         # key in a Docker container.
-        build_docker_image(gsc_image_name(image), gsc_image_name(image),
+        build_docker_image(docker_socket.api, gsc_image_name(image), gsc_image_name(image),
                            'Dockerfile.sign_manifests', forcerm=True)
 
     finally:
```

**Comment by dimakuv** [comment]
Thanks @orangecalculator ! This is a really great analysis!

> Just use method docker_socket.images.build instead of function build_docker_image. However, this workaround does not show the docker build command output, i.e. the docker build command runs silently. I figure the source tried to avoid this. Am I right?

You are absolutely correct. We wanted to show the command output so the user knows that there is ongoing progress in the Docker image build.

> Modify build_docker_image function. Currently the function newly constructs the APIClient object from socket unix://var/run/docker.sock. Instead, receive the backend of docker_socket object used in functions gsc_build, gsc_sign_image, gsc_build_graphene and others. We could access the backend of docker_socket by referencing docker_socket.api. Warning, this is not a documented feature of the package and could be changed, as far as I know. 

I love you Method 2. So I incorporated it inside my GSC-refactoring PR https://github.com/oscarlab/graphene/pull/2112. Thanks for the git diff! I understand that the feature is undocumented, but looks like this was introduced a long time ago and didn't change, so I think it's fine to use it for now.
