### ISSUE TITLE
[LibOS] some syscalls are not debug printed correctly

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#2118]
## Description of the problem
`char* name` parameter is removed for `parse_syscall_before()` in #2077.  However not all syscalls are listed in `struct parser_table`. These syscalls can be printed  before this commit but cannot now.
## Steps to reproduce
build `/Examples/bash` with command `make DEBUG=1 SGX=1`. 
run with command `SGX=1 ./pal_loader bash` and see the end of log.

## Expected results
```
[P22250:T1:bash] ---- shim_rt_sigaction([SIGCHLD],0x18e498d0,0x18e49970,8) = 0
[P22250:T1:bash] ---- shim_prlimit64(0,6,0x0,0x18e49af0) = 0
[P22250:T1:bash] ---- shim_rt_sigprocmask(BLOCK,NULL,[]) = 0
[P22250:T1:bash] ---- shim_fcntl(0,F_GETFL,0x0) = 0
[P22250:T1:bash] ---- shim_fstat(0,0x18e49bd0) = 0
[P22250:T1:bash] ---- shim_lseek(0,0,SEEK_CUR) = -29
[P22250:T1:bash] ---- shim_read(0,0x18dd1ff0,1) ... read
```
## Actual results
```
[P23165:T1:bash] ---- shim_rt_sigaction([SIGCHLD], 0x47468b0, 0x4746950, 0x8) = 0x0
[P23165:T1:bash] ---- shim_syscall302()
[P23165:T1:bash] ---- shim_rt_sigprocmask(BLOCK, NULL, []) = 0x0
[P23165:T1:bash] ---- shim_fcntl(0, F_GETFL, 0x0) = 0x0
[P23165:T1:bash] ---- shim_fstat(0, 0x4746bb0) = 0x0
[P23165:T1:bash] ---- shim_lseek(0, 0x0, SEEK_CUR) = -29
[P23165:T1:bash] ---- shim_read(0, 0x525a020, 0x1) ...
```
Log for syscall `prlimit64` is incorrect.

**Comment by dimakuv** [comment]
@boryspoplawski What do you think about this? i also don't like the output now... And why `prlimit64()` succeeded before? I thought you print `shim_syscallXXX` only on not-implemented syscalls.

**Comment by llly** [comment]
`prlimit64()` is supported.
https://github.com/oscarlab/graphene/blob/8ca27bd3c4acece11e971df5833cc9c53c4ad8d9/LibOS/shim/src/sys/shim_getrlimit.c#L116
Maybe need to check `struct parser_table` and add all implemented syscalls.
