### ISSUE TITLE
[LibOS] Incorrect behavior of recv() with MSG_PEEK flag on ended stream

### ISSUE THREAD

**Issue by llly** [oscarlab/graphene#2131]
## Description of the problem
behavior of `recv()` with `MSG_PEEK` flag on ended stream are incorrect on Graphene.

## Steps to reproduce
duplicate the three line in `tcp_msg_peek.c` to recv() with PSG_PEEK twice.
https://github.com/oscarlab/graphene/blob/cf0bfdf67a44473a6a463a48d96ad339dd8173ee/LibOS/shim/test/regression/tcp_msg_peek.c#L177-L179
Run this test without and with Graphene.

## Expected results
```
./tcp_msg_peek
[server] client is connected...
[server] done
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving without MSG_PEEK: Hello from server!
[client] checking how many bytes are left unread: 0
[client] done
```

## Actual results
```
 ./pal_loader tcp_msg_peek
[server] client is connected...
[server] done
[client] receiving 20 bytes with MSG_PEEK: Hello from server!
[client] receiving 0 bytes with MSG_PEEK: [client] receiving without MSG_PEEK: [client] checking how many bytes are left unread: 0
[client] done
```
 ## Additional information
This root cause of this issue is pal error code `PAL_ERROR_ENDOFSTREAM` is not handled correctly at
https://github.com/oscarlab/graphene/blob/cf0bfdf67a44473a6a463a48d96ad339dd8173ee/LibOS/shim/src/sys/shim_socket.c#L1319-L1327

It's similar to #2078.  Maybe we need to review all `DkStreamRead` usage.

**Comment by dimakuv** [comment]
@llly Are you working on a PR to fix this (and #2078)?

**Comment by llly** [comment]
No. Do you want me to fix them?

**Comment by dimakuv** [comment]
That would be great :) We don't have anyone assigned to these bugs.

**Comment by llly** [comment]
OK. I'll create PR to fix `PAL_ERROR_ENDOFSTREAM` issues.
