### ISSUE TITLE
[Fundamental Question] Can graphene-sgx be used to secure part of an application

### ISSUE THREAD

**Issue by SamuelGong** [oscarlab/graphene#2141]
Hi, we are new to graphene-sgx. It seems to us that graphene-sgx can be used to port an entire Python application to Intel SGX. However, our use case is that only part of the application (i.e., several functions) need to be executed in enclaves, while we do not need to protect other part of the application. Can graphene-sgx support such a scenario? Thank you for your attention!

**Comment by mkow** [comment]
Only if you split them into a separate process.
In this case it's not even related to Graphene directly, but to the problem that Python is an interpreted language, and the interpreter has to also reside inside the enclave to securely execute the functions you chose. But then you can't have some of the source executed outside the enclave, as the interpreter is already inside.

**Comment by SamuelGong** [comment]
I see. Thanks for your clarification!
