### ISSUE TITLE
[LibOS] Unlink of empty path as dir causes failure

### ISSUE THREAD

**Issue by jinengandhi-intel** [oscarlab/graphene#2142]
## Description of the problem
Unlinking of empty dirpath should result in ENOENT, whereas in Graphene OS it returned EISDIR. 
Result from the Graphene native run is as follows:

shresthi@ubuntu-test-base:~/Graphene_Master/LibOS/shim/test/ltp/install/testcases/bin$ sudo ./pal_loader ./unlink07_run
TPASS: unlink(<non-existent file>) failed as expected: ENOENT (2)
TFAIL: unlink(<path is empty string>) failed, expected errno: ENOENT: EISDIR (21)
TPASS: unlink(<path contains a non-existent file>) failed as expected: ENOENT (2)
TPASS: unlink(<invalid address>) failed as expected: EFAULT (14)
TPASS: unlink(<path contains a regular file>) failed as expected: ENOTDIR (20)
TPASS: unlink(<pathname too long>) failed as expected: ENAMETOOLONG (36)
Summary:
passed   5
failed   1
skipped  0
warnings 0

## Steps to reproduce

To repro this issue, run unlink07_setup in linux native and unlink07_run in Graphene environment.
[unlink07.zip](https://github.com/oscarlab/graphene/files/5942328/unlink07.zip)

**Comment by anjalirx-intel** [comment]
@mkow  Fixed with Latest master. Can you please close this issue
