### ISSUE TITLE
[LibOS] Graphene doesn't support/hold file permissions

### ISSUE THREAD

**Issue by jinengandhi-intel** [oscarlab/graphene#2144]
## Description of the problem

Stat03: {TST_EACCES_FILE, EACCES},
The testcase is trying to access file from the directory which does not have required permissions. In linux native it returns permission denied error(EACCESS) as expected whereas in Graphene it is able to access the file successfully. Another subtest of Stat03 tries to access the directory which has a symbolic link reference to its starting directory. In Linux native when it tries to access the directory, it returns “Too many levels of symbolic links error(ELOOP)” but in graphene native, the test fails with directory does not exist error(ENOENT) expected: 40 - ELOOP: got ENOENT (2)

Open02: The test case tries to open the file (testfile2) with 0444 permissions and actually succeeds in doing that thus hitting the fail condition ““open succeeded unexpectedly” instead of "open() failed as expected"

Test Summary:
TPASS: open() failed as expected: ENOENT (2)
TFAIL: open(/tmp/test_file2) succeeded unexpectedly

## Steps to reproduce

To repro this issue, run stat03_setup in linux native and stat03_run in Graphene environment. To repro open02 issue, run open02_setup in linux native and open02_run in Graphene environment
[CFiles.zip](https://github.com/oscarlab/graphene/files/5942546/CFiles.zip)

**Comment by mkow** [comment]
I don't think this is something we actually plan to implement. There's a partial support for this after FS rewrite (I think only user permissions), but the rest doesn't seem to be worth implementing.
