### ISSUE TITLE
Building quick start instructions fails

### ISSUE THREAD

**Issue by panaotizz** [oscarlab/graphene#2145]
## Description of the problem
I have been trying to install graphene in an SGX enabled Azure VM and when i run 

` ISGX_DRIVER_PATH=/usr/src/linux-headers-`uname -r`/arch/x86/ make SGX=1`

the build fails giving this error

`graphene/Pal/src/host/Linux-SGX//../Pal/src/pal-symbols', needed by 'pal.map'.  Stop.`

I'm really confused on what to do. Searching on previous issues i see that the instructions to build were different (make SGX_RUN=1), not sure how i should build now, same applies for the examples in the repository. 
When i try to build the examples, pal_loader is not found

Thank you in advance

**Comment by mkow** [comment]
This is weird, the file which your Make is supposedly missing is a part of our repo... Are you sure you haven't deleted it accidentally? Could you check `git status`?

**Comment by boryspoplawski** [comment]
This is reproducible on the current master. Just run make again, after the initial build.

**Comment by mkow** [comment]
I wasn't able to reproduce it, even after running `make` again. Anyways, leaving this to Borys as he has a debuggable repro :)

**Comment by panaotizz** [comment]
> This is weird, the file which your Make is supposedly missing is a part of our repo... Are you sure you haven't deleted it accidentally? Could you check `git status`?

On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Comment by panaotizz** [comment]
> This is reproducible on the current master. Just run make again, after the initial build.

after the initial build meaning? 
this? : ISGX_DRIVER_PATH=/usr/src/linux-headers-`uname -r`/arch/x86/ make SGX=1

**Comment by boryspoplawski** [comment]
@panaotizz We've already fixed this (see the linked PR that closed this issue). Try on the up to date master, should work.

**Comment by panaotizz** [comment]
> @panaotizz We've already fixed this (see the linked PR that closed this issue). Try on the up to date master, should work.
/
I just saw thank you so much. Is there a way to apply the changes with git without cloning it again? I'm sorry i never got hold of git and its branches

**Comment by mkow** [comment]
Yup, just do `git pull origin master`.

**Comment by panaotizz** [comment]
Running it gives me: * branch ,asteer =? FETCH_HEAD
Already up to date.

Is this intended? Cause its still giving me the aformentioned error

**Comment by mkow** [comment]
Try `make SGX=1 distclean` and then build again, should help.

**Comment by panaotizz** [comment]
Thanks! Should i build my applications with make SGX=1 or make SGX=1 sgx-tokens ?
