### ISSUE TITLE
protected_files not working with paths starting with ./

### ISSUE THREAD

**Issue by thomasten** [oscarlab/graphene#2175]
## Description of the problem
While this
```
sgx.protected_files.foo = "file:foo"
```
works, this
```
sgx.protected_files.foo = "file:./foo"
```
does not. But these
```
sgx.trusted_files.foo = "file:./foo"
sgx.allowed_files.foo = "file:./foo"
```
do work.

## Steps to reproduce
5492d808a771841d26fff3b276f6ac92ead40006
* add `sgx.protected_files.foo = "file:./foo"` to manifest
* `int main() { fopen("foo", "w"); }`

## Expected results
fails because `wrap key was not provided`

## Actual results
succeeds and creates an unencrypted file

**Comment by dimakuv** [comment]
As you may already know, Protected Files add the *relative* path name to the mix of "security-relevant information", over which the secure hash is taken. See https://www.tatetian.io/2017/01/15/understanding-sgx-protected-file-system/ (`Matching of file name`).

So from what I understand, in your case there is a mismatch between the command you used to encode the protected file (`./pf_crypt encrypt -w files/wrap-key -i foo`) and the way you write it in the manifest file (`"file:./foo"`). In this case, the difference is in the `./`. (I'm giving this explanation just for the context and for your understanding, I agree that this is a bug.)

I agree that this difference should NOT be accounted for. It looks like our Protected Files code doesn't canonize all these `.` and `..` parts in the file name. I hope I'll be able to quickly fix it this week. Thanks for the bug report!

**Comment by thomasten** [comment]
Thanks @dimakuv. I actually did not know that. Thought it works like trusted and allowed files.

However, in my use case I want to write a file that does not exist yet. Is this a supported way of using Protected Files? It seems to work fine if I put `file:foo` in the manifest.

**Comment by dimakuv** [comment]
> However, in my use case I want to write a file that does not exist yet. Is this a supported way of using Protected Files? It seems to work fine if I put file:foo in the manifest.

Yes, you can do that. You just have to be careful with the relative file names, as I explained above.

**Comment by sahason** [comment]
@dimakuv Please  assign this bug to me.

**Comment by sahason** [comment]
@thomasten This issue is not seen with latest master. Could you please confirm and close this?

**Comment by dimakuv** [comment]
Let's close this issue then. If this issue is still there, @thomasten, feel free to reopen.
