### ISSUE TITLE
Encrypt entire directories using protected_files

### ISSUE THREAD

**Issue by panaotizz** [oscarlab/graphene#2178]
Hello. I have been looking in the ra-tls-secret-prov example where a 'plain.txt' file is encrypted using the wrap_key once the enclave is created. 
In the docs this is mentioned:
`URIs can be files or directories. If a directory is specified, all existing files/directories within it are registered as protected recursively (and are expected to be encrypted in the PF format). New files created in a protected directory are automatically treated as protected.`

i added my directory as the URI in the manifest but what about the makefile? The example encrypts the file using 
`	LD_LIBRARY_PATH=. ./pf_crypt encrypt -w files/wrap-key -i files/plain.txt -o $@`

How can this be applied for a directory? Should i encrypt each file 1 by 1 in a loop inside the makefile? 
Thank you in advance

**Comment by dimakuv** [comment]
You can supply the directory argument to `pf_crypt`, like this:
```
LD_LIBRARY_PATH=. ./pf_crypt encrypt -w files/wrap-key -i files-to-encrypt/ -o files-encrypted/
```

This way, `pf_crypt` will go through all files and subdirectories of the root dir `files-to-encrypt/`, encrypt them, and put them (using the same file names) under `files-encrypted/`. Note that subdirectories will also be encrypted -- recursively.

The same applies to the `pf_crypt decrypt` mode.

**Comment by panaotizz** [comment]
Thank you so much @dimakuv, much appreciated!

**Comment by panaotizz** [comment]
Thank you so much @dimakuv, much appreciated!
