### ISSUE TITLE
readlink("/proc/self/exe") fails when run from python script using subprocess.run

### ISSUE THREAD

**Issue by svenkata9** [oscarlab/graphene#2185]
When run from inside the python script using subprocess.run, readlink("/proc/self/exe") fails with EINVAL. It appears that the exec's dentry is somehow not updated and is NULL. The same readlink call when run from a simple C program (even with fork) works well and succeeds. Attached is the zip containing both the C version and Python version of calling these - including the manifest.
[proc_self_exe.zip](https://github.com/oscarlab/graphene/files/6027018/proc_self_exe.zip).

It can be reproduced with master. Certain workloads like Tensorflow seems to be depending on this and hence I request to prioritize this one.

@dimakuv @mkow

**Comment by stefanberger** [comment]
The solution may be as easy as this:

```
diff --git a/LibOS/shim/src/sys/shim_exec.c b/LibOS/shim/src/sys/shim_exec.c
index df7b9cb5..57dbe066 100644
--- a/LibOS/shim/src/sys/shim_exec.c
+++ b/LibOS/shim/src/sys/shim_exec.c
@@ -216,6 +216,7 @@ reopen:
     set_handle_fs(exec, fs);
     exec->flags    = O_RDONLY;
     exec->acc_mode = MAY_READ;
+    exec->dentry   = dent;
     ret = fs->d_ops->open(exec, dent, O_RDONLY);
 
     if (qstrempty(&exec->uri)) {
```

**Comment by stefanberger** [comment]
Now this works:

```
~/graphene/Examples/bash$ ./pal_loader bash -c "readlink /proc/self/exe" 
WARNING: Using insecure argv source. Don't use this configuration in production!
/bin/readlink
```
