### ISSUE TITLE
Graphene with SGX error : "{RD,WR}{FS,GS}BASE instructions are not permitted on this platform

### ISSUE THREAD

**Issue by snedu99** [oscarlab/graphene#2189]
I have Graphene with SGX built on Ubuntu 18.04:

<
Linux sgxtest 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
>

 I have the Graphene sgx driver installed to enable FSGSBASE:
<
lsmod|grep sgx

gsgx                   16384  0
isgx                   53248  2
>

CPUinfo shows:
<
cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 142
model name	: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
stepping	: 10
microcode	: 0xca
cpu MHz		: 800.030
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 3600.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
>

While running the helloworld program. I get the following error:

<
SGX=1 ~/Tools/graphene/Runtime/pal_loader helloworld
{RD,WR}{FS,GS}BASE instructions are not permitted on this platform. Please check the instructions under "Building with SGX support" from Graphene documentation.
*** Unexpected exception occurred inside PAL at RIP = +0x0000be64! ***
(SGX HW reported AEX vector 0x6 with exit_type = 0x3)
rax: 0x0ff5f010 rcx: 0x0f686d80 rdx: 0x0b691c88 rbx: 0x00000000
rsp: 0x0ff5db88 rbp: 0x00000000 rsi: 0x00000000 rdi: 0x00000000
r8 : 0x0b178020 r9 : 0x0f68af58 r10: 0x00000000 r11: 0x0b45cd0c
r12: 0x00000003 r13: 0x0ff5dd58 r14: 0x0b1b64d0 r15: 0x0ff5dd68
rflags: 0x00010246 rip: 0x0b44de64
>

However, while running the intel SGX SDK sampleprogram (SampleEnclave), it works fine:

<
./app
Checksum(0x0x7ffc37d96b80, 100) = 0xfffd4143
Info: executing thread synchronization, please wait...  
Info: SampleEnclave successfully returned.
Enter a character before exit ...
>

I had earlier tried with Ubuntu 20.04 as well. I get the same error there too.

Is this a new problem?

**Comment by mkow** [comment]
No, please just do as asked in the very log you pasted: "{RD,WR}{FS,GS}BASE instructions are not permitted on this platform. Please check the instructions under "Building with SGX support" from Graphene documentation." :)
Here's the link: https://graphene.readthedocs.io/en/latest/building.html#building-with-sgx-support.

The gsgx driver shouldn't be used anymore, it's just a dirty hack for testing purposes.

**Comment by snedu99** [comment]
I am just trying to test that's why I didn't want to patch the kernel and instead try with the gsgx driver. This was not for use in production.

**Comment by mkow** [comment]
Yeah, but it's _really_ a dirty hack and you shouldn't use it ;) I think it doesn't work anymore on the kernel shipped with Ubuntu 18.04 and 20.04, because the kernel implemented a protection from such dirty hacks trying to forcefully enable FSGSBASE.
You'll need to use a newer kernel.

I know this isn't convenient from the user's perspective, but there's not much we can do about it. The situation will get much better soon, after distributions pick up the kernels with FSGSBASE and the SGX driver. Until then using SGX LibOSes will require some pains in the setup.
