### ISSUE TITLE
Bug: uninitialized `pipe.nonblocking` for the read file descriptor on `pipe()`

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#219]
(For simplicity, I only mention Graphene-SGX code but the bug holds also for other PALs)

When testing Redis 5 (https://github.com/antirez/redis/tree/5.0-rc1), I encountered the following bug.

Redis 5 introduces new functionality (modules) that uses non-blocking `read()` on a read end of the pipe:
```
src/module.c:4340   if (pipe(server.module_blocked_pipe) == -1) { ...  // create the pipe
...
src/module.c:4348   anetNonBlock(NULL,server.module_blocked_pipe[0]);  // set O_NONBLOCK via fcntl()
src/module.c:4349   anetNonBlock(NULL,server.module_blocked_pipe[1]);  // set O_NONBLOCK via fcntl() 
...
src/module.c:3588   while (read(server.module_blocked_pipe[0],buf,1) == 1);  // expects non-blocking read
```

In Graphene-SGX, the `pipe()` syscall ends up in `shim_pipe.c: create_pipes()`.

* The write file descriptor (`hdl2`) of the pipe is created via `DkStreamOpen() -> ... -> pipe_connect()`. In `pipe_connect()`, the file descriptor's `pipe.nonblocking` is correctly initialized to either TRUE or FALSE.

* The read file descriptor (`hdl1`) of the pipe is created via `DkStreamWaitForClient() -> ... -> pipe_waitforclient()`. The bug lurks here: `pipe_waitforclient()` *forgets* to initialize `pipe.nonblocking`, thus this variable contains garbage.

Now that `pipe.nonblocking` for the read FD contains garbage, the following happens:

1. Redis performs `fcntl(readfd, F_SETFL, O_NONBLOCK)` as part of `anetNonBlock()`

2. Graphene-SGX ends up in `LibOS/shim/src/fs/pipe/fs.c: pipe_setflags()` which verifies the correctness of requested syscall:
```
    if (attr.nonblocking) {
        if (flags & O_NONBLOCK)
            return 0;
        attr.nonblocking = PAL_FALSE;
    } else {
        if (!(flags & O_NONBLOCK))
            return 0;
        attr.nonblocking = PAL_TRUE;
    }
   ... actual fcntl syscall ...
```

3. Since `attr.nonblocking` for our read FD contains garbage, Graphene-SGX wrongly assumes that underlying FD is already non-blocking and simply does `return 0`.

4. Now, the underlying actual FD is blocking and Redis hangs on line 3588.

Bug fix is trivial: add `clnt->pipe.nonblocking = PAL_FALSE;` in `db_pipes.c`. This should be done for every supported PAL host (since this bug is in all of them). Here is the patch for Linux-SGX version only:
```
diff --git a/Pal/src/host/Linux-SGX/db_pipes.c b/Pal/src/host/Linux-SGX/db_pipes.c
index 5e55002..5d3638f 100644
--- a/Pal/src/host/Linux-SGX/db_pipes.c
+++ b/Pal/src/host/Linux-SGX/db_pipes.c
@@ -106,6 +106,7 @@ static int pipe_waitforclient (PAL_HANDLE handle, PAL_HANDLE * client)
     HANDLE_HDR(clnt)->flags |= RFD(0)|WFD(0)|WRITEABLE(0);
     clnt->pipe.fd = ret;
     clnt->pipe.pipeid = handle->pipe.pipeid;
+    clnt->pipe.nonblocking = PAL_FALSE;
     *client = clnt;

     return 0;
```

**Comment by donporter** [comment]
@dimakuv Thanks for the report and fix!  I assume that this bug only manifests after some number of iterations (i.e., not easy to write a simple unit test for this functionality)?

**Comment by dimakuv** [comment]
@donporter I will try to come up with a simple unit test tomorrow. The problem is, I don't know how to generalize the test for general use-cases of non-blocking pipes, i.e., the unit test will only cover this particular bug. Would that be good enough?

**Comment by donporter** [comment]
That would be much appreciated, if it is easy to do.  I suspect it won't really show the problem, or, at least, it would only show the problem if you run it with memory poisoning enabled, or recycle the descriptors repeatedly.

I suppose a unit test for just non-blocking pipes working correctly would be useful, even if it doesn't fail on the current master.  But don't worry about it if it isn't easy.

**Comment by donporter** [comment]
If you get a unit test, that would still be swell, but not worries if not.  We applied this fix to master, so I'm going to close the issue.
