### ISSUE TITLE
 Python vulnerabilities reported by Bandit

### ISSUE THREAD

**Issue by jurobystricky** [oscarlab/graphene#2199]
## Description of the problem

Running code scan using **_bandit_** https://github.com/PyCQA/bandit  reported numerous security problems.

Code scanned:
	Total lines of code: 23659
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 143.0
		Medium: 8.0
		High: 15.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 3.0
		Medium: 4.0
		High: 159.0

## Steps to reproduce
<pre>
$ sudo pip3 install bandit
$ cd graphene
$ bandit -r .
</pre>

The generated output is quite verbose with detailed descriptions with suggested remedies.

## Expected results

No security violations

## Actual results

Numerous high category violations

**Comment by mkow** [comment]
Hi, thanks for the report, but reporting plain output from linters or similar checkers isn't really useful - they usually contain a lot of false-positive noise.
It would be useful if you could analyze the log and report only the issues which you think are actually security issues.

**Comment by dimakuv** [comment]
@jurobystricky  Thanks for the idea of using Bandit to test our Python scripts.

I agree with @mkow that there are many false positives produced by such tools. Also, we currently have Python scripts like https://github.com/oscarlab/graphene/blob/master/python/graphenelibos/sgx_sign.py which are old and badly written -- these scripts need a re-write first, and then we can apply Bandit to check for vulnerabilities.
