### ISSUE TITLE
GSC production status on cloud service providers

### ISSUE THREAD

**Issue by rahulunair** [oscarlab/graphene#2211]
Hi, 

I have been looking thorough the projects to see if graphene can be used for PPML in production environments. I have seen issues[1][2] that are open blocking production status of grapehene, but there is documentation[3] on how to use graphene shielded containers on AKS, can you please confirm if graphene is production ready or not and if the AKS solution can be used for prod deployment ?

[1]. https://github.com/oscarlab/graphene/issues/1544
[2]. https://github.com/oscarlab/graphene/issues/1520
[3]. https://graphene.readthedocs.io/en/latest/cloud-deployment.html?highlight=containers#azure-kubernetes-services-aks

**Comment by dimakuv** [comment]
Graphene is currently **not** production ready.

The AKS solution can **not** be used for production deployment.

We are working on making both Graphene and the GSC tool production-ready.
