### ISSUE TITLE
open to contributions?

### ISSUE THREAD

**Issue by rahulunair** [oscarlab/graphene#2217]
Hi, 

I was trying to update the docs, is the repo open to external contributions?

**Comment by dimakuv** [comment]
Hi,

Yes, we can see your contribution: https://github.com/oscarlab/graphene/pull/2216. I already reviewed and approved it. There will be two more reviews/approvals, and then we'll merge this PR. Thanks for contributing!

**Comment by rahulunair** [comment]
Thank you @dimakuv
