### ISSUE TITLE
Issue running helloworld quickstart without SGX support

### ISSUE THREAD

**Issue by jaddoescad** [oscarlab/graphene#2235]
## Description of the problem
Issue Running Hello world application without sgx support in quickstart

## Steps to reproduce

follow quickstart
ran `./pal_loader helloworld`

## Expected results
running hello world

## Actual results

**

> Invalid application path specified (helloworld.manifest does not exist).
> The path should point to application configuration files, so that they can be
> found after appending corresponding extensions.

**

**Comment by mkow** [comment]
I just tested it and it worked. Are you sure you didn't forgot the `make` step in `regression` directory?

**Comment by dimakuv** [comment]
Same for me. @jaddoescad Can you reproduce your issue? I don't see why this won't work (unless Graphene build itself failed, but in this case you would see some errors).
