### ISSUE TITLE
[GSC] Occassional errors in test-5-ubuntu18.04

### ISSUE THREAD

**Issue by jurobystricky** [oscarlab/graphene#2237]
## Description of the problem
Repeatedly running GSC test test-5-ubuntu18.04 results in occasional errors such as those listed below.
I was able to reproduce the errors both on base metal host and in a VM.
These errors are very rare (once every 100 or so runs), most likely due to a subtle race condition.

<pre>
5/9: make[1]: Entering directory '/home/juro/graphene/Tools/gsc/test'
docker run  --device=/dev/sgx/enclave   gsc-ubuntu18.04-python3 -c 'import os;os.system("ls")' 2>&1 | tee out
+ '[' -z '' ']'
+ GSC_PAL=Linux-SGX
+ /graphene/python/graphene-sgx-get-token -output /entrypoint.token -sig /entrypoint.sig
Attributes:
    mr_enclave:  a35db0f1617fe0acd334e20f47d393e3e05d2bc6fdf6e246a0600f9c2a0b5fbc
    mr_signer:   e6c3e4fd8274353939b3f32b53e5864f88f279912f800078b96cfa74fa1d67cb
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0600000000000000
    attr.xfrm:   e702000000000000
    misc_select: 00000000
    misc_mask:   00000000
    modulus:     692c39fc899a29da770819b760eda6e3...
    exponent:    3
    signature:   2b9f1cdaf55e4eb5c659ea0eb1bd8e8a...
    date:        2021-03-12
+ /graphene/Runtime/pal-Linux-SGX /graphene/Runtime/libpal-Linux-SGX.so init /entrypoint -c 'import os;os.system("ls")'
WARNING: Using insecure argv source. Don't use this configuration in production!
[P25:T2:python3] process creation failed
sh: 1: Cannot fork
grep -q "entrypoint.manifest.sgx" out
make[1]: Leaving directory '/home/juro/graphene/Tools/gsc/test'
</pre>

Some other error variants:
<pre>
<snip>
+ /graphene/Runtime/pal-Linux-SGX /graphene/Runtime/libpal-Linux-SGX.so init /entrypoint -c 'import os;os.system("ls")'
WARNING: Using insecure argv source. Don't use this configuration in production!
[P11:T2:python3] process creation failed
sh: 1: Cannot fork
grep -q "entrypoint.manifest.sgx" out
make[1]: Leaving directory '/home/juro/graphene/Tools/gsc/test'

<snip>
+ /graphene/Runtime/pal-Linux-SGX /graphene/Runtime/libpal-Linux-SGX.so init /entrypoint -c 'import os;os.system("ls")'
WARNING: Using insecure argv source. Don't use this configuration in production!
[P9:T1:python3] process creation failed
grep -q "entrypoint.manifest.sgx" out
</pre>

## Steps to reproduce
Repeatedly run the test, for example with the command below.
You may need to run the test a few dozen times, possibly more.

<pre>
make SGXDRIVER_REPO="" SGXDRIVER_BRANCH="" INTEL_SGX_DEVICE="sgx/enclave" ADDITIONAL_DEVICES="" ADDITIONAL_VOLUMES="" test-5-ubuntu18.04
</pre>

I was using the latest master branch, currently at:
<pre>
commit e8ebe6b452324b1d8f888d55ed02096cfb764b3f (HEAD -> master, origin/master, origin/HEAD)
Author: Stefan Berger <stefanb@linux.ibm.com>
Date:   Thu Mar 11 07:43:44 2021 -0500

    [LibOS] Update exec handle's dentry on execve()
    
    A simple test `readlink /proc/self/exe` is added to the Bash example.
    
    Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>
</pre>

The environment was kernel-5.11-rc5 with native SGX support.

## Expected results
No errors
## Actual results
Rare errors

**Comment by mkow** [comment]
Could you try running on #2232? No idea if it's related, but the bug fixed there manifested similarly ;)

**Comment by jurobystricky** [comment]
I will re-run the tests with the patch. First I need to apply the patch to my fork of Graphene and then edit relevant  files so the containers clone Graphene from the fork.

**Comment by jurobystricky** [comment]
I created GSC containers that include the patches from [#2232](https://github.com/oscarlab/graphene/pull/2232l).
Then I ran repeatedly test-5-ubuntu18.04. It did not find any problems in 500 repetitions. While absence of evidence is not evidence of absence, the patches do seem to fix the problem. Normally, I would expect several errors after this many repetitions. Having said that, I will continue running the tests for a while longer.

**Comment by mkow** [comment]
Yay! :)
Thanks for testing this and please let us know if you manage to trigger it after more runs.

**Comment by jurobystricky** [comment]
I ran the test another 1000 times, no errors found.

**Comment by mkow** [comment]
Great to hear :) Thanks for testing!
I'm closing this issue then.
