### ISSUE TITLE
Confidentiality and integrity of protected file system.

### ISSUE THREAD

**Issue by 0400H** [oscarlab/graphene#2242]
[protected file system](https://github.com/oscarlab/graphene/pull/1325) claim that it has confidentiality and integrity. 
How it achieved?

**Comment by 0400H** [comment]
Original link:

[pf_crypt.c:pf_init](https://github.com/oscarlab/graphene/blob/1102fee8f5f5ea85316b1d20a736500b0f1bc04d/Pal/src/host/Linux-SGX/tools/pf_crypt/pf_crypt.c#L95) --> [pf_util.c:mbedtls_aes_gcm_encrypt](https://github.com/oscarlab/graphene/blob/1102fee8f5f5ea85316b1d20a736500b0f1bc04d/Pal/src/host/Linux-SGX/tools/common/pf_util.c#L110)

**Comment by mkow** [comment]
No screenshots, pleaaase... Just paste the logs or just link to them ;)

**Comment by mkow** [comment]
I'm still not sure what this issue is about, closing until we get more details.
