### ISSUE TITLE
msg_next_id verification failed

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2245]
## Description of the problem
msg_next_id specifies desired id for next allocated IPC message. By default they are equal to -1. The msgget() system call returns the System V message queue identifier associated with the value of the key argument.  It may be used either to obtain the identifier of a previously created message queue, or to create a new set. In this testfile queue_id and pid did not matched which lead to msg_next_id verification failed

## TestFile
msgget04

## Expected results
root@ubuntu-test-base: ./pal_loader ./msgget04
TINFO: Timeout per run is 0h 05m 00s
TPASS: msg_next_id succeeded, queue id 3742
TPASS: /proc/sys/kernel/msg_next_id = -1

## Actual results
root@ubuntu-test-base: ./pal_loader ./msgget04
TINFO: Timeout per run is 0h 05m 00s
TFAIL: msg_next_id failed, expected id 2, but got 33
TFAIL: /proc/sys/kernel/msg_next_id != -1 got 2

**Comment by mkow** [comment]
@anjalirx-intel Could you include more context here? What's "msgget04 test"? (I know what's this because we talked previously on Slack, but others probably don't). Same for your other recent issues.
