### ISSUE TITLE
Support for additional system calls for BESS framework

### ISSUE THREAD

**Issue by sudharkrish** [oscarlab/graphene#2251]
## Description of the problem
While enabling graphene for BESS framework, came across some system calls that are used by BESS framework,
but not supported in graphene.
1. flock (I am aware that with Pavel's work for file-sharing, we may get this support).
2. msync
3. get_mempolicy
4. iopl

Just opening this PR, to get some info on whether there is any plan to add support for these system calls.

More details on BESS here-> https://github.com/NetSys/bess

**Comment by mkow** [comment]
iopl? Are you _sure_ this one is actually used?

**Comment by sudharkrish** [comment]
During launch of application, I noticed a call in graphene's debug log, with a warning that iopl is not supported.

**Comment by mkow** [comment]
But you know what is `iopl`? It enables access to some privileged x86 instructions in usermode, it makes no sense in SGX (and in general doesn't sound like something you should ever allow programs to do in your system).
