### ISSUE TITLE
Syscalls are failing with Internal Memory Fault in Graphene OS

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2265]
## Description of the problem
Syscalls are failing with Internal Memory Fault in Graphene OS

## TestFile
1.	Sendfile04
2.	Semop02
3.	Semctl03
4.	Msgsnd02
5. 	Msgrcv05
6.	Msgrcv06
7.	Chroot03
8.	Msgsnd06
9.	Msgsnd05
10.   Recvmsg01
[InternalMemoryFault.zip](https://github.com/oscarlab/graphene/files/6191223/InternalMemoryFault.zip)

**Comment by mkow** [comment]
@anjalirx-intel Could you retry on the current master? The IPC rework was just merged.

**Comment by dimakuv** [comment]
`sendfile04` is fixed by https://github.com/oscarlab/graphene/pull/2500. In fact, that PR fixes our `sendfile()` emulation completely (bar some corner cases).

**Comment by dimakuv** [comment]
`Semop02` and `Semctl03` (as well as all other `sem*` tests) are disabled in current Graphene, because we purged Sys-V emulation from Graphene currently. So these two issues are not relevant anymore.

**Comment by dimakuv** [comment]
`Msgsnd*` and `Msgrcv*` are disabled in current Graphene, because we purged Sys-V emulation from Graphene currently. So these two issues are not relevant anymore.

**Comment by dimakuv** [comment]
`Chroot03` is disabled in current Graphene, because Graphene doesn't implement `symlink`: https://github.com/oscarlab/graphene/blob/2dc94fc698a0e61b056828561dd376d094938de6/LibOS/shim/test/ltp/ltp.cfg#L117.

**Comment by dimakuv** [comment]
SUMMARY: The only currently relevant LTP test that is crashing is `sendfile04`. It will be fixed by #2500.

**Comment by anjalirx-intel** [comment]
A new syscall has been added to the list recvmsg01

**Comment by dimakuv** [comment]
I looked into `recvmsg01`. It fails in the child process (doesn't affect the execution of the main, parent process).

There is also a detailed comment about this child-failure in our LTP config: https://github.com/oscarlab/graphene/blob/4f8d6fb8b323d62f00be2ac2c7239878b14afc1e/LibOS/shim/test/ltp/ltp.cfg#L1638-L1642

So it's kinda expected to see a memory fault. We may want to disable this particular test until we actually fix that bug in Graphene, if this confuses people and our LTP parsers. The bug fix in Graphene is *not* expected soon-ish (it needs a proper re-write of the network sockets subsystem).

So we either skip `recvmsg01` LTP test, or we ignore this particular error message. @anjalirx-intel What would you prefer?

**Comment by dimakuv** [comment]
https://github.com/oscarlab/graphene/pull/2513 -- I created a PR that skips `recvmsg01` LTP test completely. This is better than having a "half-way" working test.

**Comment by dimakuv** [comment]
Accidentally auto-closed this issue. This issue should be actually closed after #2513 is merged.

**Comment by anjalirx-intel** [comment]
Closing this defect now. We will be opening another defect for chroot03 with more details on how to reproduce this issue
