### ISSUE TITLE
shim_do_epoll_wait() is terribly inefficient

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#228]
This are two performance bugs in [`shim_do_epoll_wait()`](https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_epoll.c). I found it while testing Redis 5.0. I concentrated only on Graphene-SGX, but should be applicable to other PALs.

1. Redis relies on `epoll_wait()` for bulk I/O on network and pipes. The expectation is that under heavy load (~100 clients) this syscall will return all events on all clients. After the syscall, Redis iterates through returned ~100 events and processes each of them.

In current Graphene, `shim_do_epoll_wait()` returns only *one* event. This leads to an overhead of 100x: Redis receives only one event, processes it, and has to issue `epoll_wait()` again (with other 99 events still pending).

In particular, the problem lies here:
```
    listp_for_each_entry(epoll_fd, &epoll->fds, list)
        if (polled == epoll_fd->pal_handle) {
            ... fill in revents of epoll_fd ...
            break;  // <-- forces subsequent logic to process only this epoll_fd !
        }
```

2. Another performance bottleneck is the invocation of `DkStreamAttributesQuerybyHandle()` during `shim_do_epoll_wait()`, for *each* returned event.

`DkStreamAttributesQuerybyHandle()` ends up in a PAL-specific [`socket_attrquerybyhdl()`](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_sockets.c) for sockets, [`pipe_attrquerybyhdl()`](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_pipes.c) for pipes, etc. Note that Redis uses `epoll_wait()` on both sockets and pipes.

These `xxx_attrquerybyhdl()` helpers return attributes for a particular handle. While most attributes are extracted directly from the handle metadata, two attributes (`pending_size` and `readable`) require OCALLs (`ocall_fionread` and `ocall_poll` respectively).

Now, in Redis case, for an epoll on its 100 clients and two opened pipes, there will be 204 OCALLs in the worst case during a single `shim_do_epoll_wait()` (given that issue 1 is fixed).

Ironically, `attr->pending_size` is not even checked during `shim_do_epoll_wait()`. The `attr->readable` can be actually extracted from the first `ocall_poll()`. I believe that the invocation of `DkStreamAttributesQuerybyHandle()` is redundant.

I will post my proposed patch shortly. I am still novice in Graphene's shim layer, so the patch needs careful review.

**Comment by chiache** [comment]
Hi, Dmitrii,

Thanks so much for the detailed report and performance analysis. I totally agree that asynchronous I/O has been the biggest performance letdown in Graphene. At a deeper level, a lot of the problems you described are caused by the restriction in the host interfaces (i.e., the PAL calls). The rationale behind the PAL call definitions includes keeping them simple, ambiguous, and portable, and hence so far we have stuck to a synchronous, single-handle polling API. Unfortunately, just like what you have profiled, such an API has caused huge performance bottleneck in many workloads.

There are several ways of redefining this APIs. One way is to extend the current DkObjectsWaitAny() API to return different I/O events (readable, writable, or shutdown) and even return multiple events. The resulting API will look like poll() or select() we have nowadays. This is probably the least disruptive option, and can be potentially quite portable. In this case, the API will still be synchronous, so still not the perfect fit for implementing epoll_wait() but at least much more efficient.

The other option is to replace DkObjectsWaitAny() with an asynchronous API. This is somewhat similar to the approach taken by Bascule, except that Bascule has made all of their IO asynchronous. The problem of an asynchronous PAL call is that it might be hard to implement at the host level--say using the OCALLs. However, an asynchronous PAL call can easily implement both synchronous and asynchronous behavior in SHIM quite efficiently.

If you already have a patch, I would love to take a look. I personally may also have some proposal, so maybe we merge the ideas together.

**Comment by dimakuv** [comment]
Here is the dirty patch that I use:

```
diff --git a/LibOS/shim/src/sys/shim_epoll.c b/LibOS/shim/src/sys/shim_epoll.c
index c7d8cdf..b936005 100644
--- a/LibOS/shim/src/sys/shim_epoll.c
+++ b/LibOS/shim/src/sys/shim_epoll.c
@@ -332,27 +332,29 @@ retry:
         goto retry;
     }
 
-    PAL_STREAM_ATTR attr;
-    if (!DkStreamAttributesQuerybyHandle(polled, &attr))
-        goto reply;
+    listp_for_each_entry(epoll_fd, &epoll->fds, list) {
+        PAL_STREAM_ATTR attr;
 
-    listp_for_each_entry(epoll_fd, &epoll->fds, list)
-        if (polled == epoll_fd->pal_handle) {
+        /* TODO: Ugly hack to notify DkStreamAttributesQuery() that we want
+         *       fast path w/o syscalls. Better option is to create new func
+         *       similar to DkStreamAttributesQuery() and call it here. */
+        attr.pending_size = 0xdeadbeefdeadbeef;
+        if (!DkStreamAttributesQuerybyHandle(epoll_fd->pal_handle, &attr))
+            continue;
 
-            debug("epoll: fd %d (handle %p) polled\n", epoll_fd->fd,
-                  epoll_fd->handle);
+        debug("epoll: fd %d (handle %p) polled\n", epoll_fd->fd,
+                epoll_fd->handle);
 
-            if (attr.disconnected) {
-                epoll_fd->revents |= EPOLLERR|EPOLLHUP|EPOLLRDHUP;
-                epoll_fd->pal_handle = NULL;
-                need_update = true;
-            }
-            if (attr.readable)
-                epoll_fd->revents |= EPOLLIN;
-            if (attr.writeable)
-                epoll_fd->revents |= EPOLLOUT;
-            break;
+        if (attr.disconnected) {
+            epoll_fd->revents |= EPOLLERR|EPOLLHUP|EPOLLRDHUP;
+            epoll_fd->pal_handle = NULL;
+            need_update = true;
         }
+        if (attr.readable)
+            epoll_fd->revents |= EPOLLIN;
+        if (attr.writeable)
+            epoll_fd->revents |= EPOLLOUT;
+    }
 
 reply:
     listp_for_each_entry(epoll_fd, &epoll->fds, list) {
diff --git a/Pal/src/host/Linux-SGX/db_object.c b/Pal/src/host/Linux-SGX/db_object.c
index b7476b5..5b1ef4a 100644
--- a/Pal/src/host/Linux-SGX/db_object.c
+++ b/Pal/src/host/Linux-SGX/db_object.c
@@ -195,12 +195,8 @@ int _DkObjectsWaitAny (int count, PAL_HANDLE * handleArray, uint64_t timeout,
 
         PAL_HANDLE hdl = hdls[i];
 
-        if (polled_hdl) {
-            if (hdl != polled_hdl)
-                continue;
-        } else {
+        if (!polled_hdl)
             polled_hdl = hdl;
-        }
 
         for (j = 0 ; j < MAX_FDS ; j++)
             if ((HANDLE_HDR(hdl)->flags & (RFD(j)|WFD(j))) &&
@@ -210,6 +206,9 @@ int _DkObjectsWaitAny (int count, PAL_HANDLE * handleArray, uint64_t timeout,
         if (j == MAX_FDS)
             continue;
 
+        HANDLE_HDR(hdl)->flags &= ~READABLE(j);
+        if (fds[i].revents & POLLIN)
+            HANDLE_HDR(hdl)->flags |= READABLE(j);
         if (fds[i].revents & POLLOUT)
             HANDLE_HDR(hdl)->flags |= WRITEABLE(j);
         if (fds[i].revents & (POLLHUP|POLLERR))
diff --git a/Pal/src/host/Linux-SGX/db_pipes.c b/Pal/src/host/Linux-SGX/db_pipes.c
index 1b40a7d..9a93646 100644
--- a/Pal/src/host/Linux-SGX/db_pipes.c
+++ b/Pal/src/host/Linux-SGX/db_pipes.c
@@ -335,6 +335,18 @@ static int pipe_attrquerybyhdl (PAL_HANDLE handle, PAL_STREAM_ATTR * attr)
     if (handle->generic.fds[0] == PAL_IDX_POISON)
         return -PAL_ERROR_BADHANDLE;
 
+    if (attr->pending_size == 0xdeadbeefdeadbeef) {
+        /* fast path without syscalls, used by epoll_wait() */
+        attr->handle_type  = PAL_GET_TYPE(handle);
+        attr->disconnected = HANDLE_HDR(handle)->flags & ERROR(0);
+        attr->writeable    = PAL_FALSE;
+        attr->readable     = HANDLE_HDR(handle)->flags & READABLE(0);
+        if (!IS_HANDLE_TYPE(handle, pipesrv))
+            attr->writeable = HANDLE_HDR(handle)->flags & (
+                    IS_HANDLE_TYPE(handle, pipeprv) ? WRITEABLE(1) : WRITEABLE(0));
+        return 0;
+    }
+
     attr->handle_type  = PAL_GET_TYPE(handle);
 
     int read_fd = handle->generic.fds[0];
diff --git a/Pal/src/host/Linux-SGX/db_sockets.c b/Pal/src/host/Linux-SGX/db_sockets.c
index dbc42c9..b37bfb3 100644
--- a/Pal/src/host/Linux-SGX/db_sockets.c
+++ b/Pal/src/host/Linux-SGX/db_sockets.c
@@ -801,6 +801,15 @@ static int socket_attrquerybyhdl (PAL_HANDLE handle, PAL_STREAM_ATTR  * attr)
     if (handle->sock.fd == PAL_IDX_POISON)
         return -PAL_ERROR_BADHANDLE;
 
+    if (attr->pending_size == 0xdeadbeefdeadbeef) {
+        /* fast path without syscalls, used by epoll_wait() */
+        attr->handle_type  = HANDLE_HDR(handle)->type;
+        attr->disconnected = HANDLE_HDR(handle)->flags & ERROR(0);
+        attr->writeable    = HANDLE_HDR(handle)->flags & WRITEABLE(0);
+        attr->readable     = HANDLE_HDR(handle)->flags & READABLE(0);
+        return 0;
+    }
+
     attr->handle_type           = HANDLE_HDR(handle)->type;
     attr->disconnected          = HANDLE_HDR(handle)->flags & ERROR(0);
     attr->nonblocking           = handle->sock.nonblocking;
diff --git a/Pal/src/host/Linux-SGX/pal_host.h b/Pal/src/host/Linux-SGX/pal_host.h
index 9a80542..abd0b51 100644
--- a/Pal/src/host/Linux-SGX/pal_host.h
+++ b/Pal/src/host/Linux-SGX/pal_host.h
@@ -182,6 +182,7 @@ typedef struct pal_handle
 #define WFD(n)          (00010 << (n))
 #define WRITEABLE(n)    (00100 << (n))
 #define ERROR(n)        (01000 << (n))
+#define READABLE(n)     (010000 << (n))
 #define MAX_FDS         (3)
 #define HAS_FDS         (00077)
 
```

The ugly thing here is `0xdeadbeefdeadbeef`. Basically, we need a way to notify the shim layer that we want a fast path. I didn't want to add new funcs or change func signatures, so I re-used one of the fields (of course, since `attr` is allocated on the stack, it can accidentally contain a garbage value).

Also, I added `READABLE` macro to propagate the `POLLIN` revent. I'm not sure my solution is clean, but at least it didn't break anything.

**Comment by chiache** [comment]
Thanks for the patch. I understand the logic behind this fix. It seems to me that this solution might be a bit too ad-hoc, and might not be sustainable in the long run. For the sake of code quality, I would prefer a cleaner solution that can doesn't depend on hard-coded escape words.

Let me propose a new PAL call and create a new PR for the related change. I think we want a host API that looks like this:

```
#define PAL_WAIT_SIGNAL     0
#define PAL_WAIT_READ       1
#define PAL_WAIT_WRITE      0
#define PAL_WAIT_ERROR      0

PAL_BOL
DkObjectsWaitAny (PAL_NUM count, PAL_HANDLE * handleArray, PAL_FLG * events,
                  PAL_FLG * ret_events, PAL_NUM timeout);
```

This PAL call will avert the need of doing another `DkStreamAttributesQuerybyHandle` after the poll. It can also return multiple events from multiple handles if they occur simultaneously.

**Comment by dimakuv** [comment]
Yes, this will be the clean solution. Feel free to ping me when this is implemented, I will test on my side.
