### ISSUE TITLE
Initializing enclave fails for all tests in LibOS/shim/test/native

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#23]
Example:
```
graphene/LibOS/shim/test/native$ ./pal helloworld.manifest.sgx
initializing enclave failed: init_enclave: 1
```

The reason seems to be the missing `loader.exec` entry in `helloworld.manifest.sgx`. 

I think the right fix would be a line `loader.exec = $(EXEC)` in `LibOS/shim/test/native/manifest.template` and an additional rule in `LibOS/shim/test/Makefile` to replace the `$(EXEC)` with the correct executable name. But I was not able to fix this myself, because I can't wrap my head around this makefile.

**Comment by chiache** [comment]
Simply run `./pal helloworld` and Graphene will match the executable with the SGX-specific manifest (`helloworld.manifest.sgx`).

In the native directory, all SGX-specific manifests are generated from a generic manifest, so there is no specific `loader.exec`. If you are writing your own manifest, you can add `loader.exec` to specify the executable to run.

**Comment by adombeck** [comment]
I thought running `./pal helloworld` would run it without SGX. Does the PAL loader automatically check if there is a `*.manifest.sgx` and run it with SGX if it finds one? Is there a way to run it without SGX even if there is a `*.manifest.sgx`?
