### ISSUE TITLE
Bug in returning from signal handler in Linux-SGX

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#230]
I encountered an elusive bug while testing Redis 5.0. It has to do with exception (signal) handling in the Linux-SGX PAL.

Redis installs a SIGINT handler to gracefully shutdown. (The details are not important though.) In my situation, the main Redis thread ran in an infinite loop inside the enclave, received SIGINT, correctly handled the signal, but after returning to normal stack, its GPRs were corrupted with garbage values -> Redis got SIGBUS and crashed.

Here is the root cause of this bug. Graphene with Linux-SGX has two logical paths: (1) starting from `_DkHandleExternelEvent()` if thread received a signal while *not* in enclave mode, and (2) starting from `_DkExceptionHandler()` if thread was in enclave mode. Both are defined in [`db_exception.c`](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_exception.c).

The bug lurks in the `pal_frame* frame` processing:
```
/* _DkHandleExternelEvent() -- no bug */
    if (!frame) {
        frame = __alloca(sizeof(struct pal_frame));
        frame->identifier = PAL_FRAME_IDENTIFIER;
        frame->func = &_DkHandleExternelEvent;
        frame->funcname = "_DkHandleExternelEvent";
        arch_store_frame(&frame->arch);
    }

/* _DkExceptionRealHandler -- bug! compare with previous function */
    if (frame) {
        frame = __alloca(sizeof(struct pal_frame));
        frame->identifier = PAL_FRAME_IDENTIFIER;
        frame->func     = &_DkExceptionRealHandler;
        frame->funcname = "_DkExceptionRealHandler";
        store_register(rsp, frame->arch.rsp);
        store_register(rbp, frame->arch.rbp);
        unsigned long * last_frame = ((unsigned long *) frame->arch.rbp) + 1;
        last_frame[0]  = (unsigned long) arch_exception_return;
        last_frame[1]  = context->rax;
        last_frame[2]  = context->rbx;
        last_frame[3]  = context->rcx;
        last_frame[4]  = context->rdx;
        last_frame[5]  = context->rsi;
        last_frame[6]  = context->rdi;
        last_frame[7]  = context->r8;
        last_frame[8]  = context->r9;
        last_frame[9]  = context->r10;
        last_frame[10] = context->r11;
        last_frame[11] = context->r12;
        last_frame[12] = context->r13;
        last_frame[13] = context->r14;
        last_frame[14] = context->r15;
        last_frame[15] = context->rip;
    }
```

So, if enclave got the interrupt in enclave mode, it eventually calls `_DkExceptionRealHandler()`. This function actually has two bugs:

1. First line must say `if (!frame)`. Current logic does "if I have a frame, otherwrite it". (This is actually not the bug that I hit.)

2. `last_frame[xxx]` logic overwrites the previous stack frame. Note two things: (a) Graphene-SGX *already* installed a correct stack frame to jump back to normal execution in [`.Lhandle_exception`](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/enclave_entry.S), and (b) SGX architecture defines a *different* order of storing GPRs in [`struct sgx_arch_gpr_t`](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/sgx_arch.h).

So what happened in my case is that `last_frame[xxx]` incorrectly overwrote my frames, Redis returned from exception handling, and my normal execution tried to `mov (%rdx)` but RDX contained some garbage.

In general, I found that the exception handling logic Linux-SGX requires no `frame` at all (it never uses `frame` but instead uses `context`).

My quick fix was to:
```
/* _DkExceptionRealHandler -- do not instantiate frame at all */
#if 0
    struct pal_frame * frame = get_frame(uc);
#else
    struct pal_frame * frame = NULL;  /* no bug now */
#endif
```

I guess the correct fix would be to copy logic from well-behaved `_DkHandleExternelEvent()`.

**Comment by dimakuv** [comment]
I tried to create a test case to highlight this issue, but to no avail. This is what I tried but I cannot hit the bug anyway. I will leave it here anyway.

```
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>

volatile int flag = 0;

static void handler(int signum) {
    char buf[] = "hi from signal handler\n";
    write(STDOUT_FILENO, buf, strlen(buf));
    flag++;
}

volatile int a = 0;
volatile int* b = &a;
volatile int** c = &b;
volatile int*** d = &c;
volatile int**** e = &d;
volatile int***** f = &e;

int main(int argc, char ** argv)
{
    printf("Hello world (%s)!\n", argv[0]);
    fflush(stdout);

    struct sigaction sig;
    sig.sa_handler = handler;
    sigaction(SIGINT, &sig, 0);

    printf("...Going into infinite loop, waiting for SIGINT...\n");
    fflush(stdout);
    while (1) {
        if (flag >= 5)  break;
        /* to hit the bug, need some memory accesses based on GPR */
        asm ("add (%1), %0\n\t"
                     "add (%2), %0\n\t"
                     "add (%3), %0\n\t"
                     "add (%4), %0\n\t"
                     "add (%5), %0\n\t"
              : "+a" (a)
              : "b" (b), "c" (c), "d" (d), "S" (e), "D" (f)
              );
    }
    printf("Bye world (%d)!\n", a);
    return 0;
}
```

**Comment by dimakuv** [comment]
Bump. I ran into this bug again, while testing the "exitless" feature. I used the following test:

```
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#include <unistd.h>

void handler (int signal)
{
    write(STDOUT_FILENO, "hi from handler\n", 16);
    write(STDOUT_FILENO, "bye from handler\n", 17);
}

int main (void)
{
    int i = 0;
    signal(SIGINT, &handler);
    sleep(1000000);
    return 0;
}
```

This makes the main thread remain in the enclave waiting for the helper RPC thread to finish with `nanosleep()` system call. Upon Ctrl-C, the main thread will receive SIGINT and start delivering the signal. Since it was interrupted inside the enclave, the logic will go through `_DkExceptionHandler -> _DkExceptionRealHandler (corrupts frame!) -> _DkExceptionReturn -> restore_sgx_context (restores corrupted frame!)`.

So the bug is exactly the same as I described before. The fix is also the same.

**Comment by yamahata** [comment]
I vote for removing such frame logic.

The original intention (of Pal/Linux) is to handle a bug of PAL cuasing SIGSEGV etc gracefully.
the implementation is hacky and now it's removed from Pal/Linux.

For Pal/Linux-SGX, the implementation was wrong as you reported and hasn't worked well so far, I guess.
It's acceptable to remove it and we can show panic message and process-exit(or infinite loop for debug) in the case of such bug.

**Comment by donporter** [comment]
Is there a reason we can't unify this code path?   Is it just that one executes inside and one outside of an enclave?

I agree with this fix.  It seems well-reasoned and easy enough to test.

I'd be curious if @chiache had any other insight about this issue.

**Comment by dimakuv** [comment]
**Note to myself**:  supply PR that fixes this problem. Explain the issue and solution in PR in detail.

This issue is really annoying, I encounter this problem anew every couple months :)

**Comment by dimakuv** [comment]
Probably PRs #245 (deprecated) and #625 (new) fix this bug. Check it.

**Comment by smherwig** [comment]
Doesn't the master branch still have the logic in `_DkExceptionRealHandler` of "if I have a frame, overwrite it"

**Comment by dimakuv** [comment]
Yes, the master branch still has the logic of "If there is a frame, overwrite it". There are pending PRs to re-write the exception-handling logic completely. However, this particular bug doesn't manifest itself anymore (at least on my tests).
