### ISSUE TITLE
Build error for graphene/LibOS/glibc-build/malloc/memusagestat

### ISSUE THREAD

**Issue by dychen95** [oscarlab/graphene#2306]
## Description of the problem

Tried to build Graphene on intel Core i7-6700K desktop with Ubuntu 18.04.5 LTS. 

- gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- glibc (Ubuntu GLIBC 2.27-3ubuntu1.4) 2.27

Got the following build errors:

```
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
(CC=gcc CXX=g++ AS=gcc make -C glibc-build 2>&1 > build.log) && touch glibc-build/Build.success
//lib/x86_64-linux-gnu/librt.so.1: undefined reference to `__clock_settime@GLIBC_PRIVATE'
//lib/x86_64-linux-gnu/librt.so.1: undefined reference to `__clock_getcpuclockid@GLIBC_PRIVATE'
//lib/x86_64-linux-gnu/librt.so.1: undefined reference to `__clock_nanosleep@GLIBC_PRIVATE'
//lib/x86_64-linux-gnu/librt.so.1: undefined reference to `__clock_getres@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
make[4]: *** [/home/dychen/temp/sgx/graphene/LibOS/glibc-build/malloc/memusagestat] Error 1
make[3]: *** [malloc/others] Error 2
make[2]: *** [all] Error 2
Makefile:68: recipe for target 'glibc-build/Build.success' failed
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory '/home/dychen/temp/sgx/graphene/LibOS'
Makefile:13: recipe for target 'all' failed
make: *** [all] Error 2
```
The last few lines in the build.log shows:
```
gcc -Wl,-rpath-link=/home/dychen/temp/sgx/graphene/LibOS/glibc-build:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/math:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/elf:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/dlfcn:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/nss:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/nis:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/rt:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/resolv:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/mathvec:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/support:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/crypt:/home/dychen/temp/sgx/graphene/LibOS/glibc-build/nptl -pie -Wl,-O1 -nostdlib -nostartfiles -o /home/dychen/temp/sgx/graphene/LibOS/glibc-build/malloc/memusagestat    -Wl,-z,combreloc -Wl,-z,relro -Wl,--hash-style=both /home/dychen/temp/sgx/graphene/LibOS/glibc-build/csu/Scrt1.o /home/dychen/temp/sgx/graphene/LibOS/glibc-build/csu/crti.o `gcc  --print-file-name=crtbeginS.o` /home/dychen/temp/sgx/graphene/LibOS/glibc-build/malloc/memusagestat.o  -lgd -lpng -lz -lm -Wl,-dynamic-linker=/home/dychen/temp/sgx/graphene/LibOS/../Runtime/lib/ld-linux-x86-64.so.2  /home/dychen/temp/sgx/graphene/LibOS/glibc-build/libc.so.6 /home/dychen/temp/sgx/graphene/LibOS/glibc-build/libc_nonshared.a -Wl,--as-needed /home/dychen/temp/sgx/graphene/LibOS/glibc-build/elf/ld.so -Wl,--no-as-needed -lgcc  `gcc  --print-file-name=crtendS.o` /home/dychen/temp/sgx/graphene/LibOS/glibc-build/csu/crtn.o
../Rules:215: recipe for target '/home/dychen/temp/sgx/graphene/LibOS/glibc-build/malloc/memusagestat' failed
make[4]: Leaving directory '/home/dychen/temp/sgx/graphene/LibOS/glibc-2.31/malloc'
Makefile:470: recipe for target 'malloc/others' failed
make[3]: Leaving directory '/home/dychen/temp/sgx/graphene/LibOS/glibc-2.31'
Makefile:9: recipe for target 'all' failed
make[2]: Leaving directory '/home/dychen/temp/sgx/graphene/LibOS/glibc-build'
```

## Steps to reproduce

1. git clone https://github.com/oscarlab/graphene.git
commit d1e3f27060a06ea3654e315678922f75eb31a597 (HEAD -> master, origin/master, origin/HEAD)
2. sudo apt-get install -y build-essential autoconf gawk bison wget python3
3. cd graphene/
4. make

## Expected results

Build should succeed

## Actual results

Build failed with undefined references when linking memusagestat.

**Comment by dimakuv** [comment]
This is surprising that you experienced this issue. The culprit is `memusagestat`. Googling about this Glibc utility sheds some light:
- http://www.linuxfromscratch.org/lfs/view/6.2/chapter05/glibc.html (people suggest to disable the build of it using `--without-gd`)
- https://elixir.bootlin.com/glibc/glibc-2.33.9000/source/NEWS (search for `memusagestat` and you'll see this bugfix: `[18465] malloc: memusagestat is built using system C library`)

So yeah, this particular executable (`memusagestat`) was built against your-system C library instead of the Graphene-specific C library. And apparently, your system has some weird Glibc version or something. Note that Graphene uses Glibc version 2.31 internally, so it's different from the Glibc version installed on your system.

This particular Glibc bug seems to be fixed in 2.33 and higher, but this is like super-new. Anyway, seems like the simple & correct fix in Graphene would be to disable the build of `memusagestat` altogether. I'll prepare a PR.

**Comment by dimakuv** [comment]
@dychen95 I'll be glad if you could try #2308 on your system and see if this resolves your issues.

**Comment by dychen95** [comment]
I applied the patch [#2308](https://github.com/oscarlab/graphene/pull/2308), the build completed successfully with the patch. Thanks,

**Comment by dimakuv** [comment]
Thanks for checking! We'll merge this PR very soon.
