### ISSUE TITLE
Multiple 16-byte stack alignment violations when calling C code from assembly

### ISSUE THREAD

**Issue by rainfld** [oscarlab/graphene#231]
The unit tests under Pal/Regression use API "pal_printf" to print out messages. However, pal_printf will trigger a "Segmentation Fault" Error in printf when printing double or float variables.  For example, if running a test program as follows, by running "GDB=1 SGX=1 ../test/pal_loader doubletest" under Pal/Regression:

```
#include"pal.h"
#include"pal_debug.h"
#include<stdio.h>

int main(){
  double num = 5.0;
  pal_printf("double num is %f\n", num);
  return 1;
}
```

We got following error messages in GDB:

Program received signal SIGSEGV, Segmentation fault.
0x000000000bd7f932 in printf (fmt=0x400390 "double num is %f\n") at printf.c:66

Dissembling 0x000000000bd7f932:

Dump of assembler code for function printf:
```
   0x000000000bd7f900 <+0>:     push   %rbp
   0x000000000bd7f901 <+1>:     mov    %rsp,%rbp
   0x000000000bd7f904 <+4>:     sub    $0xd0,%rsp
   0x000000000bd7f90b <+11>:    test   %al,%al
   0x000000000bd7f90d <+13>:    mov    %rsi,-0xa8(%rbp)
   0x000000000bd7f914 <+20>:    mov    %rdx,-0xa0(%rbp)
   0x000000000bd7f91b <+27>:    mov    %rcx,-0x98(%rbp)
   0x000000000bd7f922 <+34>:    mov    %r8,-0x90(%rbp)
   0x000000000bd7f929 <+41>:    mov    %r9,-0x88(%rbp)
   0x000000000bd7f930 <+48>:    je     0xbd7f952 <printf+82>
   **=> 0x000000000bd7f932 <+50>:    movaps %xmm0,-0x80(%rbp)**
   0x000000000bd7f936 <+54>:    movaps %xmm1,-0x70(%rbp)
   0x000000000bd7f93a <+58>:    movaps %xmm2,-0x60(%rbp)
   0x000000000bd7f93e <+62>:    movaps %xmm3,-0x50(%rbp)
   0x000000000bd7f942 <+66>:    movaps %xmm4,-0x40(%rbp)
   0x000000000bd7f946 <+70>:    movaps %xmm5,-0x30(%rbp)
   0x000000000bd7f94a <+74>:    movaps %xmm6,-0x20(%rbp)
   0x000000000bd7f94e <+78>:    movaps %xmm7,-0x10(%rbp)
   0x000000000bd7f952 <+82>:    lea    0x10(%rbp),%rax
   0x000000000bd7f956 <+86>:    lea    -0xc8(%rbp),%rsi
   0x000000000bd7f95d <+93>:    mov    %rax,-0xc0(%rbp)
   0x000000000bd7f964 <+100>:   lea    -0xb0(%rbp),%rax
   0x000000000bd7f96b <+107>:   movl   $0x8,-0xc8(%rbp)
   0x000000000bd7f975 <+117>:   movl   $0x30,-0xc4(%rbp)
   0x000000000bd7f97f <+127>:   mov    %rax,-0xb8(%rbp)
   0x000000000bd7f986 <+134>:   callq  0xbd7f8a0 <vprintf>
   0x000000000bd7f98b <+139>:   leaveq
   0x000000000bd7f98c <+140>:   retq

```
If we run the same program using printf instead of pal_print, the flow works fine.

**UPDATE**:
Looks like the reason causing segmentation fault is that the value in rbp register  is not 16 byte aligned, triggering #GP according to movasp instruction requirement:

movaps %xmm0,-0x80(%rbp)

**Comment by mkow** [comment]
I think the root of problem is in the fact that all inline assembly in Graphene doesn't respect GCC convention for x64 when doing calls to C code. In not-very-old GCC the default calling convention requires the stack pointer to be aligned to 16 bytes (see the default for `-mpreferred-stack-boundary` flag) which means that `rsp` should be divisible by 16 right before executing `call` instruction.

Examples of violations of this:
https://github.com/oscarlab/graphene/blob/5f4464785d77276c51f0c79ada9c8817c7290814/LibOS/shim/src/syscallas.S#L75
https://github.com/oscarlab/graphene/blob/5f4464785d77276c51f0c79ada9c8817c7290814/LibOS/shim/src/elf/shim_rtld.c#L1578-L1580

**Comment by donporter** [comment]
Good point.  Let's put this on the short list for issues to audit and fix in the code.

**Comment by mkow** [comment]
Another violation:
https://github.com/oscarlab/graphene/blob/bf87ac02f299e4f92b8e8a16313fb838ee180683/LibOS/shim/src/start.S#L43-L56

This code miscalculates the alignment.
