### ISSUE TITLE
Setting multiple preload libraries using loader.env.LD_PRELOAD causes memory issues

### ISSUE THREAD

**Issue by daniel-weisse** [oscarlab/graphene#2340]
## Description of the problem

When running applications inside SGX enclaves using graphene and more than one shared library is defined in the manifest trough the use of the `LD_PRELOAD` env variable, e.g. `loader.env.LD_PRELOAD = "./test-2.so /test-1.so"` , applications encounter memory issues.

## Steps to reproduce

originally built using commit `3ab0dfaa5c4e54a9df826c444c57577f6f209adc`, but seems to also happen with the current version (`483a292e676f2a0bbdeeab65fd8c08582c396316`)

1. Write two test programs, compile them as shared libraries and set them in the manifest.
```
loader.env.LD_PRELOAD = "./test-2.so /test-1.so"
loader.insecure__use_host_env = 1
```

To test this, i created 2 very short go programs, which both print a single line of text, basically:
```
//export testFunction
func testFunction() {
	fmt.Println("Test Output 1")
}
```

2. Build a docker image with Graphene and the application you want to run inside the enclave, in my case i was using TensorFlow Serving. 
Enclave size was set to `sgx.enclave_size = "2G"`, which was sufficient to run TensorFlow serving on its own (no preloads)
3. Run the docker image

## Expected results
The TensorFlow server starts as expected after the two preload libraries print their text

## Actual results
Execution stops due to memory problems.
In some cases both preload libraries finish execution and the server starts but fails during setup with:
```
Test Output 1
Test Output 2
2021-04-29 14:07:27.563546: I tensorflow_serving/model_servers/server.cc:89] Building single TensorFlow model file config:  model_name: resnet50 model_base_path: /models/resnet50-v15-fp32
2021-04-29 14:07:27.568500: I tensorflow_serving/model_servers/server_core.cc:465] Adding/updating models.
2021-04-29 14:07:27.568553: I tensorflow_serving/model_servers/server_core.cc:591]  (Re-)adding model: resnet50
2021-04-29 14:07:27.881860: I tensorflow_serving/core/basic_manager.cc:740] Successfully reserved resources to load servable {name: resnet50 version: 1}
2021-04-29 14:07:27.882289: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: resnet50 version: 1}
2021-04-29 14:07:27.882417: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: resnet50 version: 1}
2021-04-29 14:07:27.883243: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: /models/resnet50-v15-fp32/1
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[P9:T21:tensorflow_model_s...] debug: killed by signal 6
```
Other times just the first library finishes after which the application encounters an out of memory error:
```
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0x31b4e000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/libc.so.6 loaded at 0x31796000
Test Output 1
runtime: out of memory: cannot allocate 4194304-byte block (0 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x32f5480d, 0xd)

```

## Additional information
The application runs fine if only one or no preload libraries are set in `loader.env.LD_PRELOAD`.
Creating the first go program as a preload library and the second as a normal application which then calls TensorFlow Serving using `C.posix_spawn` also works without problems.

Im not entirely sure if `LD_PRELOAD` is supposed to support loading of multiple libraries, since i was unable to find much documentation regarding that env variable, or if this behavior is unintentional, both libraries do however register just fine during the start process:
```
[P10:T1:tensorflow_model_server]debug: Allocating stack at 0x0 (size = 262144)
[P10:T1:tensorflow_model_server]debug: loading "file:tensorflow_model_server"
[P10:T1:tensorflow_model_server]debug: searching for interpreter: /lib/ld-linux-x86-64.so.2
[P10:T1:tensorflow_model_server]debug: Shim process initialized
[P10:i1:tensorflow_model_server]debug: Allocating stack at 0x0 (size = 16384)
[P10:i1:tensorflow_model_server]debug: IPC helper thread started
[P10:T1:tensorflow_model_server]debug: glibc register library ./test-2.so loaded at 0x32e58000
[P10:T1:tensorflow_model_server]debug: glibc register library ./test-1.so loaded at 0x32a5c000
[P10:T1:tensorflow_model_server]debug: glibc register library /usr/lib/x86_64-linux-gnu/libstdc++.so.6 loaded at 0x326d3000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/libm.so.6 loaded at 0x32394000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/libpthread.so.0 loaded at 0x32174000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/libdl.so.2 loaded at 0x31f70000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/librt.so.1 loaded at 0x31d66000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/x86_64-linux-gnu/libgcc_s.so.1 loaded at 0x31b4e000
[P10:T1:tensorflow_model_server]debug: glibc register library /lib/libc.so.6 loaded at 0x31796000
```

**Comment by dimakuv** [comment]
@daniel-weisse What do these two Go programs have as dependencies? I am not familiar with Go libraries that much, and I'm not sure if they also initialize and use the Go runtime. I'm also not sure how the two Go libraries "share" the Go runtime. Could you point to any explanations on this? And are you sure it works adequately in non-SGX (native) execution?

What I could imagine (and what seems to be the case), is that these Go libraries bring the whole Go runtime into the enclave. Maybe even twice, if each of these Go libraries brings its own copy of the Go runtime.

Finally, what seems to happen is that you have a Go runtime when you preloaded the Go libraries. Now you do `posix_spawn()` which does `vfork + execve` under the hood, and the `vfork` actually copies the whole in-enclave state (including the whole Go runtime state). So now you have not only TensorFlow code and state, but also the vestigial Go-runtime state inside your enclave.

This may explain the "out of memory" errors you see in your experiments. Probably, 2GB was barely enough for TensorFlow execution, and now you added more state -- the Go runtime state.

I'm writing all this under the assumption that the Go runtime eats a lot of memory. From what I remember about Go, this is exactly true (like Go needs a couple GBs of memory?).

**Comment by mkow** [comment]
+1 to what @dimakuv wrote, this doesn't sound like something which should work even without Graphene. `LD_PRELOAD` is not a good mechanism, it should be used mostly for hacks and testing, not in production setups. I don't think `go` runtime expects to be preloaded into completely different environment (twice!).

So, what are you actually trying to achieve with preloading?

**Comment by dimakuv** [comment]
Now about debugging and root causing this.

First, try `loader.log_level = "all"`. This will spam you with a lot of Graphene internal logs, but you'll probably see some interesting messages. You can also redirect these logs into a file using `loader.log_file = "<your file>"`.

Second, we clearly have an "out of enclave memory" error. Several ways to play with it/increase enclave memory:
- `sgx.enclave_size = "<4G, 8G, 16G>"`
- `loader.insecure__disable_aslr = 1` (this is just for debugging, it basically allows to use the whole `sgx.enclave_size` instead of "some randomized sub-region of it")
- `loader.pal_internal_mem_size = "<64M, 128M, 256M>"` (this is probably not needed, Graphene would loudly complain and suggest this option if this would be because of this)

**Comment by daniel-weisse** [comment]
Hi, thanks for the quick reply.

The entire code of the test library:
* Go code:
```go
package main

import "C"
import (
	"fmt"
)

func main() {}

//export testFunction
func testFunction() {
	fmt.Println("Test Output 1")
}
```
* C constructor:
```C
__attribute__((constructor)) static void init() {
  void testFunction();
  testFunction();
}
```

It seems i heavily underestimated the needed memory when using shared go libraries.
I did some testing with a rather simple hello world program: https://github.com/edgelesssys/marblerun/tree/master/samples/graphene-hello/preload
When i added the above to the preload, the application fails with `fatal error: failed to reserve page summary memory`.
However when i double the enclave size from originally 1G to 2G it runs fine.

The actual goal of my application was to run TensorFlow in combination with [Marblerun](https://github.com/edgelesssys/marblerun). I need to include the Marblerun premain and also a program to decrypt a pre-trained model for TensorFlow using a key provided by the Marblerun premain.

Also thanks for the tip regarding `posix_spawn()`. As of now my application runs fine using marblerun premain as a preload library and my decryption process as the main application spawning TensorFlow using `posix_spawn()`.
Faster execution and less memory usage would of course be desirable, so i tried using `execve()` and it starts TensorFlow noticeably faster.
Completely moving away from using `LD_PRELOAD` is probably the best option.

**Comment by dimakuv** [comment]
@daniel-weisse Do I understand correctly that you resolved this issue on your side? Or do you still need some changes/explanations in Graphene?

**Comment by daniel-weisse** [comment]
@dimakuv The issue is resolved, thanks for the help!
