### ISSUE TITLE
Graphene support for SGX Simulation mode

### ISSUE THREAD

**Issue by Relyor** [oscarlab/graphene#2343]
Can graphene SGX run without SGX hardware (let's say on AMD processors)? Does it support a simulation mode, or the SGX simulation mode?

Thanks!

**Comment by dimakuv** [comment]
Graphene is a LibOS runtime that has different backends (so-called "PALs" or "Platform Adaptation Layers").

Thus, Graphene can run on any support backend. We currently only have two:
- native Linux (we also call it "direct" sometimes), that doesn't require SGX hardware and runs on any x86-64 machine
- Linux-SGX (what we sometimes call "Graphene-SGX"), that requires SGX hardware

You can think of the former as the "simulation mode" of the latter. Roughly. That's not really a proper simulation, but this is the closest you can get to "simulation mode" in Graphene.
