### ISSUE TITLE
SGX PAL mutex possible vulnerability

### ISSUE THREAD

**Issue by shmeni** [oscarlab/graphene#2344]
The current implementation in SGX PAL for db_mutex uses the futex system call and passes an untrusted address to the OS. The data in this untrusted address also seemed to be used as a userspace lock. 
A malicious adversary may change the value to represent an unlock state, which will cause the trusted code to succeed in the atomic operation and consider the lock to succeed even though another thread already holds the lock.

There is a comment in the code describing it as a DOS attack
https://github.com/oscarlab/graphene/blob/8dd78b5d712bbe820365570cea920626c5880b62/Pal/src/host/Linux-SGX/db_mutex.c#L66

However, when I used an external non-enclave thread to change mutex values to unlock state, a shielded application reported `assert failed shim_async.c:360 locked(&async_helper_lock)`. This seems like an assertion for mutual exclusion indeed failed in the shim layer, unlike a DOS attack.

**Comment by dimakuv** [comment]
This issue was fixed 7 days ago: https://github.com/oscarlab/graphene/pull/2336.

**Comment by dimakuv** [comment]
But in general yes, the LibOS layer also checks the correctness of futexes (via its own enclave-memory metadata). Now with #2336 we also have the same level of protection in the PAL layer.

**Comment by boryspoplawski** [comment]
> This issue was fixed 7 days ago: #2336.

That's not true, the linked PR fixed an issue identical to this one, but in different place.

**Comment by dimakuv** [comment]
@boryspoplawski is right, sorry for confusion.

#2336 only fixes `db_events.c` logic, not the `db_mutex.c` logic.
