### ISSUE TITLE
[Pal/Linux-SGX] Replace RDRAND with RDSEED instruction

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#2348]
RDRAND hardware instruction is not suitable for producing a secret value more than 64 bits in size (by concatenating 64-bit return values of RDRAND). We use RDRAND in this way in several places in our codebase (e.g., to generate a random 256-bit master key).

We need to replace the RDRAND instruction with the RDSEED instruction -- then we can continue with our simple logic of concatenating return 64-bit values into larger-bit values. See also https://software.intel.com/content/www/us/en/develop/blogs/the-difference-between-rdrand-and-rdseed.html.

Please note that RDSEED is a significantly slower instruction, so shouldn't be used in perf-critical operations. But from my quick review of our source code, we currently call RDRAND only during Graphene/enclave initialization and for mbedTLS source of entropy (which is initialized only once and then mbedTLS uses its own PRNG without calling RDRAND/RDSEED afterwards).

**Comment by dimakuv** [comment]
Interestingly, RDSEED is not *that* slower than RDRAND: https://stackoverflow.com/questions/45336283/negligible-difference-in-performance-between-rdseed-and-rdrand. People say ~3 times slower, which is not awful.

I initially thought that we would need two interfaces: one using RDRAND for frequent operations (like LibOS requests to fill its `/dev/random`) and one using RDSEED for rare operations (like creation of keys).

But given this info on performance, and our pretty-rare usage of randomness in Graphene, looks like we can get away with simply replacing RDRAND with RDSEED instruction and that's it.

ALSO: We have two implementations of RDRAND: `include/arch/x86_64/cpu.h` and `include/arch/x86_64/rng-arch.h`. We need to use only one of those (we should remove `rdrand()` and use `get_rand64()`). We will also replace `__builtin_ia32_rdrand64_step` with `_rdseed64_step` (and add ` -mdseed` to GCC flags).

**Comment by mkow** [comment]
> RDRAND hardware instruction is not suitable for producing a secret value more than 64 bits in size (by concatenating 64-bit return values of RDRAND). We use RDRAND in this way in several places in our codebase (e.g., to generate a random 256-bit master key).
> 
> We need to replace the RDRAND instruction with the RDSEED instruction -- then we can continue with our simple logic of concatenating return 64-bit values into larger-bit values. See also https://software.intel.com/content/www/us/en/develop/blogs/the-difference-between-rdrand-and-rdseed.html.

This article doesn't make this issue any clearer to me, it just made me completely confused :) I've read on this topic before and I'm still confused and have never found a good explanation about the difference between these two instructions.

Issues:
1. The "short answer" clearly says that we should use RDRAND, not RDSEED in our case ("If you wish to seed another pseudorandom number generator (PRNG), use RDSEED. For all other purposes, use RDRAND").
2. RDRAND is described as "Cryptographically secure pseudorandom number generator" - so it sounds like it's perfectly valid to generate encryption keys from it.
3. This article uses some vague terms and marketing names without actually saying what they exactly mean or give us (e.g. "high-quality random numbers", "benefit from the entropy source of Intel Secure Key", ...).
4. I tried googling this "multiplicative prediction resistance" term to understand what it means, and the first hit is... this very article. Other results are mostly about cancer treatments :)
5. This whole article sounds like RDSEED was introduced just for compliance to another NIST standard than RDRAND complies to...
6. x86 SDM (both vol 1 and 2) doesn't make it any clearer, both are declared crypto-secure and the only difference in the descriptions is the compliance to different NIST standards.

So, overall, I don't see why should we change anything in our codebase.

**Comment by dimakuv** [comment]
After some internal discussions, looks like we can keep using RDRAND.
