### ISSUE TITLE
https 403

### ISSUE THREAD

**Issue by cathhuo** [oscarlab/graphene#2363]
--2021-05-11 08:01:04--  (try:18)  https://packages.grapheneproject.io/distfiles/uthash-2.1.0/src/uthash.h
Connecting to packages.grapheneproject.io (packages.grapheneproject.io)|2a00:1ca8:2a:d::10|:443... failed: Cannot assign requested address.
Retrying.

**Comment by woju** [comment]
On Tue, May 11, 2021 at 02:00:21AM -0700, cathhuo wrote:
> --2021-05-11 08:01:04--  (try:18)  https://packages.grapheneproject.io/distfiles/uthash-2.1.0/src/uthash.h
> Connecting to packages.grapheneproject.io (packages.grapheneproject.io)|2a00:1ca8:2a:d::10|:443... failed: Cannot assign requested address.
> Retrying.

Note this is trying IPv6 address. Is your IPv6 stack working?

**Comment by mkow** [comment]
No response from the reporter, closing (and seems to be a network issue on their side).
