### ISSUE TITLE
Graphene-SGX: Calling of Unsupported system call setresuid lead to memory fault 

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2366]
[semget02.log](https://github.com/oscarlab/graphene/files/6458919/semget02.log)
## Description of the problem
semget02: The test calls for seteuid function which is not supported by Graphene, calling this function in Graphene-SGX leads to memory fault which could be seen in trace logs

## Steps to reproduce: 
Make following changes in test file
Replace this
ltpuser = getpwnam(nobody_uid);
if (seteuid(ltpuser->pw_uid) == -1) {
		tst_resm(TINFO, "setreuid failed to "
			 "to set the effective uid to %d", ltpuser->pw_uid);
	perror("setreuid");
}
with 
if (seteuid(65534) == -1)  {
		tst_resm(TINFO, "setreuid failed to "
			 "to set the effective uid to %d", ltpuser->pw_uid);
	perror("setreuid");
}
(seteuid(65534) == -1) 

## Expected results
semget02    0  TINFO  :  setreuid failed to to set the effective uid to 65534
setreuid: Function not implemented

## Actual results
It does not print anything to console, but when log level is set to trace, it rreports
[P12708:T1:semget02] trace: ---- shim_geteuid() = 0x0
[P12708:T1:semget02] warning: Unsupported system call setresuid
[P12708:T1:semget02] debug: memory fault at 0x00000000 (IP = 0x0857e1bf)
[P12708:T1:semget02] debug: killed by signal 11
[P12708:T1:semget02] debug: Waiting for 0.5s for all in-flight IPC messages to reach their destinations
[P12708:T1:semget02] debug: process 12708 exited with status 139
debug: DkProcessExit: Returning exit code 139

## Additional information
Attached trace log for semget02

**Comment by boryspoplawski** [comment]
Your patch is invalid, you remove setting of `ltpuser` pointer, which defaults to `NULL`, but is then dereferenced anyway.
Graphene currently does not support `setresuid`, but the fault you observed is happening in the user app due to above.

**Comment by anjalirx-intel** [comment]
I think you have misunderstood the issue. In this issue ltpuser is not used, this issue occurs only in Graphene-SGX, in Graphene native it works fine and returns ENOSYS 

Trace Logs for Graphene Native:
[P27534:T1:semget02] trace: ---- return from shim_mprotect(...) = 0x0
[P27534:T1:semget02] trace: ---- shim_brk(0x0) = 0x40cbcc142000
[P27534:T1:semget02] trace: ---- shim_brk(0x40cbcc163000) = 0x40cbcc163000
[P27534:T1:semget02] trace: ---- shim_geteuid() = 0x0
[P27534:T1:semget02] warning: Unsupported system call setresuid
[P27534:T1:semget02] trace: ---- shim_ioctl(1, TCGETS, 0x40cbca92f210) ...
[P27534:T1:semget02] trace: ---- return from shim_ioctl(...) = -38
[P27534:T1:semget02] trace: ---- shim_newfstatat(1, "", 0x40cbca92f150, 4096) = 0x0
[P27534:T1:semget02] trace: ---- shim_ioctl(1, TCGETS, 0x40cbca92f0c0) ...
[P27534:T1:semget02] trace: ---- return from shim_ioctl(...) = -38
[P27534:T1:semget02] trace: ---- shim_write(1, 0x40cbcc1422c0, 0x4e) ...
semget02    0  TINFO  :  setreuid failed to to set the effective uid to 65534
[P27534:T1:semget02] trace: ---- return from shim_write(...) = 0x4e
[P27534:T1:semget02] trace: ---- shim_dup(2) = 0x3
[P27534:T1:semget02] trace: ---- shim_fcntl(3, F_GETFL, 0x40cbc9c93fd1) = 0x401
[P27534:T1:semget02] trace: ---- shim_close(3) = 0x0
[P27534:T1:semget02] trace: ---- shim_write(2, 0x40cbca92e240, 0x23) ...
setreuid: Function not implemented

Detailed log is attached as well. We discussed this observation as well in bug scrub meeting and then identified as issue.
[semget02_graphene.log](https://github.com/oscarlab/graphene/files/6530018/semget02_graphene.log)

**Comment by boryspoplawski** [comment]
`ltpuser` is used. `tst_resm(TINFO, "setreuid failed to "
"to set the effective uid to %d", `**ltpuser->pw_uid**`);`

The code you pasted is wrong, has a memory fault in user app, which is in no way related to Graphene.
If you think there is a bug in Graphene itself, please point to the offending line or attach code causing the issue.
Also note you used different compilations of Graphene (judging from paths in the logs), so maybe you applied different patches on each of them?
