### ISSUE TITLE
[Linux-SGX] Error of process Builder.

### ISSUE THREAD

**Issue by DiegoCao** [oscarlab/graphene#2388]
## Description of the problem

Compared with the commit on 1b8848bdae09fa0e92e4644b7fbd4e8c6cd1718c (on Jan 21), for the SGX graphene, the current new master has issues with the ProcessBuilder with Java.

Sample java code
```java=
package com.mycompany.app;

import java.io.File;
import java.io.IOException;

public class Testls{public static void main(String[] args) throws IOException {

    try{
        String[] cmds = {"ls"};
        ProcessBuilder builder = new ProcessBuilder(cmds);
        builder.redirectErrorStream(true);
        File file = new File("ls.log");
        builder.redirectOutput(file);
        Process process = builder.start(); // the error for SGX appears in this line.
        if (process.waitFor() != 0){
            // cannot run
            System.exit(1);
        }
        System.out.println("######## test ls finished ##############\n");



    }catch (IOException ex){
        ex.printStackTrace();
    }
    catch (java.lang.InterruptedException ex){
        ex.printStackTrace();
    }

}
}
```
Outside SGX environment the code can run well without error, but inside the code there will be error, and error for java part is:

```
java.io.IOException: Cannot run program "ls": error=22, Invalid argument
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.mycompany.app.Testls.main(Testls.java:14)
Caused by: java.io.IOException: error=22, Invalid argument
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 1 more
```

And the full log is attached here.
[Testls_sgx_logall.log](https://github.com/oscarlab/graphene/files/6513490/Testls_sgx_logall.log)

However on previous commit (on Jan 21) with SGX environments, no such error occurs.

**Comment by glorysdj** [comment]
@DiegoCao please also provide info of epc size and enclave size

**Comment by dimakuv** [comment]
> Outside SGX environment the code can run well without error

What do you mean by this? Do you mean Graphene in non-SGX mode (`graphene-direct`)?

**Comment by DiegoCao** [comment]
> > Outside SGX environment the code can run well without error
> 
> What do you mean by this? Do you mean Graphene in non-SGX mode (`graphene-direct`)?

I mean run java program simply by:
```
java -cp sample.jar com.mycompany.app.Testls
```

**Comment by dimakuv** [comment]
Please try the same in non-SGX Graphene mode. Will it work, or will it fail in the same way?

**Comment by DiegoCao** [comment]
> Please try the same in non-SGX Graphene mode. Will it work, or will it fail in the same way?

I have tried the non-SGX mode and it worked with no errors.

**Comment by dimakuv** [comment]
> @DiegoCao please also provide info of epc size and enclave size

Could you provide this info? If non-SGX mode of Graphene works fine, then it can be because of the limitations of your testing machine. In particular, a machine with too-small RAM may decide to kill Graphene processes (because that's what Linux does when it notices that too much RAM is used by some processes).

> However on previous commit (on Jan 21) with SGX environments, no such error occurs.

As I mentioned above, the failure may happen because of the limitations of your machine. Did you test the new Graphene commit on the exact same machine? In particular, amount of RAM (and the size of the swap file, if any) is important here; as well as the enclave sizes you use.

**Comment by DiegoCao** [comment]
The SGX size is 64G and the epc size is 256G. I test the new Graphene commit on exactly the same machine.

**Comment by dimakuv** [comment]
Could you provide the info on the available RAM and swap file? You can just copy-paste the output of the `free -h` command.

**Comment by dimakuv** [comment]
Actually, I have a strong feeling that this new error happens because of the interrupts during parent process's sending of the checkpoint. It looks like the parent's `send()` of a part of the checkpoint state is interrupted, and Graphene treats it as non-restartable syscall and errors out. We're currently working on fixing this problem. As soon as we have a fix, we will ask you to try out the new change.

**Comment by DiegoCao** [comment]
The info of swap is as follows.
```
              total        used        free      shared  buff/cache   available
Mem:           251G        4.1G        219G        3.3M         28G        245G
Swap:          2.0G          0B        2.0G
```

**Comment by dimakuv** [comment]
Thanks! So it's not about the small amount of RAM/EPC. This should be definitely enough to create 2 SGX enclaves, each 64GB in size.

@DiegoCao If you want to, you can try this PR: https://github.com/oscarlab/graphene/pull/2392. I hope this one fixes your issues.

**Comment by boryspoplawski** [comment]
@dimakuv #2392 handles emulated syscall restarting and is not connected to Graphene internal sends in any way.

**Comment by glorysdj** [comment]
BTW, is there any way to add this to graphene's tests for ci/cd?

**Comment by boryspoplawski** [comment]
By inspecting the provided logs and Graphene code I was able to find the offending line: https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_process.c#L313 The java process tries to checkpoint a memory region with ~16GB and this fails.
@dimakuv you seem to be the last touching it, maybe you remember better, but this seems to be a historical quirk from times when ocalls used 32bit sizes.

**Comment by dimakuv** [comment]
@boryspoplawski Thanks! This is indeed the root cause.

> @dimakuv you seem to be the last touching it, maybe you remember better, but this seems to be a historical quirk from times when ocalls used 32bit sizes.

Yes :( I didn't modify that logic at all, just simplified it. And you can guess where the original implementation came from :)

There seem to be no obstacles in having 64-bit values everywhere, so let me just remove this useless check and submit a quick PR.

**Comment by dimakuv** [comment]
> BTW, is there any way to add this to graphene's tests for ci/cd?

@glorysdj No, I don't think we want to add this test to our CI/CD. Sending ~16GB of data from one enclave to another enclave is very slow (on our wimpy NUC machines with 128MB of EPC). This will probably take a couple minutes, even if we restrict our test to sending only 4GB of data...

**Comment by dimakuv** [comment]
@glorysdj @DiegoCao Could you check if PR #2414 solves your issue? And thanks for reporting this bug!

@boryspoplawski Could you take a look at #2414? Does it seem reasonable to you?

**Comment by boryspoplawski** [comment]
@dimakuv Thanks for the PR, looks good!

**Comment by glorysdj** [comment]
> > BTW, is there any way to add this to graphene's tests for ci/cd?
> 
> @glorysdj No, I don't think we want to add this test to our CI/CD. Sending ~16GB of data from one enclave to another enclave is very slow (on our wimpy NUC machines with 128MB of EPC). This will probably take a couple minutes, even if we restrict our test to sending only 4GB of data...

Regarding to sending ~16GB data between enclaves, is there anyway to avoid this? Is dynamic epc memory management supported?

**Comment by dimakuv** [comment]
> Regarding to sending ~16GB data between enclaves, is there anyway to avoid this? Is dynamic epc memory management supported?

Enclave Dynamic Memory Management (EDMM) is not yet supported by the Intel SGX driver (the one that ships with Linux), so Graphene also doesn't support EDMM at this point. As soon as EDMM lands in the Intel SGX driver, Graphene will also have support for it.

I don't think there is any way of avoiding this, other than playing with Java Virtual Machine settings (and avoiding process forks in your Java application). Unfortunately, JVM is pretty "dumb" when it comes to memory consumption.

**Comment by DiegoCao** [comment]
Hi, I have tried with the new master branch and PR yet the previous problem with processBuilder still exists.

**Comment by dimakuv** [comment]
Could you attach the manifest and the Makefile/build instructions? And the command line how you start this.

I will try to reproduce this issue at some point.

**Comment by DiegoCao** [comment]
The java.manifest.sgx is as follows:
```
# DO NOT MODIFY. THIS FILE WAS AUTO-GENERATED.

[loader]
preload = "file:/graphene/Runtime/libsysdb.so"
log_level = "all"
insecure_disable_aslr = 1
insecure__use_cmdline_argv = 1
pal_internal_mem_size = "512M"

[libos]
entrypoint = "file:/opt/jdk8/bin/java"

[sgx]
file_check_policy = "allow_all_but_log"
static_address = 1
enclave_size = "64G"
thread_num = 1024
allow_file_creation = 1
nonpie_binary = 1
isvprodid = 0
isvsvn = 0
remote_attestation = 0
debug = 1
require_avx = 0
require_avx512 = 0
require_mpx = 0
require_pkru = 0
support_exinfo = 0
enable_stats = 0

[loader.env]
LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu:/usr//lib/x86_64-linux-gnu:/opt/jdk8:/opt/jdk8/lib/amd64/jli"
PATH = "/:/opt/jdk8/bin:/usr/sbin:/usr/bin:/sbin:/bin"
JAVA_HOME = "/opt/jdk8"
JAVA_OPTS = "'-Djava.library.path=/opt/jdk8/lib -Dsun.boot.library.path=/opt/jdk8/lib'"
SPARK_LOCAL_IP = "172.17.0.1"
SPARK_USER = "root"
SPARK_SCALA_VERSION = "2.11"
SPARK_HOME = "/ppml/trusted-big-data-ml/work/spark-2.4.3"
SPARK_MASTER_OPTS = "'-Dspark.worker.timeout=60'"

[sgx.trusted_files]
preload0 = "file:/graphene/Runtime/libsysdb.so"
java = "file:/opt/jdk8/bin/java"
date = "file:/bin/date"
setsid = "file:/usr/bin/setsid"
bash = "file:/bin/bash"
rm = "file:/bin/rm"
ld = "file:/graphene/Runtime/ld-linux-x86-64.so.2"
libc = "file:/graphene/Runtime/libc.so.6"
libm = "file:/graphene/Runtime/libm.so.6"
libdl = "file:/graphene/Runtime/libdl.so.2"
librt = "file:/graphene/Runtime/librt.so.1"
libpthread = "file:/graphene/Runtime/libpthread.so.0"
libnsscompat = "file:/lib/x86_64-linux-gnu/libnss_compat.so.2"
libnssfiles = "file:/lib/x86_64-linux-gnu/libnss_files.so.2"
libnssnis = "file:/lib/x86_64-linux-gnu/libnss_nis.so.2"
libnsl = "file:/lib/x86_64-linux-gnu/libnsl.so.1"
libz = "file:/lib/x86_64-linux-gnu/libz.so.1"
jdk_libjli = "file:/opt/jdk8/lib/amd64/jli/libjli.so"
jdk_jvmcfg = "file:/opt/jdk8/jre/lib/amd64/jvm.cfg"
jdk_libverify = "file:/opt/jdk8/jre/lib/amd64/libverify.so"
jdk_libjava = "file:/opt/jdk8/jre/lib/amd64/libjava.so"
jdk_libzip = "file:/opt/jdk8/jre/lib/amd64/libzip.so"
jdk_libnet = "file:/opt/jdk8/jre/lib/amd64/libnet.so"
jdk_libnio = "file:/opt/jdk8/jre/lib/amd64/libnio.so"
jdk_libjawt = "file:/opt/jdk8/jre/lib/amd64/libjawt.so"
jdk_libawt = "file:/opt/jdk8/jre/lib/amd64/libawt.so"
jdk_libattach = "file:/opt/jdk8/jre/lib/amd64/libattach.so"
jdk_libdt_socket = "file:/opt/jdk8/jre/lib/amd64/libdt_socket.so"
jdk_libfontmanager = "file:/opt/jdk8/jre/lib/amd64/libfontmanager.so"
jdk_libjvm = "file:/opt/jdk8/jre/lib/amd64/server/libjvm.so"
jdk_libjsig = "file:/opt/jdk8/jre/lib/amd64/server/libjsig.so"

[sgx.allowed_files]
nsswitch = "file:/etc/nsswitch.conf"
ethers = "file:/etc/ethers"
hosts = "file:/etc/hosts"
group = "file:/etc/group"
passwd = "file:/etc/passwd"
gaiconf = "file:/etc/gai.conf"
tmp = "file:/tmp"

[sgx.trusted_checksum]
preload0 = "68b31c43a12e364fb507e53e80d66816947d8dce2bb714160b9c3b8a618a9caa"
java = "68321a236310f3e1d65a8505afa118c8c06193bf86809a65b483493110e8ea5d"
date = "1f5e7c13d30a44a211f0cb86e9bf8ff75e7ccf04fed673437b3f86a8893f8bc6"
setsid = "069583575bc4d97de8acd9bf3dd7c725903d16b8604261358f11d6f4f9594bc3"
bash = "60e7389ed7264278cbb60eb77d4ddd7023cbfc1184ece1acea8926efe7d5657c"
rm = "7576b1865d9cf2acf2d41320df0413cbabee0cdff2ac175e4f5f2cd1a4a15523"
ld = "b40bae0901406963770097229446da8109206b2aba1c9410649c9081f4b41850"
libc = "479161931f0587965529208285d9fe1b4344549cc1548f51e27b03deac9e7868"
libm = "d6bb42f58e7c54cd0c042c33cfc2bf12489e61e118de9300e5554f6861ab4e79"
libdl = "8b5775069b7a485d2bf53e621d2e4d711ccae73a70f7c2fc956202cd47501dcb"
librt = "15549ee4ef96941ee4ee89152ea48c9d189cc67126d577a69eb9e334cc35b677"
libpthread = "7d8ad33d33ecc0af935acf8074df418a973ac958a3b229be5a597de5453944e6"
libnsscompat = "c78ab73d4800d19413945e938453a883fbc7b2010c874bbf5d6124ade060004b"
libnssfiles = "38d6029b89233409f935dcd32b0561e2ceda8e7fd1aa90d97aa836f6027e999d"
libnssnis = "33c429d3e8f272389c7d2ac8bf2b98c5eb338f6a24b898182498b7bf7c9fb939"
libnsl = "eadb49e46bba2299e6ca190b2c8fe31b74bda12cfd4b251bbd0b9a20d462c0af"
libz = "219c6c0efe93bd6d751bba1e8ae84a162309c665cc5e36beddcf295b72f9bc09"
jdk_libjli = "ee8e22898bae93fb1916de08b7801d0c8b6416279601601e0b532cf6d56ca800"
jdk_jvmcfg = "257f372bd9fde12f89e063b15c169f5cfd5d2420619a2b015f861b02ef319e31"
jdk_libverify = "b2528007218e54e365d70844090f2ca968afb2d41f6233ebb71249b51c3ab9f8"
jdk_libjava = "de56e8c90d3639e4acf602fe72eacce39d547ae0c5d216c3da0f632641b0ed32"
jdk_libzip = "dbc0a1be68d96db5f92ccf5112eea47b649cefc2e8b503f2f628698a54ac0d67"
jdk_libnet = "fb93ddc262ccedaa83bb0fef6f035dede546af94c1d03b955a20224d957bbb5e"
jdk_libnio = "6b9b9e5b424f5796f07631de9735fa2977d4437f335eaf5fd5849b0f7aad978f"
jdk_libjawt = "ae246e45619d0957fa978eda277684c30961c4286681bee482e353021fcdef54"
jdk_libawt = "02b5034656a3be4024527acaa815539ea26dafecfa4e385b1fb10d8d355b33e8"
jdk_libattach = "97ae9e42a44106762a13ab766af3406b7c487f0208bd1f0e1bbc3334f2dbf917"
jdk_libdt_socket = "62ac6cc8942d03fd7a3e016c73e71a05ee7d10ad623f2e6011856bdb7b24aacd"
jdk_libfontmanager = "dd33b02de51f2f0ad2b99217b075f23c7019953c798fc172250e56090f5cfb6d"
jdk_libjvm = "5d5f5b3a8664e4c9f82b1123f19b7ffb230bc8aafc533ee004720be6308a549d"
jdk_libjsig = "8b307911f4e3ecb41c4ccf77919a545ee04bc59913d8b2c1108184638bfd4ca3"

[fs.mount.lib]
type = "chroot"
path = "/lib"
uri = "file:/graphene/Runtime"

[fs.mount.lib2]
type = "chroot"
path = "/lib/x86_64-linux-gnu"
uri = "file:/lib/x86_64-linux-gnu"

[fs.mount.lib3]
type = "chroot"
path = "/usr/lib/x86_64-linux-gnu"
uri = "file:/usr/lib/x86_64-linux-gnu"

[fs.mount.usrbin]
type = "chroot"
path = "/usr/bin"
uri = "file:/usr/bin"

[fs.mount.etc]
type = "chroot"
path = "/etc"
uri = "file:/etc"

[fs.mount.opt]
type = "chroot"
path = "/opt"
uri = "file:/opt"

[fs.mount.bin]
type = "chroot"
path = "/bin"
uri = "file:/bin"

[fs.mount.tmp]
type = "chroot"
path = "/tmp"
uri = "file:/tmp"

[fs.mount.work]
type = "chroot"
path = "/ppml/trusted-big-data-ml/work"
uri = "file:/ppml/trusted-big-data-ml/work"
```
Makefile:
```
GRAPHENEDIR ?= ../..
SGX_SIGNER_KEY ?= $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/enclave-key.pem

G_JAVA_XMX ?= 2G
G_SGX_SIZE ?= 8G
G_SGX_THREAD_NUM ?= 256

THIS_DIR ?= /ppml/trusted-big-data-ml
JDK_HOME ?= /opt/jdk8
SPARK_LOCAL_IP ?= 127.0.0.1
SPARK_USER ?= root
SPARK_HOME ?= $(THIS_DIR)/work/spark-2.4.3/
WORK_DIR ?= $(THIS_DIR)/work

ifeq ($(DEBUG),1)
GRAPHENE_LOG_LEVEL = debug
else
GRAPHENE_LOG_LEVEL = error
endif

.PHONY: all
all: java.manifest | pal_loader
ifeq ($(SGX),1)
all: java.token
endif

include $(GRAPHENEDIR)/Scripts/Makefile.configs

#### java
java.manifest: java.manifest.template
        /graphene/python/graphene-manifest \
            -DGRAPHENEDIR=$(GRAPHENEDIR) \
            -DGRAPHENEDEBUG=$(GRAPHENEDEBUG) \
            -DARGV0_OVERRIDE=java \
            -DEXECPATH=$(shell which java) \
            -DEXECDIR=$(shell dirname $(shell which java)) \
            -DARCH_LIBDIR=$(ARCH_LIBDIR) \
            -DJDK_HOME=$(JDK_HOME) \
            -DSPARK_LOCAL_IP=$(SPARK_LOCAL_IP) \
            -DSPARK_USER=$(SPARK_USER) \
            -DSPARK_HOME=$(SPARK_HOME) \
            -DWORK_DIR=$(WORK_DIR) \
            -DG_SGX_SIZE=$(G_SGX_SIZE) \
            $< > $@

java.manifest.sgx: java.manifest
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-sign \
                -libpal $(GRAPHENEDIR)/Runtime/libpal-Linux-SGX.so \
                -key $(SGX_SIGNER_KEY) \
                -manifest java.manifest -output $@

java.sig: java.manifest.sgx

java.token: java.sig
        $(GRAPHENEDIR)/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token \
                -output java.token -sig java.sig

pal_loader:
        ln -s $(GRAPHENEDIR)/Runtime/pal_loader $@

.PHONY: regression
regression: all
        @mkdir -p scripts/testdir

        ./pal_loader ./bash -c "ls" > OUTPUT
        @grep -q "Makefile" OUTPUT && echo "[ Success 1/6 ]"
        @rm OUTPUT

        ./pal_loader ./bash -c "cd scripts && bash bash_test.sh 1" > OUTPUT
        @grep -q "hello 1" OUTPUT      && echo "[ Success 2/6 ]"
        @grep -q "createdfile" OUTPUT  && echo "[ Success 3/6 ]"
        @grep -q "somefile" OUTPUT     && echo "[ Success 4/6 ]"
        @grep -q "current date" OUTPUT && echo "[ Success 5/6 ]"
        @rm OUTPUT

        ./pal_loader ./bash -c "cd scripts && bash bash_test.sh 3" > OUTPUT
        @grep -q "hello 3" OUTPUT      && echo "[ Success 6/6 ]"
        @rm OUTPUT

        @rm -rf scripts/testdir


.PHONY: clean
clean:
        $(RM) *.manifest *.manifest.sgx *.token *.sig trusted-libs pal_loader OUTPUT scripts/testdir/*

.PHONY: distclean
distclean: clean
```

**Comment by dimakuv** [comment]
Not really related to the error, but why do you have these variables declared in the Makefile:
```
G_JAVA_XMX ?= 2G
G_SGX_SIZE ?= 8G
G_SGX_THREAD_NUM ?= 256
```

But they are not used anywhere? Did you try to use them? How did it go? Did the error that you report still persist with these 2G/8G sizes?

**Comment by boryspoplawski** [comment]
Is it really failing in the same way? New error log could be useful.

**Comment by DiegoCao** [comment]
I attach the error log here for the new Master branch and it still fails. The error log is:
[Testls_sgx_logall.log](https://github.com/oscarlab/graphene/files/6693303/Testls_sgx_logall.log)

**Comment by boryspoplawski** [comment]
@DiegoCao Could you provide commit hash which you used? Simple local test send big (4GB) checkpoints successfully and provided log doesn't give much more info (than that sending failed).

**Comment by DiegoCao** [comment]
Hi, the commit hash I use is 6eb3b8e33203a8f43646dac8d1c58f15416806fc.

**Comment by boryspoplawski** [comment]
This commit is not even in the master branch (or actually any other) and definitely is not and never was the latest master.
