### ISSUE TITLE
shim_do_epoll_wait() ignores user-supplied timeout

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#239]
I test Redis 5.0 and noticed that [`shim_do_epoll_wait()`](https://github.com/oscarlab/graphene/blob/master/LibOS/shim/src/sys/shim_epoll.c) completely ignores user-supplied `timeout` argument.

In case of Redis in Cluster mode, this broke the failure-detection semantics because `poll()` waited indefinitely for client connections and thus did not send periodic heartbeat messages to other instances in the cluster. This led Redis instances to believe that all other instances are failed and panic.

I don't know why this logic is used in Graphene; I notice it was there since the very beginning. Is it just a bug or there is some rationale to ignore user-supplied timeout values?

I fixed this issue as follows:
```
diff --git a/LibOS/shim/src/sys/shim_epoll.c b/LibOS/shim/src/sys/shim_epoll.c
index b936005..e42de90 100644
--- a/LibOS/shim/src/sys/shim_epoll.c
+++ b/LibOS/shim/src/sys/shim_epoll.c
@@ -316,8 +316,15 @@ retry:

     unlock(epoll_hdl->lock);

-    PAL_HANDLE polled = DkObjectsWaitAny(nread ? npals + 1 : npals, pal_handles,
-                                         nread ? NO_TIMEOUT : 0);
+    /* BUGFIX: Before `timeout` was never considered */
+    PAL_HANDLE polled = NULL;
+    if (timeout >= 0) {
+        polled = DkObjectsWaitAny(nread ? npals + 1 : npals, pal_handles,
+                nread ? timeout : 0);
+    } else {
+        polled = DkObjectsWaitAny(nread ? npals + 1 : npals, pal_handles,
+                nread ? NO_TIMEOUT : 0);
+    }

     lock(epoll_hdl->lock);

```

(The `if (timeout >= 0)` is not strictly necessary, but I wanted to be on the safe side.)

**Comment by donporter** [comment]
I am not aware of any rationale for this.  In general, the goal is compatibility with Linux, so this seems like a clear bug.

I think the fix is pretty straightforward.  Maybe just set timeout to NO_TIMEOUT and have one call to DkObjectsWaitAny?

It would be good to have a unit test for this.  I suspect one may already exist in LTP that just isn't passing.  

But otherwise, this fix looks like a no-brainer to me.

**Comment by dimakuv** [comment]
PR is posted, with a unit test. See PR #249.
