### ISSUE TITLE
RFC: Make URIs absolute

### ISSUE THREAD

**Issue by pwmarcz** [oscarlab/graphene#2415]
## Problem

PAL happily accepts relative URIs, including paths like `..`. These are passed verbatim to the host system, and treated as paths starting from current working directory, but this is completely implicit.

Problems in code that I know of:
- LibOS wants to [know where the executable is mounted](https://github.com/oscarlab/graphene/blob/8fad86c04f65027800d4dc9bf27f85a70747637d/LibOS/shim/src/bookkeep/shim_handle.c#L76), and this does not work in the general case (if the executable is `file:foo`, and we mount `file:/`, we have no way of knowing where `foo` is relative to `/`
- We report relative file paths to GDB integration and profiling, the SGX profiler [works around this by using glibc realpath](https://github.com/oscarlab/graphene/blob/7b051043754c3860c04fe218f985a1d26123534d/Pal/src/host/Linux-SGX/sgx_profile.c#L321)
- The SGX code already [normalizes paths](https://github.com/oscarlab/graphene/blob/7b051043754c3860c04fe218f985a1d26123534d/Pal/src/host/Linux-SGX/db_files.c#L47) (i.e. trims `.` and `..` when possible), but keeps relative URIs relative.

I feel that overall the code would be less brittle, and easier to debug, if it operated on absolute paths. But it does add some complexity to ensure them.

## Solution

Make sure **PAL APIs only accept absolute paths** (I think that applies to `file:` and `dir:`).

Accept relative paths in manifests, and interpret them as path relative **to the manifest location**. Convert them to absolute when reading from manifest.

(I don't think we want to disallow relative paths in manifest: they are way too useful. Without them, a directory with manifest and Graphene program is not relocatable, and you have to generate all paths from a template).

## Implementation

1. PAL must know the "origin" path, i.e. directory the manifest is in. Unfortunately this involves `realpath(3)` or equivalent mechanism, which is not always available, and I don't think we should reimplement it (it involves resolving symlinks, etc.)

  I propose to add manifest realpath path as an argument to `libpal`, so that the shell wrapper (`pal_loader`) can compute it.

2. We need to convert the URIs to absolute. We parse them in both PAL and LibOS, so I think this should be a PAL API:

```
/* Convert `file:` and `dir:` relative URIs to absolute, prepending the manifest paths */
int DkConvertUri(const char* uri_rel, char** uri);
```

Parsing the manifest would look like this (error handling omitted):

```
toml_string_in(g_manifest_root, "fs.root.uri", &fs_root_uri_rel);
DkConvertUri(fs_root_uri_rel, &fs_root_uri);
free(fs_root_uri_rel);
```

## Symlinks?

The above solution does not traverse all symlinks correctly. For example, a relative path `file:foo/../bar` will be converted to `file:/<manifest path>/bar`, even if `foo` is a symlink and `foo/../bar` should point somewhere else according to Unix path semantics.

We could disallow such cases by saying that manifest paths can only *begin* with any number of `..` segments, not contain them in the middle. Then, any `..` segments will be resolved relative to the manifest real paths, with no symlinks involved.

**Comment by pwmarcz** [comment]
>LibOS wants to know where the executable is mounted,

Counterpoint: maybe LibOS shouldn't be interested in details of URIs, and the above is a design mistake. Instead, `libos.entrypoint` in manifest should be a Graphene path, not URI.

**Comment by boryspoplawski** [comment]
I think your counterpoint is valid: LibOS shouldn't really care about host URIs, it just needs to store them and pass to PAL. Making `libos.entrypoint` a Graphene path makes total sense, if it would work, thne please do it :)
Also I like the idea that we can pass a host path (URI) to PAL and it can contain (host level) symlinks: it gives a lot of flexibility when setting up Graphene.

**Comment by pwmarcz** [comment]
Okay, I'm going in the suggested direction, closing. Thanks for the feedback.
