### ISSUE TITLE
Pal/regression seems broken after 13afef4313b3dfcc3fad73e5ecc685a2c133418f

### ISSUE THREAD

**Issue by jurobystricky** [oscarlab/graphene#2425]
## Description of the problem
Running Pal regresions seems broken
## Steps to reproduce
<pre>
$ git clone https://github.com/oscarlab/graphene.git
$ cd graphene
$ make -j32
$ cd Pal/regression/
$ make regression
</pre>

## Expected results
Regression tests passed, something like:
<pre>
==== 35 passed, 4 skipped in 12.48 seconds ====
</pre>

## Actual results
<pre>
...
make[2]: Leaving directory '/home/juro/pr/graphene/common/src'
make[1]: *** No rule to make target '../../Runtime/libpal-Linux.so', needed by '..Bootstrap'.  Stop.
make[1]: Leaving directory '/home/juro/pr/graphene/Pal/regression'
make: *** [Makefile:122: regression] Error 2
</pre>

The commit 0b814ebe4e93844f5e929271215f983ca7f229f5 preceding 13afef4313b3dfcc3fad73e5ecc685a2c133418f works:
<pre>
$ git clone https://github.com/oscarlab/graphene.git
$ cd graphene
$ git checkout 0b814ebe4e93844f5e929271215f983ca7f229f5
$ make -j32
$ cd Pal/regression/
$ make regression
...
==== 35 passed, 4 skipped in 12.48 seconds ====

</pre>

I am aware the Graphene build system is being redesigned. However, I do not think the above problem is intentional.

**Comment by woju** [comment]
Yes, this wasn't intentional. I wonder, why it even works before this commit. For now you can add `pal_lib=` argument to `make regression`, like in `.ci`: https://github.com/oscarlab/graphene/blob/293ed2032e709807bfc238728e6f55aa6c7d5d61/.ci/lib/stage-test.jenkinsfile#L21-L26 That's also why this wasn't caught...
