### ISSUE TITLE
Graphene-SGX: Execution of waitpid03 ltp test lead to inconsistent results

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2426]
## Description of the problem
Execution of waitpid03 ltp test lead to inconsistent results for Graphene-SGX

Syscalls -> waitpid(wait for a child process to stop or terminate)
Syntax ->   pid_t waitpid(pid_t pid, int *stat_loc, int options);
 
The waitpid() system call suspends execution of the calling process until a child specified by pid argument has changed state. By default, waitpid() waits only for terminated children, but this behavior is modifiable via the options argument.
The value of pid can be:
 
1.	< -1        :              meaning wait for any child process whose process group ID is equal to the absolute value of pid.
2.	-1           :              meaning wait for any child process.
3.	0             :              meaning wait for any child process whose process group ID is equal to that of the calling process.
4.	> 0          :              meaning wait for the child whose process ID is equal to the value of pid
 
TestFile: Waitpid03
Description: Parent forks numerous children, and starts waits, it Should only wait for the specific child, a second wait on the same child should return with -1 and not one of the other zombied children.

## Steps to reproduce
Run waitpid03 ltp test

## Expected results
waitpid03    1  TPASS  :  Got correct child PID
waitpid03    2  TPASS  :  Condition 2 test passed

## Actual results
graphene-sgx waitpid03
**Observation 1:**
The killing of the process does not throw any error, syscall gets executed successfully and test passes.
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
waitpid03    1  TPASS  :  Got correct child PID
waitpid03    2  TPASS  :  Condition 2 test passed
```
 
**Observation 2:**
```
waitpid03    1  TPASS  :  Got correct child PID
waitpid03    2  TPASS  :  Condition 2 test passed
[P29289:T25:waitpid03] error: Sending IPC process-exit notification failed: -13
```
 
**Observation 3:**
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P29536:shim] error: IPC worker: receiving message header from 29509 failed: -13
[P29536:shim] error: IPC worker: failed to receive an IPC message from 29509: -13
[P29509:shim] error: Child process (vmid: 0x7360) got disconnected
[P29509:shim] error: Unknown process sent a child-death notification: pid: 8, vmid: 29536
[P29509:shim] error: IPC worker: error running IPC callback 1: -22
[P29540:T9:waitpid03] error: Sending IPC process-exit notification failed: -13
```

**Observation 4:**
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P30081:shim] error: IPC worker: receiving message header from 29977 failed: -13
[P30081:shim] error: IPC worker: failed to receive an IPC message from 29977: -13
[P29977:shim] error: Child process (vmid: 0x7581) got disconnected
waitpid03    1  TPASS  :  Got correct child PID
waitpid03    2  TPASS  :  Condition 2 test passed
```

I have attached the different graphene-sgx test logs and as well as trace logs for 2 scenarios in graphene-sgx. 
Latest Logs: waitpid03_testlogs.log
waitpid03_trace_1.log
waitpid03_trace_2.log

Result and observation has been updated with latest results
[waitpid03_testlogs.log](https://github.com/oscarlab/graphene/files/6806624/waitpid03_testlogs.log)
[waitpid03_trace_1.log](https://github.com/oscarlab/graphene/files/6806625/waitpid03_trace_1.log)
[waitpid03_trace_2.log](https://github.com/oscarlab/graphene/files/6806626/waitpid03_trace_2.log)

**Comment by dimakuv** [comment]
This issue is the same as https://github.com/oscarlab/graphene/issues/2531, so a duplicate. Closing.

**Comment by anjalirai-intel** [comment]
Please reopen the issue. The issue still exists for SGX.

**Standard Output**
```
waitpid03    1  TPASS  :  Got correct child PID
waitpid03    2  TPASS  :  Condition 2 test passed
```
**Standard Error**
```
[P25:T25:waitpid03] error: Sending IPC process-exit notification failed: -13
[P24:T24:waitpid03] error: Sending IPC process-exit notification failed: -13
```

**Comment by boryspoplawski** [comment]
I've verified this: the test works as expected and passes successfully on Graphene (on both PALs).
There is one small caveat: it sometimes indeed print an error as stated above, but it's a known issue (https://github.com/gramineproject/gramine/issues/21) and it does not cause the test to fail and does not affect it in any way (it's already after the test passed successfully). Keeping this closed.
