### ISSUE TITLE
Run hellowork failed due to ioctl failed

### ISSUE THREAD

**Issue by Yourens** [oscarlab/graphene#243]
I have followed the instructions in below link to build graphene for sgx.
https://github.com/oscarlab/graphene/wiki/SGX-Quick-Start
But when I tries to run hello work
I got this error
enclave ECREATE failed in enclave creation ioctl

**Comment by dimakuv** [comment]
Please provide more information:

1. Did you install Linux SGX SDK correctly? Does the Linux driver work? Can you run examples from SGX SDK (under `SampleCode`)?
  - Please install SGX SDK, SGX driver, and PSW from https://github.com/intel/linux-sgx/ and make sure everything runs and your machine has SGX enabled.

2. What is the complete output when you run your `helloworld`?

3. You can try to debug the enclave using gdb, simply prepend your command line with `GDB=1`, i.e., `GDB=1 SGX=1 ./pal_loader helloworld`.
  - To see debug symbols, you should rebuild Pal and LibOS. For this, in steps (2) and (4) of Quick Start Guide add `DEBUG=1` to make commands, i.e. `make SGX=1 DEBUG=1`.

**Comment by Yourens** [comment]
Thanks for your quick reply.
I have install the SGX SDK and I can run the sample code provided by the Intel SGX SDK. 
I revert intel SGX driver to version 1.9, and I download the intel sgx sdk and psw 1.9 binary from the website
https://download.01.org/intel-sgx/linux-1.9/
As Far as I can see, it's because the intel sgx driver return EINVAL when create enclave at line 169 at sgx_framework.c 
the most possible cause is at intel sgx driver, sgx_validate_secs function return EINVAL.
I don't know why.

**Comment by dimakuv** [comment]
Are you sure you specified the correct directory and version when you installed Graphene's SGX driver? (Step 3 in Quick Start of Graphene-SGX). It can be that you accidentally specified a wrong directory/version when you were prompted by Graphene's SGX driver. Please repeat Step 3 from scratch (`make clean` and `make && sudo ./load.sh` again).

**Comment by donporter** [comment]
Can you confirm that you tried the SDK sample code and it worked?  (or that some other SGX code did run on your system)

You also need to do a 'make SGX_RUN=1' after the initial compile to sign all of your binaries.

Failing that, send us the complete output of a debug run (as explained above), and let us know any other characteristics of the machine that can help us reproduce your issue (what linux distro/version, what CPU you are using, etc).

**Comment by Yourens** [comment]
Hey, Don,

Thanks for your kindly remind. 
I actually visited every possible reasons, rechecked at SGX setting in BIOS, running sample code(some of them succeeded like SampleEnclave and LocalAttestation). I erase whole system and reinstall ubuntu 16.04 and graphene but still have the same problem. 
I don't know why so I use another computer then it works well now.
The significant different between two computers is the CPU. The computer which I encounter the problem has the 8th CPU with SGX 2 support but another one which is working has 7th CPU. 
I'm not sure about the real reason. It's all about my guess. Hence, if this bug are not reproducible at others SGX2 CPU, please don't bother it... 

I'm really appreciate for your help.

**Comment by rainfld** [comment]
Hi, @Yourens I suspect you actually hit the bug of graphene running on non-avx platform. Could you first check if your platform supports avx instruction set by "cat /proc/cpuinfo |grep avx"?

**Comment by Yourens** [comment]
Hi, @rainfld 
Thanks for your suggestion!! 
That's exactly the reason!
