### ISSUE TITLE
failed to create SGX docker image

### ISSUE THREAD

**Issue by ratnadeepb** [oscarlab/graphene#2435]
## Description of the problem
Attempting to create a SGX docker image results in a Python jinja2 TemplateNotFound exception

## Steps to reproduce

```
sudo docker pull envoyproxy/envoy-build
openssl genrsa -3 -out enclave-key.pem 3072
sudo ../graphene/Tools/gsc/gsc build --insecure-args envoyproxy/envoy-build ../graphene/Tools/gsc/test/ubuntu18.04-nodejs.manifest
```

## Expected results
Create an SGX version of the image

## Actual results
```
$ sudo ../graphene/Tools/gsc/gsc build --insecure-args envoyproxy/envoy-build ../graphene/Tools/gsc/test/ubuntu18.04-nodejs.manifest
Building unsigned graphenized Docker image `gsc-envoyproxy/envoy-build-unsigned` from original application image `envoyproxy/envoy-build`...
Traceback (most recent call last):
  File "../graphene/Tools/gsc/gsc", line 12, in <module>
    sys.exit(main(sys.argv))
  File "../graphene/Tools/gsc/gsc.py", line 416, in main
    return args.command(args)
  File "../graphene/Tools/gsc/gsc.py", line 165, in gsc_build
    build_template = env.get_template(f'Dockerfile.{env.globals["Distro"]}.build.template')
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: Dockerfile.ubuntu18.04.build.template
```
## Additional information
1. The environment is a virtualbox Ubuntu 20.04 VM (issue?)
2. SGX is not available, I am hoping to run this in simulation

**Comment by dimakuv** [comment]
Sorry, GSC is currently broken. We're moving to a new build/deployment system in core Graphene, which breaks GSC. We'll fix GSC as soon as this migration to the new build system is done.

**Comment by ratnadeepb** [comment]
Thanks for the update. Until such time, is there another way to dockerize graphene apps?

**Comment by dimakuv** [comment]
@ratnadeepb You can specify a particular Graphene commit in the GSC's configuration file: https://github.com/oscarlab/graphene/blob/master/Tools/gsc/config.yaml.template#L9.

Simply replace `"master"` with the specific commit ID. For example, a good candidate (I think) should be: a743b6a83b4f3587e1d72b53509239c21d3c1231. So you can replace with `"a743b6a83b4f3587e1d72b53509239c21d3c1231"`.
