### ISSUE TITLE
PYTHONPATH lookup failure

### ISSUE THREAD

**Issue by nyannko** [oscarlab/graphene#244]
Hi,

I was trying to import python application to graphene OS, and I met the following problem.

Without the modification of the `python.manifest.tamplate`, the default python import path is like,

```
$ ./python.manifest -c "import sys; print '\n'.join(sys.path).strip()"
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
```

I don't know why this path is different with the local python path (without the local
directory  `/home/umr/.local/lib/python2.7/site-packages`). So I added a line in `python.manifest.tample` ,

```
loader.env.PYTHONPATH = /usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/home/umr/.local/lib/python2.7/site-packages:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages
```

The local python path was loaded, but the third parties lib inside the local directory still cannot be imported. I also tried to execute `pip` to lookup modules, but the code throws an assert error,

```
$ ./python.manifest -c "import sys; print '\n'.join(sys.path).strip()"
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/umr/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages


$ ./python.manifest -c "import datrie"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named datrie

$ ./python.manifest -c "import pip"
assert failed fs/shim_namei.c:297 start->state & DENTRY_ISDIRECTORY (value:0)
Trace/breakpoint trap (core dumped)
```

Does anyone know the solution? Thanks.

**Comment by chiache** [comment]
Sorry for the late reply. Is this issue resolved?

**Comment by nyannko** [comment]
Yeah, I remove local packages to the global directory.

**Comment by tarikova** [comment]
hi @nyannko: apologies for pinging on a resolved issue. I am wondering what libraries you were trying to import? I am currently trying to run numpy and it fails (details here: #267). Wondering if you could help.

Thanks a lot.

**Comment by nyannko** [comment]
Hi @tarikova , I cannot import numpy, here is my output:
```
$ ./python.manifest -c "import enum"
$ ./python.manifest -c "import twisted"
$ ./python.manifest -c "import cryptography"
$ ./python.manifest -c "import numpy"
Internal memory fault at 0x0 (IP = +0xa206f, VMID = 1813063638, TID = 1)
Trace/breakpoint trap (core dumped)
$ ./python.manifest -c "import networkx"
Internal memory fault at 0x0 (IP = +0xa206f, VMID = 1820010471, TID = 1)
Trace/breakpoint trap (core dumped)
```

**Comment by tarikova** [comment]
Thanks for your quick response @nyannko. I was able to run numpy and various other libraries. Please check #267

**Comment by tarikova** [comment]
And I know you have already closed the issue, but one way to solve it is to add path using sys library.
I do the following:
```
import sys
sys.path.append('/home/<USER_NAME>/.local/lib/python2.7/site-packages')
```

**Comment by ihepburn** [comment]
Another method is to set manifest file.
https://github.com/oscarlab/graphene/issues/267#issue-373334667 gives a correct configuration for **sys.path**, and
the path in  **sys.path** should be mounted and allowed at the same time.

In order to load **/home/umr/.local/lib/python2.7/site-packages**  suitably:
1. Mount the home dir:
```
fs.mount.home.type = chroot
fs.mount.home.path = /home
fs.mount.home.uri = file:/home
```
2. Authorize the path:
`/home/umr/.local/lib/python2.7/site-packages`

**Comment by kanakraju73** [comment]
Hi @nyannko @tarikova 

I'm facing similar issues while importing numpy.

$ ./python.manifest.sgx -c "import numpy"
Internal memory fault at 0x0 (IP = +0x1e5c6, VMID = 134455687, TID = 1)
^CIllegal instruction executed in enclave

can you share your manifest here. Thanks in advance.

**Comment by ihepburn** [comment]
Hi,

This is my manifest to run NumPy in Graphene-SGX.

**Comment by kanakraju73** [comment]
Hi @ihepburn , 

It seems like you forgot to attach manifest. Could you share it now?

Thanks,
Kanak

**Comment by ihepburn** [comment]
@kanakraju73, You should remove the .txt suffix in attachments. The numpytest is a Python NumPy test script.

[python.manifest.txt](https://github.com/oscarlab/graphene/files/2977181/python.manifest.txt)

[numpytest.py.txt](https://github.com/oscarlab/graphene/files/2977184/numpytest.py.txt)

**Comment by kanakraju73** [comment]
Thanks for the prompt response. It's working for me. Thanks a ton. 

Kanak.
