### ISSUE TITLE
Uninitialized hdl_hdr.fds

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#246]
In the Pal source files
    Pal/src/host/FreeBSD/db_streams.c:292
    Pal/src/host/Linux-SGX/db_streams.c:282
    Pal/src/host/Linux/db_streams.c:295
    1)      The struct hdl_hdr is defined as local variable
    2)      The ‘fds’ member of struct hdl_hdr is used without Initialization
    3)      The pointer to struct hdl_hdr is assigned to iov[0]
    4)      The iov is assigned to struct hdr as hdr.msg_iov
    5)      Do syscall with struct hdr as one of parameters
    The bug may cause the unexpected result from syscall.

**Comment by rainfld** [comment]
This issue has been resolved and PR merged. Close
