### ISSUE TITLE
Tests failing with latest commit [LibOS] Rework IDs management

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2488]
## Description of the problem
Test Failing with latest graphene: 205cbe0123978b7b178c413a172b0be38658ef55
1. tgkill03 :- Test Failed in CI but  it does not report as FAIL because the runltp_xml parser only checks for test returncode which is 0 here

     Old Result : https://localhost:8080/job/graphene-18.04/5841/testReport/apps/LTP/test_direct___tgkill03/ 
     New Result : https://localhost:8080/job/graphene-18.04/5860/testReport/apps/LTP/test_direct___tgkill03/ 

2. rt_sigtimedwait01 :- Test Failing with SGX. Timed out after 45.0 s.

## Expected results
```
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 00m 20s
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Invalid tgid failed as expected: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Invalid tid failed as expected: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/te
...[truncated 138 chars]...
graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Defunct tid failed as expected: ESRCH (3)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Defunct tgid failed as expected: ESRCH (3)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:108: TPASS: Valid tgkill call succeeded

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

## Actual results
```
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/lib/tst_test.c:1250: TINFO: Timeout per run is 0h 00m 20s
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Invalid tgid failed as expected: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Invalid tid failed as expected: EINVAL (22)
/home/jenkins/workspace/graphene-18.04/LibOS/shim/te
...[truncated 151 chars]...
4/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:101: TPASS: Defunct tid failed as expected: ESRCH (3)
**/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:105: TFAIL: Defunct tgid should have failed with ESRCH: SUCCESS (0)**
/home/jenkins/workspace/graphene-18.04/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/tgkill/tgkill03.c:108: TPASS: Valid tgkill call succeeded

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

**Comment by jinengandhi-intel** [comment]
Shouldn't we be looking at the other test? And shouldn't you get a confirmation from the issue filer before we close the issue?

**Comment by dimakuv** [comment]
Indeed, at least the second test (`rt_sigtimedwait01`) is not covered by the merged PR #2490. Reopening.

**Comment by boryspoplawski** [comment]
> Shouldn't we be looking at the other test? rt_sigtimedwait01 is failing with Graphene SGX and Anjali will provide more data for the same, once she is online.

Sorry, I've missed that his issue describes another test, since there was no info about it in email.

> And shouldn't you get a confirmation from the issue filer before we close the issue?

We were able to cleanly reproduce the issue, so there should be no need. Worst case we can reopen the issue, if it's still present.

**Comment by anjalirx-intel** [comment]
@dimakuv @boryspoplawski We have tested the rt_sigtimedwait01 with latest master, and it is getting passed.

But we want to run this tests with all nightly builds. Please wait till tomorrow morning for all nightly results

**Comment by anjalirx-intel** [comment]
@dimakuv Both the test is passed in all Jenkins. Closing this issue now.
