### ISSUE TITLE
ra-tls-mbedtls client failed.

### ISSUE THREAD

**Issue by 0400H** [oscarlab/graphene#2516]
Example:
[ra-tls-mbedtls](https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-mbedtls)

commit:
f1a9c785128522ae4abc604a7ae10f4d4e7f0573
2fdb529f81e839ef1d9638362c2c02a4e34af79f

Test case:
```
"Normal non-RA-TLS flows; without SGX and without Graphene": pass
"RA-TLS flows with SGX and with Graphene, ECDSA-based (DCAP) attestation": client failed
"RA-TLS flows with SGX and with Graphene, client with its own verification callback": client failed
```

Server log:
```
root@2948a0b42f8b:/graphene/Examples/ra-tls-mbedtls# error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!

  . Creating the RA-TLS server cert and key... ok
  . Bind on https://localhost:4433/ ... ok
  . Seeding the random number generator... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ...
```

Client Error log:

```
root@2948a0b42f8b:/graphene/Examples/ra-tls-mbedtls# ./client dcap d70c81a5b95ad55945f675c5768e4e7da02bd94b278de0a826bf6d5bd48903f3 9ed2767918ad6ed4db6c140aa37f2d2a19090a5e6ccb420aad38e333ce3550fa 0 0
[ using our own SGX-measurement verification callback (via command line options) ]
  - ignoring ISV_PROD_ID
  - ignoring ISV_SVN

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Performing the SSL/TLS handshake... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x3000

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed

 failed
  ! mbedtls_ssl_handshake returned -30592

Last error was: -30592 - SSL - A fatal alert message was received from our peer

  . Waiting for a remote connection ...
```

**Comment by dimakuv** [comment]
Are you sure DCAP software stack is correctly installed and working on your machine?

**Comment by 0400H** [comment]
> Are you sure DCAP software stack is correctly installed and working on your machine?

I have used to run [PPML](https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html#background-on-remote-attestation-ra-tls-and-secret-provisioning) in same docker image and "secret_prov_server_dcap" in the host.

The container is running in an environment lacking internet currently.

Does the client need to connect to the Internet for sgx verification?

**Comment by dimakuv** [comment]
The client needs to connect to the PCCS (Provisioning Certificate Caching Service). This service is typically running on premises (in the same data center). E.g., if you're working on MS Azure, PCCS is available on one of the dedicated MS Azure servers. But if you're running in your single-machine testing environment, you probably installed PCCS on your machine.

Anyway, PCCS may require access to the PCS (Provisioning Certificate Service) from Intel. PCS is only available over Internet.

**Comment by 0400H** [comment]
> The client needs to connect to the PCCS (Provisioning Certificate Caching Service). This service is typically running on premises (in the same data center). E.g., if you're working on MS Azure, PCCS is available on one of the dedicated MS Azure servers. But if you're running in your single-machine testing environment, you probably installed PCCS on your machine.
> 
> Anyway, PCCS may require access to the PCS (Provisioning Certificate Service) from Intel. PCS is only available over Internet.

@dimakuv 

The libraries I install are as follows, it seems that the PCCS is missing currently.

```
apt-get install -y libsgx-pce-logic libsgx-ae-qve libsgx-quote-ex libsgx-qe3-logic sgx-aesm-service
apt-get install -y libsgx-dcap-ql-dev libsgx-dcap-default-qpl libsgx-dcap-quote-verify-dev
```

I will try it later.

**Comment by 0400H** [comment]
> The client needs to connect to the PCCS (Provisioning Certificate Caching Service). This service is typically running on premises (in the same data center). E.g., if you're working on MS Azure, PCCS is available on one of the dedicated MS Azure servers. But if you're running in your single-machine testing environment, you probably installed PCCS on your machine.
> 
> Anyway, PCCS may require access to the PCS (Provisioning Certificate Service) from Intel. PCS is only available over Internet.

@dimakuv 

After configuring the PCCS client settings(/etc/sgx_default_qcnl.conf) in container, the issue is solved, thanks.
