### ISSUE TITLE
readv system calls executes successfully fails when fd refers to a directory

### ISSUE THREAD

**Issue by anjalirai-intel** [oscarlab/graphene#2540]
## Description of the problem
Testcase to check the error condition of the readv(2) system call when fd refers to a directory.

## Steps to reproduce
Run LTP test readv03

## Expected results
readv03     1  TPASS  :  got EISDIR

## Actual results
readv03     1  TFAIL  :  Error: readv returned a positive value: errno=SUCCESS(0): Success

## Label
P0, bug

**Comment by dimakuv** [comment]
Even though it is unlikely that an app will try `pread(directory-fd)`, returning success is quite bad. So bumping priority.
