### ISSUE TITLE
FreeBSD PAL unusable

### ISSUE THREAD

**Issue by woachk** [oscarlab/graphene#256]
Is it worth it to try to fix it or it's so far behind that it's useless to do so?
(planning to use it for macOS)

**Comment by donporter** [comment]
I'd let @chiache weigh in on the scope.  I'd be excited to see this happen, but I wouldn't be surprised if it took a bit of work.

**Comment by mkow** [comment]
I'm voting for dropping FreeBSD PAL from master branch. Some arguments:
* No one maintains it.
* No one cares for it?
* Currently it's not tested in CI.
* Probably doesn't even work in current state.

We can try to find the most recent commit on which it was usable and point some branch there, for bookkeeping. Maybe in the future we'll find someone interested in supporting it.

**Comment by woachk** [comment]
@mkow Hi,

The FreeBSD PAL in its current state isn't enough to run the LibOS at all. Meanwhile, even the Linux PAL present in Graphene did severely diverge from the Microsoft Drawbridge API, nevermind the ABI, which evolved in its own way too, gaining proper SGX support in the process. 

I'm currently in the progress of documenting the Microsoft Drawbridge ABI & API as of today, as I ended up using Graphene as a base to make the PAL able to use Windows as a LibOS. 

I just care about the FreeBSD PAL for Darwin/macOS, and not for FreeBSD on its own.

An argument _against_: At least a non-Linux OS should be supported by this, and it won't be Windows*, so keeping FreeBSD might be something that would have to be done.

* Drawbridge runs on Windows in a picoprocess context to avoid shared user sections, and that can't be done for a PAL implemented in usermode in a proper way.

Thanks,

**Comment by mkow** [comment]
> I just care about the FreeBSD PAL for Darwin/macOS, and not for FreeBSD on its own.

That's a good argument actually.

We discussed this issue on our maintainers' call today and @chiache and @donporter declared that they'll try to take care of making FreeBSD PAL usable again (which includes adding it to Jenkins). We'll see how it goes and how much effort it takes to keep it up-to-date with changes to other parts of our codebase.

**Comment by woachk** [comment]
Alright, the FreeBSD PAL is not buildable again. I'll cook a fix again and then submit it here.

Maybe should I get my own CI running to prevent it becoming unbuildable in the future?

For macOS, I'd have to separate libpal.so from the launcher, because of Mach-O file format differences. (+ aliases to re-export printf not being possible with Mach-O being used instead of ELF)

**Comment by donporter** [comment]
#865 Should address this - we just need to actually land it.

We actually have a Jenkins job waiting in the wings to test this.

**Comment by woachk** [comment]
https://pastebin.ubuntu.com/p/hr6kBfK4VQ/

My local changes right now to get it building, on top of #865.

Still a regression compared to before because of the crash on launch:
`* thread #1, name = 'libpal.so', stop reason = signal SIGSEGV: invalid address (fault address: 0x2450)
    frame #0: 0x000000000102a36b pal-FreeBSD`init_slab_mgr + 235
pal-FreeBSD`init_slab_mgr:
->  0x102a36b <+235>: movl   %r12d, 0x10(%rax)
    0x102a36f <+239>: addq   $0x8, %rsi
    0x102a373 <+243>: imull  %r12d, %edi
    0x102a377 <+247>: movq   %rax, (%rdx)
`

**Comment by woachk** [comment]
At the time of its deletion, it worked in an minimal state, not enough to launch the LibOS after my patches. Probably was a wise decision to delete it, might get back to it some day.

(but as I'm going to work on Drawbridge soon at Microsoft, I might not be allowed to work on this, who knows?)

**Comment by mkow** [comment]
@woachk We can revive it once we find a maintainer for it ;)

The plan for now is to:

1. Find the most recent version which worked and link to it in the readme
2. Find a maintainer
3. Update the old working version to reach the same state as the other PALs. Actually, I think in the current state it would be easier to just copy Linux PAL and modify it to work on FreeBSD than to backport all the rewrites to the old FreeBSD PAL.

The requirement to merge output from 3. is to have a working integration with CI and someone who will declare to maintain it in the future, otherwise it will quickly degrade into the same state as it was recently.
