### ISSUE TITLE
[Tools] `graphene-manifest` doesn't ignore comment lines (`#`)

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#2581]
## Description of the problem

Our `graphene-manifest` utility invokes Jinja2's parser that doesn't recognize our TOML-style comments (starting with `#`). The particular offending line is here: https://github.com/oscarlab/graphene/blob/9f0943e39432e5440066c8448780a08eb4254c77/python/graphenelibos/manifest.py#L105

So if the user wrote something like this in the TOML manifest:
```
# libos.entrypoint = "{{ entrypoint }}" -- no, I don't want to use the variable, let's hardcode the path
libos.entrypoint = "/bin/bash"
```

And changed the manifest file from this:
```
bash.manifest: bash.manifest.template
	graphene-manifest -Dlog_level=$(GRAPHENE_LOG_LEVEL) -Dentrypoint=$(shell sh -c "command -v bash") $< >$@
```

to this:
```
bash.manifest: bash.manifest.template
	graphene-manifest -Dlog_level=$(GRAPHENE_LOG_LEVEL) $< >$@
```

The Jinja parses will still find `{{ entrypoint }}` in the manifest template, but there is no corresponding `-Dentrypoint` in the Makefile, and the build fails like this:
```
# make
graphene-manifest ...

Traceback (most recent call last):
  File "/usr/local/bin/graphene-manifest", line 5, in <module>
    sys.exit(main())
  ...
  File "/usr/local/lib/python3.7/dist-packages/graphenelibos/manifest.py", line 126, in main
    outfile.write(render(template, define))
  File "/usr/local/lib/python3.7/dist-packages/graphenelibos/manifest.py", line 105, in render
    return _env.from_string(template).render(**(variables or {}))
jinja2.exceptions.UndefinedError: 'entrypoint' is undefined
```

**Comment by dimakuv** [comment]
I'm not sure whether Jinja2 can be asked to ignore such TOML comments? Alternatively, we can have one more manifest preparation step where we remove all TOML comments via some other utility.

Or we can always just add this caveat to our docs :)

@woju @mkow What do you think?

**Comment by mkow** [comment]
Wait, this is perfectly fine and expected. That's how Jinja works. If you want to comment out something in Jinja, then you need to use Jinja comments, not TOML comments.

**Comment by dimakuv** [comment]
But this is extremely confusing to Graphene users. I was hoping that Jinja has some special integration with TOML, and we could just intrust it to ignore comments. Otherwise we need to create an intermediate file with removed TOML comments and feed this file to Jinja.

**Comment by mkow** [comment]
>But this is extremely confusing to Graphene users.

Maybe we could use .jinja or .toml.jinja extension to make it more clear that this file is _not_ in TOML, but in Jinja?

> I was hoping that Jinja has some special integration with TOML

Why would it? It's a template language, you use it to generate all possible kinds of text files. It's agnostic to the output format.

> Otherwise we need to create an intermediate file with removed TOML comments and feed this file to Jinja.

I'm not sure we should change anything except making users more aware that this is not parsed as TOML, but as Jinja, and _then_ in toml.

**Comment by mkow** [comment]
Alternative idea: just use Jinja comments in our examples, it doesn't matter if the comment lands in the final manifest.

**Comment by dimakuv** [comment]
Looks like this issue won't be resolved simply (I don't like Michal's proposals), so let's put a low priority on this. After all, this should be a rare case when someone does `# comment starts and then {{ jinja_template_occurs }}`.

**Comment by boryspoplawski** [comment]
+1 to using Jinja comments in examples and explaining in docs that we use Jinja + TOML.

**Comment by woju** [comment]
It's technically possible, we could do `env = jinja2.Environment(..., line_comment_prefix='#')`, that way Jinja will treat TOML comments the same as jinja comments, i.e. they won't appear in rendered output and jinja syntax won't be interpreted.

https://jinja.palletsprojects.com/en/3.0.x/api/#jinja2.Environment
https://jinja.palletsprojects.com/en/3.0.x/templates/#line-statements

I've never used this option, so I don't know if there are any surprises there. We should check this thoroughly beforehand, because if we commit to this change, undoing will be problematic, because it could break some manifest like the example here.

**Comment by mkow** [comment]
@woju: The problem with this is that you can't create a comment in the template which would go to the final rendered manifest. Not sure if that's a problem, but sounds like a limitation which (as you said) we won't be able to lift later without breaking compatibility.

**Comment by dimakuv** [comment]
@mkow From what I understand, using Jinja-style comments in our manifest files will lead to the same issue: comments will disappear from the final rendered manifest.

**Comment by woju** [comment]
I don't know if it's really a problem. Who needs comments in rendered manifests and why?

**Comment by dimakuv** [comment]
I agree. Doesn't seem like a problem to me.

**Comment by mkow** [comment]
> @mkow From what I understand, using Jinja-style comments in our manifest files will lead to the same issue: comments will disappear from the final rendered manifest.

The difference is that you won't be able to emit such comments if we go with skipping `#` on Jinja level. And all of this is for a weird case where a user confused the language they write in...

**Comment by mkow** [comment]
So, what shall we do with this one? I'd just close it, I think it works as expected and the upcoming signing tooling changes will make it even clearer (the manifests will end with `.toml.jinja` instead of `.manifest`).

**Comment by dimakuv** [comment]
Ok, let's just close it.
