### ISSUE TITLE
How many times does the graphene do remote attestation when the programe is multithreading like ppml ？

### ISSUE THREAD

**Issue by yanzhichao** [oscarlab/graphene#2583]
## Description of the problem
we try to count the times of getting  the wrap-key from provision-server when the programe configes the protectfile.  we want use the times for billing.  

We can't figure out the logic to get wrap key, It doesn't seem that programe only get  key one time when start.  For example ppml will get key three time from provision-server ,it means will do three times retmote attestation.

I kown when a programe is multithreading , it willl create multi enclave.  Does it mean every enclave will do one time remote attesstation and get the wrap-key from provision-server ?  So the ppml occurs three times attestation.

Could you give me some help ?

**Comment by dimakuv** [comment]
> We can't figure out the logic to get wrap key, It doesn't seem that programe only get key one time when start. For example ppml will get key three time from provision-server ,it means will do three times retmote attestation.

Are you referring to our PPML example [(this tutorial](https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html))? The key is provisioned only once in that example. How do you know / why do you think that it is provisioned three times?

> I kown when a programe is multithreading , it willl create multi enclave.

Multi-threaded programs create only *one* enclave, not multiple enclaves. *Multi-process* programs will create multiple enclaves.

> Does it mean every enclave will do one time remote attesstation and get the wrap-key from provision-server ? So the ppml occurs three times attestation.

It very much depends on what you're trying to do. Are you using the Secret Provisioning service from Graphene? I mean this one: https://graphene.readthedocs.io/en/latest/attestation.html#high-level-secret-provisioning-interface

If yes, then you're most probably using the `loader.env.LD_PRELOAD = "libsecret_prov_attest.so"` pattern (https://github.com/oscarlab/graphene/blob/0f286951f01c0768224837af683e7ed513aa33e3/Examples/ra-tls-secret-prov/secret_prov_pf_client.manifest.template#L8). This pattern works best for single-process applications. You may be right that if you have a multi-process application, then each new process in your application loads `libsecret_prov_attest.so` and connects to the secret provisioning server and receives a new copy of the same key. I will need to investigate this scenario. Your insights and steps to reproduce would be very helpful.

**Comment by yanzhichao** [comment]
Yes, I referring to your PPML example ,but I change some code as following,  I unzip the data.zip which include the input.jpg,class.txt and alexnet-pretrained.pt to the protect directory of "/workplace/encryptedData"
```
#for convenient we fix the path of encrypted data,and all the data in the zip file
#you should unzip file to /workplace/encryptedData first as follow.Then you can use
#the data normally in your code
unzip_file("/workplace/encryptedData/data.zip", "/workplace/encryptedData")


# Load the model from a file
alexnet = torch.load("/workplace/encryptedData/alexnet-pretrained.pt")

# Prepare a transform to get the input image into a format (e.g., x,y dimensions) the classifier
# expects.
from torchvision import transforms
```
and also I use your  Secret Provisioning service from Graphene.

I find the times in the secret-provisioning service's logs . when run ppml ,it seems will do three times remote-attesttion. I find three times duplication log.

as you said ,ppml is a multithreading program?  and will not create new enclave. but why in the debug log of running ppml I will see this two times, it seems create new enclave :
```
debug: enclave initializing:
debug:     enclave id:   0x0000000x
debug:     mr_enclave:   65c7dadb71497009xxxx7ad84a414x9a2a40979f8d6a2
debug: Using SGX DCAP/ECDSA attestation
debug: Key exchange succeeded: 87a7911334afe01ee57ac0xxx5672xxx356d4eb452x02b
debug: Enclave identifier: 6fb6742376368e9a -> 4a1516412227d54f90ba1a8a10793c38
debug: Received local report (mr_enclave = 65c7dadb714xxabb2664f9f7ad84a414x2a40979f8d6a2)
debug: Get report key for verification: 5676d74babd5319xx87xxa002
debug: Verify report:
debug:   cpu_svn:     11110206ff80060xxxx00000000000000
debug:   mr_enclave:  65c7dadb71xbb2664f9fxxx4dd5d4624fc9a2x9f8d6a2
debug:   mr_signer:   b78090f8e07bc84d6d85x27381fbxxxce7759212163004c9b947a9
debug:   attr.flags:  0000000xx0007
debug:   attr.xfrm:   0000xxxf
debug:   isv_prod_id: 00
debug:   isv_svn:     00
debug:   report_data: 00000000000000001c448499821a8f8b3a84a39c252d06cfa618ad0d19a7dd850000000000000000000000000000000000000000000000000000000000000000
debug:   key_id:      b86d64cxx41xx44c79c00000000000000000000000000000000
debug:   mac:         2b83ee602fe8xx2d1dfxxx
debug:   verify:     2b83ee602fxxb714ac5e69847a
debug: Enclave identifier: 8b8f1a829984441c -> 3a84a39c252d06cfa618xx9a7dd85
debug: Local attestation succeeded!
debug:   cpu_svn:     11110206ff8006000000000000000000
debug:   mr_enclave:  65c7dadb71497009ae7xxxx9a2a40979f8d6a2
debug:   mr_signer:   b78090f8e07bc84d6d852863775xxb08d1adbce7759212163004c9b947a9
debug:   attr.flags:  0000000000000007
debug:   attr.xfrm:   00000xx00001f
debug:   isv_prod_id: 00
debug:   isv_svn:     00
debug:   report_data: 01000000000000009a8e36762374b66f4a151xxf90ba1a8xx800000xx000000000000000000000000000000000000000000000000000
```
by the way, If the programe is multithreading, How many times does the graphene do remote attestation ? Only once ?

**Comment by dimakuv** [comment]
> as you said ,ppml is a multithreading program? and will not create new enclave. but why in the debug log of running ppml I will see this two times, it seems create new enclave :

I see. Thanks for the logs! The PPML example is a *multi-process* program. Apparently, it creates 3 programs (one main, and two utilities: I think PyTorch spawns a `gcc` or `ld` processes to get some information from the OS). So each program talks to the Secret Provisioning Server at startup. This is wrong, thanks for noticing this, I'll fix it soon.

> by the way, If the programe is multithreading, How many times does the graphene do remote attestation ? Only once ?

Yes, if the program is multi-threaded (not multi-process), then Graphene performs remote attestation only once.

**Comment by yanzhichao** [comment]
So do you mean you would give some modification at the PPML application level?
Is it possible that we could introduce some modification at Graphene level to force ONLY ONE remote attetstaion per application, and the secret key could be transfered implicitely via (maybe) local attetstaion to other enclaves are launched later but belong to the same application?

**Comment by dimakuv** [comment]
> So do you mean you would give some modification at the PPML application level?

No, I will perform a modification at the Graphene level. Nothing will change in the PPML application.

> Is it possible that we could introduce some modification at Graphene level to force ONLY ONE remote attetstaion per application, and the secret key could be transfered implicitely via (maybe) local attetstaion to other enclaves that are launched later but belong to the same application?

This is actually exactly what's happening already in Graphene. The only problem is that the preloaded shared library (`libsecret_prov_attest.so`) runs several times, but this is unnecessary and doesn't really change anything in Graphene behavior (because Graphene already implicitly transfers the secret key to other enclaves, as you correctly deduced).

**Comment by yanzhichao** [comment]
That's cool ,  wait for your enhancement  !

**Comment by dimakuv** [comment]
@yanzhichao I created a PR that fixes your issue: https://github.com/oscarlab/graphene/pull/2586.
