### ISSUE TITLE
ERROR: C library 'graphene-lib' not found

### ISSUE THREAD

**Issue by adityapribadi3** [oscarlab/graphene#2591]
I get this error when installing graphene on AWS ec2
referring to this guide https://graphene.readthedocs.io/en/latest/quickstart.html

**Comment by mkow** [comment]
On which command exactly? Could you include console logs?

**Comment by adityapribadi3** [comment]
i have done some research, so this command "meson build --buildtype=release -Dsgx=enabled -Ddirect=enabled" cause the error if I change to this one "-Ddirect=disabled" it will work but when I want to run this "graphene-sgx helloworld" it gives me this error 
error: Cannot open device /dev/sgx/enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -2
any idea about his error?

thank you

**Comment by mkow** [comment]
Have you done what the error says? :) ("Please make sure the Intel SGX kernel module is loaded.")
Does this file exist? If so, what's its ownership/perms?

**Comment by monavij** [comment]
>>I get this error when installing graphene on AWS ec2
Did you get an SGX enabled VM on AWS? As far as I know AWS does not support SGX .

**Comment by adityapribadi3** [comment]
I'm not sure, that's why I'm trying. Can we run graphene from the virtual box running ubuntu vm? @monavij

**Comment by monavij** [comment]
No - hardware has to support it and VMM needs to expose it to the VM. You should try and get an SGX enabled VM from Azure or ali cloud.

**Comment by mkow** [comment]
@adityapribadi3: Try running https://graphene.readthedocs.io/en/latest/manpages/is_sgx_available.html on that server.
Anyways, this is definitely not a problem in Graphene, so I'm closing the issue. Feel free to continue the discussion though.

**Comment by adityapribadi3** [comment]
@mkow sorry im new in this things, so I have come to this "~/graphene/Pal/src/host/Linux-SGX/tools/is-sgx-available" and "make" after that it shows me "g++ -O2 -std=c++14 -DNDEBUG -Wall -Wextra -Wno-multichar -masm=intel is_sgx_available.cpp -o is_sgx_available"

how can i call the is_sgx_available ?

**Comment by dimakuv** [comment]
@adityapribadi3 You built the `is_sgx_available` executable with this Make command. Now you can run it with `./is_sgx_available`.

To be honest, you should educate yourself in Linux. It seems that you don't understand what you're doing...

**Comment by adityapribadi3** [comment]
@dimakuv thank you for your advise
