### ISSUE TITLE
Graphene-SGX: Redis Example is failing without sgx.nonpie_binary = true for CentOS

### ISSUE THREAD

**Issue by anjalirai-intel** [oscarlab/graphene#2598]
## Description of the problem
Redis server is not started without` sgx.nonpie_binary = true` for SGX in CentOS
It started failing after this commit
https://github.com/oscarlab/graphene/commit/b2a8eeecb5e109c81badac17ee9b59fa99b31c8e

## Steps to reproduce
cd Examples/redis
make SGX=1 start-graphene-server & ../../Scripts/wait_for_server 5 127.0.0.1 6379
./src/src/redis-benchmark

## Expected results (Small portion)
**make SGX=1 start-graphene-server & ../../Scripts/wait_for_server 60 127.0.0.1 6379**
```
graphene-sgx redis-server --save '' --protected-mode no
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
1:C 30 Jul 2021 06:14:32.439 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 30 Jul 2021 06:14:32.439 # Redis version=6.0.5, bits=64, commit=6ab5a190, modified=1, pid=1, just started
1:C 30 Jul 2021 06:14:32.439 # Configuration loaded
1:M 30 Jul 2021 06:14:32.440 * Increased maximum number of open files to 10032 (it was originally set to 900).
1:M 30 Jul 2021 06:14:32.440 * Running mode=standalone, port=6379.
1:M 30 Jul 2021 06:14:32.440 # Server initialized
1:M 30 Jul 2021 06:14:32.482 * Ready to accept connections
```

 **./src/src/redis-benchmark**
```
====== PING_INLINE ======
  100000 requests completed in 2.65 seconds
  50 parallel clients
  3 bytes payload
  keep alive: 1
  host configuration "save":
  host configuration "appendonly": no
  multi-thread: no

0.00% <= 0.4 milliseconds
0.00% <= 0.5 milliseconds
0.01% <= 0.6 milliseconds
0.04% <= 0.7 milliseconds
0.06% <= 0.8 milliseconds
0.10% <= 0.9 milliseconds
0.31% <= 1.0 milliseconds
0.63% <= 1.1 milliseconds
7.76% <= 1.2 milliseconds
27.06% <= 1.3 milliseconds
98.48% <= 1.4 milliseconds
99.51% <= 1.5 milliseconds
99.63% <= 1.6 milliseconds
99.69% <= 1.7 milliseconds
99.69% <= 1.8 milliseconds
99.71% <= 1.9 milliseconds
99.74% <= 2 milliseconds
99.95% <= 10 milliseconds
99.99% <= 11 milliseconds
100.00% <= 11 milliseconds
37764.35 requests per second
```

## Actual results
 **make SGX=1 start-graphene-server & ../../Scripts/wait_for_server 5 127.0.0.1 6379**
`graphene-sgx redis-server --save '' --protected-mode no`

**./src/src/redis-benchmark**
```
Could not connect to Redis at 127.0.0.1:6379: Connection refused
ERROR: failed to fetch CONFIG from 127.0.0.1:6379
WARN: could not fetch server CONFIG
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
Writing to socket: Connection refused
All clients disconnected... aborting.
```

[redis_log_level_all.log](https://github.com/oscarlab/graphene/files/6906378/redis_log_level_all.log)

**Comment by dimakuv** [comment]
In the actual results, there is no error log for `graphene-sgx redis-server ...`. How is this? There is nothing that Redis prints? What about `loader.log_level = "all"`?

**Comment by anjalirx-intel** [comment]
Logs attached for " `make SGX=1 start-graphene-server & ../../Scripts/wait_for_server 60 127.0.0.1 6379`" with log_level as all

**Comment by dimakuv** [comment]
Wow. Weird.

Can you do 
```
cd graphene/Examples/redis
readelf -h redis-server
```

And paste the output

**Comment by jinengandhi-intel** [comment]
[intel1@localhost redis]$ readelf -h redis-server
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x42b170
  Start of program headers:          64 (bytes into file)
  Start of section headers:          11211456 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         10
  Size of section headers:           64 (bytes)
  Number of section headers:         39
  Section header string table index: 38

**Comment by dimakuv** [comment]
Thanks. As suspected, Redis is built as a non-PIE executable on CentOS. You can notice this by `EXEC` type and by the entry point address `0x42b170` (approx 4MB). So that's why without `sgx.nonpie_binary = true`, Redis fails.

Just for comparison, here's how Redis executable looks like on Ubuntu:
```
~/graphene/Examples/redis$ readelf -h redis-server
ELF Header:
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Entry point address:               0x3a610
```

I left the irrelevant fields out. You can see that Redis on Ubuntu is `DYN` (PIE executable, or shared object), and that its entry point address is some rather meaningless `0x3a610` (233KB).

Anyway, let me re-add `sgx.nonpie_binary = true` into the Redis example in a simple PR. I think this deserves to be added to our Redis manifest, since it doesn't hurt and makes CentOS (and probably also Fedora/RHEL) work seamlessly.

**Comment by dimakuv** [comment]
#2610 should fix this isse.
