### ISSUE TITLE
Numpy is failing with memory fault at 0x00000000 for CentOS in SGX

### ISSUE THREAD

**Issue by anjalirx-intel** [oscarlab/graphene#2599]
## Description of the problem
Numpy & Scipy Python Examples are failing with memory fault issue in CentOS

## Steps to reproduce
Comment the dist-packages mounting in python.manifest.template and /etc/default/apport line as well
make SGX=1 all
graphene-sgx ./python scripts/test-numpy.py

## Expected results
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
numpy version: 1.14.3
numpy.dot: 0.008692550659179687 sec

## Actual results
Trace logs attached
[numpy_trace.log](https://github.com/oscarlab/graphene/files/6905838/numpy_trace.log)

**Comment by anjalirx-intel** [comment]
The workload is failing in RHEL as well

**Comment by dimakuv** [comment]
I see this in the log:
```
[P1:T3:platform-python3.6] trace: ---- shim_mmap(0x0, 0x8000000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0x0) ...
[P1:T3:platform-python3.6] trace: ---- return from shim_mmap(...) = -12
```

This looks like NumPy/SciPy tries to allocate 128MB of memory per thread. And at some point the default enclave size https://github.com/oscarlab/graphene/blob/13b8be69f77315f34f49a31967f352c3e9225384/Examples/python/python.manifest.template#L42

is not sufficient.

This looks like a feature of CentOS/RHEL/Fedora-based distributions of NumPy/SciPy. I think by increasing the enclave size, your workload will start working again. Try something like `sgx.enclave_size = "4G"` and check if you still have `mmap = -12` in the log. If you do, increase the size even more.

**Comment by anjalirx-intel** [comment]
I increased the enclave size to 4G like you said and it worked.

**Result:**
[intel1@localhost python]$ graphene-sgx ./python scripts/test-numpy.py
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
numpy version: 1.14.3
numpy.dot: 0.44974699020385744 sec

Closing the issue
