### ISSUE TITLE
[GSC] Update GSC to follow the new build improvements

### ISSUE THREAD

**Issue by aneessahib** [oscarlab/graphene#2615]
GSC is currently pointed to an older version of graphene prior to the build changes.  Updates have to be made to the GSC config file and scripts to point to master.

**Comment by veenasai2** [comment]
Please assign to me.

**Comment by veenasai2** [comment]
This issue is resolved now and changes are merged to graphene master. 
Git commit id: 7059cd44a4ff9268160f15cac7441d1018452eab.
