### ISSUE TITLE
Updating Graphene to the latest version

### ISSUE THREAD

**Issue by chicolinux** [oscarlab/graphene#2616]
## Description of the problem
Hello, I already have a working version of Graphene, but this about 4 months old, so I want to update my installation to the latest one, RC1.2, How to go about it? Erase the cloned repository and clone it again?? Any ideas or recommendations?

**Comment by dimakuv** [comment]
I would erase the cloned repository, clone the new one, checkout the RC1.2 tag, and build + install again. Something like this:
```
rm -rf <cloned repo>
git clone https://github.com/oscarlab/graphene.git
git checkout v1.2-rc1
<build and install according to https://graphene.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support>
```

**Comment by dimakuv** [comment]
Since this is not a real bug/suggestion to Graphene, I'm closing this issue. If there are more questions on the build procedure, feel free to reopen the ticket.
