### ISSUE TITLE
Accessing file is denied in GrapheneSGX, even though it's specified as allowed in Manifest

### ISSUE THREAD

**Issue by VogtIndustries** [oscarlab/graphene#2622]
I am trying to run a program of mine in GrapheneSGX, but I'm encountering a problem with file access. 

The program runs flawlessly in Graphene without SGX, but in GrapheneSGX it builds and runs, but I cannot access my output file "BaselineData.txt".
When running with debug-level logging, I receive the following error: 

'''Accessing file:BaselineData.txt is denied (Operation denied). This file is not trusted or allowed. Trusted files should be regular files (seekable).'''

This heavily confuses me, as I tried both allowing and trusting the file in the manifest, with none of them working. 

Below I have both the log output and my manifest file. I have already used file output in GrapheneSGX in another work and to the best of my knowledge have done everything the same way as last time. 

[ManifestTemplate.pdf](https://github.com/oscarlab/graphene/files/6938780/ManifestTemplate.pdf)

<img width="1246" alt="GrapheneDebugLog" src="https://user-images.githubusercontent.com/55499303/128355192-30f9c5d0-c056-4dd6-9b59-df6d926fed7b.png">

The file BaselineData.txt exists, can be opened and written in Graphene without SGX. This is my directory, which contains the program. The program runs with two threads. 
<img width="289" alt="FolderScreenshot" src="https://user-images.githubusercontent.com/55499303/128355471-1e82a4a1-ed88-441a-90c8-4bceb9fa555f.png">

**Comment by dimakuv** [comment]
> This heavily confuses me, as I tried both allowing and trusting the file in the manifest, with none of them working.

Can you show the relevant snippet from your manifest file?

**Comment by VogtIndustries** [comment]
I have appended the whole Manifest File as Manifest.pdf on my post, but below is my whole SGX related Manifest part :)


############################### SGX: GENERAL ################################
sgx.enclave_size = "256M" 
sgx.debug = true 
sgx.nonpie_binary = true 
sgx.thread_num = 16
############################# SGX: TRUSTED FILES #############################
sgx.trusted_files.runtime = "file:{{ graphene.runtimedir() }}/" 
sgx.trusted_files.arch_libdir = "file:{{ arch_libdir }}/" 
sgx.trusted_files.usr_arch_libdir = "file:/usr/{{ arch_libdir }}/"
sgx.trusted_files.GrapheneBench = "file:{{ baseline_dir }}/GrapheneBench" 
sgx.trusted_files.tests = "file:{{ baseline_dir }}/tests" 
sgx.trusted_files.baseline = "file:{{ baseline_dir }}"
#sgx.trusted_files.Baselinedata = "file:{{ baseline_dir }}/BaselineData.txt"
############################# SGX: ALLOWED FILES ############################ sgx.allowed_files.BaselineData = "file:{{ baseline_dir }}/BaselineData.txt"

**Comment by dimakuv** [comment]
There is a "bug" in Graphene. You cannot do this:
```
sgx.allowed_files.BaselineData = "file:{{ baseline_dir }}/BaselineData.txt"
```

when your application opens the file like this: `file:BaselineData.txt`.

Even though the underlying path is the same, but your manifest contains the **absolute path** and the application opens the **relative path**. Graphene currently doesn't understand that these two ways of specifying a file path are the same.

So the fix is simple:
```
sgx.allowed_files.BaselineData = "file:BaselineData.txt"  # use relative path!
```

(Same for your `sgx.trusted_files` attempt.)

**Comment by VogtIndustries** [comment]
Ohh I see, thank you very much!!! 👍🏼 
This solved my issue and everything works as expected now :) 
Also thank you for the extremely quick replies!
