### ISSUE TITLE
PPML example with SGX Error

### ISSUE THREAD

**Issue by adityapribadi3** [oscarlab/graphene#2630]
Hi so I follow this guide 
https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html#executing-pytorch-with-graphene-in-sgx-enclave
I have successfully run "make SGX=1" however when I run "graphene-sgx ./pytorch pytorchexample.py"
it throws me this error

error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
  File "pytorchexample.py", line 47, in <module>
    with open("result.txt", "w") as outfile:
FileExistsError: [Errno 17] File exists: 'result.txt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 35, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the CPU table

Original exception was:
Traceback (most recent call last):
  File "pytorchexample.py", line 47, in <module>
    with open("result.txt", "w") as outfile:
FileExistsError: [Errno 17] File exists: 'result.txt'

I have tried to "make clean" run remake the file and also remove the "result.txt" and run again but still, it shows me the same error. I have test with he hello world test using SGX and it works fine

**Comment by dimakuv** [comment]
Strange, the file should have been overwritten, but Python says that it can't overwrite it...

Does anyone from the Graphene team have time to look into this?

**Comment by mkow** [comment]
@adityapribadi3 please use proper Markdown formatting for issues, the current version is unreadable.

**Comment by adityapribadi3** [comment]
<img width="1280" alt="Screen Shot 2021-08-07 at 1 12 03 am" src="https://user-images.githubusercontent.com/22907832/128532276-fea6a417-a58e-49dd-9a87-144996ef4e6e.png">

**Comment by mkow** [comment]
@adityapribadi3: Sorry for being a bit rude, but have you actually read my comment...?

**Comment by adityapribadi3** [comment]
sorry, I didn't get it you want me to use the template if I want to report the issue or do you want me to resend the error again from the terminal?

**Comment by adityapribadi3** [comment]
## Description of the problem

PPML example with SGX Error when executing

## Steps to reproduce

This guide
https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html#executing-pytorch-with-graphene-in-sgx-enclave
I have successfully run "make SGX=1" however when I run "graphene-sgx ./pytorch pytorchexample.py"

## Expected results
result.txt
## Actual results
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
/home/ubuntu/.local/lib/python3.6/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1156.)
return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):
File "pytorchexample.py", line 47, in
with open("result.txt", "w") as outfile:
FileExistsError: [Errno 17] File exists: 'result.txt'
Error in sys.excepthook:
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
from apport.fileutils import likely_packaged, get_recent_crashes
File "/usr/lib/python3/dist-packages/apport/init.py", line 5, in
from apport.report import Report
File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in
import apport.fileutils
File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in
from apport.packaging_impl import impl as packaging
File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in
import apt
File "/usr/lib/python3/dist-packages/apt/init.py", line 35, in
apt_pkg.init_system()
apt_pkg.Error: E:Error reading the CPU table

Original exception was:
Traceback (most recent call last):
File "pytorchexample.py", line 47, in
with open("result.txt", "w") as outfile:
FileExistsError: [Errno 17] File exists: 'result.txt'


<!-- ## Additional information -->
<!-- if applicable, uncomment and fill this section -->

**Comment by adityapribadi3** [comment]
Hi @mkow, for the update this error already resolve by changing the script in "pytorchexample.py" when importing the torchvision to "import torchvision.models as models" However now when I run "sudo graphene-sgx ./pytorch pytorchexample.py" I have a different error

ubuntu@VM2:~/graphene/Examples/pytorch$ sudo graphene-sgx ./pytorch pytorchexample.py
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
./pytorch: can't open file 'pytorchexample.py': [Errno 13] Permission denied

**Comment by sahason** [comment]
@mkow PR #2655 seems to address this as well. Please assign it to me.

**Comment by adityapribadi3** [comment]
Hi @sahason , is it already fixed?

**Comment by sahason** [comment]
@adityapribadi3 Yes, please check with this PR #2655.

**Comment by adityapribadi3** [comment]
hi sahason, I have try to change the code in "pytorch.manifest.template" and it works but the problem is the example get killed in my machine, I'm using azure DC VM with 16gb RAM, if there a way to limit the RAM so the application is not killed?
'''
ubuntu@VM3:~/graphene/Examples/pytorch$ sudo graphene-sgx ./pytorch ./pytorchexample.py
Killed
'''

**Comment by sahason** [comment]
@adityapribadi3  I am sure about any such mechanism. @mkow Can you please comment here? 
One suggestion here is to increase the size of RAM/EPC.

**Comment by adityapribadi3** [comment]
I'm using Azure VM with 32Gb RAM and still the process get killed

**Comment by mkow** [comment]
Does this workload really need 16GB of memory?

I guess the reason you get OOM-ed is that PyTorch is spawning some children, each of which also taking 16GB. And you probably don't have any swap mounted (or just a small one), so the OOM killer kills you right after you cross the 16/32 GB boundary.

**Comment by adityapribadi3** [comment]
oh ok then thx, so the only way is upgrading the RAM right?
