### ISSUE TITLE
execve for a zero length file with executable permission failing with EINVAL instead of ENOEXEC 

### ISSUE THREAD

**Issue by aniket-intelx** [oscarlab/graphene#2639]
## Description of the problem
execve03: This testfile checks for execve syscall for different errors like ENAMETOLONG, ENOENT, ENOTDIR, EFAULT, EACCESS and ENOEXEC.

**Failed TC**: 
6. {test_name6, ENOEXEC}
This testcase creates a file which is of zero length and has execute permissions, so this testcase should result in ENOEXEC error.

This testcase was working fine before this commit https://github.com/oscarlab/graphene/commit/b9e151748d66be80d1e20cfa0513fc44f1cbe85b and started failing in recent builds.

## Steps to reproduce
Run LTP test execve03

## Expected results
```
graphene-direct execve03
TINFO: Timeout per run is 0h 05m 00s
TPASS: execve failed as expected: ENAMETOOLONG (36)
TPASS: execve failed as expected: ENOENT (2)
TPASS: execve failed as expected: ENOTDIR (20)
TPASS: execve failed as expected: EFAULT (14)
TPASS: execve failed as expected: EACCES (13)
TPASS: execve failed as expected: ENOEXEC (8)

Summary:
passed   0
failed   0
skipped  0
warnings 0

```
## Actual results (Filename "execve03_try" has been modified in this log which is not required)
```
graphene-direct execve03
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
[P1:T1:] error: Mounting file:/proc may expose unsanitized, unsafe files to unsuspecting application. Graphene will continue application execution, but this configuration is not recommended for use in production!
TINFO: Timeout per run is 0h 05m 00s
TPASS: execve failed as expected: ENAMETOOLONG (36)
TPASS: execve failed as expected: ENOENT (2)
TPASS: execve failed as expected: ENOTDIR (20)
TPASS: execve failed as expected: EFAULT (14)
TPASS: execve failed as expected: EACCES (13)
[P2:T2:execve03] error: Failed to read ELF header from /tmp/execve03_try
TFAIL: execve failed unexpectedly; expected Exec format error: EINVAL (22)

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

Trace logs has been attached.
[execve03_tracelogs.txt](https://github.com/oscarlab/graphene/files/6960718/execve03_tracelogs.txt)

**Comment by mkow** [comment]
Please check if #2640 fixes the problem for you.

**Comment by aniket-intelx** [comment]
I am getting the expected results for the above mentioned PR #2640. Thanks.
