### ISSUE TITLE
Pal/test is outdated

### ISSUE THREAD

**Issue by woachk** [oscarlab/graphene#264]
Hi,

This test was done on Ubuntu 14.04 to be near the true conditions for which Graphene was designed for in the first place.
In Pal/test, the HandleSend, Fork, Ipc (even with gipc actually enabled) tests will always fail.

`root@graphene:/graphene/Pal/test# ./pal_loader ./HandleSend`
`Parent: Executing the program`
`Parent: Creating handles`
`Parent: DKStreamWrite failed`
`root@graphene:/graphene/Pal/test# ./pal_loader ./Fork`      
`Enter Main Thread`
`nothing happens here even after a while^CSegmentation fault (core dumped)`
`root@graphene:/graphene/Pal/test# ./pal_loader ./Ipc` 
`mem = 0x7ff7a2da7000`
`(child) StreamOpen Failed`
`Failed to get exit signal from child, 0`
`root@graphene:/graphene/Pal/test# ls -l /dev/gipc`
`crw-rw-rw-. 1 root root 10, 240 Oct 21 18:26 /dev/gipc`
`root@graphene:/graphene/Pal/test# `

Host kernel is Linux 4.19-rc8 with Docker and /dev/gipc passed through.

**Comment by mkow** [comment]
This was fixed by #1397.
