### ISSUE TITLE
Pal/regression uses some outside functions

### ISSUE THREAD

**Issue by woachk** [oscarlab/graphene#265]
memset() and such are used in some Pal/regression tests, that as such aren't 100% representative of the PAL and cannot even run properly on some host OSes that do not have them, resulting in a crash at runtime because of a nondefined symbol.

**Comment by mkow** [comment]
I verified that Pal/regression tests use our own `memset` implementation (from `Pal/lib/string/memset.c`). Please reopen with a reproduction steps included if you still see this problem.
