### ISSUE TITLE
[Examples] Python Example Stuck Without Any Error Message

### ISSUE THREAD

**Issue by KeplerC** [oscarlab/graphene#2693]
## Description of the problem

I just installed graphene and `make` the manifest by the document. The installation and manifest compilation do not report any error message. However, as I ran `graphene-direct ./pytorch pytorchexample.py`, and the program stuck indefinitely. This occurs for both vanilla python and pytorch example. 

```
(base)  $ graphene-direct ./pytorch pytorchexample.py
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
error: Forwarding host environment variables to the app is enabled. Graphene will continue application execution, but this configuration must not be used in production!
[P2325784944::] debug: Host: Linux
[P2325784944::] debug: LibOS xsave_enabled 1, xsave_size 0x440(1088), xsave_features 0x1f
```

## Steps to reproduce

After installing the graphene, 
```bash
cd Examples/pytorch
DEBUG=1 make
graphene-direct ./pytorch pytorchexample.py
```

## Expected results
result.txt

## Actual results
The program stuck there indefinitely.

**Comment by mkow** [comment]
This repository is not used anymore, please use https://github.com/gramineproject/gramine.
