### ISSUE TITLE
Issue in Cloud Deployment to AKS

### ISSUE THREAD

**Issue by saruvig** [oscarlab/graphene#2698]
Hi,

I am following the steps given in https://graphene.readthedocs.io/en/latest/cloud-deployment.html#prerequisites for deploying the Hello World application to AKS. 

I am getting an error at the ./gsc build step: Failed to build unsigned graphenized docker image `gsc-python-unsigned`.

It stops running at Step 1/19: FROM gsc-graphenelibos/aks:latest AS graphene

The Azure VM has the following features: Linux (ubuntu 21.04), Standard DC2s v2 (2 vcpus, 8 GiB memory)

**Comment by dimakuv** [comment]
Please note that Graphene was renamed to Gramine, and all repositories and documentation moved to new places:
- https://github.com/gramineproject/gramine -- main Gramine repo
- https://gramine.readthedocs.io/en/latest/cloud-deployment.html -- documentation on Cloud Deployment

**Comment by dimakuv** [comment]
So please check there (actually, wait until tomorrow since we'll update the Cloud Deployment page -- it had some small bugs)

**Comment by mkow** [comment]
Closing this, as we're no longer using this repository.
