### ISSUE TITLE
memcached multi-threading

### ISSUE THREAD

**Issue by shmeni** [oscarlab/graphene#27]
Hey,
I got the following problem trying to run memcached in graphene-sgx.
I'm running Ubuntu 14.04, with SGX-enabled HW (I'm able to run native enclaves)

[memcached.manifest.tar.gz](https://github.com/oscarlab/graphene/files/661096/memcached.manifest.tar.gz)

I tried running memcached with the attached manifest file after signing it.

Memcached runs correctly with the following command line:
./memcached.manifest.sgx -u user -l 132.68.52.219 -p 9000 -c 1024 -t 2 -U 0 -m 256 -C

Increasing memcached to support more threads, e.g. the following command line results in the application getting stuck.
./memcached.manifest.sgx -u user -l 132.68.52.219 -p 9000 -c 1024 -t 2 -U 0 -m 256 -C

Using the inline debug_type of the loader suggests that it stuck after poll, though I'm not sure I read it correctly.

**Comment by sjtugjy** [comment]
It seems that the two commands are the same.
Besides, could you teach me how to compile memcached with graphene-sgx?

**Comment by chiache** [comment]
memcached should work in the latest version. Please make sure to update the SDK version, and only run with "-u root".
