### ISSUE TITLE
pytorch sample config for better performance

### ISSUE THREAD

**Issue by salsal97** [oscarlab/graphene#2700]
## Description of the problem
Hi, 

I'm trying to run the pytorch example in this repo and its taking ~45 seconds to run completely right now, with a decreased enclave size of 4GB. This was the optimum state I could reach, and not even the openMP patch would decrease the runtime further. 
- Is there any way to make this example faster?
- Is there any change required in the current environment for the openMP patch to actually show the performance difference? 

## Steps to reproduce

Running Examples/pytorch as specified in the readme
- change the enclave size in the manifest template to 4G

## Expected results
NA
## Actual results
NA

**Comment by dimakuv** [comment]
First, you should use the new Gramine repo: https://github.com/gramineproject/gramine (Graphene was renamed to Gramine and moved under a new GitHub org). This "Graphene" repo is outdated.

Second, what is your machine? How much EPC does it have? If you have an older, wimpy SGX-enabled machine with only 96MB - 128MB of EPC, you will see pretty bad performance on big workloads like PyTorch. Please also read through this: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#enclave-size and this: https://gramine.readthedocs.io/en/latest/devel/performance.html#choice-of-sgx-machine

**Comment by salsal97** [comment]
@dimakuv 
Hi, I used graphene since gramine does not have a pytorch sample as of yet. I'm using an Icelake machine, with 24 cores - 

```
$ is-sgx-available 
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x200000000
SGX driver loaded: true
AESMD installed: true
SGX PSW/libsgx installed: true
```
