### ISSUE TITLE
redis-benchmark hangs in epoll_wait()

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#276]
redis-benchmark on Graphene-SGX hangs in a call to epoll_wait().

Specifically, the application monitors a socket fd for EPOLLOUT and EPOLLIN. However, the PAL logic for [epoll_wait()](https://github.com/oscarlab/graphene/blob/f07dfd052f476912617de74a0835f83d63f309eb/Pal/src/host/Linux-SGX/db_object.c#L165) decides to only add EPOLLOUT to the underlying poll() call if the corresponding PAL_HANDLE's WRITEABLE flag is unset. What is the logic behind this?

The application wants to do a write next, but since we are only polling for read availability on the socket, the application is stuck in the poll() call. Is the WRITEABLE test needed for correctness? Is it an optimization, i.e., only wait for writability if we don't already know the PAL_HANDLE/fd to be writeable?

Adding EPOLLOUT regardless of the WRITEABLE bit solves the problem with redis-benchmark. Will this break other things though?

The attached sample illustrates the issue. It runs fine on Linux, but hangs on  @Graphene(-SGX).
[main.c.txt](https://github.com/oscarlab/graphene/files/2540519/main.c.txt)

Thanks @dimakuv for helping with this!

**Comment by donporter** [comment]
There are a few pending PRs on this issue, including #197.  I'm guessing these are distinct issues?

**Comment by thomasknauth** [comment]
No, actually this is the exact same issue. I am closing this, since it is already being tracked. Maybe the test case is useful for regression testing.
