### ISSUE TITLE
LTP testcase alarm03, alarm05, alarm06

### ISSUE THREAD

**Issue by arjun4084346** [oscarlab/graphene#30]
Fixed in branch abora-local
File changed : shim_async.c

1) System call alarm is supposed to return number of seconds remaining in any previously set alarm.
It was returning 0 all the time. Code to calculate correct return value merged in branch abora-local
2) System call alarm is supposed to cancel any pending alarm. Code to cancel any pending alarm merged in branch abora-local

**Comment by mkow** [comment]
Outdated, closing.
