### ISSUE TITLE
Remove or update modelines in source files?

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#304]
When the project started, we used a lot of Emacs and Vim modelines. Here is an example:
 
```
/* -*- mode:c; c-file-style:"k&r"; c-basic-offset: 4; tab-width:4; indent-tabs-mode:nil; mode:auto-fill; fill-column:78; -*- */
/* vim: set ts=4 sw=4 et tw=78 fo=cqt wm=0: */
```

I personally like them because they are convenient for per-project settings, but I don't know how other people feel about them. I assume with the new coding style guideline, we need to either update them or remove them once for all. Do we consider them too annoying? Maybe move them to something like a `.vimrc` file?

Suggestions are welcome.

**Comment by yamahata** [comment]
Personally I don't care much. (I'm using emacs)
If mode line is included, that's okay.
If not, I'll just update auto-mode-alist in my .emacs.el.

**Comment by mkow** [comment]
I don't like them ;) IMO they may be annoying for users of other editors (like me). I'd prefer to specify recommended configs for various editors in some .md file and link it in the README.md.

**Comment by dimakuv** [comment]
Removing modelines is fine with me.
