### ISSUE TITLE
How to write an SGX application with graphene? 

### ISSUE THREAD

**Issue by sjtugjy** [oscarlab/graphene#32]
Does graphene support unmodified applications? The Helloworld example needs to invoke the function provided by graphene instead of the original functions from libc.

**Comment by chiache** [comment]
It does. The helloworld example (in `LibOS/test/native`) is an ordinary Linux binary, and can be directly run (without Graphene) by the command `./helloworld`.

**Comment by sjtugjy** [comment]
How to write the manifest for any application? For example, I have statically compiled the Memcached. How to know the SIGSTRUCT of it? Is there any guide to write the manifest for SGX applications? Thanks in advance!

**Comment by donporter** [comment]
https://github.com/oscarlab/graphene/wiki/SGX-Manifest-Syntax

Writing a manifest can be a little tricky, but usually just pattern-matching on another manifest is sufficient.  

Is there a more specific problem you are having that we can help with?

Also, static compilation may not work; you really need to be able to dynamically link to get Graphene to work on SGX.

**Comment by donporter** [comment]
Regarding sigstruct, you need to do something like this:

<path to graphene>/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal <path to graphene>/Pal/src/host/Linux-SGX/../../libpal-enclave.so -key <graphene>/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output app.manifest.sgx -exec path/to/app/bin -manifest app.manifest

**Comment by sjtugjy** [comment]
The multithread bug does not occur for every time.
I have just successfully run the Memcached with the Pal.
I am curious about the implementation of multithread enclave. If I specify that sgx.thread_num is N, it will add N TCS for the enclave and assign a TCS for each thread? Or, there is a user mode scheduler in the enclave's libOS.

**Comment by donporter** [comment]
Hi!  There were recently a number of fixes posted that dealt with memcached specifically.

Does the latest version address these problems, or are you still having issues?
