### ISSUE TITLE
Deallocation of the initial stack

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#334]
In our PALs, each thread is given a 4KB or 8KB stack to start with. The stack is likely to be abandoned when the library OS takes over. Unfortunately, freeing this stack is somewhat tricky, because we can't anticipate what's the right timing for deallocation. In #281, we unmap the thread stack as the last statement before calling `exit()`. However, this implementation in fragile because the compiler may still use the stack after unmapping.

Another solution is to deallocate the stack when closing the thread handle, assuming the library OS will only close the handle after the thread has terminated. However, this assumption is a little problematic, as there are situations as pointed out by #322.

**Comment by mkow** [comment]
I vote for either:
* Deallocation after closing the handle (as @chiache suggested),
* or writing this fragile part of the code in assembly (which would guarantee that the stack isn't touched after deallocation). This should be easy, as we only need to issue 2 simple syscalls.

**Comment by yamahata** [comment]
For record, CLONE_THREAD case, thread area is leaked.
It's because wait system call isn't called. pthread_join only checks if tid is cleared and done.

**Comment by dimakuv** [comment]
This was fixed long ago in both PALs.

- Linux PAL re-uses the stacks left from the exited threads (so the memory leak is kinda there, but it is capped): https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/Pal/src/host/Linux/db_threading.c#L25

- Linux-SGX PAL frees the untrusted stack at thread exit: https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/Pal/src/host/Linux-SGX/sgx_thread.c#L222
