### ISSUE TITLE
epoll, poll, and select do not work with newly created sockets

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#365]
Due to the minimal PAL interface, which forces socket()+connect() or socket()+bind()+listen() into a single function (DkStreamOpen), Graphene cannot create a host socket descriptor at the application's call to socket(), but must rather wait until the application calls connect() or bind().

Some applications, such as nginx, implement a non-blocking connect by first calling socket(), then adding that descriptor to the epoll/poll/select list, and then calling connect() when these functions indicate that the descriptor is readable/writeable (which is trivially true, at least initialyl for the fd).

The problem is that, when adding such an fd via say, epoll_ctl(EPOLL_CTL_ADD), epoll_ctl will return EPERM, since a pal_hdl has not yet been associated with graphene's internal hdl for that descriptor.

It might be worth changing Graphene's implementation of epoll/poll/select to handle this special case.

**Comment by mkow** [comment]
@smherwig Could you post your change as a PR?

**Comment by smherwig** [comment]
Sure.  Allow me a day or two.

**Comment by dimakuv** [comment]
This was fixed long time ago by this commit: https://github.com/oscarlab/graphene/commit/4485f5af9883c4996137ab4c8ff1e7bb1a257bac
