### ISSUE TITLE
Bug in get_norm_path

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#38]
[This line](https://github.com/oscarlab/graphene/blob/master/Pal/lib/graphene/path.c#L57) causes get_norm_path to return an error when a component of a path starts with `..`.

Example:
```
cd LibOS/shim/test/native
./pal ls.manifest.sgx /lib/..foo
```
results in `file:/bin/ls: cannot access '/lib/..foo': Interrupted system call`.

I wonder why you rewrite a function like get_norm_path. IMO this is bound to cause bugs, possibly leading to vulnerabilities. Wouldn't it be better to reuse existing code for this, for example realpath from the glibc?

**Comment by donporter** [comment]
I see the point here.  At least one implementation we saw (musl) relied heavily on /proc and other features that some hosts may not have.  We are also considering moving to a more permissive license, so we probably want to avoid adding more GPL code for now.
