### ISSUE TITLE
Containerized execution of enclaves (e.g. docker)

### ISSUE THREAD

**Issue by shankari** [oscarlab/graphene#383]
Our use case involves the use of separate enclaves that are idle most of the time (https://github.com/e-mission/e-mission-docs/blob/master/docs/future_work/secure_execution_options.md). However, each instance of the enclave program has its own secret and needs to be independently executed. We would like to support this by running the enclave programs in containers (e.g. docker) that can be paused and resumed on demand.

This issue tracks the options that we have explored and the tradeoffs for each.

**Comment by shankari** [comment]
@njriasan has briefly looked at compiling graphene in a docker container. He had issues with linux kernel header versions during the compilation. Presumably this will go away when #127 is fixed, but we will need a workaround until that is fixed.

**Comment by shankari** [comment]
@mkow, can we help with the docker integration in any way?

**Comment by shankari** [comment]
Also, does your implementation include sealing/unsealing while pausing/unpausing docker containers?

**Comment by mkow** [comment]
@shankari Sure, we'd be glad to hear feedback and feature suggestions from you. We plan to start with a pull request (somewhen in January) and then we will discuss what should be changed and what is still missing.

Regarding pausing/unpausing containers: We never had a use-case for this so we haven't implemented such a feature. But sounds interesting and useful. Have you already done any work in this direction?
@chiache @donporter What do you think about such a feature?

**Comment by shankari** [comment]
@mkow we don't have the docker integration working yet, so hadn't moved on to pausing/unpausing :)
but there are clear sealing APIs defined, and apparently, the currently unmaintained [python-sgx](https://github.com/adombeck/python-sgx) had [sealing support](https://github.com/adombeck/python-sgx#test-sealing)
so we were going to take a look at that and see if we could at least port/maintain that part

@liurenju did you get to play around with python-sgx? what did you find wrt current status?

**Comment by liurenju** [comment]
@shankari Sorry. I've been crazily working on my project this past week. I'll update you no later than the end of this week.

**Comment by donporter** [comment]
If there is a use case for pausing/unpausing, it should be relatively easy to support.

**Comment by mkow** [comment]
There's a PR which adds Docker integration: https://github.com/oscarlab/graphene/pull/1345
I'm not sure about supporting freezing/unfreezing, you'll need to take a look by yourself at the PR ;)

Closing this issue. Feel free to reopen if you're still interested in discussing this feature.
