### ISSUE TITLE
Secure execution of interpreted programs

### ISSUE THREAD

**Issue by shankari** [oscarlab/graphene#384]
We expect that our enclaves will primarily run python code. While the pal loader will verify the executable and the dynamically loaded native libraries, that will verify that we are running python.

We also want it to:
- verify the python scripts (text files) that are loaded for execution
- ensure that the REPL and `$ python -i` are disabled, so that the syadmin doesn't just launch python and type out arbitrary code

The graphene paper includes an evaluation with `R`, so this must be a solved problem. We would just like some more details on how it works and how we can configure the execution accordingly.

**Comment by dimakuv** [comment]
1. "Verify the python scripts" -- you should white-list allowed python scripts in the Manifest using `sgx.trusted_files.[identifier]=[URI]`. For example, `sgx.trusted_files.python_script_01=scripts/hello_world.py` will generate a checksum for file `./scripts/hello_world.py`, and when this file is loaded inside the SGX enclave, its checksum will be verified against the pre-generated one. Attempts to load any other, non-white-listed files/scripts will fail.

2. "Ensure that interactive mode is disabled" -- this one is tricky. I didn't find any info on how to disable interactive mode in Python itself (I was hoping for environment variables or something like this). One idea would be to disallow `stdin` in Graphene-SGX (so even if admin launches python in interactive mode, she cannot type anything), though I don't know how this can be done easily. I will look into this, but maybe others can reply as well.

**Comment by shankari** [comment]
@dimakuv Thanks!

1. Will this include scripts loaded from within python as well (e.g. using `importlib`)? Those will be translated into syscalls under the hood, so I assume so, but I wanted to confirm.
1. There has been prior work in micropython on disabling inputs to the REPL https://github.com/micropython/micropython/issues/2349 This may not be exactly what we want but certainly gives us some pointers. However, I think that the solution to disallow `stdin` (in the manifest, of course) is preferable if possible because:
   1. it is a generic solution that works for all languages that support a REPL, including some non-scripting languages such as scala
   1. it doesn't introduce the maintenance hassle of modifying and recompiling python. One of the big advantages of graphene is the ability to run unmodified programs and we should stick to that design goal if at all possible

**Comment by dimakuv** [comment]
1. Yes, this should include *all* files that Python executable will access.

2. I didn't find a simple way to disallow `stdin` in Graphene-SGX. You can dig into Graphene and figure out how to add such functionality and apply a Pull Request. Or someone else will have to implement it :)

**Comment by shankari** [comment]
@dimakuv yeah we are happy to make the change and contribute a PR. I was hoping to get some pointers on where to start from @chiache - he seemed to think that it wasn't too hard... :)

**Comment by shankari** [comment]
@chiache any updates on this? Now that finals week is done, I am hoping that some students can take a look at this - e.g. @njriasan

**Comment by dimakuv** [comment]
@shankari Is this issue still relevant? Unfortunately, I didn't look at "disabling stdin".

**Comment by mkow** [comment]
I believe this issue is fixed by using protected files + protected argv, which are already on master.
