### ISSUE TITLE
shim_do_poll incorrectly setting revents wrt POLLERR and POLLHUP

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#389]
In `sys/shim_poll.c`, the function `shim_do_poll` has an error on the line that reads:

```
 fds[i].revents |= (fds[i].events & (POLLERR|POLLHUP));
```

Per the manpage, `POLLERR` and `POLLUP` are returned in `revents` and ignored in `events`.  Indeed, programs should not be setting -- and typically don't set  -- `events` with these values.

The effect of the bug above is, among others, that a process will never get a disconnect event for a peer socket.

**Comment by donporter** [comment]
Thanks for the bug report.  I'm guessing there is an LTP test or another simple test case that can demonstrate this issue?
