### ISSUE TITLE
Memory limitation

### ISSUE THREAD

**Issue by jaebaek** [oscarlab/graphene#39]
Hi, I have a question about the memory allocation.
As far as I understand, we can specify the required memory in the manifest like

sgx.enclave_size = 10240M

However, the problem I meet is that the size is limited up to 4GB ..
I think it is a problem of mmap() in sgx device driver.
It seems isgx_vma_open() of sgx driver does not support memory more than 4GB.

If you have any idea to solve this problem (e.g., allocating 10GB), could you please give me some information?

Thank you so much (and thank you for this wonderful project!)

**Comment by donporter** [comment]
The issue isn't allocations bigger than 4 GB, it is that enclave sizes need to be a power of two.  This is a hardware limitation.

So in this example you can do 8GB or 16 GB, but not 10.

We added a unit test and some clearer warnings about this issue.
