### ISSUE TITLE
listening unix domain socket pipeid likely always 0

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#390]
In `sys/shim_socket.c`'s function `shim_do_bind`, if the socket has type `AF_UNIX`, its piped is set to

```
 data->pipeid = dent->rel_path.hash >> 32;
```

I haven't worked through the logic, but, empirically,  in`fs/shim_fs_hash.c`, `hash_one` returns a 32-bit hash, despite having a return type of `uint64_t`.  Thus, after the bit shift, the listening socket has a pipeid of 0.  The result is that a process can only have one listening unix domain socket.

Is there a reason for the bit shift in the first place?

**Comment by donporter** [comment]
I'm not sure about this off the top of my head.  @chiache ?

**Comment by mkow** [comment]
This shift doesn't make any sense to me. The same bug is in `shim_do_connect`, but I see you already fixed both in your commit.

Also, the hash itself contains an undefined behavior (when compiled with 32-bit longs):
https://github.com/oscarlab/graphene/blob/90dae44640849aba32b91c4054c71180e5199c51/LibOS/shim/src/fs/shim_fs_hash.c#L33-L37
This shift is illegal then, and on 32-bit x86 will most likely result in `hash += hash`. Why do we need that folding function?
