### ISSUE TITLE
[Pal and LibOS] fix printf argument which requires printf in PAL to support %zu

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#392]
by adding __attribute__((format(printf, ))) reviled some printf argument is wrong.
In order to fix it cleanly protably, 
- enhance printf in Pal to support more % argument
  current %zu for size_t isn't supported
- introduce PRIxx for portability
- fix LibOS print argument 
- checkpoint part needs to be fixed. it mixes size_t and int.

**Comment by dimakuv** [comment]
We added `attribute((format(printf)))` everywhere and fixed all related issues long ago. Closing.
