### ISSUE TITLE
Golang feature support

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#396]
Go powers many of the most critical cloud infrastructure projects. Many more companies are depending on Go in production. Over the years, developers use Go for cloud development because of its efficiency, productivity, built-in concurrency, and low latency. 
We'd like to see Graphene-SGX natively support unmodified Golang applications. so increasing the adoption and usability, Thanks.

**Comment by donporter** [comment]
Agreed.  I think this is a good goal for the project.

**Comment by jvsteiner** [comment]
I'd like to see this as well, has it made it to the roadmap yet?

**Comment by dimakuv** [comment]
Short answer is Yes. We are currently working on this.

**Comment by jakecraige** [comment]
Any update on the status of this?

**Comment by dimakuv** [comment]
We have an internal version running. It is still about one half of the way to the mainline. Unfortunately, Golang wasn't (and still is not) our main priority.

**Comment by duanbing** [comment]
@dimakuv if it's low priority for you guys, opensouce it will bring it a new life.

**Comment by dimakuv** [comment]
@duanbing Well, technically the PR is there: https://github.com/oscarlab/graphene/pull/1218. Unfortunately, we currently have other features to finish. But you are encouraged to try this PR out :)

**Comment by mkow** [comment]
@yamahata Would you have time to check if we have any outstanding problems with Go after merging #2090?

**Comment by mkow** [comment]
So far it seems that the newly added Go support is working, so I'm closing this one.

**Comment by lghhh** [comment]
> So far it seems that the newly added Go support is working, so I'm closing this one.

Where can I found the Go support?

**Comment by dimakuv** [comment]
@lghhh There is currently no example of Go applications. What is meant by "Go support is working" is that Graphene can run Go applications. So you can try it out yourself -- take your original Go app and write a Graphene manifest file for it, and run.

We are currently working on adding a Go-app example to Graphene. So at some point you'll see it under https://github.com/oscarlab/graphene/tree/master/Examples

**Comment by lghhh** [comment]
> @lghhh There is currently no example of Go applications. What is meant by "Go support is working" is that Graphene can run Go applications. So you can try it out yourself -- take your original Go app and write a Graphene manifest file for it, and run.
> 
> We are currently working on adding a Go-app example to Graphene. So at some point you'll see it under https://github.com/oscarlab/graphene/tree/master/Examples

Thanks a lot!

**Comment by lghhh** [comment]
> @lghhh There is currently no example of Go applications. What is meant by "Go support is working" is that Graphene can run Go applications. So you can try it out yourself -- take your original Go app and write a Graphene manifest file for it, and run.
> 
> We are currently working on adding a Go-app example to Graphene. So at some point you'll see it under https://github.com/oscarlab/graphene/tree/master/Examples

I have a hard time migrating golang into Graphene. I try to write simple helloworld.go, Makefile and manifest.template like Python example. But I got "no child prosess" error for graphene-direct and "out of memory" error for graphene sgx, I have try various enclave_size, stack.size and thread_num.

Could you please help me confirm that Graphene support golang runtime (run .go inside) or linux binary files(build outside first)? 

Thanks a lot!
