### ISSUE TITLE
Cannot run Python with SGX (missing libs)

### ISSUE THREAD

**Issue by sgx1** [oscarlab/graphene#41]
Runtime/resolv is missing in SGX mode

**Comment by adombeck** [comment]
It works after setting `LIBCDIR = $(level)../../glibc-build` in `LibOS/shim/test/Makefile`.
I guess [this change](https://github.com/oscarlab/graphene/commit/872af4984ca378d0fbd0175e7d8e8a05d6e905dc#diff-2b530a0be708ff8a4dfa655c0610e723) was committed inadvertently

**Comment by donporter** [comment]
Should be fixed now. Sorry about that.

Albeit a gradual process, we are working on improving the build process.  So the change was intentional, but not fully tested and disrupted some app builds.
