### ISSUE TITLE
Can not make OPENJDK in SGX mode

### ISSUE THREAD

**Issue by achenfengb** [oscarlab/graphene#42]
Hi,

The OPENJDK app can not be compiled using the command "make SGX=1", and the following is the error msg. Do you know what I should do? Thank you in advance.

`     make JDK_TOPDIR=/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/jdk JDK_MAKE_SHARED_DIR=/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/jdk/make/common/shared EXTERNALSANITYCONTROL=true SOURCE_LANGUAGE_VERSION=7 TARGET_CLASS_VERSION=7 MILESTONE=internal BUILD_NUMBER=b00 JDK_BUILD_NUMBER=b00 FULL_VERSION=1.7.0-internal-user_2017_02_01_14_24-b00 PREVIOUS_JDK_VERSION=1.6.0 JDK_VERSION=1.7.0 JDK_MKTG_VERSION=7 JDK_MAJOR_VERSION=1 JDK_MINOR_VERSION=7 JDK_MICRO_VERSION=0 PREVIOUS_MAJOR_VERSION=1 PREVIOUS_MINOR_VERSION=6 PREVIOUS_MICRO_VERSION=0 STATIC_CXX=false PAX_COMMAND=/usr/sbin/paxmark.sh PAX_COMMAND_ARGS="-vm" ARCH_DATA_MODEL=64 COOKED_BUILD_NUMBER=0 ALT_OUTPUTDIR=/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/build/linux-amd64/hotspot/outputdir ALT_EXPORT_PATH=/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/build/linux-amd64/hotspot/import BUILD_FLAVOR=product ALT_SLASH_JAVA=/NOT-SET ALT_BOOTDIR=/usr/lib/jvm/java-7-openjdk-amd64 HOTSPOT_BUILD_JOBS=8 all_product
INFO: ENABLE_FULL_DEBUG_SYMBOLS=1
make[3]: Entering directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/hotspot/make'
cd /home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/hotspot/make; \
        make BUILD_FLAVOR=product VM_TARGET=product generic_build2 ALT_OUTPUTDIR=/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/build/linux-amd64/hotspot/outputdir
INFO: ENABLE_FULL_DEBUG_SYMBOLS=1
make[4]: Entering directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/hotspot/make'
mkdir -p /home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/build/linux-amd64/hotspot/outputdir
cd /home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/build/linux-amd64/hotspot/outputdir; \
            MAKEFLAGS= MFLAGS= EXTRA_userLAGS="-fPIC" nmake -NOLOGO -f \\home\\user\\graphene\\LibOS\\shim\\test\\apps\\openjdk\\openjdk-7\\hotspot\\make\\windows\\build.make \
                      Variant=compiler2 \
                      WorkSpace=\\home\\user\\graphene\\LibOS\\shim\\test\\apps\\openjdk\\openjdk-7\\hotspot \
                      BootStrapDir=\\usr\\lib\\jvm\\java-7-openjdk-amd64 \
                      BuildUser= \
                       ENABLE_FULL_DEBUG_SYMBOLS=1 ZIP_DEBUGINFO_FILES=1 RM="rm -f" ZIPEXE=zip JDK_MKTG_VERSION=7 JDK_MAJOR_VER=1 JDK_MINOR_VER=7 JDK_MICRO_VER=0 JDK_BUILD_NUMBER=0 BUILD_WIN_SA=1 JAVA_HOME=\\usr\\lib\\jvm\\java-7-openjdk-amd64 OUTPUTDIR=\\home\\user\\graphene\\LibOS\\shim\\test\\apps\\openjdk\\openjdk-7\\build\\linux-amd64\\hotspot\\outputdir GAMMADIR=\\home\\user\\graphene\\LibOS\\shim\\test\\apps\\openjdk\\openjdk-7\\hotspot MAKE_VERBOSE=y HOTSPOT_RELEASE_VERSION=24.95-b00 JRE_RELEASE_VERSION=1.7.0-internal-user_2017_02_01_14_24-b00 HOTSPOT_BUILD_VERSION= INCLUDE_TRACE=1 product
/bin/sh: 2: nmake: not found
make[4]: *** [generic_build2] Error 127
make[4]: Leaving directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/hotspot/make'
make[3]: *** [product] Error 2
make[3]: Leaving directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7/hotspot/make'
make[2]: *** [hotspot-build] Error 2
make[2]: Leaving directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7'
make[1]: *** [build_product_image] Error 2
make[1]: Leaving directory `/home/user/graphene/LibOS/shim/test/apps/openjdk/openjdk-7'
make: *** [openjdk-7/build/linux-amd64/j2sdk-image/jre/bin/java] Error 2`

**Comment by achenfengb** [comment]
OS: Ubuntu 14.04 server.
Kernel: 3.19.

Thank you.

**Comment by chiache** [comment]
In the latest commit, we tested Graphene-SGX with the off-the-shelf OpenJDK 7. It does not completely work because of the huge memory footprint of OpenJDK. However, some small programs not too much bigger than a helloworld may actually work.

**Comment by donporter** [comment]
I just tested that HelloWorld does work (at least for me) in sgx with the current master on 14.04.

I do think it is just as well not to have to build OpenJDK from scratch; easier to use prebuilt libraries.

Do let us know if this works for you.
