### ISSUE TITLE
I have followed the SGX Quick Start but no PAL binary in /LibOS/shim/test/native

### ISSUE THREAD

**Issue by Ruide** [oscarlab/graphene#43]
There is a pal_loader but shell saying it is not built, , or security mode is not supported

**Comment by donporter** [comment]
The test/native directory is deprecated.  We have been making some changes to the build system that probably broke this.

Are there specific unit tests in that directory that you want to run?  If so, we can probably port them into the regression testing framework.

**Comment by Ruide** [comment]
Thank you for your quick response.

I am trying to test graphene with sgx on my machine. I am working on a project which need to port a legacy application into enclave. But it turns out I cannot make it work following the tutorials. 

When I follow the <SGX quick start>, I have the issue I said in this thread.
When I follow <Run Applications with SGX>, shell says pal-Linux is not built, or security mode is not supported.

So can you inform me where can I know how to put graphene into action?
Thank you.

**Comment by chiache** [comment]
I've updated the wiki page on quick-start instructions.

**Comment by donporter** [comment]
If the build succeeded, you should have a pal-Linux in <graphene root>/Runtime.  If you built with SGX=1, you will have a pal-Linux-SGX in <graphene root>/Runtime.

If you don't have these, please post a more detailed set of command output from the build so we can see what is going wrong.

Once you have these, it should be as simple* as:
path/to/Pal [executable|manifest]

Caveat: you also need to make a manifest, which is less simple; this can be pattern-matched on existing manifests.

**Comment by Ruide** [comment]
Yes, I found the pal-Linux-SGX and it is working now. Thank you for your help!
And the following command need to be added.

sudo sysctl vm.mmap_min_addr=0

Yes, making a manifest will take some time before I can port the binary, thank you for your heads-up!

**Comment by Ruide** [comment]
Still for the Quick start tutorial, when I do last part:
cd LibOS/shim/test/apps/lmbench
make SGX=1

it says:
make[1]: Leaving directory `/home/rd/Downloads/graphene-master/LibOS/shim/test/apps/lmbench/lmbench-2.5/src'             

ln -sf ../../../Makefile.lmbench lmbench-2.5/bin/linux/Makefile

make -C lmbench-2.5/bin/linux/

make[1]: Entering directory `/home/rd/Downloads/graphene-master/LibOS/shim/test/apps/lmbench/lmbench-2.5/bin/linux'

Makefile:19: warning: overriding commands for target `pal_loader'

../../../../../Makefile:43: warning: ignoring old commands for target `pal_loader'

make[1]: *** No rule to make target `../../../../../pal_loader', needed by `pal_loader'.  Stop.

make[1]: Leaving directory `/home/rd/Downloads/graphene-master/LibOS/shim/test/apps/lmbench/lmbench-2.5/bin/linux'

make: *** [build-manifest] Error 2

**Comment by Nithinccu** [comment]
In the Quick start tutorial, while building the library OS
cd LibOS
make SGX=1

make[3]: Entering directory '/home/sgx/Desktop/graphene/Pal/lib'
[ atoi.o ]
[ strlen.o ]
[ memcmp.o ]
[ memcpy.o ]
[ wordcopy.o ]
[ memset.o ]
[ strchr.o ]
[ printfmt.o ]
[ hton.o ]
[ inet_pton.o ]
[ config.o ]
[ path.o ]
[ udivmodti4.o ]
[ cipher_wrap.o ]
[ dhm.o ]
[ cipher.o ]
[ rsa.o ]
[ cmac.o ]
[ sha256.o ]
[ md.o ]
[ aes.o ]
[ bignum.o ]
[ aesni.o ]
[ mbedtls_adapter.o ]
[ mbedtls_dh.o ]
[ graphene-lib.a ]
make[3]: Leaving directory '/home/sgx/Desktop/graphene/Pal/lib'
make[2]: *** No rule to make target '/home/sgx/Desktop/graphene/LibOS/shim/src/../../../Runtime/libpal-Linux-SGX.so', needed by 'libsysdb.so'.  Stop.
make[2]: Leaving directory '/home/sgx/Desktop/graphene/LibOS/shim/src'
Makefile:13: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/sgx/Desktop/graphene/LibOS/shim'
Makefile:14: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dimakuv** [comment]
Are you sure you performed steps correctly? It looks like you are building LibOS without PAL. You first need to build PAL:
```
cd Pal/src
make SGX=1
```

Note that `SGX=1` here is important.

**Comment by Nithinccu** [comment]
Yes, it worked! Thank you very much!
