### ISSUE TITLE
Problem with write()

### ISSUE THREAD

**Issue by adilahmad17** [oscarlab/graphene#44]
Hi,

So my enclave program simply creates a file and starts writing to the file. I wanted to add gibberish to fill up a file to 8GB of size. However, write() crashes after 2GB which is a simple problem of int being used within the code. However, even when I changed them to uint64_t, I still can't create a file larger than 4GB. Can you please check why this is the case?

Thanks!

**Comment by donporter** [comment]
Can you post some test code?  Just the app+manifest would help.

**Comment by adilahmad17** [comment]
`void test_empty_write() {
    int fd = open("test_file.txt", O_CREAT | O_RDWR, 0700);

    char * buf = malloc(sizeof(char)*1024000);
    *buf = 'a';

    size_t ret;
    for (int i = 0; i < 5000; i++) {
        ret = write(fd, buf, sizeof(char)*1024000);
        printf("%d \n", i);
        assert(ret == sizeof(char)*1024000);
    }

    close(fd);
}`

Manifest:
`# https://github.com/oscarlab/graphene/wiki/Manifest-Syntax
loader.preload = file:$(SHIMPATH)
loader.env.LD_LIBRARY_PATH = /lib
loader.debug_type = inline
loader.syscall_symbol = syscalldb

fs.mount.lib.type = chroot
fs.mount.lib.path = /lib
fs.mount.lib.uri = file:$(LIBCDIR)

fs.mount.bin.type = chroot
fs.mount.bin.path = /bin
fs.mount.bin.uri = file:/bin

sys.brk.size = 64M
sys.stack.size = 64M


net.allow_bind.1 = 127.0.0.1:8000
net.allow_peer.1 = 127.0.0.1:8000

sgx.trusted_files.ld = file:$(LIBCDIR)/ld-linux-x86-64.so.2
sgx.trusted_files.libc = file:$(LIBCDIR)/libc.so.6
sgx.trusted_files.libdl = file:$(LIBCDIR)/libdl.so.2
sgx.trusted_files.libm = file:$(LIBCDIR)/libm.so.6
sgx.trusted_files.libpthread = file:$(LIBCDIR)/libpthread.so.0
sgx.trusted_files.libsysdb = file:$(SHIMPATH)

sgx.allowed_files.dir = file:testfile
sgx.allowed_files.encrypted =top file:encrypted
sgx.enclave_size = 16384M`

Thanks!

**Comment by adilahmad17** [comment]
We solved this issue. Please have a look at this diff. Also, there are a couple of more places that integers are used instead of uint64_t or similar which causes problems while loading larger files in graphene. Let me post those diffs too. 

Thanks!

```
diff --git a/graphene/Pal/src/host/Linux-SGX/ocall_types.h b/graphene/Pal/src/host/Linux-SGX/ocall_types.h
index 706d5c5..d208005 100644
--- a/graphene/Pal/src/host/Linux-SGX/ocall_types.h
+++ b/graphene/Pal/src/host/Linux-SGX/ocall_types.h
@@ -131,7 +131,7 @@ typedef struct {
 
 typedef struct {
     int ms_fd;
-    unsigned int ms_length;
+    uint64_t ms_length;
 } ms_ocall_ftruncate_t;
 
 typedef struct {
```

**Comment by donporter** [comment]
Thanks!  Changing to uint64_t is pretty uncontroversial to me.  If you would post a pull request, or send a complete patch with the other 64-bit changes, I will merge them.

**Comment by adilahmad17** [comment]
Okay sure. I am currently working towards a deadline but I will definitely make a clean diff for you to patch Graphene. 
Thanks for this amazing LibOS btw!
