### ISSUE TITLE
[Pal/Linux, Linux-SGX] db_events.c uses 64bit integer for futex

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#441]
Linux futex word is 32bits integer among all platform. even on 64 bit arch.
db_events.c uses struct atomic_int for futex which is 64bit integer.
It should use 32bits integer.

Because of little endianness, it's luckly working. but it should be corrected.

**Comment by donporter** [comment]
Agreed.  Fixes welcome.   Perhaps add atomic_int32 and atomic_int64 types?

**Comment by mkow** [comment]
Futexes were rewritten in https://github.com/oscarlab/graphene/pull/1164, this issue is outdated.
