### ISSUE TITLE
ocall_sock_send and ocall_sock_recv can overflow stack

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#442]
In `Pal/src/host/Linux-SGX/enclave_ocalls.c`, the `ocall_sock_recv` and `ocall_sock_send` will copy the respective buffer arguments to the untrusted user by adjusting the stack.  In the case of `ocall_sock_recv`, this occurs in the line

```
ms->ms_buf = ALLOC_IN_USER(buf, count)
```

and,  in the case of  of `ocall_sock_send`, the line
```
ms->ms_buf = COPY_TO_USER(buf, count);
```
Note that both `ALLOC_IN_USER` and `COPY_TO_USER` will eventually call `enclave_framework.c`'s `sgx_ocalloc` function, which adjusts the stack.

The problem, of course, is that if the buffer is too big, the stack will overflow.

The fix is to apply the same check that `ocall_read` and `ocall_write` do; that is, if the buffer to be allocated is too large to fit on the stack, call `ocall_alloc_untrusted` to allocate some untrusted heap memory.

**Comment by donporter** [comment]
Seems like a legit bug to me.  Thanks for the report - any fixes welcome.

**Comment by yamahata** [comment]
Seems valid bug.
Because you have already have a fix, can you please send it as PR?
