### ISSUE TITLE
clone() for fork doesn't work

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#446]
native glibc (not-modified for graphene or USE_clone_FOR_fork defined) uses clone(2) syscall for fork(3) library function
as clone(CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHD,   0, NULL, &THREAD_SELF->tid)

This doesn't work as expected and the execution stalls somewhere. I guess it's not tested
because modified glibc uses fork(2) system call, not clone(2).

Once this is fixed, glibc modification to nptl/sysdeps/unix/sysv/linux/x86_64/fork.c
can be removed.

**Comment by donporter** [comment]
Thanks for the issue.  I'd love to get rid of as many glibc patches as possible.
