### ISSUE TITLE
Test apps fail with segfault

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#45]
Today I pulled the commits since f2c36a1 and rebuilt everything. Now most of the test apps fail.

Example:
```
cd LibOS/shim/test/apps/python
make SGX=1 && make SGX_RUN=1
./python.manifest.sgx scripts/helloworld.py
```
Then it just hangs without output, on ^C it prints `Segmentation fault`. The same happens with lighttpd. But `native/helloworld.manifest.sgx` works.

**Comment by chiache** [comment]
Should be resolved in the latest version.
