### ISSUE TITLE
Function "check_parent_mrenclave" doesn't check the mrenclave value of the parent enclave

### ISSUE THREAD

**Issue by rainfld** [oscarlab/graphene#466]
The function "check_parent_mrenclave" in Linux-SGX/db_process.c is used as a callback during attestation for fork to verify the enclave. However, mrenclave of the parent enclave is not validated in this function. 

See the comments:

    /* for now, we will accept any enclave as a parent, but eventually
       we should check parent, maybe using crypto challenge */
    return 0;

This will be to-do feature.

**Comment by mkow** [comment]
Outdated, closing.
