### ISSUE TITLE
No rule to make target 'exec_victim.manifest.sgx'.  Stop.  recipe for target 'pie.manifest.sgx' failed

### ISSUE THREAD

**Issue by gokhalesushant65** [oscarlab/graphene#472]
I am using the documentation and repo at [this](https://github.com/oscarlab/graphene) site.

I am getting issue right from "Building Graphene SGX" step. Following are the errors encountered.

**(graphene) dell@dell:~/graphene-master$ make SGX=1**
/home/dell/graphene-master/Pal/src/host/Linux-SGX/signer/pal-sgx-sign -libpal /home/dell/graphene-master/Pal/src/host/Linux-SGX/../../../../Runtime/libpal-Linux-SGX.so -key /home/dell/graphene-master/Pal/src/host/Linux-SGX/signer/enclave-key.pem -output static.manifest.sgx -exec static -manifest static.manifest
Attributes:
    size:      268435456
    threadnum: 4
    isvprodid: 0
    isvsvn:    0
    flags:     0600000000000000
    xfrms:     0700000000000000
    miscs:     00000000
Trusted files:
    2d5333c74dc3fcb17bc42824c2c522a037e0c8ddbf31143e58c719d8b7291ea4 file:../../../../Runtime/libsysdb.so
    74b95e2090dfab5e52eb1ea24c9b5d59fbf664193e087181eb783d16f91bac27 static
Trusted children:
Memory:
    000000000ffff000 [REG:R--] (manifest) measured
    000000000fff6000-000000000fffe000 [REG:RW-] (ssa)
    000000000fff1000-000000000fff5000 [TCS:---] (tcs)
    000000000ffec000-000000000fff0000 [REG:RW-] (tls)
    000000000ffdb000-000000000ffeb000 [REG:RW-] (stack)
    000000000ffca000-000000000ffda000 [REG:RW-] (stack)
    000000000ffb9000-000000000ffc9000 [REG:RW-] (stack)
    000000000ffa8000-000000000ffb8000 [REG:RW-] (stack)
    000000000bd77000-000000000bda2000 [REG:R-X] (code) measured
    000000000bfa2000-000000000bfa4000 [REG:RW-] (data) measured
    000000000bfa4000-000000000ffa7000 [REG:RW-] (bss)
    0000000000400000-00000000004ca000 [REG:RWX] (code) measured
    00000000006c9000-00000000006cc000 [REG:RW-] (data) measured
    00000000006cc000-00000000006ce000 [REG:RW-] (bss)
    00000000006ce000-000000000bd76000 [REG:RWX] (free)
    0000000000010000-0000000000400000 [REG:RWX] (free)
Measurement:
    4f9d70de1c6af95247530cea06535d9b5b98dbd8175b17a37c6b703a33a6adc7
make[5]: Entering directory '/home/dell/graphene-master/LibOS/shim/test/native'
make[5]: 'manifest' is up to date.
make[5]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test/native'
for f in `grep -Po 'sgx.trusted_children.[^\\s=]+\\s*=\\s*file:\\K\\S+' manifest`; do make ${f%.sig}.manifest.sgx; done
make[5]: Entering directory '/home/dell/graphene-master/LibOS/shim/test/native'
make[5]: *** No rule to make target 'exec_victim.manifest.sgx'.  Stop.
make[5]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test/native'
../../../../Pal/src///host/Linux-SGX/Makefile.Test:33: recipe for target 'pie.manifest.sgx' failed
make[4]: *** [pie.manifest.sgx] Error 2
make[4]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test/native'
make[3]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test'
make[2]: Leaving directory '/home/dell/graphene-master/LibOS/shim'
make[1]: Leaving directory '/home/dell/graphene-master/LibOS'
make -C Runtime all
make[1]: Entering directory '/home/dell/graphene-master/Runtime'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/dell/graphene-master/Runtime'

**(graphene) dell@dell:~/graphene-master$ cd LibOS/shim/test/native/**

**(graphene) dell@dell:~/graphene-master/LibOS/shim/test/native$ make SGX=1**
make[1]: Entering directory '/home/dell/graphene-master/LibOS/shim/test/native'
make[1]: 'manifest' is up to date.
make[1]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test/native'
for f in `grep -Po 'sgx.trusted_children.[^\\s=]+\\s*=\\s*file:\\K\\S+' manifest`; do make ${f%.sig}.manifest.sgx; done
make[1]: Entering directory '/home/dell/graphene-master/LibOS/shim/test/native'
make[1]: *** No rule to make target 'exec_victim.manifest.sgx'.  Stop.
make[1]: Leaving directory '/home/dell/graphene-master/LibOS/shim/test/native'
../../../../Pal/src///host/Linux-SGX/Makefile.Test:33: recipe for target 'pie.manifest.sgx' failed
make: *** [pie.manifest.sgx] Error 2

**(graphene) dell@dell:~/graphene-master/LibOS/shim/test/native$ make SGX_RUN=1**
[ Token: static ]
Attributes:
    mrenclave: 4f9d70de1c6af95247530cea06535d9b5b98dbd8175b17a37c6b703a33a6adc7
    isvprodid: 0
    isvsvn:    0
    flags:     0600000000000000
    xfrms:     0700000000000000
    miscs:     00000000
    modulus:   f357fd12f0287bd924ae74d602136d1b...
    exponent:  3
    signature: 0d239b243efa42e7aaa67cac03f9d430...
make: *** No rule to make target 'pie.token', needed by 'all'.  Stop.

**(graphene) dell@dell:~/graphene-master/LibOS/shim/test/native$ ls**
alarm              divzero.c       fork                 helloworld.c          meminfo.c           pal_loader      readdir                 sleep                     static.sig                udp.c
alarm.c            dup             fork_bomb            helloworld.pthread    msg_create          pid_alloc       readdir.c               sleep.c                   static.token              unix
brk                dup.c           fork_bomb.c          helloworld.pthread.c  msg_create.c        pid_alloc.c     rename                  socketpair                sync.pthread              unix.c
brk.c              epoll           fork.c               kill                  msg_create.libos    pid_kill        rename.c                socketpair.c              sync.pthread.c            vfork
clone              epoll.c         fork_exec            kill.c                msg_create.libos.c  pid_kill.c      sandbox_create.libos    sqrt.m                    system                    vfork.c
clone.c            epoll_socket    fork_exec.c          ls.manifest           msg_send            pie             sandbox_create.libos.c  sqrt.m.c                  system.c                  vfork_exec
condvar.pthread    epoll_socket.c  fs                   ls.manifest.template  msg_send.c          pie.c           script                  start.pthread.m           tcp                       vfork_exec.c
condvar.pthread.c  errno           fs.c                 Makefile              msg_send.libos      pipe            script1.sh              start.pthread.m.c         tcp.c
cpuinfo            errno.c         futextest.pthread    malloc                msg_send.libos.c    pipe.c          script2.sh              static                    test_start_pthread_m.m
cpuinfo.c          exec_fork       futextest.pthread.c  malloc.c              multiproc           pipe_latency    script3.sh              static.c                  test_start_pthread_m.m.c
dir                exec_fork.c     get_time.m           manifest              multiproc.c         pipe_latency.c  script.c                static.manifest           time
dir.c              file            get_time.m.c         manifest.template     multisleep          proc            sem                     static.manifest.sgx       time.c
divzero            file.c          helloworld           meminfo               multisleep.c        proc.c          sem.c                   static.manifest.template  udp

**(graphene) dell@dell:~/graphene-master/LibOS/shim/test/native$ SGX=1 ./pal_loader helloworld**
cannot open manifest file: helloworld.manifest.sgx
USAGE: /home/dell/graphene-master/Runtime/pal-Linux-SGX [executable|manifest] args ...

**Comment by donporter** [comment]
This does not happen on my system.  Can you tell me a bit more about what OS and gcc version you are using to compile with, as well as any other error messages higher up in the build output? (or attach the complete output)

**Comment by gokhalesushant65** [comment]
[graphene build output.txt](https://github.com/oscarlab/graphene/files/2865351/graphene.build.output.txt)

**Comment by dimakuv** [comment]
Looks like you are running into this issue: https://github.com/oscarlab/graphene/pull/391

Apply the patch from that Pull Request to `LibOS/shim/test/native/manifest.template`. Rebuild the system from scratch and try HelloWorld again.

**Comment by mkow** [comment]
FYI: #391 was just merged to master.

**Comment by gokhalesushant65** [comment]
Thanks dimakuv and mkow :+1:  The original compilation part is resolved.

Now, when I run the helloworld program, I get following error. 
**(graphene) dell@dell:~/graphene/LibOS/shim/test/native$  SGX=1 ./pal_loader helloworld**
Permission denied on mapping enclave. You may need to set sysctl vm.mmap_min_addr to zero
initializing enclave failed: create_enclave: 12

But, when I run the above command with "sudo" prefixed, I get the desired output. Attached is the output of the command.
**(graphene) dell@dell:~/graphene/LibOS/shim/test/native$ sudo SGX=1 ./pal_loader helloworld > helloworld_output.txt**
[helloworld_output.txt](https://github.com/oscarlab/graphene/files/2868075/helloworld_output.txt)

Should I always run "sudo" or am I doing something wrong yet?

**Comment by mkow** [comment]
You can also use `sysctl vm.mmap_min_addr=0`.
AFAIR this requirement is only for non-PIE binaries, which has to be loaded at a hardcoded address and for this, we need to cover also low addresses, because of SGX peculiarities\*.

\* SECS.BASEADDR must be aligned to SECS.SIZE, so if you want to have a big enclave (e.g. 1GB) and at the same time map something to low addresses (as non-PIE binaries often require), then you need to also cover address 0.

**Comment by dimakuv** [comment]
As @mkow said, you need to set `mmap_min_addr` to zero using root privileges. You will need to set it every time you reboot the machine.

For quick reference, this is the command to do it: `echo 0 | sudo tee /proc/sys/vm/mmap_min_addr`.

**Comment by gokhalesushant65** [comment]
thanks mkow and dimakuv :) :+1: 
Issue is resolved. Closing the issue.
