### ISSUE TITLE
Rename misleading `PAL_EVENT_DIVZERO`

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#480]
Currently `SIGFPE` is translated as `PAL_EVENT_DIVZERO`, which is IMO very misleading, as `SIGFPE` is a generic name for a bunch of different arithmetic faults (`#DE` and `#MF` are translated into `SIGFPE`, which can be caused by e.g. `x/0`, `INT_MIN/-1` or floating point exceptions).
I'd suggest renaming it to `PAL_EVENT_ARITHMETIC_ERROR`.

**Comment by donporter** [comment]
Sounds good to me.
