### ISSUE TITLE
Can't execute other docker image except redis

### ISSUE THREAD

**Issue by joey110119** [oscarlab/graphene#482]
When I follow README in "graphene/Tools/", although it still has some problem due to the new version of redis, but it will execute.

However when I use other dock images, they all comes the same error said " Unable to find image [dock image] locally".
For example, when running "./gsce run hello-world", the error message shows "Unable to find image 'gsc_hello-world:latest' locally".
I have confirmed that I already login and can run when use "docker run hello-world", but it still shows that.

**Comment by Kushg02** [comment]
I am having a similar issue when following the same README. After using docker to build an image (called testapp) in a external directory, verifying it runs correctly within said directory, went to graphene/Tools, and used the command `sudo ./gsce run testapp:latest` as instructed. 

I was given the following error: 
```bash
Step 6/13 : COPY Runtime/* /home/kushgarg/graphene/Runtime/
COPY failed: stat /var/lib/docker/tmp/docker-builder829585833/home/kushgarg/graphene/LibOS/glibc-build/csu/crt1.o: no such file or directory
Unable to find image 'gsc_testapp:latest' locally
docker: Error response from daemon: pull access denied for gsc_testapp, repository does not exist or may require 'docker login'.
See 'docker run --help'.
```

Any ideas on what I am doing wrong or overlooking? Were you eventualyl able to find a solution @joey110119?

**Comment by Kushg02** [comment]
I was able to get the program to run by creating a new image with the identical setup called 'gsc_testapp' and my program ran.

**Comment by thomasknauth** [comment]
The files under Runtime/ are symbolic links by default which makes the copy in step 6/13 fail; replacing with the actual files rectifies this issue. There are others things which don't work anymore because Graphene has evolved since anybody had a look at this script. I'll give it a shot and produce a fix. In general, I'd be positively surprised if it works for anything but the original test case. ;)

**Comment by thomasknauth** [comment]
You may want to try and see if this branch fixes the problems you are seeing: https://github.com/thomasknauth/graphene/tree/gsce-fix

**Comment by mkow** [comment]
GSC was deprecated, but there's a new implementation under review, which should be much better: https://github.com/oscarlab/graphene/pull/1345.
I'm closing this issue as outdated.
