### ISSUE TITLE
Accessing machine register using asm language in c/c++

### ISSUE THREAD

**Issue by gokhalesushant65** [oscarlab/graphene#483]
My code is attached herewith.
[test-rdpmc.txt](https://github.com/oscarlab/graphene/files/2880157/test-rdpmc.txt) 
Its a simple code to access performance counter using RDPMC instruction.

Its giving me following error:
> (graphene) dell@dell:~/graphene/LibOS/shim/test/apps/mytest_forRegisterAccess$ SGX=1 ./pal_loader test-rdpmc
Illegal instruction executed in enclave

I want to know if am I even allowed to directly access a machine register.
**My Assumption:**  graphene-SGX fundamentally doesnt shield such accesses and hence, such access can pose a security risk.

If my assumption is correct, is there any other way I can access machine registers? Or only through library calls?

**Comment by mkow** [comment]
Hi,

All performance counters, `cpuid` and other similar things are disabled during execution in enclave mode. This is enforced by SGX itself, not Graphene.

Does this answer your question?

**Comment by donporter** [comment]
I believe we emulate `cpuid` in Graphene by catching this signal and then emulating.  But not rdpmc.

I agree that we can't execute this directly in either case.

**Comment by dimakuv** [comment]
For completeness, I will refer you to the [source code](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_exception.c#L213).

As you can see, the code looks like this:
```c
        if (instr[0] == 0xcc) { /* skip int 3 */
            uc->rip++;
            restore_sgx_context(uc);
            return;
        }
        if (instr[0] == 0x0f && instr[1] == 0xa2) {  /* call cpuid */
            unsigned int values[4];
            if (!_DkCpuIdRetrieve(uc->rax & 0xffffffff,
                                  uc->rcx & 0xffffffff, values)) {
                uc->rip += 2;
                uc->rax = values[0];
                uc->rbx = values[1];
                uc->rcx = values[2];
                uc->rdx = values[3];
                restore_sgx_context(uc);
                return;
            }
        }
        if (instr[0] == 0x0f && instr[1] == 0x31) {  /* emulate rdtsc with ZERO values */
            uc->rip += 2;
            uc->rdx = 0;  /* ZERO value */
            uc->rax = 0;  /* ZERO value */
            restore_sgx_context(uc);
            return;
        }
```

So, currently Graphene-SGX traps on three illegal instructions: `int 3`, `cpuid`, and `rdtsc`. The first one is ignored completely, the second is executed in untrusted environment, and the third one is emulated to always return zeros.

If you want to emulate `rdpmc` and you understand security implications, you can add your own special case to Graphene-SGX, which will look very similar to `rdtsc` handling. You just need to replace opcodes from `0x0f 0x31` to `0x0f 0x33`. However, as @mkow noticed, there will be no real performance counters in production enclaves (should still work for debug enclaves, but I never tried that).

**Comment by dimakuv** [comment]
I guess one question is: why do you want to do that? I vaguely remember some research on using performance counters on debug enclaves for optimization purposes. If this is what you want, you should check out those research papers.

**Comment by gokhalesushant65** [comment]
Thanks @donporter @dimakuv @mkow 
@dimakuv I need to access a register from a c/c++ code. For my thesis purpose, I was checking if I could port the same code to graphene-SGX. 
Well, will get back on the this if required.
