### ISSUE TITLE
[LibOS] shim_signal.pal_context is useless

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#487]
`shim_tls.h` defines `shim_signal` as:
```
struct shim_signal {
    siginfo_t   info;
    bool        context_stored;
    ucontext_t  context;
    PAL_CONTEXT * pal_context;
};
```

`shim_signal.pal_context` is used only in `shim_signal.c` and it is only written to and never read. It is useless. Probably the idea for it was to update the normal user context after returning from signal handling (e.g., user app could install SIGILL handler which updates RIP to ignore this exception, see https://www.oracle.com/technetwork/articles/servers-storage-dev/signal-handlers-studio-2282526.html). But it is not implemented anyway.

**Fix**: remove `pal_context` from `shim_signal` and everywhere else.

**Comment by chiache** [comment]
`pal_context` is used for copying the user context back to the host-level context. The copying is implemented in `_DkExceptionReturn()` of both Linux and Linux-SGX PAL.

**Comment by dimakuv** [comment]
You are right, should have double-checked. `signal->pal_context` is a pointer to `event->context`. When `signal->pal_context` is updated after user signal handler, so is `event->context` content. For some reason, I thought that `signal->pal_context` is newly allocated.

Closing this issue.
