### ISSUE TITLE
If app signal handler updates the context, it is not reflected after returning back to normal app execution

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#488]
If the app installs a signal handler which updates the context `ucontext_t` (https://www.oracle.com/technetwork/articles/servers-storage-dev/signal-handlers-studio-2282526.html), the changes in registers must be reflected when app returns back to normal context. However, the changes are not propagated to normal context in LibOS/Pal.

In particular, there is some code that is supposed to do that (?) in `shim_signal.c`:
```c
    (*handler) (sig, &signal->info, &signal->context);

    if (context)
        memcpy(&tcb->context, context, sizeof(struct shim_context));

    if (signal->pal_context)
        memcpy(signal->pal_context, signal->context.uc_mcontext.gregs,
               sizeof(PAL_CONTEXT));
```

So, after the app signal handler is executed, the updated normal context will be stored in `signal->context` (which is allocated on LibOS stack). The next statement overwrites `tcb->context` with the old `tcb->context` which is basically a noop (seems unnecessary). The next statement overwrites `signal->pal_context` which is not used at all (see #487).

Thus, `signal->context` updated by the app's signal handler is not memorized anywhere. When `signal` is popped off the LibOS stack, the updates are completely lost.

**Fix**: copy `signal->context` to `event->context` so that `_DkExceptionReturn()` updates the normal user context. Note that this was already fixed in #347 (but that PR introduces a completely new signal-handling mechanism).

**Comment by chiache** [comment]
Please understand `event` passed by the PAL is just an opaque pointer. Different PALs can have different structures for `event` and the library OS should not be aware of it.

I have to investigate whether copying `context` into `tcb->context` is *completely* useless. The original intention of doing such an update is to handle the case when an exception occurs in the middle of a system call and the library OS ends up needing the context after the signal handler updates it.

**Comment by dimakuv** [comment]
Similar to #487, I didn't understand that `signal->context` simply points to `event->context`. Therefore, the third statement will actually update `event->context` contents, and the reg changes will be reflected.

Interestingly, my debugging didn't reflect this correct behavior. I'll try again, but closing this issue for now.
