### ISSUE TITLE
shim_context.next is useless

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#489]
`shim_tls.h` defines `shim_context` as follows:
```c
struct shim_context {
    unsigned long           syscall_nr;
    void *                  sp;
    void *                  ret_ip;
    struct shim_regs *      regs;
    struct shim_context *   next;
    uint64_t                enter_time;
    uint64_t                preempt;
};
```

`shim_context.next` is useless. It is written only once in `shim_signal.c` and is never read.

**Fix**: remove this field and all its uses.

**Comment by chiache** [comment]
In my opinion, this point chains up all the nested contexts and can enable potential debug features such as stack backtrace. Since it is fairly harmless, I would suggest keeping it just for now.

**Comment by dimakuv** [comment]
Sure. I will close the issue then.
