### ISSUE TITLE
semctl02 flakiness

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#495]
On some jenkins runs, the semctl02 test fails intermittently.

I am not 100% sure this message came from that test, but may be relevant:
```
Internal memory fault at 0x617002 (IP = +0x9a495, VMID = 265956409, TID = 1)

Trace/breakpoint trap (core dumped)
```

**Comment by mkow** [comment]
SYS-V synchronization was removed from Graphene due to it's poor implementation quality, so this issue is no longer relevant.
