### ISSUE TITLE
How the direct syscalls are handled?

### ISSUE THREAD

**Issue by jsakkine** [oscarlab/graphene#5]
Hi

I'm the lead developer for the SGX driver that we are eventually trying to upstream. I just recently studied your project and one question popped into my mind.

Couldn't you bypass your sandbox by directly inserting SYSENTER opcode to the program instead of using libc to make the syscall? Of course with SGX this would not be possible because that would
cause #GP.

In order to fight against such attempts two options come up to my mind:
- Patch the binary. This is BTW something that Chromium used to do some years ago for JIT before seccomp filters came around.
- Block all direct system calls with a seccomp filter. This would thrawt the promise to run unmodified binaries.

If you have a solution for this issue, maybe it would be good to explain in the wiki because this is really the very first question that popped up when I ready it through.

**Comment by chiache** [comment]
Hi,

System calls made from the binaries are restricted by the SECCOMP filter (described in our original paper: http://www.oscar.cs.stonybrook.edu/papers/files/tsai14graphene.pdf), when running on Linux hosts. If Graphene is running inside an enclave, any system calls will cause #GP as you predict. System calls in enclaves will be handled in the future.

Thanks for the advice about adding the explanation in the Wiki. We will make the edit in the near future.

**Comment by jsakkine** [comment]
One more adventurous way to get this issue sorted would be to somehow extend seccomp to allow user space handlers for system calls. In practice, it would be non-trivial problem to find an upstreamable solution.

**Comment by jsakkine** [comment]
I'm not saying that Graphene is unusable without support for various ways of doing a direct syscall. All I'm saying is that it's an obvious limitation :)

**Comment by chiache** [comment]
Thanks for the comment. Indeed, one of main reasons for us to add SECCOMP filter is to support static binaries, and certainly there are non-trivial amount of them. Graphene is not using binary patching now, but it is a feature we will actively explore in the future.

**Comment by jsakkine** [comment]
Hey, I wasn't aware that there was SECCOMP_RET_PTRACE. And it was added back in 2012 (commit fb0fadf9b)That is quite cool. I just read the seccomp documentation and found this out. Sorry for being ignorant in that part, that's why my previous comments about seccomp must have sound like bit trippy :)  I guess this is what you are using for non-SGX use case? Of course this doesn't sort out SGX part but is still a great thing to have.

**Comment by jsakkine** [comment]
This can be safely closed after SGX related corner issues have been put into wiki page!

**Comment by mkow** [comment]
This whole thread seems to be greatly outdated so I'm closing it (static binary support was reworked and probably will change even more soon). Also, sandboxing support in Graphene was deprecated. If you want a two-way sandbox then just use a proper security sandbox and run Graphene inside.
