### ISSUE TITLE
Segfault with current Graphene tests

### ISSUE THREAD

**Issue by adilahmad17** [oscarlab/graphene#50]
Hi,

The native tests (all of them) in the LibOS directory fail with a segfault:

`[_DkResumeSighandler @sgx_exception.c:238] Segmentation Fault in Untrusted Code (RIP = 7fffed794980)`

I'm guessing there is some issue with compatibility with SGX SDK and SGX Drivers. Can you please tell me which commit (of SDK and drivers) I should use?

I can run the tests in the native SDK without any trouble but Graphene tests now fail.

Adil

**Comment by leesera** [comment]
I have a same problem @adilahmad17 describes :(

**Comment by adilahmad17** [comment]
Ah, so the problem is actually with the Linux Kernel Version. It seems like the current version of Graphene does not support the latest Linux Kernel 4.8. If I downgrade to 4.4, I can run it fine. I'll try to debug why it does not work with 4.8.

**Comment by donporter** [comment]
I am using 4.4 on my main dev machine, so 4.4 is more likely to work for sure.  It might be worth opening a separate issue about kernel version incompatibility.
