### ISSUE TITLE
Broadcast test fails without multicast route

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#501]
The "Multi-Process Broadcast Channel Transmission" regression test fails if there's no multicast route configured.

I see 3 options:

1. Automatically add a route when running this test. This would require root.
2. Skip the test if there's no multicast route
3. Fail the test, but improve the error message.

Any preferences? (I think 2. or 3.).

**Comment by mkow** [comment]
3rd option looks the best IMO.

@donporter, @chiache: Any thoughts?

**Comment by donporter** [comment]
I prefer to have PAL unit tests that always indicate a failure, even if we know it is a missing feature.  Helps us remember we aren't done :)

So, basically, I agree on # 3.
