### ISSUE TITLE
[LibOS] Clean-up of signal handling (without semantic changes)

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#506]
- [x] All test functions must be renamed `bool is_something()`. E.g., `test_user_memory()/test_user_string()` should be `is_user_memory_valid()/is_user_string_valid()`.

- [x] Merge single-caller functions with their callers. E.g., `_DkGenericEventTrigger()` should be folded into `_DkGenericSignalHandle()`.

- [x] Better names for functions. E.g., `_DkTerminateSighandler()` is actually a handler for all async signals, and `_DkResumeSighandler()` is for all sync signals/exceptions.

**Comment by mkow** [comment]
+1
Also, for predicate functions: their semantics should be verified (and updated changed) when doing such changes. E.g. `test_user_memory` currently returns `true` if a range is *invalid*.

**Comment by donporter** [comment]
+1

**Comment by yamahata** [comment]
+1. Because the patch will be trivial clean up, just go create a PR.

**Comment by mkow** [comment]
Seems that all of this was done while rewriting the codebase.
