### ISSUE TITLE
[PALs] New PAL error specifically for `ETIMEDOUT`

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#513]
PR #438 found an interesting bug of PALs merging `ETIMEDOUT` and `EAGAIN` in the same PAL error `PAL_ERROR_TRYAGAIN`. This simplification results in a bug in `futex` syscall.

#438 proposes a "hacky" solution to special-case the `futex` syscall in Linux-SGX PAL. However, I believe this solution will backfire in the future.

My proposal is to add a new PAL error specifically for `ETIMEDOUT` (let's call it `PAL_ERROR_TIMEDOUT`).  This solution will allow for clean check for error in `futex` syscall. It will also require a careful analysis of current checks on `PAL_ERROR_TRYAGAIN`.

**Comment by yamahata** [comment]
The current sgx_ocall adapts PAL error. But I don't see any good reason for PAL error, but Linux errno.

So I vote for sgx_ocall returning -errno.
It would also help future code consolidation of Pal-Linux and Pal-Linux-SGX.

**Comment by dimakuv** [comment]
I agree with @yamahata . I will close this issue and create a new one.
