### ISSUE TITLE
[LibOS] Missing support for readlink syscall

### ISSUE THREAD

**Issue by zhangckid** [oscarlab/graphene#516]
In WIKI page:
readlink
Symbolic links are not supported. Readlink will simply resolve absolute paths.

Graphene can't handle the readlink syscall, This makes it impossible to read any symbolic links inside Graphene. 
For example, APP want to get system status from /proc/self/exe (it is a symbolic link).  It will always return NULL.

**Comment by donporter** [comment]
Thanks for the issue report

**Comment by pwmarcz** [comment]
`readlink()` should work correctly now. Example from report  (using `python`):

```
$ graphene-direct python -c 'import os; print(os.readlink("/proc/self/exe"))'
/usr/bin/python3.8
```

Note that symlinks are (intentionally) not supported when mounting host files: host symlinks appear as normal files to the application.
