### ISSUE TITLE
[Linux-SGX PAL] Bug in multi-threading: Thread map not cleaned up

### ISSUE THREAD

**Issue by martinschmatz** [oscarlab/graphene#517]
Symptom: 
When using multi-threading, the program crashes as soon as threads are completed (start -> execute -> exit) more often than what is specified by sgx.thread_num in the manifest file. 

Bug: 
A thread registers itself via map_tcs(tid), but never un-registers via unmap_tcs(), hence resources remain blocked even after thread has exited.
 
Root cause: 
In file sgx_thread.c in Pal/src/host/Linux-SGX/ in static void * thread_start (void * arg) , a new thread registers itself via map_tcs(tid) before ecall_thread_start() is called. 
Once thread is complete (e.g. via syscall exit(0), which is intercepted by shim_do_exit(), the next code line unmap_tcs() should be executed to free claimed resources in enclave_thread_map.
However, the program never reaches this line. 

Potential fix: 
Make sure that the return address for an exiting thread is setup correctly (e.g. exit_target in handle_ecall([..] in enclave_ecalls.c ?? or the assembler code in enclave_entry.S ??) . 
Or clean up (including potentially polluted stack) via unmap_tcs() from e.g. _DkThreadExit.

**Comment by dimakuv** [comment]
Thanks for the bug report. Indeed, it is a known issue. We still need to work on the fix.

**Comment by yamahata** [comment]
Actually more resources are leaked.
new thread is created by pthread_create() as joinable thread.
So thread resource in glibc is leaked without pthread_join().
Even if a new thread is created as detached, thread should exit by pthread_exit().

**Comment by martinschmatz** [comment]
@yamahata: 
1) We tried with simple 
for(i=0; i<num_threads; i++)
   my_thread[i].join();
2) We also tried with:
std::thread::native_handle_type myhandle;
for(i=0; i<num_threads; i++)
{
   myhandle = my_thread[i].native_handle();
   my_thread[i].join();
   pthread_cancel(myhandle);
}
3) We tried with pthread_exit() as last line inside a thread. 

Same resource blocking effect by not reaching unmap_tcs() for all of the above.

**Comment by donporter** [comment]
Thanks for the report!  If you want to share your simple test program, that would be great!  PRs that address the issue are also welcome!

**Comment by martinschmatz** [comment]
Simple test program as requested ==> https://github.com/martinschmatz/GrapheneBugTest
See comment in manifest file related to sgx.thread_num. 
1) Build
2) Create signature and .sgx manifest via /graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-sign
3) Get token via /graphene/Pal/src/host/Linux-SGX/signer/pal-sgx-get-token
4) Launch via /graphene/Runtime/pal-Linux-SGX

**Comment by rainfld** [comment]
PR #641 Resolves this issue

**Comment by martinschmatz** [comment]
Many thanks! Looking forward to see the PR merged.
