### ISSUE TITLE
Bug in unmapping untrusted files

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#52]
In [db_files.c#L119](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L119) the `size` argument is calculated as `map_start - map_end`. Obviously, the size of the memory region is `map_end - map_start`, like it is calculated in [db_files.c#L125](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L125).

**Comment by chiache** [comment]
Thanks. I will fix this asap.

**Comment by mkow** [comment]
This was probably fixed long time ago, but the original reporter posted the links to `master` instead of the particular commit, so it's hard to say which places they wanted to mention. Anyways, I grepped the whole Linux-SGX/db_files.c for such an error pattern and didn't find any occurrence.
