### ISSUE TITLE
Linux-SGX file_read() TOCTTOU vulnerability

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#53]
I think the `file_read()` implementation in [Linux-SGX/db_files.c#L86](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L86) has a time-of-check-to-time-of-use vulnerability:

- In [L108](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L108) the target file is mapped to untrusted memory. 
- In `verify_trusted_file()` in [L114](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L114), the memory is verified using a CMAC. 
- If the verification was successful, the memory is copied in [L124](https://github.com/oscarlab/graphene/blob/master/Pal/src/host/Linux-SGX/db_files.c#L124).

Because the file is mapped to untrusted memory, the untrusted OS can modify the content of the memory after the verification and before the memory is copied.

Maybe I got this wrong, because I don't really understand your file verification process in the first place. First you try to verify the file with the SHA256 checksum in `load_trusted_file()` called by `file_open()`, generate a CMAC in `load_trusted_file()`, and then try to verify the CMAC in `file_read()`. Why the CMAC? 
Also, IIUC, `load_trusted_file()` operates on untrusted files. Why perform a check in `load_trusted_file()` in the first place, if the untrusted OS can modify the file afterwards?

**Comment by adombeck** [comment]
> The correct behavior is: load_trusted_file() is supposed to check the SHA256 checksum of the file and cache the chesksums of each block to prevent rehashing the whole file. Each time when a block is loaded into the enclave, its checksum must always be checked.

I don't see any checksum caching. I think you just calculate the AES CMAC over the whole memory in both `file_open()` and `file_read()`. I'm not sure if this makes sense if the only reason is performance.

**Comment by chiache** [comment]
1. We are no longer using AES CMAC to generate the file checksums. The initial checksum of a trusted file is a SHA256 digest. When the file is opened for the first time, each 16k block is loaded and hashed into a SHA512 digest. The SHA512 digests are cached in the enclave and checked against the content whenever reading from the file.

2. Besides the TOCTOU issue you described, I don't see why this strategy is insecure or meaningless. Would you care to elaborate why you think this design is problematic?

**Comment by adombeck** [comment]
> We are no longer using AES CMAC to generate the file checksums. The initial checksum of a trusted file is a SHA256 digest. When the file is opened for the first time, each 16k block is loaded and hashed into a SHA512 digest. The SHA512 digests are cached in the enclave and checked against the content whenever reading from the file.

Ah, turns out I was looking at old code.

> Besides the TOCTOU issue you described, I don't see why this strategy is insecure or meaningless. Would you care to elaborate why you think this design is problematic?

Ok, two things:

1. I think the verification in `file_open()` currently doesn't make any sense, because you only return a file handle. This is again a TOCTOU issue, the verification during `file_open()` doesn't tell you anything about the file content when it is being used. I think this is why you call the `verify_trusted_file()` in `file_read()`.

2. I don't understand why you would calculate a ~~AES CMAC~~ SHA512 digest in `file_open()` if you already have the SHA256 digest from the manifest and could just use this in `file_read()`.

**Comment by chiache** [comment]
The verification in `file_open` ensures the whole file is not tampered by the host. If the checksum does not matches with the manifest, `load_trusted_file` will reject the access.

Because we don't cache the whole file content in the enclave, whenever we read from a verified file, we must check whether the file content is tampered since opened. Reverify the whole file for just reading a part of the file will be a huge cost to pay. Therefore we generate a list of block checksums to support partial verification.

**Comment by adombeck** [comment]
Ok, I see now that the `file_read()` only verifies the part of the file that should be read, not the complete file, like I understood previously. This makes sense now and I think it should be secure if you also fix the TOCTOU in `load_trusted_file()` (i.e. copy `umem` to the enclave before calculating the SHA256 digest and the SHA512 digest).

**Comment by chiache** [comment]
You are absolutely right.
