### ISSUE TITLE
chroot_readdir doesn't set d_type properly for directories

### ISSUE THREAD

**Issue by omeg** [oscarlab/graphene#531]
Repro: mount/allow some directory with subdirectories in the manifest, do a readdir() and check d_type fields.
From what I can see, it seems that names received from PAL don't end in slashes which LibOS expects for directories.

**Comment by omeg** [comment]
It seems that `readdir()` on a Linux host does return `d_type` fields even if it's not technically required. Graphene only implements `d_type` fields in 64-bit version of the `linux_dirent` structure. The issue I'm encountering is a `sysconf(_SC_NPROCESSORS_CONF)` call which in turn tries to read `/sys/devices/system/cpu`. According to sysconf source it should use `readdir64`:

https://github.com/bminor/glibc/blob/glibc-2.19/sysdeps/unix/sysv/linux/getsysstats.c#L249

...but from testing it seems that normal `getdents` is called:

```
test: calling sysconf
[     1] ---- return from shim_write(...) = 14
[     1] > chroot_open 0xba23948
[     1] > __chroot_open 0xba23948
> dir_open /sys/devices/system/cpu
< dir_open /sys/devices/system/cpu = 0xbf583d0
[     1] < __chroot_open 0xba23948: pal hdl = 0xbf583d0
[     1] < chroot_open 0xba23948: shim hdl 0xba1c488
[     1] ---- shim_openat(AT_FDCWD,"/sys/devices/system/cpu",O_RDONLY|2204000,0000) = 3
[     1] > shim_do_getdents 3
```

`getdents` implementation doesn't return `d_type` fields and the `sysconf` call fails.

**Comment by omeg** [comment]
It seems that `sysconf` does in fact call `getdents` in the end. From `strace` log on the host:

```
write(1, "test: calling sysconf\n", 22test: calling sysconf
) = 22
open("/sys/devices/system/cpu", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFDIR|0755, st_size=0, ...}) = 0
getdents(3, /* 22 entries */, 32768)    = 656
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
```

**Comment by donporter** [comment]
Thanks for the report.  I think changing getdents to also include this information would be fine with me.

**Comment by omeg** [comment]
It seems that the `shim_dentry.type` field isn't correctly set for all cases currently. Fix incoming soon :)
