### ISSUE TITLE
clone06 is flaky

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#538]
`clone06` from LTP fails from time to time. The core issue seems to be the same as in #529.

Bash script for repro:
```Bash
for i in `seq 1 3000`; do
    echo "[$i]"
    ../../../../pal_loader clone06 || break
done
```

Example output, after running in `LibOS/shim/test/apps/ltp/opt/ltp/testcases/bin`:
```
[...]
[101]
WARNING: no physical memory support, process creation may be slow.
clone06     1  TBROK  :  clone06.c:81: read from pipe failed: errno=EINTR(4): Interrupted system call
clone06     2  TBROK  :  clone06.c:81: Remaining cases broken
```

**Comment by dimakuv** [comment]
For more info on the root cause, see https://github.com/oscarlab/graphene/issues/529#issuecomment-511065357

**Comment by mkow** [comment]
Seems to not reproduce anymore on the current master, closing (did 500 runs without any failure).
