### ISSUE TITLE
Format existing code according to code style

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#539]
I'm sure this already planned but I didn't find a ticket for it.

Automatic reformatting is very useful to get consistent code style without much work and discussions. But due to the big amount of not yet reformatted code the `make format` target is not very helpful at the moment (too many unrelated changes to filter out).

**Comment by mkow** [comment]
Yup, it's planned, but it's good to have a ticket for this. I'm waiting mostly for #385 to be merged to proceed with reformatting.
