### ISSUE TITLE
Drop SGX_HAS_FSGSBASE == 0 code paths

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#545]
AFAICS `SGX_HAS_FSGSBASE` has been hard coded to 1 since the initial SGX support. So it looks like nobody uses or tests the alternative code path.

Therefore I think it would be best to simply drop it and thereby make the code easier to read. If we really decide to add support for it we can still get it back from the git history.

Any objections?

**Comment by dimakuv** [comment]
+1. There was some historical reason for this flag (very first SGX versions didn't support FS/GS?) but it is redundant now. Especially SGX-specific assembly will be simplified.

**Comment by donporter** [comment]
I'm not even sure whether the original versions didn't have it.

Perhaps retain a comment that, on a CPU without this, one would need to add checks here?

Otherwise, this is probably fine.
