### ISSUE TITLE
TOCTOU bugs in ocall handling

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#549]
There seem to be multiple "time of check time of use" problems in the ocall handling code.

For example [ocall_map_untrusted](https://github.com/oscarlab/graphene/blob/fb48d0e388af6f89da61016f0bd62cf2bb693b36/Pal/src/host/Linux-SGX/enclave_ocalls.c#L136) checks the returned pointer directly in the struct in untrusted memory and later copies the pointer to trusted memory.

**Comment by dimakuv** [comment]
This is true (at least for `ocall_map_untrusted`).

Do you have a PR for this? If not, I can go through all such cases and submit a PR.

Is this only in `enclave_ocalls.c`?

**Comment by dimakuv** [comment]
After quick scan of the code, TOCTOU bugs are here:
* `ocall_alloc_untrusted`
* `ocall_map_untrusted`
* `ocall_sock_listen`
* `ocall_sock_accept`
* `ocall_sock_connect`
* `ocall_sock_recv`
* `ocall_sock_recv_fd`

**Comment by HW42** [comment]
No I did not work on this one yet. So if you want, feel free to go ahead.

**Comment by HW42** [comment]
> Is this only in `enclave_ocalls.c`?

This is where I noticed it while looking for something else.

**Comment by dimakuv** [comment]
Additional logic: Add an argument to COPY_FROM_USER() to check the size of the target memory (to protect against integer-overflow attacks).
