### ISSUE TITLE
OpenMP apps are not supported because libgomp.so executes a raw syscall instruction

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#567]
Libgomp (the library to support OpenMP) uses a raw `syscall` instruction to call futex() which is not supported by Graphene-SGX. (Graphene-SGX expects that apps and libraries never issue an actual `syscall` but instead must rely on glibc for that.)

This issue is very similar to this one: https://github.com/cloudius-systems/osv/issues/590

PR #561 adds support for syscall-instruction emulation. I have not yet tested OpenMP apps with this PR.

Simple test to reproduce an "Illegal instruction" failure in Graphene-SGX:
```c
/* build with: gcc -fopenmp openmp-test.c -o openmp-test */
#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

int v[10];

int main(void) {
#pragma omp parallel for
    for (int i=0; i<10; i++)
        v[i] = i;

    printf("first: %d, last: %d\n", v[0], v[9]);
    return 0;
}
```

**Comment by mkow** [comment]
Additional note: Blender also uses `#pragma omp`, which makes it fail on some scenes.
