### ISSUE TITLE
OOM error

### ISSUE THREAD

**Issue by AsierRF** [oscarlab/graphene#57]
Hello,

I am trying to run a quite big c++ program with Graphene in SGX and the program seems to start working, until it reaches the following error:

>  Fatal process OOM in heap setup
[    1] ---- return from shim_write(...) = 40

I think it is Out Of Memory error and I tried changing the values of the following lines in the manifest to up to 4 times their original value without any success:
sgx.enclave_size=[SIZE]
sys.stack.size=[# of bytes]
sys.brk.size=[# of bytes]

Any help will be welcome :)

**Comment by AsierRF** [comment]
Hello,

I found out that the error is generated because I the program is trying to get memory from outside the heap in the "get_reserved_pages" function in the file "./Pal/src/host/Linux-SGX/enclave_pages.c" because this if "if (addr >= heap_base + heap_size) " is returning true.

So, I understand I need a bigger heap for my program. However, I have no idea how. I tried the following configuration values with no success:
sgx.enclave_size=[SIZE]
sys.stack.size=[# of bytes]
sys.brk.size=[# of bytes]
sgx.heap_min=[# of bytes]

I tracked the heap_base and heap_size values to the file "./Pal/src/host/Linux-SGX/sgx_main.c" but I still don't know how I can configure them to be bigger. If that is possible.

I feel that I am really close to making a big step in my project, so I would really appreciate some help.

Thanks in advance.

**Comment by rainfld** [comment]
The heap size is the enclave pages left after the stack and other parts of the enclave (SSA, TLS, binary, etc) were allocated. So essentially it may be helpful to maximize the enclave size and minimum the stack size. Then you will get a bigger heap
