### ISSUE TITLE
[PAL/SGX] file_attrquery hangs if called on a named pipe

### ISSUE THREAD

**Issue by omeg** [oscarlab/graphene#570]
SGX's `file_attrquery` implementation tries to open the given file and then calls `fstat`, in contrast to Linux-PAL which just calls `stat`. This causes unintended consequences on special files like named pipes (`open` blocks by default in such case until the other end is connected).

**Comment by dimakuv** [comment]
The reason why SGX PAL does *not* perform `stat()` is because Graphene-SGX tries to use the minimum set of syscalls to the underlying host OS. SGX PAL only has `ocall_fstat()`. Introducing an new `ocall_stat()` would increase the attack surface.

Do you think there is a way to special-case named pipes so that SGX PAL still uses the combination of `open() + fstat()`?

**Comment by omeg** [comment]
I'm not sure it's possible since even if opening the pipe succeeds it can have unintended side effects. Say, process A and process B use this pipe for communication. Process A opens the pipe which blocks until process B also opens it. If some unrelated process running in Graphene tries to open the pipe, the A-B communication is possibly disrupted.

Also, simple repro code:

```
#include <stdio.h>
#include <sys/stat.h>

int main(int argc, char *argv[])
{
    struct stat s;
    int rv = stat(argv[1], &s);
    printf("test: stat = %d\n", rv);
    return rv;
}
```

Create a pipe by `mkfifo test_pipe` in the shell, then run the above program with the pipe name as argument.

**Comment by dimakuv** [comment]
Ok, I understand the issue now.

This is a peculiar behavior of `open()`. See a related SO question and comments here: https://stackoverflow.com/questions/5782279/why-does-a-read-only-open-of-a-named-pipe-block .

A simple (and hopefully sufficient) workaround for this particular issue would be to call `ocall_open()` with `O_NONBLOCK` inside `file_attrquery()`. We don't even need to special-case named pipes because `O_NONBLOCK` will be silently ignored by the host Linux for normal kinds of files.

**Comment by pwmarcz** [comment]
Seems to be fixed by 13bd8c6e85f2f803d19f29079cf8fea5b5c5d5f7.

**Comment by dimakuv** [comment]
Pawel will look at it again, but just in case, I'm assigning this bug Priority 1 (if this bug is still there).

**Comment by pwmarcz** [comment]
Okay... looks like right now we don't support host-level named pipes (only emulated ones, created with `mknod` from inside Graphene).

Unfortunately trying to access a "real" named pipe, mounted from outside triggers a `BUG()` - I think they worked "by accident" before and were exposed as regular files...

I would like to fix that, but does it make sense? Should Graphene have both emulated named pipes, and host-level ones?

**Comment by mkow** [comment]
Hmm, no idea. If we don't rely on this functionality in LibOS then just doing `BUG()` if someone (i.e. LibOS developer) actually tries to do this sounds reasonable and it may actually catch some bugs in LibOS where we accidentally access some pipes not created by us.

**Comment by dimakuv** [comment]
> I would like to fix that, but does it make sense? Should Graphene have both emulated named pipes, and host-level ones?

I would say that we shouldn't support this case. Named pipes (`mknod(S_IFIFO)`) sit somewhere between regular pipes (`pipe()`) and UNIX domain sockets (`socketpair()`). Both regular pipes and UNIX domain sockets can only be created inside Graphene. Also, both are transparently encrypted.

So we should follow this pattern: allow named pipes only between related Graphene processes and always encrypt them. Note that the encryption part is already there for `mknod(S_IFIFO)` (see `shim_pipe.c`).

**Comment by dimakuv** [comment]
But throwing a `BUG()` is wrong. We should catch this case (app trying to open an "unknown", host level named pipe) and report an error like `Graphene cannot work with host-level named pipes (only named pipes created between related Graphene processes)`. Something like this.

Ideally, we should also check named UNIX domain sockets, and report a similar error. I guess right now UNIX domain sockets also trigger a `BUG()`.

**Comment by pwmarcz** [comment]
So, to sum up: the reported bug in `file_attrquery` is fixed by 13bd8c6e85f2f803d19f29079cf8fea5b5c5d5f7 (it now opens the file with `O_NONBLOCK`); I also verified manually that it works.

However, accessing a host named pipe also triggers a `BUG()` in LibOS, which I'm fixing in #2592.

**Comment by pwmarcz** [comment]
>Ideally, we should also check named UNIX domain sockets, and report a similar error. I guess right now UNIX domain sockets also trigger a BUG().

Apparently PAL exposes such sockets as `pal_type_dev` and Graphene is happy to report them to user as character devices...

**Comment by mkow** [comment]
Ah, I thought this `BUG()` can only be triggered by modifying LibOS code, then `BUG()` is perfectly fine. If it's reachable from the user app then it should be fixed to not allow this.

**Comment by dimakuv** [comment]
>> Ideally, we should also check named UNIX domain sockets, and report a similar error. I guess right now UNIX domain sockets also trigger a BUG().

> Apparently PAL exposes such sockets as `pal_type_dev` and Graphene is happy to report them to user as character devices...

Is this meaningful? Sounds like a totally wrong thing to do. Anyway, this is not relevant to this particular issue.
