### ISSUE TITLE
Consider deprecating the `glibc.heap_size` option

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#623]
This ugly hack for glibc heap (arena) allocation logic should be abolished or at least rewritten. I will try to propose a better design within the next few weeks.

https://github.com/oscarlab/graphene/blob/0849296a02565b89b43559768f8688a19cfc9185/LibOS/glibc-2.19.patch#L681-L726

**Comment by dimakuv** [comment]
What was the point of this hack?

**Comment by dimakuv** [comment]
This is clearly not needed as my experiments show: https://github.com/oscarlab/graphene/pull/1369.

The PR #1369 removes this hack completely and will close this issue.
