### ISSUE TITLE
[Pal/Linux-SGX] On OCALL return, restrict possibly malicious return value to sane values

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#634]
As part of OCALL hardening, on OCALL return, we must verify and restrict possibly malicious return value. In most cases, we should add checks on permissible error values.

The PR for this issue will depend on #554 -- it changes error codes from PAL codes to normal POSIX syscall error codes.

Special case OCALLs:
* CPUID: should check meaningful bit & leaf combinations?

**Comment by yamahata** [comment]
It sounds good hardening.
In long term, we'd like to consolidate Pal/Linux and Pal/Linux-SGX, such checks of ocall return value should be contained enclave_ocall.c
Just my 2 cents.

**Comment by dimakuv** [comment]
Yes, the idea is to contain these checks in `enclave_ocall.c`
