### ISSUE TITLE
Review exception handling for proper handling of nesting

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#637]
While looking at a problem with nested exceptions @yamahata pointed out in my PR #625, I noticed that the exception/resume handling in `enclave_entry.S` looks broken:

 - We use `%gs:SGX_GPR`, which AFAICS always points to the first SSA frame. But that's wrong if we get interrupted again here, no?
 - `.Lhandle_exception` falls back to `%gs:SGX_STACK` if it's not 0. This logic also doesn't work if we nest this code, I think.

Maybe @yamahata's PR #632 fixes this already, I hadn't time yet to look at it enough. Opening this ticket anyway to keep track of it.

**Comment by dimakuv** [comment]
> We use `%gs:SGX_GPR`, which AFAICS always points to the first SSA frame. But that's wrong if we get interrupted again here, no?

Yes, I think we allow this currently, and it can break our logic.

The simple solution is to:
* At the untrusted host OS level, block delivering signals during signal handling (change `sigaction.sa_mask` in `sgx_exception.c`). This prevents nested signal handling at the host OS level.
* Since we cannot trust OS, we should double-check that `CurrentSSA == 1` in `.Lhandle_resume` in `enclave_entry.S` and go into infinite loop, for example.

This would prevent the case of "host-induced" nested signal handling. Notice that we correctly *emulate* nested signal handling at the LibOS level (well, we will at some point when we merge Isaku's patches).

**Comment by yamahata** [comment]
regarding %gs:SGX_GPR. please see https://github.com/oscarlab/graphene/pull/639
regarding to %gs:SGX_STACK, #632 addresses it. concretely, https://github.com/oscarlab/graphene/pull/632/commits/206c5fcdb66cb0966bf7e11d7ce5cfad33d3b273

I think we need to split #632 into smaller part to merge step by step.

**Comment by dimakuv** [comment]
Cool, thanks for #639!

**Comment by dimakuv** [comment]
Yes, #632 should be split. Some commits are already pushed as separate PRs (see https://github.com/oscarlab/graphene/pull/632#pullrequestreview-229306570). I also suggest to rename this PR to "[RFC] Use dedicated stack..." so that it is obvious it is not a PR-to-merge but an overview patch.

**Comment by yamahata** [comment]
regarding to %gs:SGX_STACK, I uploaded the below for review.
https://github.com/oscarlab/graphene/pull/640

**Comment by yamahata** [comment]
updated #632 message.

**Comment by HW42** [comment]
While looking at PR #639 I noticed that at the moment this is not necessary. We set NSSA to 2 (which will be properly signed once PR #573 is merged). Since EENTER enforces CSSA < NSSA (and the exception code is only reached if CSSA != 0), currently it's already guaranteed that CSSA == 1.

Of course if there's a reason in the future to extend NSSA we need this check. Not sure how likely this is.

**Comment by dimakuv** [comment]
@HW42, we still need PR #639 to suppress signals at host-OS PAL layer (see `Pal/src/host/Linux-SGX/sgx_exception.c` in that PR). I agree that the `FAIL_LOOP` precaution may be an overkill, but why not have this additional defense? As you mention, NSSA may change in the future, and your assumption will break.

**Comment by HW42** [comment]
> @HW42, we still need PR #639 to suppress signals at host-OS PAL layer (see `Pal/src/host/Linux-SGX/sgx_exception.c` in that PR).

Yes, I should have been more explicit that I only meant the CSSA == 1 check.

> I agree that the `FAIL_LOOP` precaution may be an overkill, but why not have this additional defense?

I'm fine with adding the assert. I highlighted the point above because when I opened this issue I thought that this is a bug (probably with security implications) but then realized that CSSA is already guaranteed to be 1.

> As you mention, NSSA may change in the future, and your assumption will break.

Yeah, although I'm not sure that it's likely to have a reason for NSSA > 2, which doesn't also need a significant rework of the exception handling code.

**Comment by dimakuv** [comment]
Closing since the specific issue is resolved (by relying on `SECS.NSSA == 2`, validated by the SGX hardware), and since Borys created a new meta-issue #2533.
