### ISSUE TITLE
Add network shield

### ISSUE THREAD

**Issue by adombeck** [oscarlab/graphene#64]
If I understand correctly, currently the only secure channel available for enclaves is System V message queues. It would be very useful if authenticated enclaves could also use sockets for secure communication. 

I want this feature because I'm currently working on a remote attestation solution for existing applications, and one problem I'm facing is the creation of a secure channel between the remote party and the existing application after a successful remote attestation. A generic solution would be to use a wrapper application which performs the remote attestation and then forwards the connection to the existing application. But this requires a secure communication between two sockets protected from the host OS.

This would also allow to secure applications which do not have built-in application layer encryption, similarly to SCONE's network shield.

**Comment by dimakuv** [comment]
Adding some context here, in case people stumble on this issue.

The “Network Shield” automatically wraps all TCP/IP connections with TLS (and then adds RA-TLS functionality to these TLS connections to automatically perform SGX remote attestation). SCONE implements it, though I'm not familiar with the details and the completeness of this feature.
 
There was actually some research on this front in Graphene, but it was never finalized and open-sourced. The main issue is: the way people write TCP code is quite different from the way people write TLS code. So the Network Shield may work in simple cases, but as soon as you start to dig deeper, simple “TLS wrappers around TCP” break semantics and original application code. One example: adding TLS to Redis took ages, and it took another 20+ PRs to fix its bugs (https://github.com/redis/redis/pull/6236). 

There is currently no active development effort for the Network Shield in Graphene, and I doubt there will be. We of course welcome contributions but I don’t think any of the core developers will implement this any time soon. From a “minimal viable product” perspective it’s pretty simple but then you get into corner cases and things get ugly quick.

The correct solution as I see it as follows. All modern applications support TLS, so you should build your Graphene/SGX environment on top of this TLS support. *RA-TLS* and *Secret Provisioning* of Graphene were specifically designed to add SGX attestation functionality on top of TLS. For more info on RA-TLS and Secret Provisioning see:
- https://graphene.readthedocs.io/en/latest/tutorials/pytorch/index.html (end-to-end example)
- https://github.com/oscarlab/graphene/tree/master/Pal/src/host/Linux-SGX/tools (see README and source code / headers)
- https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-mbedtls (RA-TLS examples)
https://github.com/oscarlab/graphene/tree/master/Examples/ra-tls-secret-prov (secret provisioning examples)

**Comment by mkow** [comment]
Currently we don't plan to implement network shielding (see the comment above), closing.
