### ISSUE TITLE
Issue with calling getsockopt before bind

### ISSUE THREAD

**Issue by dxoigmn** [oscarlab/graphene#644]
I am debugging in an issue with gRPC which calls `getsockopt` before `bind` (see https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_server_utils_posix_common.cc#L165). When I run this program in Graphene, `getsockopt` fails because a `pal_handle` isn't assigned until `bind` is called. It seems like a `pal_handle` should be assigned earlier when `socket` is called. Below is a minimal test case.

```
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <netinet/ip.h>
#include <unistd.h>
#include <assert.h>

int main(int argc, char **argv)
{
    int fd, ret, flags = 1;
    socklen_t len = sizeof(flags);

    fd = socket(AF_INET, SOCK_STREAM, IPPROTO_IP);
    ret = getsockopt(fd, SOL_TCP, TCP_NODELAY, (void *)&flags, &len);
    close(fd);

    assert(ret == 0);

    return ret;
}
```

**Comment by dimakuv** [comment]
After six months of procrastinating, time to debug this :)

**Comment by msheller** [comment]
Just a note: I've been able to get gRPC working with the following hacks:

Calling set/getsockopt AFTER bind/connect
Calling epoll_ctl AFTER connect

Without the additional epoll_ctl call, the client socket never gets the server responses. I'm going to try @dimakuv 's suggestion of removing the pal_handle nullptr check in the epoll_ctl shim.

**Comment by msheller** [comment]
Removing the pal_handle null ptr lead to a core dump:

assert failed ../../../Pal/lib/slabmgr.h:456 *m == SLAB_CANARY_STRING
Trace/breakpoint trap (core dumped)

I'm going to stick with my epoll hack in grpc for the time being. Let me know if I should open an issue on this (I don't have an easy test case like Mr. Radiohead above (dxiosifgfmsnfmgafh).

**Comment by dimakuv** [comment]
@dxoigmn @msheller https://github.com/oscarlab/graphene/pull/1257 fixes this issue.
