### ISSUE TITLE
pal_sec.instance_id and pal_sec.mcast_port are untrusted

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#647]
The fields `pal_sec.instance_id` and `pal_sec.mcast_port` are initialized to random values during enclave initialization. Since they are initialized in untrusted code, the attacker can try to launch an attack using them.

`pal_sec.instance_id` is used to create a named pipe associated with a Graphene-SGX process. Later, `instance_id` is used to populate the string `pal_sec.pipe_prefix` which is used as the socket address on which Graphene-SGX performs IPC.

`pal_sec.mcast_port` is used to perform multicast IPC (e.g., from parent to notify all child processes).

Two open issues:
1. Is it possible to construct an attack if the attacker can e.g. create two instances of an enclave with the same `instance_id`/`mcast_port`?
2. Is it possible to initialize or verify these values *inside* of the enclave?

@HW42, since you worked on moving other `pal_sec` fields inside of enclave, do you have any comments about this? From my perspective, since all IPC requires enclaves to first SGX-attest each other, the attacker cannot do anything interesting with these two fields.

**Comment by HW42** [comment]
`mcast_port` looks harmless to me since this is something which the urts can mess with anyway (it should just be an argument to the ipc ocall).

For `pal_sec.pipe_prefix` the same should hold (although for strings there's a risk that it will be inserted into some trusted context (e.g. a log) without proper sanitization).

`instance_id` sound prone to be used without having in mind that it's untrusted. AFAICS the only appearance is in `Par/src/db_rtld.c` but that part is disabled by ifdef. So it's not directly a problem, but sounds fragile. Why do we have instance_id in the first place?

**Comment by dimakuv** [comment]
@HW42 is right, I got confused by this code snippet:
```c
// src/host/Linux-SGX/sgx_main.c
static void create_instance (struct pal_sec * pal_sec) {
    unsigned int id;
    getrand(&id, sizeof(id));
    snprintf(pal_sec->pipe_prefix, sizeof(pal_sec->pipe_prefix),
             "/graphene/%x/", id);
    pal_sec->instance_id = id;
}
```

`pal_sec.instance_id` and `pal_sec.pipe_prefix` are both initialized using the same untrusted random `id`. But they do not depend on each other. Therefore, `pal_sec.instance_id` is basically not used inside of enclave (because `Pal/src/db_rtld.c` code is not compiled due to `CACHE_LOADED_BINARIES = 0`). And `pal_sec.pipe_prefix` is harmless (with the caveat of no-sanitization).

**Comment by HW42** [comment]
How about dropping `instance_id` from `pal_sec`. And just generate a random value for `pal_main` inside the enclave? Or since it's never used maybe also drop instance_id from the generic PAL code?

**Comment by mkow** [comment]
The first solution sounds good.
@chiache: Any reason this could be a bad idea?

**Comment by dimakuv** [comment]
I vote for removing `instance_id` completely.

I guess first we need to figure out if `Pal/src/db_rtld.c` dead code (due to `CACHE_LOADED_BINARIES = 0`) can be removed alltogether. What was the point of this code?

**Comment by yamahata** [comment]
regarding to pipe_prefix, mkdtemp(3) or similar should be used.

**Comment by mkow** [comment]
> I guess first we need to figure out if Pal/src/db_rtld.c dead code (due to CACHE_LOADED_BINARIES = 0) can be removed alltogether. What was the point of this code?

As usual, I guess @chiache probably knows ;)

**Comment by dimakuv** [comment]
Note from Chia-Che:

> The process id is supposed to be inherited from parent processes; in other words, process that starts with the same `pal_loader` command will be in the same guest environment; otherwise they should not share any guest-level abstraction, including the unix domain socket.

> Notice that the idea of Graphene is to simplify the implementation of namespacing. We simply want to isolate processes that are mutually irrelevant. So there is no individual namespace id, only what we call "instance id". If you run the [Unix domain socket] server and the client in different guest environments, they shouldn't see each other. Think about running two programs in two virtual machines.

**Comment by dimakuv** [comment]
`mcast_port` was removed long time ago.

`instance_id` is populated inside the enclave now (very recent change by Borys): https://github.com/oscarlab/graphene/blob/4cb98219d8e302055587a8952c1102415a72ba42/Pal/src/db_main.c#L276-L282

So the issue can be closed.
