### ISSUE TITLE
[LibOS] syscalldb function doesn't preserve rflags. linux syscall does.

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#661]
Linux syscall preserves rflags. On the other hand, libos syscalldb doesn't.
It should be fixed.
https://github.com/oscarlab/graphene/pull/561
raises this issue.
#660 is first step to fix it. more patches are needed.
#428 
and then after that clone child issue can be addressed.

**Comment by mkow** [comment]
Relevant discussion thread: https://reviewable.io/reviews/oscarlab/graphene/561#-LdR7pNE37gdW3jTa-f9

**Comment by mkow** [comment]
Seems this is already fixed on current master, closing.
