### ISSUE TITLE
PAL/LibOS think BYTE_ORDER is BIG_ENDIAN

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#677]
`Pal/lib/network/hton.c` (and perhaps others) think that `BYTE_ORDER` is `BIG_ENDIAN` for Linux-SGX.

**Comment by dimakuv** [comment]
This is bizarre. Is there a simple test case to verify that? By looking at the code, I see no reason for Graphene to assume `BIG_ENDIAN` byte order.

**Comment by smherwig** [comment]
Just add a `#error` to `Pal/lib/network/hton.c`, as in

```
uint32_t __htonl (uint32_t)
{
#if BYTE_ORDER == BIG_ENDIAN
# error "Graphene thinks BYTE_ORDER is BIG_ENDIAN!"
    return x
#elif BYTE_RODDER == LITTLE_ENDIAN
    return __bswap_32 (x);
#else
# error "What kind of system is this?"
#endif
}
```

I'm calling the `DkStreamOpen` from within one of by filesystem, which is how I notice it.  You would never notice this from an application packing a socket address, as the `shim_socket.c` will call `__htons`, and then, in the PAL `db_sockets.c` will call it again, effectively undoing the change.

**Comment by dimakuv** [comment]
I'm not sure where the macro `BYTE_ORDER` comes from. Can you replace it with `__BYTE_ORDER` (with two underscores as prefix) and check again on your application?

**Comment by dimakuv** [comment]
Ok, so `__BYTE_ORDER` returns correct values. Interesting, `BYTE_ORDER` is something weird... I will submit a PR to fix this.

**Comment by dimakuv** [comment]
Here is the new PR: https://github.com/oscarlab/graphene/pull/679

If you're Ok with these changes, please approve with `LGTM`. Also, if you can construct a simple regression test, post it either here or in the PR page.
