### ISSUE TITLE
[LibOS] eventfd2 enabled?

### ISSUE THREAD

**Issue by martinschmatz** [oscarlab/graphene#678]
Symptom: I'm getting an error EINVAL (Invalid argument) when calling eventfd(count, flags). 

Context: eventfd.c (in ./LibOS/glibc-2.19/sysdeps/unix/sysv/linux) checks for the define of __NR_eventfd2. If defined, the call is actually routed to the eventfd2 syscall, which is intercepted via SHIM_SYSCALL_PASSTHROUGH (eventfd2, 2, int, int, count, int, flags) in file ./LibOS.shim/src/shim_syscall.c. Hence the call to eventfd(count, flags) is passed on to the kernel using eventfd2. This is what we'd expect to happen. 

Issue: The observed error can only happen, if neither __NR_eventfd2 nor __ASSUME_EVENTFD2 are defined - from which we can conclude that eventfd2 is not enabled even though readily available.

Question: Is __NR_eventfd2 defined during GLIBC build? Asked differently, shouldn't __NR_eventfd2 be defined and __ASSUME_EVENTFD2 remain undefined during build of GLIBC? Sorry, with the complex makefile setup, I wasn't yet able to pinpoint a location to do this.

**Comment by donporter** [comment]
I think the potential misunderstanding is PASSTHROUGH does not actually passthrough to the host - this is a vestige of the very, very early days of the project.  It should be returning -ENOSYS on this particular call.

I'm more surprised to see the -EINVAL rather than a -ENOSYS.

**Comment by martinschmatz** [comment]
Hmm - are you saying that eventfd(count, flags) is actually not supported by Graphene?

**Comment by donporter** [comment]
Yes, I believe this is the case.

**Comment by dimakuv** [comment]
`eventfd()` is not supported by Graphene.

Yes, the name `SHIM_SYSCALL_PASSTHROUGH` is unfortunate. I just checked `LibOS/shim/include/shim_internal.h`, and this macro calls `DO_SYSCALL_{0,1,2..6}` -- all of which return `-ENOSYS`. So raw syscall `eventfd()` must actually return `-ENOSYS`. It is probable that your Glibc wrapper transforms this error code into `-EINVAL` (which I'm lazy to check now).

**Comment by martinschmatz** [comment]
I wanted to dig deeper and cloned/built/installed Graphene freshly today (the version which caused the eventfd error described above is ~4 weeks old). 
Now I'm getting - already during the enclave initialization phase of my application - the error "shim_init() in init_randgen (-13)"
So I now need to clean this first before I can look deeper in a solution for an event-based multi-threaded HTTPS server....

**Comment by dimakuv** [comment]
Interesting error. This error happens even before running your application. Probably you need to perform a comprehensive `make SGX=1 clean`. Please post a bug report with a log if you can't resolve this bug by yourself.

**Comment by martinschmatz** [comment]
It's indeed an 'interesting' error: While it's easy to find the place where the error message is generated (RUN_INIT(func, ...) macro in shim_init.c), I can't find any occurrence of the trouble causing function 'init_randgen' in the entire Graphene code base.
I already did a complete fresh installation cycle. I also re-installed the Intel SGX stuff, just in case. 
I can now reproduce the situation that with a Graphene version which, based on file dates, was cloned from master branch on March 8, there is no such error, while with the fresh install from yesterday, the above described issue shows up during initialization of the enclave. 
I'll try a couple of things, and if not successful will post a new issue.

**Comment by martinschmatz** [comment]
OK, found the issue: The old installation was in a directory ../graphene, while I've put the new installation in ../graphene2. 
But I forgot to change the manifest file, so that the trusted files in the manifest file still pointed to the old directory.
I quickly corrected all relevant paths in my manifest file to 'graphene2'. Now I'm back at the lack-of-support-for-eventfd issue and can start to evaluate an alternative for it.

**Comment by martinschmatz** [comment]
So, back to the eventfd issue: Luckily, the friendly folks over in h2o-land (https://github.com/h2o/h2o) provided an alternative using pipes in stead of eventfd. 

==> After changing the event loop in h2o from using eventfd to using pipes, my multi-threaded h2o HTTP2/TLS1.3 server prototype now shows life inside an enclave on an Ubuntu18.04LTS server, even including a libcurl based client in case there's a need for funneling a service request further upstream. 

Remarks: I had to build OpenSSL (v1.1.1c, with enable-tls1_3 option) on an Ubuntu 14.04 to avoid a GLIBC2.25 issue in libcrypto. I also built libcurl using './configure --with-nghttp2=/usr/local', which implies that I obviously also built nghttp2. I linked libh2o, libnghttp2, libcurl & libz statically, and libssl & libcrypto dynamically; former libs are built on Ubuntu18.04, the latter on Ubuntu14.04. Maybe this remark can help others.

I still have to do more in-depth tests and also assess the performance, but at least I have a working code skeleton for a micro-service inside an enclave. Thanks!

A final question: Is the lack of support for eventfd due to a security concern, or is it just not implemented yet? 
Pending the answer to the above, this issue can either be marked 'closed' or should be marked 'enhancement', 'feature request' or similar.

**Comment by dimakuv** [comment]
@martinschmatz, thank you for a detailed description!

`eventfd()` is a missing feature. There is some internal work on adding this, hopefully we'll merge it into mainline in a not so distant future.

Would you mind telling more about your experiences with Ubuntu 18.04 and particularly with the newer version of Glibc? Also, did you try debugging with our gdb (`GDB=1 SGX=1 ./pal_loader <my-executable>`) under Ubuntu 18.04? I am trying to figure out the issues with Glibc 2.19 (inside of Graphene's enclave) and the host Glibc (2.23 in Ubuntu 16.04 and 2.27 in Ubuntu 18.04 -- and they seem to be incompatible in non-trivial ways).

**Comment by martinschmatz** [comment]
Experience with Ubuntu18.04: 

- Installation (both of the Intel SGX as well as Graphene): Very smooth. 

- Running examples: Most worked right out of the box, some refused to compile due to more stringent checks (read: some warnings become errors) on the newest gcc framework. I didn't try to resolve these issues, because I didn't want to invest to much time in the examples.

- Building an application: Here, the issues start. When compiling open-source packages (and other home-grown applications), the compiler/linker framework uses the newest versions of the libraries that are available. Most of the time, a GLIBC version <=2.19 is used, but occasionally, a GLIBC version >2.19 is required for linking. ldd -v helps to establish the actual situation. 
There are then two ways to handle the case of a >2.19 requirement: (1) Static linking, (2) explicitly specifying a version of the shared library which was built on a system that has only up to GLIBC2.19. Hence my strategy is to use static linking as often I can (consciously paying the price in terms of code size), or build the shared libraries on Ubuntu14.04. For the latter, I upgraded an Ubuntu14.04 server with a sufficiently recent gcc environment (7.4.0 in my case, but might depend on what a contemporary open source package needs, in particular which c++ version [11,14,17,..] the package needs). It goes without say that the custom code that will sit on top of and make use of the open-source packages needs to be written such that no GLIBC>2.19 is required. 
Unfortunately, even with the above mitigation principle, there are packages (one example I experienced is Proxygen) for which I wasn't able to build it on Ubuntu14.04, and for which many >2.19 GLIBC calls exist when built on Ubuntu18.04. And Proxygen for example is using a gazzillion of libraries, for which I wasn't able to establish a working mix of static and dynamic linking. 
Hence, rather then resolving the build process of most-modern packages on Ubuntu14.04, I decided do search for packages for which I was able to handle the issues with the above described strategy. This is how I ended up using h2o and cURL for my task at hand, which is to build an intelligent reverse proxy running inside an enclave. The term "intelligent' implies number crunching on the HTTP data payload (both upstream as well as downstream) that goes way beyond reg-ex capabilities. Event based multi-threading, HTTP2 and TLS1.3 were the requirements which only h2o/cURL were fulfilling (at least within the search space I covered). 
- Use of debugging with Graphene gdb: So far, I didn't triy that out, hence I can't comment. The only thing I can add here is that I'm not using the pal-loader approach, but the "triple step" to do launch an application inside Graphene enclave ("triple step" = pal-sgx-sign -> pal-sgx-get-token -> pal-Linux-SGX).

- If it were Christmas: Having GLIBCv2.27(+) with the vast majority of system calls handled in the the shim as a Christmas present would be great and super helpful. As time goes by, I'd anticipate the issues with GLIBC incompatibility to grow, potentially to a point where the current GLIBC2.19 plus "tricks" described above doesn't cut it anymore - at which point Graphene becomes obsolete. I guess many people out there (including myself) are, for the better or worse, bound to use the latest LTS Ubuntu version for many reasons...

I hope the above addresses your questions. If not, feel free to append.

**Comment by martinschmatz** [comment]
Just in case this is useful for somebody, here a link to a couple of snippets I'm using during the build/installation process of various packages: https://gist.github.com/martinschmatz

Disclaimers: 
- The snippets might or might not be complete, in particular when it comes to prerequisites (e.g. having a recent CMake environment available is deemed a given). 
- The snippets might or might not work in your environment; they are just straight copies from a collection of snippets that I have in my personal repository. They nevertheless help me to execute a fresh install of what I need in case I want/need to start from scratch.

**Comment by dimakuv** [comment]
Nice, thank you for the detailed reply!

I guess sufficiently many people (including me) complain about the ancient Glibc version we use internally in Graphene, such that it's high time to upgrade to a newer version.

The situation with supporting syscalls is more complicated. There are just too many of them, some require non-trivial emulation (like eventfd). But yes, we're working on your Christmas present :)

**Comment by donporter** [comment]
Indeed, thank you! I agree that a newer glibc is going to be a growing pain point.  There are some changes going in that are making this easier to patch future versions, but I think we should raise the priority here.
