### ISSUE TITLE
[GDB] Debugging apps under Glibc 2.27 is broken

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#682]
It is impossible to debug applications on host systems which uses Glibc >2.23, e.g., Ubutnu 18.04 which uses Glibc 2.27. While trying to debug via `GDB=1 ./pal_loader <some-binary>`, the user sees this error:
```
[New Thread 0x7f56df6c4700 (LWP 5402)]
add symbol table from file "../../../../Runtime/libc.so.6" at
... loading symbols ...
thread_get_info_callback: cannot get thread info: generic error
```

The root cause is tricky. For the discussion below, check some resources on libthread_db.so threads debugging support:
* http://timetobleed.com/notes-about-an-odd-esoteric-yet-incredibly-useful-library-libthread_db/
* https://docs.oracle.com/cd/E19455-01/806-0630/6j9vkb8dk/index.html
* https://sourceware.org/gdb/onlinedocs/gdb/Threads.html (see discussion of libthread_db)
* https://fossies.org/linux/gdb/gdb/linux-thread-db.c (source code of libthread_db.so)
* https://stackoverflow.com/questions/10840621/gdb-cannot-find-new-threads-generic-error-after-system-update

So, Graphene has a complete Glibc shared lib which the shielded app uses. The only currently supported version of this "internal" Glibc is 2.19. Any app-to-put-inside-Graphene must work with this version (that's why sometimes apps need to be "downgraded" from newer Glibc to our 2.19, e.g. #179).

Glibc is a collection of shared libraries. libpthread.so is part of Glibc libraries and is used by multi-threaded apps. Now the tricky part: there is another helper library called libthread_db.so. It is also part of Glibc libraries and is used by debuggers, in particular GDB, to have more control over debugged multi-threaded apps. GDB loads this helper library by default, and (in my experience) it is impossible to debug multi-threaded apps without this library (I got GDB internal errors).

libpthread.so and libthread_db.so always go together. Matching libthread_db.so v2.27 with libpthread.so v2.19 leads to the aforementioned error.

These two libs interact in their own internal ways. In particular, libpthread updated internal thread structures which are used by libthread_db to learn about app's threads. This internal thread structs change from Glibc version to Glibc version; this is the reason their versions must match.

What happens in Graphene under GDB is as follows:
1. PAL executable (the "Graphene" executable) is built against the host Glibc. In case of Ubuntu 18.04, it is Glibc 2.27.
2. GDB looks at the PAL executable, notices it is built against Glibc v2.27 and loads the corresponding libthread_db.so v2.27. Now GDB will use libthread_db.so v2.27 for all thread-related communication with Graphene and its internal app.
3. PAL executable at some point loads libsysdb.so (LibOS layer), app binary itself, ld-linux.so ("internal" loader), and libc.so ("internal" Glibc). Of interest for us is libc.so -- as it initializes, it tries to inform libthread_db.so of its internal thread structures (because this is the "internal" Glibc version).
4. The loaded libthread_db.so is of v2.27, so libc.so v2.19 sends it incorrect format of thread structures. This results in the above error.

Notice how the flow didn't even get to libpthread.so loading and stopped already at libc.so.

P.S. An interesting fact: Ubuntu 16.04 uses Glibc 2.23. We are lucky that Glibc 2.19 and 2.23 have the same format of internal thread structures. This is why GDB works under Ubuntu 16.04.

**Comment by dimakuv** [comment]
Solutions to this debugging issue:

1. (BROKEN) Force GDB to use libthread_db.so v2.19 on Ubuntu 18.04. Though it is trivial to do so (use `set libthread-db-search-path <path-to-graphene-runtime>`), it breaks because the PAL Graphene executable breaks then -- since it is built against the host Glibc v2.27, libthread_db.so freaks out and fails with error.

2. (BREAKS COMPATIBILITY) Update "internal" Glibc in Graphene to v2.27. This will make GDB work on Ubuntu 18.04 but will break compatibility with Ubuntu 16.04. But still an Ok solution.

3. Have several versions of "internal" Glibcs in Graphene, one for each of the "important" Glibc versions. This may require non-trivial effort.

**Comment by dimakuv** [comment]
FYI: Intel SGX SDK doesn't have this problem because it uses its own, minimal libc/thread library. This library doesn't have any hooks into libthread_db. So GDB doesn't know and care about internal enclave threads.

**Comment by yamahata** [comment]
In the past, I tried 1 and gave up. The problem is, dynamic linker as ELF interpreter is specified as absolute path. In retrospect, chroot or something could be used.

anyway yet another potential solution.
4. link pal-sgx to the graphene internal version of libc instead of host version.
    Probably we have to play with ld to override default linker script/library search path.
graphene modified glibc can work without libos because it defines weak symbol of syscalldb which issues syscall instruction. (syscallas.S)

**Comment by dimakuv** [comment]
Yes, this is also a workable solution. My only issue with (4) is that I noticed that GDB has some assumptions on internals of Glibc. It may be the case that newer GDB will refuse to work with our old-Glibc-based Graphene. But we can circumvent that by requiring to debug with an older GDB.

**Comment by mkow** [comment]
I think GDB should work with older glibcs, as it needs to support statically linked binaries (which may have a different glibc inside). I like (4) the most, but we should do (2) at some point also.

> 3. PAL executable at some point loads libsysdb.so (LibOS layer), app binary itself, ld-linux.so ("internal" loader), and libc.so ("internal" Glibc). Of interest for us is libc.so -- as it initializes, it tries to inform libthread_db.so of its internal thread structures (because this is the "internal" Glibc version).
> 4. The loaded libthread_db.so is of v2.27, so libc.so v2.19 sends it incorrect format of thread structures. This results in the above error.

I think I misunderstand something here. Shouldn't in-LibOS glibc talk with in-LibOS libthread_db.so, not PAL's libthread_db.so? The problem seems to be that in-LibOS libthread_db.so was taken from the host OS, not from our patched glibc.

**Comment by dimakuv** [comment]
libthread_db.so is loaded only once per inferior (process). Since the "first" Glibc to be loaded is the one Pal executable is linked against (2.27), this version of libthread_db is used for the whole process.

There is no "reloading" of libthread_db.so when in-LibOS glibc initializes. This helper library is strictly for the debugger, and GDB does it only once.

**Comment by mkow** [comment]
> so libc.so v2.19 sends it incorrect format of thread structures

So, in-LibOS glibc talks with outer libthread_db.so? How does this happen? I mean, how does it find the outer libthread and communicate with it? (this is just out of curiosity now, most likely unrelated to how to fix this)

**Comment by dimakuv** [comment]
https://sourceware.org/gdb/wiki/FAQ#GDB_does_not_see_any_threads_besides_the_one_in_which_crash_occurred.3B_or_SIGTRAP_kills_my_program_when_I_set_a_breakpoint.

> GDB itself does not know how to decode "thread control blocks" maintained by glibc and considered to be glibc private implementation detail. It uses libthread_db.so.1 (part of glibc) to help it do so. Therefore, libthread_db.so.1 and libpthread.so.0 must match in version and compilation flags. In addition, libthread_db.so.1 requires certain non-global symbols to be present in libpthread.so.0.

I'm not sure what is the exact flow of how in-LibOS glibc talks to the outer libthread_db.so. I debugged it once in my head, and AFAIR in-LibOS Glibc has callback functions into whatever version of libthread_db.so is provided by GDB (which is currently the wrong one). As arguments to these callback funcs, in-LibOS Glibc provides some internal data structs (about "thread control blocks"). And because libthread_db.so expects another format of these internal data structs, it fails and forces GDB to fail.

But don't quote me on this.

**Comment by dimakuv** [comment]
We now can choose between several "internal" Glibc versions, including v2.27. So there are no debugging issues on Ubuntu 18.04 anymore. Closing.
