### ISSUE TITLE
[Pal, LibOS] sort out aux vector to include enough AT_xxx

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#685]
Currently Pal and LibOS creates limited set of aux vector of AT_xxx.
Sort out of what AT_xxx should be passed and stop randomly adding new AT_xxx on demand.

#684

**Comment by dimakuv** [comment]
List of all available aux vectors: https://elixir.bootlin.com/linux/latest/source/include/uapi/linux/auxvec.h

Most of these vectors can be easily emulated. Though some report HW-specific info, we should probably propagate it from the host.

**Comment by dimakuv** [comment]
Actually, I don't see a reason for this. Adding stuff on-demand looks like a reasonable strategy in Graphene. Closing this issue, but if someone has strong feelings, we can reopen it.
