### ISSUE TITLE
** Note: Please use Intel SGX Linux SDK and driver version 1.9 or lower. **? 

### ISSUE THREAD

**Issue by MatthewShine** [oscarlab/graphene#691]
** Note: Please use Intel SGX Linux SDK and driver version 1.9 or lower. **
** Note: Please use GCC version 4 or 5 **

now it 20190517,the latest sgx is 2.5, is this still right? do i have to fellow this suggestion?

which is the best to run a graphene with sgx support now ?
- OS  version
- sgx and driver version
- tools

**Comment by martinschmatz** [comment]
For what it's worth: 
I'm using gcc version 7.4.0 on Ubuntu 18.04
I'm using sgx v2.5 (from April 2, 2019)
Works for me, but needs quite a bit of effort to handle GLIBC (in-)compatibilities....would actually recommend to use the latest and greatest only if you really have to.

**Comment by dimakuv** [comment]
You don't have to follow these suggestions anymore.

As of May 2019, you will have the best experience with Ubuntu 16.04 (which comes with gcc 5.4 and Glibc 2.23). The version of the Intel SGX driver doesn't really matter anymore (I had positive experiences with 1.9, 2.0, 2.1, 2.5, and the latest master). Under such environment, you will be able to build apps, run them, and debug them using Graphene's GDB.

I also can attest that Ubuntu 18.04 (with gcc 7.3 and Glibc 2.27) works perfectly fine with Graphene. The only issue is debugging with Graphene's GDB -- there is currently a mismatch between internals of Graphene and newer Glibc which GDB hooks into.

The Linux version doesn't matter (I tested with up to 5.1).

**Comment by MatthewShine** [comment]
Thanks for answers above. I did it successfully with environment bellow
1. Ubuntu 16.04 LTS
2. sgx & driver  both 2.5(just git clone from the github)
3. gcc 5.4
HardWare Info:
1. Intel Core TM 6400 (6th generation cpu)
2. ASUS BIOS setting SGX=enabled

I run the python helloworld pgm with sgx support smoothly。
Now  i trying to run python with numpy pandas lib for ML models.Hope i can fix it.
