### ISSUE TITLE
fork() system call execution

### ISSUE THREAD

**Issue by ShobhaV** [oscarlab/graphene#7]
Hi,

I want to run a benchmark which makes some system calls. I have written a small program to test if some system calls were working, But the fork() function seems to  be stuck in a infinite loop and never exits the program. The program runs successfully natively on Linux.

I have attached a part of the program here and the manifest file is similar to the manifest.template of opendjk example in the library.

**_code snippet**_

```
           switch (fork()) {
           case -1:            /* Error */
               errExit("fork");

           case 0:             /* Child */
               printf("DOne3 \n");
               CPU_SET(childCPU, &set);
               if (sched_setaffinity(getpid(), sizeof(set), &set) == -1)
                     errExit("sched_setaffinity")
               else
                     printf("Setaffinity success!\n");

               for (j = 0; j < nloops; j++)
                   getppid();

               exit(EXIT_SUCCESS);
```

**_manifest.template snippet**_

```
sys.stack.size = 256K
sys.brk.size = 16M
glibc.heap_size = 16M

sgx.enclave_size = 512M
sgx.thread_num = 16
```

I cloned and installed the library from GitHub just yesterday after seeing 'bugfix: process fork in LibOS' and ran the program. It gave the output and gets stuck.

```
WARNING: no physical memory support, process creation will be slow.
sched_setaffinity: Function not implemented

```

**Comment by chiache** [comment]
Hi, sorry for the late response. sched_setaffinity is not implemented in Graphene yet. We are planning to support scheduling APIs in the future by adding host interface to Graphene. Currently calling sched_setaffinity will get a warning "**sched_setaffinity: Function not implemented**" and return **-ENOSYS** to the application. I will suggest you modify the source code and bypass failed calls to sched_setaffinity.
