### ISSUE TITLE
Issue while running python helloworld

### ISSUE THREAD

**Issue by reckeyzhang** [oscarlab/graphene#717]
Hello,
I was testing with a helloworld python application based here: https://github.com/oscarlab/graphene/wiki/Run-Applications-with-SGX#running-python-in-graphene

When I ran "./python.manifest.sgx scripts/helloworld.py"
The cpu is charged 95%, but it hangs and nothing happened, there was no print "Hello World"

Could you pls kindly help me on that?

Thanks

**Comment by donporter** [comment]
That is strange indeed.  If you set debugger to inline in your manifest and build with DEBUG=1, do you get any additional output?  How long does it hang?

**Comment by dimakuv** [comment]
I just tried it out, and I have no issues when running `helloworld.py`. My system is Ubuntu 16.04 with Glibc 2.23 and Python 2.7. As Don mentioned, you should do smth like:
```bash
cd <graphene-dir>
make SGX=1 clean  # complete cleanup just to be sure
make SGX=1 DEBUG=1  # rebuild graphene with debug info
cd LibOS/shim/test/apps/python
make SGX=1 clean  # complete cleanup of Python just to be sure
vim python.manifest.template
# replace "loader.debug_type = none" with "loader.debug_type = inline"
make SGX=1
make SGX_RUN=1
./python.manifest.sgx scripts/helloworld.py
```

Now observe the output log and try to figure out what goes wrong there. Feel free to attach your log here so we can look at it as well.

Please also tell your system settings.

**Comment by reckeyzhang** [comment]
Hello,
Thanks very much for your reply.
It works when I compiled with DEBUG mode, however, I had un error "Accessing file denied" when running HelloWorld, is it normal?  Thanks very much

...
allowed: file:/usr/lib/python2.7
allowed: file:scripts
Accessing file:/usr/local/lib/python2.7/dist-packages/easy-install.pth is denied. (Unknown error) This file is not trusted or allowed.
Hello World

**Comment by donporter** [comment]
This issue should be resolved by adding that file to your manifest's allowed files.

**Comment by reckeyzhang** [comment]
Thanks very much for your reply, the issue is solved :)
