### ISSUE TITLE
Issues running nginx and memcached

### ISSUE THREAD

**Issue by ddragoti** [oscarlab/graphene#718]
Hi,

System: gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
SDK and SGX driver v2.5.

I have been trying to run **Nginx** and **Memcached** on my system while playing around with Graphene and both `make SGX=1` and `make SGX_RUN=1` finish successfully but there seem to be some errors when I try to run them.

For Nginx:
```
*** allocating out of heap: 0x81c7e9000 ***
nginx: /lib/libc.so.6: version `GLIBC_2.27' not found (required by nginx)
nginx: /lib/libc.so.6: version `GLIBC_2.25' not found (required by /lib/x86_64-linux-gnu/libcrypt.so.1)
```

For Memcached:
```
shim_init() in init_mount (-13)
Saturation error in exit code -13, getting rounded down to 243
```

I tried running the ../test/native apps and they work, as do the Python scripts. Also when I run the binaries directly they do work, but not with Graphene.

Any ideas on why?

**Comment by dimakuv** [comment]
Issue with Nginx:
* Your build of Nginx requires a version of Glibc at least 2.27. The current version of in-Graphene Glibc is 2.19. Nginx refuses to run without the newer version, thus you see these errors.
* We are actively working on updating the in-Graphene version of Glibc to 2.27. Hopefully it will happen in the next month or so.

Issue with Memcached:
* This one looks interesting. Newer versions of Memcached are known to *not* work in Graphene: https://github.com/oscarlab/graphene/pull/252.
* We will work on Memcached support. You can try to debug the issue yourself and post your findings here. This will help us a lot.

**Comment by mkow** [comment]
@ddragoti We now support Glibc 2.27 and #252 was merged, could you check if you still can reproduce the problem?

**Comment by mkow** [comment]
No response from the author, closing.
