### ISSUE TITLE
Cannot prepare manifest for R example

### ISSUE THREAD

**Issue by hyunbinl** [oscarlab/graphene#728]
I was following the wiki to run R in graphene with SGX. Meanwhile, the makefile stops with a message that says

`make: *** No rule to make target 'sh.manifest', needed by 'all'.  Stop.`

I examined the Makefile of LibOS/shim/test/apps/r and found that sh.manifest was set as one of manifest requirements of the Makefile, but I couldn't find sh.manifest.template in the directory. 

I followed the same set of procedures for other app examples (e.g. python) but did not face an issue, so I suspect that I am missing something here. Could I get some guidance on this problem?

Thanks.
Hyun Bin Lee

**Comment by mkow** [comment]
Sorry for our late response. Do you still need help with this or can I close the issue?
Also, I actually see `sh.manifest.template` in the repo (https://github.com/oscarlab/graphene/blob/7a356b5a874f4f3189a0694a1aca61f51bb49525/Examples/r/sh.manifest.template).

**Comment by hyunbinl** [comment]
Yes, you may close the issue. Thanks.
