### ISSUE TITLE
[LibOS] Remove magic constant in init_brk_region()

### ISSUE THREAD

**Issue by omeg** [oscarlab/graphene#729]
```
/*
 * Chia-Che 8/24/2017
 * Adding an argument to specify the initial starting
 * address of brk region.
 * The general assumption of Linux is that the brk region
 * should be within [exec-data-end, exec-data-end + 0x2000000)
 */
```

The earliest appearance of this constant in Linux kernel source doesn't explain its purpose or why such value was chosen:
https://elixir.bootlin.com/linux/v2.6.25-rc1/source/arch/x86/kernel/process_64.c#L925

Testing shows that our regression tests and the LTP suite passes when this constant is changed to 0. More testing may be needed, especially LTP+SGX.

**Comment by mkow** [comment]
Message from the commit which added this also isn't too helpful: https://github.com/torvalds/linux/commit/c1d171a002942ea2d93b4fbd0c9583c56fce0772

**Comment by dimakuv** [comment]
+1 for removing this constant if tests reveal it's useless. Chia-Che mentioned that removing it broke some LTP tests, and we anyhow want to properly audit LTP tests (and enable more of them), so at some point during this effort we'll be confident enough to remove the constant.

**Comment by boryspoplawski** [comment]
The offset of the brk region from the executable gets randomized in range [0, this constant) and unfortunately malloc from glibc still uses brk to obtain dynamic memory.
Changing it to 0 would disable heap address randomization in non-pie executables and hence is discouraged.
As to why such a value was chosen: I suspect that it was a trade off between getting some randomization and still leaving some space for the heap to expand (especially on i386).

**Comment by mkow** [comment]
As per discussion on Slack: We're fine with closely following the kernel on this + there's already an explanation in our source. We can close this issue.
