### ISSUE TITLE
fix inconsistencies in PAL layers

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#769]
many inconsistencies in the PAL layers (not only Linux-SGX).
For example, instance/process IDs are sometimes PAL_NUM and sometimes PAL_IDX; proc_fds are sometimes ints and sometimes PAL_IDX; ports are sometimes unsigned shorts and sometimes PAL_IDX.

Clear them all.

**Comment by yamahata** [comment]
#766 was first attempt. But more needs to be done.

**Comment by mkow** [comment]
I'd rather just drop all that PAL_* types, I don't see any real advantage of using them, they just make everything much more complicated and cause problems like this issue.

**Comment by dimakuv** [comment]
This metaissue is of little value. We know that some code must be cleaned up / refactored. Closing.
