### ISSUE TITLE
App does not execute to the end with GSC (Graphene-SGX Secure Container)

### ISSUE THREAD

**Issue by reckeyzhang** [oscarlab/graphene#777]
Hello,

I have a python3 based docker image, the application is a Brain analysis application.
### Step3) Since the new graphene secure docker is generated, then I tried to trigger it manually, it seems that the application does not execute to the end (nothing is generated in the mapping output folder)

Please find the attached log file: app_gsc_log.txt

[app_gsc_log.txt](https://github.com/oscarlab/graphene/files/3315572/app_gsc_log.txt)

**Comment by dimakuv** [comment]
One thing that immediately jumps out is this line:
```
adding pages to enclave: 0x0-0xbb70000 [REG:RWX] (free)
```

Usually normal enclave apps do not start with address 0x0. Are you running a static executable? (But you said that you use Python3? So do you run your own app or a script under Python3?) It's not too bad: your enclave is mapped to 32GB high address anyway.

Next weird thing I see is this:
```
[     1] ---- shim_ioctl(0,TCGETS,0x809c19ae0) ... ioctl
[     1] ---- return from shim_ioctl(...) = -22
[     1] ---- shim_ioctl(0,TCGETS,0x809c19aa0) ... ioctl
[     1] ---- return from shim_ioctl(...) = -22
[     1] ---- shim_fstat(0,0x809c19350) = 0
[     1] ---- shim_ioctl(0,TCGETS,0x809c192c0) ... ioctl
[     1] ---- return from shim_ioctl(...) = -22
```

So here your app wants to do http://man7.org/linux/man-pages/man2/ioctl_tty.2.html and the syscalls return EINVAL (-22). If you look at Graphene source code LibOS/shim/src/sys/shim_ioctl.c, you'll see that **TCGETS is not supported**.

So you need to check why your app even wants to do this `ioctl(TCGETS)` and how to prevent the app from doing it. Hope this helps.

**Comment by reckeyzhang** [comment]
Hi Dmitrii,
Thanks very much for your swift reply.

Issue 1): The command in the original Dockerfile is:
 CMD ["python3", "/app/plot_3d_and_4d_niimg_nogui.py", "/output", "image_"]
Actually the application runs a python script, it does some calculation and save the output in a file.

Issue 2):  Do you think the ioctl is required because the python need to save the output file?
I just check the python, it calls the function like pyplot savefig(), which allows saving a file in a specific folder of the container.
So does GSC supporting saving file in a specific folder in docker container? Otherwise, it also surprises me why we need to call ioctl.

We can also send you our Dockerfile or our docker image to help find the root issue if it does not bother you.

**Comment by dimakuv** [comment]
Regarding issue 2. Why do you think the `ioctl(TCGETS)` has to do with "saving a file in a specific folder"? (By the way, it is supported in Graphene. If some folder is not specified in the manifest, Graphene would complain, and you could add the folder to the manifest.)

It seems that this particular `ioctl(TCGETS)` is some Python package (probably pyplot?) trying to write to TTY. Which is not supported in Graphene so this fails. And then there is probably no fall-back in this Python package, and it just hangs/fails.

I won't have time to check your Dockerfile :(

**Comment by mkow** [comment]
GSC was deprecated, but there's a new implementation under review, which should be much better: https://github.com/oscarlab/graphene/pull/1345.
I'm closing this issue as outdated.
