### ISSUE TITLE
[UX] Please update the Wiki

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#783]
Several Wiki pages are out-dated and contain misleading instructions. For example, the quick start instruction (https://github.com/oscarlab/graphene/wiki/Quick-Start) did not mention initializing the submodules. 

IMO, the commands listed in the Wiki should just work by copy-and-pasting into the console. This is not the case in many Wiki pages because steps are missing such as `cd` into the root of the local repository.

**Comment by mkow** [comment]
Outdated, closing.
