### ISSUE TITLE
[UX] Consider deprecating `make SGX_RUN=1`

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#784]
IMHO, the usage of `make SGX_RUN=1` is extremely obscure and confusing. The retrieval of enclave tokens should be made part of the PAL loader instead of using a separate Python script. 

Moreover, it's not obvious to the users when exactly `make SGX=1` should be run. If the users rebuilt the binaries and failed to run `make SGX_RUN=1`, the execution would fail at enclave creation. The renewal of enclave tokens should be made automatic just like the SGX SDK.

**Comment by HW42** [comment]
I also just looked into removing `SGX_RUN`. Before seeing this ticket my plan was to move the ticket generation into a separate make target (like `make sgx_tokens` or something).

> The renewal of enclave tokens should be made automatic just like the SGX SDK.

I'm surprised by this. If it's anyway done by the executing task what's the point of those tokens. Isn't this intentionally separated (to have some local authorization service or something like this)?

**Comment by HW42** [comment]
> I also just looked into removing SGX_RUN. Before seeing this ticket my plan was to move the ticket generation into a separate make target (like make sgx_tokens or something).

This part is implemented in PR #961.

**Comment by mkow** [comment]
`SGX_RUN` was removed by #961, which also introduced sgx-tokens target, so I'm closing this issue.
