### ISSUE TITLE
Need to clean up debugging info when a library is unloaded

### ISSUE THREAD

**Issue by donporter** [oscarlab/graphene#794]
In debugging the issues with Apache in a debug build (PR #574), I found that there is a bug where debugging info in the Shim is left in memory after a library is removed.  This causes a segfault when restoring from a checkpoint, as the debug info is still in the checkpoint, but the library is not.

#574 is a point fix, but there is some opportunity to do something cleaner, both with respect to clearer APIs (multiple seemingly fine proposed solutions lead to infinite recursion loops), and locking (the vma_list_lock seems to be sufficient, but a clearer protocol would be good).

**Comment by dimakuv** [comment]
This was fixed at some point by Pawel. Closing.
