### ISSUE TITLE
os.fork() in Python causes segmentation fault

### ISSUE THREAD

**Issue by chiache** [oscarlab/graphene#80]
This bug is reproduced with the "developing" branch, on both Ubuntu 16.04 and 14.04.

When running the following code:
```
import os
os.fork()
```
The program is terminated **quietly** by `SIGSEGV`. The segmentation fault can be observed in the log when turning on "debug_type=inline".  The log is as follows:
```
[    2] ---- shim_getpid() = 2
[    2] ---- shim_set_robust_list(0xba1de60,24) = 0
[    2] memory fault at 0x0 (IP = 0x4b610d)
[P4006] set tcb to 0xffd9a20
[    2] SIGSEGV handled
[P4006] ipc helper thread started
[    2] run signal handler 0xbac172e (11, 0xba7ccb0, 0xba7cd38)
[    2] killed by SIGSEGV
[    2] ipc broadcast: IPC_CLD_EXIT(1, 2, 0)
```

The segfault is trigger by accessing a variable called `_PyThreadState_Current` in python. In Graphene, this variable was not migrated when forking. The variable is 0 in the child thread as initially assigned in the Python binary.

**Comment by donporter** [comment]
Looks like this issue can be closed.
