### ISSUE TITLE
[PAL Linux-SGX] Timeout in sgx_ocall_poll

### ISSUE THREAD

**Issue by martinschmatz** [oscarlab/graphene#804]
Background: The `epoll_wait` Linux syscall is handled in Graphene (after going through a couple of layers) by `sgx_ocall_poll` in `Pal/src/host/Linux-SGX/sgx_enclave.c`.
The way I understand it, the timeout is provided in milli-seconds (ms), and translated to a timespec structure representation which has an entry for the seconds (sec), and one for the nano-seconds (nsec).

Observation: The milli-seconds specified for the timeout are translated to [sec, nsec] by these two lines in `sgx_ocall_poll`: 
```
        ts->tv_sec = ms->ms_timeout / 1000000;
        ts->tv_nsec = (ms->ms_timeout - ts->tv_sec * 1000000) * 1000;
```

Question: Shouldn't the code (which might have been inherited from a situation where the time is provided as micro-seconds) should be: 

```
        ts->tv_sec = ms->ms_timeout / 1000;
        ts->tv_nsec = (ms->ms_timeout - ts->tv_sec * 1000) * 1000000;
```

Reasoning: 
For a timeout specification of 1001ms, the existing code gives [sec, nsec] = [0, 1001000], which is zero seconds and 1.001ms, hence ~1000x too small. 
For the alternative code provided above, the result would be [sec, nsec] = [1, 1000000], which is one second and one milli-second (in total 1001ms), hence exactly what we expect.
When playing around with timeout values in my app, I can see this factor of 1000.

**Comment by martinschmatz** [comment]
Word of caution: When I implemented the above change and re-built Graphene, I see horrible latencies (10 seconds!!!) for cases when there is only one event present at the input of an `epoll_wait`, therefore also only one event present in` _DkObjectsWaitAny` (`db_object.c`) and therefore `_DkObjectWaitOne` is called. 
If two (or more) events are present, they are fully handled inside` _DkObjectsWaitAny`  and latency is small around single digit milli-seconds, as to be expected. 
I'm trying to find out why....

**Comment by dimakuv** [comment]
Doesn't seem to be directly related to your issue, but we have a couple of PRs:
- https://github.com/oscarlab/graphene/pull/651 -- on units of time
- https://github.com/oscarlab/graphene/pull/229 -- on slow epoll (but solving the other issue of returning *only one* event even for cases of hundreds of events ready on epoll)

**Comment by martinschmatz** [comment]
Thanks for the links!

Related to units of time: If Graphene uses us as internal timebase, shouldn't there be a conversion from ms to us for `epoll_wait` functionality (which specifies timeout in ms)? e.g. adding a scaling ms->us in the related syscall handler `shim_do_epoll_wait` in `LibOS/shim/src/sys/shim_epoll.c`
A possible place to do that would be to add the scaling factor here: 
```
PAL_HANDLE polled = DkObjectsWaitAny(nread ? npals + 1 : npals, pal_handles,
                                         nread ? (timeout == -1 ? NO_TIMEOUT : (PAL_NUM) timeout * 1000) : 0);
```
PAL_NUM is uint64_t, timeout is int, hence a multiplication by 1'000 doesn't cause any overflow issues.

Related to the slow epoll: 
1) The above mentioned timeout scaling would be needed as well if `DkObjectsWaitAny` would be replaced by a new `DkObjectsWaitEvents` as far as I can tell. 
2) I haven't yet found the root case of the performance degradation when using `epoll_wait` -> `shim_do_epoll_wait` -> `DkObjectsWaitAny` , hence I can't say whether or not the use of the new `DkObjectsWaitEvents` would solve my problem. I'll keep searching...

Finally, a (maybe stupid, maybe rhetoric) question: Can it be that the epoll-wait effectively is implemented as a polling loop, rather than an event triggered loop? If so, I can simply set my timeout to 0 for `epoll_wait` to degenerate the event triggered loop to a pure polling loop, in which case I don't experience (any significant) performance drop when compared to non-Graphene use case.

**Comment by dimakuv** [comment]
* I thought that we had this time-scaling somewhere inside Graphene, but I may be wrong. Have to look into this. Thanks for proposing a solution.

* Regarding `epoll_wait()` -- it is implemented as a normal event-based loop. One thing of notice is that the actual host-OS system call is not `epoll_wait()` as one might expect but a more portable `ppoll()`. The control flow is like this: `shim_do_epoll_wait() -> DkObjectsWaitAny() -> sgx_ocall_poll() -> host ppoll()`. 

Btw, what this means is that if you have 1000s of open sockets, Graphene will construct the `struct pollfd *fds` array on every `epoll_wait()` invocation (at least I remember so...). Not sure if that helps you.

**Comment by martinschmatz** [comment]
Thanks for the control flow, which confirms what I found. 

Besides the timeout thing (which I'm convinced is easy to solve), I have the suspicion that I'm loosing a `POLLOUT` flag somewhere, which is why I run in the timeout when sending. 
Or formulated differently: It could be that an addition of a `POLLOUT` flag to an event_fd which was created with `POLLIN` is never reflected in the depth of the epoll handlers when `epoll_wait()` is executed. 

Question/Request: In` _DkObjectsWaitAny`, info about events are extracted from handles as far as I can tell. Can you perhaps have a quick look at the `EPOLL_CTL_MOD` case statement in `shim_do_epoll_ctl(..)` in `LibOS/shim/src/sys/shim_epoll.c`? 
 ==> In particular: Wouldn't we have to touch `epoll_fd->handle`, `epoll_fd->epoll`, and/or `epoll_fd->pal_handle` in `EPOLL_CTL_MOD`, such that this info about flags is available in `_DkObjectsWaitAny`?

**Comment by martinschmatz** [comment]
Just a brief update: In my application (when reaching `_DkObjectsWaitAny` during the `epoll_wait(..)` execution), it looks like the `WRITABLE` flag is active for a flag which also would have `WFD` flag active - hence `POLLOUT` is not added to the events....need to better understand why.....
The `WRITABLE` flag is set in tcp_write in `db_sockets`.

**Comment by dimakuv** [comment]
More PRs coming your way :)

https://github.com/oscarlab/graphene/pull/197 -- is this PR related to your issue?
Also see https://github.com/oscarlab/graphene/issues/192 for a description of problem it tries to solve.

Just to make it clear: I am not well-versed in the epoll subsystem of Graphene. I will try to look into it later and understand your problem, but no guarantees. Alternatively, if you could create a simple test case to reproduce your issue, it would be much easier for me to debug it.

**Comment by martinschmatz** [comment]
The description of #197 indeed sounds familiar to what I experience. Could well be that the PR solves the issue. 

In the mean time, I circumvented the issue by adaptively setting the timeout to zero for a a write poll in my application. This solved my problem (as far as I can tell with only some limited testing so far). But once the PR is incorporated, I'll check back!

Many thanks for your great support!

**Comment by martinschmatz** [comment]
Before I forget: The issue related to timeout scaling ms<->us remains....

**Comment by martinschmatz** [comment]
I checked the PR related to #197, and indeed it solves my problem with epoll_wait(..) for write polls.

**Comment by dimakuv** [comment]
These PRs fixed this issue, closing:
- https://github.com/oscarlab/graphene/pull/1128
- https://github.com/oscarlab/graphene/pull/1244
