### ISSUE TITLE
[Libos]make failed with gcc 4.85 or gcc 6.4.0

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#805]
I try to build graphene-sgx(latest master branch) in AliOS(based on CentOS) with two gcc version, but both failed.
The build is performed according to the README.

1.gcc 4.8.5 & ld 2.25:
no such file: #include <stdatomic.h>
This is a gcc`s bug: stdatomic.h is missing in gcc 4.8.x, and was fixed on 4.9.

2.gcc 6.4.0 & ld 2.27:
Error starts "make -C LibOS all", the first is a lot of warning:
_
make[1]: Leaving directory `/mnt/jack.wxz/graphene/Pal'
make -C LibOS all
make[1]: Entering directory `/mnt/jack.wxz/graphene/LibOS'
Building glibc, may take a while to finish. Warning messages may show up. If this process terminates with failures, see "glibc-build/build.log" for more information.
(make -C glibc-build 2>&1 >> build.log) && touch glibc-build/Build.success
`__libc_multiple_libcs' referenced in section `.text' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os: defined in discarded section `.data' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os
`__environ' referenced in section `.text' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os: defined in discarded section `.bss' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os
`__libc_argc' referenced in section `.text' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os: defined in discarded section `.bss' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os
....
_

then the error:
_
graphene/LibOS/glibc-build/libc_pic.os: defined in discarded section `__libc_thread_freeres_fn' of /mnt/jack.wxz/graphene/LibOS/glibc-build/libc_pic.os
/usr/bin/ld: BFD version 2.27-34.base.alios7 assertion fail elf64-x86-64.c:5976
/usr/bin/ld: BFD version 2.27-34.base.alios7 assertion fail elf64-x86-64.c:5976
/usr/bin/ld: BFD version 2.27-34.base.alios7 assertion fail elf64-x86-64.c:5976
/usr/bin/ld: BFD version 2.27-34.base.alios7 assertion fail elf64-x86-64.c:5976
/usr/bin/ld: discarded output section: `.got.plt'
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[4]: *** [/mnt/jack.wxz/graphene/LibOS/glibc-build/libc.so] Error 1
make[3]: *** [elf/subdir_lib] Error 2
make[2]: *** [all] Error 2
make[1]: *** [glibc-build/Build.success] Error 2
make[1]: Leaving directory `/mnt/jack.wxz/graphene/LibOS'
make: *** [all] Error 2
_

Finally I finished the build using ubuntu docker ubuntu container "Ubuntu 18.04.2 LTS".
If graphene-sgx consider commercial distribution, do you need to consider adapting them in each OS version.

**Comment by dimakuv** [comment]
The closest thing to your issue I could find is this description: https://mcuoneclipse.com/2017/11/12/solving-problem-with-gnu-linker-and-referenced-in-section-defined-in-discarded-section-error-message/.

It seems that your particular LD & binutils bundle of v2.27 uses `-flto` and incorrectly removes functions and variables from Graphene's internal Glibc (which is of v2.19). There is ongoing work on updating Graphene's internal Glibc to newer versions. Hopefully, when it is updated to v2.27, these errors will go away.

**Comment by pangzi85480** [comment]
> The closest thing to your issue I could find is this description: https://mcuoneclipse.com/2017/11/12/solving-problem-with-gnu-linker-and-referenced-in-section-defined-in-discarded-section-error-message/.
> 
> It seems that your particular LD & binutils bundle of v2.27 uses `-flto` and incorrectly removes functions and variables from Graphene's internal Glibc (which is of v2.19). There is ongoing work on updating Graphene's internal Glibc to newer versions. Hopefully, when it is updated to v2.27, these errors will go away.

Thanks a lot.
