### ISSUE TITLE
Error when running lighttpd on Graphene-SGX

### ISSUE THREAD

**Issue by hustliyilin** [oscarlab/graphene#807]
When I run lighttpd on Graphene with sgx, do the following command；
 `./pal_loader SGX lighttpd.manifest.sgx` or `./pal_loader SGX lighttpd.manifest`
There is an error like this,
`shim_init() in init_mount (-2) ` 
`Saturation error in exit code -2, getting rounded down to 254` 
So, what should I do to solve this error ? Can you help me ?

**Comment by mkow** [comment]
-2 corresponds to ENOENT, so I think something mounted in the manifest you use doesn't exist. Could you verify all the paths which are mounted there?

**Comment by dimakuv** [comment]
For a reference Manifest, you can take a look at this PR: https://github.com/oscarlab/graphene-tests/pull/2/files (this is for a Memcached example, but it explains the general ideas). I added extensive comments so you may use it as a guide.

As @mkow mentions, there is something wrong with you mount points. Most probably you have a bug in your manifest file.

**Comment by hustliyilin** [comment]
Thanks for your help (@mkow @dimakuv), I checked all the paths which are mounted in the manifest of lighttpd and modified the `lighttpd.manifest.template` and corresponding `Makefile` files, this  error is solved. However,  there is a new error like this, 
`assert failed fs/shim_fs.c : 454 dent == dentry_root || !(dent->state & DENTRY_VALID) (value:0)`
`Saturation error in exit code -131, getting rounded down to 125`
So, how can I do to solve this new error? I would appreciate it if you can give me some useful advice.

**Comment by dimakuv** [comment]
Can you enable `loader.debug_type = inline` option in your manifest, run the application again, and send us the complete log and the manifest itself (please attach not copy)?

It is again has to do something with the way you mount directories.

**Comment by hustliyilin** [comment]
@dimakuv, OK，there are my [log](https://github.com/hustliyilin/linux/blob/master/graphene_sgx_lighttped_log) and manifest of [lighttpd](https://github.com/hustliyilin/linux/blob/master/lighttpd.manifest.template) on graphene-sgx, thanks again.

**Comment by hustliyilin** [comment]
@dimakuv  this error is solved by another programmer in our company, thanks for your advice.
