### ISSUE TITLE
Issue when running bootstrap-C++ test file

### ISSUE THREAD

**Issue by Kushg02** [oscarlab/graphene#812]
When I follow the instructions on #801 to run the C++ test file and enter the following commands:
```bash
cd LibOS/shim/test/regression
./pal_loader bootstrap-c++
```
I get the following: 
```bash
/home/kushgarg/graphene/Runtime/pal-Linux is not built, or security mode is not supported"
```
although I had setup and built graphene correctly. I have previously ran the same commands shortly after 801 was merged into master succesfully, so I am not sure what I am doing wrong. 

What is even more strange, is that inside of /Runtime if I try to run commands like `ls` or `make` I get the following:
```bash
ls: /lib64/ld-linux-x86-64.so.2: version `SHIM' not found (required by libc.so.6)
make: /lib64/ld-linux-x86-64.so.2: version `SHIM' not found (required by libc.so.6)
```

Any guidance or any indications of what I am doing wrong would be greatly appreciated!

**Comment by dimakuv** [comment]
You see two issues:

1. `/home/kushgarg/graphene/Runtime/pal-Linux is not built` simply means that you haven't built Graphene in no-SGX mode. Recall that Graphene has several backends (so-called Pals: one no-SGX Linux Pal, one SGX Linux Pal, and a couple less interesting ones). So when you built your Graphene, you probably ran `make SGX=1` which build the SGX Linux Pal (with the corresponding binary `pal-Linux-SGX`). If you build your Graphene again but without SGX variable: `make`, then you will build the no-SGX Linux Pal (with the corresponding binary `pal-Linux`).

2. The second "strange" issue is indeed strange. Can you provide more info on this one? If you run `ls` elsewhere on your system, it works fine? It only starts failing when your current directory is `graphene/Runtime`? What is your Linux version and distribution? (I imagine that `ls` may try to look for `libc.so` in the current directory first and finds our Graphene version of Glibc, but this Graphene version is not supposed to be used by host-OS programs, so `ls` fails miserably. But this is not the case at least on my Ubuntus 16.04/18.04.)

So the first issue is easily solved, but the second issue needs more debugging.

**Comment by Kushg02** [comment]
Thank you for your quick response, I appreciate your help. 

1) So in order to run in SGX mode, would I run the following? : 
```bash
make SGX=1
make SGX_RUN=1
./pal_loader SGX bootstrap-c++
```

2) Yes, I can run `ls` ,`make`, and other commands fine anywhere outside of Runtime. 

     I am running Ubuntu 16.04.6 LTS xenial 64-bit. 
     My kernel is: `Linux kushgarg-desktop 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24    13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

The libc.so.6 link was originally broken so I replaced it with a fresh one which points to the same location (presumably). I have attached a screenshot of the properties.

![image](https://user-images.githubusercontent.com/25259793/60834448-8ff5b180-a175-11e9-8a02-8ca5e5dea67a.png)

**Comment by dimakuv** [comment]
Please don't send screenshots, command line output is much better.

1. Yes, to run under SGX, you need to run the commands you mentioned.

2. You need to dig deeper. At least send the command line output (not as a screenshot!) of the failing invocations of `ls`.

**Comment by Kushg02** [comment]
My apologies. Here is the command line output:


```bash
kushgarg@kushgarg-desktop:~/graphene$ ls
CODESTYLE.md     index.md      LICENSE.addendum.txt  Makefile.configs  README.md  Tools
CONTRIBUTING.md  Jenkinsfiles  LICENSE.txt           Makefile.rules    Runtime
HACKING.md       LibOS         Makefile              Pal               Scripts

kushgarg@kushgarg-desktop:~/graphene$ cd Runtime/

kushgarg@kushgarg-desktop:~/graphene/Runtime$ ls
ls: /lib64/ld-linux-x86-64.so.2: version `SHIM' not found (required by libc.so.6)

kushgarg@kushgarg-desktop:~/graphene/Runtime$ make
make: /lib64/ld-linux-x86-64.so.2: version `SHIM' not found (required by libc.so.6)

kushgarg@kushgarg-desktop:~/graphene/Runtime$ sudo make
make: Nothing to be done for 'all'.

kushgarg@kushgarg-desktop:~/graphene/Runtime$ sudo ls
crt1.o		      libc.so.6        libpal-Linux-SGX.so  libsysdb_debug.so  pal_gdb-Linux-SGX
crti.o		      libdl.so.2       libpthread.so.0	    libsysdb.so        pal-Linux-SGX
crtn.o		      liblibos.so.1    libresolv.so.2	    libthread_db.so.1  pal_loader
ld-linux-x86-64.so.2  libm.so.6        librt.so.1	    libutil.so.1
libc.so		      libnss_dns.so.2  libsysdb.a	    Makefile
```

Interesting that I'm not getting any errors when using sudo.

**Comment by dimakuv** [comment]
What is the output of `echo $LD_LIBRARY_PATH`?

It looks like you accidentally added the `.` (current dir) in your LD_LIBRARY_PATH variable.

**Comment by Kushg02** [comment]
Here's the output:
```bash
kushgarg@kushgarg-desktop:~/graphene/Runtime$ echo $LD_LIBRARY_PATH
/usr/local/gcc-9.1/lib64:
```

Also wanted to mention that I am trying to run a C++ program, and used GCC 9.1 (seeing as gcc was supported in the apps folder as opposed to g++) with the -lstdc++ flag to make an executable. Do I need to downgrade my gcc to a graphene compatible version?

**Comment by dimakuv** [comment]
Hm, you somehow polluted your environment such that `ls` tries to use the graphene/Runtime/libc.so.6. I thought it was due to garbage in your LD_LIBRARY_PATH but doesn't look like it.

Regarding the C++ program, I'm not sure what you're doing. Please be more specific. There is a difference between running `gcc myprogram.cpp` and `g++ myprogram.cpp`. The first is incorrect (as far as I remember), the second is the one you need to use. Even if your version of GCC is 9.1. You don't need to downgrade GCC to the older version -- at least, it doesn't seem your issue has to do anything with the version of the GCC toolchain.

**Comment by Kushg02** [comment]
Could you elaborate on what polluted environment means and how I would go about fixing it? Does it mean I need to reset my operating system? 

Apologies for the confusion. I don't know why I was using gcc to compile a c++ file.

**Comment by dimakuv** [comment]
By polluted environment I mean that there is an environment variable or some configuration item in some configuration file or something like this which forces `ls` to think that it must load `libc.so.6` from the current directory. Unfortunately, I only know of `LD_LIBRARY_PATH` which can have this.

My suspicion is also supported by the fact that `sudo ls` works for you -- which means that your normal "kushgarg" user has a polluted environment while the "root" user cleans it and runs with a clean environment.

One obvious thing to try is to reboot the OS.

**Comment by Kushg02** [comment]
A fresh re-install of my OS resolved my issues and now Graphene works properly. Thank you for your help!

**Comment by mkow** [comment]
> Here's the output:
> 
> ```shell
> kushgarg@kushgarg-desktop:~/graphene/Runtime$ echo $LD_LIBRARY_PATH
> /usr/local/gcc-9.1/lib64:
> ```

> I thought it was due to garbage in your LD_LIBRARY_PATH but doesn't look like it.

@dimakuv It *was* due to this LD_LIBRARY_PATH ;) `/usr/local/gcc-9.1/lib64:` means that there will be 2 additional search paths: `/usr/local/gcc-9.1/lib64` and an empty one, which is the same as `.`. The correct setting for this variable should be `/usr/local/gcc-9.1/lib64` (without the colon).

**Comment by dimakuv** [comment]
Man, and I briefly thought that the colon at the end was weird! Now we know, thanks.
