### ISSUE TITLE
Pal/test/Makefile clobbers the CC environment variable

### ISSUE THREAD

**Issue by scottconstable** [oscarlab/graphene#813]
When specifying a compiler manually, e.g.,
```bash
$ cd graphene
$ CC=gcc-5 CXX=g++-5 make
```
the `CC` and `CXX` environment variable are clobbered in several places, specifically:
https://github.com/oscarlab/graphene/blob/178faecb8865888569bc33d7d0e51eca90366b3f/Pal/test/Makefile#L3
https://github.com/oscarlab/graphene/blob/178faecb8865888569bc33d7d0e51eca90366b3f/Pal/regression/Makefile#L3
https://github.com/oscarlab/graphene/blob/178faecb8865888569bc33d7d0e51eca90366b3f/LibOS/shim/test/Makefile#L16
https://github.com/oscarlab/graphene/blob/178faecb8865888569bc33d7d0e51eca90366b3f/LibOS/shim/test/Makefile#L17

The implication for this issue is that, suppose my `gcc` aliases to `gcc-9`, but I need to use `gcc-5` to compile graphene. If I execute
```bash
$ CC=gcc-5 make
```
then Make will only use the correct compiler until it hits one of the Makefiles I linked to above, after which it will begin using the wrong compiler.

**Comment by dimakuv** [comment]
Part of this PR: https://github.com/oscarlab/graphene/pull/774

Sorry, we really need to increase our speed of merging PRs into mainline...

**Comment by mkow** [comment]
This was fixed by #1397 (Merge Pal/test directory into Pal/regression)
