### ISSUE TITLE
SSL: 1 -1 error:140E0197:SSL routines:SSL_shutdown:shutdown while in init

### ISSUE THREAD

**Issue by hustliyilin** [oscarlab/graphene#818]
When I access lighttped on graphene-sgx using `https` (`make start-ssl-graphene-server`), there is an error  like this:

`2019-07-11 17:22:03: (connections.c.1725) SSL: 1 -1 error:140E0197:SSL routines:SSL_shutdown :shutdown while in init `

What should I do to solve this problem? Thanks very much!

**Comment by donporter** [comment]
I'm not sure.  I might start by doing a debug build (make DEBUG=1) and setting the 'debug=inline' option in the manifest.  Then share the output.

**Comment by hustliyilin** [comment]
OK, Thanks very much，I solved this problem today.
