### ISSUE TITLE
Cannot allow the files in current directory to be accessed by Graphene

### ISSUE THREAD

**Issue by rainfld** [oscarlab/graphene#82]
Taken python in Graphene-SGX for example. The original version of running hello world is as follows:

SGX=1 ./python.manifest.sgx scripts/helloworld.py

As scripts was added as an allowed subfolder: "**sgx.allowed_files.scripts = file:scripts**"

However, if I tried "SGX=1 ./python.manifest.sgx helloworld.py", even I put the current directory in manifest as "sgx.allowed_files.curr = $(PWD)", it cannot work.

The reason is that Graphene is judge if the file can be access or not by matching the prefix of allowed folder paths. However, for current directory, the file does not have path, therefore, prefix matching always return false.

**Comment by pwmarcz** [comment]
As discussed in #176, this is intentionally not allowed, and `sgx.allow_file_creation` solves the reporter's use-case. Closing.
