### ISSUE TITLE
"undefined symbol:" error in GSC 

### ISSUE THREAD

**Issue by brian-xu** [oscarlab/graphene#825]
System info:
OS: Ubuntu 16.04 LTS
CPU: Intel Core i5-7260U
RAM: 16 GB
SGX Driver Version: 2.1

I have containerized and built an [opencv/dldt](https://github.com/opencv/dldt) application, security_barrier_camera_demo, using GSC. The application runs as expected when using pictures for input, but when a video is used for input a crash occurs with the following error message:

```
[ INFO ] Trying to open input video ...
[     1] ---- return from shim_write(...) = 40
security_barrier_camera_demo: symbol lookup error: /usr/local/lib/libopencv_videoio.so.4.1: undefined symbol: _ZN2cv5utils7logging8internal15getGlobalLogTagEv
[     1] ---- shim_writev(2,0x17d735540,10) = 159
[     1] ---- shim_exit_group (returning 127)
```

I have verified that the generated container contains this library file and that the library file includes this symbol through the use of the readelf command, as shown below:

```
# readelf -s --wide libopencv_videoio.so.4.1
Symbol table '.dynsym' contains 365 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
...
   212: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZN2cv5utils7logging8internal15getGlobalLogTagEv

Symbol table '.symtab' contains 1018 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
...
  1001: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZN2cv5utils7logging8internal15getGlobalLogTagEv
```

**Comment by dimakuv** [comment]
Do you see this library `/usr/local/lib/libopencv_videoio.so.4.1` in the list of `trusted_files` in the generated Manifest?

**Comment by brian-xu** [comment]
Yes,
```
Trusted files:
...
    9d79acfeb7014fca5bfcf3dbb759528ae8319111c8b21af114d52adec337c540 file:/opencv/opencv/build/lib/libopencv_videoio.so.4.1
```

**Comment by brian-xu** [comment]
Actually, the library directory is different. Could this be an issue?

**Comment by dimakuv** [comment]
Yes, this can be an issue. It could be that you have two slightly different versions of the library in these two directories.

Please try to re-build, re-sign, and change the manifest to have the same directory.

**Comment by brian-xu** [comment]
```
Trusted files:
    ...
    7c3fe49a1026a9646252352b3b39f11316f9c8b79b091114c8b8ed92befe39bf file:/usr/local/lib/libopencv_videoio.so.4.1
    ...
[ INFO ] Trying to open input video ...
security_barrier_camera_demo: symbol lookup error: /usr/local/lib/libopencv_videoio.so.4.1: undefined symbol: _ZN2cv5utils7logging8internal15getGlobalLogTagEv
```

Unfortunately, this didn't seem to do anything.

**Comment by dimakuv** [comment]
I guess you've done it already, but can you double-check that it works without Graphene and uses the same library? E.g., by stracing the original application.

I see two explanations:
1. The symbol is actually not in this library (because lib version is different, because it is defined in another lib somehow, because it is relocatable but not reflected in ELF headers, smth like that).
2. Graphene's rtld (dynamic loader) is silently corrupted somehow, due to some related Graphene bug -- this would be tough to diagnose...

**Comment by brian-xu** [comment]
Sorry, the trail runs cold here. My application suddenly started working, with no indication of the previous issues occurring.

I did rebuild the application from scratch though due to corruption in my dockerfile, so it is very possible that this entire situation was caused by a faulty libopencv_videoio.so.4.1 file that somehow appeared fine under the lens of readelf. Or, the rebuild fixed a corruption in Graphene's rtld.

Anyways, that's about all I have to say about this issue. Marking as closed.

**Comment by MasterSkepticista** [comment]
> System info:
> OS: Ubuntu 16.04 LTS
> CPU: Intel Core i5-7260U
> RAM: 16 GB
> SGX Driver Version: 2.1
> 
> I have containerized and built an [opencv/dldt](https://github.com/opencv/dldt) application, security_barrier_camera_demo, using GSC. The application runs as expected when using pictures for input, but when a video is used for input a crash occurs with the following error message:
> 
> ```
> [ INFO ] Trying to open input video ...
> [     1] ---- return from shim_write(...) = 40
> security_barrier_camera_demo: symbol lookup error: /usr/local/lib/libopencv_videoio.so.4.1: undefined symbol: _ZN2cv5utils7logging8internal15getGlobalLogTagEv
> [     1] ---- shim_writev(2,0x17d735540,10) = 159
> [     1] ---- shim_exit_group (returning 127)
> ```
> 
> I have verified that the generated container contains this library file and that the library file includes this symbol through the use of the readelf command, as shown below:
> 
> ```
> # readelf -s --wide libopencv_videoio.so.4.1
> Symbol table '.dynsym' contains 365 entries:
>    Num:    Value          Size Type    Bind   Vis      Ndx Name
> ...
>    212: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZN2cv5utils7logging8internal15getGlobalLogTagEv
> 
> Symbol table '.symtab' contains 1018 entries:
>    Num:    Value          Size Type    Bind   Vis      Ndx Name
> ...
>   1001: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND _ZN2cv5utils7logging8internal15getGlobalLogTagEv
> ```
Can you share your dockerfile/install process for containerizing that application (regardless of the errors you faced above.) I'm trying to do this for a generic cpp application in dldt.

**Comment by brian-xu** [comment]
> Can you share your dockerfile/install process for containerizing that application (regardless of the errors you faced above.) I'm trying to do this for a generic cpp application in dldt.

Hey, I actually fixed this and successfully ran the application in question. Unfortunately, I did this during an internship and no longer have access to my documentation. From what I can remember, you need to configure the dockerfile so that running the container automatically executes the program with the correct arguments, and make sure that the application is running headlessly. I think that creating the windows inside a container might have been what caused the errors. In addition, I think I used some x-window command argument to force display forwarding.

In general, I think the error is caused when a secured container tries to create an output window without proper permissions. Again, I don't have access to the documentation I wrote and this happened several months ago, so I'm not entirely sure if what I wrote is right. However, I hope that what I wrote might point you towards a solution.

**Comment by dimakuv** [comment]
@MasterSkepticista Did you try to run your application with Graphene, but without GSC? In other words, just do the manual Graphene wrapping, without Docker containers.

If you don't know how to start with your OpenVINO app, please check this example: https://github.com/oscarlab/graphene-tests/tree/master/openvino
