### ISSUE TITLE
Checkpoint on child's do_migration may overlap with parent's VMAs

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#826]
Here is an intermittent bug (due to randomization of address spaces):

```
[P00907] checkpoint mapped at 0xb970000-0xba2b793
[P00907] 767891 bytes read on stream
[P00907] restore checkpoint at 0x0b970000 rebased from 0x53f0000
[P00907] memory entry [0xb973610]: 0x600000-0x601000
...
[P00907] memory entry [0xb971fb0]: 0xb9c5000-0xba05000
[P00907] bkeep_mmap: 0xb9c5000-0xba05000
restore_checkpoint() at vma (-13)
... child process fails ...
```

What happens is that:
1. Parent checkpoints its VMAs to restore them on the client. Notice the last VMA `0xb9c5000-0xba05000`. The checkpoint of size 767891B is sent to child as one blob.
2. Child allocates 767891B somewhere in its own memory to hold the checkpoint blob. Notice that the child randomly chose the addresses `0xb970000-0xba2b793`.
3. Child starts to restore VMAs. But the very first VMA it tries to restore is `0xb9c5000-0xba05000` -- overlapping with the checkpoint blob itself! Child cannot overwrite the checkpoint memory region, so the child panics (in `__bkeep_unmapped()`) and dies with `-13 = -EACCES`.

*Solutions*:
1. There is a macro disabled by default `CPSTORE_DERANDOMIZATION`. If this macro is enabled, the child process will always map the checkpoint at the same address as parent, thus never experiencing an accidental overlap with parent's VMAs. But this is bad for fragmentation/security.
2. The child process must move the checkpoint to some address where there will be no overlap with restored parent's VMAs. This seems like a sensible solution to implement.

**Comment by donporter** [comment]
If you are trying to implement something like fork(), it seems that you definitely do want the checkpoint at the same addresses.  I think the cpstore location is somewhat irrelevant to security if you don't use it after you are done with restoring.

Option 2 is potentially ok as well - the first thing the child receives needs to be a set of reserved address ranges.

**Comment by yamahata** [comment]
Have you seen the case where pal-Linux and/or libos overlaps with vmas?
In Pal/Linux-SGX, the loaded address is fixed so such overlap won't happen, but Pal/Linux case with ASLR enabled, it can happen, I guess.

do_migration_fork() handled all_vma transfers in the middle. can we transfer all_vma first? then such check and moving around area would be easier.

**Comment by dimakuv** [comment]
@donporter: The issue with cpstore (the checkpoint blob) is that it is not freed after the checkpoint but actively used. E.g., many restored objects (e.g. `qstr->oflow` comes to mind) simply point inside this checkpoint blob for the rest of the execution, instead of allocating a new object.

@yamahata: I have never seen a case of Pal-Linux overlaps. But I never looked for it specifically.

Yes, I think we can transfer all_vma first, reserve them in the child, and then create a checkpoint blob.

**Comment by mkow** [comment]
> The issue with cpstore (the checkpoint blob) is that it is not freed after the checkpoint but actively used. E.g., many restored objects (e.g. `qstr->oflow` comes to mind) simply point inside this checkpoint blob for the rest of the execution, instead of allocating a new object.

On a side note: I really dislike this implementation. This is the reason why we have `realloc()` commented out, as far as I remember.

**Comment by donporter** [comment]
Ideally, we would either fully incorporate live objects into the heap, so that they could be freed and realloced, or we would fully serialize and copy them out.  It seems the complaint is that we have an unholy mixture of both right now.

**Comment by mkow** [comment]
> It seems the complaint is that we have an unholy mixture of both right now.

Exactly :)

**Comment by donporter** [comment]
Note: I was looking at the state of Linux-SGX Jenkins and trying Apache.  It hits this bug pretty much deterministically.

**Comment by donporter** [comment]
Option 1 does make Apache work on SGX.
