### ISSUE TITLE
[LibOS/ld] Randomizing the heap top leads to ridiculously small heap/low shared-lib address, breaking Glibc's _dl_start()

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#828]
This is a pretty rare data race, happening ~1 out of 50 runs.

Graphene by default enables macro `ENABLE_ASLR = 1`. This leads to randomization of the heap top in `shim_vma.c` as part of process init:
```c
#if ENABLE_ASLR == 1
    /*
     * Randomize the heap top in top 5/6 of the user address space.
     * This is a simplified version of the mmap_base() logic in the Linux
     * kernel: https://elixir.bootlin.com/linux/v4.8/ident/mmap_base
     */
    size_t addr_rand_size =
        (PAL_CB(user_address.end) - PAL_CB(user_address.start)) * 5 / 6;
    size_t rand;
    ret = DkRandomBitsRead(&rand, sizeof(rand));
    if (ret < 0)
        return -convert_pal_errno(-ret);
    current_heap_top -= ALIGN_DOWN(rand % addr_rand_size);
#endif
    debug("heap top adjusted to %p\n", current_heap_top);
```

Very infrequently, the heap top will be adjusted to some rather small value, and the following VMA logic happens:
```bash
...
[P14351] Converting early VMA [0xbd6f138] 0xba50000-0xba52000
[P14351] heap top adjusted to 0x2c0c000  # randomized heap top, too low!
[     2] bkeep_unmapped: 0x280b000-0x2c0c000 => stack
[     2] heap top adjusted to 0x280b000
[     2] adding file:exec_victim as runtime object loaded at 0x400000-0x603000
[     2] bkeep_mmap: 0x400000-0x402000
[     2] bkeep_mmap: 0x601000-0x603000
[     2] bkeep_mmap: 0x7e3000-0x27e3000
[     2] brk area: 0x7e3000 - 0x7e4000
[     2] brk reserved area: 0x7e4000 - 0x27e3000
[     2] bkeep_mmap: 0x7e3000-0x7e4000
[     2] search interpreter: /lib/ld-linux-x86-64.so.2
[     2] bkeep_unmapped: 0xb9d9000-0xb9dd000 => filebuf
[     2] bkeep_unmapped: 0x1dd000-0x400000  # ld...so.2 was loaded here!
[     2] heap top adjusted to 0x1dd000  # so heap top was adjusted to be even smaller
[     2] bkeep_mmap: 0x220000-0x222000
[     2] bkeep_mmap: 0x222000-0x223000
[     2] add a library for gdb: file:../../../../Runtime/ld-linux-x86-64.so.2
[     2] shim process initialized
[     2] EXECUTE ELF OBJECT: entry=0x1dde40, argcp=0x2c0ae10  # added by me, starts executing _dl_start() of ld-linux-x86-64.so.2
[     2] memory fault at 0x00000000 (IP = 0x001de207)  # _dl_start() didn't expect such memory layout!
```

So what this log shows is:
1. Heap top was randomized to `0x2c0c000`; this value is too low as we will see below and leads to a fatal segfault inside of ld-linux-x86-64.so.2.
2. The stack of 4MB is allocated (this stack size is specified in `exec_victim.manifest.template` for no good reason) at the heap top; this pushes heap top to become `0x280b000`.
3. Now `exec_victim` binary is loaded, with code section occupying the usual `0x400000-0x402000` and the data section `0x601000-0x603000`.
4. Now `brk` region of size 32MB (this brk size is specified in `exec_victim.manifest.template` for no good reason) is allocated on the heap and slightly randomized (this is the recently updated logic in `shim_brk.c`).
5. After all these allocations we have unoccupied memory fragments on the heap: `0x10000 - 0x400000` (heap min till code segment), and `0x603000 - 0x7e3000` (data segment till brk), `0x27e3000 - 0x280b000` (after brk)! Their sizes are 4MB, 1.9MB, and 0.15MB respectively.
6. So now finally Graphene's LibOS loads the `ld-linux-x86-64.so.2` library. It must be loaded on the heap. The size of this library is 2.13MB so the only place to put it is *right below code segment of executable* (`0x1dd000-0x400000`)!
7. At this point, we have:
    - `ld-linux-x86-64.so.2` library placed below our executable!
    - heap is only `0x10000 - 0x1dd000`, or 1.8MB!

So life is terrible now, and when execution is given to `ld-linux-x86-64.so.2` (more specifically, to its `_dl_start()`) there is a NULL dereference and a segfault. I tried to understand the exact reason what happens inside this library (`LibOS/glibc-2.19/elf/rtld.c`) but failed. However, I only encountered this failure in this corner case.

**Comment by yamahata** [comment]
The randomization logic seems trim down 5/6 at most. correct?
It seems too much. maybe MAX(1/6, min randomization factor)?

**Comment by dimakuv** [comment]
Yes, I think we can solve this issue by doing two things:
1. Putting some checks on meaningful heap size/heap top values right before giving control to `ld`/executable.
2. Decreasing randomization factor from 5/6 (which in the worst case removes 83% of usable space) to e.g. 1/6 as Isaku suggests.

One thing that bothers me is that I don't understand what exactly `ld.so` wants from us. Is it too-small heap space? Is it the fact that `ld.so` (shared lib) is placed below the executable? Does anyone have experience with this?

**Comment by mkow** [comment]
> So life is terrible now, and when execution is given to `ld-linux-x86-64.so.2` (more specifically, to its `_dl_start())` there is a NULL dereference and a segfault. I tried to understand the exact reason what happens inside this library (`LibOS/glibc-2.19/elf/rtld.c`) but failed. However, I only encountered this failure in this corner case.

This NULL-deref has been debugged: #1408 (Elf relocations do not work correctly for small base addresses). See also #1410 (workaround for #1408).

**Comment by boryspoplawski** [comment]
Since the deref has been debugged and now brk and vmas work a bit different (see #1431), I'm voting for closing this (as resolved/tracked elsewhere).

**Comment by dimakuv** [comment]
Agreed with @boryspoplawski . Closing this.
