### ISSUE TITLE
[PAL] Exit code is 0 on SIGSEGV

### ISSUE THREAD

**Issue by omeg** [oscarlab/graphene#841]
Both with and without SGX. It would be nice to fix for detecting crashing tests and similar things.

**Comment by yamahata** [comment]
Do you mean host process to kick graphene process like bash should get corresponding wait status code by wait(2) system call?
And wait status should include several bits corresponding WIFEXITED, WIFSIGNALED, WTERMSIG, WCOREDUMP etc?

_exit(2), exit_group(2) system calls can only specify 8bit exit code. Other flags are set by host kernel.

**Comment by mkow** [comment]
@omeg Could you check if #1034 fixes this issue?

**Comment by omeg** [comment]
Doesn't seem so:
```
[     1] memory fault at 0x00000000 (IP = 0x0040051a)
[     1] SIGSEGV handled
[     1] run signal handler 0x7fe3919d619e (11, 0x41bc058a2390, 0x41bc058a2418)
[     1] killed by SIGSEGV
[     1] IPC broadcast: IPC_CLD_EXIT(1, 1, 0, 139)
[     1] this is the only thread 1
[     1] Waiting for 0.5s for all in-flight IPC messages to reach their destinations
[     1] Deleting port 0x7fe39196f048 (handle 0x7fe391ef0390) of process 24194
[     1] process 24194 exited with status 0
```
