### ISSUE TITLE
Symlinks generated by makefiles should be relative

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#854]
I built the project in this directory.:/mnt2/graphene/
and I can run app, eg. helloworld.
but, if I change the directory name, like:
`mv /mnt2/graphene /mnt2/graphene-new`
Running the helloworld will fail, error log:
`/mnt2/graphene-new/Runtime/pal-Linux-SGX is not built, or security mode is not supported`

I think the reason for the failure is that the link file points to an absolute path,
`ll /mnt2/graphene-new/Runtime/
lrwxrwxrwx 1 jack.wxz users   43 Jul 23 15:34 ../../../../Runtime/crt1.o -> /mnt2/graphene/LibOS/glibc-build/csu/crt1.o
lrwxrwxrwx 1 jack.wxz users   43 Jul 23 15:34 ../../../../Runtime/crti.o -> /mnt2/graphene/LibOS/glibc-build/csu/crti.o
lrwxrwxrwx 1 jack.wxz users   43 Jul 23 15:34 ../../../../Runtime/crtn.o -> /mnt2/graphene/LibOS/glibc-build/csu/crtn.o
lrwxrwxrwx 1 jack.wxz users   57 Jul 23 15:34 ../../../../Runtime/ld-linux-x86-64.so.2 -> /mnt2/graphene/LibOS/glibc-build/elf/ld-linux-x86-64.so.2
lrwxrwxrwx 1 jack.wxz users   40 Jul 23 15:34 ../../../../Runtime/libc.so -> /mnt2/graphene/LibOS/glibc-build/libc.so
`

Then I tried to modify the makefile so that all linked files in the runtime directory use relative paths.
`$ll Runtime/
total 3684
-rw-r--r-- 1 jack.wxz users    1904 Jul 23 11:13 crt1.o
-rw-r--r-- 1 jack.wxz users    1248 Jul 23 11:13 crti.o
-rw-r--r-- 1 jack.wxz users     968 Jul 23 11:13 crtn.o
lrwxrwxrwx 1 jack.wxz users       5 Jul 23 11:13 ld-linux-x86-64.so.2 -> ld.so
-rwxr-xr-x 1 jack.wxz users  159992 Jul 23 11:13 ld.so
-rwxr-xr-x 1 jack.wxz users 2035224 Jul 23 11:13 libc.so
lrwxrwxrwx 1 jack.wxz users       7 Jul 23 11:13 libc.so.6 -> libc.so`

But still an error has occurred:
`cannot find /mnt2/graphene/Pal/src/../../Runtime/libpal-Linux-SGX.so
Segmentation Fault in Untrusted Code (RIP = 55e4b7f1ae1d)`

I think this problem should be solved because it affects our release of the software. Do I have to specify a path to the compile machine when I run the program on the target machine?

**Comment by yamahata** [comment]
You have two issues.
One issue is abspath vs relpath.
It seems you have patch, please upload PR.

The second issues is segv. I'm not sure if the issu is real or not. Once the first issue is fixed, please test it again.

**Comment by mkow** [comment]
This was just fixed by #1721.
