### ISSUE TITLE
[PAL regression tests] Need to fix AvxDisable test

### ISSUE THREAD

**Issue by dimakuv** [oscarlab/graphene#855]
(The below analysis is for the old implementation of our regression subsystem, not the new Pytest implementation.)

First of all, the test is incorrectly written (see `AvxDisable.c` and its manifest -- this implementation is very brittle and relies on a specific debug message from our PAL). Second of all, the test was *never* added to our PAL Makefile so it was never run (notice the absence of `06_*.py` in the Makefile).

**Comment by dimakuv** [comment]
The current logic in `AvxDisable.c`:
```c
int main(){
  __m256 evens = _mm256_set_ps(2.0, 4.0, 6.0, 8.0, 10.0, 12.0, 14.0, 16.0);
  __m256 odds = _mm256_set_ps(1.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0, 15.0);
  __m256 result = _mm256_sub_ps(evens, odds);
  float f = result[0];
   ...
   return 1;
}
```

and the check is:
```python
regression.add_check(name="Disable AVX bit in XFRM",
    check=lambda res: "Illegal instruction executed in enclave" in res[0].log)
```

I suggest to reverse this logic, print some success message in the C test and check for `"Success message" not in res[0].log`.

**Comment by mkow** [comment]
This test was removed in #1726, closing.
