### ISSUE TITLE
[LibOS] variable context may be NULL but is dereferenced

### ISSUE THREAD

**Issue by alexandermerritt** [oscarlab/graphene#858]
I am unsure if variable `context` may ever be NULL; it is checked for debug printing but the result of the check is ignored and is dereferenced, regardless.

See `illegal_upcall` in file [LibOS/shim/src/bookkeep/shim_signal.c](https://github.com/oscarlab/graphene/blob/52786e5f4de4067f165955083c77a320a2ccc969/LibOS/shim/src/bookkeep/shim_signal.c#L478)

**Comment by yamahata** [comment]
context should not be NULL because without context (rip), SIGILL doesn't make sense.
Maybe we can add assert(context).

**Comment by mkow** [comment]
An assert + removal of the `if (context)` sounds good.
