### ISSUE TITLE
Use YAML or TOML syntax for manifests

### ISSUE THREAD

**Issue by bigdata-memory** [oscarlab/graphene#870]
YAML is easier for humans to read and write than other common data formats, it is also flexible enough to accommodate much more complex structure of configuration. Further, there are libraries available in most programming languages for working with YAML.

**Comment by dimakuv** [comment]
Just an additional note: the manifest syntax should also be able to unset envvars. Here is an example for Redis:
```
# Explicitly unset all environment variables used by Redis. This is just a
# precaution so that attacker cannot influence the default behavior of Redis
# by setting unexpected environment variables.
#
# TODO(dimakuv): Graphene's PAL incorrectly handles this currently. See
# `read_environments()`, the end of function. Below strings create envvars
# with empty strings, which forces Redis to do incorrect things like thinking
# it was started by systemd/upstart (due to UPSTART_JOB=="").
#loader.env.UPSTART_JOB =
#loader.env.NOTIFY_SOCKET =
```

**Comment by woju** [comment]
TOML would be better:
- It is closer to current syntax (AFAIU, current files would only need quotes around strings to be compatible).
- It is simpler to parse. YAML has many features, most of them rarely used (~unneeded) and sometimes even underspecified, which leads to differences between dialects.

https://github.com/toml-lang/toml
https://en.wikipedia.org/wiki/TOML

**Comment by dimakuv** [comment]
+1 for TOML. Looks very simple and clear.

**Comment by dimakuv** [comment]
It was agreed to use TOML and migrate to it completely (removing the old ad-hoc parser). I am modifying the existing https://github.com/cktan/tomlc99 parser for our specific Graphene needs (no deps on Glibc, no setlongjumps, C-style error handling) and will submit a PR soon.
