### ISSUE TITLE
pal-Linux: _DkSystemTimeQuery's use of CLOCK_MONOTONIC

### ISSUE THREAD

**Issue by smherwig** [oscarlab/graphene#880]
There are different settings in `pal_linux_defs.h` that change the host syscall used to retrieve time: basically either `clock_gettime` or `gettimeofday`.  The issue is that if `clock_gettime` is  specified, then monotonic time is returned; otherwise, realtime is returned.  I don't know if this is intended behavior, or if it's a bug and `CLOCK_REALTIME` should be passed as the `clk_id` parameter to `clock_gettime`.

This behavior also differs from `pal-Linux-SGX`, in which `gettimeofday` is the host syscall used.

**Comment by dimakuv** [comment]
Yep, looks like an inconsistency in implementation. I also see that `gettimeofday()` is being deprecated by POSIX 2008 and that `clock_gettime()` should be used instead.

I believe `clock_gettime(CLOCK_MONOTONIC, ...)` should be the correct way to get time for Graphene purposes (as the actual implementation of `DkSystemTimeQuery()`). Looks like historically the weaker `gettimeofday()` was used and then it was "updated" to a more well-defined `clock_gettime(CLOCK_MONOTONIC, ...)`, and surrounded by macros just in case.

@smherwig, would it be better for your workloads to just have `clock_gettime(CLOCK_MONOTONIC, ...)` in the implementation of all PALs? Or what would be your suggestion to fix it?

**Comment by mkow** [comment]
Can we just drop `gettimeofday` implementation altogether? It's deprecated anyway.

**Comment by smherwig** [comment]
The `clock_gettime` actually threw me off because I was doing certificate validation, and thus expected real time.  If `gettimeofday` is dropped, it immediately leads to the question of how to implement `clock_gettime`'s  `clk_id` parameter (it's unused in `shim_time.c`).

**Comment by smherwig** [comment]
To clarify, perhaps the solution is to change the signature of `DkSystemTimeQuery` to allow the caller to specify the time type/source.  So, at first pass, `DkSystemTimeQuery` would just wrap `clock_gettime`.

**Comment by mkow** [comment]
Note: This may not be that easy, remember that `DkSystemTimeQuery` must be implementable on various platforms (Linux, Windows, FreeBSD...). We should be careful before expanding the PAL API.

But I don't say no, just saying that we should be careful here ;)

What clock types would you like to have supported?

**Comment by dimakuv** [comment]
I see, so we can have a simple solution for now using `clock_gettime(CLOCK_REALTIME, ...)` everywhere.

**Comment by smherwig** [comment]
That makes sense to me.

**Comment by dimakuv** [comment]
This issue was fixed in this commit: https://github.com/oscarlab/graphene/commit/66d8e61453da7bec667936feaf494672eaded4d8#diff-1e1e63718feef3de130985c2241ef89172b3fa89cba1ee1f6e7fec33de7d1cfb
