### ISSUE TITLE
[SGX] build breaks with driver version 2.0

### ISSUE THREAD

**Issue by alexandermerritt** [oscarlab/graphene#886]
Installing the Intel SGX driver with version 2.0 and then specifying this version to Graphene will break the build.

Commits used as of this issue (July 31, 2019):
- Graphene branch `master` commit 5ec5e2f24cd24d6f9a1f29248d69df41cb2a0a7b
- Intel SGX branch `sgx2` commit `791488f7758f0cbdb30c9c2546d019fce01eafe3`

Rough steps to reproduce are below.

Fetch + build SGX driver. README claims branch `sgx2` is for driver version `2.0`.
```sh
mkdir -p /opt/intel
cd /opt/intel/
git clone -b sgx2 https://github.com/intel/linux-sgx-driver.git
cd linux-sgx-driver
make && make install && modprobe isgx
```

For Graphene, skipping some setup
```sh
git clone https://github.com/oscarlab/graphene.git
cd graphene
git checkout -b sgx-bork 5ec5e2f24cd24d
# [skipping to driver build]
cd Pal/src/host/Linux-SGX/sgx-driver
make
# path: /opt/intel/linux-sgx-driver
# version: 2.0
```

Build from top-level directory with `make SGX=1` gives this error:

```sh
# ...skip...
  [ sgx_framework.o ]
sgx_framework.c: In function ‘init_enclave’:
sgx_framework.c:366:14: error: ‘SGX_INVALID_LICENSE’ undeclared (first use in this function); did you mean ‘SGX_INVALID_KEYNAME’?
         case SGX_INVALID_LICENSE:
              ^~~~~~~~~~~~~~~~~~~
              SGX_INVALID_KEYNAME
sgx_framework.c:366:14: note: each undeclared identifier is reported only once for each function it appears in
Makefile:60: recipe for target 'sgx_framework.o' failed
```
Rebuilding in `Pal/src/host/Linux-SGX/sgx-driver` but specifying the driver version is `2.1` resolves the build error.

**Comment by mkow** [comment]
@omeg Didn't we have the same problem in graphene-ng? I guess sgx_framework.c (or some header) should just #ifdef this?

**Comment by yamahata** [comment]
https://github.com/oscarlab/graphene-sgx-driver/pull/3

**Comment by mkow** [comment]
Fixed long time ago, closing.
