### ISSUE TITLE
Seccomp filter can be circumvented

### ISSUE THREAD

**Issue by mkow** [oscarlab/graphene#90]
https://github.com/oscarlab/graphene/blob/c2c92723b9da232481882d5b4bd494b6663c79ee/Pal/src/security/Linux/filter.c#L196-L203

If I get the code correctly, it should be easy to fool it in two different ways:
* `code_end` is exclusive, so there should be `JGE` instead of `JGT`. One can place a page right at `code_end` and place `syscall` instruction exactly on `code_end` address.
* Unfortunately the whole idea of this filter seems to be wrong - malicious code can set up registers for a syscall and jump directly to a `syscall` instruction inside `code_start` - `code_end` range. Such syscall will be accepted by this filter.

**Comment by chiache** [comment]
Thanks for raising this concern. We are aware of the possibility that an application could circumvent the check of instruction pointers. The purpose of using a SECCOMP filter here is to reduce the attack surface to the host kernel, by forbidding a major portion of the system call table. Checking the instruction pointers is mostly a compatibility feature, since we need to support static binaries. The SECCOMP filter is never meant for completely blocking an application from making a direct system call.

**Comment by donporter** [comment]
Thanks for the fixes, @mkow 

Perhaps to clarify the point: Any system call the PAL is allowed to issue is checked by the seccomp filter/reference monitor outside of the process.  We assume that the PAL can be compromised by the application (unlike, say Native client), and that the application may issue that system call.

The point of IP-based checking is really for convenience and portability.  In particular, our original goal was to support statically linked binaries or catch inline system call instructions, on a best-effort basis, and redirect these to the libOS.  If an application managed to circumvent this check, the reference monitor is responsible for system safety, and the application only harms itself by confusing the libOS.

Does this make sense?

**Comment by mkow** [comment]
Sounds good :)
IMO it would be nice to add a comment to the second filter and explain that it's not a security feature, it should be less misleading then (just copy-pasting what you wrote here would be enough). What do you thing about this?

**Comment by mkow** [comment]
Also, it would be a nice to fix the off-by-one bug in the range checking (`JGT` should be `JGE`).

**Comment by mkow** [comment]
This feature was removed, so this issue is not relevant anymore.
