### ISSUE TITLE
[LibOS] ELF loader crashes on binary without DT_HASH in the dynamic section

### ISSUE THREAD

**Issue by alexandermerritt** [oscarlab/graphene#905]
Description
---
LibOS crashes when parsing ELF binary headers which do not contain an array entry with tag `DT_HASH` in the `PT_DYNAMIC` or `.dynamic` section. The symptom is a thrown AEX vector inside Pal.

Symptom
---

One may see the following, e.g., executing `uname`:

```
*** An unexpected AEX vector occurred inside PAL. Exiting the thread. *** 
(vector = 0x2, type = 0x0 valid = 0, RIP = +0x00007400)
rax: 0x80bfa9f4c rcx: 0x101719f2c8 rdx: 0x00000000 rbx: 0x80bfaad5c
rsp: 0x80ffe97e8 rbp: 0x80ffe9820 rsi: 0x80bfaad94 rdi: 0x80bfaad5c
r8 : 0x6fffffff r9 : 0x70000021 r10: 0x00000031 r11: 0x6ffffdff
r12: 0x00000001 r13: 0x37ffff1a0 r14: 0x6ffffeff r15: 0x37ffffa00
rflags: 0x00010202 rip: 0x80bd75400
pausing for debug
```

RIP `0x7400` inside `libpal*.so` is (Intel ASM syntax):

```asm
00000000000073f0 <setup_elf_hash>:
    73f0:       48 8b 87 90 02 00 00    mov    rax,QWORD PTR [rdi+0x290]
    73f7:       48 85 c0                test   rax,rax
    73fa:       74 54                   je     7450 <setup_elf_hash+0x60>
    73fc:       48 8b 48 08             mov    rcx,QWORD PTR [rax+0x8]
    7400:       8b 11                   mov    edx,DWORD PTR [rcx]
```

corresponding to the source code

```c
void setup_elf_hash (struct link_map *map)
{
    /* ... */
    map->l_nbuckets = *hash32++;
    /* ... */
}
```
In other instances (e.g., executing `/bin/nc.openbsd`), the following source code fails:

```c
void setup_elf_hash (struct link_map *map)
{
    /* ... */
    if (!map->l_info[DT_HASH])
        return;
    hash = (void *) D_PTR (map->l_info[DT_HASH]); /* hash has bad value */
    map->l_nbuckets = *hash++;
                   // ^^^^^ dereference throws AEX
    /* ... */
}
```

How to reproduce
---

In `LibOS/shim/test/native` reuse `ls.manifest.template` to point to a binary which **does not** contain a `DT_HASH` array entry. Examples: `uname`, `nc`, `ps`, `true`, `ln`, etc. Ensure the dependent libraries for the binary are included in the list of trusted files (check with `ldd`).

```
loader.exec = file:/bin/ls
# Change to
loader.exec = file:/bin/uname
```

Build Graphene and the applications in this directory as usual, and execute `SGX=1 ./pal_loader ls.manifest.sgx` to observe.

**Comment by dimakuv** [comment]
LibOS ELF loader was completely reworked recently by Pawel, and `setup_elf_hash()` is not even present in the reworked code. Closing this.
