### ISSUE TITLE
regression: testcase in python should keep stdout, stderr at least on failure

### ISSUE THREAD

**Issue by yamahata** [oscarlab/graphene#907]
the current python regression tests discards stdout and stderr always.
KEEP_LOG=1 is ignored now.
test runner doesn't save log to investigate failure on CI system.
Only process exit code is available. more clue is needed for investigation.

**Comment by mkow** [comment]
CC: @woju

**Comment by pwmarcz** [comment]
Stdout and stderr are printed on failure since dace80ce084349584109620c2e785eb42e87fb95.
