### ISSUE TITLE
[LibOS] handle_copy(): wrong source and destination for memcpy()

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#909]
Found this when debugging an issue with renaming files.

https://github.com/oscarlab/graphene/blob/8c37290b6fce94221fd1ca8c4d16b580e2d4ad73/LibOS/shim/src/sys/shim_fs.c#L494

The line should actually be `memcpy(bufo + boffo, bufi + boffi, copysize);`

**Comment by dimakuv** [comment]
@thomasknauth Could you check https://github.com/oscarlab/graphene/pull/1000 and, if correct, put LGTM in Reviewable?

**Comment by dimakuv** [comment]
We just merged #1000 so this issue is fixed.
