### ISSUE TITLE
Publish Jenkins build logs

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#921]
Jenkins is not publicly accessible for security reasons. At the moment this has the consequence that the build logs are not externally accessible.

For main contributors that's not a big problem, they just need to remember to use the ssh tunnel. But external contributors have no access, which is (IMO) bad for an open source project.

I have looked into how to published the build logs after a build has finished.

Part 1: How to collect and upload the build logs:

 1. Use a Jenkins plugin which does this. Looking around I didn't see a plugin which supports some generic upload target like SFTP or a git repo. Only plugins for specific third-party services like "AWS CloudWatch Logs"
 2. Use a Jenkins plugin (like [1], but seems unmaintained) to get the log to the job's workspace and upload it in a "post" step.
 3. Allow HTTP access from the slaves to the master and get the log from master from the job's post step.
 4. Redirect log output inside the job (like [2], output example [3]) and then upload this in a post step. This has the down side that it doesn't contain output of non shell script steps (like docker setup).
 5. Run a script somewhere else which fetches the log from Jenkins and uploads it.

Part 2: Where to publish it:

 1. Use some simple Webspace. While it would be easy to provide this I think it's preferable if this would be also on the UNC infrastructure which runs Jenkins, to keep things easier to maintain.
 2. (Ab-)use a git repo (like [4]). This has the advantage we can use the already existing infrastructure. Just add a repo under the GitHub org. and add an ssh key.
 3. Some third-party service (ideally one with a ready to use Jenkins plugin).

Part 3: Fix the link in the GitHub commit status:

Grepping through the source code of the GitHub integration plugin this doesn't look configurable ... (But I might be wrong here).

I have scripts for 4-2 and 5-2 (which are trivial to adopt for variant 3-2) (using 2-2, 2-1 should also be trivial).

@woju: AFAIK you have some more Jenkins experience. What do you think?

cc: @donporter 

[1]: https://github.com/devconsoft/console-log-to-workspace-plugin
[2]: https://github.com/HW42/graphene/blob/0d6f26730d4976ddd38fb9940b7e7d2a60a1f38a/Jenkinsfiles/Linux-SGX#L16
[3]: https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-graphene-sgx-1722/build-log
[4]: https://github.com/HW42/graphene-build-logs

**Comment by donporter** [comment]
@dcowhig

**Comment by dimakuv** [comment]
There was no movement on this, and I think nobody really has any problems with this. Closing.
