### ISSUE TITLE
why does the usage of graphene in DEBUG mode needs driver?

### ISSUE THREAD

**Issue by sammyne** [oscarlab/graphene#924]
I want to develop app based on graphene in localhost without SGX support. When using the original SGX SDK, it's would be fine without SGX driver installed. 

**So is it possible to remove the dependencies on SGX drivers to ease local development?**

I run on my SGX-enabled machine with SGX SDK 2.5 and SGX Driver 2.5, still got 
```bash
In file included from sgx_framework.c:6:0:
sgx-driver/graphene-sgx.h:8:26: fatal error: isgx_version.h: No such file or directory
compilation terminated.
Makefile:58: recipe for target 'sgx_framework.o' failed
make[3]: *** [sgx_framework.o] Error 1
make[3]: Leaving directory '/home/block01/Workspaces/lixiangmin01/graphene/Pal/src/host/Linux-SGX'
Makefile:95: recipe for target 'host_lib_recurse' failed
make[2]: *** [host_lib_recurse] Error 2
make[2]: Leaving directory '/home/block01/Workspaces/lixiangmin01/graphene/Pal/src'
Makefile:7: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/block01/Workspaces/lixiangmin01/graphene/Pal'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2
```

Any help would be greatly appreciated~

**Comment by dimakuv** [comment]
Replies for your two questions:

1. It is currently not possible to run Graphene-SGX in *simulation mode*. Graphene-SGX always has to run on an SGX-enabled machine. There are two solutions for your problem: (a) use Graphene with Linux PAL (i.e., build and run without `SGX=1`), or (b) develop and build on your local non-SGX machine, then copy the produced binaries and run them on an SGX-enabled machine.

In general, it is not obvious why Graphene-SGX in simulation mode would be useful. If you are deploying your applications on top of Graphene, you can always try your application in non-SGX (normal Linux PAL) mode. If you need to change/use something specific to SGX, then it only makes sense to develop on an SGX-enabled machine.

2. For you build error, it looks like you forgot to build a Graphene SGX driver: see Step 4 in https://github.com/oscarlab/graphene/wiki/SGX-Quick-Start.

**Comment by mkow** [comment]
No reply from the author, closing.
