### ISSUE TITLE
alarm() does not cancel/reset outstanding alarms

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#93]
https://github.com/oscarlab/graphene/blob/26eae52106d87418e161aafc6199ebbcc9cfe149/LibOS/shim/src/sys/shim_alarm.c#L46

The current implementation does not handle the case where installing a new alarm cancels a previous alarm nor does it indicate whether there was a previous alarm (via the return value). This breaks, for example, libresolv, which uses alarms to detect DNS query timeouts (I believe, haven't looked into the source of libresolv).

**Comment by donporter** [comment]
Thanks for reporting this issue, @thomasknauth .  It looks like the LTP test alarm05 is a good unit test for this issue.

**Comment by donporter** [comment]
@thomasknauth PR #101 should fix this issue.
