### ISSUE TITLE
PAL SGX loader does not build under Debian

### ISSUE THREAD

**Issue by xvzcf** [oscarlab/graphene#97]
I tried to build the `pal-sgx` executable inside a Debian Docker container. While not installed, the `linux-sgx-driver`, specifically the source of version `1.9`, is available to the build process.

Here's the output of `uname -a`
```
Linux b961494fc492 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 GNU/Linux
```

`cat /etc/debian_version` returns `9.1` and here are the errors I get when running `make SGX=1 DEBUG=1` in `Pal/src`:

```
[ host/Linux-SGX/sgx_entry.o ]
[ host/Linux-SGX/pal-sgx ]
../../.lib/graphene-lib.a(config.o): In function `__del_config':
/opt/graphene/Pal/lib/graphene/config.c:199: undefined reference to `__abort'
/opt/graphene/Pal/lib/graphene/config.c:199: undefined reference to `__abort'
/opt/graphene/Pal/lib/graphene/config.c:200: undefined reference to `__abort'
/opt/graphene/Pal/lib/graphene/config.c:200: undefined reference to `__abort'
collect2: error: ld returned 1 exit status
Makefile:60: recipe for target 'pal-sgx' failed
```
I believe the problem to be the use of `__abort` in the `assert` macro defined in `Pal/lib/assert.h`, but I'm not sure as to how to proceed.

**Comment by donporter** [comment]
I suspect that the issue is that __abort may not be defined in the URT (untrusted runtime) code.  It is weird that we haven't seen this problem on ubuntu, but maybe it slipped through the cracks (time for more CI work...).

In the short term, I bet the problem will go away if you don't build with DEBUG=1.  I believe the correct fix will be to add an implementation of __abort in Pal/src/host/Linux-SGX/sgx_main.c

I'll also see if I can repro soon.

**Comment by donporter** [comment]
I see the problem.  Would you mind trying the fix-assert branch and see if it addresses your issue?

**Comment by donporter** [comment]
I can't reproduce this error, but I think the type issue clang flagged does seem wrong.  I'm surprised gcc 5.4 isn't complaining.

I pushed a change on the same branch that may address this.  Let me know if it works.

**Comment by xvzcf** [comment]
I've updated my previous comment to reflect the compiler versions, and the new change does work. Thank you very much.
