### ISSUE TITLE
No rule to make target 'test_start_pthread_m.m', needed by 'all'.

### ISSUE THREAD

**Issue by az-hasan** [oscarlab/graphene#970]
Hello,

I'm trying to run the helloworld example, after following the Quick Start guide [here](https://graphene.readthedocs.io/en/latest/oldwiki/SGX-Quick-Start.html). The SGX and Graphene drivers are loaded properly. When I run "make SGX=1" in step 6 (Run a helloworld program), I get this [output](https://github.com/az-hasan/makefile-output/blob/master/make.txt): "make: *** No rule to make target 'test_start_pthread_m.m', needed by 'all'.  Stop.", and all the manifest files end with "....manifest.sgx.d".

I am not sure why this is failing, as I have not added any of my own code, etc. Any idea what I need to do to make the example work?

**Comment by yamahata** [comment]
https://github.com/oscarlab/graphene/pull/931
will fix it.
the current CI doesn’t compile them. so it was missed.

**Comment by az-hasan** [comment]
Thanks, that fixed it
