### ISSUE TITLE
Numpy with openblas causes CPU running at 100% in SGX mode

### ISSUE THREAD

**Issue by lejunzhu** [oscarlab/graphene#977]
I installed numpy by `pip install numpy==1.16.5`, then run this simple python script using Graphene SGX and python3:
```
import time
import numpy
while True:
        print(time.time(), flush=True)
        time.sleep(10)
```
Even this program is supposed to be almost idle, 'top' shows all CPU threads are running at 100%. Debug log keeps printing something like this:

```
[     5] ---- shim_sched_yield() = 0
[     7] ---- shim_sched_yield() = 0
[     3] ---- shim_sched_yield() = 0
[     5] ---- shim_sched_yield() = 0
[     2] ---- shim_sched_yield() = 0
[     4] ---- shim_sched_yield() = 0
[     5] ---- shim_sched_yield() = 0
[     7] ---- shim_sched_yield() = 0
[     3] ---- shim_sched_yield() = 0
[     5] ---- shim_sched_yield() = 0
```

This does not happen when I run the same script using non SGX Graphene. 

Also, the binary version of numpy includes openblas. For those who have the same problem, the phenomena disappears if numpy is built from source, e.g. `pip install --no-binary=":all:" numpy==1.16.5`

**Comment by dimakuv** [comment]
In these two years, we fixed a lot of such performance bugs in Graphene. We haven't heard any complaints about NumPy recently, so closing this.
