### ISSUE TITLE
18.04 is flaky on Jenkins

### ISSUE THREAD

**Issue by HW42** [oscarlab/graphene#980]
When the tests on Jenkins run on Ubuntu 18.04, graphene seems to sometimes hang.

Failed examples:
https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/694/build-log
https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/685/build-log
https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/747/build-log

Successful examples:
https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/695/build-log
https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/749/build-log

On Jenkins it hits very often the `test_pal.py::TC_01_Bootstrap::test_104_manifest_as_executable_name` (aka Bootstrap2) PAL regression test (timeout). As can be seen above this is not always the case.

I haven't managed to reproduce this locally so far. Even running 4 parallel loops, with each executing Bootstrap2 10 000 times (on a 2 cores 4 threads machine) didn't help. SGX also works (note that I didn't find a recent Jenkins log where that test fails for SGX).

**Comment by HW42** [comment]
If someone has some hints (for example if you are able to observer this locally on some other test), please leave a comment).

**Comment by mkow** [comment]
Observation:
I checked `graphene-18.04` pipeline and it *always* succeeds on `slave-leeroy` and `slave-uncledeadly` and *always* fails on `slave-pepe`, `slave-statler`, `slave-beaker12`, `slave-waldorf` and `slave-bobothebear`.

I don't know what's the difference between them nor have ssh access to investigate further. Maybe different kernel on the host or thread/cores count?
CC: @donporter, @dcowhig

**Comment by HW42** [comment]
Hahaha ...

That timeout in https://raw.githubusercontent.com/HW42/graphene-build-logs/jenkins-full-output/graphene-18.04/685/build-log got me on the wrong track.

Compare `Bootstrap.c`:
```
[...]
    /* check manifest name */
    char manifest[30];
    DkStreamGetName(pal_control.manifest_handle, manifest, 30);
    pal_printf("Loaded Manifest: %s\n", manifest);
[...]
```

With `Bootstrap2.c`:
```
[...]
    /* check manifest name */
    char manifest[30] = "";
    DkStreamGetName(pal_control.manifest_handle, manifest, 30);
    pal_printf("Loaded Manifest: %s\n", manifest);
[...]
```

;]

Still interesting how reproducible the memory corruption triggers a hang or not. Will look at the other regression failures after the weekend.

**Comment by HW42** [comment]
Deleted my wrong comment.

**Comment by donporter** [comment]
I suspect it is somehow related to hyperthreading being enabled.  I can repro on a test system.  Stay tuned...

**Comment by donporter** [comment]
This line is the culprit for most of the issues: https://github.com/oscarlab/graphene/blob/de42ebabe1f7af1a1b71a5fb82f5f34643c845a6/Pal/regression/Makefile#L4

We are turning on all AVX instructions (not the default), and gcc is using vpxor to do the string init in several Pal tests.  On machines without avx512, this is a SIGILL and gets hung.

Note that there is a different issue with Process.  I'm not sure what is going on there.  It seems to hang reading a pipe, until a signal comes in.

**Comment by HW42** [comment]
> Note that there is a different issue with Process. I'm not sure what is going on there. It seems to hang reading a pipe, until a signal comes in.

The Pipe and Socket test are also failing. So my current guess is that the process test fails because it also want to use a pipe.

**Comment by HW42** [comment]
Can you reproduce the hang of the Pipe/Socket/Process test locally?

**Comment by donporter** [comment]
Yes.  Email dcowhig and cc me if you need an account on the test machine I'm using.

**Comment by HW42** [comment]
Great that you can reproduce! Thanks to the tip about AVX I tried booting with `noxsave`. And now I can reproduce the Bootstrap2 and the Pipe failure. So I will first play locally.

**Comment by HW42** [comment]
> Note that there is a different issue with Process. I'm not sure what is going on there. It seems to hang reading a pipe, until a signal comes in.

Hmm, on my test machine they work if I fix the AVX problem.

**Comment by mkow** [comment]
For bookkeeping: #987 from Isaku fixes the AVX flag being incorrectly set on too many tests.
Please verify whether this solves the problem or we need more fixes.

**Comment by donporter** [comment]
At least on my test system, this fixes all of the issues I can reproduce.
