### ISSUE TITLE
[Tools] Update and write test for GSCE

### ISSUE THREAD

**Issue by thomasknauth** [oscarlab/graphene#985]
GSCE does not work on master anymore. At a minimum, the script needs a better strategy to handle symbolic links in Runtime/ which is broken by default. Also needs an update to handle changed/evolved paths, e.g., generated_offsets.py.

Related: #482

https://github.com/oscarlab/graphene/blob/a01bbdfb602874a2f99d981e1c30e54fa31c4971/Tools/gsce#L43

**Comment by mkow** [comment]
GSC was deprecated, but there's a new implementation under review, which should be much better: https://github.com/oscarlab/graphene/pull/1345.
I'm closing this issue as outdated.
