### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Starkemis** [oscarlab/graphene#994]
Absolutely 0 reason to name it Graphene. All it does is mislead.

**Comment by woju** [comment]
No, that was actually the right button.

**Comment by mkow** [comment]
Still better than "Apple".

**Comment by dimakuv** [comment]
+1 for the thread starter. I was misled into contributing to this project.

**Comment by chiache** [comment]
My advisor told me that this is a physics project until I joined...

**Comment by Starkemis** [comment]
Exactly, you guys. This can't compare to the awesomeness of actual graphene.

**Comment by mkow** [comment]
Ok, enough fun, I'm closing this :)
