### ISSUE TITLE
[bug report]sendfile failed when send regular file to sock

### ISSUE THREAD

**Issue by pangzi85480** [oscarlab/graphene#998]
testcase: 
    run lighttpd or nginx in graphene-sgx, then curl 127.0.0.1:8000
error info:
    sendfile failed:Permission denied 3

I found three problems in sendfile(LibOS/shim/src/sys/shim_fs.c  handle_copy()):
1. error param for memcpy
        if (do_mapi && do_mapo) {
            copysize = count - bytes > bufsize ? bufsize :
                       count - bytes;
            memcpy(hdlo + boffo, hdli + boffi, copysize);       /*hdlo and hdli is shim_handle*/
            ....
        }
2. if do_mapi is true and do_mapo is false(regular file to sock), bufi is not in enclave mem space(mmap non-enclave), then ocall_sock_send() will return error.

3. if count + addrlen > PAGE_SIZE, buf needs to be checked if it is in encalve space by ocall_sock_send().

I wrote a patch fo fix them.

```
commit 454de17a40d60d3738ccaefd1c462d6e06a00091
Author: jack.wxz <jack.wxz@alibaba-inc.com>
Date:   Fri Sep 13 14:12:02 2019 +0800

    bug fix: sendfile() failed when send a regular file to a sock
    
    Signed-off-by: jack.wxz <jack.wxz@alibaba-inc.com>

diff --git a/LibOS/shim/src/sys/shim_fs.c b/LibOS/shim/src/sys/shim_fs.c
index 5d345a1..8bf4744 100644
--- a/LibOS/shim/src/sys/shim_fs.c
+++ b/LibOS/shim/src/sys/shim_fs.c
@@ -418,7 +418,7 @@ static ssize_t handle_copy (struct shim_handle * hdli, off_t * offseti,
             }
         } while(0);
 
-    void * bufi = NULL, * bufo = NULL;
+    void * bufi = NULL, * bufo = NULL, * buftmp = NULL;
     int bytes = 0;
     int bufsize = MAP_SIZE;
     int copysize = 0;
@@ -492,7 +492,7 @@ static ssize_t handle_copy (struct shim_handle * hdli, off_t * offseti,
         if (do_mapi && do_mapo) {
             copysize = count - bytes > bufsize ? bufsize :
                        count - bytes;
-            memcpy(hdlo + boffo, hdli + boffi, copysize);
+            memcpy(bufo + boffo, bufi + boffi, copysize);
             DkVirtualMemoryFree(bufi, ALIGN_UP(bufsize + boffi));
             bufi = NULL;
             DkVirtualMemoryFree(bufo, ALIGN_UP(bufsize + boffo));
@@ -504,7 +504,11 @@ static ssize_t handle_copy (struct shim_handle * hdli, off_t * offseti,
             if (copysize < 0)
                 break;
         } else if (do_mapi) {
-            copysize = fso->fs_ops->write(hdlo, bufi + boffi, bufsize);
+            if (!buftmp)
+                buftmp = (void *)malloc(bufsize);
+
+            memcpy(buftmp, bufi + boffi, bufsize);
+            copysize = fso->fs_ops->write(hdlo, buftmp, bufsize);
             DkVirtualMemoryFree(bufi, ALIGN_UP(bufsize + boffi));
             bufi = NULL;
             if (copysize < 0)
@@ -533,6 +537,11 @@ static ssize_t handle_copy (struct shim_handle * hdli, off_t * offseti,
             break;
     } while (bytes < count);
 
+    if (buftmp) {
+        free(buftmp);
+        buftmp = NULL;
+    }
+
     if (copysize < 0 || (count > 0 && bytes < count)) {
         int ret = copysize < 0 ? copysize : -EAGAIN;
 
diff --git a/Pal/src/host/Linux-SGX/enclave_ocalls.c b/Pal/src/host/Linux-SGX/enclave_ocalls.c
index ebaca7d..6507daf 100644
--- a/Pal/src/host/Linux-SGX/enclave_ocalls.c
+++ b/Pal/src/host/Linux-SGX/enclave_ocalls.c
@@ -791,6 +791,12 @@ int ocall_sock_send (int sockfd, const void * buf, unsigned int count,
     void * obuf = NULL;
     ms_ocall_sock_send_t * ms;
 
+    if (!buf)
+        return -EINVAL;
+
+    if (!sgx_is_completely_inside_enclave(buf, count))
+        return -EPERM;
+
     if ((count + addrlen) > PRESET_PAGESIZE) {
         retval = ocall_alloc_untrusted(ALLOC_ALIGNUP(count), &obuf);
         if (IS_ERR(retval))

```

**Comment by dimakuv** [comment]
Thanks for the patch! We actually found (at least one of) these bugs: https://github.com/oscarlab/graphene/issues/909. We will create a PR on this. Thanks again.

**Comment by dimakuv** [comment]
Ok, I took a deeper look at the proposed changes. I have a couple questions:

I agree with this patch 1. But I don't understand the need for patches 3 (`ocall_sock_send()`) and 2 (`buftmp`).

First, `ocall_sock_send()` doesn't need additional checks on the arguments. These arguments are supplied by the LibOS so the assumption (by the SGX PAL layer) is that all arguments were checked already. Why would we disallow `[buf, buf+count]` to be outside of the enclave? It is perfectly legal to ask SGX PAL to write an untrusted-memory buffer to the socket.

Second, why is it important to copy-paste from `bufi` to `buftmp`? (I understand that `buftmp` is allocated entirely in the enclave and that's your goal.) Given my first point, there seems to be no functional issue with sending directly from `bufi`? I mean, it will not segfault Graphene.

Maybe I'm missing some security argument for patches 2 and 3? I didn't consider thoroughly the security implications of "regular file -> socket" copying.

**Comment by pangzi85480** [comment]
> Ok, I took a deeper look at the proposed changes. I have a couple questions:
> 
> I agree with this patch 1. But I don't understand the need for patches 3 (`ocall_sock_send()`) and 2 (`buftmp`).
> 
> First, `ocall_sock_send()` doesn't need additional checks on the arguments. These arguments are supplied by the LibOS so the assumption (by the SGX PAL layer) is that all arguments were checked already. Why would we disallow `[buf, buf+count]` to be outside of the enclave? It is perfectly legal to ask SGX PAL to write an untrusted-memory buffer to the socket.
> 
> Second, why is it important to copy-paste from `bufi` to `buftmp`? (I understand that `buftmp` is allocated entirely in the enclave and that's your goal.) Given my first point, there seems to be no functional issue with sending directly from `bufi`? I mean, it will not segfault Graphene.
> 
> Maybe I'm missing some security argument for patches 2 and 3? I didn't consider thoroughly the security implications of "regular file -> socket" copying.

buftmp is added for the following reasons:
fso->fs_ops->write(hdlo, bufi, bufsize) 
   ->....
     -> ocall_sock_send()
        ->sgx_copy_to_ustack()


sgx_copy_to_unstack will return NULL if [bufi, bufi + count] not in enclave.
```
void* sgx_copy_to_ustack(const void* ptr, uint64_t size) {
    if (!sgx_is_completely_within_enclave(ptr, size)) {
        return NULL;
    }
    ....
}
```

If we don't need to check the bufi parameters, we can even do a copy-free in sgx_copy_to_ustack():
```
diff --git a/LibOS/shim/src/sys/shim_fs.c b/LibOS/shim/src/sys/shim_fs.c
index 5d345a1..9f2f33e 100644
--- a/LibOS/shim/src/sys/shim_fs.c
+++ b/LibOS/shim/src/sys/shim_fs.c
@@ -492,7 +492,7 @@ static ssize_t handle_copy (struct shim_handle * hdli, off_t * offseti,
         if (do_mapi && do_mapo) {
             copysize = count - bytes > bufsize ? bufsize :
                        count - bytes;
-            memcpy(hdlo + boffo, hdli + boffi, copysize);
+            memcpy(bufo + boffo, bufi + boffi, copysize);
             DkVirtualMemoryFree(bufi, ALIGN_UP(bufsize + boffi));
             bufi = NULL;
             DkVirtualMemoryFree(bufo, ALIGN_UP(bufsize + boffo));
diff --git a/Pal/src/host/Linux-SGX/enclave_ocalls.c b/Pal/src/host/Linux-SGX/enclave_ocalls.c
index ebaca7d..a6c0e8a 100644
--- a/Pal/src/host/Linux-SGX/enclave_ocalls.c
+++ b/Pal/src/host/Linux-SGX/enclave_ocalls.c
@@ -791,30 +791,35 @@ int ocall_sock_send (int sockfd, const void * buf, unsigned int count,
     void * obuf = NULL;
     ms_ocall_sock_send_t * ms;
 
-    if ((count + addrlen) > PRESET_PAGESIZE) {
-        retval = ocall_alloc_untrusted(ALLOC_ALIGNUP(count), &obuf);
-        if (IS_ERR(retval))
-            return retval;
-    }
+    if (!buf)
+        return -EINVAL;
 
     ms = sgx_alloc_on_ustack(sizeof(*ms));
-    if (!ms) {
-        retval = -EPERM;
-        goto out;
-    }
+    if (!ms)
+        return -EPERM;
 
     ms->ms_sockfd = sockfd;
     ms->ms_count = count;
     ms->ms_addrlen = addrlen;
     ms->ms_addr = addr ? sgx_copy_to_ustack(addr, addrlen) : NULL;
-    if (obuf) {
+
+    if (sgx_is_completely_outside_enclave(buf, count)) {
+        ms->ms_buf = buf;
+    } else if (!sgx_is_completely_within_enclave(buf, count)) {
+        retval = -EPERM;
+        goto out;
+    } else if ((count + addrlen) > PRESET_PAGESIZE) {
+        retval = ocall_alloc_untrusted(ALLOC_ALIGNUP(count), &obuf);
+        if (IS_ERR(retval))
+            goto out;
+
         ms->ms_buf = obuf;
         memcpy(obuf, buf, count);
     } else {
         ms->ms_buf = sgx_copy_to_ustack(buf, count);
     }
 
-    if (!ms->ms_buf || (addr && !ms->ms_addr)) {
+    if (addr && !ms->ms_addr) {
         retval = -EPERM;
         goto out;
     }

```

**Comment by dimakuv** [comment]
Thanks, @pangzi85480! Indeed, I overlooked the check in `sgx_copy_to_ustack()`. I like your second variant of the patch. I will submit a PR with this now.

P.S. The only issue with your second patch is that you perform a second OCALL (`ocall_alloc_untrusted`) during your first OCALL (`ocall_sock_send`). This breaks our untrusted per-thread stack because it doesn't allow nested frames (for performance and simplicity reasons). So the code you removed in the very beginning of the function and moved lower was put there on purpose.

**Comment by dimakuv** [comment]
@pangzi85480, could you check https://github.com/oscarlab/graphene/pull/1000 and, if correct, put LGTM in Reviewable?

**Comment by pangzi85480** [comment]
> @pangzi85480, could you check #1000 and, if correct, put LGTM in Reviewable?

Done. 
I closed this issue, and thank you for reminding me about the problem of nested frames.
